include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, também a primeira tinha ordenanças de culto divino, e um santuário terrestre.

[[v58-9-2]]

^<<v58-9-2,2>>^ Porque um tabernáculo estava preparado, o primeiro, em que havia o candeeiro, e a mesa, e os pães da proposição; ao que se chama o santuário.

[[v58-9-3]]

^<<v58-9-3,3>>^ Mas depois do segundo véu estava o tabernáculo que se chama o santo dos santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ Que tinha o incensário de ouro, e a arca da aliança, coberta de ouro toda em redor; em que estava um vaso de ouro, que continha o maná, e a vara de Arão, que tinha florescido, e as tábuas da aliança;

[[v58-9-5]]

^<<v58-9-5,5>>^ E sobre a arca os querubins da glória, que faziam sombra no propiciatório; das quais coisas não falaremos agora particularmente.

[[v58-9-6]]

^<<v58-9-6,6>>^ Ora, estando estas coisas assim preparadas, a todo o tempo entravam os sacerdotes no primeiro tabernáculo, cumprindo os serviços;

[[v58-9-7]]

^<<v58-9-7,7>>^ Mas, no segundo, só o sumo sacerdote, uma vez no ano, não sem sangue, que oferecia por si mesmo e pelas culpas do povo;

[[v58-9-8]]

^<<v58-9-8,8>>^ Dando nisto a entender o Espírito Santo que ainda o caminho do santuário não estava descoberto enquanto se conservava em pé o primeiro tabernáculo,

[[v58-9-9]]

^<<v58-9-9,9>>^ Que é uma alegoria para o tempo presente, em que se oferecem dons e sacrifícios que, quanto à consciência, não podem aperfeiçoar aquele que faz o serviço;

[[v58-9-10]]

^<<v58-9-10,10>>^ Consistindo somente em comidas, e bebidas, e várias abluções e justificações da carne, impostas até ao tempo da correção.

[[v58-9-11]]

^<<v58-9-11,11>>^ Mas, vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação,

[[v58-9-12]]

^<<v58-9-12,12>>^ Nem por sangue de bodes e bezerros, mas por seu próprio sangue, entrou uma vez no santuário, havendo efetuado uma eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Porque, se o sangue dos touros e bodes, e a cinza de uma novilha esparzida sobre os imundos, os santifica, quanto à purificação da carne,

[[v58-9-14]]

^<<v58-9-14,14>>^ Quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu a si mesmo imaculado a Deus, purificará as vossas consciências das obras mortas, para servirdes ao Deus vivo?

[[v58-9-15]]

^<<v58-9-15,15>>^ E por isso é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.

[[v58-9-16]]

^<<v58-9-16,16>>^ Porque onde há testamento, é necessário que intervenha a morte do testador.

[[v58-9-17]]

^<<v58-9-17,17>>^ Porque um testamento tem força onde houve morte; ou terá ele algum valor enquanto o testador vive?

[[v58-9-18]]

^<<v58-9-18,18>>^ Por isso também o primeiro não foi consagrado sem sangue;

[[v58-9-19]]

^<<v58-9-19,19>>^ Porque, havendo Moisés anunciado a todo o povo todos os mandamentos segundo a lei, tomou o sangue dos bezerros e dos bodes, com água, lã purpúrea e hissopo, e aspergiu tanto o mesmo livro como todo o povo,

[[v58-9-20]]

^<<v58-9-20,20>>^ Dizendo: Este é o sangue do testamento que Deus vos tem mandado.

[[v58-9-21]]

^<<v58-9-21,21>>^ E semelhantemente aspergiu com sangue o tabernáculo e todos os vasos do ministério.

[[v58-9-22]]

^<<v58-9-22,22>>^ E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.

[[v58-9-23]]

^<<v58-9-23,23>>^ De sorte que era bem necessário que as figuras das coisas que estão no céu assim se purificassem; mas as próprias coisas celestiais com sacrifícios melhores do que estes.

[[v58-9-24]]

^<<v58-9-24,24>>^ Porque Cristo não entrou num santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para agora comparecer por nós perante a face de Deus;

[[v58-9-25]]

^<<v58-9-25,25>>^ Nem também para a si mesmo se oferecer muitas vezes, como o sumo sacerdote cada ano entra no santuário com sangue alheio;

[[v58-9-26]]

^<<v58-9-26,26>>^ De outra maneira, necessário lhe fora padecer muitas vezes desde a fundação do mundo. Mas agora na consumação dos séculos uma vez se manifestou, para aniquilar o pecado pelo sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, como aos homens está ordenado morrerem uma vez, vindo depois disso o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ Assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para salvação.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]