include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v58-8-1]]

^<<v58-8-1,1>>^ Ora, a suma do que temos dito é que temos um sumo sacerdote tal, que está assentado nos céus à destra do trono da majestade,

[[v58-8-2]]

^<<v58-8-2,2>>^ Ministro do santuário, e do verdadeiro tabernáculo, o qual o Senhor fundou, e não o homem.

[[v58-8-3]]

^<<v58-8-3,3>>^ Porque todo o sumo sacerdote é constituído para oferecer dons e sacrifícios; por isso era necessário que este também tivesse alguma coisa que oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Ora, se ele estivesse na terra, nem tão pouco sacerdote seria, havendo ainda sacerdotes que oferecem dons segundo a lei,

[[v58-8-5]]

^<<v58-8-5,5>>^ Os quais servem de exemplo e sombra das coisas celestiais, como Moisés divinamente foi avisado, estando já para acabar o tabernáculo; porque foi dito: Olha, faze tudo conforme o modelo que no monte se te mostrou.

[[v58-8-6]]

^<<v58-8-6,6>>^ Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de uma melhor aliança que está confirmada em melhores promessas.

[[v58-8-7]]

^<<v58-8-7,7>>^ Porque, se aquela primeira fora irrepreensível, nunca se teria buscado lugar para a segunda.

[[v58-8-8]]

^<<v58-8-8,8>>^ Porque, repreendendo-os, lhes diz: Eis que virão dias, diz o Senhor, Em que com a casa de Israel e com a casa de Judá estabelecerei uma nova aliança,

[[v58-8-9]]

^<<v58-8-9,9>>^ Não segundo a aliança que fiz com seus pais No dia em que os tomei pela mão, para os tirar da terra do Egito;Como não permaneceram naquela minha aliança,Eu para eles não atentei, diz o Senhor.

[[v58-8-10]]

^<<v58-8-10,10>>^ Porque esta é a aliança que depois daqueles diasFarei com a casa de Israel, diz o Senhor; Porei as minhas leis no seu entendimento, E em seu coração as escreverei; E eu lhes serei por Deus, E eles me serão por povo;

[[v58-8-11]]

^<<v58-8-11,11>>^ E não ensinará cada um a seu próximo, Nem cada um ao seu irmão, dizendo: Conhece o Senhor; Porque todos me conhecerão, Desde o menor deles até ao maior.

[[v58-8-12]]

^<<v58-8-12,12>>^ Porque serei misericordioso para com suas iniqüidades, E de seus pecados e de suas prevaricações não me lembrarei mais.

[[v58-8-13]]

^<<v58-8-13,13>>^ Dizendo Nova aliança, envelheceu a primeira. Ora, o que foi tornado velho, e se envelhece, perto está de acabar.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]