include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-56-1]]

^<<v19-56-1,1>>^ Tem misericórdia de mim, ó Deus, porque o homem procura devorar-me; pelejando todo dia, me oprime.

[[v19-56-2]]

^<<v19-56-2,2>>^ Os meus inimigos procuram devorar-me todo dia; pois são muitos os que pelejam contra mim, ó Altíssimo.

[[v19-56-3]]

^<<v19-56-3,3>>^ Em qualquer tempo em que eu temer, confiarei em ti.

[[v19-56-4]]

^<<v19-56-4,4>>^ Em Deus louvarei a sua palavra, em Deus pus a minha confiança; não temerei o que me possa fazer a carne.

[[v19-56-5]]

^<<v19-56-5,5>>^ Todos os dias torcem as minhas palavras; todos os seus pensamentos são contra mim para o mal.

[[v19-56-6]]

^<<v19-56-6,6>>^ Ajuntam-se, escondem-se, marcam os meus passos, como aguardando a minha alma.

[[v19-56-7]]

^<<v19-56-7,7>>^ Porventura escaparão eles por meio da sua iniqüidade? Ó Deus, derruba os povos na tua ira!

[[v19-56-8]]

^<<v19-56-8,8>>^ Tu contas as minhas vagueações; põe as minhas lágrimas no teu odre. Não estão elas no teu livro?

[[v19-56-9]]

^<<v19-56-9,9>>^ Quando eu a ti clamar, então voltarão para trás os meus inimigos: isto sei eu, porque Deus é por mim.

[[v19-56-10]]

^<<v19-56-10,10>>^ Em Deus louvarei a sua palavra; no Senhor louvarei a sua palavra.

[[v19-56-11]]

^<<v19-56-11,11>>^ Em Deus tenho posto a minha confiança; não temerei o que me possa fazer o homem.

[[v19-56-12]]

^<<v19-56-12,12>>^ Os teus votos estão sobre mim, ó Deus; eu te renderei ações de graças;

[[v19-56-13]]

^<<v19-56-13,13>>^ Pois tu livraste a minha alma da morte; não livrarás os meus pés da queda, para andar diante de Deus na luz dos viventes?

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]