include::./index.adoc[]

[[v19-45-0]]
=== Salmos, 45
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-45-1]]

^<<v19-45-1,1>>^ O meu coração ferve com palavras boas, falo do que tenho feito no tocante ao Rei. A minha língua é a pena de um destro escritor.

[[v19-45-2]]

^<<v19-45-2,2>>^ Tu és mais formoso do que os filhos dos homens; a graça se derramou em teus lábios; por isso Deus te abençoou para sempre.

[[v19-45-3]]

^<<v19-45-3,3>>^ Cinge a tua espada à coxa, ó valente, com a tua glória e a tua majestade.

[[v19-45-4]]

^<<v19-45-4,4>>^ E neste teu esplendor cavalga prosperamente, por causa da verdade, da mansidão e da justiça; e a tua destra te ensinará coisas terríveis.

[[v19-45-5]]

^<<v19-45-5,5>>^ As tuas flechas são agudas no coração dos inimigos do rei, e por elas os povos caíram debaixo de ti.

[[v19-45-6]]

^<<v19-45-6,6>>^ O teu trono, ó Deus, é eterno e perpétuo; o cetro do teu reino é um cetro de eqüidade.

[[v19-45-7]]

^<<v19-45-7,7>>^ Tu amas a justiça e odeias a impiedade; por isso Deus, o teu Deus, te ungiu com óleo de alegria mais do que a teus companheiros.

[[v19-45-8]]

^<<v19-45-8,8>>^ Todas as tuas vestes cheiram a mirra e aloés e cássia, desde os palácios de marfim de onde te alegram.

[[v19-45-9]]

^<<v19-45-9,9>>^ As filhas dos reis estavam entre as tuas ilustres mulheres; à tua direita estava a rainha ornada de finíssimo ouro de Ofir.

[[v19-45-10]]

^<<v19-45-10,10>>^ Ouve, filha, e olha, e inclina os teus ouvidos; esquece-te do teu povo e da casa do teu pai.

[[v19-45-11]]

^<<v19-45-11,11>>^ Então o rei se afeiçoará da tua formosura, pois ele é teu Senhor; adora-o.

[[v19-45-12]]

^<<v19-45-12,12>>^ E a filha de Tiro estará ali com presentes; os ricos do povo suplicarão o teu favor.

[[v19-45-13]]

^<<v19-45-13,13>>^ A filha do rei é toda ilustre lá dentro; o seu vestido é entretecido de ouro.

[[v19-45-14]]

^<<v19-45-14,14>>^ Levá-la-ão ao rei com vestidos bordados; as virgens que a acompanham a trarão a ti.

[[v19-45-15]]

^<<v19-45-15,15>>^ Com alegria e regozijo as trarão; elas entrarão no palácio do rei.

[[v19-45-16]]

^<<v19-45-16,16>>^ Em lugar de teus pais estarão teus filhos; deles farás príncipes sobre toda a terra.

[[v19-45-17]]

^<<v19-45-17,17>>^ Farei lembrado o teu nome de geração em geração; por isso os povos te louvarão eternamente.

'''

xref:019-salmos/019-salmos-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-salmos/019-salmos-046.adoc#v19-46-0[Próximo Capítulo &#62;]