include::./index.adoc[]

[[v19-77-0]]
=== Salmos, 77
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-77-1]]

^<<v19-77-1,1>>^ Clamei a Deus com a minha voz, a Deus levantei a minha voz, e ele inclinou para mim os ouvidos.

[[v19-77-2]]

^<<v19-77-2,2>>^ No dia da minha angústia busquei ao Senhor; a minha mão se estendeu de noite, e não cessava; a minha alma recusava ser consolada.

[[v19-77-3]]

^<<v19-77-3,3>>^ Lembrava-me de Deus, e me perturbei; queixava-me, e o meu espírito desfalecia. (Selá.)

[[v19-77-4]]

^<<v19-77-4,4>>^ Sustentaste os meus olhos acordados; estou tão perturbado que não posso falar.

[[v19-77-5]]

^<<v19-77-5,5>>^ Considerava os dias da antiguidade, os anos dos tempos antigos.

[[v19-77-6]]

^<<v19-77-6,6>>^ De noite chamei à lembrança o meu cântico; meditei em meu coração, e o meu espírito esquadrinhou.

[[v19-77-7]]

^<<v19-77-7,7>>^ Rejeitará o Senhor para sempre e não tornará a ser favorável?

[[v19-77-8]]

^<<v19-77-8,8>>^ Cessou para sempre a sua benignidade? Acabou-se já a promessa de geração em geração?

[[v19-77-9]]

^<<v19-77-9,9>>^ Esqueceu-se Deus de ter misericórdia? Ou encerrou ele as suas misericórdias na sua ira? (Selá.)

[[v19-77-10]]

^<<v19-77-10,10>>^ E eu disse: Isto é enfermidade minha; mas eu me lembrarei dos anos da destra do Altíssimo.

[[v19-77-11]]

^<<v19-77-11,11>>^ Eu me lembrarei das obras do Senhor; certamente que eu me lembrarei das tuas maravilhas da antiguidade.

[[v19-77-12]]

^<<v19-77-12,12>>^ Meditarei também em todas as tuas obras, e falarei dos teus feitos.

[[v19-77-13]]

^<<v19-77-13,13>>^ O teu caminho, ó Deus, está no santuário. Quem é Deus tão grande como o nosso Deus?

[[v19-77-14]]

^<<v19-77-14,14>>^ Tu és o Deus que fazes maravilhas; tu fizeste notória a tua força entre os povos.

[[v19-77-15]]

^<<v19-77-15,15>>^ Com o teu braço remiste o teu povo, os filhos de Jacó e de José. (Selá.)

[[v19-77-16]]

^<<v19-77-16,16>>^ As águas te viram, ó Deus, as águas te viram, e tremeram; os abismos também se abalaram.

[[v19-77-17]]

^<<v19-77-17,17>>^ As nuvens lançaram água, os céus deram um som; as tuas flechas correram duma para outra parte.

[[v19-77-18]]

^<<v19-77-18,18>>^ A voz do teu trovão estava no céu; os relâmpagos iluminaram o mundo; a terra se abalou e tremeu.

[[v19-77-19]]

^<<v19-77-19,19>>^ O teu caminho é no mar, e as tuas veredas nas águas grandes, e os teus passos não são conhecidos.

[[v19-77-20]]

^<<v19-77-20,20>>^ Guiaste o teu povo, como a um rebanho, pela mão de Moisés e de Arão.

'''

xref:019-salmos/019-salmos-076.adoc#v19-76-0[&#60; Capítulo Anterior] | <<v19-77-0,Topo>> | xref:019-salmos/019-salmos-078.adoc#v19-78-0[Próximo Capítulo &#62;]