include::./index.adoc[]

[[v19-83-0]]
=== Salmos, 83
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-83-1]]

^<<v19-83-1,1>>^ Ó Deus, não estejas em silêncio; não te cales, nem te aquietes, ó Deus,

[[v19-83-2]]

^<<v19-83-2,2>>^ Porque eis que teus inimigos fazem tumulto, e os que te odeiam levantaram a cabeça.

[[v19-83-3]]

^<<v19-83-3,3>>^ Tomaram astuto conselho contra o teu povo, e consultaram contra os teus escondidos.

[[v19-83-4]]

^<<v19-83-4,4>>^ Disseram: Vinde, e desarraiguemo-los para que não sejam nação, nem haja mais memória do nome de Israel.

[[v19-83-5]]

^<<v19-83-5,5>>^ Porque consultaram juntos e unânimes; eles se unem contra ti:

[[v19-83-6]]

^<<v19-83-6,6>>^ As tendas de Edom, e dos ismaelitas, de Moabe, e dos agarenos,

[[v19-83-7]]

^<<v19-83-7,7>>^ De Gebal, e de Amom, e de Amaleque, a Filístia, com os moradores de Tiro;

[[v19-83-8]]

^<<v19-83-8,8>>^ Também a Assíria se ajuntou com eles; foram ajudar aos filhos de Ló. (Selá.)

[[v19-83-9]]

^<<v19-83-9,9>>^ Faze-lhes como aos midianitas; como a Sísera, como a Jabim na ribeira de Quisom;

[[v19-83-10]]

^<<v19-83-10,10>>^ Os quais pereceram em Endor; tornaram-se como estrume para a terra.

[[v19-83-11]]

^<<v19-83-11,11>>^ Faze aos seus nobres como a Orebe, e como a Zeebe; e a todos os seus príncipes, como a Zebá e como a Zalmuna,

[[v19-83-12]]

^<<v19-83-12,12>>^ Que disseram: Tomemos para nós as casas de Deus em possessão.

[[v19-83-13]]

^<<v19-83-13,13>>^ Deus meu, faze-os como um tufão, como a aresta diante do vento.

[[v19-83-14]]

^<<v19-83-14,14>>^ Como o fogo que queima um bosque, e como a chama que incendeia as brenhas,

[[v19-83-15]]

^<<v19-83-15,15>>^ Assim os persegue com a tua tempestade, e os assombra com o teu torvelinho.

[[v19-83-16]]

^<<v19-83-16,16>>^ Encham-se de vergonha as suas faces, para que busquem o teu nome, Senhor.

[[v19-83-17]]

^<<v19-83-17,17>>^ Confundam-se e assombrem-se perpetuamente; envergonhem-se, e pereçam,

[[v19-83-18]]

^<<v19-83-18,18>>^ Para que saibam que tu, a quem só pertence o nome de Senhor, és o Altíssimo sobre toda a terra.

'''

xref:019-salmos/019-salmos-082.adoc#v19-82-0[&#60; Capítulo Anterior] | <<v19-83-0,Topo>> | xref:019-salmos/019-salmos-084.adoc#v19-84-0[Próximo Capítulo &#62;]