include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-9-1]]

^<<v19-9-1,1>>^ Eu te louvarei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas.

[[v19-9-2]]

^<<v19-9-2,2>>^ Em ti me alegrarei e saltarei de prazer; cantarei louvores ao teu nome, ó Altíssimo.

[[v19-9-3]]

^<<v19-9-3,3>>^ Porquanto os meus inimigos retornaram, caíram e pereceram diante da tua face.

[[v19-9-4]]

^<<v19-9-4,4>>^ Pois tu tens sustentado o meu direito e a minha causa; tu te assentaste no tribunal, julgando justamente;.

[[v19-9-5]]

^<<v19-9-5,5>>^ Repreendeste as nações, destruíste os ímpios; apagaste o seu nome para sempre e eternamente.

[[v19-9-6]]

^<<v19-9-6,6>>^ Oh! inimigo! acabaram-se para sempre as assolações; e tu arrasaste as cidades, e a sua memória pereceu com elas.

[[v19-9-7]]

^<<v19-9-7,7>>^ Mas o Senhor está assentado perpetuamente; já preparou o seu tribunal para julgar.

[[v19-9-8]]

^<<v19-9-8,8>>^ Ele mesmo julgará o mundo com justiça; exercerá juízo sobre povos com retidão.

[[v19-9-9]]

^<<v19-9-9,9>>^ O Senhor será também um alto refúgio para o oprimido; um alto refúgio em tempos de angústia.

[[v19-9-10]]

^<<v19-9-10,10>>^ Em ti confiarão os que conhecem o teu nome; porque tu, Senhor, nunca desamparaste os que te buscam.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantai louvores ao Senhor, que habita em Sião; anunciai entre os povos os seus feitos.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois quando inquire do derramamento de sangue, lembra-se deles: não se esquece do clamor dos aflitos.

[[v19-9-13]]

^<<v19-9-13,13>>^ Tem misericórdia de mim, Senhor, olha para a minha aflição, causada por aqueles que me odeiam; tu que me levantas das portas da morte;.

[[v19-9-14]]

^<<v19-9-14,14>>^ Para que eu conte todos os teus louvores nas portas da filha de Sião, e me alegre na tua salvação.

[[v19-9-15]]

^<<v19-9-15,15>>^ Os gentios enterraram-se na cova que fizeram; na rede que ocultaram ficou preso o seu pé.

[[v19-9-16]]

^<<v19-9-16,16>>^ O Senhor é conhecido pelo juízo que fez; enlaçado foi o ímpio nas obras de suas mãos. (Higaiom; Selá.).

[[v19-9-17]]

^<<v19-9-17,17>>^ Os ímpios serão lançados no inferno, e todas as nações que se esquecem de Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ Porque o necessitado não será esquecido para sempre, nem a expectação dos pobres perecerá perpetuamente.

[[v19-9-19]]

^<<v19-9-19,19>>^ Levanta-te, Senhor; não prevaleça o homem; sejam julgados os gentios diante da tua face.

[[v19-9-20]]

^<<v19-9-20,20>>^ Põe-os em medo, Senhor, para que saibam as nações que são formadas por meros homens. (Selá.).

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]