include::./index.adoc[]

[[v19-98-0]]
=== Salmos, 98
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-98-1]]

^<<v19-98-1,1>>^ Cantai ao SENHOR um cântico novo, porque fez maravilhas; a sua destra e o seu braço santo lhe alcançaram a salvação.

[[v19-98-2]]

^<<v19-98-2,2>>^ O Senhor fez notória a sua salvação, manifestou a sua justiça perante os olhos dos gentios.

[[v19-98-3]]

^<<v19-98-3,3>>^ Lembrou-se da sua benignidade e da sua verdade para com a casa de Israel; todas as extremidades da terra viram a salvação do nosso Deus.

[[v19-98-4]]

^<<v19-98-4,4>>^ Exultai no Senhor toda a terra; exclamai e alegrai-vos de prazer, e cantai louvores.

[[v19-98-5]]

^<<v19-98-5,5>>^ Cantai louvores ao Senhor com a harpa; com a harpa e a voz do canto.

[[v19-98-6]]

^<<v19-98-6,6>>^ Com trombetas e som de cornetas, exultai perante a face do Senhor, do Rei.

[[v19-98-7]]

^<<v19-98-7,7>>^ Brame o mar e a sua plenitude; o mundo, e os que nele habitam.

[[v19-98-8]]

^<<v19-98-8,8>>^ Os rios batam as palmas; regozijem-se também as montanhas,

[[v19-98-9]]

^<<v19-98-9,9>>^ Perante a face do Senhor, porque vem a julgar a terra; com justiça julgará o mundo, e o povo com eqüidade.

'''

xref:019-salmos/019-salmos-097.adoc#v19-97-0[&#60; Capítulo Anterior] | <<v19-98-0,Topo>> | xref:019-salmos/019-salmos-099.adoc#v19-99-0[Próximo Capítulo &#62;]