include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-108-1]]

^<<v19-108-1,1>>^ Preparado está o meu coração, ó Deus; cantarei e darei louvores até com a minha glória.

[[v19-108-2]]

^<<v19-108-2,2>>^ Despertai, saltério e harpa; eu mesmo despertarei ao romper da alva.

[[v19-108-3]]

^<<v19-108-3,3>>^ Louvar-te-ei entre os povos, Senhor, e a ti cantarei louvores entre as nações.

[[v19-108-4]]

^<<v19-108-4,4>>^ Porque a tua benignidade se estende até aos céus, e a tua verdade chega até às mais altas nuvens.

[[v19-108-5]]

^<<v19-108-5,5>>^ Exalta-te sobre os céus, ó Deus, e a tua glória sobre toda a terra.

[[v19-108-6]]

^<<v19-108-6,6>>^ Para que sejam livres os teus amados, salva-nos com a tua destra, e ouve-nos.

[[v19-108-7]]

^<<v19-108-7,7>>^ Deus falou na sua santidade; eu me regozijarei; repartirei a Siquém, e medirei o vale de Sucote.

[[v19-108-8]]

^<<v19-108-8,8>>^ Meu é Gileade, meu é Manassés; e Efraim a força da minha cabeça, Judá o meu legislador.

[[v19-108-9]]

^<<v19-108-9,9>>^ Moabe a minha bacia de lavar; sobre Edom lançarei o meu sapato, sobre a Filístia jubilarei.

[[v19-108-10]]

^<<v19-108-10,10>>^ Quem me levará à cidade forte? Quem me guiará até Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Porventura não serás tu, ó Deus, que nos rejeitaste? E não sairás, ó Deus, com os nossos exércitos?

[[v19-108-12]]

^<<v19-108-12,12>>^ Dá-nos auxílio para sair da angústia, porque vão é o socorro da parte do homem.

[[v19-108-13]]

^<<v19-108-13,13>>^ Em Deus faremos proezas, pois ele calcará aos pés os nossos inimigos.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]