include::./index.adoc[]

[[v19-111-0]]
=== Salmos, 111
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-111-1]]

^<<v19-111-1,1>>^ Louvai ao SENHOR. Louvarei ao SENHOR de todo o meu coração, na assembléia dos justos e na congregação.

[[v19-111-2]]

^<<v19-111-2,2>>^ Grandes são as obras do Senhor, procuradas por todos os que nelas tomam prazer.

[[v19-111-3]]

^<<v19-111-3,3>>^ A sua obra tem glória e majestade, e a sua justiça permanece para sempre.

[[v19-111-4]]

^<<v19-111-4,4>>^ Fez com que as suas maravilhas fossem lembradas; piedoso e misericordioso é o Senhor.

[[v19-111-5]]

^<<v19-111-5,5>>^ Deu mantimento aos que o temem; lembrar-se-á sempre da sua aliança.

[[v19-111-6]]

^<<v19-111-6,6>>^ Anunciou ao seu povo o poder das suas obras, para lhe dar a herança dos gentios.

[[v19-111-7]]

^<<v19-111-7,7>>^ As obras das suas mãos são verdade e juízo, seguros todos os seus mandamentos.

[[v19-111-8]]

^<<v19-111-8,8>>^ Permanecem firmes para todo o sempre; e são feitos em verdade e retidão.

[[v19-111-9]]

^<<v19-111-9,9>>^ Redenção enviou ao seu povo; ordenou a sua aliança para sempre; santo e tremendo é o seu nome.

[[v19-111-10]]

^<<v19-111-10,10>>^ O temor do Senhor é o princípio da sabedoria; bom entendimento têm todos os que cumprem os seus mandamentos; o seu louvor permanece para sempre.

'''

xref:019-salmos/019-salmos-110.adoc#v19-110-0[&#60; Capítulo Anterior] | <<v19-111-0,Topo>> | xref:019-salmos/019-salmos-112.adoc#v19-112-0[Próximo Capítulo &#62;]