include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-76-1]]

^<<v19-76-1,1>>^ Conhecido é Deus em Judá; grande é o seu nome em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ E em Salém está o seu tabernáculo, e a sua morada em Sião.

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali quebrou as flechas do arco; o escudo, e a espada, e a guerra. (Selá.)

[[v19-76-4]]

^<<v19-76-4,4>>^ Tu és mais ilustre e glorioso do que os montes de caça.

[[v19-76-5]]

^<<v19-76-5,5>>^ Os que são ousados de coração são despojados; dormiram o seu sono; e nenhum dos homens de força achou as próprias mãos.

[[v19-76-6]]

^<<v19-76-6,6>>^ À tua repreensão, ó Deus de Jacó, carros e cavalos são lançados num sono profundo.

[[v19-76-7]]

^<<v19-76-7,7>>^ Tu, tu és temível; e quem subsistirá à tua vista, uma vez que te irares?

[[v19-76-8]]

^<<v19-76-8,8>>^ Desde os céus fizeste ouvir o teu juízo; a terra tremeu e se aquietou,

[[v19-76-9]]

^<<v19-76-9,9>>^ Quando Deus se levantou para fazer juízo, para livrar a todos os mansos da terra. (Selá.)

[[v19-76-10]]

^<<v19-76-10,10>>^ Certamente a cólera do homem redundará em teu louvor; o restante da cólera tu o restringirás.

[[v19-76-11]]

^<<v19-76-11,11>>^ Fazei votos, e pagai ao Senhor vosso Deus; tragam presentes, os que estão em redor dele, àquele que é temível.

[[v19-76-12]]

^<<v19-76-12,12>>^ Ele ceifará o espírito dos príncipes; é tremendo para com os reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]