include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-85-1]]

^<<v19-85-1,1>>^ Abençoaste, SENHOR, a tua terra; fizeste voltar o cativeiro de Jacó.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste a iniqüidade do teu povo; cobriste todos os seus pecados. (Selá.)

[[v19-85-3]]

^<<v19-85-3,3>>^ Fizeste cessar toda a tua indignação; desviaste-te do ardor da tua ira.

[[v19-85-4]]

^<<v19-85-4,4>>^ Torna-nos a trazer, ó Deus da nossa salvação, e faze cessar a tua ira de sobre nós.

[[v19-85-5]]

^<<v19-85-5,5>>^ Acaso estarás sempre irado contra nós? Estenderás a tua ira a todas as gerações?

[[v19-85-6]]

^<<v19-85-6,6>>^ Não tornarás a vivificar-nos, para que o teu povo se alegre em ti?

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos, Senhor, a tua misericórdia, e concede-nos a tua salvação.

[[v19-85-8]]

^<<v19-85-8,8>>^ Escutarei o que Deus, o Senhor, falar; porque falará de paz ao seu povo, e aos santos, para que não voltem à loucura.

[[v19-85-9]]

^<<v19-85-9,9>>^ Certamente que a salvação está perto daqueles que o temem, para que a glória habite na nossa terra.

[[v19-85-10]]

^<<v19-85-10,10>>^ A misericórdia e a verdade se encontraram; a justiça e a paz se beijaram.

[[v19-85-11]]

^<<v19-85-11,11>>^ A verdade brotará da terra, e a justiça olhará desde os céus.

[[v19-85-12]]

^<<v19-85-12,12>>^ Também o Senhor dará o que é bom, e a nossa terra dará o seu fruto.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça irá adiante dele, e nos porá no caminho das suas pisadas.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]