include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei a misericórdia e o juízo; a ti, SENHOR, cantarei.

[[v19-101-2]]

^<<v19-101-2,2>>^ Portar-me-ei com inteligência no caminho reto. Quando virás a mim? Andarei em minha casa com um coração sincero.

[[v19-101-3]]

^<<v19-101-3,3>>^ Não porei coisa má diante dos meus olhos. Odeio a obra daqueles que se desviam; não se me pegará a mim.

[[v19-101-4]]

^<<v19-101-4,4>>^ Um coração perverso se apartará de mim; não conhecerei o homem mau.

[[v19-101-5]]

^<<v19-101-5,5>>^ Aquele que murmura do seu próximo às escondidas, eu o destruirei; aquele que tem olhar altivo e coração soberbo, não suportarei.

[[v19-101-6]]

^<<v19-101-6,6>>^ Os meus olhos estarão sobre os fiéis da terra, para que se assentem comigo; o que anda num caminho reto, esse me servirá.

[[v19-101-7]]

^<<v19-101-7,7>>^ O que usa de engano não ficará dentro da minha casa; o que fala mentiras não estará firme perante os meus olhos.

[[v19-101-8]]

^<<v19-101-8,8>>^ Pela manhã destruirei todos os ímpios da terra, para desarraigar da cidade do Senhor todos os que praticam a iniqüidade.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]