include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-49-1]]

^<<v19-49-1,1>>^ Ouvi isto, vós todos os povos; inclinai os ouvidos, todos os moradores do mundo,

[[v19-49-2]]

^<<v19-49-2,2>>^ Tanto baixos como altos, tanto ricos como pobres.

[[v19-49-3]]

^<<v19-49-3,3>>^ A minha boca falará de sabedoria, e a meditação do meu coração será de entendimento.

[[v19-49-4]]

^<<v19-49-4,4>>^ Inclinarei os meus ouvidos a uma parábola; declararei o meu enigma na harpa.

[[v19-49-5]]

^<<v19-49-5,5>>^ Por que temerei eu nos dias maus, quando me cercar a iniqüidade dos que me armam ciladas?

[[v19-49-6]]

^<<v19-49-6,6>>^ Aqueles que confiam na sua fazenda, e se gloriam na multidão das suas riquezas,

[[v19-49-7]]

^<<v19-49-7,7>>^ Nenhum deles de modo algum pode remir a seu irmão, ou dar a Deus o resgate dele.

[[v19-49-8]]

^<<v19-49-8,8>>^ (Pois a redenção da sua alma é caríssima, e cessará para sempre),

[[v19-49-9]]

^<<v19-49-9,9>>^ Para que viva para sempre, e não veja corrupção.

[[v19-49-10]]

^<<v19-49-10,10>>^ Porque ele vê que os sábios morrem; perecem igualmente tanto o louco como o brutal, e deixam a outros os seus bens.

[[v19-49-11]]

^<<v19-49-11,11>>^ O seu pensamento interior é que as suas casas serão perpétuas e as suas habitações de geração em geração; dão às suas terras os seus próprios nomes.

[[v19-49-12]]

^<<v19-49-12,12>>^ Todavia o homem que está em honra não permanece; antes é como os animais, que perecem.

[[v19-49-13]]

^<<v19-49-13,13>>^ Este caminho deles é a sua loucura; contudo a sua posteridade aprova as suas palavras. (Selá.)

[[v19-49-14]]

^<<v19-49-14,14>>^ Como ovelhas são postos na sepultura; a morte se alimentará deles e os retos terão domínio sobre eles na manhã, e a sua formosura se consumirá na sepultura, a habitação deles.

[[v19-49-15]]

^<<v19-49-15,15>>^ Mas Deus remirá a minha alma do poder da sepultura, pois me receberá. (Selá.)

[[v19-49-16]]

^<<v19-49-16,16>>^ Não temas, quando alguém se enriquece, quando a glória da sua casa se engrandece.

[[v19-49-17]]

^<<v19-49-17,17>>^ Porque, quando morrer, nada levará consigo, nem a sua glória o acompanhará.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que na sua vida ele bendisse a sua alma; e os homens te louvarão, quando fizeres bem a ti mesmo,

[[v19-49-19]]

^<<v19-49-19,19>>^ Irá para a geração de seus pais; eles nunca verão a luz.

[[v19-49-20]]

^<<v19-49-20,20>>^ O homem que está em honra, e não tem entendimento, é semelhante aos animais, que perecem.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]