include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-97-1]]

^<<v19-97-1,1>>^ O SENHOR reina; regozije-se a terra; alegrem-se as muitas ilhas.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens e escuridão estão ao redor dele; justiça e juízo são a base do seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Um fogo vai adiante dele, e abrasa os seus inimigos em redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Os seus relâmpagos iluminam o mundo; a terra viu e tremeu.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes derretem como cera na presença do Senhor, na presença do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus anunciam a sua justiça, e todos os povos vêem a sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Confundidos sejam todos os que servem imagens de escultura, que se gloriam de ídolos; prostrai-vos diante dele todos os deuses.

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouviu e se alegrou; e os filhos de Judá se alegraram por causa da tua justiça, ó Senhor.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, Senhor, és o mais alto sobre toda a terra; tu és muito mais exaltado do que todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ Vós, que amais ao Senhor, odiai o mal. Ele guarda as almas dos seus santos; ele os livra das mãos dos ímpios.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz semeia-se para o justo, e a alegria para os retos de coração.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrai-vos, ó justos, no Senhor, e dai louvores à memória da sua santidade.

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]