include::./index.adoc[]

[[v19-64-0]]
=== Salmos, 64
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-64-1]]

^<<v19-64-1,1>>^ Ouve, ó Deus, a minha voz na minha oração; guarda a minha vida do temor do inimigo.

[[v19-64-2]]

^<<v19-64-2,2>>^ Esconde-me do secreto conselho dos maus, e do tumulto dos que praticam a iniqüidade.

[[v19-64-3]]

^<<v19-64-3,3>>^ Que afiaram as suas línguas como espadas; e armaram por suas flechas palavras amargas,

[[v19-64-4]]

^<<v19-64-4,4>>^ A fim de atirarem em lugar oculto ao que é íntegro; disparam sobre ele repentinamente, e não temem.

[[v19-64-5]]

^<<v19-64-5,5>>^ Firmam-se em mau intento; falam de armar laços secretamente, e dizem: Quem os verá?

[[v19-64-6]]

^<<v19-64-6,6>>^ Andam inquirindo malícias, inquirem tudo o que se pode inquirir; e ambos, o íntimo pensamento de cada um deles, e o coração, são profundos.

[[v19-64-7]]

^<<v19-64-7,7>>^ Mas Deus atirará sobre eles uma seta, e de repente ficarão feridos.

[[v19-64-8]]

^<<v19-64-8,8>>^ Assim eles farão com que as suas línguas tropecem contra si mesmos; todos aqueles que os virem, fugirão.

[[v19-64-9]]

^<<v19-64-9,9>>^ E todos os homens temerão, e anunciarão a obra de Deus; e considerarão prudentemente os feitos dele.

[[v19-64-10]]

^<<v19-64-10,10>>^ O justo se alegrará no Senhor, e confiará nele, e todos os retos de coração se gloriarão.

'''

xref:019-salmos/019-salmos-063.adoc#v19-63-0[&#60; Capítulo Anterior] | <<v19-64-0,Topo>> | xref:019-salmos/019-salmos-065.adoc#v19-65-0[Próximo Capítulo &#62;]