include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-58-1]]

^<<v19-58-1,1>>^ Acaso falais vós, deveras, ó congregação, a justiça? Julgais retamente, ó filhos dos homens?

[[v19-58-2]]

^<<v19-58-2,2>>^ Antes no coração forjais iniqüidades; sobre a terra pesais a violência das vossas mãos.

[[v19-58-3]]

^<<v19-58-3,3>>^ Alienam-se os ímpios desde a madre; andam errados desde que nasceram, falando mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ O seu veneno é semelhante ao veneno da serpente; são como a víbora surda, que tapa os ouvidos,

[[v19-58-5]]

^<<v19-58-5,5>>^ Para não ouvir a voz dos encantadores, do encantador sábio em encantamentos.

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra-lhes os dentes nas suas bocas; arranca, Senhor, os queixais aos filhos dos leões.

[[v19-58-7]]

^<<v19-58-7,7>>^ Escorram como águas que correm constantemente. Quando ele armar as suas flechas, fiquem feitas em pedaços.

[[v19-58-8]]

^<<v19-58-8,8>>^ Como a lesma se derrete, assim se vá cada um deles; como o aborto duma mulher, que nunca viu o sol.

[[v19-58-9]]

^<<v19-58-9,9>>^ Antes que as vossas panelas sintam o calor dos espinhos, como por um redemoinho os arrebatará ele, vivo e em indignação.

[[v19-58-10]]

^<<v19-58-10,10>>^ O justo se alegrará quando vir a vingança; lavará os seus pés no sangue do ímpio.

[[v19-58-11]]

^<<v19-58-11,11>>^ Então dirá o homem: Deveras há uma recompensa para o justo; deveras há um Deus que julga na terra.

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]