include::./index.adoc[]

[[v19-73-0]]
=== Salmos, 73
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-73-1]]

^<<v19-73-1,1>>^ Verdadeiramente bom é Deus para com Israel, para com os limpos de coração.

[[v19-73-2]]

^<<v19-73-2,2>>^ Quanto a mim, os meus pés quase que se desviaram; pouco faltou para que escorregassem os meus passos.

[[v19-73-3]]

^<<v19-73-3,3>>^ Pois eu tinha inveja dos néscios, quando via a prosperidade dos ímpios.

[[v19-73-4]]

^<<v19-73-4,4>>^ Porque não há apertos na sua morte, mas firme está a sua força.

[[v19-73-5]]

^<<v19-73-5,5>>^ Não se acham em trabalhos como outros homens, nem são afligidos como outros homens.

[[v19-73-6]]

^<<v19-73-6,6>>^ Por isso a soberba os cerca como um colar; vestem-se de violência como de adorno.

[[v19-73-7]]

^<<v19-73-7,7>>^ Os olhos deles estão inchados de gordura; eles têm mais do que o coração podia desejar.

[[v19-73-8]]

^<<v19-73-8,8>>^ São corrompidos e tratam maliciosamente de opressão; falam arrogantemente.

[[v19-73-9]]

^<<v19-73-9,9>>^ Põem as suas bocas contra os céus, e as suas línguas andam pela terra.

[[v19-73-10]]

^<<v19-73-10,10>>^ Por isso o povo dele volta aqui, e águas de copo cheio se lhes espremem.

[[v19-73-11]]

^<<v19-73-11,11>>^ E eles dizem: Como o sabe Deus? Há conhecimento no Altíssimo?

[[v19-73-12]]

^<<v19-73-12,12>>^ Eis que estes são ímpios, e prosperam no mundo; aumentam em riquezas.

[[v19-73-13]]

^<<v19-73-13,13>>^ Na verdade que em vão tenho purificado o meu coração; e lavei as minhas mãos na inocência.

[[v19-73-14]]

^<<v19-73-14,14>>^ Pois todo o dia tenho sido afligido, e castigado cada manhã.

[[v19-73-15]]

^<<v19-73-15,15>>^ Se eu dissesse: Falarei assim; eis que ofenderia a geração de teus filhos.

[[v19-73-16]]

^<<v19-73-16,16>>^ Quando pensava em entender isto, foi para mim muito doloroso;

[[v19-73-17]]

^<<v19-73-17,17>>^ Até que entrei no santuário de Deus; então entendi eu o fim deles.

[[v19-73-18]]

^<<v19-73-18,18>>^ Certamente tu os puseste em lugares escorregadios; tu os lanças em destruição.

[[v19-73-19]]

^<<v19-73-19,19>>^ Como caem na desolação, quase num momento! Ficam totalmente consumidos de terrores.

[[v19-73-20]]

^<<v19-73-20,20>>^ Como um sonho, quando se acorda, assim, ó Senhor, quando acordares, desprezarás a aparência deles.

[[v19-73-21]]

^<<v19-73-21,21>>^ Assim o meu coração se azedou, e sinto picadas nos meus rins.

[[v19-73-22]]

^<<v19-73-22,22>>^ Assim me embruteci, e nada sabia; fiquei como um animal perante ti.

[[v19-73-23]]

^<<v19-73-23,23>>^ Todavia estou de contínuo contigo; tu me sustentaste pela minha mão direita.

[[v19-73-24]]

^<<v19-73-24,24>>^ Guiar-me-ás com o teu conselho, e depois me receberás na glória.

[[v19-73-25]]

^<<v19-73-25,25>>^ Quem tenho eu no céu senão a ti? e na terra não há quem eu deseje além de ti.

[[v19-73-26]]

^<<v19-73-26,26>>^ A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração, e a minha porção para sempre.

[[v19-73-27]]

^<<v19-73-27,27>>^ Pois eis que os que se alongam de ti, perecerão; tu tens destruído todos aqueles que se desviam de ti.

[[v19-73-28]]

^<<v19-73-28,28>>^ Mas para mim, bom é aproximar-me de Deus; pus a minha confiança no Senhor DEUS, para anunciar todas as tuas obras.

'''

xref:019-salmos/019-salmos-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-salmos/019-salmos-074.adoc#v19-74-0[Próximo Capítulo &#62;]