include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-10-1]]

^<<v19-10-1,1>>^ Por que estás ao longe, SENHOR? Por que te escondes nos tempos de angústia?

[[v19-10-2]]

^<<v19-10-2,2>>^ Os ímpios na sua arrogância perseguem furiosamente o pobre; sejam apanhados nas ciladas que maquinaram.

[[v19-10-3]]

^<<v19-10-3,3>>^ Porque o ímpio gloria-se do desejo da sua alma; bendiz ao avarento, e renuncia ao Senhor.

[[v19-10-4]]

^<<v19-10-4,4>>^ Pela altivez do seu rosto o ímpio não busca a Deus; todas as suas cogitações são que não há Deus.

[[v19-10-5]]

^<<v19-10-5,5>>^ Os seus caminhos atormentam sempre; os teus juízos estão longe da vista dele, em grande altura, e despreza aos seus inimigos.

[[v19-10-6]]

^<<v19-10-6,6>>^ Diz em seu coração: Não serei abalado, porque nunca me verei na adversidade.

[[v19-10-7]]

^<<v19-10-7,7>>^ A sua boca está cheia de imprecações, de enganos e de astúcia; debaixo da sua língua há malícia e maldade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Põe-se de emboscada nas aldeias; nos lugares ocultos mata o inocente; os seus olhos estão ocultamente fixos sobre o pobre.

[[v19-10-9]]

^<<v19-10-9,9>>^ Arma ciladas no esconderijo, como o leão no seu covil; arma ciladas para roubar o pobre; rouba-o, prendendo-o na sua rede.

[[v19-10-10]]

^<<v19-10-10,10>>^ Encolhe-se, abaixa-se, para que os pobres caiam em suas fortes garras.

[[v19-10-11]]

^<<v19-10-11,11>>^ Diz em seu coração: Deus esqueceu-se, cobriu o seu rosto, e nunca isto verá.

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, Senhor. Ó Deus, levanta a tua mão; não te esqueças dos humildes.

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que blasfema o ímpio de Deus? dizendo no seu coração: Tu não o esquadrinharás?

[[v19-10-14]]

^<<v19-10-14,14>>^ Tu o viste, porque atentas para o trabalho e enfado, para o retribuir com tuas mãos; a ti o pobre se encomenda; tu és o auxílio do órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebra o braço do ímpio e malvado; busca a sua impiedade, até que nenhuma encontres.

[[v19-10-16]]

^<<v19-10-16,16>>^ O Senhor é Rei eterno; da sua terra perecerão os gentios.

[[v19-10-17]]

^<<v19-10-17,17>>^ Senhor, tu ouviste os desejos dos mansos; confortarás os seus corações; os teus ouvidos estarão abertos para eles;

[[v19-10-18]]

^<<v19-10-18,18>>^ Para fazer justiça ao órfão e ao oprimido, a fim de que o homem da terra não prossiga mais em usar da violência.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]