include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-53-1]]

^<<v19-53-1,1>>^ Disse o néscio no seu coração: Não há Deus. Têm-se corrompido, e cometido abominável iniqüidade; não há ninguém que faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Deus olhou desde os céus para os filhos dos homens, para ver se havia algum que tivesse entendimento e buscasse a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Desviaram-se todos, e juntamente se fizeram imundos; não há quem faça o bem, não, nem sequer um.

[[v19-53-4]]

^<<v19-53-4,4>>^ Acaso não têm conhecimento os que praticam a iniqüidade, os quais comem o meu povo como se comessem pão? Eles não invocaram a Deus.

[[v19-53-5]]

^<<v19-53-5,5>>^ Ali se acharam em grande temor, onde não havia temor, pois Deus espalhou os ossos daquele que te cercava; tu os confundiste, porque Deus os rejeitou.

[[v19-53-6]]

^<<v19-53-6,6>>^ Oh! se já de Sião viesse a salvação de Israel! Quando Deus fizer voltar os cativos do seu povo, então se regozijará Jacó e se alegrará Israel.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]