include::./index.adoc[]

[[v19-94-0]]
=== Salmos, 94
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-94-1]]

^<<v19-94-1,1>>^ Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente.

[[v19-94-2]]

^<<v19-94-2,2>>^ Exalta-te, tu, que és juiz da terra; dá a paga aos soberbos.

[[v19-94-3]]

^<<v19-94-3,3>>^ Até quando os ímpios, Senhor, até quando os ímpios saltarão de prazer?

[[v19-94-4]]

^<<v19-94-4,4>>^ Até quando proferirão, e falarão coisas duras, e se gloriarão todos os que praticam a iniqüidade?

[[v19-94-5]]

^<<v19-94-5,5>>^ Reduzem a pedaços o teu povo, ó Senhor, e afligem a tua herança.

[[v19-94-6]]

^<<v19-94-6,6>>^ Matam a viúva e o estrangeiro, e ao órfão tiram a vida.

[[v19-94-7]]

^<<v19-94-7,7>>^ Contudo dizem: O Senhor não o verá; nem para isso atenderá o Deus de Jacó.

[[v19-94-8]]

^<<v19-94-8,8>>^ Atendei, ó brutais dentre o povo; e vós, loucos, quando sereis sábios?

[[v19-94-9]]

^<<v19-94-9,9>>^ Aquele que fez o ouvido não ouvirá? E o que formou o olho, não verá?

[[v19-94-10]]

^<<v19-94-10,10>>^ Aquele que argüi os gentios não castigará? E o que ensina ao homem o conhecimento, não saberá?

[[v19-94-11]]

^<<v19-94-11,11>>^ O Senhor conhece os pensamentos do homem, que são vaidade.

[[v19-94-12]]

^<<v19-94-12,12>>^ Bem-aventurado é o homem a quem tu castigas, ó Senhor, e a quem ensinas a tua lei;

[[v19-94-13]]

^<<v19-94-13,13>>^ Para lhe dares descanso dos dias maus, até que se abra a cova para o ímpio.

[[v19-94-14]]

^<<v19-94-14,14>>^ Pois o Senhor não rejeitará o seu povo, nem desamparará a sua herança.

[[v19-94-15]]

^<<v19-94-15,15>>^ Mas o juízo voltará à retidão, e segui-lo-ão todos os retos de coração.

[[v19-94-16]]

^<<v19-94-16,16>>^ Quem será por mim contra os malfeitores? Quem se porá por mim contra os que praticam a iniqüidade?

[[v19-94-17]]

^<<v19-94-17,17>>^ Se o Senhor não tivera ido em meu auxílio, a minha alma quase que teria ficado no silêncio.

[[v19-94-18]]

^<<v19-94-18,18>>^ Quando eu disse: O meu pé vacila; a tua benignidade, Senhor, me susteve.

[[v19-94-19]]

^<<v19-94-19,19>>^ Na multidão dos meus pensamentos dentro de mim, as tuas consolações recrearam a minha alma.

[[v19-94-20]]

^<<v19-94-20,20>>^ Porventura o trono de iniqüidade te acompanha, o qual forja o mal por uma lei?

[[v19-94-21]]

^<<v19-94-21,21>>^ Eles se ajuntam contra a alma do justo, e condenam o sangue inocente.

[[v19-94-22]]

^<<v19-94-22,22>>^ Mas o Senhor é a minha defesa; e o meu Deus é a rocha do meu refúgio.

[[v19-94-23]]

^<<v19-94-23,23>>^ E trará sobre eles a sua própria iniqüidade; e os destruirá na sua própria malícia; o Senhor nosso Deus os destruirá.

'''

xref:019-salmos/019-salmos-093.adoc#v19-93-0[&#60; Capítulo Anterior] | <<v19-94-0,Topo>> | xref:019-salmos/019-salmos-095.adoc#v19-95-0[Próximo Capítulo &#62;]