include::./index.adoc[]

[[v19-110-0]]
=== Salmos, 110
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-110-1]]

^<<v19-110-1,1>>^ Disse o SENHOR ao meu Senhor: Assenta-te à minha mão direita, até que ponha os teus inimigos por escabelo dos teus pés.

[[v19-110-2]]

^<<v19-110-2,2>>^ O Senhor enviará o cetro da tua fortaleza desde Sião, dizendo: Domina no meio dos teus inimigos.

[[v19-110-3]]

^<<v19-110-3,3>>^ O teu povo será mui voluntário no dia do teu poder; nos ornamentos de santidade, desde a madre da alva, tu tens o orvalho da tua mocidade.

[[v19-110-4]]

^<<v19-110-4,4>>^ Jurou o Senhor, e não se arrependerá: tu és um sacerdote eterno, segundo a ordem de Melquisedeque.

[[v19-110-5]]

^<<v19-110-5,5>>^ O Senhor, à tua direita, ferirá os reis no dia da sua ira.

[[v19-110-6]]

^<<v19-110-6,6>>^ Julgará entre os gentios; tudo encherá de corpos mortos; ferirá os cabeças de muitos países.

[[v19-110-7]]

^<<v19-110-7,7>>^ Beberá do ribeiro no caminho, por isso exaltará a cabeça.

'''

xref:019-salmos/019-salmos-109.adoc#v19-109-0[&#60; Capítulo Anterior] | <<v19-110-0,Topo>> | xref:019-salmos/019-salmos-111.adoc#v19-111-0[Próximo Capítulo &#62;]