include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-99-1]]

^<<v19-99-1,1>>^ O SENHOR reina; tremam os povos. Ele está assentado entre os querubins; comova-se a terra.

[[v19-99-2]]

^<<v19-99-2,2>>^ O Senhor é grande em Sião, e mais alto do que todos os povos.

[[v19-99-3]]

^<<v19-99-3,3>>^ Louvem o teu nome, grande e tremendo, pois é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ Também o poder do Rei ama o juízo; tu firmas a eqüidade, fazes juízo e justiça em Jacó.

[[v19-99-5]]

^<<v19-99-5,5>>^ Exaltai ao Senhor nosso Deus, e prostrai-vos diante do escabelo de seus pés, pois é santo.

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão, entre os seus sacerdotes, e Samuel entre os que invocam o seu nome, clamavam ao Senhor, e Ele lhes respondia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Na coluna de nuvem lhes falava; eles guardaram os seus testemunhos, e os estatutos que lhes dera.

[[v19-99-8]]

^<<v19-99-8,8>>^ Tu os escutaste, Senhor nosso Deus: tu foste um Deus que lhes perdoaste, ainda que tomaste vingança dos seus feitos.

[[v19-99-9]]

^<<v19-99-9,9>>^ Exaltai ao Senhor nosso Deus e adorai-o no seu monte santo, pois o Senhor nosso Deus é santo.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]