include::./index.adoc[]

[[v19-28-0]]
=== Salmos, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-28-1]]

^<<v19-28-1,1>>^ A ti clamarei, ó Senhor, Rocha minha; não emudeças para comigo; não aconteça, cal ando-te tu para comigo, que eu fique semelhante aos que descem ao abismo.

[[v19-28-2]]

^<<v19-28-2,2>>^ Ouve a voz das minhas súplicas, quando a ti clamar, quando levantar as minhas mãos para o teu santo oráculo.

[[v19-28-3]]

^<<v19-28-3,3>>^ Não me arrastes com os ímpios e com os que praticam a iniqüidade; que falam de paz ao seu próximo, mas têm mal nos seus corações.

[[v19-28-4]]

^<<v19-28-4,4>>^ Dá-lhes segundo as suas obras e segundo a malícia dos seus esforços; dá-lhes conforme a obra das suas mãos; torna-lhes a sua recompensa.

[[v19-28-5]]

^<<v19-28-5,5>>^ Porquanto não atentam às obras do Senhor, nem à obra das suas mãos; pois que ele os derrubará e não os reedificará.

[[v19-28-6]]

^<<v19-28-6,6>>^ Bendito seja o Senhor, porque ouviu a voz das minhas súplicas.

[[v19-28-7]]

^<<v19-28-7,7>>^ O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido; assim o meu coração salta de prazer, e com o meu canto o louvarei.

[[v19-28-8]]

^<<v19-28-8,8>>^ O Senhor é a força do seu povo; também é a força salvadora do seu ungido.

[[v19-28-9]]

^<<v19-28-9,9>>^ Salva o teu povo, e abençoa a tua herança; e apascenta-os e exalta-os para sempre.

'''

xref:019-salmos/019-salmos-027.adoc#v19-27-0[&#60; Capítulo Anterior] | <<v19-28-0,Topo>> | xref:019-salmos/019-salmos-029.adoc#v19-29-0[Próximo Capítulo &#62;]