include::./index.adoc[]

[[v19-39-0]]
=== Salmos, 39
// acf ?, ACF - Almeida Corrigida Fiel

[[v19-39-1]]

^<<v19-39-1,1>>^ Eu disse: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a boca com um freio, enquanto o ímpio estiver diante de mim.

[[v19-39-2]]

^<<v19-39-2,2>>^ Com o silêncio fiquei mudo; calava-me mesmo acerca do bem, e a minha dor se agravou.

[[v19-39-3]]

^<<v19-39-3,3>>^ Esquentou-se-me o coração dentro de mim; enquanto eu meditava se acendeu um fogo; então falei com a minha língua:

[[v19-39-4]]

^<<v19-39-4,4>>^ Faze-me conhecer, Senhor, o meu fim, e a medida dos meus dias qual é, para que eu sinta quanto sou frágil.

[[v19-39-5]]

^<<v19-39-5,5>>^ Eis que fizeste os meus dias como a palmos; o tempo da minha vida é como nada diante de ti; na verdade, todo homem, por mais firme que esteja, é totalmente vaidade. (Selá.)

[[v19-39-6]]

^<<v19-39-6,6>>^ Na verdade, todo homem anda numa và aparência; na verdade, em vão se inquietam; amontoam riquezas, e não sabem quem as levará.

[[v19-39-7]]

^<<v19-39-7,7>>^ Agora, pois, Senhor, que espero eu? A minha esperança está em ti.

[[v19-39-8]]

^<<v19-39-8,8>>^ Livra-me de todas as minhas transgressões; não me faças o opróbrio dos loucos.

[[v19-39-9]]

^<<v19-39-9,9>>^ Emudeci; não abro a minha boca, porquanto tu o fizeste.

[[v19-39-10]]

^<<v19-39-10,10>>^ Tira de sobre mim a tua praga; estou desfalecido pelo golpe da tua mão.

[[v19-39-11]]

^<<v19-39-11,11>>^ Quando castigas o homem, com repreensões por causa da iniqüidade, fazes com que a sua beleza se consuma como a traça; assim todo homem é vaidade. (Selá.)

[[v19-39-12]]

^<<v19-39-12,12>>^ Ouve, Senhor, a minha oração, e inclina os teus ouvidos ao meu clamor; não te cales perante as minhas lágrimas, porque sou um estrangeiro contigo e peregrino, como todos os meus pais.

[[v19-39-13]]

^<<v19-39-13,13>>^ Poupa-me, até que tome alento, antes que me vá, e não seja mais.

'''

xref:019-salmos/019-salmos-038.adoc#v19-38-0[&#60; Capítulo Anterior] | <<v19-39-0,Topo>> | xref:019-salmos/019-salmos-040.adoc#v19-40-0[Próximo Capítulo &#62;]