include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v15-10-1]]

^<<v15-10-1,1>>^ E enquanto Esdras orava, e fazia confissão, chorando e prostrando-se diante da casa de Deus, ajuntou-se a ele, de Israel, uma grande congregação de homens, mulheres e crianças; pois o povo chorava com grande choro.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Secanias, filho de Jeiel, um dos filhos de Elão, tomou a palavra e disse a Esdras: Nós temos transgredido contra o nosso Deus, e casamos com mulheres estrangeiras dentre os povos da terra, mas, no tocante a isto, ainda há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Agora, pois, façamos aliança com o nosso Deus de que despediremos todas as mulheres, e os que delas são nascidos, conforme ao conselho do meu senhor, e dos que tremem ao mandado do nosso Deus; e faça-se conforme a lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te, pois, porque te pertence este negócio, e nós seremos contigo; esforça-te, e age.

[[v15-10-5]]

^<<v15-10-5,5>>^ Então Esdras se levantou, e ajuramentou os chefes dos sacerdotes e dos levitas, e a todo o Israel, de que fariam conforme a esta palavra; e eles juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ E Esdras se levantou de diante da casa de Deus, e entrou na câmara de Joanã, filho de Eliasibe; e, chegando lá, não comeu pão, e nem bebeu água; porque lamentava pela transgressão dos do cativeiro.

[[v15-10-7]]

^<<v15-10-7,7>>^ E fizeram passar pregão por Judá e Jerusalém, a todos os que vieram do cativeiro, para que se ajuntassem em Jerusalém.

[[v15-10-8]]

^<<v15-10-8,8>>^ E que todo aquele que em três dias não viesse, segundo o conselho dos príncipes e dos anciãos, toda a sua fazenda se poria em interdito, e ele seria separado da congregação dos do cativeiro.

[[v15-10-9]]

^<<v15-10-9,9>>^ Então todos os homens de Judá e Benjamim em três dias se ajuntaram em Jerusalém; era o nono mês, aos vinte dias do mês; e todo o povo se assentou na praça da casa de Deus, tremendo por este negócio e por causa das grandes chuvas.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então se levantou Esdras, o sacerdote, e disse-lhes: Vós tendes transgredido, e casastes com mulheres estrangeiras, aumentando a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, pois, fazei confissão ao Senhor Deus de vossos pais, e fazei a sua vontade; e apartai-vos dos povos das terras, e das mulheres estrangeiras.

[[v15-10-12]]

^<<v15-10-12,12>>^ E respondeu toda a congregação, e disse em altas vozes: Assim seja, conforme às tuas palavras nos convém fazer.

[[v15-10-13]]

^<<v15-10-13,13>>^ Porém o povo é muito, e também é tempo de grandes chuvas, e não se pode estar aqui fora; nem é obra de um dia nem de dois, porque somos muitos os que transgredimos neste negócio.

[[v15-10-14]]

^<<v15-10-14,14>>^ Ora, ponham-se os nossos líderes, por toda a congregação sobre este negócio; e todos os que em nossas cidades casaram com mulheres estrangeiras venham em tempos apontados, e com eles os anciãos de cada cidade, e os seus juízes, até que desviemos de nós o ardor da ira do nosso Deus, por esta causa.

[[v15-10-15]]

^<<v15-10-15,15>>^ Porém, somente Jônatas, filho de Asael, e Jaseías, filho de Ticva, se opuseram a isto; e Mesulão, e Sabetai, levita, os ajudaram.

[[v15-10-16]]

^<<v15-10-16,16>>^ E assim o fizeram os que voltaram do cativeiro; e o sacerdote Esdras e os homens, chefes dos pais, segundo a casa de seus pais, e todos pelos seus nomes, foram apontados; e assentaram-se no primeiro dia do décimo mês, para inquirirem neste negócio.

[[v15-10-17]]

^<<v15-10-17,17>>^ E no primeiro dia do primeiro mês acabaram de tratar com todos os homens que casaram com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ E acharam-se dos filhos dos sacerdotes que casaram com mulheres estrangeiras: Dos filhos de Jesuá, filho de Jozadaque, e seus irmãos, Maaséias, e Eliezer, e Jaribe, e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ E deram as suas mãos prometendo que despediriam suas mulheres; e, achando-se culpados, ofereceram um carneiro do rebanho pelo seu delito.

[[v15-10-20]]

^<<v15-10-20,20>>^ E dos filhos de Imer: Hanani e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ E dos filhos de Harim: Maaséias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ E dos filhos de Pasur: Elioenai, Maaséias, Ismael, Netanel, Jozabade e Eleasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ E dos levitas: Jozabade, Simei, Quelaías (este é Quelita), Petaías, Judá e Eliezer.

[[v15-10-24]]

^<<v15-10-24,24>>^ E dos cantores: Eliasibe; e dos porteiros: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E de Israel, dos filhos de Parós: Ramias, Jezias, Malquias, Miamim, Eleazar, Malquias e Benaia.

[[v15-10-26]]

^<<v15-10-26,26>>^ E dos filhos de Elão: Matanias, Zacarias, Jeiel, Abdi, Jeremote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ E dos filhos de Zatu: Elioenai, Eliasibe, Matanias, Jeremote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ E dos filhos de Bebai: Joanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ E dos filhos de Bani: Mesulão, Maluque, Adaías, Jasube, Seal, Jeremote.

[[v15-10-30]]

^<<v15-10-30,30>>^ E dos filhos de Paate-Moabe: Adna, Quelal, Benaia, Maséias, Matanias, Bezalel, Binui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ E dos filhos de Harim: Eliezer, Josias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque, Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dos filhos de Bani: Maadai, Anrão, e Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matnai e Jaasai,

[[v15-10-38]]

^<<v15-10-38,38>>^ E Bani, Binui, Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ E Selemias, Natã e Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azareel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes tomaram mulheres estrangeiras; e alguns deles tinham mulheres de quem tiveram filhos.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]