include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v15-8-1]]

^<<v15-8-1,1>>^ Estes, pois, são os chefes das casas paternas e esta a genealogia dos que subiram comigo de babilônia no reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ Dos filhos de Finéias, Gérson; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ Dos filhos de Secanias, e dos filhos de Parós, Zacarias, e com ele, segundo a genealogia, se contaram até cento e cinqüenta homens.

[[v15-8-4]]

^<<v15-8-4,4>>^ Dos filhos de Paate-Moabe, Elioenai, filho de Zacarias, e com ele duzentos homens.

[[v15-8-5]]

^<<v15-8-5,5>>^ Dos filhos de Secanias, o filho de Jeaziel, e com ele trezentos homens.

[[v15-8-6]]

^<<v15-8-6,6>>^ E dos filhos de Adim, Ebede, filho de Jônatas, e com ele cinqüenta homens.

[[v15-8-7]]

^<<v15-8-7,7>>^ E dos filhos de Elão, Jesaías, filho de Atalias, e com ele setenta homens.

[[v15-8-8]]

^<<v15-8-8,8>>^ E dos filhos de Sefatias, Zebadias, filho de Micael, e com ele oitenta homens.

[[v15-8-9]]

^<<v15-8-9,9>>^ Dos filhos de Joabe, Obadias, filho de Jeiel, e com ele duzentos e dezoito homens.

[[v15-8-10]]

^<<v15-8-10,10>>^ E dos filhos de Selomite, o filho de Josifias, e com ele cento e sessenta homens.

[[v15-8-11]]

^<<v15-8-11,11>>^ E dos filhos de Bebai, Zacarias, o filho de Bebai, e com ele vinte e oito homens.

[[v15-8-12]]

^<<v15-8-12,12>>^ E dos filhos de Azgade, Joanã, o filho de Hacatã, e com ele cento e dez homens.

[[v15-8-13]]

^<<v15-8-13,13>>^ E dos últimos filhos de Adonicão, cujos nomes eram estes: Elifelete, Jeiel e Semaías, e com eles sessenta homens.

[[v15-8-14]]

^<<v15-8-14,14>>^ E dos filhos de Bigvai, Utai e Zabude, e com eles setenta homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ E ajuntei-os perto do rio que vai a Aava, e ficamos ali acampados três dias. Então atentei para o povo e para os sacerdotes, e não achei ali nenhum dos filhos de Levi.

[[v15-8-16]]

^<<v15-8-16,16>>^ Enviei, pois, Eliezer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, os chefes; como também a Joiaribe, e a Elnatã, que eram entendidos.

[[v15-8-17]]

^<<v15-8-17,17>>^ E enviei-os com mandado a Ido, chefe em Casifia; e falei a eles o que deveriam dizer a Ido e aos seus irmãos, servidores do templo, em Casifia, que nos trouxessem ministros para a casa do nosso Deus.

[[v15-8-18]]

^<<v15-8-18,18>>^ E trouxeram-nos, segundo a boa mão de Deus sobre nós, um homem entendido, dos filhos de Mali, filho de Levi, filho de Israel, a saber: Serebias, com os seus filhos e irmãos, dezoito;

[[v15-8-19]]

^<<v15-8-19,19>>^ E a Hasabias, e com ele Jesaías, dos filhos de Merari, com seus irmãos e os filhos deles, vinte;

[[v15-8-20]]

^<<v15-8-20,20>>^ E dos servidores do templo que Davi e os príncipes deram para o ministério dos levitas, duzentos e vinte servidores do templo; que foram todos mencionados por seus nomes.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então apregoei ali um jejum junto ao rio Aava, para nos humilharmos diante da face de nosso Deus, para lhe pedirmos caminho seguro para nós, para nossos filhos e para todos os nossos bens.

[[v15-8-22]]

^<<v15-8-22,22>>^ Porque tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo pelo caminho; porquanto tínhamos falado ao rei, dizendo: A mão do nosso Deus é sobre todos os que o buscam, para o bem deles; mas o seu poder e a sua ira contra todos os que o deixam.

[[v15-8-23]]

^<<v15-8-23,23>>^ Nós, pois, jejuamos, e pedimos isto ao nosso Deus, e moveu-se pelas nossas orações.

[[v15-8-24]]

^<<v15-8-24,24>>^ Então separei doze dos chefes dos sacerdotes: Serebias, Hasabias, e com eles dez dos seus irmãos.

[[v15-8-25]]

^<<v15-8-25,25>>^ E pesei-lhes a prata, o ouro e os vasos; que eram a oferta para a casa de nosso Deus, que ofereceram o rei, os seus conselheiros, os seus príncipes e todo o Israel que ali se achou.

[[v15-8-26]]

^<<v15-8-26,26>>^ E pesei em suas mãos seiscentos e cinqüenta talentos de prata, e em vasos de prata cem talentos, e cem talentos de ouro,

[[v15-8-27]]

^<<v15-8-27,27>>^ E vinte bacias de ouro, de mil dracmas, e dois vasos de bom metal lustroso, tão precioso como ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ E disse-lhes: Vós sois santos ao Senhor, e são santos estes utensílios, como também esta prata e este ouro, oferta voluntária, oferecida ao Senhor Deus de vossos pais.

[[v15-8-29]]

^<<v15-8-29,29>>^ Vigiai, pois, e guardai-os até que os peseis na presença dos chefes dos sacerdotes e dos levitas, e dos chefes dos pais de Israel, em Jerusalém, nas câmaras da casa do Senhor.

[[v15-8-30]]

^<<v15-8-30,30>>^ Então os sacerdotes e os levitas receberam o peso da prata, do ouro e dos utensílios, para os trazerem a Jerusalém, à casa de nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ E partimos do rio Aava, no dia doze do primeiro mês, para irmos a Jerusalém; e a mão do nosso Deus estava sobre nós, e livrou-nos da mão dos inimigos, e dos que nos armavam ciladas pelo caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ E chegamos a Jerusalém, e repousamos ali três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ E no quarto dia se pesou a prata, o ouro e os utensílios, na casa do nosso Deus, por mão de Meremote, filho do sacerdote Urias; e com ele Eleazar, filho de Finéias, e com eles Jozabade, filho de Jesuá, e Noadias, filho de Binui, levitas.

[[v15-8-34]]

^<<v15-8-34,34>>^ Tudo foi contado e pesado; e todo o peso foi registrado na mesma ocasião.

[[v15-8-35]]

^<<v15-8-35,35>>^ E os exilados, que vieram do cativeiro, ofereceram holocaustos ao Deus de Israel: doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros, e doze bodes em sacrifício pelo pecado; tudo em holocausto ao Senhor.

[[v15-8-36]]

^<<v15-8-36,36>>^ Então deram as ordens do rei aos seus sátrapas, e aos governadores dalém do rio; e estes ajudaram o povo e a casa de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]