include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v15-5-1]]

^<<v15-5-1,1>>^ E os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá, e em Jerusalém; em nome do Deus de Israel lhes profetizaram.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então se levantaram Zorobabel, filho de Sealtiel, e Jesuá, filho de Jozadaque, e começaram a edificar a casa de Deus, que está em Jerusalém; e com eles os profetas de Deus, que os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Naquele tempo vieram a eles Tatenai, governador dalém do rio, e Setar-Bozenai, e os seus companheiros, e disseram-lhes assim: Quem vos deu ordem para reedificardes esta casa, e restaurardes este muro?

[[v15-5-4]]

^<<v15-5-4,4>>^ Disseram-lhes, mais: E quais são os nomes dos homens que construíram este edifício?

[[v15-5-5]]

^<<v15-5-5,5>>^ Porém os olhos de Deus estavam sobre os anciãos dos judeus, e não os impediram, até que o negócio chegasse a Dario, e viesse resposta por carta sobre isso.

[[v15-5-6]]

^<<v15-5-6,6>>^ Cópia da carta que Tatenai, o governador dalém do rio, com Setar-Bozenai e os seus companheiros, os afarsaquitas, que estavam dalém do rio, enviaram ao rei Dario.

[[v15-5-7]]

^<<v15-5-7,7>>^ Enviaram-lhe uma carta, na qual estava escrito: Toda a paz ao rei Dario.

[[v15-5-8]]

^<<v15-5-8,8>>^ Seja notório ao rei, que nós fomos à província de Judá, à casa do grande Deus, a qual se edifica com grandes pedras, e a madeira já está sendo posta nas paredes; e esta obra vai sendo feita com diligência, e se adianta em suas mãos.

[[v15-5-9]]

^<<v15-5-9,9>>^ Então perguntamos aos anciãos, e assim lhes dissemos: Quem vos deu ordem para reedificardes esta casa, e restaurardes este muro?

[[v15-5-10]]

^<<v15-5-10,10>>^ Além disso, lhes perguntamos também pelos seus nomes, para tos declararmos; para que te pudéssemos escrever os nomes dos homens que entre eles são os chefes.

[[v15-5-11]]

^<<v15-5-11,11>>^ E esta foi a resposta que nos deram: Nós somos servos do Deus dos céus e da terra, e reedificamos a casa que há muitos anos foi edificada; porque um grande rei de Israel a edificou e a terminou.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor, rei de babilônia, o caldeu, o qual destruiu esta casa, e transportou o povo para babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Porém, no primeiro ano de Ciro, rei de babilônia, o rei Ciro deu ordem para que esta casa de Deus se reedificasse.

[[v15-5-14]]

^<<v15-5-14,14>>^ E até os utensílios de ouro e prata, da casa de Deus, que Nabucodonosor tomou do templo que estava em Jerusalém e os levou para o templo de babilônia, o rei Ciro os tirou do templo de babilônia, e foram dados a um homem cujo nome era Sesbazar, a quem nomeou governador.

[[v15-5-15]]

^<<v15-5-15,15>>^ E disse-lhe: Toma estes utensílios, vai e leva-os ao templo que está em Jerusalém, e faze reedificar a casa de Deus, no seu lugar.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então veio este Sesbazar, e pôs os fundamentos da casa de Deus, que está em Jerusalém, e desde então para cá se está reedificando, e ainda não está acabada.

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, pois, se parece bem ao rei, busque-se na casa dos tesouros do rei, que está em babilônia, se é verdade que se deu uma ordem pelo rei Ciro para reedificar esta casa de Deus em Jerusalém; e sobre isto nos faça saber a vontade do rei.

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]