include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v39-2-1]]

^<<v39-2-1,1>>^ Agora, ó sacerdotes, este mandamento é para vós.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se não ouvirdes e se não propuserdes, no vosso coração, dar honra ao meu nome, diz o Senhor dos Exércitos, enviarei a maldição contra vós, e amaldiçoarei as vossas bênçãos; e também já as tenho amaldiçoado, porque não aplicais a isso o coração.

[[v39-2-3]]

^<<v39-2-3,3>>^ Eis que reprovarei a vossa semente, e espalharei esterco sobre os vossos rostos, o esterco das vossas festas solenes; e para junto deste sereis levados.

[[v39-2-4]]

^<<v39-2-4,4>>^ Então sabereis que eu vos enviei este mandamento, para que a minha aliança fosse com Levi, diz o Senhor dos Exércitos.

[[v39-2-5]]

^<<v39-2-5,5>>^ Minha aliança com ele foi de vida e de paz, e eu lhas dei para que temesse; então temeu-me, e assombrou-se por causa do meu nome.

[[v39-2-6]]

^<<v39-2-6,6>>^ A lei da verdade esteve na sua boca, e a iniqüidade não se achou nos seus lábios; andou comigo em paz e em retidão, e da iniqüidade converteu a muitos.

[[v39-2-7]]

^<<v39-2-7,7>>^ Porque os lábios do sacerdote devem guardar o conhecimento, e da sua boca devem os homens buscar a lei porque ele é o mensageiro do Senhor dos Exércitos.

[[v39-2-8]]

^<<v39-2-8,8>>^ Mas vós vos desviastes do caminho; a muitos fizestes tropeçar na lei; corrompestes a aliança de Levi, diz o Senhor dos Exércitos.

[[v39-2-9]]

^<<v39-2-9,9>>^ Por isso também eu vos fiz desprezíveis, e indignos diante de todo o povo, visto que não guardastes os meus caminhos, mas fizestes acepção de pessoas na lei.

[[v39-2-10]]

^<<v39-2-10,10>>^ Não temos nós todos um mesmo Pai? Não nos criou um mesmo Deus? Por que agimos aleivosamente cada um contra seu irmão, profanando a aliança de nossos pais?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá tem sido desleal, e abominação se cometeu em Israel e em Jerusalém; porque Judá profanou o santuário do Senhor, o qual ele ama, e se casou com a filha de deus estranho.

[[v39-2-12]]

^<<v39-2-12,12>>^ O Senhor destruirá das tendas de Jacó o homem que fizer isto, o que vela, e o que responde, e o que apresenta uma oferta ao Senhor dos Exércitos.

[[v39-2-13]]

^<<v39-2-13,13>>^ Ainda fazeis isto outra vez, cobrindo o altar do Senhor de lágrimas, com choro e com gemidos; de sorte que ele não olha mais para a oferta, nem a aceitará com prazer da vossa mão.

[[v39-2-14]]

^<<v39-2-14,14>>^ E dizeis: Por quê? Porque o Senhor foi testemunha entre ti e a mulher da tua mocidade, com a qual tu foste desleal, sendo ela a tua companheira, e a mulher da tua aliança.

[[v39-2-15]]

^<<v39-2-15,15>>^ E não fez ele somente um, ainda que lhe sobrava o espírito? E por que somente um? Ele buscava uma descendência para Deus. Portanto guardai-vos em vosso espírito, e ninguém seja infiel para com a mulher da sua mocidade.

[[v39-2-16]]

^<<v39-2-16,16>>^ Porque o Senhor, o Deus de Israel diz que odeia o repúdio, e aquele que encobre a violência com a sua roupa, diz o Senhor dos Exércitos; portanto guardai-vos em vosso espírito, e não sejais desleais.

[[v39-2-17]]

^<<v39-2-17,17>>^ Enfadais ao Senhor com vossas palavras; e ainda dizeis: Em que o enfadamos? Nisto que dizeis: Qualquer que faz o mal passa por bom aos olhos do Senhor, e desses é que ele se agrada, ou, onde está o Deus do juízo?

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]