include::./index.adoc[]

[[v39-4-0]]
=== Malaquias, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v39-4-1]]

^<<v39-4-1,1>>^ Porque eis que aquele dia vem ardendo como fornalha; todos os soberbos, e todos os que cometem impiedade, serão como a palha; e o dia que está para vir os abrasará, diz o SENHOR dos Exércitos, de sorte que lhes não deixará nem raiz nem ramo.

[[v39-4-2]]

^<<v39-4-2,2>>^ Mas para vós, os que temeis o meu nome, nascerá o sol da justiça, e cura trará nas suas asas; e saireis e saltareis como bezerros da estrebaria.

[[v39-4-3]]

^<<v39-4-3,3>>^ E pisareis os ímpios, porque se farão cinza debaixo das plantas de vossos pés, naquele dia que estou preparando, diz o Senhor dos Exércitos.

[[v39-4-4]]

^<<v39-4-4,4>>^ Lembrai-vos da lei de Moisés, meu servo, que lhe mandei em Horebe para todo o Israel, a saber, estatutos e juízos.

[[v39-4-5]]

^<<v39-4-5,5>>^ Eis que eu vos enviarei o profeta Elias, antes que venha o grande e terrível dia do Senhor;

[[v39-4-6]]

^<<v39-4-6,6>>^ E ele converterá o coração dos pais aos filhos, e o coração dos filhos a seus pais; para que eu não venha, e fira a terra com maldição.

'''

xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-mateus/040-mateus-001.adoc#v40-1-0[Próximo Capítulo &#62;]