include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v25-4-1]]

^<<v25-4-1,1>>^ Como se escureceu o ouro! Como se mudou o ouro puro e bom! Como estão espalhadas as pedras do santuário sobre cada rua!

[[v25-4-2]]

^<<v25-4-2,2>>^ Os preciosos filhos de Sião, avaliados a puro ouro, como são agora reputados por vasos de barro, obra das mãos do oleiro!

[[v25-4-3]]

^<<v25-4-3,3>>^ Até os chacais abaixam o peito, dão de mamar aos seus filhos; mas a filha do meu povo tornou-se cruel como os avestruzes no deserto.

[[v25-4-4]]

^<<v25-4-4,4>>^ A língua do que mama fica pegada pela sede ao seu paladar; os meninos pedem pão, e ninguém lho reparte.

[[v25-4-5]]

^<<v25-4-5,5>>^ Os que comiam comidas finas agora desfalecem nas ruas; os que se criaram em carmesim abraçam monturos.

[[v25-4-6]]

^<<v25-4-6,6>>^ Porque maior é a iniqüidade da filha do meu povo do que o pecado de Sodoma, a qual foi subvertida como num momento, sem que mãos lhe tocassem.

[[v25-4-7]]

^<<v25-4-7,7>>^ Os seus nobres eram mais puros do que a neve, mais brancos do que o leite, mais vermelhos de corpo do que os rubis, e mais polidos do que a safira.

[[v25-4-8]]

^<<v25-4-8,8>>^ Mas agora escureceu-se o seu aspecto mais do que o negrume; não são conhecidos nas ruas; a sua pele se lhes pegou aos ossos, secou-se, tornou-se como um pau.

[[v25-4-9]]

^<<v25-4-9,9>>^ Os mortos à espada foram mais ditosos do que os mortos à fome; porque estes morreram lentamente, por falta dos frutos dos campos.

[[v25-4-10]]

^<<v25-4-10,10>>^ As mãos das mulheres compassivas cozeram seus próprios filhos; serviram-lhes de alimento na destruição da filha do meu povo.

[[v25-4-11]]

^<<v25-4-11,11>>^ Deu o Senhor cumprimento ao seu furor; derramou o ardor da sua ira, e acendeu fogo em Sião, que consumiu os seus fundamentos.

[[v25-4-12]]

^<<v25-4-12,12>>^ Não creram os reis da terra, nem todos os moradores do mundo, que entrasse o adversário e o inimigo pelas portas de Jerusalém.

[[v25-4-13]]

^<<v25-4-13,13>>^ Foi por causa dos pecados dos profetas, das maldades dos seus sacerdotes, que derramaram o sangue dos justos no meio dela.

[[v25-4-14]]

^<<v25-4-14,14>>^ Vagueiam como cegos nas ruas, andam contaminados de sangue; de tal sorte que ninguém pode tocar nas suas roupas.

[[v25-4-15]]

^<<v25-4-15,15>>^ Desviai-vos, imundos! gritavam-lhes; desviai-vos, desviai-vos, não toqueis! quando fugiram e também andaram errantes, dizia-se entre os gentios: Nunca mais morarão aqui.

[[v25-4-16]]

^<<v25-4-16,16>>^ A face indignada do Senhor os espalhou, ele nunca mais tornará a olhar para eles; não respeitaram a pessoa dos sacerdotes, nem se compadeceram dos velhos.

[[v25-4-17]]

^<<v25-4-17,17>>^ Os nossos olhos desfaleciam, esperando o nosso vão socorro; olhávamos atentamente para uma nação que não nos podia livrar.

[[v25-4-18]]

^<<v25-4-18,18>>^ Espiaram os nossos passos, de maneira que não podíamos andar pelas nossas ruas; está chegado o nosso fim, estão cumpridos os nossos dias, porque é vindo o nosso fim.

[[v25-4-19]]

^<<v25-4-19,19>>^ Os nossos perseguidores foram mais ligeiros do que as águias dos céus; sobre os montes nos perseguiram, no deserto nos armaram ciladas.

[[v25-4-20]]

^<<v25-4-20,20>>^ O fôlego das nossas narinas, o ungido do Senhor, foi preso nas suas covas; dele dizíamos: Debaixo da sua sombra viveremos entre os gentios.

[[v25-4-21]]

^<<v25-4-21,21>>^ Regozija-te e alegra-te, ó filha de Edom, que habitas na terra de Uz; o cálice passará também para ti; embebedar-te-ás, e te descobrirás.

[[v25-4-22]]

^<<v25-4-22,22>>^ O castigo da tua maldade está consumado, ó filha de Sião; ele nunca mais te levará para o cativeiro; ele visitará a tua maldade, ó filha de Edom, descobrirá os teus pecados.

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]