include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v25-1-1]]

^<<v25-1-1,1>>^ Como está sentada solitária aquela cidade, antes tão populosa! Tornou-se como viúva, a que era grande entre as nações! A que era princesa entre as províncias, tornou-se tributária!

[[v25-1-2]]

^<<v25-1-2,2>>^ Chora amargamente de noite, e as suas lágrimas lhe correm pelas faces; não tem quem a console entre todos os seus amantes; todos os seus amigos se houveram aleivosamente com ela, tornaram-se seus inimigos.

[[v25-1-3]]

^<<v25-1-3,3>>^ Judá passou em cativeiro por causa da aflição, e por causa da grande servidão; ela habita entre os gentios, não acha descanso; todos os seus perseguidores a alcançam entre as suas dificuldades.

[[v25-1-4]]

^<<v25-1-4,4>>^ Os caminhos de Sião pranteiam, porque não há quem venha à festa solene; todas as suas portas estão desoladas; os seus sacerdotes suspiram; as suas virgens estão tristes, e ela mesma tem amargura.

[[v25-1-5]]

^<<v25-1-5,5>>^ Os seus adversários têm sido feitos chefes, os seus inimigos prosperam; porque o Senhor a afligiu, por causa da multidão das suas transgressões; os seus filhinhos foram para o cativeiro na frente do adversário.

[[v25-1-6]]

^<<v25-1-6,6>>^ E da filha de Sião já se foi toda a sua formosura; os seus príncipes ficaram sendo como corços que não acham pasto e caminham sem força adiante do perseguidor.

[[v25-1-7]]

^<<v25-1-7,7>>^ Lembra-se Jerusalém, nos dias da sua aflição e dos seus exílios, de todas as suas mais queridas coisas, que tivera desde os tempos antigos; quando caía o seu povo na mão do adversário, e não havia quem a socorresse; os adversários a viram, e fizeram escárnio da sua ruína.

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém gravemente pecou, por isso se fez errante; todos os que a honravam, a desprezaram, porque viram a sua nudez; ela também suspira e volta para trás.

[[v25-1-9]]

^<<v25-1-9,9>>^ A sua imundícia está nas suas saias; nunca se lembrou do seu fim; por isso foi pasmosamente abatida, não tem consolador; vê, Senhor, a minha aflição, porque o inimigo se tem engrandecido.

[[v25-1-10]]

^<<v25-1-10,10>>^ Estendeu o adversário a sua mão a todas as coisas mais preciosas dela; pois ela viu entrar no seu santuário os gentios, acerca dos quais mandaste que não entrassem na tua congregação.

[[v25-1-11]]

^<<v25-1-11,11>>^ Todo o seu povo anda suspirando, buscando o pão; deram as suas coisas mais preciosas a troco de mantimento para restaurarem a alma; vê, Senhor, e contempla, que sou desprezível.

[[v25-1-12]]

^<<v25-1-12,12>>^ Não vos comove isto a todos vós que passais pelo caminho? Atendei, e vede, se há dor como a minha dor, que veio sobre mim, com que o Senhor me afligiu, no dia do furor da sua ira.

[[v25-1-13]]

^<<v25-1-13,13>>^ Desde o alto enviou fogo a meus ossos, o qual se assenhoreou deles; estendeu uma rede aos meus pés, fez-me voltar para trás, fez-me assolada e enferma todo o dia.

[[v25-1-14]]

^<<v25-1-14,14>>^ O jugo das minhas transgressões está atado pela sua mão; elas estão entretecidas, subiram sobre o meu pescoço, e ele abateu a minha força; entregou-me o Senhor nas mãos daqueles a quem não posso resistir.

[[v25-1-15]]

^<<v25-1-15,15>>^ O Senhor atropelou todos os meus poderosos no meio de mim; convocou contra mim uma assembléia, para esmagar os meus jovens; o Senhor pisou como num lagar a virgem filha de Judá.

[[v25-1-16]]

^<<v25-1-16,16>>^ Por estas coisas eu ando chorando; os meus olhos, os meus olhos se desfazem em águas; porque se afastou de mim o consolador que devia restaurar a minha alma; os meus filhos estão assolados, porque prevaleceu o inimigo.

[[v25-1-17]]

^<<v25-1-17,17>>^ Estende Sião as suas mãos, não há quem a console; mandou o Senhor acerca de Jacó que lhe fossem inimigos os que estão em redor dele; Jerusalém é entre eles como uma mulher imunda.

[[v25-1-18]]

^<<v25-1-18,18>>^ Justo é o Senhor, pois me rebelei contra o seu mandamento; ouvi, pois, todos os povos, e vede a minha dor; as minhas virgens e os meus jovens foram levados para o cativeiro.

[[v25-1-19]]

^<<v25-1-19,19>>^ Chamei os meus amantes, mas eles me enganaram; os meus sacerdotes e os meus anciãos expiraram na cidade; enquanto buscavam para si mantimento, para restaurarem a sua alma.

[[v25-1-20]]

^<<v25-1-20,20>>^ Olha, Senhor, porque estou angustiada; turbadas estão as minhas entranhas; o meu coração está transtornado dentro de mim, porque gravemente me rebelei; fora me desfilhou a espada, em casa está a morte.

[[v25-1-21]]

^<<v25-1-21,21>>^ Ouviram que eu suspiro, mas não tenho quem me console; todos os meus inimigos que souberam do meu mal folgam, porque tu o fizeste; mas, em trazendo tu o dia que apregoaste, serão como eu.

[[v25-1-22]]

^<<v25-1-22,22>>^ Venha toda a sua maldade diante de ti, e faze-lhes como me fizeste a mim por causa de todas as minhas transgressões; porque os meus suspiros são muitos, e o meu coração está desfalecido.

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]