include::./index.adoc[]

[[v5-14-0]]
=== Deuteronômio, 14
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-14-1]]

^<<v5-14-1,1>>^ Filhos sois do SENHOR vosso Deus; não vos dareis golpes, nem fareis calva entre vossos olhos por causa de algum morto.

[[v5-14-2]]

^<<v5-14-2,2>>^ Porque és povo santo ao Senhor teu Deus; e o Senhor te escolheu, de todos os povos que há sobre a face da terra, para lhe seres o seu próprio povo.

[[v5-14-3]]

^<<v5-14-3,3>>^ Nenhuma coisa abominável comereis.

[[v5-14-4]]

^<<v5-14-4,4>>^ Estes são os animais que comereis: o boi, a ovelha, e a cabra.

[[v5-14-5]]

^<<v5-14-5,5>>^ O veado e a corça, e o búfalo, e a cabra montês, e o texugo, e a camurça, e o gamo.

[[v5-14-6]]

^<<v5-14-6,6>>^ Todo o animal que tem unhas fendidas, divididas em duas, que rumina, entre os animais, aquilo comereis.

[[v5-14-7]]

^<<v5-14-7,7>>^ Porém estes não comereis, dos que somente ruminam, ou que têm a unha fendida: o camelo, e a lebre, e o coelho, porque ruminam mas não têm a unha fendida; imundos vos serão.

[[v5-14-8]]

^<<v5-14-8,8>>^ Nem o porco, porque tem unha fendida, mas não rumina; imundo vos será; não comereis da carne destes, e não tocareis nos seus cadáveres.

[[v5-14-9]]

^<<v5-14-9,9>>^ Isto comereis de tudo o que há nas águas; tudo o que tem barbatanas e escamas comereis.

[[v5-14-10]]

^<<v5-14-10,10>>^ Mas tudo o que não tiver barbatanas nem escamas não o comereis; imundo vos será.

[[v5-14-11]]

^<<v5-14-11,11>>^ Toda a ave limpa comereis.

[[v5-14-12]]

^<<v5-14-12,12>>^ Porém estas são as que não comereis: a águia, e o quebrantosso, e o xofrango,

[[v5-14-13]]

^<<v5-14-13,13>>^ E o abutre, e o falcão, e o milhafre, segundo a sua espécie.

[[v5-14-14]]

^<<v5-14-14,14>>^ E todo o corvo, segundo a sua espécie.

[[v5-14-15]]

^<<v5-14-15,15>>^ E o avestruz, e o mocho, e a gaivota, e o gavião, segundo a sua espécie.

[[v5-14-16]]

^<<v5-14-16,16>>^ E o bufo, e a coruja, e a gralha,

[[v5-14-17]]

^<<v5-14-17,17>>^ E o cisne, e o pelicano, e o corvo marinho,

[[v5-14-18]]

^<<v5-14-18,18>>^ E a cegonha, e a garça, segundo a sua espécie, e a poupa, e o morcego.

[[v5-14-19]]

^<<v5-14-19,19>>^ Também todo o inseto que voa, vos será imundo; não se comerá.

[[v5-14-20]]

^<<v5-14-20,20>>^ Toda a ave limpa comereis.

[[v5-14-21]]

^<<v5-14-21,21>>^ Não comereis nenhum animal morto; ao estrangeiro, que está dentro das tuas portas, o darás a comer, ou o venderás ao estranho, porquanto és povo santo ao Senhor teu Deus. Não cozerás o cabrito com leite da sua mãe.

[[v5-14-22]]

^<<v5-14-22,22>>^ Certamente darás os dízimos de todo o fruto da tua semente, que cada ano se recolher do campo.

[[v5-14-23]]

^<<v5-14-23,23>>^ E, perante o Senhor teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu grão, do teu mosto e do teu azeite, e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer ao Senhor teu Deus todos os dias.

[[v5-14-24]]

^<<v5-14-24,24>>^ E quando o caminho te for tão comprido que os não possas levar, por estar longe de ti o lugar que escolher o Senhor teu Deus para ali pôr o seu nome, quando o Senhor teu Deus te tiver abençoado;

[[v5-14-25]]

^<<v5-14-25,25>>^ Então vende-os, e ata o dinheiro na tua mão, e vai ao lugar que escolher o Senhor teu Deus;

[[v5-14-26]]

^<<v5-14-26,26>>^ E aquele dinheiro darás por tudo o que deseja a tua alma, por vacas, e por ovelhas, e por vinho, e por bebida forte, e por tudo o que te pedir a tua alma; come-o ali perante o Senhor teu Deus, e alegra-te, tu e a tua casa;

[[v5-14-27]]

^<<v5-14-27,27>>^ Porém não desampararás o levita que está dentro das tuas portas; pois não tem parte nem herança contigo.

[[v5-14-28]]

^<<v5-14-28,28>>^ Ao fim de três anos tirarás todos os dízimos da tua colheita no mesmo ano, e os recolherás dentro das tuas portas;

[[v5-14-29]]

^<<v5-14-29,29>>^ Então virá o levita (pois nem parte nem herança tem contigo), e o estrangeiro, e o órfão, e a viúva, que estão dentro das tuas portas, e comerão, e fartar-se-ão; para que o Senhor teu Deus te abençoe em toda a obra que as tuas mãos fizerem.

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]