include::./index.adoc[]

[[v5-25-0]]
=== Deuteronômio, 25
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-25-1]]

^<<v5-25-1,1>>^ Quando houver contenda entre alguns, e vierem a juízo, para que os julguem, ao justo justificarão, e ao injusto condenarão.

[[v5-25-2]]

^<<v5-25-2,2>>^ E será que, se o injusto merecer açoites, o juiz o fará deitar-se, para que seja açoitado diante de si; segundo a sua culpa, será o número de açoites.

[[v5-25-3]]

^<<v5-25-3,3>>^ Quarenta açoites lhe fará dar, não mais; para que, porventura, se lhe fizer dar mais açoites do que estes, teu irmão não fique envilecido aos teus olhos.

[[v5-25-4]]

^<<v5-25-4,4>>^ Não atarás a boca ao boi, quando trilhar.

[[v5-25-5]]

^<<v5-25-5,5>>^ Quando irmãos morarem juntos, e um deles morrer, e não tiver filho, então a mulher do falecido não se casará com homem estranho, de fora; seu cunhado estará com ela, e a receberá por mulher, e fará a obrigação de cunhado para com ela.

[[v5-25-6]]

^<<v5-25-6,6>>^ E o primogênito que ela lhe der será sucessor do nome do seu irmão falecido, para que o seu nome não se apague em Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ Porém, se o homem não quiser tomar sua cunhada, esta subirá à porta dos anciãos, e dirá: Meu cunhado recusa suscitar a seu irmão nome em Israel; não quer cumprir para comigo o dever de cunhado.

[[v5-25-8]]

^<<v5-25-8,8>>^ Então os anciãos da sua cidade o chamarão, e com ele falarão; e, se ele persistir, e disser: Não quero tomá-la;

[[v5-25-9]]

^<<v5-25-9,9>>^ Então sua cunhada se chegará a ele na presença dos anciãos, e lhe descalçará o sapato do pé, e lhe cuspirá no rosto, e protestará, e dirá: Assim se fará ao homem que não edificar a casa de seu irmão;

[[v5-25-10]]

^<<v5-25-10,10>>^ E o seu nome se chamará em Israel: A casa do descalçado.

[[v5-25-11]]

^<<v5-25-11,11>>^ Quando pelejarem dois homens, um contra o outro, e a mulher de um chegar para livrar a seu marido da mão do que o fere, e ela estender a sua mão, e lhe pegar pelas suas vergonhas,

[[v5-25-12]]

^<<v5-25-12,12>>^ Então cortar-lhe-ás a mão; não a poupará o teu olho.

[[v5-25-13]]

^<<v5-25-13,13>>^ Na tua bolsa não terás pesos diversos, um grande e um pequeno.

[[v5-25-14]]

^<<v5-25-14,14>>^ Na tua casa não terás dois tipos de efa, um grande e um pequeno.

[[v5-25-15]]

^<<v5-25-15,15>>^ Peso inteiro e justo terás; efa inteiro e justo terás; para que se prolonguem os teus dias na terra que te dará o Senhor teu Deus.

[[v5-25-16]]

^<<v5-25-16,16>>^ Porque abominação é ao Senhor teu Deus todo aquele que faz isto, todo aquele que fizer injustiça.

[[v5-25-17]]

^<<v5-25-17,17>>^ Lembra-te do que te fez Amaleque no caminho, quando saías do Egito;

[[v5-25-18]]

^<<v5-25-18,18>>^ Como te saiu ao encontro no caminho, e feriu na tua retaguarda todos os fracos que iam atrás de ti, estando tu cansado e afadigado; e não temeu a Deus.

[[v5-25-19]]

^<<v5-25-19,19>>^ Será, pois, que, quando o Senhor teu Deus te tiver dado repouso de todos os teus inimigos em redor, na terra que o Senhor teu Deus te dá por herança, para possuí-la, então apagarás a memória de Amaleque de debaixo do céu; não te esqueças.

'''

xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[Próximo Capítulo &#62;]