include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-28-1]]

^<<v5-28-1,1>>^ E será que, se ouvires a voz do SENHOR teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu hoje te ordeno, o SENHOR teu Deus te exaltará sobre todas as nações da terra.

[[v5-28-2]]

^<<v5-28-2,2>>^ E todas estas bênçãos virão sobre ti e te alcançarão, quando ouvires a voz do Senhor teu Deus:

[[v5-28-3]]

^<<v5-28-3,3>>^ Bendito serás na cidade, e bendito serás no campo.

[[v5-28-4]]

^<<v5-28-4,4>>^ Bendito o fruto do teu ventre, e o fruto da tua terra, e o fruto dos teus animais; e as crias das tuas vacas e das tuas ovelhas.

[[v5-28-5]]

^<<v5-28-5,5>>^ Bendito o teu cesto e a tua amassadeira.

[[v5-28-6]]

^<<v5-28-6,6>>^ Bendito serás ao entrares, e bendito serás ao saíres.

[[v5-28-7]]

^<<v5-28-7,7>>^ O Senhor entregará, feridos diante de ti, os teus inimigos, que se levantarem contra ti; por um caminho sairão contra ti, mas por sete caminhos fugirão da tua presença.

[[v5-28-8]]

^<<v5-28-8,8>>^ O Senhor mandará que a bênção esteja contigo nos teus celeiros, e em tudo o que puseres a tua mão; e te abençoará na terra que te der o Senhor teu Deus.

[[v5-28-9]]

^<<v5-28-9,9>>^ O Senhor te confirmará para si como povo santo, como te tem jurado, quando guardares os mandamentos do Senhor teu Deus, e andares nos seus caminhos.

[[v5-28-10]]

^<<v5-28-10,10>>^ E todos os povos da terra verão que é invocado sobre ti o nome do Senhor, e terão temor de ti.

[[v5-28-11]]

^<<v5-28-11,11>>^ E o Senhor te dará abundância de bens no fruto do teu ventre, e no fruto dos teus animais, e no fruto do teu solo, sobre a terra que o Senhor jurou a teus pais te dar.

[[v5-28-12]]

^<<v5-28-12,12>>^ O Senhor te abrirá o seu bom tesouro, o céu, para dar chuva à tua terra no seu tempo, e para abençoar toda a obra das tuas mãos; e emprestarás a muitas nações, porém tu não tomarás emprestado.

[[v5-28-13]]

^<<v5-28-13,13>>^ E o Senhor te porá por cabeça, e não por cauda; e só estarás em cima, e não debaixo, se obedeceres aos mandamentos do Senhor teu Deus, que hoje te ordeno, para os guardar e cumprir.

[[v5-28-14]]

^<<v5-28-14,14>>^ E não te desviarás de todas as palavras que hoje te ordeno, nem para a direita nem para a esquerda, andando após outros deuses, para os servires.

[[v5-28-15]]

^<<v5-28-15,15>>^ Será, porém, que, se não deres ouvidos à voz do Senhor teu Deus, para não cuidares em cumprir todos os seus mandamentos e os seus estatutos, que hoje te ordeno, então virão sobre ti todas estas maldições, e te alcançarão:

[[v5-28-16]]

^<<v5-28-16,16>>^ Maldito serás tu na cidade, e maldito serás no campo.

[[v5-28-17]]

^<<v5-28-17,17>>^ Maldito o teu cesto e a tua amassadeira.

[[v5-28-18]]

^<<v5-28-18,18>>^ Maldito o fruto do teu ventre, e o fruto da tua terra, e as crias das tuas vacas, e das tuas ovelhas.

[[v5-28-19]]

^<<v5-28-19,19>>^ Maldito serás ao entrares, e maldito serás ao saíres.

[[v5-28-20]]

^<<v5-28-20,20>>^ O Senhor mandará sobre ti a maldição; a confusão e a derrota em tudo em que puseres a mão para fazer; até que sejas destruído, e até que repentinamente pereças, por causa da maldade das tuas obras, pelas quais me deixaste.

[[v5-28-21]]

^<<v5-28-21,21>>^ O Senhor fará pegar em ti a pestilência, até que te consuma da terra a que passas a possuir.

[[v5-28-22]]

^<<v5-28-22,22>>^ O Senhor te ferirá com a tísica e com a febre, e com a inflamação, e com o calor ardente, e com a secura, e com crestamento e com ferrugem; e te perseguirão até que pereças.

[[v5-28-23]]

^<<v5-28-23,23>>^ E os teus céus, que estão sobre a cabeça, serão de bronze; e a terra que está debaixo de ti, será de ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ O Senhor dará por chuva sobre a tua terra, pó e poeira; dos céus descerá sobre ti, até que pereças.

[[v5-28-25]]

^<<v5-28-25,25>>^ O Senhor te fará cair diante dos teus inimigos; por um caminho sairás contra eles, e por sete caminhos fugirás de diante deles, e serás espalhado por todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ E o teu cadáver servirá de comida a todas as aves dos céus, e aos animais da terra; e ninguém os espantará.

[[v5-28-27]]

^<<v5-28-27,27>>^ O Senhor te ferirá com as úlceras do Egito, com tumores, e com sarna, e com coceira, de que não possas curar-te;

[[v5-28-28]]

^<<v5-28-28,28>>^ O Senhor te ferirá com loucura, e com cegueira, e com pasmo de coração;

[[v5-28-29]]

^<<v5-28-29,29>>^ E apalparás ao meio-dia, como o cego apalpa na escuridão, e não prosperarás nos teus caminhos; porém somente serás oprimido e roubado todos os dias, e não haverá quem te salve.

[[v5-28-30]]

^<<v5-28-30,30>>^ Desposar-te-ás com uma mulher, porém outro homem dormirá com ela; edificarás uma casa, porém não morarás nela; plantarás uma vinha, porém não aproveitarás o seu fruto.

[[v5-28-31]]

^<<v5-28-31,31>>^ O teu boi será morto aos teus olhos, porém dele não comerás; o teu jumento será roubado diante de ti, e não voltará a ti; as tuas ovelhas serão dadas aos teus inimigos, e não haverá quem te salve.

[[v5-28-32]]

^<<v5-28-32,32>>^ Teus filhos e tuas filhas serão dados a outro povo, os teus olhos o verão, e por eles desfalecerão todo o dia; porém não haverá poder na tua mão.

[[v5-28-33]]

^<<v5-28-33,33>>^ O fruto da tua terra e todo o teu trabalho, comerá um povo que nunca conheceste; e tu serás oprimido e quebrantado todos os dias.

[[v5-28-34]]

^<<v5-28-34,34>>^ E enlouquecerás com o que vires com os teus olhos.

[[v5-28-35]]

^<<v5-28-35,35>>^ O Senhor te ferirá com úlceras malignas nos joelhos e nas pernas, de que não possas sarar, desde a planta do teu pé até ao alto da cabeça.

[[v5-28-36]]

^<<v5-28-36,36>>^ O Senhor te levará a ti e a teu rei, que tiveres posto sobre ti, a uma nação que não conheceste, nem tu nem teus pais; e ali servirás a outros deuses, ao pau e à pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ E serás por pasmo, por ditado, e por fábula, entre todos os povos a que o Senhor te levará.

[[v5-28-38]]

^<<v5-28-38,38>>^ Lançarás muita semente ao campo; porém colherás pouco, porque o gafanhoto a consumirá.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarás vinhas, e cultivarás; porém não beberás vinho, nem colherás as uvas; porque o bicho as colherá.

[[v5-28-40]]

^<<v5-28-40,40>>^ Em todos os termos terás oliveiras; porém não te ungirás com azeite; porque a azeitona cairá da tua oliveira.

[[v5-28-41]]

^<<v5-28-41,41>>^ Filhos e filhas gerarás; porém não serão para ti; porque irão em cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Todo o teu arvoredo e o fruto da tua terra consumirá a lagarta.

[[v5-28-43]]

^<<v5-28-43,43>>^ O estrangeiro, que está no meio de ti, se elevará muito sobre ti, e tu mais baixo descerás;

[[v5-28-44]]

^<<v5-28-44,44>>^ Ele te emprestará a ti, porém tu não emprestarás a ele; ele será por cabeça, e tu serás por cauda.

[[v5-28-45]]

^<<v5-28-45,45>>^ E todas estas maldições virão sobre ti, e te perseguirão, e te alcançarão, até que sejas destruído; porquanto não ouviste à voz do Senhor teu Deus, para guardares os seus mandamentos, e os seus estatutos, que te tem ordenado;

[[v5-28-46]]

^<<v5-28-46,46>>^ E serão entre ti por sinal e por maravilha, como também entre a tua descendência para sempre.

[[v5-28-47]]

^<<v5-28-47,47>>^ Porquanto não serviste ao Senhor teu Deus com alegria e bondade de coração, pela abundância de tudo.

[[v5-28-48]]

^<<v5-28-48,48>>^ Assim servirás aos teus inimigos, que o Senhor enviará contra ti, com fome e com sede, e com nudez, e com falta de tudo; e sobre o teu pescoço porá um jugo de ferro, até que te tenha destruído.

[[v5-28-49]]

^<<v5-28-49,49>>^ O Senhor levantará contra ti uma nação de longe, da extremidade da terra, que voa como a águia, nação cuja língua não entenderás;

[[v5-28-50]]

^<<v5-28-50,50>>^ Nação feroz de rosto, que não respeitará o rosto do velho, nem se apiedará do moço;

[[v5-28-51]]

^<<v5-28-51,51>>^ E comerá o fruto dos teus animais, e o fruto da tua terra, até que sejas destruído; e não te deixará grão, mosto, nem azeite, nem crias das tuas vacas, nem das tuas ovelhas, até que te haja consumido;

[[v5-28-52]]

^<<v5-28-52,52>>^ E sitiar-te-á em todas as tuas portas, até que venham a cair os teus altos e fortes muros, em que confiavas em toda a tua terra; e te sitiará em todas as tuas portas, em toda a tua terra que te tem dado o Senhor teu Deus.

[[v5-28-53]]

^<<v5-28-53,53>>^ E comerás o fruto do teu ventre, a carne de teus filhos e de tuas filhas, que te der o Senhor teu Deus, no cerco e no aperto com que os teus inimigos te apertarão.

[[v5-28-54]]

^<<v5-28-54,54>>^ Quanto ao homem mais mimoso e delicado no meio de ti, o seu olho será maligno para com o seu irmão, e para com a mulher do seu regaço, e para com os demais de seus filhos que ainda lhe ficarem;

[[v5-28-55]]

^<<v5-28-55,55>>^ De sorte que não dará a nenhum deles da carne de seus filhos, que ele comer; porquanto nada lhe ficou de resto no cerco e no aperto, com que o teu inimigo te apertará em todas as tuas portas.

[[v5-28-56]]

^<<v5-28-56,56>>^ E quanto à mulher mais mimosa e delicada no meio de ti, que de mimo e delicadeza nunca tentou pôr a planta de seu pé sobre a terra, será maligno o seu olho contra o homem de seu regaço, e contra seu filho, e contra sua filha;

[[v5-28-57]]

^<<v5-28-57,57>>^ E isto por causa de suas páreas, que saírem dentre os seus pés, e para com os seus filhos que tiver, porque os comerá às escondidas pela falta de tudo, no cerco e no aperto, com que o teu inimigo te apertará nas tuas portas.

[[v5-28-58]]

^<<v5-28-58,58>>^ Se não tiveres cuidado de guardar todas as palavras desta lei, que estão escritas neste livro, para temeres este nome glorioso e temível, o SENHOR TEU DEUS,

[[v5-28-59]]

^<<v5-28-59,59>>^ Então o Senhor fará espantosas as tuas pragas, e as pragas de tua descendência, grandes e permanentes pragas, e enfermidades malignas e duradouras;

[[v5-28-60]]

^<<v5-28-60,60>>^ E fará tornar sobre ti todos os males do Egito, de que tu tiveste temor, e se apegarão a ti.

[[v5-28-61]]

^<<v5-28-61,61>>^ Também o Senhor fará vir sobre ti toda a enfermidade e toda a praga, que não está escrita no livro desta lei, até que sejas destruído.

[[v5-28-62]]

^<<v5-28-62,62>>^ E ficareis poucos em número, em lugar de haverem sido como as estrelas dos céus em multidão; porquanto não destes ouvidos à voz do Senhor teu Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ E será que, assim como o Senhor se deleitava em vós, em fazer-vos bem e multiplicar-vos, assim o Senhor se deleitará em destruir-vos e consumir-vos; e desarraigados sereis da terra a qual passais a possuir.

[[v5-28-64]]

^<<v5-28-64,64>>^ E o Senhor vos espalhará entre todos os povos, desde uma extremidade da terra até à outra; e ali servireis a outros deuses que não conheceste, nem tu nem teus pais; ao pau e à pedra.

[[v5-28-65]]

^<<v5-28-65,65>>^ E nem ainda entre estas nações descansarás, nem a planta de teu pé terá repouso; porquanto o Senhor ali te dará coração agitado, e desfalecimento de olhos, e desmaio da alma.

[[v5-28-66]]

^<<v5-28-66,66>>^ E a tua vida, como em suspenso, estará diante de ti; e estremecerás de noite e de dia, e não crerás na tua própria vida.

[[v5-28-67]]

^<<v5-28-67,67>>^ Pela manhã dirás: Ah! quem me dera ver a noite! E à tarde dirás: ah! quem me dera ver a manhã! pelo pasmo de teu coração, que sentirás, e pelo que verás com os teus olhos.

[[v5-28-68]]

^<<v5-28-68,68>>^ E o Senhor te fará voltar ao Egito em navios, pelo caminho de que te tenho dito; nunca jamais o verás; e ali sereis vendidos como escravos e escravas aos vossos inimigos; mas não haverá quem vos compre.

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]