include::./index.adoc[]

[[v5-9-0]]
=== Deuteronômio, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-9-1]]

^<<v5-9-1,1>>^ Ouve, ó Israel, hoje passarás o Jordão, para entrares a possuir nações maiores e mais fortes do que tu; cidades grandes, e muradas até aos céus;

[[v5-9-2]]

^<<v5-9-2,2>>^ Um povo grande e alto, filhos de gigantes, que tu conheces, e de que já ouviste. Quem resistiria diante dos filhos dos gigantes?

[[v5-9-3]]

^<<v5-9-3,3>>^ Sabe, pois, hoje que o Senhor teu Deus, que passa adiante de ti, é um fogo consumidor, que os destruirá, e os derrubará de diante de ti; e tu os lançarás fora, e cedo os desfarás, como o Senhor te tem falado.

[[v5-9-4]]

^<<v5-9-4,4>>^ Quando, pois, o Senhor teu Deus os lançar fora de diante de ti, não fales no teu coração, dizendo: Por causa da minha justiça é que o Senhor me trouxe a esta terra para a possuir; porque pela impiedade destas nações é que o Senhor as lança fora de diante de ti.

[[v5-9-5]]

^<<v5-9-5,5>>^ Não é por causa da tua justiça, nem pela retidão do teu coração que entras a possuir a sua terra, mas pela impiedade destas nações o Senhor teu Deus as lança fora, de diante de ti, e para confirmar a palavra que o Senhor jurou a teus pais, Abraão, Isaque e Jacó.

[[v5-9-6]]

^<<v5-9-6,6>>^ Sabe, pois, que não é por causa da tua justiça que o Senhor teu Deus te dá esta boa terra para possuí-la, pois tu és povo obstinado.

[[v5-9-7]]

^<<v5-9-7,7>>^ Lembra-te, e não te esqueças, de que muito provocaste à ira ao Senhor teu Deus no deserto; desde o dia em que saístes do Egito, até que chegastes a esse lugar, rebeldes fostes contra o Senhor;

[[v5-9-8]]

^<<v5-9-8,8>>^ Pois em Horebe provocastes à ira o Senhor, tanto que o Senhor se indignou contra vós para vos destruir.

[[v5-9-9]]

^<<v5-9-9,9>>^ Subindo eu ao monte a receber as tábuas de pedra, as tábuas da aliança que o Senhor fizera convosco, então fiquei no monte quarenta dias e quarenta noites; pão não comi, e água não bebi;

[[v5-9-10]]

^<<v5-9-10,10>>^ E o Senhor me deu as duas tábuas de pedra, escritas com o dedo de Deus; e nelas estava escrito conforme a todas aquelas palavras que o Senhor tinha falado convosco no monte, do meio do fogo, no dia da assembléia.

[[v5-9-11]]

^<<v5-9-11,11>>^ Sucedeu, pois, que ao fim dos quarenta dias e quarenta noites, o Senhor me deu as duas tábuas de pedra, as tábuas da aliança.

[[v5-9-12]]

^<<v5-9-12,12>>^ E o Senhor me disse: Levanta-te, desce depressa daqui, porque o teu povo, que tiraste do Egito, já se tem corrompido; cedo se desviaram do caminho que eu lhes tinha ordenado; fizeram para si uma imagem de fundição.

[[v5-9-13]]

^<<v5-9-13,13>>^ Falou-me ainda o Senhor, dizendo: Atentei para este povo, e eis que ele é povo obstinado;

[[v5-9-14]]

^<<v5-9-14,14>>^ Deixa-me que os destrua, e apague o seu nome de debaixo dos céus; e te faça a ti nação mais poderosa e mais numerosa do que esta.

[[v5-9-15]]

^<<v5-9-15,15>>^ Então virei-me, e desci do monte; o qual ardia em fogo e as duas tábuas da aliança estavam em ambas as minhas mãos.

[[v5-9-16]]

^<<v5-9-16,16>>^ E olhei, e eis que havíeis pecado contra o Senhor vosso Deus; vós tínheis feito um bezerro de fundição; cedo vos desviastes do caminho que o Senhor vos ordenara.

[[v5-9-17]]

^<<v5-9-17,17>>^ Então peguei das duas tábuas, e as arrojei das minhas mãos, e as quebrei diante dos vossos olhos.

[[v5-9-18]]

^<<v5-9-18,18>>^ E me lancei perante o Senhor, como antes, quarenta dias, e quarenta noites; não comi pão e não bebi água, por causa de todo o vosso pecado que havíeis cometido, fazendo mal aos olhos do Senhor, para o provocar à ira.

[[v5-9-19]]

^<<v5-9-19,19>>^ Porque temi por causa da ira e do furor, com que o Senhor tanto estava irado contra vós para vos destruir; porém ainda por esta vez o Senhor me ouviu.

[[v5-9-20]]

^<<v5-9-20,20>>^ Também o Senhor se irou muito contra Arão para o destruir; mas também orei por Arão ao mesmo tempo.

[[v5-9-21]]

^<<v5-9-21,21>>^ Porém eu tomei o vosso pecado, o bezerro que tínheis feito, e o queimei a fogo, e o pisei, moendo-o bem, até que se desfez em pó; e o seu pó lancei no ribeiro que descia do monte.

[[v5-9-22]]

^<<v5-9-22,22>>^ Também em Taberá, e em Massá, e em Quibrote-Hataavá provocastes muito a ira do Senhor.

[[v5-9-23]]

^<<v5-9-23,23>>^ Quando também o Senhor vos enviou de Cades-Barnéia, dizendo: Subi, e possuí a terra, que vos tenho dado: rebeldes fostes ao mandado do Senhor vosso Deus, e não o crestes, e não obedecestes à sua voz.

[[v5-9-24]]

^<<v5-9-24,24>>^ Rebeldes fostes contra o Senhor desde o dia em que vos conheci.

[[v5-9-25]]

^<<v5-9-25,25>>^ E prostrei-me perante o Senhor; aqueles quarenta dias e quarenta noites estive prostrado, porquanto o Senhor dissera que vos queria destruir.

[[v5-9-26]]

^<<v5-9-26,26>>^ E orei ao SENHOR, dizendo: Senhor DEUS, não destruas o teu povo e a tua herança, que resgataste com a tua grandeza, que tiraste do Egito com mão forte.

[[v5-9-27]]

^<<v5-9-27,27>>^ Lembra-te dos teus servos, Abraão, Isaque, e Jacó. Não atentes para a dureza deste povo, nem para a sua impiedade, nem para o seu pecado;

[[v5-9-28]]

^<<v5-9-28,28>>^ Para que o povo da terra donde nos tiraste não diga: Porquanto o Senhor não os pôde introduzir na terra de que lhes tinha falado, e porque os odiava, os tirou para matá-los no deserto;

[[v5-9-29]]

^<<v5-9-29,29>>^ Todavia são eles o teu povo e a tua herança, que tiraste com a tua grande força e com o teu braço estendido.

'''

xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[Próximo Capítulo &#62;]