include::./index.adoc[]

[[v5-29-0]]
=== Deuteronômio, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-29-1]]

^<<v5-29-1,1>>^ Estas são as palavras da aliança que o SENHOR ordenou a Moisés que fizesse com os filhos de Israel, na terra de Moabe, além da aliança que fizera com eles em Horebe.

[[v5-29-2]]

^<<v5-29-2,2>>^ E chamou Moisés a todo o Israel, e disse-lhes: Tendes visto tudo quanto o Senhor fez perante vossos olhos, na terra do Egito, a Faraó, e a todos os seus servos, e a toda a sua terra;

[[v5-29-3]]

^<<v5-29-3,3>>^ As grandes provas que os teus olhos têm visto, aqueles sinais e grandes maravilhas;

[[v5-29-4]]

^<<v5-29-4,4>>^ Porém não vos tem dado o Senhor um coração para entender, nem olhos para ver, nem ouvidos para ouvir, até ao dia de hoje.

[[v5-29-5]]

^<<v5-29-5,5>>^ E quarenta anos vos fiz andar pelo deserto; não se envelheceram sobre vós as vossas vestes, e nem se envelheceu o vosso sapato no vosso pé.

[[v5-29-6]]

^<<v5-29-6,6>>^ Pão não comestes, e vinho e bebida forte não bebestes; para que soubésseis que eu sou o Senhor vosso Deus.

[[v5-29-7]]

^<<v5-29-7,7>>^ Vindo vós, pois, a este lugar, Siom, rei de Hesbom, e Ogue, rei de Basã, nos saíram ao encontro, à peleja, e nós os ferimos;

[[v5-29-8]]

^<<v5-29-8,8>>^ E tomamos a sua terra e a demos por herança aos rubenitas, e aos gaditas, e à meia tribo dos manassitas.

[[v5-29-9]]

^<<v5-29-9,9>>^ Guardai, pois, as palavras desta aliança, e cumpri-as, para que prospereis em tudo quanto fizerdes.

[[v5-29-10]]

^<<v5-29-10,10>>^ Vós todos estais hoje perante o Senhor vosso Deus; os capitães de vossas tribos, vossos anciãos, e os vossos oficiais, todos os homens de Israel;

[[v5-29-11]]

^<<v5-29-11,11>>^ Os vossos meninos, as vossas mulheres, e o estrangeiro que está no meio do vosso arraial; desde o rachador da vossa lenha até ao tirador da vossa água;

[[v5-29-12]]

^<<v5-29-12,12>>^ Para entrardes na aliança do Senhor teu Deus, e no seu juramento que o Senhor teu Deus hoje faz convosco;

[[v5-29-13]]

^<<v5-29-13,13>>^ Para que hoje te confirme por seu povo, e ele te seja por Deus, como te tem dito, e como jurou a teus pais, Abraão, Isaque e Jacó.

[[v5-29-14]]

^<<v5-29-14,14>>^ E não somente convosco faço esta aliança e este juramento;

[[v5-29-15]]

^<<v5-29-15,15>>^ Mas com aquele que hoje está aqui em pé conosco perante o Senhor nosso Deus, e com aquele que hoje não está aqui conosco.

[[v5-29-16]]

^<<v5-29-16,16>>^ Porque vós sabeis como habitamos na terra do Egito, e como passamos pelo meio das nações pelas quais passastes;

[[v5-29-17]]

^<<v5-29-17,17>>^ E vistes as suas abominações, e os seus ídolos, o pau e a pedra, a prata e o ouro que havia entre eles,

[[v5-29-18]]

^<<v5-29-18,18>>^ Para que entre vós não haja homem, nem mulher, nem família, nem tribo, cujo coração hoje se desvie do Senhor nosso Deus, para que vá servir aos deuses destas nações; para que entre vós não haja raiz que dê veneno e fel;

[[v5-29-19]]

^<<v5-29-19,19>>^ E aconteça que, alguém ouvindo as palavras desta maldição, se abençoe no seu coração, dizendo: Terei paz, ainda que ande conforme o parecer do meu coração; para acrescentar à sede a bebedeira.

[[v5-29-20]]

^<<v5-29-20,20>>^ O Senhor não lhe quererá perdoar; mas fumegará a ira do Senhor e o seu zelo contra esse homem, e toda a maldição escrita neste livro pousará sobre ele; e o Senhor apagará o seu nome de debaixo do céu.

[[v5-29-21]]

^<<v5-29-21,21>>^ E o Senhor o separará para mal, de todas as tribos de Israel, conforme a todas as maldições da aliança escrita no livro desta lei.

[[v5-29-22]]

^<<v5-29-22,22>>^ Então dirá à geração vindoura, os vossos filhos, que se levantarem depois de vós, e o estrangeiro que virá de terras remotas, vendo as pragas desta terra, e as suas doenças, com que o Senhor a terá afligido;

[[v5-29-23]]

^<<v5-29-23,23>>^ E toda a sua terra abrasada com enxofre, e sal, de sorte que não será semeada, e nada produzirá, nem nela crescerá erva alguma; assim como foi a destruição de Sodoma e de Gomorra, de Admá e de Zeboim, que o Senhor destruiu na sua ira e no seu furor.

[[v5-29-24]]

^<<v5-29-24,24>>^ E todas as nações dirão: Por que fez o Senhor assim com esta terra? Qual foi a causa do furor desta tão grande ira?

[[v5-29-25]]

^<<v5-29-25,25>>^ Então se dirá: Porquanto deixaram a aliança do Senhor Deus de seus pais, que com eles tinha feito, quando os tirou do Egito;

[[v5-29-26]]

^<<v5-29-26,26>>^ E foram, e serviram a outros deuses, e se inclinaram diante deles; deuses que eles não conheceram, e nenhum dos quais lhes tinha sido dado.

[[v5-29-27]]

^<<v5-29-27,27>>^ Por isso a ira do Senhor se acendeu contra esta terra, para trazer sobre ela toda a maldição que está escrita neste livro.

[[v5-29-28]]

^<<v5-29-28,28>>^ E o Senhor os arrancou da sua terra com ira, e com indignação, e com grande furor, e os lançou em outra terra como neste dia se vê.

[[v5-29-29]]

^<<v5-29-29,29>>^ As coisas encobertas pertencem ao Senhor nosso Deus, porém as reveladas nos pertencem a nós e a nossos filhos para sempre, para que cumpramos todas as palavras desta lei.

'''

xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[&#60; Capítulo Anterior] | <<v5-29-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[Próximo Capítulo &#62;]