include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-8-1]]

^<<v5-8-1,1>>^ Todos os mandamentos que hoje vos ordeno guardareis para os cumprir; para que vivais, e vos multipliqueis, e entreis, e possuais a terra que o SENHOR jurou a vossos pais.

[[v5-8-2]]

^<<v5-8-2,2>>^ E te lembrarás de todo o caminho, pelo qual o Senhor teu Deus te guiou no deserto estes quarenta anos, para te humilhar, e te provar, para saber o que estava no teu coração, se guardarias os seus mandamentos, ou não.

[[v5-8-3]]

^<<v5-8-3,3>>^ E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram; para te dar a entender que o homem não viverá só de pão, mas de tudo o que sai da boca do Senhor viverá o homem.

[[v5-8-4]]

^<<v5-8-4,4>>^ Nunca se envelheceu a tua roupa sobre ti, nem se inchou o teu pé nestes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ Sabes, pois, no teu coração que, como um homem castiga a seu filho, assim te castiga o Senhor teu Deus.

[[v5-8-6]]

^<<v5-8-6,6>>^ E guarda os mandamentos do Senhor teu Deus, para andares nos seus caminhos e para o temeres.

[[v5-8-7]]

^<<v5-8-7,7>>^ Porque o Senhor teu Deus te põe numa boa terra, terra de ribeiros de águas, de fontes, e de mananciais, que saem dos vales e das montanhas;

[[v5-8-8]]

^<<v5-8-8,8>>^ Terra de trigo e cevada, e de vides e figueiras, e romeiras; terra de oliveiras, de azeite e mel.

[[v5-8-9]]

^<<v5-8-9,9>>^ Terra em que comerás o pão sem escassez, e nada te faltará nela; terra cujas pedras são ferro, e de cujos montes tu cavarás o cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ Quando, pois, tiveres comido, e fores farto, louvarás ao Senhor teu Deus pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te que não te esqueças do Senhor teu Deus, deixando de guardar os seus mandamentos, e os seus juízos, e os seus estatutos que hoje te ordeno;

[[v5-8-12]]

^<<v5-8-12,12>>^ Para não suceder que, havendo tu comido e fores farto, e havendo edificado boas casas, e habitando-as,

[[v5-8-13]]

^<<v5-8-13,13>>^ E se tiverem aumentado os teus gados e os teus rebanhos, e se acrescentar a prata e o ouro, e se multiplicar tudo quanto tens,

[[v5-8-14]]

^<<v5-8-14,14>>^ Se eleve o teu coração e te esqueças do Senhor teu Deus, que te tirou da terra do Egito, da casa da servidão;

[[v5-8-15]]

^<<v5-8-15,15>>^ Que te guiou por aquele grande e terrível deserto de serpentes ardentes, e de escorpiões, e de terra seca, em que não havia água; e tirou água para ti da rocha pederneira;

[[v5-8-16]]

^<<v5-8-16,16>>^ Que no deserto te sustentou com maná, que teus pais não conheceram; para te humilhar, e para te provar, para no fim te fazer bem;

[[v5-8-17]]

^<<v5-8-17,17>>^ E digas no teu coração: A minha força, e a fortaleza da minha mão, me adquiriu este poder.

[[v5-8-18]]

^<<v5-8-18,18>>^ Antes te lembrarás do Senhor teu Deus, que ele é o que te dá força para adquirires riqueza; para confirmar a sua aliança, que jurou a teus pais, como se vê neste dia.

[[v5-8-19]]

^<<v5-8-19,19>>^ Será, porém, que, se de qualquer modo te esqueceres do Senhor teu Deus, e se ouvires outros deuses, e os servires, e te inclinares perante eles, hoje eu testifico contra vós que certamente perecereis.

[[v5-8-20]]

^<<v5-8-20,20>>^ Como as nações que o Senhor destruiu diante de vós, assim vós perecereis, porquanto não queríeis obedecer à voz do Senhor vosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]