include::./index.adoc[]

[[v5-34-0]]
=== Deuteronômio, 34
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-34-1]]

^<<v5-34-1,1>>^ Então subiu Moisés das campinas de Moabe ao monte Nebo, ao cume de Pisga, que está em frente a Jericó e o SENHOR mostrou-lhe toda a terra desde Gileade até Dã;

[[v5-34-2]]

^<<v5-34-2,2>>^ E todo Naftali, e a terra de Efraim, e Manassés e toda a terra de Judá, até ao mar ocidental;

[[v5-34-3]]

^<<v5-34-3,3>>^ E o sul, e a campina do vale de Jericó, a cidade das palmeiras, até Zoar.

[[v5-34-4]]

^<<v5-34-4,4>>^ E disse-lhe o Senhor: Esta é a terra que jurei a Abraão, Isaque, e Jacó, dizendo: À tua descendência a darei; eu te faço vê-la com os teus olhos, porém lá não passarás.

[[v5-34-5]]

^<<v5-34-5,5>>^ Assim morreu ali Moisés, servo do Senhor, na terra de Moabe, conforme a palavra do Senhor.

[[v5-34-6]]

^<<v5-34-6,6>>^ E o sepultou num vale, na terra de Moabe, em frente de Bete-Peor; e ninguém soube até hoje o lugar da sua sepultura.

[[v5-34-7]]

^<<v5-34-7,7>>^ Era Moisés da idade de cento e vinte anos quando morreu; os seus olhos nunca se escureceram, nem perdeu o seu vigor.

[[v5-34-8]]

^<<v5-34-8,8>>^ E os filhos de Israel prantearam a Moisés trinta dias, nas campinas de Moabe; e os dias do pranto no luto de Moisés se cumpriram.

[[v5-34-9]]

^<<v5-34-9,9>>^ E Josué, filho de Num, foi cheio do espírito de sabedoria, porquanto Moisés tinha posto sobre ele as suas mãos; assim os filhos de Israel lhe deram ouvidos, e fizeram como o Senhor ordenara a Moisés.

[[v5-34-10]]

^<<v5-34-10,10>>^ E nunca mais se levantou em Israel profeta algum como Moisés, a quem o Senhor conhecera face a face;

[[v5-34-11]]

^<<v5-34-11,11>>^ Nem semelhante em todos os sinais e maravilhas, que o Senhor o enviou para fazer na terra do Egito, a Faraó, e a todos os seus servos, e a toda a sua terra.

[[v5-34-12]]

^<<v5-34-12,12>>^ E em toda a mão forte, e em todo o grande espanto, que praticou Moisés aos olhos de todo o Israel.

'''

xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[&#60; Capítulo Anterior] | <<v5-34-0,Topo>> | xref:006-josue/006-josue-001.adoc#v6-1-0[Próximo Capítulo &#62;]