include::./index.adoc[]

[[v5-18-0]]
=== Deuteronômio, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-18-1]]

^<<v5-18-1,1>>^ Os sacerdotes levitas, toda a tribo de Levi, não terão parte nem herança com Israel; das ofertas queimadas do SENHOR e da sua herança comerão.

[[v5-18-2]]

^<<v5-18-2,2>>^ Por isso não terão herança no meio de seus irmãos; o Senhor é a sua herança, como lhes tem dito.

[[v5-18-3]]

^<<v5-18-3,3>>^ Este, pois, será o direito dos sacerdotes, a receber do povo, dos que oferecerem sacrifício, seja boi ou gado miúdo; que darão ao sacerdote a espádua e as queixadas e o bucho.

[[v5-18-4]]

^<<v5-18-4,4>>^ Dar-lhe-ás as primícias do teu grão, do teu mosto e do teu azeite, e as primícias da tosquia das tuas ovelhas.

[[v5-18-5]]

^<<v5-18-5,5>>^ Porque o Senhor teu Deus o escolheu de todas as tuas tribos, para que assista e sirva no nome do Senhor, ele e seus filhos, todos os dias.

[[v5-18-6]]

^<<v5-18-6,6>>^ E, quando chegar um levita de alguma das tuas portas, de todo o Israel, onde habitar; e vier com todo o desejo da sua alma ao lugar que o Senhor escolheu;

[[v5-18-7]]

^<<v5-18-7,7>>^ E servir no nome do Senhor seu Deus, como também todos os seus irmãos, os levitas, que assistem ali perante o Senhor,

[[v5-18-8]]

^<<v5-18-8,8>>^ Igual porção comerão, além das vendas do seu patrimônio.

[[v5-18-9]]

^<<v5-18-9,9>>^ Quando entrares na terra que o Senhor teu Deus te der, não aprenderás a fazer conforme as abominações daquelas nações.

[[v5-18-10]]

^<<v5-18-10,10>>^ Entre ti não se achará quem faça passar pelo fogo a seu filho ou a sua filha, nem adivinhador, nem prognosticador, nem agoureiro, nem feiticeiro;

[[v5-18-11]]

^<<v5-18-11,11>>^ Nem encantador, nem quem consulte a um espírito adivinhador, nem mágico, nem quem consulte os mortos;

[[v5-18-12]]

^<<v5-18-12,12>>^ Pois todo aquele que faz tal coisa é abominação ao Senhor; e por estas abominações o Senhor teu Deus os lança fora de diante de ti.

[[v5-18-13]]

^<<v5-18-13,13>>^ Perfeito serás, como o Senhor teu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ Porque estas nações, que hás de possuir, ouvem os prognosticadores e os adivinhadores; porém a ti o Senhor teu Deus não permitiu tal coisa.

[[v5-18-15]]

^<<v5-18-15,15>>^ O Senhor teu Deus te levantará um profeta do meio de ti, de teus irmãos, como eu; a ele ouvireis;

[[v5-18-16]]

^<<v5-18-16,16>>^ Conforme a tudo o que pediste ao Senhor teu Deus em Horebe, no dia da assembléia, dizendo: Não ouvirei mais a voz do Senhor teu Deus, nem mais verei este grande fogo, para que não morra.

[[v5-18-17]]

^<<v5-18-17,17>>^ Então o Senhor me disse: Falaram bem naquilo que disseram.

[[v5-18-18]]

^<<v5-18-18,18>>^ Eis lhes suscitarei um profeta do meio de seus irmãos, como tu, e porei as minhas palavras na sua boca, e ele lhes falará tudo o que eu lhe ordenar.

[[v5-18-19]]

^<<v5-18-19,19>>^ E será que qualquer que não ouvir as minhas palavras, que ele falar em meu nome, eu o requererei dele.

[[v5-18-20]]

^<<v5-18-20,20>>^ Porém o profeta que tiver a presunção de falar alguma palavra em meu nome, que eu não lhe tenha mandado falar, ou o que falar em nome de outros deuses, esse profeta morrerá.

[[v5-18-21]]

^<<v5-18-21,21>>^ E, se disseres no teu coração: Como conhecerei a palavra que o Senhor não falou?

[[v5-18-22]]

^<<v5-18-22,22>>^ Quando o profeta falar em nome do Senhor, e essa palavra não se cumprir, nem suceder assim; esta é palavra que o Senhor não falou; com soberba a falou aquele profeta; não tenhas temor dele.

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]