include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta, porém, é a bênção com que Moisés, homem de Deus, abençoou os filhos de Israel antes da sua morte.

[[v5-33-2]]

^<<v5-33-2,2>>^ Disse pois: O Senhor veio de Sinai, e lhes subiu de Seir; resplandeceu desde o monte Parã, e veio com dez milhares de santos; à sua direita havia para eles o fogo da lei.

[[v5-33-3]]

^<<v5-33-3,3>>^ Na verdade ama os povos; todos os seus santos estão na sua mão; postos serão no meio, entre os teus pés, e cada um receberá das tuas palavras.

[[v5-33-4]]

^<<v5-33-4,4>>^ Moisés nos deu a lei, como herança da congregação de Jacó.

[[v5-33-5]]

^<<v5-33-5,5>>^ E foi rei em Jesurum, quando se congregaram os cabeças do povo com as tribos de Israel.

[[v5-33-6]]

^<<v5-33-6,6>>^ Viva Rúben, e não morra, e que os seus homens não sejam poucos.

[[v5-33-7]]

^<<v5-33-7,7>>^ E isto é o que disse de Judá: Ouve, ó Senhor, a voz de Judá, e introduze-o no seu povo; as suas mãos lhe bastem, e tu lhe sejas em ajuda contra os seus inimigos.

[[v5-33-8]]

^<<v5-33-8,8>>^ E de Levi disse: Teu Tumim e teu Urim são para o teu amado, que tu provaste em Massá, com quem contendeste junto às águas de Meribá.

[[v5-33-9]]

^<<v5-33-9,9>>^ Aquele que disse a seu pai, e à sua mãe: Nunca os vi; e não conheceu a seus irmãos, e não estimou a seus filhos; pois guardaram a tua palavra e observaram a tua aliança.

[[v5-33-10]]

^<<v5-33-10,10>>^ Ensinaram os teus juízos a Jacó, e a tua lei a Israel; puseram incenso no teu nariz, e o holocausto sobre o teu altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa o seu poder, ó Senhor, e aceita a obra das suas mãos; fere os lombos dos que se levantam contra ele e o odeiam, para que nunca mais se levantem.

[[v5-33-12]]

^<<v5-33-12,12>>^ E de Benjamim disse: O amado do Senhor habitará seguro com ele; todo o dia o cobrirá, e morará entre os seus ombros.

[[v5-33-13]]

^<<v5-33-13,13>>^ E de José disse: Bendita do Senhor seja a sua terra, com o mais excelente dos céus, com o orvalho e com o abismo que jaz abaixo.

[[v5-33-14]]

^<<v5-33-14,14>>^ E com os mais excelentes frutos do sol, e com as mais excelentes produções das luas,

[[v5-33-15]]

^<<v5-33-15,15>>^ E com o mais excelente dos montes antigos, e com o mais excelente dos outeiros eternos.

[[v5-33-16]]

^<<v5-33-16,16>>^ E com o mais excelente da terra, e da sua plenitude, e com a benevolência daquele que habitava na sarça, venha sobre a cabeça de José, e sobre o alto da cabeça daquele que foi separado de seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ Ele tem a glória do primogênito do seu touro, e os seus chifres são chifres de boi selvagem; com eles rechaçará todos os povos até às extremidades da terra; estes pois são os dez milhares de Efraim, e estes são os milhares de Manassés.

[[v5-33-18]]

^<<v5-33-18,18>>^ E de Zebulom disse: Zebulom, alegra-te nas tuas saídas; e tu, Issacar, nas tuas tendas.

[[v5-33-19]]

^<<v5-33-19,19>>^ Eles chamarão os povos ao monte; ali apresentarão ofertas de justiça, porque chuparão a abundância dos mares e os tesouros escondidos da areia.

[[v5-33-20]]

^<<v5-33-20,20>>^ E de Gade disse: Bendito aquele que faz dilatar a Gade; habita como a leoa, e despedaça o braço e o alto da cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ E se proveu da melhor parte, porquanto ali estava escondida a porção do legislador; por isso veio com os chefes do povo, executou a justiça do Senhor e os seus juízos para com Israel.

[[v5-33-22]]

^<<v5-33-22,22>>^ E de Dã disse: Dã é cria de leão; que salta de Basã.

[[v5-33-23]]

^<<v5-33-23,23>>^ E de Naftali disse: Farta-te, ó Naftali, da benevolência, e enche-te da bênção do Senhor; possui o ocidente e o sul.

[[v5-33-24]]

^<<v5-33-24,24>>^ E de Aser disse: Bendito seja Aser com seus filhos; agrade a seus irmãos, e banhe em azeite o seu pé.

[[v5-33-25]]

^<<v5-33-25,25>>^ Seja de ferro e de metal o teu calçado; e a tua força seja como os teus dias.

[[v5-33-26]]

^<<v5-33-26,26>>^ Não há outro, ó Jesurum, semelhante a Deus, que cavalga sobre os céus para a tua ajuda, e com a sua majestade sobre as mais altas nuvens.

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus eterno é a tua habitação, e por baixo estão os braços eternos; e ele lançará o inimigo de diante de ti, e dirá: Destrói-o.

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel, pois, habitará só, seguro, na terra da fonte de Jacó, na terra de grão e de mosto; e os seus céus gotejarão orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Bem-aventurado tu, ó Israel! Quem é como tu? Um povo salvo pelo Senhor, o escudo do teu socorro, e a espada da tua majestade; por isso os teus inimigos te serão sujeitos, e tu pisarás sobre as suas alturas.

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]