include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// acf ?, ACF - Almeida Corrigida Fiel

[[v5-19-1]]

^<<v5-19-1,1>>^ Quando o SENHOR teu Deus desarraigar as nações cuja terra te dará o SENHOR teu Deus, e tu as possuíres, e morares nas suas cidades e nas suas casas,

[[v5-19-2]]

^<<v5-19-2,2>>^ Três cidades separarás, no meio da terra que te dará o Senhor teu Deus para a possuíres.

[[v5-19-3]]

^<<v5-19-3,3>>^ Preparar-te-ás o caminho; e os termos da tua terra, que te fará possuir o Senhor teu Deus, dividirás em três; e isto será para que todo o homicida se acolha ali.

[[v5-19-4]]

^<<v5-19-4,4>>^ E este é o caso tocante ao homicida, que se acolher ali, para que viva; aquele que por engano ferir o seu próximo, a quem não odiava antes;

[[v5-19-5]]

^<<v5-19-5,5>>^ Como aquele que entrar com o seu próximo no bosque, para cortar lenha, e, pondo força na sua mão com o machado para cortar a árvore, o ferro saltar do cabo e ferir o seu próximo e este morrer, aquele se acolherá a uma destas cidades, e viverá;

[[v5-19-6]]

^<<v5-19-6,6>>^ Para que o vingador do sangue não vá após o homicida, quando se enfurecer o seu coração, e o alcançar, por ser comprido o caminho, e lhe tire a vida; porque não é culpado de morte, pois o não odiava antes.

[[v5-19-7]]

^<<v5-19-7,7>>^ Portanto te dou ordem, dizendo: Três cidades separarás.

[[v5-19-8]]

^<<v5-19-8,8>>^ E, se o Senhor teu Deus dilatar os teus termos, como jurou a teus pais, e te der toda a terra que disse daria a teus pais

[[v5-19-9]]

^<<v5-19-9,9>>^ (Quando guardares todos estes mandamentos, que hoje te ordeno, para cumprí-los, amando ao Senhor teu Deus e andando nos seus caminhos todos os dias), então acrescentarás outras três cidades além destas três.

[[v5-19-10]]

^<<v5-19-10,10>>^ Para que o sangue inocente não se derrame no meio da tua terra, que o Senhor teu Deus te dá por herança, e haja sangue sobre ti.

[[v5-19-11]]

^<<v5-19-11,11>>^ Mas, havendo alguém que odeia a seu próximo, e lhe arma ciladas, e se levanta contra ele, e o fere mortalmente, e se acolhe a alguma destas cidades,

[[v5-19-12]]

^<<v5-19-12,12>>^ Então os anciãos da sua cidade mandarão buscá-lo; e dali o tirarão, e o entregarão na mão do vingador do sangue, para que morra.

[[v5-19-13]]

^<<v5-19-13,13>>^ O teu olho não o perdoará; antes tirarás o sangue inocente de Israel, para que bem te suceda.

[[v5-19-14]]

^<<v5-19-14,14>>^ Não mudes o limite do teu próximo, que estabeleceram os antigos na tua herança, que receberás na terra que te dá o Senhor teu Deus para a possuíres.

[[v5-19-15]]

^<<v5-19-15,15>>^ Uma só testemunha contra alguém não se levantará por qualquer iniqüidade, ou por qualquer pecado, seja qual for o pecado que cometeu; pela boca de duas testemunhas, ou pela boca de três testemunhas, se estabelecerá o fato.

[[v5-19-16]]

^<<v5-19-16,16>>^ Quando se levantar testemunha falsa contra alguém, para testificar contra ele acerca de transgressão,

[[v5-19-17]]

^<<v5-19-17,17>>^ Então aqueles dois homens, que tiverem a demanda, se apresentarão perante o Senhor, diante dos sacerdotes e dos juízes que houver naqueles dias.

[[v5-19-18]]

^<<v5-19-18,18>>^ E os juízes inquirirão bem; e eis que, sendo a testemunha falsa, que testificou falsamente contra seu irmão,

[[v5-19-19]]

^<<v5-19-19,19>>^ Far-lhe-eis como cuidou fazer a seu irmão; e assim tirarás o mal do meio de ti.

[[v5-19-20]]

^<<v5-19-20,20>>^ Para que os que ficarem o ouçam e temam, e nunca mais tornem a fazer tal mal no meio de ti.

[[v5-19-21]]

^<<v5-19-21,21>>^ O teu olho não perdoará; vida por vida, olho por olho, dente por dente, mão por mão, pé por pé.

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]