include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v34-2-1]]

^<<v34-2-1,1>>^ O destruidor subiu contra ti. Guarda tu a fortaleza, vigia o caminho, fortalece os lombos, reforça muito o teu poder.

[[v34-2-2]]

^<<v34-2-2,2>>^ Porque o Senhor restaurará a excelência de Jacó como a excelência de Israel; porque os saqueadores os despojaram, e destruíram os seus sarmentos.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os escudos dos seus fortes serão vermelhos, os homens valorosos estarão vestidos de escarlate, os carros como tochas flamejantes no dia da sua preparação, e os ciprestes serão terrivelmente abalados.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os carros correrão furiosamente nas ruas, colidirão um contra o outro nos largos caminhos; o seu aspecto será como o de tochas, correrão como relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ Ele se lembrará dos seus valentes; eles, porém, tropeçarão na sua marcha; apressar-se-ão para chegar ao seu muro, quando o amparo for preparado.

[[v34-2-6]]

^<<v34-2-6,6>>^ As portas dos rios se abrirão, e o palácio será dissolvido.

[[v34-2-7]]

^<<v34-2-7,7>>^ É decretado: ela será levada cativa, conduzida para cima; e as suas servas a acompanharão, gemendo como pombas, batendo em seus peitos.

[[v34-2-8]]

^<<v34-2-8,8>>^ Nínive desde que existiu tem sido como um tanque de águas, porém elas agora vazam. Parai, parai, clamar-se-á; mas ninguém olhará para trás.

[[v34-2-9]]

^<<v34-2-9,9>>^ Saqueai a prata, saqueai o ouro, porque não têm fim as provi-sões, riquezas há de todo o gênero de bens desejáveis.

[[v34-2-10]]

^<<v34-2-10,10>>^ Vazia, esgotada e devastada está; derrete-se o coração, e tremem os joelhos, e em todos os lombos há dor, e os rostos de todos eles se enegrecem.

[[v34-2-11]]

^<<v34-2-11,11>>^ Onde está agora o covil dos leões, e as pastagens dos leõezinhos, onde passeava o leão velho, e o filhote do leão, sem haver ninguém que os espantasse?

[[v34-2-12]]

^<<v34-2-12,12>>^ O leão arrebatava o que bastava para os seus filhotes, e estrangulava a presa para as suas leoas, e enchia de presas as suas cavernas, e os seus covis de rapina.

[[v34-2-13]]

^<<v34-2-13,13>>^ Eis que eu estou contra ti, diz o Senhor dos Exércitos, e queimarei na fumaça os teus carros, e a espada devorará os teus leõezinhos, e arrancarei da terra a tua presa, e não se ouvirá mais a voz dos teus mensageiros.

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]