include::./index.adoc[]

[[v21-6-0]]
=== Eclesiastes, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v21-6-1]]

^<<v21-6-1,1>>^ Há um mal que tenho visto debaixo do sol, e é mui freqüente entre os homens:

[[v21-6-2]]

^<<v21-6-2,2>>^ Um homem a quem Deus deu riquezas, bens e honra, e nada lhe falta de tudo quanto a sua alma deseja, e Deus não lhe dá poder para daí comer, antes o estranho lho come; também isto é vaidade e má enfermidade.

[[v21-6-3]]

^<<v21-6-3,3>>^ Se o homem gerar cem filhos, e viver muitos anos, e os dias dos seus anos forem muitos, e se a sua alma não se fartar do bem, e além disso não tiver sepultura, digo que um aborto é melhor do que ele.

[[v21-6-4]]

^<<v21-6-4,4>>^ Porquanto debalde veio, e em trevas se vai, e de trevas se cobre o seu nome.

[[v21-6-5]]

^<<v21-6-5,5>>^ E ainda que nunca viu o sol, nem conheceu nada, mais descanso tem este do que aquele.

[[v21-6-6]]

^<<v21-6-6,6>>^ E, ainda que vivesse duas vezes mil anos e não gozasse o bem, não vão todos para um mesmo lugar?

[[v21-6-7]]

^<<v21-6-7,7>>^ Todo o trabalho do homem é para a sua boca, e contudo nunca se satisfaz o seu apetite.

[[v21-6-8]]

^<<v21-6-8,8>>^ Porque, que mais tem o sábio do que o tolo? E que mais tem o pobre que sabe andar perante os vivos?

[[v21-6-9]]

^<<v21-6-9,9>>^ Melhor é a vista dos olhos do que o vaguear da cobiça; também isto é vaidade e aflição de espírito.

[[v21-6-10]]

^<<v21-6-10,10>>^ Seja qualquer o que for, já o seu nome foi nomeado, e sabe-se que é homem, e que não pode contender com o que é mais forte do que ele.

[[v21-6-11]]

^<<v21-6-11,11>>^ Na verdade que há muitas coisas que multiplicam a vaidade; que mais tem o homem de melhor?

[[v21-6-12]]

^<<v21-6-12,12>>^ Pois, quem sabe o que é bom nesta vida para o homem, por todos os dias da sua vida de vaidade, os quais gasta como sombra? Quem declarará ao homem o que será depois dele debaixo do sol?

'''

xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[&#60; Capítulo Anterior] | <<v21-6-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[Próximo Capítulo &#62;]