include::./index.adoc[]

[[v21-8-0]]
=== Eclesiastes, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v21-8-1]]

^<<v21-8-1,1>>^ Quem é como o sábio? E quem sabe a interpretação das coisas? A sabedoria do homem faz brilhar o seu rosto, e a dureza do seu rosto se muda.

[[v21-8-2]]

^<<v21-8-2,2>>^ Eu digo: Observa o mandamento do rei, e isso em consideração ao juramento que fizeste a Deus.

[[v21-8-3]]

^<<v21-8-3,3>>^ Não te apresses a sair da presença dele, nem persistas em alguma coisa má, porque ele faz tudo o que quer.

[[v21-8-4]]

^<<v21-8-4,4>>^ Porque a palavra do rei tem poder; e quem lhe dirá: Que fazes?

[[v21-8-5]]

^<<v21-8-5,5>>^ Quem guardar o mandamento não experimentará nenhum mal; e o coração do sábio discernirá o tempo e o juízo.

[[v21-8-6]]

^<<v21-8-6,6>>^ Porque para todo o propósito há seu tempo e juízo; porquanto a miséria do homem pesa sobre ele.

[[v21-8-7]]

^<<v21-8-7,7>>^ Porque não sabe o que há de suceder, e quando há de ser, quem lho dará a entender?

[[v21-8-8]]

^<<v21-8-8,8>>^ Nenhum homem há que tenha domínio sobre o espírito, para o reter; nem tampouco tem ele poder sobre o dia da morte; como também não há licença nesta peleja; nem tampouco a impiedade livrará aos ímpios.

[[v21-8-9]]

^<<v21-8-9,9>>^ Tudo isto vi quando apliquei o meu coração a toda a obra que se faz debaixo do sol; tempo há em que um homem tem domínio sobre outro homem, para desgraça sua.

[[v21-8-10]]

^<<v21-8-10,10>>^ Assim também vi os ímpios, quando os sepultavam; e eles entravam, e saíam do lugar santo; e foram esquecidos na cidade, em que assim fizeram; também isso é vaidade.

[[v21-8-11]]

^<<v21-8-11,11>>^ Porquanto não se executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para fazer o mal.

[[v21-8-12]]

^<<v21-8-12,12>>^ Ainda que o pecador faça o mal cem vezes, e os dias se lhe prolonguem, contudo eu sei com certeza que bem sucede aos que temem a Deus, aos que temem diante dele.

[[v21-8-13]]

^<<v21-8-13,13>>^ Porém o ímpio não irá bem, e ele não prolongará os seus dias, que são como a sombra; porque ele não teme diante de Deus.

[[v21-8-14]]

^<<v21-8-14,14>>^ Ainda há outra vaidade que se faz sobre a terra: que há justos a quem sucede segundo as obras dos ímpios, e há ímpios a quem sucede segundo as obras dos justos. Digo que também isto é vaidade.

[[v21-8-15]]

^<<v21-8-15,15>>^ Então louvei eu a alegria, porquanto para o homem nada há melhor debaixo do sol do que comer, beber e alegrar-se; porque isso o acompanhará no seu trabalho nos dias da sua vida que Deus lhe dá debaixo do sol.

[[v21-8-16]]

^<<v21-8-16,16>>^ Aplicando eu o meu coração a conhecer a sabedoria, e a ver o trabalho que há sobre a terra (que nem de dia nem de noite vê o homem sono nos seus olhos);

[[v21-8-17]]

^<<v21-8-17,17>>^ Então vi toda a obra de Deus, que o homem não pode perceber, a obra que se faz debaixo do sol; por mais que trabalhe o homem para a descobrir, não a achará; e, ainda que diga o sábio que a conhece, nem por isso a poderá compreender.

'''

xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[&#60; Capítulo Anterior] | <<v21-8-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[Próximo Capítulo &#62;]