include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v21-2-1]]

^<<v21-2-1,1>>^ Disse eu no meu coração: Ora vem, eu te provarei com alegria; portanto goza o prazer; mas eis que também isso era vaidade.

[[v21-2-2]]

^<<v21-2-2,2>>^ Ao riso disse: Está doido; e da alegria: De que serve esta?

[[v21-2-3]]

^<<v21-2-3,3>>^ Busquei no meu coração como estimular com vinho a minha carne (regendo porém o meu coração com sabedoria), e entregar-me à loucura, até ver o que seria melhor que os filhos dos homens fizessem debaixo do céu durante o número dos dias de sua vida.

[[v21-2-4]]

^<<v21-2-4,4>>^ Fiz para mim obras magníficas; edifiquei para mim casas; plantei para mim vinhas.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz para mim hortas e jardins, e plantei neles árvores de toda a espécie de fruto.

[[v21-2-6]]

^<<v21-2-6,6>>^ Fiz para mim tanques de águas, para regar com eles o bosque em que reverdeciam as árvores.

[[v21-2-7]]

^<<v21-2-7,7>>^ Adquiri servos e servas, e tive servos nascidos em casa; também tive grandes possessões de gados e ovelhas, mais do que todos os que houve antes de mim em Jerusalém.

[[v21-2-8]]

^<<v21-2-8,8>>^ Amontoei também para mim prata e ouro, e tesouros dos reis e das províncias; provi-me de cantores e cantoras, e das delícias dos filhos dos homens; e de instrumentos de música de toda a espécie.

[[v21-2-9]]

^<<v21-2-9,9>>^ E fui engrandecido, e aumentei mais do que todos os que houve antes de mim em Jerusalém; perseverou também comigo a minha sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ E tudo quanto desejaram os meus olhos não lhes neguei, nem privei o meu coração de alegria alguma; mas o meu coração se alegrou por todo o meu trabalho, e esta foi a minha porção de todo o meu trabalho.

[[v21-2-11]]

^<<v21-2-11,11>>^ E olhei eu para todas as obras que fizeram as minhas mãos, como também para o trabalho que eu, trabalhando, tinha feito, e eis que tudo era vaidade e aflição de espírito, e que proveito nenhum havia debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então passei a contemplar a sabedoria, e a loucura e a estultícia. Pois que fará o homem que seguir ao rei? O mesmo que outros já fizeram.

[[v21-2-13]]

^<<v21-2-13,13>>^ Então vi eu que a sabedoria é mais excelente do que a estultícia, quanto a luz é mais excelente do que as trevas.

[[v21-2-14]]

^<<v21-2-14,14>>^ Os olhos do homem sábio estão na sua cabeça, mas o louco anda em trevas; então também entendi eu que o mesmo lhes sucede a ambos.

[[v21-2-15]]

^<<v21-2-15,15>>^ Assim eu disse no meu coração: Como acontece ao tolo, assim me sucederá a mim; por que então busquei eu mais a sabedoria? Então disse no meu coração que também isto era vaidade.

[[v21-2-16]]

^<<v21-2-16,16>>^ Porque nunca haverá mais lembrança do sábio do que do tolo; porquanto de tudo, nos dias futuros, total esquecimento haverá. E como morre o sábio, assim morre o tolo!

[[v21-2-17]]

^<<v21-2-17,17>>^ Por isso odiei esta vida, porque a obra que se faz debaixo do sol me era penosa; sim, tudo é vaidade e aflição de espírito.

[[v21-2-18]]

^<<v21-2-18,18>>^ Também eu odiei todo o meu trabalho, que realizei debaixo do sol, visto que eu havia de deixá-lo ao homem que viesse depois de mim.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem sabe se será sábio ou tolo? Todavia, se assenhoreará de todo o meu trabalho que realizei e em que me houve sabiamente debaixo do sol; também isto é vaidade.

[[v21-2-20]]

^<<v21-2-20,20>>^ Então eu me volvi e entreguei o meu coração ao desespero no tocante ao trabalho, o qual realizei debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Porque há homem cujo trabalho é feito com sabedoria, conhecimento, e destreza; contudo deixará o seu trabalho como porção de quem nele não trabalhou; também isto é vaidade e grande mal.

[[v21-2-22]]

^<<v21-2-22,22>>^ Porque, que mais tem o homem de todo o seu trabalho, e da aflição do seu coração, em que ele anda trabalhando debaixo do sol?

[[v21-2-23]]

^<<v21-2-23,23>>^ Porque todos os seus dias são dores, e a sua ocupação é aflição; até de noite não descansa o seu coração; também isto é vaidade.

[[v21-2-24]]

^<<v21-2-24,24>>^ Não há nada melhor para o homem do que comer e beber, e fazer com que sua alma goze do bem do seu trabalho. Também vi que isto vem da mão de Deus.

[[v21-2-25]]

^<<v21-2-25,25>>^ Pois quem pode comer, ou quem pode gozar melhor do que eu?

[[v21-2-26]]

^<<v21-2-26,26>>^ Porque ao homem que é bom diante dele, dá Deus sabedoria e conhecimento e alegria; mas ao pecador dá trabalho, para que ele ajunte, e amontoe, para dá-lo ao que é bom perante Deus. Também isto é vaidade e aflição de espírito.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]