include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v21-5-1]]

^<<v21-5-1,1>>^ Guarda o teu pé, quando entrares na casa de Deus; porque chegar-se para ouvir é melhor do que oferecer sacrifícios de tolos, pois não sabem que fazem mal.

[[v21-5-2]]

^<<v21-5-2,2>>^ Não te precipites com a tua boca, nem o teu coração se apresse a pronunciar palavra alguma diante de Deus; porque Deus está nos céus, e tu estás sobre a terra; assim sejam poucas as tuas palavras.

[[v21-5-3]]

^<<v21-5-3,3>>^ Porque, da muita ocupação vêm os sonhos, e a voz do tolo da multidão das palavras.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos; o que votares, paga-o.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é que não votes do que votares e não cumprires.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não consintas que a tua boca faça pecar a tua carne, nem digas diante do anjo que foi erro; por que razão se iraria Deus contra a tua voz, e destruiria a obra das tuas mãos?

[[v21-5-7]]

^<<v21-5-7,7>>^ Porque, como na multidão dos sonhos há vaidades, assim também nas muitas palavras; mas tu teme a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se vires em alguma província opressão do pobre, e violência do direito e da justiça, não te admires de tal procedimento; pois quem está altamente colocado tem superior que o vigia; e há mais altos do que eles.

[[v21-5-9]]

^<<v21-5-9,9>>^ O proveito da terra é para todos; até o rei se serve do campo.

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem amar o dinheiro jamais dele se fartará; e quem amar a abundância nunca se fartará da renda; também isto é vaidade.

[[v21-5-11]]

^<<v21-5-11,11>>^ Onde os bens se multiplicam, ali se multiplicam também os que deles comem; que mais proveito, pois, têm os seus donos do que os ver com os seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é o sono do trabalhador, quer coma pouco quer muito; mas a fartura do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Há um grave mal que vi debaixo do sol, e atrai enfermidades: as riquezas que os seus donos guardam para o seu próprio dano;

[[v21-5-14]]

^<<v21-5-14,14>>^ Porque as mesmas riquezas se perdem por qualquer má ventura, e havendo algum filho nada lhe fica na sua mão.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como saiu do ventre de sua mãe, assim nu tornará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão.

[[v21-5-16]]

^<<v21-5-16,16>>^ Assim que também isto é um grave mal que, justamente como veio, assim há de ir; e que proveito lhe vem de trabalhar para o vento,

[[v21-5-17]]

^<<v21-5-17,17>>^ E de haver comido todos os seus dias nas trevas, e de haver padecido muito enfado, e enfermidade, e furor?

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis aqui o que eu vi, uma boa e bela coisa: comer e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias de vida que Deus lhe deu, porque esta é a sua porção.

[[v21-5-19]]

^<<v21-5-19,19>>^ E a todo o homem, a quem Deus deu riquezas e bens, e lhe deu poder para delas comer e tomar a sua porção, e gozar do seu trabalho, isto é dom de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Porque não se lembrará muito dos dias da sua vida; porquanto Deus lhe enche de alegria o seu coração.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]