include::./index.adoc[]

[[v21-4-0]]
=== Eclesiastes, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v21-4-1]]

^<<v21-4-1,1>>^ Depois voltei-me, e atentei para todas as opressões que se fazem debaixo do sol; e eis que vi as lágrimas dos que foram oprimidos e dos que não têm consolador, e a força estava do lado dos seus opressores; mas eles não tinham consolador.

[[v21-4-2]]

^<<v21-4-2,2>>^ Por isso eu louvei os que já morreram, mais do que os que vivem ainda.

[[v21-4-3]]

^<<v21-4-3,3>>^ E melhor que uns e outros é aquele que ainda não é; que não viu as más obras que se fazem debaixo do sol.

[[v21-4-4]]

^<<v21-4-4,4>>^ Também vi eu que todo o trabalho, e toda a destreza em obras, traz ao homem a inveja do seu próximo. Também isto é vaidade e aflição de espírito.

[[v21-4-5]]

^<<v21-4-5,5>>^ O tolo cruza as suas mãos, e come a sua própria carne.

[[v21-4-6]]

^<<v21-4-6,6>>^ Melhor é a mão cheia com descanso do que ambas as mãos cheias com trabalho, e aflição de espírito.

[[v21-4-7]]

^<<v21-4-7,7>>^ Outra vez me voltei, e vi vaidade debaixo do sol.

[[v21-4-8]]

^<<v21-4-8,8>>^ Há um que é só, e não tem ninguém, nem tampouco filho nem irmão; e contudo não cessa do seu trabalho, e também seus olhos não se satisfazem com riqueza; nem diz: Para quem trabalho eu, privando a minha alma do bem? Também isto é vaidade e enfadonha ocupação.

[[v21-4-9]]

^<<v21-4-9,9>>^ Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.

[[v21-4-10]]

^<<v21-4-10,10>>^ Porque se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante.

[[v21-4-11]]

^<<v21-4-11,11>>^ Também, se dois dormirem juntos, eles se aquentarão; mas um só, como se aquentará?

[[v21-4-12]]

^<<v21-4-12,12>>^ E, se alguém prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa.

[[v21-4-13]]

^<<v21-4-13,13>>^ Melhor é a criança pobre e sábia do que o rei velho e insensato, que não se deixa mais admoestar.

[[v21-4-14]]

^<<v21-4-14,14>>^ Porque um sai do cárcere para reinar; enquanto outro, que nasceu em seu reino, torna-se pobre.

[[v21-4-15]]

^<<v21-4-15,15>>^ Vi a todos os viventes andarem debaixo do sol com a criança, a sucessora, que ficará no seu lugar.

[[v21-4-16]]

^<<v21-4-16,16>>^ Não tem fim todo o povo que foi antes dele; tampouco os que lhe sucederem se alegrarão dele. Na verdade que também isto é vaidade e aflição de espírito.

'''

xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[&#60; Capítulo Anterior] | <<v21-4-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[Próximo Capítulo &#62;]