include::./index.adoc[]

[[v6-18-0]]
=== Josué, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v6-18-1]]

^<<v6-18-1,1>>^ E Toda a congregação dos filhos de Israel se reuniu em Siló, e ali armaram a tenda da congregação, depois que a terra lhes foi sujeita.

[[v6-18-2]]

^<<v6-18-2,2>>^ E dentre os filhos de Israel ficaram sete tribos que ainda não tinham repartido a sua herança.

[[v6-18-3]]

^<<v6-18-3,3>>^ E disse Josué aos filhos de Israel: Até quando sereis negligentes em chegardes para possuir a terra que o Senhor Deus de vossos pais vos deu?

[[v6-18-4]]

^<<v6-18-4,4>>^ De cada tribo escolhei vós três homens, para que eu os envie, e eles se levantem e percorram a terra, e a demarquem segundo as suas heranças, e voltem a mim.

[[v6-18-5]]

^<<v6-18-5,5>>^ E dividi-la-ão em sete partes: Judá ficará no seu termo para o sul, e a casa de José ficará no seu termo para o norte.

[[v6-18-6]]

^<<v6-18-6,6>>^ E vós demarcareis a terra em sete partes, e me trareis a mim aqui descrita, para que eu aqui lance as sortes perante o Senhor nosso Deus,

[[v6-18-7]]

^<<v6-18-7,7>>^ Porquanto os levitas não têm parte no meio de vós, porque o sacerdócio do Senhor é a sua parte; e Gade, e Rúben, e a meia tribo de Manassés, receberam a sua herança além do Jordão para o oriente, a qual lhes deu Moisés, o servo do Senhor.

[[v6-18-8]]

^<<v6-18-8,8>>^ Então aqueles homens se levantaram e se foram; e Josué deu ordem aos que iam demarcar a terra, dizendo: Ide, e percorrei a terra, e demarcai-a, e então voltai a mim, e aqui vos lançarei as sortes perante o Senhor, em Siló.

[[v6-18-9]]

^<<v6-18-9,9>>^ Foram, pois, aqueles homens, e passaram pela terra, e a demarcaram, em sete partes segundo as cidades, descrevendo-a num livro; e voltaram a Josué, ao arraial em Siló.

[[v6-18-10]]

^<<v6-18-10,10>>^ Então Josué lhes lançou as sortes em Siló, perante o Senhor; e ali repartiu Josué a terra aos filhos de Israel, conforme às suas divisões.

[[v6-18-11]]

^<<v6-18-11,11>>^ E tirou a sorte da tribo dos filhos de Benjamim, segundo as suas famílias; e coube-lhe o termo da sua sorte entre os filhos de Judá e os filhos de José.

[[v6-18-12]]

^<<v6-18-12,12>>^ E o seu termo foi para o lado do norte, desde o Jordão; e sobe aquele termo ao lado de Jericó para o norte, e sobe pela montanha para o ocidente, terminando no deserto de Bete-Áven.

[[v6-18-13]]

^<<v6-18-13,13>>^ E dali passa este termo a Luz, ao lado de Luz (que é Betel), para o sul; e desce a Atarote-Adar, ao pé do monte que está do lado do sul de Bete-Horom de baixo;

[[v6-18-14]]

^<<v6-18-14,14>>^ E vai este termo e volta ao lado do ocidente para o sul do monte que está defronte de Bete-Horom, para o sul, terminando em Quiriate-Baal (que é Quiriate-Jearim), cidade dos filhos de Judá; esta é a sua extensão para o ocidente.

[[v6-18-15]]

^<<v6-18-15,15>>^ E a sua extensão para o sul começa na extremidade de Quiriate-Jearim; e vai este termo ao ocidente e segue até à fonte das águas de Neftoa.

[[v6-18-16]]

^<<v6-18-16,16>>^ E desce este termo até à extremidade do monte que está defronte do vale do filho de Hinom, que está no vale dos refains para o norte, e desce pelo vale de Hinom do lado dos jebuseus para o sul; e então desce a En-Rogel;

[[v6-18-17]]

^<<v6-18-17,17>>^ E vai desde o norte, e chega a En-Semes; e dali sai a Gelilote, que está defronte da subida de Adumim, e desce à pedra de Boã, filho de Rúben;

[[v6-18-18]]

^<<v6-18-18,18>>^ E passa até ao lado, defronte de Arabá, para o norte, e desce a Arabá.

[[v6-18-19]]

^<<v6-18-19,19>>^ Passa mais este termo até ao lado de Bete-Hogla, para o norte, saindo esse termo na baía do Mar Salgado, para o norte, na extremidade do Jordão, para o sul; este é o termo do sul.

[[v6-18-20]]

^<<v6-18-20,20>>^ E o Jordão será seu termo do lado do oriente; esta é a herança dos filhos de Benjamim, nos seus termos em redor, segundo as suas famílias.

[[v6-18-21]]

^<<v6-18-21,21>>^ E as cidades da tribo dos filhos de Benjamim, segundo as suas famílias, são: Jericó, e Bete-Hogla, e Emeque-Queziz,

[[v6-18-22]]

^<<v6-18-22,22>>^ E Bete-Arabá, e Zemaraim, e Betel,

[[v6-18-23]]

^<<v6-18-23,23>>^ E Avim, e Pará, e Ofra,

[[v6-18-24]]

^<<v6-18-24,24>>^ E Quefar-Amonai, e Ofni e Gaba: doze cidades e as suas aldeias;

[[v6-18-25]]

^<<v6-18-25,25>>^ Gibeão, e Ramá e Beerote,

[[v6-18-26]]

^<<v6-18-26,26>>^ E Mizpá, e Cefira e Moza,

[[v6-18-27]]

^<<v6-18-27,27>>^ E Requém e Irpeel, e Tarala,

[[v6-18-28]]

^<<v6-18-28,28>>^ E Zela, Elefe, e Jebus (esta é Jerusalém), Gibeá e Quiriate: catorze cidades com as suas aldeias; esta é a herança dos filhos de Benjamim, segundo as suas famílias.

'''

xref:006-josue/006-josue-017.adoc#v6-17-0[&#60; Capítulo Anterior] | <<v6-18-0,Topo>> | xref:006-josue/006-josue-019.adoc#v6-19-0[Próximo Capítulo &#62;]