include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// acf ?, ACF - Almeida Corrigida Fiel

[[v6-17-1]]

^<<v6-17-1,1>>^ Também coube sorte à tribo de Manassés, porquanto era o primogênito de José. Maquir, o primogênito de Manassés, pai de Gileade, porquanto era homem de guerra, teve a Gileade e Basã;

[[v6-17-2]]

^<<v6-17-2,2>>^ Também os demais filhos de Manassés tiveram a sua parte, segundo as suas famílias, a saber: Os filhos de Abiezer, e os filhos de Heleque, e os filhos de Asriel, e os filhos de Siquém, e os filhos de Hefer, e os filhos de Semida; esses são os filhos de Manassés, filho de José, segundo as suas famílias.

[[v6-17-3]]

^<<v6-17-3,3>>^ Zelofeade, porém, filho de Hefer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, mas só filhas; e estes são os nomes de suas filhas: Maalá, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Estas, pois, chegaram diante de Eleazar, o sacerdote, e diante de Josué, filho de Num, e diante dos príncipes, dizendo: O Senhor ordenou a Moisés que se nos desse herança no meio de nossos irmãos, pelo que, conforme a ordem do Senhor, lhes deu herança no meio dos irmãos de seu pai.

[[v6-17-5]]

^<<v6-17-5,5>>^ E couberam a Manassés dez quinhões, afora a terra de Gileade e Basã, que está além do Jordão;

[[v6-17-6]]

^<<v6-17-6,6>>^ Porque as filhas de Manassés receberam herança entre os filhos dele; e os outros filhos de Manassés ficaram com a terra de Gileade.

[[v6-17-7]]

^<<v6-17-7,7>>^ E o termo de Manassés foi desde Aser até Micmetá, que está defronte de Siquém; e estende-se este termo à direita até os moradores de En-Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ Tinha Manassés a terra de Tapua; porém Tapua, junto ao termo de Manassés, pertencia aos filhos de Efraim.

[[v6-17-9]]

^<<v6-17-9,9>>^ Então descia este termo ao ribeiro de Caná. A Efraim couberam as cidades ao sul do ribeiro, entre as cidades de Manassés; e o termo de Manassés estava ao norte do ribeiro, indo terminar no mar.

[[v6-17-10]]

^<<v6-17-10,10>>^ Efraim ao sul, e Manassés ao norte, e o mar é o seu termo; pelo norte tocam em Aser, e pelo oriente em Issacar.

[[v6-17-11]]

^<<v6-17-11,11>>^ Porque em Issacar e em Aser tinha Manassés a Bete-Seã e as suas vilas, e Ibleã e as suas vilas, e os habitantes de Dor e as suas vilas, e os habitantes de En-Dor e as suas vilas, e os habitantes de Taanaque e as suas vilas, e os habitantes de Megido e as suas vilas; três outeiros.

[[v6-17-12]]

^<<v6-17-12,12>>^ E os filhos de Manassés não puderam expulsar os habitantes daquelas cidades; porquanto os cananeus queriam habitar na mesma terra.

[[v6-17-13]]

^<<v6-17-13,13>>^ E sucedeu que, engrossando em forças os filhos de Israel, fizeram tributários aos cananeus; porém não os expulsaram de todo.

[[v6-17-14]]

^<<v6-17-14,14>>^ Então os filhos de José falaram a Josué, dizendo: Por que me deste por herança só uma sorte e um quinhão, sendo eu um tão grande povo, visto que o Senhor até aqui me tem abençoado?

[[v6-17-15]]

^<<v6-17-15,15>>^ E disse-lhes Josué: Se tão grande povo és, sobe ao bosque, e ali corta, para ti, lugar na terra dos perizeus e dos refains; pois que as montanhas de Efraim te são tão estreitas.

[[v6-17-16]]

^<<v6-17-16,16>>^ Então disseram os filhos de José: As montanhas não nos bastariam; também carros de ferro há entre todos os cananeus que habitam na terra do vale, entre os de Bete-Seã e as suas vilas, e entre os que estão no vale de Jizreel.

[[v6-17-17]]

^<<v6-17-17,17>>^ Então Josué falou à casa de José, a Efraim e a Manassés, dizendo: Grande povo és, e grande força tens; não terás uma sorte apenas;

[[v6-17-18]]

^<<v6-17-18,18>>^ Porém as montanhas serão tuas. Ainda que é bosque, cortá-lo-ás, e as suas extremidades serão tuas; porque expulsarás os cananeus, ainda que tenham carros de ferro, ainda que sejam fortes.

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]