include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v6-8-1]]

^<<v6-8-1,1>>^ Então disse o SENHOR a Josué: Não temas, e não te espantes; toma contigo toda a gente de guerra, e levanta-te, sobe a Ai; olha que te tenho dado na tua mão o rei de Ai e o seu povo, e a sua cidade, e a sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Farás, pois, a Ai e a seu rei, como fizeste a Jericó, e a seu rei; salvo que, para vós, tomareis os seus despojos, e o seu gado; põe emboscadas à cidade, por detrás dela.

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué levantou-se, e toda a gente de guerra, para subir contra Ai; e escolheu Josué trinta mil homens valorosos, e enviou-os de noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ E deu-lhes ordem, dizendo: Olhai! Ponde-vos de emboscadas contra a cidade, por detrás dela; não vos alongueis muito da cidade; e estai todos vós atentos.

[[v6-8-5]]

^<<v6-8-5,5>>^ Porém eu e todo o povo que está comigo nos aproximaremos da cidade; e será que, quando nos saírem ao encontro, como antes, fugiremos diante deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Deixai-os, pois, sair atrás de nós, até que os tiremos da cidade; porque dirão: Fogem diante de nós como antes. Assim fugiremos diante deles.

[[v6-8-7]]

^<<v6-8-7,7>>^ Então saireis vós da emboscada, e tomareis a cidade; porque o Senhor vosso Deus vo-la dará nas vossas mãos.

[[v6-8-8]]

^<<v6-8-8,8>>^ E será que tomando vós a cidade, pôr-lhe-eis fogo; conforme a palavra do Senhor fareis; olhai que vo-lo tenho mandado.

[[v6-8-9]]

^<<v6-8-9,9>>^ Assim Josué os enviou, e eles se foram à emboscada; e ficaram entre Betel e Ai, ao ocidente de Ai; porém Josué passou aquela noite no meio do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ E levantou-se Josué de madrugada, e contou o povo; e subiram ele e os anciãos de Israel adiante do povo contra Ai.

[[v6-8-11]]

^<<v6-8-11,11>>^ E subiram também todos os homens de guerra, que estavam com ele; e aproximaram-se, e chegaram defronte da cidade; e alojaram-se do lado norte de Ai, e havia um vale entre eles e Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Tomou também uns cinco mil homens, e pô-los de emboscada entre Betel e Ai, ao ocidente da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ E puseram o povo, todo o arraial que estava ao norte da cidade, e a emboscada ao ocidente da cidade; e foi Josué aquela noite até ao meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ E sucedeu que, vendo-o o rei de Ai, ele e todo o seu povo se apressaram, e se levantaram de madrugada, e os homens da cidade saíram ao encontro de Israel ao combate, ao tempo determinado, defronte das campinas; porém ele não sabia que se achava uma emboscada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué, pois, e todo o Israel se houveram como feridos diante deles, e fugiram pelo caminho do deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Por isso todo o povo, que estava na cidade, foi convocado para os seguir; e seguiram a Josué e foram afastados da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ E nem um só homem ficou em Ai, nem em Betel, que não saísse após Israel; e deixaram a cidade aberta, e seguiram a Israel.

[[v6-8-18]]

^<<v6-8-18,18>>^ Então o Senhor disse a Josué: Estende a lança que tens na tua mão, para Ai, porque a darei na tua mão. E Josué estendeu a lança, que estava na sua mão, para a cidade.

[[v6-8-19]]

^<<v6-8-19,19>>^ Então a emboscada se levantou apressadamente do seu lugar, e, estendendo ele a sua mão, correram e entraram na cidade, e a tomaram; e apressando-se, puseram fogo na cidade.

[[v6-8-20]]

^<<v6-8-20,20>>^ E virando-se os homens de Ai para trás, olharam, e eis que a fumaça da cidade subia ao céu, e não puderam fugir nem para uma parte nem para outra, porque o povo, que fugia para o deserto, se tornou contra os que os seguiam.

[[v6-8-21]]

^<<v6-8-21,21>>^ E vendo Josué e todo o Israel que a emboscada tomara a cidade, e que a fumaça da cidade subia, voltaram, e feriram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Também aqueles da cidade lhes saíram ao encontro, e assim ficaram no meio dos israelitas, uns de uma, e outros de outra parte; e feriram-nos, até que nenhum deles sobreviveu nem escapou.

[[v6-8-23]]

^<<v6-8-23,23>>^ Porém ao rei de Ai tomaram vivo, e o trouxeram a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ E sucedeu que, acabando os israelitas de matar todos os moradores de Ai no campo, no deserto, onde os tinham seguido, e havendo todos caído ao fio da espada, até serem consumidos, todo o Israel se tornou a Ai e a feriu ao fio de espada.

[[v6-8-25]]

^<<v6-8-25,25>>^ E todos os que caíram aquele dia, assim homens como mulheres, foram doze mil, todos moradores de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Porque Josué não retirou a sua mão, que estendera com a lança, até destruir totalmente a todos os moradores de Ai.

[[v6-8-27]]

^<<v6-8-27,27>>^ Tão-somente os israelitas tomaram para si o gado e os despojos da cidade, conforme à palavra do Senhor, que tinha ordenado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Queimou, pois, Josué a Ai e a tornou num montão perpétuo, em ruínas, até ao dia de hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ E ao rei de Ai enforcou num madeiro, até à tarde; e ao pôr do sol ordenou Josué que o seu corpo fosse tirado do madeiro; e o lançaram à porta da cidade, e levantaram sobre ele um grande montão de pedras, até o dia de hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué edificou um altar ao Senhor Deus de Israel, no monte Ebal.

[[v6-8-31]]

^<<v6-8-31,31>>^ Como Moisés, servo do Senhor, ordenara aos filhos de Israel, conforme ao que está escrito no livro da lei de Moisés, a saber: um altar de pedras inteiras, sobre o qual não se moverá instrumento de ferro; e ofereceram sobre ele holocaustos ao Senhor, e sacrificaram ofertas pacíficas.

[[v6-8-32]]

^<<v6-8-32,32>>^ Também escreveu ali, em pedras, uma cópia da lei de Moisés, que este havia escrito diante dos filhos de Israel.

[[v6-8-33]]

^<<v6-8-33,33>>^ E todo o Israel, com os seus anciãos, e os seus príncipes, e os seus juízes, estavam de um e de outro lado da arca, perante os sacerdotes levitas, que levavam a arca da aliança do Senhor, assim estrangeiros como naturais; metade deles em frente do monte Gerizim, e a outra metade em frente do monte Ebal, como Moisés, servo do Senhor, ordenara, para abençoar primeiramente o povo de Israel.

[[v6-8-34]]

^<<v6-8-34,34>>^ E depois leu em alta voz todas as palavras da lei, a bênção e a maldição, conforme a tudo o que está escrito no livro da lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Palavra nenhuma houve, de tudo o que Moisés ordenara, que Josué não lesse perante toda a congregação de Israel, e as mulheres, e os meninos, e os estrangeiros, que andavam no meio deles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]