include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v6-11-1]]

^<<v6-11-1,1>>^ Sucedeu depois disto que, ouvindo-o Jabim, rei de Hazor, enviou mensageiros a Jobabe, rei de Madom, e ao rei de Sinrom, e ao rei de Acsafe;

[[v6-11-2]]

^<<v6-11-2,2>>^ E aos reis, que estavam ao norte, nas montanhas, e na campina para o sul de Quinerete, e nas planícies, e nas elevações de Dor, do lado do mar;

[[v6-11-3]]

^<<v6-11-3,3>>^ Ao cananeu do oriente e do ocidente; e ao amorreu, e ao heteu, e ao perizeu, e ao jebuseu nas montanhas; e ao heveu ao pé de Hermom, na terra de Mizpá.

[[v6-11-4]]

^<<v6-11-4,4>>^ Saíram pois estes, e todos os seus exércitos com eles, muito povo, em multidão como a areia que está na praia do mar; e muitíssimos cavalos e carros.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos estes reis se ajuntaram, e vieram e se acamparam junto às águas de Merom, para pelejarem contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ E disse o Senhor a Josué: Não temas diante deles; porque amanhã, a esta mesma hora, eu os darei todos feridos diante dos filhos de Israel; os seus cavalos jarretarás, e os seus carros queimarás a fogo.

[[v6-11-7]]

^<<v6-11-7,7>>^ E Josué, e todos os homens de guerra com ele, veio apressadamente sobre eles às águas de Merom, e atacou-os de repente.

[[v6-11-8]]

^<<v6-11-8,8>>^ E o Senhor os deu nas mãos de Israel; e eles os feriram, e os perseguiram até à grande Sidom, e até Misrefote-Maim, e até ao vale de Mizpá ao oriente; feriram até não lhes deixarem nenhum.

[[v6-11-9]]

^<<v6-11-9,9>>^ E fez-lhes Josué como o Senhor lhe dissera; os seus cavalos jarretou, e os seus carros queimou a fogo.

[[v6-11-10]]

^<<v6-11-10,10>>^ E naquele mesmo tempo voltou Josué, e tomou a Hazor, e feriu à espada ao seu rei; porquanto Hazor antes era a cabeça de todos estes reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ E a todos os que nela estavam, feriram ao fio da espada, e totalmente os destruíram; nada restou do que tinha fôlego, e a Hazor queimou a fogo.

[[v6-11-12]]

^<<v6-11-12,12>>^ E Josué tomou todas as cidades destes reis, e todos os seus reis, e os feriu ao fio da espada, destruindo-os totalmente, como ordenara Moisés servo do Senhor.

[[v6-11-13]]

^<<v6-11-13,13>>^ Tão-somente não queimaram os israelitas as cidades que estavam sobre os seus outeiros; a não ser Hazor, a qual Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ E todos os despojos destas cidades, e o gado, os filhos de Israel tomaram para si; tão-somente a todos os homens feriram ao fio da espada, até que os destruíram; nada do que tinha fôlego deixaram com vida.

[[v6-11-15]]

^<<v6-11-15,15>>^ Como ordenara o Senhor a Moisés, seu servo, assim Moisés ordenou a Josué; e assim Josué o fez; nem uma só palavra tirou de tudo o que o Senhor ordenara a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Assim Josué tomou toda aquela terra, as montanhas, e todo o sul, e toda a terra de Gósen, e as planícies, e as campinas, e as montanhas de Israel, e as suas planícies.

[[v6-11-17]]

^<<v6-11-17,17>>^ Desde o monte Halaque, que sobe a Seir, até Baal-Gade, no vale do Líbano, ao pé do monte de Hermom; também tomou todos os seus reis, e os feriu e os matou.

[[v6-11-18]]

^<<v6-11-18,18>>^ Por muito tempo Josué fez guerra contra todos estes reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve cidade que fizesse paz com os filhos de Israel, senão os heveus, moradores de Gibeom; por guerra as tomaram todas.

[[v6-11-20]]

^<<v6-11-20,20>>^ Porquanto do Senhor vinha o endurecimento de seus corações, para saírem à guerra contra Israel, para que fossem totalmente destruídos e não achassem piedade alguma; mas para os destruir a todos como o Senhor tinha ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquele tempo veio Josué, e extirpou os anaquins das montanhas de Hebrom, de Debir, de Anabe e de todas as montanhas de Judá e de todas as montanhas de Israel; Josué os destruiu totalmente com as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Nenhum dos anaquins foi deixado na terra dos filhos de Israel; somente ficaram alguns em Gaza, em Gate, e em Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim Josué tomou toda esta terra, conforme a tudo o que o Senhor tinha dito a Moisés; e Josué a deu em herança aos filhos de Israel, conforme as suas divisões, segundo as suas tribos; e a terra descansou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]