include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// acf ?, ACF - Almeida Corrigida Fiel

[[v6-13-1]]

^<<v6-13-1,1>>^ Era, porém, Josué já velho, entrado em dias; e disse-lhe o SENHOR: Já estás velho, entrado em dias; e ainda muitíssima terra ficou para possuir.

[[v6-13-2]]

^<<v6-13-2,2>>^ A terra que ainda fica é esta: Todos os termos dos filisteus e toda a Gesur;

[[v6-13-3]]

^<<v6-13-3,3>>^ Desde Sior, que está em frente ao Egito, até ao termo de Ecrom para o norte, que se diz ser dos cananeus; cinco príncipes dos filisteus; o gazeu, e o asdodeu, o asqueloneu, o giteu, e o ecroneu, e os aveus;

[[v6-13-4]]

^<<v6-13-4,4>>^ Desde o sul, toda a terra dos cananeus, e Meara, que é dos sidônios; até Afeca, até ao termo dos amorreus;

[[v6-13-5]]

^<<v6-13-5,5>>^ Como também a terra dos gebalitas, e todo o Líbano, para o nascente do sol, desde Baal-Gade, ao pé do monte Hermom, até a entrada de Hamate;

[[v6-13-6]]

^<<v6-13-6,6>>^ Todos os que habitam nas montanhas desde o Líbano até Misrefote-Maim, todos os sidônios; eu os lançarei de diante dos filhos de Israel; tão-somente reparte a terra em herança a Israel, como já te mandei.

[[v6-13-7]]

^<<v6-13-7,7>>^ Reparte, pois, agora esta terra por herança às nove tribos, e à meia tribo de Manassés,

[[v6-13-8]]

^<<v6-13-8,8>>^ Com a qual os rubenitas e os gaditas já receberam a sua herança, além do Jordão para o oriente, assim como já lhes tinha dado Moisés, servo do Senhor.

[[v6-13-9]]

^<<v6-13-9,9>>^ Desde Aroer, que está à beira do ribeiro de Arnom, e a cidade que está no meio do vale, e toda a campina de Medeba até Dibom;

[[v6-13-10]]

^<<v6-13-10,10>>^ E todas as cidades de Siom, rei dos amorreus, que reinou em Hesbom, até ao termo dos filhos de Amom;

[[v6-13-11]]

^<<v6-13-11,11>>^ E Gileade, e o termo dos gesureus, e dos maacateus, e todo o monte Hermom, e toda a Basã até Salcá;

[[v6-13-12]]

^<<v6-13-12,12>>^ Todo o reino de Ogue em Basã, que reinou em Astarote e em Edrei; este ficou do restante dos gigantes que Moisés feriu e expulsou.

[[v6-13-13]]

^<<v6-13-13,13>>^ Porém os filhos de Israel não expulsaram os gesureus, nem os maacateus; antes Gesur e Maacate ficaram habitando no meio de Israel até ao dia de hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ Tão-somente à tribo de Levi não deu herança; os sacrifícios queimados do Senhor Deus de Israel são a sua herança, como já lhe tinha falado.

[[v6-13-15]]

^<<v6-13-15,15>>^ Assim Moisés deu à tribo dos filhos de Rúben, conforme as suas famílias.

[[v6-13-16]]

^<<v6-13-16,16>>^ E foi o seu limite desde Aroer, que está à beira do ribeiro de Arnom, e a cidade que está no meio do vale, e toda a campina até Medeba;

[[v6-13-17]]

^<<v6-13-17,17>>^ Hesbom e todas as suas cidades, que estão na campina; Dibom, e Bamote-Baal, e Bete-Baal-Meom;

[[v6-13-18]]

^<<v6-13-18,18>>^ E Jasa e Quedemote, e Mefaate;

[[v6-13-19]]

^<<v6-13-19,19>>^ E Quiriataim e Sibma, e Zerete-Saar, no monte do vale;

[[v6-13-20]]

^<<v6-13-20,20>>^ Bete-Peor, e Asdote-Pisga, Bete-Jesimote;

[[v6-13-21]]

^<<v6-13-21,21>>^ E todas as cidades da campina, e todo o reino de Siom, rei dos amorreus, que reinou em Hesbom, a quem Moisés feriu, como também aos príncipes de Midiã, Evi, e Requém, e Zur, e Hur, e Reba, príncipes de Siom, moradores da terra.

[[v6-13-22]]

^<<v6-13-22,22>>^ Também os filhos de Israel mataram à espada a Balaão, filho de Beor, o adivinho, com os outros que por eles foram mortos.

[[v6-13-23]]

^<<v6-13-23,23>>^ E o termo dos filhos de Rúben ficou sendo o Jordão e os seus limites; esta foi a herança dos filhos de Rúben, segundo as suas famílias, as cidades, e as suas aldeias.

[[v6-13-24]]

^<<v6-13-24,24>>^ E deu Moisés à tribo de Gade, aos filhos de Gade, segundo as suas famílias.

[[v6-13-25]]

^<<v6-13-25,25>>^ E foi o seu termo Jazer, e todas as cidades de Gileade, e metade da terra dos filhos de Amom, até Aroer, que está em frente de Rabá.

[[v6-13-26]]

^<<v6-13-26,26>>^ E desde Hesbom até Ramate-Mizpá e Betonim, e desde Maanaim até ao termo de Debir;

[[v6-13-27]]

^<<v6-13-27,27>>^ E no vale Bete-Arã, e Bete-Nimra, e Sucote, Zafom, que ficara do restante do reino de Siom, em Hesbom, o Jordão e o seu termo, até a extremidade do mar de Quinerete além do Jordão para o oriente.

[[v6-13-28]]

^<<v6-13-28,28>>^ Esta é a herança dos filhos de Gade segundo as suas famílias, as cidades e as suas aldeias.

[[v6-13-29]]

^<<v6-13-29,29>>^ Deu também Moisés herança à meia tribo de Manassés; e deu à meia tribo dos filhos de Manassés, segundo as suas famílias.

[[v6-13-30]]

^<<v6-13-30,30>>^ De maneira que o seu termo foi desde Maanaim, todo o Basã, todo o reino de Ogue, rei de Basã, e todas as aldeias de Jair, que estão em Basã, sessenta cidades,

[[v6-13-31]]

^<<v6-13-31,31>>^ E metade de Gileade, e Astarote, e Edrei, cidades do reino de Ogue em Basã, deu aos filhos de Maquir, filho de Manassés, a saber, à metade dos filhos de Maquir, segundo as suas famílias.

[[v6-13-32]]

^<<v6-13-32,32>>^ Isto é o que Moisés repartiu em herança nas campinas de Moabe, além do Jordão para o oriente de Jericó.

[[v6-13-33]]

^<<v6-13-33,33>>^ Porém, à tribo de Levi, Moisés não deu herança; o Senhor Deus de Israel é a sua herança, como já lhe tinha falado.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]