include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-19-1]]

^<<v26-19-1,1>>^ E tu levanta uma lamentação sobre os príncipes de Israel,

[[v26-19-2]]

^<<v26-19-2,2>>^ E dize: Quem foi tua mãe? Uma leoa entre os leões a qual, deitada no meio dos leõezinhos, criou os seus filhotes.

[[v26-19-3]]

^<<v26-19-3,3>>^ E educou um dos seus filhotes, o qual veio a ser leãozinho e aprendeu a apanhar a presa, e devorou homens,

[[v26-19-4]]

^<<v26-19-4,4>>^ E, ouvindo falar dele as nações, foi apanhado na cova delas, e o trouxeram com cadeias à terra do Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ Vendo, pois, ela que havia esperado muito, e que a sua expectação era perdida, tomou outro dos seus filhotes, e fez dele um leãozinho.

[[v26-19-6]]

^<<v26-19-6,6>>^ Este, pois, andando continuamente no meio dos leões, veio a ser leãozinho, e aprendeu a apanhar a presa, e devorou homens.

[[v26-19-7]]

^<<v26-19-7,7>>^ E conheceu os seus palácios, e destruiu as suas cidades; e assolou-se a terra, e a sua plenitude, ao som do seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então se ajuntaram contra ele os povos das províncias ao redor, e estenderam sobre ele a rede, e foi apanhado na cova deles.

[[v26-19-9]]

^<<v26-19-9,9>>^ E com cadeias colocaram-no em uma jaula, e o levaram ao rei de babilônia; fizeram-no entrar nos lugares fortes, para que não se ouvisse mais a sua voz nos montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ Tua mãe era como uma videira no teu sangue, plantada junto às águas; ela frutificou, e encheu-se de ramos, por causa das muitas águas.

[[v26-19-11]]

^<<v26-19-11,11>>^ E tinha varas fortes para cetros de dominadores, e elevou-se a sua estatura entre os espessos ramos, e foi vista na sua altura com a multidão dos seus ramos.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas foi arrancada com furor, foi lançada por terra, e o vento oriental secou o seu fruto; quebraram-se e secaram-se as suas fortes varas, o fogo as consumiu,

[[v26-19-13]]

^<<v26-19-13,13>>^ E agora está plantada no deserto, numa terra seca e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ E de uma vara dos seus ramos saiu fogo que consumiu o seu fruto de maneira que nela não há mais vara forte, cetro para dominar. Esta é a lamentação, e servirá de lamentação.

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]