include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-43-1]]

^<<v26-43-1,1>>^ Então me levou à porta, à porta que olha para o caminho do oriente.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que a glória do Deus de Israel vinha do caminho do oriente; e a sua voz era como a voz de muitas águas, e a terra resplandeceu por causa da sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ E o aspecto da visão que tive era como o da visão que eu tivera quando vim destruir a cidade; e eram as visões como as que tive junto ao rio Quebar; e caí sobre o meu rosto.

[[v26-43-4]]

^<<v26-43-4,4>>^ E a glória do Senhor entrou na casa pelo caminho da porta, cuja face está para o lado do oriente.

[[v26-43-5]]

^<<v26-43-5,5>>^ E levantou-me o Espírito, e me levou ao átrio interior; e eis que a glória do SENHOR encheu a casa.

[[v26-43-6]]

^<<v26-43-6,6>>^ E ouvi alguém que falava comigo de dentro da casa, e um homem se pôs em pé junto de mim.

[[v26-43-7]]

^<<v26-43-7,7>>^ E disse-me: Filho do homem, este é o lugar do meu trono, e o lugar das plantas dos meus pés, onde habitarei no meio dos filhos de Israel para sempre; e os da casa de Israel não contaminarão mais o meu nome santo, nem eles nem os seus reis, com suas prostituições e com os cadáveres dos seus reis, nos seus altos,

[[v26-43-8]]

^<<v26-43-8,8>>^ Pondo o seu limiar ao pé do meu limiar, e o seu umbral junto ao meu umbral, e havendo uma parede entre mim e eles; e contaminaram o meu santo nome com as suas abominações que cometiam; por isso eu os consumi na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora lancem eles para longe de mim a sua prostituição, e os cadáveres dos seus reis, e habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ Tu, pois, ó filho do homem, mostra à casa de Israel esta casa, para que se envergonhe das suas maldades, e meça o modelo.

[[v26-43-11]]

^<<v26-43-11,11>>^ E, envergonhando-se eles de tudo quanto fizeram, faze-lhes saber a forma desta casa, e a sua figura, e as suas saídas, e as suas entradas, e todas as suas formas, e todos os seus estatutos, todas as suas formas, e todas as suas leis; e escreve isto aos seus olhos, para que guardem toda a sua forma, e todos os seus estatutos, e os cumpram.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei da casa: Sobre o cume do monte todo o seu contorno em redor será santíssimo; eis que esta é a lei da casa.

[[v26-43-13]]

^<<v26-43-13,13>>^ E estas são as medidas do altar, em côvados (o côvado é um côvado e um palmo): e o fundo será de um côvado de altura, e um côvado de largura, e a sua borda em todo o seu contorno, de um palmo; e esta é a base do altar.

[[v26-43-14]]

^<<v26-43-14,14>>^ E do fundo, desde a terra até a armação inferior, dois côvados, e de largura um côvado, e desde a pequena armação até a grande, quatro côvados, e a largura de um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ E o altar, de quatro côvados; e desde o altar e para cima havia quatro pontas.

[[v26-43-16]]

^<<v26-43-16,16>>^ E o altar terá doze côvados de comprimento, e doze de largura, quadrado nos quatro lados.

[[v26-43-17]]

^<<v26-43-17,17>>^ E a armação, catorze côvados de comprimento, e catorze de largura, nos seus quatro lados; e o contorno, ao redor dela, de meio côvado, e o fundo dela de um côvado, ao redor; e os seus degraus davam para o oriente.

[[v26-43-18]]

^<<v26-43-18,18>>^ E disse-me: Filho do homem, assim diz o Senhor DEUS: Estes são os estatutos do altar, no dia em que o fizerem, para oferecerem sobre ele holocausto e para aspergirem sobre ele sangue.

[[v26-43-19]]

^<<v26-43-19,19>>^ E aos sacerdotes levitas, que são da descendência de Zadoque, que se chegam a mim (diz o Senhor DEUS) para me servirem, darás um bezerro, para oferta pelo pecado.

[[v26-43-20]]

^<<v26-43-20,20>>^ E tomarás do seu sangue, e o porás sobre as suas quatro pontas, e sobre os quatro cantos da armação, e no contorno ao redor; assim o purificarás e o expiarás.

[[v26-43-21]]

^<<v26-43-21,21>>^ Então tomarás o bezerro da oferta pelo pecado, e o queimará no lugar da casa para isso designado, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ E no segundo dia oferecerás um bode, sem mancha, como oferta pelo pecado; e purificarão o altar, como o purificaram com o bezerro.

[[v26-43-23]]

^<<v26-43-23,23>>^ E, acabando tu de purificá-lo, oferecerás um bezerro, sem mancha, e um carneiro do rebanho, sem mancha.

[[v26-43-24]]

^<<v26-43-24,24>>^ E oferecê-los-ás perante a face do Senhor; e os sacerdotes deitarão sal sobre eles, e oferecê-los-ão em holocausto ao Senhor.

[[v26-43-25]]

^<<v26-43-25,25>>^ Por sete dias prepararás, cada dia um bode como oferta pelo pecado; também prepararão um bezerro, e um carneiro do rebanho, sem mancha.

[[v26-43-26]]

^<<v26-43-26,26>>^ Por sete dias expiarão o altar, e o purificarão; e assim consagrar-se-ão.

[[v26-43-27]]

^<<v26-43-27,27>>^ E, cumprindo eles estes dias, será que, ao oitavo dia, e dali em diante, os sacerdotes oferecerão sobre o altar os vossos holocaustos e as vossas ofertas pacíficas; e eu me deleitarei em vós, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]