include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-6-1]]

^<<v26-6-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-6-2]]

^<<v26-6-2,2>>^ Filho do homem, dirige o teu rosto para os montes de Israel, e profetiza contra eles.

[[v26-6-3]]

^<<v26-6-3,3>>^ E dirás: Montes de Israel, ouvi a palavra do Senhor DEUS: Assim diz o Senhor DEUS aos montes, aos outeiros, aos ribeiros e aos vales: Eis que eu, sim eu, trarei a espada sobre vós, e destruirei os vossos lugares altos.

[[v26-6-4]]

^<<v26-6-4,4>>^ E serão assolados os vossos altares, e quebradas as vossas imagens do sol e derrubarei os vossos mortos, diante dos vossos ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ E porei os cadáveres dos filhos de Israel diante dos seus ídolos; e espalharei os vossos ossos em redor dos vossos altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Em todos os vossos lugares habitáveis, as cidades serão destruídas, e os lugares altos assolados; para que os vossos altares sejam destruídos e assolados, e os vossos ídolos se quebrem e se acabem, e as vossas imagens sejam cortadas, e desfeitas as vossas obras.

[[v26-6-7]]

^<<v26-6-7,7>>^ E os mortos cairão no meio de vós, para que saibais que eu sou o Senhor.

[[v26-6-8]]

^<<v26-6-8,8>>^ Porém deixarei um remanescente, para que tenhais entre as nações alguns que escaparem da espada, quando fordes espalhados pelas terras.

[[v26-6-9]]

^<<v26-6-9,9>>^ Então os que dentre vós escaparem se lembrarão de mim entre as nações para onde foram levados em cativeiro; porquanto me quebrantei por causa do seu coração corrompido, que se desviou de mim, e por causa dos seus olhos, que andaram se corrompendo após os seus ídolos; e terão nojo de si mesmos, por causa das maldades que fizeram em todas as suas abominações.

[[v26-6-10]]

^<<v26-6-10,10>>^ E saberão que eu sou o Senhor, e que não disse debalde que lhes faria este mal.

[[v26-6-11]]

^<<v26-6-11,11>>^ Assim diz o Senhor DEUS: Bate com a mão, e bate com o teu pé, e dize: Ah! Por todas as grandes abominações da casa de Israel! Porque cairão à espada, e de fome, e de peste.

[[v26-6-12]]

^<<v26-6-12,12>>^ O que estiver longe morrerá de peste, e o que está perto cairá à espada; e o que restar e ficar cercado morrerá de fome; assim cumprirei o meu furor sobre eles.

[[v26-6-13]]

^<<v26-6-13,13>>^ Então sabereis que eu sou o Senhor, quando os seus mortos estiverem no meio dos seus ídolos, em redor dos seus altares, em todo o outeiro alto, em todos os cumes dos montes, e debaixo de toda a árvore verde, e debaixo de todo o carvalho frondoso, no lugar onde ofereciam cheiro suave a todos os seus ídolos.

[[v26-6-14]]

^<<v26-6-14,14>>^ E estenderei a minha mão sobre eles, e farei a terra desolada, e mais devastada do que o deserto do lado de Dibla, em todas as suas habitações; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]