include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-44-1]]

^<<v26-44-1,1>>^ Então me fez voltar para o caminho da porta exterior do santuário, que olha para o oriente, a qual estava fechada.

[[v26-44-2]]

^<<v26-44-2,2>>^ E disse-me o Senhor: Esta porta permanecerá fechada, não se abrirá; ninguém entrará por ela, porque o Senhor, o Deus de Israel entrou por ela; por isso permanecerá fechada.

[[v26-44-3]]

^<<v26-44-3,3>>^ Quanto ao príncipe, por ser príncipe, se assentará nela para sempre, para comer o pão diante do Senhor; pelo caminho do vestíbulo da porta entrará e por esse mesmo caminho sairá.

[[v26-44-4]]

^<<v26-44-4,4>>^ Depois me levou pelo caminho da porta do norte, diante da casa; e olhei, e eis que a glória do Senhor encheu a casa do Senhor; então caí sobre o meu rosto.

[[v26-44-5]]

^<<v26-44-5,5>>^ E disse-me o Senhor: Filho do homem, pondera no teu coração, e vê com os teus olhos, e ouve com os teus ouvidos, tudo quanto eu te disser de todos os estatutos da casa do Senhor, e de todas as suas leis; e considera no teu coração a entrada da casa, com todas as saídas do santuário.

[[v26-44-6]]

^<<v26-44-6,6>>^ E dize ao rebelde, à casa de Israel: Assim diz o Senhor DEUS: Bastem-vos todas as vossas abominações, ó casa de Israel!

[[v26-44-7]]

^<<v26-44-7,7>>^ Porque introduzistes estrangeiros, incircuncisos de coração e incircuncisos de carne, para estarem no meu santuário, para o profanarem em minha casa, quando ofereceis o meu pão, a gordura, e o sangue; e eles invalidaram a minha aliança, por causa de todas as vossas abominações.

[[v26-44-8]]

^<<v26-44-8,8>>^ E não guardastes a ordenança a respeito das minhas coisas sagradas; antes vos constituístes, a vós mesmos, guardas da minha ordenança no meu santuário.

[[v26-44-9]]

^<<v26-44-9,9>>^ Assim diz o Senhor DEUS: Nenhum estrangeiro, incircunciso de coração ou incircunciso de carne, entrará no meu santuário, dentre os estrangeiros que se acharem no meio dos filhos de Israel.

[[v26-44-10]]

^<<v26-44-10,10>>^ Mas os levitas que se apartaram para longe de mim, quando Israel andava errado; os quais andavam transviados, desviados de mim, para irem atrás dos seus ídolos, levarão sobre si a sua iniqüidade.

[[v26-44-11]]

^<<v26-44-11,11>>^ Contudo serão ministros no meu santuário, nos ofícios das portas da casa, e servirão à casa; eles matarão o holocausto, e o sacrifício para o povo, e estarão perante eles, para os servir.

[[v26-44-12]]

^<<v26-44-12,12>>^ Porque lhes ministraram diante dos seus ídolos, e fizeram a casa de Israel cair em iniqüidade; por isso eu levantei a minha mão contra eles, diz o Senhor DEUS, e levarão sobre si a sua iniqüidade.

[[v26-44-13]]

^<<v26-44-13,13>>^ E não se chegarão a mim, para me servirem no sacerdócio, nem para se chegarem a alguma de todas as minhas coisas sagradas, às coisas que são santíssimas, mas levarão sobre si a sua vergonha e as suas abominações que cometeram.

[[v26-44-14]]

^<<v26-44-14,14>>^ Contudo, eu os constituirei guardas da ordenança da casa, em todo o seu serviço, e em tudo o que nela se fizer.

[[v26-44-15]]

^<<v26-44-15,15>>^ Mas os sacerdotes levíticos, os filhos de Zadoque, que guardaram a ordenança do meu santuário quando os filhos de Israel se extraviaram de mim, eles se chegarão a mim, para me servirem, e estarão diante de mim, para me oferecerem a gordura e o sangue, diz o Senhor DEUS.

[[v26-44-16]]

^<<v26-44-16,16>>^ Eles entrarão no meu santuário, e se chegarão à minha mesa, para me servirem, e guardarão a minha ordenança;

[[v26-44-17]]

^<<v26-44-17,17>>^ E será que, quando entrarem pelas portas do átrio interior, se vestirão com vestes de linho; e não se porá lã sobre eles, quando servirem nas portas do átrio interior, e dentro.

[[v26-44-18]]

^<<v26-44-18,18>>^ Gorros de linho estarão sobre as suas cabeças, e calções de linho sobre os seus lombos; não se cingirão de modo que lhes venha suor.

[[v26-44-19]]

^<<v26-44-19,19>>^ E, saindo eles ao átrio exterior, ao átrio de fora, ao povo, despirão as suas vestiduras com que ministraram, e as porão nas santas câmaras, e se vestirão de outras vestes, para que não santifiquem o povo estando com as suas vestiduras.

[[v26-44-20]]

^<<v26-44-20,20>>^ E não raparão a sua cabeça, nem deixarão crescer o cabelo; antes, como convém, tosquiarão as suas cabeças.

[[v26-44-21]]

^<<v26-44-21,21>>^ E nenhum sacerdote beberá vinho quando entrar no átrio interior.

[[v26-44-22]]

^<<v26-44-22,22>>^ E eles não se casarão nem com viúva nem com repudiada, mas tomarão virgens da linhagem da casa de Israel, ou viúva que for viúva de sacerdote.

[[v26-44-23]]

^<<v26-44-23,23>>^ E a meu povo ensinarão a distinguir entre o santo e o profano, e o farão discernir entre o impuro e o puro.

[[v26-44-24]]

^<<v26-44-24,24>>^ E, quando houver disputa, eles assistirão a ela para a julgarem; pelos meus juízos as julgarão; e as minhas leis e os meus estatutos guardarão em todas as minhas solenidades, e santificarão os meus sábados.

[[v26-44-25]]

^<<v26-44-25,25>>^ E eles não se aproximarão de nenhum homem morto, para se contaminarem; mas por pai, ou por mãe, ou por filho, ou por filha, ou por irmão, ou por irmã que não tiver marido, se poderão contaminar.

[[v26-44-26]]

^<<v26-44-26,26>>^ E, depois da sua purificação, contar-se-lhe-ão sete dias.

[[v26-44-27]]

^<<v26-44-27,27>>^ E, no dia em que ele entrar no lugar santo, no átrio interior, para ministrar no lugar santo, oferecerá a sua expiação pelo pecado, diz o Senhor DEUS.

[[v26-44-28]]

^<<v26-44-28,28>>^ Eles terão uma herança: eu serei a sua herança. Não lhes dareis, portanto, possessão em Israel; eu sou a sua possessão.

[[v26-44-29]]

^<<v26-44-29,29>>^ Eles comerão a oferta de alimentos, e a oferta pelo pecado e a oferta pela culpa; e toda a coisa consagrada em Israel será deles.

[[v26-44-30]]

^<<v26-44-30,30>>^ E as primícias de todos os primeiros frutos de tudo, e toda a oblação de tudo, de todas as vossas oblações, serão dos sacerdotes; também as primeiras das vossas massas dareis ao sacerdote, para que faça repousar a bênção sobre a tua casa.

[[v26-44-31]]

^<<v26-44-31,31>>^ Nenhuma coisa, que tenha morrido ou tenha sido despedaçada, de aves e de animais, comerão os sacerdotes.

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]