include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-35-1]]

^<<v26-35-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ Filho do homem, dirige o teu rosto contra o monte Seir, e profetiza contra ele.

[[v26-35-3]]

^<<v26-35-3,3>>^ E dize-lhe: Assim diz o Senhor DEUS: Eis que eu estou contra ti, ó monte Seir, e estenderei a minha mão contra ti, e te farei maior desolação.

[[v26-35-4]]

^<<v26-35-4,4>>^ As tuas cidades farei desertas, e tu serás desolado; e saberás que eu sou o Senhor.

[[v26-35-5]]

^<<v26-35-5,5>>^ Porquanto guardaste inimizade perpétua, e espalhaste os filhos de Israel pelo poder da espada no tempo da sua calamidade e no tempo da iniqüidade final.

[[v26-35-6]]

^<<v26-35-6,6>>^ Por isso vivo eu, diz o Senhor DEUS, que te preparei para sangue, e o sangue te perseguirá; visto que não odiaste o sangue, o sangue te perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ E farei do monte Seir uma extrema desolação, e exterminarei dele o que por ele passar, e o que por ele voltar.

[[v26-35-8]]

^<<v26-35-8,8>>^ E encherei os seus montes dos seus mortos; nos teus outeiros, e nos teus vales, e em todos os teus rios cairão os mortos à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Em desolações perpétuas te porei, e as tuas cidades nunca mais serão habitadas; assim sabereis que eu sou o Senhor.

[[v26-35-10]]

^<<v26-35-10,10>>^ Porquanto disseste: As duas nações e as duas terras serão minhas, e as possuiremos, sendo que o Senhor se achava ali.

[[v26-35-11]]

^<<v26-35-11,11>>^ Portanto, vivo eu, diz o Senhor DEUS, que procederei conforme a tua ira, e conforme a tua inveja, de que usaste, no teu ódio contra eles; e me farei conhecer entre eles, quando te julgar.

[[v26-35-12]]

^<<v26-35-12,12>>^ E saberás que eu, o Senhor, ouvi todas as tuas blasfêmias, que proferiste contra os montes de Israel, dizendo: Já estão assolados, a nós nos são entregues por pasto.

[[v26-35-13]]

^<<v26-35-13,13>>^ Assim vos engrandecestes contra mim com a vossa boca, e multiplicastes as vossas palavras contra mim. Eu o ouvi.

[[v26-35-14]]

^<<v26-35-14,14>>^ Assim diz o Senhor DEUS: Quando toda a terra se alegrar eu te porei em desolação.

[[v26-35-15]]

^<<v26-35-15,15>>^ Como te alegraste da herança da casa de Israel, porque foi assolada, assim te farei a ti; assolado serás, ó monte Seir, e todo o Edom, sim, todo ele; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]