include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-10-1]]

^<<v26-10-1,1>>^ Depois olhei, e eis que no firmamento, que estava por cima da cabeça dos querubins, apareceu sobre eles uma como pedra de safira, semelhante a forma de um trono.

[[v26-10-2]]

^<<v26-10-2,2>>^ E falou ao homem vestido de linho, dizendo: Vai por entre as rodas, até debaixo do querubim, e enche as tuas mãos de brasas acesas dentre os querubins e espalha-as sobre a cidade. E ele entrou à minha vista.

[[v26-10-3]]

^<<v26-10-3,3>>^ E os querubins estavam ao lado direito da casa, quando entrou aquele homem; e uma nuvem encheu o átrio interior.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então se levantou a glória do Senhor de sobre o querubim indo para a entrada da casa; e encheu-se a casa de uma nuvem, e o átrio se encheu do resplendor da glória do Senhor.

[[v26-10-5]]

^<<v26-10-5,5>>^ E o ruído das asas dos querubins se ouviu até ao átrio exterior, como a voz do Deus Todo-Poderoso, quando fala.

[[v26-10-6]]

^<<v26-10-6,6>>^ Sucedeu, pois, que, dando ele ordem ao homem vestido de linho, dizendo: Toma fogo dentre as rodas, dentre os querubins, entrou ele, e parou junto às rodas.

[[v26-10-7]]

^<<v26-10-7,7>>^ Então estendeu um querubim a sua mão dentre os querubins para o fogo que estava entre os querubins; e tomou dele, e o pôs nas mãos do que estava vestido de linho; o qual o tomou, e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ E apareceu nos querubins uma semelhança de mão de homem debaixo das suas asas.

[[v26-10-9]]

^<<v26-10-9,9>>^ Então olhei, e eis quatro rodas junto aos querubins, uma roda junto a um querubim, e outra roda junto a outro querubim; e o aspecto das rodas era como a cor da pedra de berilo.

[[v26-10-10]]

^<<v26-10-10,10>>^ E, quanto ao seu aspecto, as quatro tinham uma mesma semelhança; como se estivesse uma roda no meio de outra roda.

[[v26-10-11]]

^<<v26-10-11,11>>^ Andando estes, andavam para os quatro lados deles; não se viravam quando andavam, mas para o lugar para onde olhava a cabeça, para esse seguiam; não se viravam quando andavam.

[[v26-10-12]]

^<<v26-10-12,12>>^ E todo o seu corpo, as suas costas, as suas mãos, as suas asas e as rodas, as rodas que os quatro tinham, estavam cheias de olhos ao redor.

[[v26-10-13]]

^<<v26-10-13,13>>^ E, quanto às rodas, ouvindo eu, se lhes gritava: Roda!

[[v26-10-14]]

^<<v26-10-14,14>>^ E cada um tinha quatro rostos; o rosto do primeiro era rosto de querubim, e o rosto do segundo, rosto de homem, e do terceiro era rosto de leão, e do quarto, rosto de águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ E os querubins se elevaram ao alto; estes são os mesmos seres viventes que vi junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ E, andando os querubins, andavam as rodas juntamente com eles; e, levantando os querubins as suas asas, para se elevarem de sobre a terra, também as rodas não se separavam deles.

[[v26-10-17]]

^<<v26-10-17,17>>^ Parando eles, paravam elas; e, elevando-se eles elevavam-se elas, porque o espírito do ser vivente estava nelas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então saiu a glória do Senhor de sobre a entrada da casa, e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ E os querubins alçaram as suas asas, e se elevaram da terra aos meus olhos, quando saíram; e as rodas os acompanhavam; e cada um parou à entrada da porta oriental da casa do Senhor; e a glória do Deus de Israel estava em cima, sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ Estes são os seres viventes que vi debaixo do Deus de Israel, junto ao rio Quebar, e conheci que eram querubins.

[[v26-10-21]]

^<<v26-10-21,21>>^ Cada um tinha quatro rostos e cada um quatro asas, e a semelhança de mãos de homem debaixo das suas asas.

[[v26-10-22]]

^<<v26-10-22,22>>^ E a semelhança dos seus rostos era a dos rostos que eu tinha visto junto ao rio Quebar, o aspecto deles, e eles mesmos; cada um andava para diante do seu rosto.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]