include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-25-1]]

^<<v26-25-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-25-2]]

^<<v26-25-2,2>>^ Filho do homem, dirige o teu rosto contra os filhos de Amom, e profetiza contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ E dize aos filhos de Amom: Ouvi a palavra do Senhor DEUS: Assim diz o Senhor DEUS: Porquanto tu disseste: Ah! contra o meu santuário, quando foi profanado; e contra a terra de Israel, quando foi assolada; e contra a casa de Judá, quando foi ao cativeiro;

[[v26-25-4]]

^<<v26-25-4,4>>^ Portanto, eis que te entregarei em possessão aos do oriente, e em ti estabelecerão os seus acampamentos, e porão em ti as suas moradas; eles comerão os teus frutos, e eles beberão o teu leite.

[[v26-25-5]]

^<<v26-25-5,5>>^ E farei de Rabá uma estrebaria de camelos, e dos filhos de Amom um curral de ovelhas; e sabereis que eu sou o Senhor.

[[v26-25-6]]

^<<v26-25-6,6>>^ Porque assim diz o Senhor DEUS: Porquanto bateste com as mãos, e pateaste com os pés, e com todo o desprezo do teu coração te alegraste contra a terra de Israel,

[[v26-25-7]]

^<<v26-25-7,7>>^ Portanto, eis que eu tenho estendido a minha mão sobre ti, e te darei por despojo aos gentios, e te arrancarei dentre os povos, e te destruirei dentre as terras, e acabarei de todo contigo; e saberás que eu sou o Senhor.

[[v26-25-8]]

^<<v26-25-8,8>>^ Assim diz o Senhor DEUS: Porquanto dizem Moabe e Seir: Eis que a casa de Judá é como todos os gentios;

[[v26-25-9]]

^<<v26-25-9,9>>^ Portanto, eis que eu abrirei o lado de Moabe desde as cidades, desde as suas cidades da fronteira, a glória da terra, Bete-Jesimote, Baal-Meom, e Quiriataim.

[[v26-25-10]]

^<<v26-25-10,10>>^ E aos do oriente, contra os filhos de Amom, o entregarei em possessão, para que não haja memória dos filhos de Amom entre as nações.

[[v26-25-11]]

^<<v26-25-11,11>>^ Também executarei juízos sobre Moabe, e saberão que eu sou o Senhor.

[[v26-25-12]]

^<<v26-25-12,12>>^ Assim diz o Senhor DEUS: Porquanto Edom se houve vingativamente para com a casa de Judá, e se fez culpadíssimo, quando se vingou deles;

[[v26-25-13]]

^<<v26-25-13,13>>^ Portanto assim diz o Senhor DEUS: Também estenderei a minha mão sobre Edom, e arrancarei dela homens e animais; e a tornarei em deserto, e desde Temã até Dedã cairão à espada.

[[v26-25-14]]

^<<v26-25-14,14>>^ E exercerei a minha vingança sobre Edom, pela mão do meu povo de Israel; e farão em Edom segundo a minha ira e segundo o meu furor; e conhecerão a minha vingança, diz o Senhor DEUS.

[[v26-25-15]]

^<<v26-25-15,15>>^ Assim diz o Senhor DEUS: Porquanto os filisteus se houveram vingativamente, e executaram vingança com desprezo de coração, para destruírem com perpétua inimizade,

[[v26-25-16]]

^<<v26-25-16,16>>^ Portanto assim diz o Senhor DEUS: Eis que eu estendo a minha mão sobre os filisteus, e arrancarei os quereteus, e destruirei o restante da costa do mar.

[[v26-25-17]]

^<<v26-25-17,17>>^ E executarei sobre eles grandes vinganças, com furiosos castigos, e saberão que eu sou o Senhor, quando eu tiver exercido a minha vingança sobre eles.

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]