include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-24-1]]

^<<v26-24-1,1>>^ E veio a mim a palavra do SENHOR, no nono ano, no décimo mês, aos dez do mês, dizendo:

[[v26-24-2]]

^<<v26-24-2,2>>^ Filho do homem, escreve o nome deste dia, deste mesmo dia; porque o rei de babilônia se pôs contra Jerusalém neste mesmo dia.

[[v26-24-3]]

^<<v26-24-3,3>>^ E fala por parábola à casa rebelde, e dize-lhes: Assim diz o Senhor DEUS: Põe a panela ao lume, põe-na, e deita-lhe também água dentro.

[[v26-24-4]]

^<<v26-24-4,4>>^ Ajunta nela pedaços, todos os bons pedaços, as coxas e as espáduas; enche-a de ossos escolhidos.

[[v26-24-5]]

^<<v26-24-5,5>>^ Escolhe o melhor do rebanho, e queima também os ossos debaixo dela; faze-a ferver bem, e cozam-se dentro dela os seus ossos.

[[v26-24-6]]

^<<v26-24-6,6>>^ Portanto, assim diz o Senhor DEUS: Ai da cidade sanguinária, da panela que escuma por dentro, e cuja escuma não saiu dela! Tira dela pedaço por pedaço; não caia sorte sobre ela;

[[v26-24-7]]

^<<v26-24-7,7>>^ Porque o seu sangue está no meio dela, sobre uma penha descalvada o pôs; não o derramou sobre a terra, para o cobrir com pó.

[[v26-24-8]]

^<<v26-24-8,8>>^ Para fazer subir a indignação, para tomar vingança, eu pus o seu sangue numa penha descalvada, para que não fosse coberto.

[[v26-24-9]]

^<<v26-24-9,9>>^ Portanto, assim diz o Senhor DEUS: Ai da cidade sanguinária! Também eu farei uma grande fogueira.

[[v26-24-10]]

^<<v26-24-10,10>>^ Amontoa muita lenha, acende o fogo, ferve bem a carne, e tempera o caldo, e ardam os ossos.

[[v26-24-11]]

^<<v26-24-11,11>>^ Então a porás vazia sobre as suas brasas, para que ela aqueça, e se queime o seu cobre, e se funda a sua imundícia no meio dela, e se consuma a sua escuma.

[[v26-24-12]]

^<<v26-24-12,12>>^ Ela com mentiras se cansou; e não saiu dela a sua muita escuma; ao fogo irá a sua escuma.

[[v26-24-13]]

^<<v26-24-13,13>>^ Na imundícia está a infâmia, porquanto te purifiquei, e não permaneceste pura; nunca mais serás purificada da tua imundícia, enquanto eu não fizer descansar sobre ti a minha indignação.

[[v26-24-14]]

^<<v26-24-14,14>>^ Eu, o SENHOR, o disse: viva isso, e o farei, não me tornarei atrás, e não pouparei, nem me arrependerei; conforme os teus caminhos, e conforme os teus feitos, te julgarão, diz o Senhor DEUS.

[[v26-24-15]]

^<<v26-24-15,15>>^ E veio a mim a palavra do Senhor, dizendo:

[[v26-24-16]]

^<<v26-24-16,16>>^ Filho do homem, eis que, de um golpe tirarei de ti o desejo dos teus olhos, mas não lamentarás, nem chorarás, nem te correrão as lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Geme em silêncio, não faças luto por mortos; ata o teu turbante, e põe nos pés os teus sapatos, e não cubras os teus lábios, e não comas o pão dos homens.

[[v26-24-18]]

^<<v26-24-18,18>>^ E falei ao povo pela manhã, e à tarde morreu minha mulher; e fiz pela manhã como me foi mandado.

[[v26-24-19]]

^<<v26-24-19,19>>^ E o povo me disse: Porventura não nos farás saber o que significam para nós estas coisas que estás fazendo?

[[v26-24-20]]

^<<v26-24-20,20>>^ E eu lhes disse: Veio a mim a palavra do Senhor, dizendo:

[[v26-24-21]]

^<<v26-24-21,21>>^ Dize à casa de Israel: Assim diz o Senhor DEUS: Eis que eu profanarei o meu santuário, a glória da vossa força, o desejo dos vossos olhos, e o anelo das vossas almas; e vossos filhos e vossas filhas, que deixastes, cairão à espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ E fareis como eu fiz; não vos cobrireis os lábios, e não comereis o pão dos homens.

[[v26-24-23]]

^<<v26-24-23,23>>^ E tereis nas cabeças os vossos turbantes, e os vossos sapatos nos pés; não lamentareis, nem chorareis, mas definhar-vos-eis nas vossas maldades, e gemereis uns com os outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Assim vos servirá Ezequiel de sinal; conforme tudo quanto ele fez, fareis; quando isso suceder, sabereis que eu sou o Senhor DEUS.

[[v26-24-25]]

^<<v26-24-25,25>>^ E quanto a ti, filho do homem, não sucederá que no dia que eu lhes tirar a sua força, a alegria da sua glória, o desejo dos seus olhos, e o anelo de suas almas, com seus filhos e suas filhas,

[[v26-24-26]]

^<<v26-24-26,26>>^ Nesse dia virá ter contigo aquele que escapar, para te dar notícias pessoalmente?

[[v26-24-27]]

^<<v26-24-27,27>>^ Naquele dia abrir-se-á a tua boca para com aquele que escapar, e falarás, e não mais ficarás mudo; assim virás a ser para eles um sinal, e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]