include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-48-1]]

^<<v26-48-1,1>>^ E estes são os nomes das tribos: desde o extremo norte, ao longo do caminho de Hetlom, indo para Hamate, até Hazar-Enom, termo de Damasco para o norte, ao pé de Hamate, terá Dã uma parte, desde o lado oriental até o ocidental.

[[v26-48-2]]

^<<v26-48-2,2>>^ E junto ao termo de Dã, desde o lado oriental até o ocidental, Aser terá uma porção.

[[v26-48-3]]

^<<v26-48-3,3>>^ E junto ao termo de Aser, desde o lado oriental até o ocidental, Naftali, uma porção.

[[v26-48-4]]

^<<v26-48-4,4>>^ E junto ao termo de Naftali, desde o lado oriental até o lado ocidental, Manassés, uma porção.

[[v26-48-5]]

^<<v26-48-5,5>>^ E junto ao termo de Manassés, desde o lado oriental até o lado ocidental, Efraim, uma porção.

[[v26-48-6]]

^<<v26-48-6,6>>^ E junto ao termo de Efraim, desde o lado oriental até o lado ocidental, Rúben, uma porção.

[[v26-48-7]]

^<<v26-48-7,7>>^ E junto ao termo de Rúben, desde o lado oriental até o lado ocidental, Judá, uma porção.

[[v26-48-8]]

^<<v26-48-8,8>>^ E junto ao termo de Judá, desde o lado oriental até o lado ocidental, será a oferta que haveis de fazer de vinte e cinco mil canas de largura, e de comprimento de cada uma das porções, desde o lado oriental até o lado ocidental; e o santuário estará no meio dela.

[[v26-48-9]]

^<<v26-48-9,9>>^ A oferta que haveis de oferecer ao Senhor será do comprimento de vinte e cinco mil canas, e da largura de dez mil.

[[v26-48-10]]

^<<v26-48-10,10>>^ E ali será a oferta santa para os sacerdotes, medindo para o norte vinte e cinco mil canas de comprimento, e para o ocidente dez mil de largura, e para o oriente dez mil de largura, e para o sul vinte e cinco mil de comprimento; e o santuário do Senhor estará no meio dela.

[[v26-48-11]]

^<<v26-48-11,11>>^ E será para os sacerdotes santificados dentre os filhos de Zadoque, que guardaram a minha ordenança, que não se desviaram, quando os filhos de Israel se extraviaram, como se extraviaram os outros levitas.

[[v26-48-12]]

^<<v26-48-12,12>>^ E eles terão uma oferta, da oferta da terra, lugar santíssimo, junto ao limite dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ E os levitas terão, consoante ao termo dos sacerdotes, vinte e cinco mil canas de comprimento, e de largura dez mil; todo o comprimento será vinte e cinco mil, e a largura dez mil.

[[v26-48-14]]

^<<v26-48-14,14>>^ E não venderão disto, nem trocarão, nem transferirão as primícias da terra, porque é santidade ao Senhor.

[[v26-48-15]]

^<<v26-48-15,15>>^ Mas as cinco mil canas, as que restaram da largura, diante das vinte e cinco mil, ficarão para uso comum, para a cidade, para habitação e para arrabaldes; e a cidade estará no meio delas.

[[v26-48-16]]

^<<v26-48-16,16>>^ E estas serão as suas medidas: o lado do norte de quatro mil e quinhentas canas, o lado do sul de quatro mil e quinhentas, o lado oriental de quatro mil e quinhentas e o lado ocidental de quatro mil e quinhentas.

[[v26-48-17]]

^<<v26-48-17,17>>^ E os arrabaldes da cidade serão para o norte de duzentas e cinqüenta canas, para o sul de duzentas e cinqüenta, para o oriente de duzentas e cinqüenta e para o ocidente de duzentas e cinqüenta.

[[v26-48-18]]

^<<v26-48-18,18>>^ E, quanto ao que restou do comprimento, consoante com a santa oferta, será dez mil para o oriente, e dez mil para o ocidente; e corresponderá à santa oferta; e a sua novidade será para sustento daqueles que servem a cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ E os que servem à cidade, servi-la-ão dentre todas as tribos de Israel.

[[v26-48-20]]

^<<v26-48-20,20>>^ Toda a oferta será de vinte e cinco mil canas com mais vinte e cinco mil; em quadrado oferecereis a oferta santa, com a possessão da cidade.

[[v26-48-21]]

^<<v26-48-21,21>>^ E o que restou será para o príncipe; deste e do outro lado da oferta santa, e da possessão da cidade, diante das vinte e cinco mil canas da oferta, até ao termo do oriente e do ocidente, diante das vinte e cinco mil, até ao termo do ocidente, correspondente às porções, será para o príncipe; e a santa oferta e o santuário da casa estarão no meio dela.

[[v26-48-22]]

^<<v26-48-22,22>>^ E desde a possessão dos levitas, e desde a possessão da cidade, no meio do que pertencer ao príncipe, entre o termo de Judá, e o termo de Benjamim, será isso para o príncipe.

[[v26-48-23]]

^<<v26-48-23,23>>^ E, quanto ao restante das tribos, desde o lado oriental até o lado ocidental, Benjamim terá uma porção.

[[v26-48-24]]

^<<v26-48-24,24>>^ E junto ao termo de Benjamim, desde o lado oriental até o lado ocidental, Simeão terá uma porção.

[[v26-48-25]]

^<<v26-48-25,25>>^ E junto ao termo de Simeão, desde o lado oriental até o lado ocidental, Issacar terá uma porção.

[[v26-48-26]]

^<<v26-48-26,26>>^ E junto ao termo de Issacar, desde o lado oriental até o lado ocidental, Zebulom terá uma porção.

[[v26-48-27]]

^<<v26-48-27,27>>^ E junto ao termo de Zebulom, desde o lado oriental até o lado ocidental, Gade terá uma porção.

[[v26-48-28]]

^<<v26-48-28,28>>^ E junto ao termo de Gade, ao sul, do lado sul, será o termo desde Tamar até às águas da contenda de Cades, junto ao rio até ao mar grande.

[[v26-48-29]]

^<<v26-48-29,29>>^ Esta é a terra que sorteareis em herança às tribos de Israel; e estas são as suas porções, diz o Senhor DEUS.

[[v26-48-30]]

^<<v26-48-30,30>>^ E estas são as saídas da cidade, desde o lado norte: quatro mil e quinhentas canas por medida.

[[v26-48-31]]

^<<v26-48-31,31>>^ E as portas da cidade serão conforme os nomes das tribos de Israel; três portas para o norte: a porta de Rúben uma, a porta de Judá outra, a porta de Levi outra.

[[v26-48-32]]

^<<v26-48-32,32>>^ E do lado oriental quatro mil e quinhentas canas, e três portas, a saber: a porta de José uma, a porta de Benjamim outra, a porta de Dã outra.

[[v26-48-33]]

^<<v26-48-33,33>>^ E do lado sul quatro mil e quinhentas canas por medida, e três portas: a porta de Simeão uma, a porta de Issacar outra, a porta de Zebulom outra.

[[v26-48-34]]

^<<v26-48-34,34>>^ Do lado ocidental quatro mil e quinhentas canas, e as suas três portas: a porta de Gade uma, a porta de Aser outra, a porta de Naftali outra.

[[v26-48-35]]

^<<v26-48-35,35>>^ Dezoito mil canas por medida terá ao redor; e o nome da cidade desde aquele dia será: o Senhor está ali.

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]