include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano, no décimo mês, no dia doze do mês, veio a mim a palavra do SENHOR, dizendo:

[[v26-29-2]]

^<<v26-29-2,2>>^ Filho do homem, dirige o teu rosto contra Faraó, rei do Egito, e profetiza contra ele e contra todo o Egito.

[[v26-29-3]]

^<<v26-29-3,3>>^ Fala, e dize: Assim diz o Senhor DEUS: Eis-me contra ti, ó Faraó, rei do Egito, grande dragão, que pousas no meio dos teus rios, e que dizes: O meu rio é meu, e eu o fiz para mim.

[[v26-29-4]]

^<<v26-29-4,4>>^ Mas eu porei anzóis em teus queixos, e farei que os peixes dos teus rios se apeguem às tuas escamas; e tirar-te-ei do meio dos teus rios, e todos os peixes dos teus rios se apegarem às tuas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ E te deixarei no deserto, a ti e a todo o peixe dos teus rios; sobre a face do campo cairás; não serás recolhido nem ajuntado; aos animais da terra e às aves do céu te dei por mantimento.

[[v26-29-6]]

^<<v26-29-6,6>>^ E saberão todos os moradores do Egito que eu sou o Senhor, porquanto se tornaram um bordão de cana para a casa de Israel.

[[v26-29-7]]

^<<v26-29-7,7>>^ Tomando-te eles pela mão, te quebraste, e lhes rasgaste todo o ombro; e quando se apoiaram em ti, te quebraste, e lhes fazias tremer todos os seus lombos.

[[v26-29-8]]

^<<v26-29-8,8>>^ Portanto, assim diz o Senhor DEUS: Eis que eu trarei sobre ti a espada, e de ti destruirei homem e animal,

[[v26-29-9]]

^<<v26-29-9,9>>^ E a terra do Egito se tornará em desolação e deserto; e saberão que eu sou o Senhor, porquanto disse: O rio é meu, e eu o fiz.

[[v26-29-10]]

^<<v26-29-10,10>>^ Portanto, eis que eu estou contra ti, e contra os teus rios; e tornarei a terra do Egito deserta, em completa desolação, desde a torre de Syene até aos confins da Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Não passará por ela pé de homem, nem pé de animal passará por ela, nem será habitada quarenta anos.

[[v26-29-12]]

^<<v26-29-12,12>>^ Porque tornarei a terra do Egito em desolação no meio das terras desoladas; e as suas cidades entre as cidades desertas se tornarão em desolação por quarenta anos; e espalharei os egípcios entre as nações, e os dispersarei pelas terras.

[[v26-29-13]]

^<<v26-29-13,13>>^ Porém, assim diz o Senhor DEUS: Ao fim de quarenta anos ajuntarei os egípcios dentre os povos entre os quais foram espalhados.

[[v26-29-14]]

^<<v26-29-14,14>>^ E removerei o cativeiro dos egípcios, e os farei voltar à terra de Patros, à terra de sua origem; e serão ali um reino humilde;

[[v26-29-15]]

^<<v26-29-15,15>>^ Mais humilde se fará do que os outros reinos, e nunca mais se exalçará sobre as nações; porque os diminuirei, para que não dominem sobre as nações.

[[v26-29-16]]

^<<v26-29-16,16>>^ E não será mais a confiança da casa de Israel, para lhes trazer à lembrança a sua iniqüidade, quando olharem para trás deles; antes saberão que eu sou o Senhor DEUS.

[[v26-29-17]]

^<<v26-29-17,17>>^ E sucedeu que, no ano vinte e sete, no primeiro mês, no primeiro dia do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-29-18]]

^<<v26-29-18,18>>^ Filho do homem, Nabucodonosor, rei de babilônia, fez com que o seu exército prestasse um grande serviço contra Tiro; toda a cabeça se tornou calva, e todo o ombro se pelou; e não houve paga de Tiro para ele, nem para o seu exército, pelo serviço que prestou contra ela.

[[v26-29-19]]

^<<v26-29-19,19>>^ Portanto, assim diz o Senhor DEUS: Eis que eu darei a Nabucodonosor, rei de babilônia, a terra do Egito; e levará a sua multidão, e tomará o seu despojo, e roubará a sua presa, e isto será a recompensa para o seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Como recompensa do seu trabalho, com que serviu contra ela, lhe dei a terra do Egito; porquanto trabalharam por mim, diz o Senhor DEUS.

[[v26-29-21]]

^<<v26-29-21,21>>^ Naquele dia farei brotar o poder na casa de Israel, e abrirei a tua boca no meio deles; e saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]