include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-30-1]]

^<<v26-30-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-30-2]]

^<<v26-30-2,2>>^ Filho do homem, profetiza, e dize: Assim diz o Senhor DEUS: Gemei: Ah! Aquele dia!

[[v26-30-3]]

^<<v26-30-3,3>>^ Porque está perto o dia, sim, está perto o dia do Senhor; dia nublado; será o tempo dos gentios.

[[v26-30-4]]

^<<v26-30-4,4>>^ A espada virá ao Egito, e haverá grande dor na Etiópia, quando caírem os traspassados no Egito; e tomarão a sua multidão, e serão destruídos os seus fundamentos.

[[v26-30-5]]

^<<v26-30-5,5>>^ Etiópia, Pute e Lude, e toda a mistura de gente, e Cube, e os homens da terra da liga, juntamente com eles cairão à espada.

[[v26-30-6]]

^<<v26-30-6,6>>^ Assim diz o SENHOR: Também cairão os que sustém o Egito, e descerá a soberba de seu poder; desde a torre de Syene ali cairão à espada, diz o Senhor DEUS.

[[v26-30-7]]

^<<v26-30-7,7>>^ E serão desolados no meio das terras assoladas; e as suas cidades estarão no meio das cidades desertas.

[[v26-30-8]]

^<<v26-30-8,8>>^ E saberão que eu sou o Senhor, quando eu puser fogo no Egito, e forem destruídos todos os que lhe davam auxílio.

[[v26-30-9]]

^<<v26-30-9,9>>^ Naquele dia sairão mensageiros de diante de mim em navios, para espantarem a Etiópia descuidada; e haverá neles grandes dores, como no dia do Egito; pois, eis que já vem.

[[v26-30-10]]

^<<v26-30-10,10>>^ Assim diz o Senhor DEUS: Eu, pois, farei cessar a multidão do Egito, por mão de Nabucodonosor, rei de babilônia.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e o seu povo com ele, os mais terríveis das nações, serão levados para destruírem a terra; e desembainharão as suas espadas contra o Egito, e encherão a terra de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ E secarei os rios, e venderei a terra entregando-a na mão dos maus, e assolarei a terra e a sua plenitude pela mão dos estrangeiros; eu, o Senhor, o disse.

[[v26-30-13]]

^<<v26-30-13,13>>^ Assim diz o Senhor DEUS: Também destruirei os ídolos, e farei cessar as imagens de Nofe; e não haverá mais um príncipe da terra do Egito; e porei o temor na terra do Egito.

[[v26-30-14]]

^<<v26-30-14,14>>^ E assolarei a Patros, e porei fogo a Zoã, e executarei juízos em Nô.

[[v26-30-15]]

^<<v26-30-15,15>>^ E derramarei o meu furor sobre Sim, a fortaleza do Egito, e exterminarei a multidão de Nô.

[[v26-30-16]]

^<<v26-30-16,16>>^ E porei fogo no Egito; Sim terá grande dor, e Nô será fendida, e Nofe terá angústias cotidianas.

[[v26-30-17]]

^<<v26-30-17,17>>^ Os jovens de Áven e Pi-Besete cairão à espada, e as cidades irão em cativeiro.

[[v26-30-18]]

^<<v26-30-18,18>>^ E em Tafnes se escurecerá o dia, quando eu quebrar ali os jugos do Egito, e nela cessar a soberba do seu poder; uma nuvem a cobrirá, e suas filhas irão em cativeiro.

[[v26-30-19]]

^<<v26-30-19,19>>^ Assim executarei juízos no Egito, e saberão que eu sou o Senhor.

[[v26-30-20]]

^<<v26-30-20,20>>^ E sucedeu que, no ano undécimo, no primeiro mês, aos sete do mês, veio a mim a palavra do Senhor, dizendo:

[[v26-30-21]]

^<<v26-30-21,21>>^ Filho do homem, eu quebrei o braço de Faraó, rei do Egito, e eis que não foi atado para se lhe aplicar remédios, nem lhe colocarão ligaduras para o atar, a fim de torná-lo forte, para pegar na espada.

[[v26-30-22]]

^<<v26-30-22,22>>^ Portanto assim diz o Senhor DEUS: Eis que eu estou contra Faraó, rei do Egito, e quebrarei os seus braços, assim o forte como o que está quebrado, e farei cair da sua mão a espada.

[[v26-30-23]]

^<<v26-30-23,23>>^ E espalharei os egípcios entre as nações, e os dispersarei pelas terras.

[[v26-30-24]]

^<<v26-30-24,24>>^ E fortalecerei os braços do rei de babilônia, e porei a minha espada na sua mão; mas quebrarei os braços de Faraó, e diante dele gemerá como geme o traspassado.

[[v26-30-25]]

^<<v26-30-25,25>>^ Eu fortalecerei os braços do rei de babilônia, mas os braços de Faraó cairão; e saberão que eu sou o SENHOR, quando eu puser a minha espada na mão do rei de babilônia, e ele a estender sobre a terra do Egito.

[[v26-30-26]]

^<<v26-30-26,26>>^ E espalharei os egípcios entre as nações, e os dispersarei entre as terras; assim saberão que eu sou o Senhor.

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]