include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-47-1]]

^<<v26-47-1,1>>^ Depois disto me fez voltar à porta da casa, e eis que saíam águas por debaixo do umbral da casa para o oriente; porque a face da casa dava para o oriente, e as águas desciam de debaixo, desde o lado direito da casa, ao sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ E ele me fez sair pelo caminho da porta do norte, e me fez dar uma volta pelo caminho de fora, até à porta exterior, pelo caminho que dá para o oriente e eis que corriam as águas do lado direito.

[[v26-47-3]]

^<<v26-47-3,3>>^ E saiu aquele homem para o oriente, tendo na mão um cordel de medir; e mediu mil côvados, e me fez passar pelas águas, águas que me davam pelos artelhos.

[[v26-47-4]]

^<<v26-47-4,4>>^ E mediu mais mil côvados, e me fez passar pelas águas, águas que me davam pelos joelhos; e outra vez mediu mil, e me fez passar pelas águas que me davam pelos lombos.

[[v26-47-5]]

^<<v26-47-5,5>>^ E mediu mais mil, e era um rio, que eu não podia atravessar, porque as águas eram profundas, águas que se deviam passar a nado, rio pelo qual não se podia passar.

[[v26-47-6]]

^<<v26-47-6,6>>^ E disse-me: Viste isto, filho do homem? Então levou-me, e me fez voltar para a margem do rio.

[[v26-47-7]]

^<<v26-47-7,7>>^ E, tendo eu voltado, eis que à margem do rio havia uma grande abundância de árvores, de um e de outro lado.

[[v26-47-8]]

^<<v26-47-8,8>>^ Então disse-me: Estas águas saem para a região oriental, e descem ao deserto, e entram no mar; e, sendo levadas ao mar, as águas tornar-se-ão saudáveis.

[[v26-47-9]]

^<<v26-47-9,9>>^ E será que toda a criatura vivente que passar por onde quer que entrarem estes rios viverá; e haverá muitíssimo peixe, porque lá chegarão estas águas, e serão saudáveis, e viverá tudo por onde quer que entrar este rio.

[[v26-47-10]]

^<<v26-47-10,10>>^ Será também que os pescadores estarão em pé junto dele; desde En-Gedi até En-Eglaim haverá lugar para estender as redes; o seu peixe, segundo a sua espécie, será como o peixe do mar grande, em multidão excessiva.

[[v26-47-11]]

^<<v26-47-11,11>>^ Mas os seus charcos e os seus pântanos não tornar-se-ão saudáveis; serão deixados para sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ E junto ao rio, à sua margem, de um e de outro lado, nascerá toda a sorte de árvore que dá fruto para se comer; não cairá a sua folha, nem acabará o seu fruto; nos seus meses produzirá novos frutos, porque as suas águas saem do santuário; e o seu fruto servirá de comida e a sua folha de remédio.

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim diz o Senhor DEUS: Este será o termo conforme o qual repartireis a terra em herança, segundo as doze tribos de Israel; José terá duas partes.

[[v26-47-14]]

^<<v26-47-14,14>>^ E vós a herdareis, tanto um como o outro; terra sobre a qual levantei a minha mão, para dá-la a vossos pais; assim esta mesma terra vos cairá a vós em herança.

[[v26-47-15]]

^<<v26-47-15,15>>^ E este será o termo da terra; do lado do norte, desde o mar grande, caminho de Hetlom, até à entrada de Zedade;

[[v26-47-16]]

^<<v26-47-16,16>>^ Hamate, Berota, Sibraim, que estão entre o termo de Damasco e o termo de Hamate; Hazer-Haticom, que está junto ao termo de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ E o termo será desde o mar até Hazar-Enom, o termo de Damasco, e na direção do norte, para o norte, está o termo de Hamate. Este será o lado do norte.

[[v26-47-18]]

^<<v26-47-18,18>>^ E o lado do oriente, entre Haurã, e Damasco, e Gileade, e a terra de Israel será o Jordão; desde o termo do norte até ao mar do oriente medireis. Este será o lado do oriente.

[[v26-47-19]]

^<<v26-47-19,19>>^ E o lado do sul, para o sul, será desde Tamar até às águas da contenda de Cades, junto ao ribeiro, até ao mar grande. Este será o lado do sul.

[[v26-47-20]]

^<<v26-47-20,20>>^ E o lado do ocidente será o mar grande, desde o termo do sul até a entrada de Hamate. Este será o lado do ocidente.

[[v26-47-21]]

^<<v26-47-21,21>>^ Repartireis, pois, esta terra entre vós, segundo as tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Será, porém, que a sorteareis para vossa herança, e para a dos estrangeiros que habitam no meio de vós, que gerarão filhos no meio de vós; e vos serão como naturais entre os filhos de Israel; convosco entrarão em herança, no meio das tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ E será que na tribo em que habitar o estrangeiro, ali lhe dareis a sua herança, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]