include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-8-1]]

^<<v26-8-1,1>>^ Sucedeu, pois, no sexto ano, no sexto mês, no quinto dia do mês, estando eu assentado na minha casa, e os anciãos de Judá assentados diante de mim, que ali a mão do Senhor DEUS caiu sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ E olhei, e eis uma semelhança como o aspecto de fogo; desde o aspecto dos seus lombos, e daí para baixo, era fogo; e dos seus lombos e daí para cima como o aspecto de um resplendor como a cor de âmbar.

[[v26-8-3]]

^<<v26-8-3,3>>^ E estendeu a forma de uma mão, e tomou-me pelos cabelos da minha cabeça; e o Espírito me levantou entre a terra e o céu, e levou-me a Jerusalém em visões de Deus, até à entrada da porta do pátio de dentro, que olha para o norte, onde estava o assento da imagem do ciúmes, que provoca ciúmes.

[[v26-8-4]]

^<<v26-8-4,4>>^ E eis que a glória do Deus de Israel estava ali, conforme o aspecto que eu tinha visto no vale.

[[v26-8-5]]

^<<v26-8-5,5>>^ E disse-me: Filho do homem, levanta agora os teus olhos para o caminho do norte. E levantei os meus olhos para o caminho do norte, e eis que ao norte da porta do altar, estava esta imagem de ciúmes na entrada.

[[v26-8-6]]

^<<v26-8-6,6>>^ E disse-me: Filho do homem, vês tu o que eles estão fazendo? As grandes abominações que a casa de Israel faz aqui, para que me afaste do meu santuário? Mas ainda tornarás a ver maiores abominações.

[[v26-8-7]]

^<<v26-8-7,7>>^ E levou-me à porta do átrio; então olhei, e eis que havia um buraco na parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ E disse-me: Filho do homem, cava agora naquela parede. E cavei na parede, e eis que havia uma porta.

[[v26-8-9]]

^<<v26-8-9,9>>^ Então me disse: Entra, e vê as malignas abominações que eles fazem aqui.

[[v26-8-10]]

^<<v26-8-10,10>>^ E entrei, e olhei, e eis que toda a forma de répteis, e animais abomináveis, e de todos os ídolos da casa de Israel, estavam pintados na parede em todo o redor.

[[v26-8-11]]

^<<v26-8-11,11>>^ E estavam em pé diante deles setenta homens dos anciãos da casa de Israel, e Jaazanias, filho de Safã, em pé, no meio deles, e cada um tinha na mão o seu incensário; e subia uma espessa nuvem de incenso.

[[v26-8-12]]

^<<v26-8-12,12>>^ Então me disse: Viste, filho do homem, o que os anciãos da casa de Israel fazem nas trevas, cada um nas suas câmaras pintadas de imagens? Pois dizem: O Senhor não nos vê; o Senhor abandonou a terra.

[[v26-8-13]]

^<<v26-8-13,13>>^ E disse-me: Ainda tornarás a ver maiores abominações, que estes fazem.

[[v26-8-14]]

^<<v26-8-14,14>>^ E levou-me à entrada da porta da casa do Senhor, que está do lado norte, e eis que estavam ali mulheres assentadas chorando a Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ E disse-me: Vês isto, filho do homem? Ainda tornarás a ver abominações maiores do que estas.

[[v26-8-16]]

^<<v26-8-16,16>>^ E levou-me para o átrio interior da casa do Senhor, e eis que estavam à entrada do templo do Senhor, entre o pórtico e o altar, cerca de vinte e cinco homens, de costas para o templo do Senhor, e com os rostos para o oriente; e eles, virados para o oriente adoravam o sol.

[[v26-8-17]]

^<<v26-8-17,17>>^ Então me disse: Vês isto, filho do homem? Há porventura coisa mais leviana para a casa de Judá, do que tais abominações, que fazem aqui? Havendo enchido a terra de violência, tornam a irritar-me; e ei-los a chegar o ramo ao seu nariz.

[[v26-8-18]]

^<<v26-8-18,18>>^ Por isso também eu os tratarei com furor; o meu olho não poupará, nem terei piedade; ainda que me gritem aos ouvidos com grande voz, contudo não os ouvirei.

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]