include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-34-1]]

^<<v26-34-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ Filho do homem, profetiza contra os pastores de Israel; profetiza, e dize aos pastores: Assim diz o Senhor DEUS: Ai dos pastores de Israel que se apascentam a si mesmos! Não devem os pastores apascentar as ovelhas?

[[v26-34-3]]

^<<v26-34-3,3>>^ Comeis a gordura, e vos vestis da lã; matais o cevado; mas não apascentais as ovelhas.

[[v26-34-4]]

^<<v26-34-4,4>>^ As fracas não fortalecestes, e a doente não curastes, e a quebrada não ligastes, e a desgarrada não tornastes a trazer, e a perdida não buscastes; mas dominais sobre elas com rigor e dureza.

[[v26-34-5]]

^<<v26-34-5,5>>^ Assim se espalharam, por não haver pastor, e tornaram-se pasto para todas as feras do campo, porquanto se espalharam.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andaram desgarradas por todos os montes, e por todo o alto outeiro; sim, as minhas ovelhas andaram espalhadas por toda a face da terra, sem haver quem perguntasse por elas, nem quem as buscasse.

[[v26-34-7]]

^<<v26-34-7,7>>^ Portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-8]]

^<<v26-34-8,8>>^ Vivo eu, diz o Senhor DEUS, que, porquanto as minhas ovelhas foram entregues à rapina, e as minhas ovelhas vieram a servir de pasto a todas as feras do campo, por falta de pastor, e os meus pastores não procuraram as minhas ovelhas; e os pastores apascentaram a si mesmos, e não apascentaram as minhas ovelhas;

[[v26-34-9]]

^<<v26-34-9,9>>^ Portanto, ó pastores, ouvi a palavra do Senhor:

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o Senhor DEUS: Eis que eu estou contra os pastores; das suas mãos demandarei as minhas ovelhas, e eles deixarão de apascentar as ovelhas; os pastores não se apascentarão mais a si mesmos; e livrarei as minhas ovelhas da sua boca, e não lhes servirão mais de pasto.

[[v26-34-11]]

^<<v26-34-11,11>>^ Porque assim diz o Senhor DEUS: Eis que eu, eu mesmo, procurarei pelas minhas ovelhas, e as buscarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como o pastor busca o seu rebanho, no dia em que está no meio das suas ovelhas dispersas, assim buscarei as minhas ovelhas; e livrá-las-ei de todos os lugares por onde andam espalhadas, no dia nublado e de escuridão.

[[v26-34-13]]

^<<v26-34-13,13>>^ E tirá-las-ei dos povos, e as congregarei dos países, e as trarei à sua própria terra, e as apascentarei nos montes de Israel, junto aos rios, e em todas as habitações da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Em bons pastos as apascentarei, e nos altos montes de Israel será o seu aprisco; ali se deitarão num bom redil, e pastarão em pastos gordos nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo apascentarei as minhas ovelhas, e eu as farei repousar, diz o Senhor DEUS.

[[v26-34-16]]

^<<v26-34-16,16>>^ A perdida buscarei, e a desgarrada tornarei a trazer, e a quebrada ligarei, e a enferma fortalecerei; mas a gorda e a forte destruirei; apascentá-las-ei com juízo.

[[v26-34-17]]

^<<v26-34-17,17>>^ E quanto a vós, ó ovelhas minhas, assim diz o Senhor DEUS: Eis que eu julgarei entre ovelhas e ovelhas, entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Acaso não vos basta pastar os bons pastos, senão que pisais o resto de vossos pastos aos vossos pés? E não vos basta beber as águas claras, senão que sujais o resto com os vossos pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ E quanto às minhas ovelhas elas pastarão o que haveis pisado com os vossos pés, e beberão o que haveis sujado com os vossos pés.

[[v26-34-20]]

^<<v26-34-20,20>>^ Por isso o Senhor DEUS assim lhes diz: Eis que eu, eu mesmo, julgarei entre a ovelha gorda e a ovelha magra.

[[v26-34-21]]

^<<v26-34-21,21>>^ Porquanto com o lado e com o ombro dais empurrões, e com os vossos chifres escorneais todas as fracas, até que as espalhais para fora.

[[v26-34-22]]

^<<v26-34-22,22>>^ Portanto livrarei as minhas ovelhas, para que não sirvam mais de rapina, e julgarei entre ovelhas e ovelhas.

[[v26-34-23]]

^<<v26-34-23,23>>^ E suscitarei sobre elas um só pastor, e ele as apascentará; o meu servo Davi é que as apascentará; ele lhes servirá de pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ E eu, o Senhor, lhes serei por Deus, e o meu servo Davi será príncipe no meio delas; eu, o Senhor, o disse.

[[v26-34-25]]

^<<v26-34-25,25>>^ E farei com elas uma aliança de paz, e acabarei com as feras da terra, e habitarão em segurança no deserto, e dormirão nos bosques.

[[v26-34-26]]

^<<v26-34-26,26>>^ E delas e dos lugares ao redor do meu outeiro, farei uma bênção; e farei descer a chuva a seu tempo; chuvas de bênção serão.

[[v26-34-27]]

^<<v26-34-27,27>>^ E as árvores do campo darão o seu fruto, e a terra dará a sua novidade, e estarão seguras na sua terra; e saberão que eu sou o Senhor, quando eu quebrar as ataduras do seu jugo e as livrar da mão dos que se serviam delas.

[[v26-34-28]]

^<<v26-34-28,28>>^ E não servirão mais de rapina aos gentios, as feras da terra nunca mais as devorarão; e habitarão seguramente, e ninguém haverá que as espante.

[[v26-34-29]]

^<<v26-34-29,29>>^ E lhes levantarei uma plantação de renome, e nunca mais serão consumidas pela fome na terra, nem mais levarão sobre si o opróbrio dos gentios.

[[v26-34-30]]

^<<v26-34-30,30>>^ Saberão, porém, que eu, o SENHOR seu Deus, estou com elas, e que elas são o meu povo, a casa de Israel, diz o Senhor DEUS.

[[v26-34-31]]

^<<v26-34-31,31>>^ Vós, pois, ó ovelhas minhas, ovelhas do meu pasto; homens sois; porém eu sou o vosso Deus, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]