include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-17-1]]

^<<v26-17-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-17-2]]

^<<v26-17-2,2>>^ Filho do homem, propõe um enigma, e profere uma parábola para com a casa de Israel.

[[v26-17-3]]

^<<v26-17-3,3>>^ E disse: Assim diz o Senhor DEUS: Uma grande águia, de grandes asas, de plumagem comprida, e cheia de penas de várias cores, veio ao Líbano e levou o mais alto ramo de um cedro.

[[v26-17-4]]

^<<v26-17-4,4>>^ E arrancou a ponta mais alta dos seus renovos, e a levou a uma terra de mercancia; numa cidade de mercadores a pôs.

[[v26-17-5]]

^<<v26-17-5,5>>^ Tomou da semente da terra, e a lançou num solo frutífero; tomando-a, colocou-a junto às muitas águas, plantando-a como salgueiro.

[[v26-17-6]]

^<<v26-17-6,6>>^ E brotou, e tornou-se numa videira muito larga, de pouca altura, virando-se para ela os seus ramos, porque as suas raízes estavam debaixo dela; e tornou-se numa videira, e produzia sarmentos, e brotava renovos.

[[v26-17-7]]

^<<v26-17-7,7>>^ E houve mais uma grande águia, de grandes asas, e cheia de penas; e eis que esta videira lançou para ela as suas raízes, e estendeu para ela os seus ramos, desde as covas do seu plantio, para que a regasse.

[[v26-17-8]]

^<<v26-17-8,8>>^ Num bom campo, junto a muitas águas, estava ela plantada, para produzir ramos, e para dar fruto, a fim de que fosse videira excelente.

[[v26-17-9]]

^<<v26-17-9,9>>^ Dize: Assim diz o Senhor DEUS: Porventura há de prosperar? Não lhe arrancará as suas raízes, e não cortará o seu fruto, para que se seque? Para que sequem todas as folhas de seus renovos, e isto não com grande força, nem muita gente, para arrancá-la pelas suas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ Mas, estando plantada, prosperará? Porventura, tocando-lhe vento oriental, de todo não se secará? Nas covas do seu plantio se secará.

[[v26-17-11]]

^<<v26-17-11,11>>^ Então veio a mim a palavra do Senhor, dizendo:

[[v26-17-12]]

^<<v26-17-12,12>>^ Dize agora à casa rebelde: Não sabeis o que significam estas coisas? Dize: Eis que veio o rei de babilônia a Jerusalém, e tomou o seu rei e os seus príncipes, e os levou consigo para babilônia.

[[v26-17-13]]

^<<v26-17-13,13>>^ E tomou um da descendência real, e fez aliança com ele, e o fez prestar juramento; e tomou consigo os poderosos da terra,

[[v26-17-14]]

^<<v26-17-14,14>>^ Para que o reino ficasse humilhado, e não se levantasse, embora, guardando a sua aliança, pudesse subsistir.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas rebelou-se contra ele, enviando os seus mensageiros ao Egito, para que se lhe mandassem cavalos e muita gente. Porventura prosperará ou escapará aquele que faz tais coisas, ou quebrará a aliança, e ainda escapará?

[[v26-17-16]]

^<<v26-17-16,16>>^ Vivo eu, diz o Senhor DEUS, que no lugar em que habita o rei que o fez reinar, cujo juramento desprezou, e cuja aliança quebrou, sim, com ele no meio de babilônia certamente morrerá.

[[v26-17-17]]

^<<v26-17-17,17>>^ E Faraó, nem com grande exército, nem com uma companhia numerosa, fará coisa alguma com ele em guerra, levantando trincheiras e edificando baluartes, para destruir muitas vidas.

[[v26-17-18]]

^<<v26-17-18,18>>^ Porque desprezou o juramento, quebrando a aliança; eis que ele tinha dado a sua mão; contudo fez todas estas coisas; não escapará.

[[v26-17-19]]

^<<v26-17-19,19>>^ Portanto, assim diz o Senhor DEUS: Vivo eu, que o meu juramento, que desprezou, e a minha aliança, que quebrou, isto farei recair sobre a sua cabeça.

[[v26-17-20]]

^<<v26-17-20,20>>^ E estenderei sobre ele a minha rede, e ficará preso no meu laço; e o levarei a babilônia, e ali entrarei em juízo com ele por causa da rebeldia que praticou contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ E todos os seus fugitivos, com todas as suas tropas, cairão à espada, e os que restarem serão espalhados a todo o vento; e sabereis que eu, o Senhor, o disse.

[[v26-17-22]]

^<<v26-17-22,22>>^ Assim diz o Senhor DEUS: Também eu tomarei um broto do topo do cedro, e o plantarei; do principal dos seus renovos cortarei o mais tenro, e o plantarei sobre um monte alto e sublime.

[[v26-17-23]]

^<<v26-17-23,23>>^ No monte alto de Israel o plantarei, e produzirá ramos, e dará fruto, e se fará um cedro excelente; e habitarão debaixo dele aves de toda plumagem, à sombra dos seus ramos habitarão.

[[v26-17-24]]

^<<v26-17-24,24>>^ Assim saberão todas as árvores do campo que eu, o Senhor, abati a árvore alta, elevei a árvore baixa, sequei a árvore verde, e fiz reverdecer a árvore seca; eu, o Senhor, o disse, e o fiz.

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]