include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-40-1]]

^<<v26-40-1,1>>^ No ano vinte e cinco do nosso cativeiro, no princípio do ano, no décimo dia do mês, catorze anos depois que a cidade foi conquistada, naquele mesmo dia veio sobre mim a mão do SENHOR, e me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Em visões de Deus me levou à terra de Israel, e me pôs sobre um monte muito alto, sobre o qual havia como que um edifício de cidade para o lado sul.

[[v26-40-3]]

^<<v26-40-3,3>>^ E, havendo-me levado ali, eis que um homem cuja aparência era como a do bronze, tendo um cordel de linho na sua mão e uma cana de medir, e estava em pé na porta.

[[v26-40-4]]

^<<v26-40-4,4>>^ E disse-me o homem: Filho do homem, vê com os teus olhos, e ouve com os teus ouvidos, e põe no teu coração tudo quanto eu te fizer ver; porque para to mostrar foste tu aqui trazido; anuncia, pois, à casa de Israel tudo quanto vires.

[[v26-40-5]]

^<<v26-40-5,5>>^ E havia um muro fora da casa, em seu redor, e na mão do homem uma cana de medir, de seis côvados, cada um dos quais tinha um côvado e um palmo; e ele mediu a largura do edifício, uma cana, e a altura, uma cana.

[[v26-40-6]]

^<<v26-40-6,6>>^ Então veio à porta que olhava para o caminho do oriente, e subiu pelos seus degraus; mediu o umbral da porta, uma cana de largo, e o outro umbral, uma cana de largo.

[[v26-40-7]]

^<<v26-40-7,7>>^ E cada câmara tinha uma cana de comprido, e uma cana de largo, e o espaço entre os aposentos era de cinco côvados; e o umbral da porta, ao pé do vestíbulo da porta, por dentro, era de uma cana.

[[v26-40-8]]

^<<v26-40-8,8>>^ Também mediu o vestíbulo da porta, por dentro, uma cana.

[[v26-40-9]]

^<<v26-40-9,9>>^ Então mediu o vestíbulo da porta, que tinha oito côvados, e os seus pilares, dois côvados, e este vestíbulo da porta, estava por dentro.

[[v26-40-10]]

^<<v26-40-10,10>>^ As câmaras da porta para o lado do oriente eram três de um lado e três do outro; a mesma medida era a dos três; também os pilares de um lado e do outro tinham a mesma medida.

[[v26-40-11]]

^<<v26-40-11,11>>^ Mediu mais a largura da entrada da porta, que era de dez côvados; e o comprimento da porta, treze côvados.

[[v26-40-12]]

^<<v26-40-12,12>>^ E o espaço em frente das câmaras era de um côvado, e de um côvado o espaço do outro lado; e cada câmara tinha seis côvados de um lado e seis côvados do outro.

[[v26-40-13]]

^<<v26-40-13,13>>^ Então mediu a porta desde o telhado de uma câmara até ao telhado da outra, vinte e cinco côvados de largo, porta contra porta.

[[v26-40-14]]

^<<v26-40-14,14>>^ Fez também os pilares, de sessenta côvados, cada pilar, do átrio, em redor da porta.

[[v26-40-15]]

^<<v26-40-15,15>>^ E, desde a face da porta da entrada até à face do vestíbulo da porta interior, havia cinqüenta côvados.

[[v26-40-16]]

^<<v26-40-16,16>>^ Havia também janelas estreitas nas câmaras, e nos seus pilares, dentro da porta ao redor, e da mesma sorte nos vestíbulos; e as janelas estavam ao redor, na parte de dentro, e nos pilares havia palmeiras.

[[v26-40-17]]

^<<v26-40-17,17>>^ E ele me levou ao átrio exterior, e eis que havia nele câmaras, e um pavimento que estava feito no átrio em redor; trinta câmaras havia naquele pavimento.

[[v26-40-18]]

^<<v26-40-18,18>>^ E o pavimento do lado das portas era proporcional ao comprimento das portas; o pavimento estava mais baixo.

[[v26-40-19]]

^<<v26-40-19,19>>^ E mediu a largura desde a dianteira da porta inferior até a dianteira do átrio interior, por fora, cem côvados, do lado do oriente e do norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ E, quanto à porta que olhava para o caminho do norte, no átrio exterior, ele mediu o seu comprimento e a sua largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ E as suas câmaras eram três de um lado, e três do outro, e os seus pilares e os seus arcos eram da medida da primeira porta: cinqüenta côvados era o seu comprimento, e a largura vinte e cinco côvados.

[[v26-40-22]]

^<<v26-40-22,22>>^ E as suas janelas, e os seus arcos, e as suas palmeiras, eram da medida da porta que olhava para o caminho do oriente; e subia-se para ela por sete degraus, e os seus arcos estavam diante dela.

[[v26-40-23]]

^<<v26-40-23,23>>^ E a porta do átrio interior estava defronte da porta do norte bem como da do oriente; e mediu de porta a porta cem côvados.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então ele me levou ao caminho do sul, e eis que havia ali uma porta que olhava para o caminho do sul, e mediu os seus pilares e os seus arcos conforme estas medidas.

[[v26-40-25]]

^<<v26-40-25,25>>^ E havia também janelas em redor dos seus arcos, como as outras janelas; cinqüenta côvados era o comprimento, e a largura vinte e cinco côvados.

[[v26-40-26]]

^<<v26-40-26,26>>^ E de sete degraus eram as suas subidas, e os seus arcos estavam diante delas; e tinha palmeiras, uma de um lado e outra do outro, nos seus pilares.

[[v26-40-27]]

^<<v26-40-27,27>>^ Também havia uma porta no átrio interior para o caminho do sul; e mediu de porta a porta, para o caminho do sul, cem côvados.

[[v26-40-28]]

^<<v26-40-28,28>>^ Então me levou ao átrio interior pela porta do sul; e mediu a porta do sul, conforme estas medidas.

[[v26-40-29]]

^<<v26-40-29,29>>^ E as suas câmaras, e os seus pilares, e os seus arcos eram conforme estas medidas; e tinham também janelas ao redor dos seus arcos; o comprimento era de cinqüenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-30]]

^<<v26-40-30,30>>^ E havia arcos em redor; o comprimento era de vinte e cinco côvados, e a largura de cinco côvados.

[[v26-40-31]]

^<<v26-40-31,31>>^ E os seus arcos estavam na direção do átrio exterior, e havia palmeiras nos seus pilares; e de oito degraus eram as suas subidas.

[[v26-40-32]]

^<<v26-40-32,32>>^ Depois me levou ao átrio interior, para o caminho do oriente, e mediu a porta conforme estas medidas;

[[v26-40-33]]

^<<v26-40-33,33>>^ E também as suas câmaras, e os seus pilares, e os seus arcos, conforme estas medidas; e havia também janelas em redor dos seus arcos; o comprimento de cinqüenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-34]]

^<<v26-40-34,34>>^ E os seus arcos estavam no átrio de fora; também havia palmeiras nos seus pilares de um e de outro lado; e eram as suas subidas de oito degraus.

[[v26-40-35]]

^<<v26-40-35,35>>^ Então me levou à porta do norte, e mediu conforme estas medidas;

[[v26-40-36]]

^<<v26-40-36,36>>^ As suas câmaras, os seus pilares, e os seus arcos; também tinha janelas em redor; o comprimento era de cinqüenta côvados, e a largura de vinte e cinco côvados.

[[v26-40-37]]

^<<v26-40-37,37>>^ E os seus pilares estavam no átrio exterior; também havia palmeiras nos seus pilares de um e de outro lado; e eram as suas subidas de oito degraus.

[[v26-40-38]]

^<<v26-40-38,38>>^ E as suas câmaras e as suas entradas estavam junto aos pilares das portas onde lavavam o holocausto.

[[v26-40-39]]

^<<v26-40-39,39>>^ E no vestíbulo da porta havia duas mesas de um lado, e duas mesas do outro, para nelas se matar o holocausto e a oferta pelo pecado e pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ Também do lado de fora da subida para a entrada da porta do norte havia duas mesas; e do outro lado, que estava no vestíbulo da porta, havia duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Quatro mesas de um lado, e quatro mesas do outro; aos lados da porta oito mesas, sobre as quais imolavam.

[[v26-40-42]]

^<<v26-40-42,42>>^ E as quatro mesas para o holocausto eram de pedras lavradas; o comprimento era de um côvado e meio, e a largura de um côvado e meio, e a altura de um côvado; e sobre elas se punham os instrumentos com que imolavam o holocausto e o sacrifício.

[[v26-40-43]]

^<<v26-40-43,43>>^ E os ganchos de um palmo de comprimento, estavam fixos por dentro em redor, e sobre as mesas estava a carne da oferta.

[[v26-40-44]]

^<<v26-40-44,44>>^ E fora da porta interior estavam as câmaras dos cantores, no átrio de dentro, que estava ao lado da porta do norte e olhava para o caminho do sul; uma estava ao lado da porta do oriente, e olhava para o caminho do norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ E ele me disse: Esta câmara que olha para o caminho do sul é para os sacerdotes que têm a guarda da casa.

[[v26-40-46]]

^<<v26-40-46,46>>^ Mas a câmara que olha para o caminho do norte é para os sacerdotes que têm a guarda do altar; são estes os filhos de Zadoque, que se chegam ao Senhor, dentre os filhos de Levi, para o servir.

[[v26-40-47]]

^<<v26-40-47,47>>^ E mediu o átrio; o comprimento de cem côvados e a largura de cem côvados, um quadrado; e o altar estava diante da casa.

[[v26-40-48]]

^<<v26-40-48,48>>^ Então me levou ao vestíbulo da casa, e mediu a cada pilar do vestíbulo, cinco côvados de um lado, e cinco côvados do outro; e a largura da porta, três côvados de um lado, e três côvados do outro.

[[v26-40-49]]

^<<v26-40-49,49>>^ O comprimento do vestíbulo era de vinte côvados, e a largura de onze côvados, e era por degraus, que se subia a ele; e havia colunas junto aos pilares, uma de um lado e outra do outro.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]