include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-4-1]]

^<<v26-4-1,1>>^ Tu, pois, ó filho do homem, toma um tijolo, e pô-lo-ás diante de ti, e grava nele a cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ E põe contra ela um cerco, e edifica contra ela uma fortificação, e levanta contra ela uma trincheira, e põe contra ela arraiais, e põe-lhe aríetes em redor.

[[v26-4-3]]

^<<v26-4-3,3>>^ E tu toma uma sertã de ferro, e põe-na por muro de ferro entre ti e a cidade; e dirige para ela o teu rosto, e assim será cercada, e a cercarás; isto servirá de sinal à casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ Tu também deita-te sobre o teu lado esquerdo, e põe a iniqüidade da casa de Israel sobre ele; conforme o número dos dias que te deitares sobre ele, levarás as suas iniqüidades.

[[v26-4-5]]

^<<v26-4-5,5>>^ Porque eu já te tenho fixado os anos da sua iniqüidade, conforme o número dos dias, trezentos e noventa dias; e levarás a iniqüidade da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ E, quando tiveres cumprido estes dias, tornar-te-ás a deitar sobre o teu lado direito, e levarás a iniqüidade da casa de Judá quarenta dias; um dia te dei para cada ano.

[[v26-4-7]]

^<<v26-4-7,7>>^ Dirigirás, pois, o teu rosto para o cerco de Jerusalém, com o teu braço descoberto, e profetizarás contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ E eis que porei sobre ti cordas; assim tu não te voltarás de um lado para o outro, até que cumpras os dias do teu cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ E tu, toma trigo, e cevada, e favas, e lentilhas, e milho e aveia, e coloca-os numa vasilha, e faze deles pão; conforme o número dos dias que tu te deitares sobre o teu lado, trezentos e noventa dias, comerás disso.

[[v26-4-10]]

^<<v26-4-10,10>>^ E a tua comida, que hás de comer, será do peso de vinte siclos por dia; de tempo em tempo a comerás.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também beberás a água por medida, a saber, a sexta parte de um him; de tempo em tempo beberás.

[[v26-4-12]]

^<<v26-4-12,12>>^ E o que comeres será como bolos de cevada, e cozê-los-ás sobre o esterco que sai do homem, diante dos olhos deles.

[[v26-4-13]]

^<<v26-4-13,13>>^ E disse o Senhor: Assim comerão os filhos de Israel o seu pão imundo, entre os gentios para onde os lançarei.

[[v26-4-14]]

^<<v26-4-14,14>>^ Então disse eu: Ah! Senhor DEUS! Eis que a minha alma não foi contaminada, pois desde a minha mocidade até agora, nunca comi daquilo que morrer de si mesmo, ou que é despedaçado por feras; nem carne abominável entrou na minha boca.

[[v26-4-15]]

^<<v26-4-15,15>>^ E disse-me: Vê, dei-te esterco de vacas, em lugar de esterco de homem; e sobre ele prepararás o teu pão.

[[v26-4-16]]

^<<v26-4-16,16>>^ Disse-me ainda: Filho do homem, eis que eu quebrarei o sustento de pão em Jerusalém, e comerão o pão por peso, e com ansiedade; e a água beberão por medida, e com espanto;

[[v26-4-17]]

^<<v26-4-17,17>>^ Para que lhes falte o pão e a água, e se espantem uns com os outros, e se consumam nas suas iniqüidades.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]