include::./index.adoc[]

[[v26-15-0]]
=== Ezequiel, 15
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-15-1]]

^<<v26-15-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v26-15-2]]

^<<v26-15-2,2>>^ Filho do homem, que mais é a árvore da videira do que qualquer outra árvore, ou do que o sarmento que está entre as árvores do bosque?

[[v26-15-3]]

^<<v26-15-3,3>>^ Toma-se dela madeira para fazer alguma obra? Ou toma-se dela alguma estaca, para que se lhe pendure um vaso?

[[v26-15-4]]

^<<v26-15-4,4>>^ Eis que é lançado no fogo, para ser consumido; ambas as suas extremidades consome o fogo, e o meio dela fica também queimado; serviria porventura para alguma obra?

[[v26-15-5]]

^<<v26-15-5,5>>^ Ora, se estando inteiro, não servia para obra alguma, quanto menos sendo consumido pelo fogo, e, sendo queimado, se faria ainda obra dele?

[[v26-15-6]]

^<<v26-15-6,6>>^ Portanto, assim diz o Senhor DEUS: Como a árvore da videira entre as árvores do bosque, que tenho entregue ao fogo para que seja consumido, assim entregarei os habitantes de Jerusalém.

[[v26-15-7]]

^<<v26-15-7,7>>^ E porei a minha face contra eles; do fogo sairão, mas o fogo os consumirá; e sabereis que eu sou o Senhor, quando tiver posto a minha face contra eles.

[[v26-15-8]]

^<<v26-15-8,8>>^ E tornarei a terra em desolação, porquanto grandemente transgrediram, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[&#60; Capítulo Anterior] | <<v26-15-0,Topo>> | xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[Próximo Capítulo &#62;]