include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-26-1]]

^<<v26-26-1,1>>^ E sucedeu no undécimo ano, ao primeiro do mês, que veio a mim a palavra do SENHOR, dizendo:

[[v26-26-2]]

^<<v26-26-2,2>>^ Filho do homem, visto que Tiro disse contra Jerusalém: Ah! está quebrada a porta dos povos; virou-se para mim; eu me encherei, agora que ela está assolada;

[[v26-26-3]]

^<<v26-26-3,3>>^ Portanto assim diz o Senhor DEUS: Eis que eu estou contra ti, ó Tiro, e farei subir contra ti muitas nações, como o mar faz subir as suas ondas,

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão os muros de Tiro, e derrubarão as suas torres; e eu lhe varrerei o seu pó, e dela farei uma penha descalvada.

[[v26-26-5]]

^<<v26-26-5,5>>^ No meio do mar virá a ser um enxugadouro das redes; porque eu o falei, diz o Senhor DEUS; e servirá de despojo para as nações.

[[v26-26-6]]

^<<v26-26-6,6>>^ E suas filhas, que estão no campo, serão mortas à espada; e saberão que eu sou o Senhor.

[[v26-26-7]]

^<<v26-26-7,7>>^ Porque assim diz o Senhor DEUS: Eis que eu, desde o norte, trarei contra Tiro a Nabucodonosor, rei de babilônia, o rei dos reis, com cavalos, e com carros, e com cavaleiros, e companhias, e muito povo.

[[v26-26-8]]

^<<v26-26-8,8>>^ As tuas filhas que estão no campo, ele as matará à espada, e levantará um baluarte contra ti, e fundará uma trincheira contra ti, e levantará paveses contra ti.

[[v26-26-9]]

^<<v26-26-9,9>>^ E disporá os seus aríetes contra os teus muros, e derrubará as tuas torres com os seus machados.

[[v26-26-10]]

^<<v26-26-10,10>>^ Por causa da multidão de seus cavalos te cobrirá o seu pó; os teus muros tremerão com o estrondo dos cavaleiros, e das rodas, e dos carros, quando ele entrar pelas tuas portas, como os homens entram numa cidade em que se fez brecha.

[[v26-26-11]]

^<<v26-26-11,11>>^ Com os cascos dos seus cavalos pisará todas as tuas ruas; ao teu povo matará à espada, e as tuas fortes colunas cairão por terra.

[[v26-26-12]]

^<<v26-26-12,12>>^ E roubarão as tuas riquezas, e saquearão as tuas mercadorias, e derrubarão os teus muros, e arrazarão as tuas casas agradáveis; e lançarão no meio das águas as tuas pedras, e as tuas madeiras, e o teu pó.

[[v26-26-13]]

^<<v26-26-13,13>>^ E farei cessar o ruído das tuas cantigas, e o som dos tuas harpas não se ouvirá mais.

[[v26-26-14]]

^<<v26-26-14,14>>^ E farei de ti uma penha descalvada; virás a ser um enxugadouro das redes, nunca mais serás edificada; porque eu o SENHOR o falei, diz o Senhor DEUS.

[[v26-26-15]]

^<<v26-26-15,15>>^ Assim diz o Senhor DEUS a Tiro: Porventura não tremerão as ilhas com o estrondo da tua queda, quando gemerem os feridos, quando se fizer uma espantosa matança no meio de ti?

[[v26-26-16]]

^<<v26-26-16,16>>^ E todos os príncipes do mar descerão dos seus tronos, e tirarão de si os seus mantos, e despirão as suas vestes bordadas; se vestirão de tremores, sobre a terra se assentarão, e estremecerão a cada momento; e por tua causa pasmarão.

[[v26-26-17]]

^<<v26-26-17,17>>^ E levantarão uma lamentação sobre ti, e te dirão: Como pereceste, ó bem povoada e afamada cidade, que foste forte no mar; ela e os seus moradores, que atemorizaram a todos os seus habitantes!

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora, estremecerão as ilhas no dia da tua queda; sim, as ilhas, que estão no mar, turbar-se-ão com tua saída.

[[v26-26-19]]

^<<v26-26-19,19>>^ Porque assim diz o Senhor DEUS: Quando eu te fizer uma cidade assolada, como as cidades que não se habitam, quando eu fizer subir sobre ti o abismo, e as muitas águas te cobrirem,

[[v26-26-20]]

^<<v26-26-20,20>>^ Então te farei descer com os que descem à cova, ao povo antigo, e te farei habitar nas mais baixas partes da terra, em lugares desertos antigos, com os que descem à cova, para que não sejas habitada; e estabelecerei a glória na terra dos viventes.

[[v26-26-21]]

^<<v26-26-21,21>>^ Farei de ti um grande espanto, e não mais existirás; e quando te buscarem então nunca mais serás achada para sempre, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]