include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-39-1]]

^<<v26-39-1,1>>^ Tu, pois, ó filho do homem, profetiza ainda contra Gogue, e dize: Assim diz o Senhor DEUS: Eis que eu sou contra ti, ó Gogue, príncipe e chefe de Meseque e de Tubal.

[[v26-39-2]]

^<<v26-39-2,2>>^ E te farei voltar, mas deixarei uma sexta parte de ti, e far-te-ei subir do extremo norte, e te trarei aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ E, com um golpe, tirarei o teu arco da tua mão esquerda, e farei cair as tuas flechas da tua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Nos montes de Israel cairás, tu e todas as tuas tropas, e os povos que estão contigo; e às aves de rapina, de toda espécie, e aos animais do campo, te darei por comida.

[[v26-39-5]]

^<<v26-39-5,5>>^ Sobre a face do campo cairás, porque eu o falei, diz o Senhor DEUS.

[[v26-39-6]]

^<<v26-39-6,6>>^ E enviarei um fogo sobre Magogue e entre os que habitam seguros nas ilhas; e saberão que eu sou o Senhor.

[[v26-39-7]]

^<<v26-39-7,7>>^ E farei conhecido o meu santo nome no meio do meu povo Israel, e nunca mais deixarei profanar o meu santo nome; e os gentios saberão que eu sou o Senhor, o Santo em Israel.

[[v26-39-8]]

^<<v26-39-8,8>>^ Eis que vem, e se cumprirá, diz o Senhor DEUS; este é o dia de que tenho falado.

[[v26-39-9]]

^<<v26-39-9,9>>^ E os habitantes das cidades de Israel sairão, e acenderão o fogo, e queimarão as armas, e os escudos e as rodelas, com os arcos, e com as flechas, e com os bastões de mão, e com as lanças; e acenderão fogo com elas por sete anos.

[[v26-39-10]]

^<<v26-39-10,10>>^ E não trarão lenha do campo, nem a cortarão dos bosques, mas com as armas acenderão fogo; e roubarão aos que os roubaram, e despojarão aos que os despojaram, diz o Senhor DEUS.

[[v26-39-11]]

^<<v26-39-11,11>>^ E sucederá que, naquele dia, darei ali a Gogue um lugar de sepultura em Israel, o vale dos que passam ao oriente do mar; e pararão os que por ele passarem; e ali sepultarão a Gogue, e a toda a sua multidão, e lhe chamarão o vale da multidão de Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ E a casa de Israel os enterrará durante sete meses, para purificar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Sim, todo o povo da terra os enterrará, e será para eles memo-rável dia em que eu for glorificado, diz o Senhor Deus.

[[v26-39-14]]

^<<v26-39-14,14>>^ E separarão homens que incessantemente percorrerão a terra, para que eles, juntamente com os que passam, sepultem os que tiverem ficado sobre a face da terra, para a purificarem; durante sete meses farão esta busca.

[[v26-39-15]]

^<<v26-39-15,15>>^ E os que percorrerem a terra, a qual atravessarão, vendo algum osso de homem, porão ao lado um sinal; até que os enterradores o tenham enterrado no vale da multidão de Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ E também o nome da cidade será Hamona; assim purificarão a terra.

[[v26-39-17]]

^<<v26-39-17,17>>^ Tu, pois, ó filho do homem, assim diz o Senhor DEUS, dize às aves de toda espécie, e a todos os animais do campo: Ajuntai-vos e vinde, congregai-vos de toda parte para o meu sacrifício, que eu ofereci por vós, um sacrifício grande, nos montes de Israel, e comei carne e bebei sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comereis a carne dos poderosos e bebereis o sangue dos príncipes da terra; dos carneiros, dos cordeiros, e dos bodes, e dos bezerros, todos cevados de Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ E comereis a gordura até vos fartardes e bebereis o sangue até vos embebedardes, do meu sacrifício que ofereci por vós.

[[v26-39-20]]

^<<v26-39-20,20>>^ E, à minha mesa, fartar-vos-ei de cavalos, de carros, de poderosos, e de todos os homens de guerra, diz o Senhor DEUS.

[[v26-39-21]]

^<<v26-39-21,21>>^ E eu porei a minha glória entre os gentios e todos os gentios verão o meu juízo, que eu tiver executado, e a minha mão, que sobre elas tiver descarregado.

[[v26-39-22]]

^<<v26-39-22,22>>^ E saberão os da casa de Israel que eu sou o Senhor seu Deus, desde aquele dia em diante.

[[v26-39-23]]

^<<v26-39-23,23>>^ E os gentios saberão que os da casa de Israel, por causa da sua iniqüidade, foram levados em cativeiro, porque se rebelaram contra mim, e eu escondi deles a minha face, e os entreguei nas mãos de seus adversários, e todos caíram à espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Conforme a sua imundícia e conforme as suas transgressões me houve com eles, e escondi deles a minha face.

[[v26-39-25]]

^<<v26-39-25,25>>^ Portanto assim diz o Senhor DEUS: Agora tornarei a trazer os cativos de Jacó, e me compadecerei de toda a casa de Israel; zelarei pelo meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ E levarão sobre si a sua vergonha, e toda a sua rebeldia, com que se rebelaram contra mim, quando eles habitarem seguros na sua terra, sem haver quem os espante.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu os tornar a trazer de entre os povos, e os houver ajuntado das terras de seus inimigos, e eu for santificado neles aos olhos de muitas nações,

[[v26-39-28]]

^<<v26-39-28,28>>^ Então saberão que eu sou o Senhor seu Deus, vendo que eu os fiz ir em cativeiro entre os gentios, e os ajuntarei para voltarem a sua terra, e não mais deixarei lá nenhum deles.

[[v26-39-29]]

^<<v26-39-29,29>>^ Nem lhes esconderei mais a minha face, pois derramarei o meu Espírito sobre a casa de Israel, diz o Senhor DEUS.

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]