include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v26-5-1]]

^<<v26-5-1,1>>^ E tu, ó filho do homem, toma uma faca afiada, como navalha de barbeiro, e a farás passar pela tua cabeça e pela tua barba; então tomarás uma balança de peso, e repartirás os cabelos.

[[v26-5-2]]

^<<v26-5-2,2>>^ Uma terça parte queimarás no fogo, no meio da cidade, quando se cumprirem os dias do cerco; então tomarás outra terça parte, e feri-la-ás com uma faca ao redor dela; e a outra terça parte espalharás ao vento; porque desembainharei a espada atrás deles.

[[v26-5-3]]

^<<v26-5-3,3>>^ Também tomarás dali um pequeno número, e atá-los-ás nas bordas do teu manto.

[[v26-5-4]]

^<<v26-5-4,4>>^ E ainda destes tomarás alguns, e os lançarás no meio do fogo e os queimarás a fogo; e dali sairá um fogo contra toda a casa de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ Assim diz o Senhor DEUS: Esta é Jerusalém; coloquei-a no meio das nações e das terras que estão ao redor dela.

[[v26-5-6]]

^<<v26-5-6,6>>^ Ela, porém, mudou em impiedade os meus juízos, mais do que as nações, e os meus estatutos mais do que as terras que estão ao redor dela; porque rejeitaram os meus juízos e os meus estatutos, e não andaram neles.

[[v26-5-7]]

^<<v26-5-7,7>>^ Portanto assim diz o Senhor DEUS: Porque multiplicastes mais do que as nações, que estão ao redor de vós, e não andastes nos meus estatutos, nem guardastes os meus juízos, nem ainda procedestes segundo os juízos das nações que estão ao redor de vós;

[[v26-5-8]]

^<<v26-5-8,8>>^ Por isso assim diz o Senhor DEUS: Eis que eu, sim eu, estou contra ti; e executarei juízos no meio de ti aos olhos das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ E farei em ti o que nunca fiz, e o que jamais farei, por causa de todas as tuas abominações.

[[v26-5-10]]

^<<v26-5-10,10>>^ Portanto os pais comerão a seus filhos no meio de ti, e os filhos comerão a seus pais; e executarei em ti juízos, e tudo o que restar de ti, espalharei a todos os ventos.

[[v26-5-11]]

^<<v26-5-11,11>>^ Portanto, como eu vivo, diz o Senhor DEUS, certamente, porquanto profanaste o meu santuário com todas as tuas coisas detestáveis, e com todas as tuas abominações, também eu te diminuirei, e o meu olho não te perdoará, nem também terei piedade.

[[v26-5-12]]

^<<v26-5-12,12>>^ Uma terça parte de ti morrerá de peste, e se consumirá de fome no meio de ti; e outra terça parte cairá à espada em redor de ti; e a outra terça parte espalharei a todos os ventos, e desembainharei a espada atrás deles.

[[v26-5-13]]

^<<v26-5-13,13>>^ Assim se cumprirá a minha ira, e satisfarei neles o meu furor, e me consolarei; e saberão que eu, o Senhor, tenho falado no meu zelo, quando eu cumprir neles o meu furor.

[[v26-5-14]]

^<<v26-5-14,14>>^ E pôr-te-ei em desolação, e por objeto de opróbrio entre as nações que estão em redor de ti, aos olhos de todos os que passarem.

[[v26-5-15]]

^<<v26-5-15,15>>^ E será objeto de opróbrio e blasfêmia, instrução e espanto às nações que estão em redor de ti, quando eu executar em ti juízos com ira, e com furor, e com terríveis castigos. Eu, o Senhor, falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ Quando eu enviar as malignas flechas da fome contra eles, que servirão para destruição, as quais eu mandarei para vos destruir, então aumentarei a fome sobre vós, e vos quebrarei o sustento do pão.

[[v26-5-17]]

^<<v26-5-17,17>>^ E enviarei sobre vós a fome, e as feras que te desfilharão; e a peste e o sangue passarão por ti; e trarei a espada sobre ti. Eu, o Senhor, falei.

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]