include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-6-1]]

^<<v38-6-1,1>>^ E outra vez levantei os meus olhos, e vi, e eis que quatro carros saiam dentre dois montes, e estes montes eram montes de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ No primeiro carro eram cavalos vermelhos, e no segundo carro, cavalos pretos,

[[v38-6-3]]

^<<v38-6-3,3>>^ E no terceiro carro, cavalos brancos, e no quarto carro, cavalos malhados, todos eram fortes.

[[v38-6-4]]

^<<v38-6-4,4>>^ E respondi, dizendo ao anjo que falava comigo: Que é isto, senhor meu?

[[v38-6-5]]

^<<v38-6-5,5>>^ E o anjo respondeu, dizendo-me: Estes são os quatro espíritos dos céus, saindo donde estavam perante o Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro em que estão os cavalos pretos, sai para a terra do norte, e os brancos saem atrás deles, e os malhados saem para a terra do sul.

[[v38-6-7]]

^<<v38-6-7,7>>^ E os cavalos fortes saíam, e procuravam ir por diante, para percorrerem a terra. E ele disse: Ide, percorrei a terra. E percorreram a terra.

[[v38-6-8]]

^<<v38-6-8,8>>^ E chamou-me, e falou-me, dizendo: Eis que aqueles que saíram para a terra do norte fizeram repousar o meu Espírito na terra do norte.

[[v38-6-9]]

^<<v38-6-9,9>>^ E a palavra do Senhor veio a mim, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ Toma dos que foram levados cativos, a saber, de Heldai, de Tobias e de Jedaías, os quais vieram de babilônia, e vem tu no mesmo dia, e entra na casa de Josias, filho de Sofonias.

[[v38-6-11]]

^<<v38-6-11,11>>^ Toma, digo, prata e ouro, e faze coroas, e põe-nas na cabeça do sumo sacerdote Josué, filho de Jozadaque.

[[v38-6-12]]

^<<v38-6-12,12>>^ E fala-lhe, dizendo: Assim diz o SENHOR dos Exércitos: Eis aqui o homem cujo nome é RENOVO; ele brotará do seu lugar, e edificará o templo do SENHOR.

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele mesmo edificará o templo do Senhor, e ele levará a glória; assentar-se-á no seu trono e dominará, e será sacerdote no seu trono, e conselho de paz haverá entre ambos os ofícios.

[[v38-6-14]]

^<<v38-6-14,14>>^ E estas coroas serão para Helém, e para Tobias, e para Jedaías, e para Hem, filho de Sofonias, como um memorial no templo do Senhor.

[[v38-6-15]]

^<<v38-6-15,15>>^ E aqueles que estão longe virão, e edificarão no templo do Senhor, e vós sabereis que o Senhor dos Exércitos me tem enviado a vós; e isto sucederá assim, se diligentemente ouvirdes a voz do Senhor vosso Deus.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]