include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-4-1]]

^<<v38-4-1,1>>^ E o anjo que falava comigo voltou, e despertou-me, como a um homem que é despertado do seu sono,

[[v38-4-2]]

^<<v38-4-2,2>>^ E disse-me: Que vês? E eu disse: Olho, e eis que vejo um castiçal todo de ouro, e um vaso de azeite no seu topo, com as suas sete lâmpadas; e sete canudos, um para cada uma das lâmpadas que estão no seu topo.

[[v38-4-3]]

^<<v38-4-3,3>>^ E, por cima dele, duas oliveiras, uma à direita do vaso de azeite, e outra à sua esquerda.

[[v38-4-4]]

^<<v38-4-4,4>>^ E respondi, dizendo ao anjo que falava comigo: Senhor meu, que é isto?

[[v38-4-5]]

^<<v38-4-5,5>>^ Então respondeu o anjo que falava comigo, dizendo-me: Não sabes tu o que é isto? E eu disse: Não, senhor meu.

[[v38-4-6]]

^<<v38-4-6,6>>^ E respondeu-me, dizendo: Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força nem por violência, mas sim pelo meu Espírito, diz o Senhor dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és tu, ó grande monte? Diante de Zorobabel tornar-te-ás uma campina; porque ele trará a pedra angular com aclamações: Graça, graça a ela.

[[v38-4-8]]

^<<v38-4-8,8>>^ E a palavra do Senhor veio novamente a mim, dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ As mãos de Zorobabel têm lançado os alicerces desta casa; também as suas mãos a acabarão, para que saibais que o Senhor dos Exércitos me enviou a vós.

[[v38-4-10]]

^<<v38-4-10,10>>^ Porque, quem despreza o dia das coisas pequenas? Pois esses se alegrarão, vendo o prumo na mão de Zorobabel; esses são os sete olhos do Senhor, que percorrem por toda a terra.

[[v38-4-11]]

^<<v38-4-11,11>>^ Respondi mais, dizendo-lhe: Que são as duas oliveiras à direita e à esquerda do castiçal?

[[v38-4-12]]

^<<v38-4-12,12>>^ E, respondendo-lhe outra vez, disse: Que são aqueles dois ramos de oliveira, que estão junto aos dois tubos de ouro, e que vertem de si azeite dourado?

[[v38-4-13]]

^<<v38-4-13,13>>^ E ele me falou, dizendo: Não sabes tu o que é isto? E eu disse: Não, senhor meu.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele disse: Estes são os dois ungidos, que estão diante do Senhor de toda a terra.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]