include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-14-1]]

^<<v38-14-1,1>>^ Eis que vem o dia do SENHOR, em que teus despojos se repartirão no meio de ti.

[[v38-14-2]]

^<<v38-14-2,2>>^ Porque eu ajuntarei todas as nações para a peleja contra Jerusalém; e a cidade será tomada, e as casas serão saqueadas, e as mulheres forçadas; e metade da cidade sairá para o cativeiro, mas o restante do povo não será extirpado da cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ E o Senhor sairá, e pelejará contra estas nações, como pele- jou, sim, no dia da batalha.

[[v38-14-4]]

^<<v38-14-4,4>>^ E naquele dia estarão os seus pés sobre o monte das Oliveiras, que está defronte de Jerusalém para o oriente; e o monte das Oliveiras será fendido pelo meio, para o oriente e para o ocidente, e haverá um vale muito grande; e metade do monte se apartará para o norte, e a outra metade dele para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ E fugireis pelo vale dos meus montes, pois o vale dos montes chegará até Azel; e fugireis assim como fugistes de diante do terremoto nos dias de Uzias, rei de Judá. Então virá o Senhor meu Deus, e todos os santos contigo.

[[v38-14-6]]

^<<v38-14-6,6>>^ E acontecerá naquele dia, que não haverá preciosa luz, nem espessa escuridão.

[[v38-14-7]]

^<<v38-14-7,7>>^ Mas será um dia conhecido do Senhor; nem dia nem noite será; mas acontecerá que ao cair da tarde haverá luz.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia também acontecerá que sairão de Jerusalém águas vivas, metade delas para o mar oriental, e metade delas para o mar ocidental; no verão e no inverno sucederá isto.

[[v38-14-9]]

^<<v38-14-9,9>>^ E o Senhor será rei sobre toda a terra; naquele dia um será o Senhor, e um será o seu nome.

[[v38-14-10]]

^<<v38-14-10,10>>^ Toda a terra em redor se tornará em planície, desde Geba até Rimom, ao sul de Jerusalém, e ela será exaltada, e habitada no seu lugar, desde a porta de Benjamim até ao lugar da primeira porta, até à porta da esquina, e desde a torre de Hananeel até aos lagares do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ E habitarão nela, e não haverá mais destruição, porque Jerusalém habitará segura.

[[v38-14-12]]

^<<v38-14-12,12>>^ E esta será a praga com que o Senhor ferirá a todos os povos que guerrearam contra Jerusalém: a sua carne apodrecerá, estando eles em pé, e lhes apodrecerão os olhos nas suas órbitas, e a língua lhes apodrecerá na sua boca.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia também acontecerá que haverá da parte do Senhor uma grande perturbação entre eles; porque cada um pegará na mão do seu próximo, e cada um levantará a mão contra o seu próximo.

[[v38-14-14]]

^<<v38-14-14,14>>^ E também Judá pelejará em Jerusalém, e as riquezas de todos os gentios serão ajuntadas ao redor, ouro e prata e roupas em grande abundância.

[[v38-14-15]]

^<<v38-14-15,15>>^ Assim será também a praga dos cavalos, dos mulos, dos camelos e dos jumentos e de todos os animais que estiverem naqueles arraiais, como foi esta praga.

[[v38-14-16]]

^<<v38-14-16,16>>^ E acontecerá que, todos os que restarem de todas as nações que vieram contra Jerusalém, subirão de ano em ano para adorar o Rei, o Senhor dos Exércitos, e para celebrarem a festa dos tabernáculos.

[[v38-14-17]]

^<<v38-14-17,17>>^ E acontecerá que, se alguma das famílias da terra não subir a Jerusalém, para adorar o Rei, o Senhor dos Exércitos, não virá sobre ela a chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ E, se a família dos egípcios não subir, nem vier, não virá sobre ela a chuva; virá sobre eles a praga com que o Senhor ferirá os gentios que não subirem a celebrar a festa dos tabernáculos.

[[v38-14-19]]

^<<v38-14-19,19>>^ Este será o castigo do pecado dos egípcios e o castigo do pecado de todas as nações que não subirem a celebrar a festa dos tabernáculos.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia será gravado sobre as campainhas dos cavalos: SANTIDADE AO SENHOR; e as panelas na casa do SENHOR serão como as bacias diante do altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ E todas as panelas em Jerusalém e Judá serão consagradas ao Senhor dos Exércitos, e todos os que sacrificarem virão, e delas tomarão, e nelas cozerão. E naquele dia não haverá mais cananeu na casa do Senhor dos Exércitos.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]