include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-10-1]]

^<<v38-10-1,1>>^ Pedi ao SENHOR chuva no tempo da chuva serôdia, sim, ao SENHOR que faz relâmpagos; e lhes dará chuvas abundantes, e a cada um erva no campo.

[[v38-10-2]]

^<<v38-10-2,2>>^ Porque os ídolos têm falado vaidade, e os adivinhos têm visto mentira, e contam sonhos falsos; com vaidade consolam, por isso seguem o seu caminho como ovelhas; estão aflitos, porque não há pastor.

[[v38-10-3]]

^<<v38-10-3,3>>^ Contra os pastores se acendeu a minha ira, e castigarei os bodes; mas o Senhor dos Exércitos visitará o seu rebanho, a casa de Judá, e os fará como o seu majestoso cavalo na peleja.

[[v38-10-4]]

^<<v38-10-4,4>>^ Dele sairá a pedra de esquina, dele a estaca, dele o arco de guerra, dele juntamente sairá todo o opressor.

[[v38-10-5]]

^<<v38-10-5,5>>^ E serão como poderosos que na batalha esmagam ao inimigo no lodo das ruas; porque o Senhor estará com eles; e confundirão os que andam montados em cavalos.

[[v38-10-6]]

^<<v38-10-6,6>>^ E fortalecerei a casa de Judá, e salvarei a casa de José, e fá-los- ei voltar, porque me compadeci deles; e serão como se eu não os tivera rejeitado, porque eu sou o Senhor seu Deus, e os ouvirei.

[[v38-10-7]]

^<<v38-10-7,7>>^ E os de Efraim serão como um poderoso, e o seu coração se alegrará como pelo vinho; e seus filhos o verão, e se alegrarão; o seu coração se regozijará no Senhor.

[[v38-10-8]]

^<<v38-10-8,8>>^ Eu lhes assobiarei, e os ajuntarei, porque eu os tenho remido; e multiplicar-se-ão como antes se tinham multiplicado.

[[v38-10-9]]

^<<v38-10-9,9>>^ Ainda que os espalhei por entre os povos, eles se lembrarão de mim em lugares remotos; e viverão com seus filhos, e voltarão.

[[v38-10-10]]

^<<v38-10-10,10>>^ Porque eu os farei voltar da terra do Egito, e os congregarei da Assíria; e trá-los-ei à terra de Gileade e do Líbano, e não se achará lugar bastante para eles.

[[v38-10-11]]

^<<v38-10-11,11>>^ E ele passará pelo mar com angústia, e ferirá as ondas no mar, e todas as profundezas do Nilo se secarão; então será derrubada a soberba da Assíria, e o cetro do Egito se retirará.

[[v38-10-12]]

^<<v38-10-12,12>>^ E eu os fortalecerei no Senhor, e andarão no seu nome, diz o Senhor.

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]