include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-5-1]]

^<<v38-5-1,1>>^ E outra vez levantei os meus olhos, e vi, e eis um rolo volante.

[[v38-5-2]]

^<<v38-5-2,2>>^ E disse-me o anjo: Que vês? E eu disse: Vejo um rolo volante, que tem vinte côvados de comprido e dez côvados de largo.

[[v38-5-3]]

^<<v38-5-3,3>>^ Então disse-me: Esta é a maldição que sairá pela face de toda a terra; porque qualquer que furtar será desarraigado, conforme está estabelecido de um lado do rolo; como também qualquer que jurar falsamente, será desarraigado, conforme está estabelecido do outro lado do rolo.

[[v38-5-4]]

^<<v38-5-4,4>>^ Eu a farei sair, disse o Senhor dos Exércitos, e ela entrará na casa do ladrão, e na casa do que jurar falsamente pelo meu nome; e permanecerá no meio da sua casa, e a consumirá juntamente com a sua madeira e com as suas pedras.

[[v38-5-5]]

^<<v38-5-5,5>>^ E saiu o anjo, que falava comigo, e disse-me: Levanta agora os teus olhos, e vê que é isto que sai.

[[v38-5-6]]

^<<v38-5-6,6>>^ E eu disse: Que é isto? E ele disse: Isto é um efa que sai. Disse ainda: Este é o aspecto deles em toda a terra.

[[v38-5-7]]

^<<v38-5-7,7>>^ E eis que foi levantado um talento de chumbo, e uma mulher estava assentada no meio do efa.

[[v38-5-8]]

^<<v38-5-8,8>>^ E ele disse: Esta é a impiedade. E a lançou dentro do efa; e lançou sobre a boca deste o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ E levantei os meus olhos, e vi, e eis que saíram duas mulheres; e traziam vento nas suas asas, pois tinham asas como as da cegonha; e levantaram o efa entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Então eu disse ao anjo que falava comigo: Para onde levam elas o efa?

[[v38-5-11]]

^<<v38-5-11,11>>^ E ele me disse: Para lhe edificarem uma casa na terra de Sinar; e, estando ela acabada, ele será posto ali na sua base.

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]