include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v38-8-1]]

^<<v38-8-1,1>>^ Depois veio a mim a palavra do SENHOR dos Exércitos, dizendo:

[[v38-8-2]]

^<<v38-8-2,2>>^ Assim diz o Senhor dos Exércitos: Zelei por Sião com grande zelo, e com grande indignação zelei por ela.

[[v38-8-3]]

^<<v38-8-3,3>>^ Assim diz o Senhor: Voltarei para Sião, e habitarei no meio de Jerusalém; e Jerusalém chamar-se-á a cidade da verdade, e o monte do Senhor dos Exércitos, o monte santo.

[[v38-8-4]]

^<<v38-8-4,4>>^ Assim diz o Senhor dos Exércitos: Ainda nas praças de Jerusalém habitarão velhos e velhas; levando cada um, na mão, o seu bordão, por causa da sua muita idade.

[[v38-8-5]]

^<<v38-8-5,5>>^ E as ruas da cidade se encherão de meninos e meninas, que nelas brincarão.

[[v38-8-6]]

^<<v38-8-6,6>>^ Assim diz o Senhor dos Exércitos: Se isto for maravilhoso aos olhos do restante deste povo naqueles dias, será também maravilhoso aos meus olhos? diz o Senhor dos Exércitos.

[[v38-8-7]]

^<<v38-8-7,7>>^ Assim diz o Senhor dos Exércitos: Eis que salvarei o meu povo da terra do oriente e da terra do ocidente;

[[v38-8-8]]

^<<v38-8-8,8>>^ E trá-los-ei, e habitarão no meio de Jerusalém; e eles serão o meu povo, e eu lhes serei o seu Deus em verdade e em justiça.

[[v38-8-9]]

^<<v38-8-9,9>>^ Assim diz o Senhor dos Exércitos: Esforcem-se as vossas mãos, ó vós que nestes dias ouvistes estas palavras da boca dos profetas, que estiveram no dia em que foi posto o fundamento da casa do Senhor dos Exércitos, para que o templo fosse edificado.

[[v38-8-10]]

^<<v38-8-10,10>>^ Porque antes destes dias não tem havido salário para os homens, nem lhes davam ganhos os animais; nem havia paz para o que entrava nem para o que saía, por causa do inimigo, porque eu incitei a todos os homens, cada um contra o seu próximo.

[[v38-8-11]]

^<<v38-8-11,11>>^ Mas agora não serei para com o restante deste povo como nos primeiros dias, diz o Senhor dos Exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ Porque haverá semente de prosperidade; a vide dará o seu fruto, e a terra dará a sua novidade, e os céus darão o seu orvalho; e farei que o restante deste povo herde tudo isto.

[[v38-8-13]]

^<<v38-8-13,13>>^ E há de suceder, ó casa de Judá, e casa de Israel, que, assim como fostes uma maldição entre os gentios, assim vos salvarei, e sereis uma bênção; não temais, esforcem-se as vossas mãos.

[[v38-8-14]]

^<<v38-8-14,14>>^ Porque assim diz o Senhor dos Exércitos: Como pensei fazer-vos mal, quando vossos pais me provocaram à ira, diz o Senhor dos Exércitos, e não me arrependi,

[[v38-8-15]]

^<<v38-8-15,15>>^ Assim tornei a pensar nestes dias fazer o bem a Jerusalém e à casa de Judá; não temais.

[[v38-8-16]]

^<<v38-8-16,16>>^ Estas são as coisas que deveis fazer: Falai a verdade cada um com o seu próximo; executai juízo de verdade e de paz nas vossas portas.

[[v38-8-17]]

^<<v38-8-17,17>>^ E nenhum de vós pense mal no seu coração contra o seu próximo, nem ameis o juramento falso; porque todas estas são coisas que eu odeio diz o Senhor.

[[v38-8-18]]

^<<v38-8-18,18>>^ E a palavra do Senhor dos Exércitos veio a mim, dizendo:

[[v38-8-19]]

^<<v38-8-19,19>>^ Assim diz o Senhor dos Exércitos: O jejum do quarto, e o jejum do quinto, e o jejum do sétimo, e o jejum do décimo mês será para a casa de Judá gozo, alegria, e festividades solenes; amai, pois, a verdade e a paz.

[[v38-8-20]]

^<<v38-8-20,20>>^ Assim diz o Senhor dos Exércitos: Ainda sucederá que virão os povos e os habitantes de muitas cidades.

[[v38-8-21]]

^<<v38-8-21,21>>^ E os habitantes de uma cidade irão à outra, dizendo: Vamos depressa suplicar o favor do Senhor, e buscar o Senhor dos Exércitos; eu também irei.

[[v38-8-22]]

^<<v38-8-22,22>>^ Assim virão muitos povos e poderosas nações, a buscar em Jerusalém ao Senhor dos Exércitos, e a suplicar o favor do Senhor.

[[v38-8-23]]

^<<v38-8-23,23>>^ Assim diz o Senhor dos Exércitos: Naquele dia sucederá que pegarão dez homens, de todas as línguas das nações, pegarão, sim, na orla das vestes de um judeu, dizendo: Iremos convosco, porque temos ouvido que Deus está convosco.

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]