include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-8-1]]

^<<v27-8-1,1>>^ No ano terceiro do reinado do rei Belsazar apareceu-me uma visão, a mim, Daniel, depois daquela que me apareceu no princípio.

[[v27-8-2]]

^<<v27-8-2,2>>^ E vi na visão; e sucedeu que, quando vi, eu estava na cidadela de Susã, na província de Elão; vi, pois, na visão, que eu estava junto ao rio Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ E levantei os meus olhos, e vi, e eis que um carneiro estava diante do rio, o qual tinha dois chifres; e os dois chifres eram altos, mas um era mais alto do que o outro; e o mais alto subiu por último.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi que o carneiro dava marradas para o ocidente, e para o norte e para o sul; e nenhum dos animais lhe podia resistir; nem havia quem pudesse livrar-se da sua mão; e ele fazia conforme a sua vontade, e se engrandecia.

[[v27-8-5]]

^<<v27-8-5,5>>^ E, estando eu considerando, eis que um bode vinha do ocidente sobre toda a terra, mas sem tocar no chão; e aquele bode tinha um chifre insigne entre os olhos.

[[v27-8-6]]

^<<v27-8-6,6>>^ E dirigiu-se ao carneiro que tinha os dois chifres, ao qual eu tinha visto em pé diante do rio, e correu contra ele no ímpeto da sua força.

[[v27-8-7]]

^<<v27-8-7,7>>^ E vi-o chegar perto do carneiro, enfurecido contra ele, e ferindo-o quebrou-lhe os dois chifres, pois não havia força no carneiro para lhe resistir, e o bode o lançou por terra, e o pisou aos pés; não houve quem pudesse livrar o carneiro da sua mão.

[[v27-8-8]]

^<<v27-8-8,8>>^ E o bode se engrandeceu sobremaneira; mas, estando na sua maior força, aquele grande chifre foi quebrado; e no seu lugar subiram outros quatro também insignes, para os quatro ventos do céu.

[[v27-8-9]]

^<<v27-8-9,9>>^ E de um deles saiu um chifre muito pequeno, o qual cresceu muito para o sul, e para o oriente, e para a terra formosa.

[[v27-8-10]]

^<<v27-8-10,10>>^ E se engrandeceu até contra o exército do céu; e a alguns do exército, e das estrelas, lançou por terra, e os pisou.

[[v27-8-11]]

^<<v27-8-11,11>>^ E se engrandeceu até contra o príncipe do exército; e por ele foi tirado o sacrifício contínuo, e o lugar do seu santuário foi lançado por terra.

[[v27-8-12]]

^<<v27-8-12,12>>^ E um exército foi dado contra o sacrifício contínuo, por causa da transgressão; e lançou a verdade por terra, e o fez, e prosperou.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois ouvi um santo que falava; e disse outro santo àquele que falava: Até quando durará a visão do sacrifício contínuo, e da transgressão assoladora, para que sejam entregues o santuário e o exército, a fim de serem pisados?

[[v27-8-14]]

^<<v27-8-14,14>>^ E ele me disse: Até duas mil e trezentas tardes e manhãs; e o santuário será purificado.

[[v27-8-15]]

^<<v27-8-15,15>>^ E aconteceu que, havendo eu, Daniel, tido a visão, procurei o significado, e eis que se apresen- tou diante de mim como que uma semelhança de homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz de homem entre as margens do Ulai, a qual gritou, e disse: Gabriel, dá a entender a este a visão.

[[v27-8-17]]

^<<v27-8-17,17>>^ E veio perto de onde eu estava; e, vindo ele, me amedrontei, e caí sobre o meu rosto; mas ele me disse: Entende, filho do homem, porque esta visão acontecerá no fim do tempo.

[[v27-8-18]]

^<<v27-8-18,18>>^ E, estando ele falando comigo, caí adormecido com o rosto em terra; ele, porém, me tocou, e me fez estar em pé.

[[v27-8-19]]

^<<v27-8-19,19>>^ E disse: Eis que te farei saber o que há de acontecer no último tempo da ira; pois isso pertence ao tempo determinado do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ Aquele carneiro que viste com dois chifres são os reis da Média e da Pérsia,

[[v27-8-21]]

^<<v27-8-21,21>>^ Mas o bode peludo é o rei da Grécia; e o grande chifre que tinha entre os olhos é o primeiro rei;

[[v27-8-22]]

^<<v27-8-22,22>>^ O ter sido quebrado, levantando-se quatro em lugar dele, significa que quatro reinos se levantarão da mesma nação, mas não com a força dele.

[[v27-8-23]]

^<<v27-8-23,23>>^ Mas, no fim do seu reinado, quando acabarem os prevaricadores, se levantará um rei, feroz de semblante, e será entendido em adivinhações.

[[v27-8-24]]

^<<v27-8-24,24>>^ E se fortalecerá o seu poder, mas não pela sua própria força; e destruirá maravilhosamente, e prosperará, e fará o que lhe aprouver; e destruirá os poderosos e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ E pelo seu entendimento também fará prosperar o engano na sua mão; e no seu coração se engrandecerá, e destruirá a muitos que vivem em segurança; e se levantará contra o Príncipe dos príncipes, mas sem mão será quebrado.

[[v27-8-26]]

^<<v27-8-26,26>>^ E a visão da tarde e da manhã que foi falada, é verdadeira. Tu, porém, cerra a visão, porque se refere a dias muito distantes.

[[v27-8-27]]

^<<v27-8-27,27>>^ E eu, Daniel, enfraqueci, e estive enfermo alguns dias; então levantei-me e tratei do negócio do rei. E espantei-me acerca da visão, e não havia quem a entendesse.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]