include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-1-1]]

^<<v27-1-1,1>>^ No ano terceiro do reinado de Jeoiaquim, rei de Judá, veio Nabucodonosor, rei de babilônia, a Jerusalém, e a sitiou.

[[v27-1-2]]

^<<v27-1-2,2>>^ E o Senhor entregou nas suas mãos a Jeoiaquim, rei de Judá, e uma parte dos utensílios da casa de Deus, e ele os levou para a terra de Sinar, para a casa do seu deus, e pôs os utensílios na casa do tesouro do seu deus.

[[v27-1-3]]

^<<v27-1-3,3>>^ E disse o rei a Aspenaz, chefe dos seus eunucos, que trouxesse alguns dos filhos de Israel, e da linhagem real e dos príncipes,

[[v27-1-4]]

^<<v27-1-4,4>>^ Jovens em quem não houvesse defeito algum, de boa aparência, e instruídos em toda a sabedoria, e doutos em ciência, e entendidos no conhecimento, e que tivessem habilidade para assistirem no palácio do rei, e que lhes ensinassem as letras e a língua dos caldeus.

[[v27-1-5]]

^<<v27-1-5,5>>^ E o rei lhes determinou a porção diária, das iguarias do rei, e do vinho que ele bebia, e que assim fossem mantidos por três anos, para que no fim destes pudessem estar diante do rei.

[[v27-1-6]]

^<<v27-1-6,6>>^ E entre eles se achavam, dos filhos de Judá, Daniel, Hananias, Misael e Azarias;

[[v27-1-7]]

^<<v27-1-7,7>>^ E o chefe dos eunucos lhes pôs outros nomes, a saber: a Daniel pôs o de Beltessazar, e a Hananias o de Sadraque, e a Misael o de Mesaque, e a Azarias o de Abednego.

[[v27-1-8]]

^<<v27-1-8,8>>^ E Daniel propôs no seu coração não se contaminar com a porção das iguarias do rei, nem com o vinho que ele bebia; portanto pediu ao chefe dos eunucos que lhe permitisse não se contaminar.

[[v27-1-9]]

^<<v27-1-9,9>>^ Ora, Deus fez com que Daniel achasse graça e misericórdia diante do chefe dos eunucos.

[[v27-1-10]]

^<<v27-1-10,10>>^ E disse o chefe dos eunucos a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida; pois por que veria ele os vossos rostos mais tristes do que os dos outros jovens da vossa idade? Assim porias em perigo a minha cabeça para com o rei.

[[v27-1-11]]

^<<v27-1-11,11>>^ Então disse Daniel ao despenseiro a quem o chefe dos eunucos havia constituído sobre Daniel, Hananias, Misael e Azarias:

[[v27-1-12]]

^<<v27-1-12,12>>^ Experimenta, peço-te, os teus servos dez dias, e que se nos dêem legumes a comer, e água a beber.

[[v27-1-13]]

^<<v27-1-13,13>>^ Então se examine diante de ti a nossa aparência, e a aparência dos jovens que comem a porção das iguarias do rei; e, conforme vires, procederás para com os teus servos.

[[v27-1-14]]

^<<v27-1-14,14>>^ E ele consentiu isto, e os experimentou dez dias.

[[v27-1-15]]

^<<v27-1-15,15>>^ E, ao fim dos dez dias, apareceram os seus semblantes melhores, e eles estavam mais gordos de carne do que todos os jovens que comiam das iguarias do rei.

[[v27-1-16]]

^<<v27-1-16,16>>^ Assim o despenseiro tirou-lhes a porção das iguarias, e o vinho de que deviam beber, e lhes dava legumes.

[[v27-1-17]]

^<<v27-1-17,17>>^ Quanto a estes quatro jovens, Deus lhes deu o conhecimento e a inteligência em todas as letras, e sabedoria; mas a Daniel deu entendimento em toda a visão e sonhos.

[[v27-1-18]]

^<<v27-1-18,18>>^ E ao fim dos dias, em que o rei tinha falado que os trouxessem, o chefe dos eunucos os trouxe diante de Nabucodonosor.

[[v27-1-19]]

^<<v27-1-19,19>>^ E o rei falou com eles; entre todos eles não foram achados outros tais como Daniel, Hananias, Misael e Azarias; portanto ficaram assistindo diante do rei.

[[v27-1-20]]

^<<v27-1-20,20>>^ E em toda a matéria de sabedoria e de discernimento, sobre o que o rei lhes perguntou, os achou dez vezes mais doutos do que todos os magos astrólogos que havia em todo o seu reino.

[[v27-1-21]]

^<<v27-1-21,21>>^ E Daniel permaneceu até ao primeiro ano do rei Ciro.

'''

xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]