include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-12-1]]

^<<v27-12-1,1>>^ E naquele tempo se levantará Miguel, o grande príncipe, que se levanta a favor dos filhos do teu povo, e haverá um tempo de angústia, qual nunca houve, desde que houve nação até àquele tempo; mas naquele tempo livrar-se-á o teu povo, todo aquele que for achado escrito no livro.

[[v27-12-2]]

^<<v27-12-2,2>>^ E muitos dos que dormem no pó da terra ressuscitarão, uns para vida eterna, e outros para vergonha e desprezo eterno.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os que forem sábios, pois, resplandecerão como o fulgor do firmamento; e os que a muitos ensinam a justiça, como as estrelas sempre e eternamente.

[[v27-12-4]]

^<<v27-12-4,4>>^ E tu, Daniel, encerra estas palavras e sela este livro, até ao fim do tempo; muitos correrão de uma parte para outra, e o conhecimento se multiplicará.

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu, Daniel, olhei, e eis que estavam em pé outros dois, um deste lado, à beira do rio, e o outro do outro lado, à beira do rio.

[[v27-12-6]]

^<<v27-12-6,6>>^ E ele disse ao homem vestido de linho, que estava sobre as águas do rio: Quando será o fim destas maravilhas?

[[v27-12-7]]

^<<v27-12-7,7>>^ E ouvi o homem vestido de linho, que estava sobre as águas do rio, o qual levantou ao céu a sua mão direita e a sua mão esquerda, e jurou por aquele que vive eternamente que isso seria para um tempo, tempos e metade do tempo, e quando tiverem acabado de espalhar o poder do povo santo, todas estas coisas serão cumpridas.

[[v27-12-8]]

^<<v27-12-8,8>>^ Eu, pois, ouvi, mas não entendi; por isso eu disse: Senhor meu, qual será o fim destas coisas?

[[v27-12-9]]

^<<v27-12-9,9>>^ E ele disse: Vai, Daniel, porque estas palavras estão fechadas e seladas até ao tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.

[[v27-12-11]]

^<<v27-12-11,11>>^ E desde o tempo em que o sacrifício contínuo for tirado, e posta a abominação desoladora, haverá mil duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Bem-aventurado o que espera e chega até mil trezentos e trinta e cinco dias.

[[v27-12-13]]

^<<v27-12-13,13>>^ Tu, porém, vai até ao fim; porque descansarás, e te levantarás na tua herança, no fim dos dias.

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]