include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-4-1]]

^<<v27-4-1,1>>^ Nabucodonosor rei, a todos os povos, nações e línguas, que moram em toda a terra: Paz vos seja multiplicada.

[[v27-4-2]]

^<<v27-4-2,2>>^ Pareceu-me bem fazer conhecidos os sinais e maravilhas que Deus, o Altíssimo, tem feito para comigo.

[[v27-4-3]]

^<<v27-4-3,3>>^ Quão grandes são os seus sinais, e quão poderosas as suas maravilhas! O seu reino é um reino sempiterno, e o seu domínio de geração em geração.

[[v27-4-4]]

^<<v27-4-4,4>>^ Eu, Nabucodonosor, estava sossegado em minha casa, e próspero no meu palácio.

[[v27-4-5]]

^<<v27-4-5,5>>^ Tive um sonho, que me espantou; e estando eu na minha cama, as imaginações e as visões da minha cabeça me turbaram.

[[v27-4-6]]

^<<v27-4-6,6>>^ Por isso expedi um decreto, para que fossem introduzidos à minha presença todos os sábios de babilônia, para que me fizessem saber a interpretação do sonho.

[[v27-4-7]]

^<<v27-4-7,7>>^ Então entraram os magos, os astrólogos, os caldeus e os adivinhadores, e eu contei o sonho diante deles; mas não me fizeram saber a sua interpretação.

[[v27-4-8]]

^<<v27-4-8,8>>^ Mas por fim entrou na minha presença Daniel, cujo nome é Beltessazar, segundo o nome do meu deus, e no qual há o espírito dos deuses santos; e eu lhe contei o sonho, dizendo:

[[v27-4-9]]

^<<v27-4-9,9>>^ Beltessazar, mestre dos magos, pois eu sei que há em ti o espírito dos deuses santos, e nenhum mistério te é difícil, dize-me as visões do meu sonho que tive e a sua interpretação.

[[v27-4-10]]

^<<v27-4-10,10>>^ Eis, pois, as visões da minha cabeça, estando eu na minha cama: Eu estava assim olhando, e vi uma árvore no meio da terra, cuja altura era grande;

[[v27-4-11]]

^<<v27-4-11,11>>^ Crescia esta árvore, e se fazia forte, de maneira que a sua altura chegava até ao céu; e era vista até aos confins da terra.

[[v27-4-12]]

^<<v27-4-12,12>>^ A sua folhagem era formosa, e o seu fruto abundante, e havia nela sustento para todos; debaixo dela os animais do campo achavam sombra, e as aves do céu faziam morada nos seus ramos, e toda a carne se mantinha dela.

[[v27-4-13]]

^<<v27-4-13,13>>^ Estava vendo isso nas visões da minha cabeça, estando eu na minha cama; e eis que um vigia, um santo, descia do céu,

[[v27-4-14]]

^<<v27-4-14,14>>^ Clamando fortemente, e dizendo assim: Derrubai a árvore, e cortai-lhe os ramos, sacudi as suas folhas, espalhai o seu fruto; afugentem-se os animais de debaixo dela, e as aves dos seus ramos.

[[v27-4-15]]

^<<v27-4-15,15>>^ Mas deixai na terra o tronco com as suas raízes, atada com cadeias de ferro e de bronze, na erva do campo; e seja molhado do orvalho do céu, e seja a sua porção com os animais na erva da terra;

[[v27-4-16]]

^<<v27-4-16,16>>^ Seja mudado o seu coração, para que não seja mais coração de homem, e lhe seja dado coração de animal; e passem sobre ele sete tempos.

[[v27-4-17]]

^<<v27-4-17,17>>^ Esta sentença é por decreto dos vigias, e esta ordem por mandado dos santos, a fim de que conheçam os viventes que o Altíssimo tem domínio sobre o reino dos homens, e o dá a quem quer, e até ao mais humilde dos homens constitui sobre ele.

[[v27-4-18]]

^<<v27-4-18,18>>^ Este sonho eu, rei Nabucodonosor vi. Tu, pois, Beltessazar, dize a interpretação, porque todos os sábios do meu reino não puderam fazer-me saber a sua interpretação, mas tu podes; pois há em ti o espírito dos deuses santos.

[[v27-4-19]]

^<<v27-4-19,19>>^ Então Daniel, cujo nome era Beltessazar, esteve atônito por uma hora, e os seus pensamentos o turbavam; falou, pois, o rei, dizendo: Beltessazar, não te espante o sonho, nem a sua interpretação. Respondeu Beltessazar, dizendo: Senhor meu, seja o sonho contra os que te têm ódio, e a sua interpretação aos teus inimigos.

[[v27-4-20]]

^<<v27-4-20,20>>^ A árvore que viste, que cresceu, e se fez forte, cuja altura chegava até ao céu, e que foi vista por toda a terra;

[[v27-4-21]]

^<<v27-4-21,21>>^ Cujas folhas eram formosas, e o seu fruto abundante, e em que para todos havia sustento, debaixo da qual moravam os animais do campo, e em cujos ramos habitavam as aves do céu;

[[v27-4-22]]

^<<v27-4-22,22>>^ És tu, ó rei, que cresceste, e te fizeste forte; a tua grandeza cresceu, e chegou até ao céu, e o teu domínio até à extremidade da terra.

[[v27-4-23]]

^<<v27-4-23,23>>^ E quanto ao que viu o rei, um vigia, um santo, que descia do céu, e dizia: Cortai a árvore, e destruí-a, mas o tronco com as suas raízes deixai na terra, e atada com cadeias de ferro e de bronze, na erva do campo; e seja molhado do orvalho do céu, e a sua porção seja com os animais do campo, até que passem sobre ele sete tempos;

[[v27-4-24]]

^<<v27-4-24,24>>^ Esta é a interpretação, ó rei; e este é o decreto do Altíssimo, que virá sobre o rei, meu senhor:

[[v27-4-25]]

^<<v27-4-25,25>>^ Serás tirado dentre os homens, e a tua morada será com os animais do campo, e te farão comer erva como os bois, e serás molhado do orvalho do céu; e passar-se-ão sete tempos por cima de ti; até que conheças que o Altíssimo tem domínio sobre o reino dos homens, e o dá a quem quer.

[[v27-4-26]]

^<<v27-4-26,26>>^ E quanto ao que foi falado, que deixassem o tronco com as raízes da árvore, o teu reino voltará para ti, depois que tiveres conhecido que o céu reina.

[[v27-4-27]]

^<<v27-4-27,27>>^ Portanto, ó rei, aceita o meu conselho, e põe fim aos teus pecados, praticando a justiça, e às tuas iniqüidades, usando de misericórdia com os pobres, pois, talvez se prolongue a tua tranqüilidade.

[[v27-4-28]]

^<<v27-4-28,28>>^ Todas estas coisas vieram sobre o rei Nabucodonosor.

[[v27-4-29]]

^<<v27-4-29,29>>^ Ao fim de doze meses, quando passeava no palácio real de babilônia,

[[v27-4-30]]

^<<v27-4-30,30>>^ Falou o rei, dizendo: Não é esta a grande babilônia que eu edifiquei para a casa real, com a força do meu poder, e para glória da minha magnificência?

[[v27-4-31]]

^<<v27-4-31,31>>^ Ainda estava a palavra na boca do rei, quando caiu uma voz do céu: A ti se diz, ó rei Nabucodonosor: Passou de ti o reino.

[[v27-4-32]]

^<<v27-4-32,32>>^ E serás tirado dentre os homens, e a tua morada será com os animais do campo; far-te-ão comer erva como os bois, e passar-se-ão sete tempos sobre ti, até que conheças que o Altíssimo domina sobre o reino dos homens, e o dá a quem quer.

[[v27-4-33]]

^<<v27-4-33,33>>^ Na mesma hora se cumpriu a palavra sobre Nabucodonosor, e foi tirado dentre os homens, e comia erva como os bois, e o seu corpo foi molhado do orvalho do céu, até que lhe cresceu pêlo, como as penas da águia, e as suas unhas como as das aves.

[[v27-4-34]]

^<<v27-4-34,34>>^ Mas ao fim daqueles dias eu, Nabucodonosor, levantei os meus olhos ao céu, e tornou-me a vir o entendimento, e eu bendisse o Altíssimo, e louvei e glorifiquei ao que vive para sempre, cujo domínio é um domínio sempiterno, e cujo reino é de geração em geração.

[[v27-4-35]]

^<<v27-4-35,35>>^ E todos os moradores da terra são reputados em nada, e segundo a sua vontade ele opera com o exército do céu e os moradores da terra; não há quem possa estorvar a sua mão, e lhe diga: Que fazes?

[[v27-4-36]]

^<<v27-4-36,36>>^ No mesmo tempo tornou a mim o meu entendimento, e para a dignidade do meu reino tornou-me a vir a minha majestade e o meu resplendor; e buscaram-me os meus conselheiros e os meus senhores; e fui restabelecido no meu reino, e a minha glória foi aumentada.

[[v27-4-37]]

^<<v27-4-37,37>>^ Agora, pois, eu, Nabucodonosor, louvo, exalço e glorifico ao Rei do céu; porque todas as suas obras são verdade, e os seus caminhos juízo, e pode humilhar aos que andam na soberba.

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]