include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-10-1]]

^<<v27-10-1,1>>^ No terceiro ano de Ciro, rei da Pérsia, foi revelada uma palavra a Daniel, cujo nome era Beltessazar; a palavra era verdadeira e envolvia grande conflito; e ele entendeu esta palavra, e tinha entendimento da visão.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naqueles dias eu, Daniel, estive triste por três semanas.

[[v27-10-3]]

^<<v27-10-3,3>>^ Alimento desejável não comi, nem carne nem vinho entraram na minha boca, nem me ungi com ungüento, até que se cumpriram as três semanas.

[[v27-10-4]]

^<<v27-10-4,4>>^ E no dia vinte e quatro do primeiro mês eu estava à borda do grande rio Hidequel;

[[v27-10-5]]

^<<v27-10-5,5>>^ E levantei os meus olhos, e olhei, e eis um homem vestido de linho, e os seus lombos cingidos com ouro fino de Ufaz;

[[v27-10-6]]

^<<v27-10-6,6>>^ E o seu corpo era como berilo, e o seu rosto parecia um relâmpago, e os seus olhos como tochas de fogo, e os seus braços e os seus pés brilhavam como bronze polido; e a voz das suas palavras era como a voz de uma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ E só eu, Daniel, tive aquela visão. Os homens que estavam comigo não a viram; contudo caiu sobre eles um grande temor, e fugiram, escondendo-se.

[[v27-10-8]]

^<<v27-10-8,8>>^ Fiquei, pois, eu só, a contemplar esta grande visão, e não ficou força em mim; transmudou-se o meu semblante em corrupção, e não tive força alguma.

[[v27-10-9]]

^<<v27-10-9,9>>^ Contudo ouvi a voz das suas palavras; e, ouvindo o som das suas palavras, eu caí sobre o meu rosto num profundo sono, com o meu rosto em terra.

[[v27-10-10]]

^<<v27-10-10,10>>^ E eis que certa mão me tocou, e fez com que me movesse sobre os meus joelhos e sobre as palmas das minhas mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E me disse: Daniel, homem muito amado, entende as palavras que vou te dizer, e levanta-te sobre os teus pés, porque a ti sou enviado. E, falando ele comigo esta palavra, levantei-me tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ Então me disse: Não temas, Daniel, porque desde o primeiro dia em que aplicaste o teu coração a compreender e a humilhar-te perante o teu Deus, são ouvidas as tuas palavras; e eu vim por causa das tuas palavras.

[[v27-10-13]]

^<<v27-10-13,13>>^ Mas o príncipe do reino da Pérsia me resistiu vinte e um dias, e eis que Miguel, um dos primeiros príncipes, veio para ajudar-me, e eu fiquei ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora vim, para fazer-te entender o que há de acontecer ao teu povo nos derradeiros dias; porque a visão é ainda para muitos dias.

[[v27-10-15]]

^<<v27-10-15,15>>^ E, falando ele comigo estas palavras, abaixei o meu rosto para a terra, e emudeci.

[[v27-10-16]]

^<<v27-10-16,16>>^ E eis que alguém, semelhante aos filhos dos homens, tocou-me os lábios; então abri a minha boca, e falei, dizendo àquele que estava em pé diante de mim: senhor meu, por causa da visão sobrevieram-me dores, e não me ficou força alguma.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como, pois, pode o servo do meu senhor falar com o meu senhor? Porque, quanto a mim, desde agora não resta força em mim, e nem fôlego ficou em mim.

[[v27-10-18]]

^<<v27-10-18,18>>^ E aquele, que tinha aparência de um homem, tocou-me outra vez, e fortaleceu-me.

[[v27-10-19]]

^<<v27-10-19,19>>^ E disse: Não temas, homem muito amado, paz seja contigo; anima-te, sim, anima-te. E, falando ele comigo, fiquei fortalecido, e disse: Fala, meu senhor, porque me fortaleceste.

[[v27-10-20]]

^<<v27-10-20,20>>^ E ele disse: Sabes por que eu vim a ti? Agora, pois, tornarei a pelejar contra o príncipe dos persas; e, saindo eu, eis que virá o príncipe da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ Mas eu te declararei o que está registrado na escritura da verdade; e ninguém há que me anime contra aqueles, senão Miguel, vosso príncipe.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]