include::./index.adoc[]

[[v27-2-0]]
=== Daniel, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v27-2-1]]

^<<v27-2-1,1>>^ E no segundo ano do reinado de Nabucodonosor, Nabucodonosor teve sonhos; e o seu espírito se perturbou, e passou-se-lhe o sono.

[[v27-2-2]]

^<<v27-2-2,2>>^ Então o rei mandou chamar os magos, os astrólogos, os encantadores e os caldeus, para que declarassem ao rei os seus sonhos; e eles vieram e se apresentaram diante do rei.

[[v27-2-3]]

^<<v27-2-3,3>>^ E o rei lhes disse: Tive um sonho; e para saber o sonho está perturbado o meu espírito.

[[v27-2-4]]

^<<v27-2-4,4>>^ E os caldeus disseram ao rei em aramaico: Ó rei, vive eternamente! Dize o sonho a teus servos, e daremos a interpretação.

[[v27-2-5]]

^<<v27-2-5,5>>^ Respondeu o rei, e disse aos caldeus: O assunto me tem escapado; se não me fizerdes saber o sonho e a sua interpretação, sereis despedaçados, e as vossas casas serão feitas um monturo;

[[v27-2-6]]

^<<v27-2-6,6>>^ Mas se vós me declarardes o sonho e a sua interpretação, recebereis de mim dádivas, recompensas e grande honra; portanto declarai-me o sonho e a sua interpretação.

[[v27-2-7]]

^<<v27-2-7,7>>^ Responderam segunda vez, e disseram: Diga o rei o sonho a seus servos, e daremos a sua interpretação.

[[v27-2-8]]

^<<v27-2-8,8>>^ Respondeu o rei, e disse: Percebo muito bem que vós quereis ganhar tempo; porque vedes que o assunto me tem escapado.

[[v27-2-9]]

^<<v27-2-9,9>>^ De modo que, se não me fizerdes saber o sonho, uma só sentença será a vossa; pois vós preparastes palavras mentirosas e perversas para as proferirdes na minha presença, até que se mude o tempo; portanto dizei-me o sonho, para que eu entenda que me podeis dar a sua interpretação.

[[v27-2-10]]

^<<v27-2-10,10>>^ Responderam os caldeus na presença do rei, e disseram: Não há ninguém sobre a terra que possa declarar a palavra ao rei; pois nenhum rei há, grande ou dominador, que requeira coisas semelhantes de algum mago, ou astrólogo, ou caldeu.

[[v27-2-11]]

^<<v27-2-11,11>>^ Porque o assunto que o rei requer é difícil; e ninguém há que o possa declarar diante do rei, senão os deuses, cuja morada não é com a carne.

[[v27-2-12]]

^<<v27-2-12,12>>^ Por isso o rei muito se irou e enfureceu; e ordenou que matassem a todos os sábios de babilônia.

[[v27-2-13]]

^<<v27-2-13,13>>^ E saiu o decreto, segundo o qual deviam ser mortos os sábios; e buscaram a Daniel e aos seus companheiros, para que fossem mortos.

[[v27-2-14]]

^<<v27-2-14,14>>^ Então Daniel falou avisada e prudentemente a Arioque, capitão da guarda do rei, que tinha saído para matar os sábios de babilônia.

[[v27-2-15]]

^<<v27-2-15,15>>^ Respondeu, e disse a Arioque, capitão do rei: Por que se apressa tanto o decreto da parte do rei? Então Arioque explicou o caso a Daniel.

[[v27-2-16]]

^<<v27-2-16,16>>^ E Daniel entrou; e pediu ao rei que lhe desse tempo, para que lhe pudesse dar a interpretação.

[[v27-2-17]]

^<<v27-2-17,17>>^ Então Daniel foi para a sua casa, e fez saber o caso a Hananias, Misael e Azarias, seus companheiros;

[[v27-2-18]]

^<<v27-2-18,18>>^ Para que pedissem misericórdia ao Deus do céu, sobre este mistério, a fim de que Daniel e seus companheiros não perecessem, juntamente com o restante dos sábios da Babilônia.

[[v27-2-19]]

^<<v27-2-19,19>>^ Então foi revelado o mistério a Daniel numa visão de noite; então Daniel louvou o Deus do céu.

[[v27-2-20]]

^<<v27-2-20,20>>^ Falou Daniel, dizendo: Seja bendito o nome de Deus de eternidade a eternidade, porque dele são a sabedoria e a força;

[[v27-2-21]]

^<<v27-2-21,21>>^ E ele muda os tempos e as estações; ele remove os reis e estabelece os reis; ele dá sabedoria aos sábios e conhecimento aos entendidos.

[[v27-2-22]]

^<<v27-2-22,22>>^ Ele revela o profundo e o escondido; conhece o que está em trevas, e com ele mora a luz.

[[v27-2-23]]

^<<v27-2-23,23>>^ Ó Deus de meus pais, eu te dou graças e te louvo, porque me deste sabedoria e força; e agora me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.

[[v27-2-24]]

^<<v27-2-24,24>>^ Por isso Daniel foi ter com Arioque, ao qual o rei tinha constituído para matar os sábios de babilônia; entrou, e disse-lhe assim: Não mates os sábios de babilônia; introduze-me na presença do rei, e declararei ao rei a interpretação.

[[v27-2-25]]

^<<v27-2-25,25>>^ Então Arioque depressa introduziu a Daniel na presença do rei, e disse-lhe assim: Achei um homem dentre os cativos de Judá, o qual fará saber ao rei a interpretação.

[[v27-2-26]]

^<<v27-2-26,26>>^ Respondeu o rei, e disse a Daniel (cujo nome era Beltessazar): Podes tu fazer-me saber o sonho que tive e a sua interpretação?

[[v27-2-27]]

^<<v27-2-27,27>>^ Respondeu Daniel na presença do rei, dizendo: O segredo que o rei requer, nem sábios, nem astrólogos, nem magos, nem adivinhos o podem declarar ao rei;

[[v27-2-28]]

^<<v27-2-28,28>>^ Mas há um Deus no céu, o qual revela os mistérios; ele, pois, fez saber ao rei Nabucodonosor o que há de acontecer nos últimos dias; o teu sonho e as visões da tua cabeça que tiveste na tua cama são estes:

[[v27-2-29]]

^<<v27-2-29,29>>^ Estando tu, ó rei, na tua cama, subiram os teus pensamentos, acerca do que há de ser depois disto. Aquele, pois, que revela os mistérios te fez saber o que há de ser.

[[v27-2-30]]

^<<v27-2-30,30>>^ E a mim me foi revelado esse mistério, não porque haja em mim mais sabedoria que em todos os viventes, mas para que a interpretação se fizesse saber ao rei, e para que entendesses os pensamentos do teu coração.

[[v27-2-31]]

^<<v27-2-31,31>>^ Tu, ó rei, estavas vendo, e eis aqui uma grande estátua; esta estátua, que era imensa, cujo esplendor era excelente, e estava em pé diante de ti; e a sua aparência era terrível.

[[v27-2-32]]

^<<v27-2-32,32>>^ A cabeça daquela estátua era de ouro fino; o seu peito e os seus braços de prata; o seu ventre e as suas coxas de cobre;

[[v27-2-33]]

^<<v27-2-33,33>>^ As pernas de ferro; os seus pés em parte de ferro e em parte de barro.

[[v27-2-34]]

^<<v27-2-34,34>>^ Estavas vendo isto, quando uma pedra foi cortada, sem auxílio de mão, a qual feriu a estátua nos pés de ferro e de barro, e os esmiuçou.

[[v27-2-35]]

^<<v27-2-35,35>>^ Então foi juntamente esmiuçado o ferro, o barro, o bronze, a prata e o ouro, os quais se fizeram como pragana das eiras do estio, e o vento os levou, e não se achou lugar algum para eles; mas a pedra, que feriu a estátua, se tornou grande monte, e encheu toda a terra.

[[v27-2-36]]

^<<v27-2-36,36>>^ Este é o sonho; também a sua interpretação diremos na presença do rei.

[[v27-2-37]]

^<<v27-2-37,37>>^ Tu, ó rei, és rei de reis; a quem o Deus do céu tem dado o reino, o poder, a força, e a glória.

[[v27-2-38]]

^<<v27-2-38,38>>^ E onde quer que habitem os filhos de homens, na tua mão entregou os animais do campo, e as aves do céu, e fez que reinasse sobre todos eles; tu és a cabeça de ouro.

[[v27-2-39]]

^<<v27-2-39,39>>^ E depois de ti se levantará outro reino, inferior ao teu; e um terceiro reino, de bronze, o qual dominará sobre toda a terra.

[[v27-2-40]]

^<<v27-2-40,40>>^ E o quarto reino será forte como ferro; pois, como o ferro, esmiúça e quebra tudo; como o ferro que quebra todas as coisas, assim ele esmiuçará e fará em pedaços.

[[v27-2-41]]

^<<v27-2-41,41>>^ E, quanto ao que viste dos pés e dos dedos, em parte de barro de oleiro, e em parte de ferro, isso será um reino dividido; contudo haverá nele alguma coisa da firmeza do ferro, pois viste o ferro misturado com barro de lodo.

[[v27-2-42]]

^<<v27-2-42,42>>^ E como os dedos dos pés eram em parte de ferro e em parte de barro, assim por uma parte o reino será forte, e por outra será frágil.

[[v27-2-43]]

^<<v27-2-43,43>>^ Quanto ao que viste do ferro misturado com barro de lodo, misturar-se-ão com semente humana, mas não se ligarão um ao outro, assim como o ferro não se mistura com o barro.

[[v27-2-44]]

^<<v27-2-44,44>>^ Mas, nos dias desses reis, o Deus do céu levantará um reino que não será jamais destruído; e este reino não passará a outro povo; esmiuçará e consumirá todos esses reinos, mas ele mesmo subsistirá para sempre,

[[v27-2-45]]

^<<v27-2-45,45>>^ Da maneira que viste que do monte foi cortada uma pedra, sem auxílio de mãos, e ela esmiuçou o ferro, o bronze, o barro, a prata e o ouro; o grande Deus fez saber ao rei o que há de ser depois disto. Certo é o sonho, e fiel a sua interpretação.

[[v27-2-46]]

^<<v27-2-46,46>>^ Então o rei Nabucodonosor caiu sobre a sua face, e adorou a Daniel, e ordenou que lhe oferecessem uma oblação e perfumes suaves.

[[v27-2-47]]

^<<v27-2-47,47>>^ Respondeu o rei a Daniel, e disse: Certamente o vosso Deus é Deus dos deuses, e o Senhor dos reis e revelador de mistérios, pois pudeste revelar este mistério.

[[v27-2-48]]

^<<v27-2-48,48>>^ Então o rei engrandeceu a Daniel, e lhe deu muitas e grandes dádivas, e o pôs por governador de toda a província de babilônia, como também o fez chefe dos governadores sobre todos os sábios de babilônia.

[[v27-2-49]]

^<<v27-2-49,49>>^ E pediu Daniel ao rei, e constituiu ele sobre os negócios da província de babilônia a Sadraque, Mesaque e Abednego; mas Daniel permaneceu na porta do rei.

'''

xref:027-daniel/027-daniel-001.adoc#v27-1-0[&#60; Capítulo Anterior] | <<v27-2-0,Topo>> | xref:027-daniel/027-daniel-003.adoc#v27-3-0[Próximo Capítulo &#62;]