include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-26-1]]

^<<v13-26-1,1>>^ Quanto às divisões dos porteiros: dos coraítas: Meselemias, filho de Coré, dos filhos de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ E foram os filhos de Meselemias: Zacarias o primogênito, Jediael o segundo, Zebadias o terceiro, Jatniel o quarto,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão o quinto, Joanã o sexto, Elioenai o sétimo.

[[v13-26-4]]

^<<v13-26-4,4>>^ E os filhos de Obede-Edom foram: Semaías o primogênito, Jozabade o segundo, Joá o terceiro, e Sacar o quarto, e Natanael o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel o sexto, Issacar o sétimo, Peuletai o oitavo; porque Deus o tinha abençoado.

[[v13-26-6]]

^<<v13-26-6,6>>^ Também a seu filho Semaías nasceram filhos, que dominaram sobre a casa de seu pai; porque foram homens valentes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Os filhos de Semaías: Otni, Rafael, Obede, e Elzabade, com seus irmãos, homens valentes, Eliú e Semaquias.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos estes foram dos filhos de Obede-Edom; eles e seus filhos, e seus irmãos, homens valentes e de força para o ministério; ao todo sessenta e dois, de Obede-Edom.

[[v13-26-9]]

^<<v13-26-9,9>>^ E os filhos e os irmãos de Meselemias, homens valentes, foram dezoito.

[[v13-26-10]]

^<<v13-26-10,10>>^ E de Hosa, dentre os filhos de Merari, foram filhos: Sinri o chefe (ainda que não era o primogênito, contudo seu pai o constituiu chefe),

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias o segundo, Tebalias o terceiro, Zacarias o quarto; todos os filhos e irmãos de Hosa foram treze.

[[v13-26-12]]

^<<v13-26-12,12>>^ Destes se fizeram as turmas dos porteiros, alternando os principais dos homens da guarda, juntamente com os seus irmãos, para ministrarem na casa do Senhor.

[[v13-26-13]]

^<<v13-26-13,13>>^ E lançaram sortes, assim os pequenos como os grandes, segundo as casas de seus pais, para cada porta.

[[v13-26-14]]

^<<v13-26-14,14>>^ E caiu a sorte do oriente a Selemias; e lançou-se a sorte por seu filho Zacarias, conselheiro entendido, e saiu-lhe a do norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ E para Obede-Edom a do sul; e para seus filhos a casa dos depósitos.

[[v13-26-16]]

^<<v13-26-16,16>>^ Para Supim e Hosa a do ocidente, junto a porta Salequete, perto do caminho da subida; uma guarda defronte de outra guarda.

[[v13-26-17]]

^<<v13-26-17,17>>^ Ao oriente seis levitas; ao norte quatro por dia, ao sul quatro por dia, porém para as casas dos depósitos de dois em dois.

[[v13-26-18]]

^<<v13-26-18,18>>^ Em Parbar, ao ocidente, quatro junto ao caminho, e dois junto a Parbar.

[[v13-26-19]]

^<<v13-26-19,19>>^ Estas são as turmas dos porteiros dentre os filhos dos coraítas, e dentre os filhos de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ E dos levitas: Aías tinha cargo dos tesouros da casa de Deus e dos tesouros das coisas sagradas.

[[v13-26-21]]

^<<v13-26-21,21>>^ Quanto aos filhos de Ladã, os filhos dos gersonitas que pertencem a Ladã, chefes das casas paternas de Ladã: Jeieli.

[[v13-26-22]]

^<<v13-26-22,22>>^ Os filhos de Jeieli: Zetã e Joel, seu irmão; estes tinham cargo dos tesouros da casa do Senhor,

[[v13-26-23]]

^<<v13-26-23,23>>^ Dos anramitas, dos izaritas, dos hebronitas, dos uzielitas.

[[v13-26-24]]

^<<v13-26-24,24>>^ E Sebuel, filho de Gérson, o filho de Moisés, era o chefe dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ E seus irmãos foram, do lado de Eliézer, Reabias seu filho, e Jesaías seu filho, e Jorão seu filho, e Zicri seu filho, e Selomite, seu filho.

[[v13-26-26]]

^<<v13-26-26,26>>^ Este Selomite e seus irmãos tinham a seu cargo todos os tesouros das coisas dedicadas que o rei Davi e os chefes das casas paternas, capitães de milhares, e de centenas, e capitães do exército tinham consagrado.

[[v13-26-27]]

^<<v13-26-27,27>>^ Dos despojos das guerras dedicaram ofertas para repararem a casa do Senhor.

[[v13-26-28]]

^<<v13-26-28,28>>^ Como também tudo quanto tinha consagrado Samuel, o vidente, e Saul filho de Quis, e Abner filho de Ner, e Joabe filho de Zeruia; tudo que qualquer havia dedicado estava debaixo da mão de Selomite e seus irmãos.

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos izaritas, Quenanias e seus filhos foram postos sobre Israel como oficiais e como juízes, dos negócios externos.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos hebronitas foram Hasabias e seus irmãos, homens valentes, mil e setecentos, que tinham a superintendência sobre Israel, além do Jordão para o ocidente, em toda a obra do Senhor, e para o serviço do rei.

[[v13-26-31]]

^<<v13-26-31,31>>^ Dos hebronitas Jerias era o chefe, segundo as suas gerações conforme as suas famílias. No ano quarenta do reino de Davi se buscaram e acharam entre eles homens valentes em Jazer de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ E seus irmãos, homens valentes, dois mil e setecentos, chefes dos pais; e o rei Davi os constituiu sobre os rubenitas e os gaditas, e a meia tribo dos manassitas, para todos os negócios de Deus, e para todos os negócios do rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]