include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-12-1]]

^<<v13-12-1,1>>^ Estes, porém, são os que vieram a Davi, a Ziclague, estando ele ainda escondido, por causa de Saul, filho de Quis; e eram dos valentes que o ajudaram na guerra.

[[v13-12-2]]

^<<v13-12-2,2>>^ Estavam armados de arco, e usavam tanto da mão direita como da esquerda em atirar pedras e em atirar flechas com o arco; eram dos irmãos de Saul, benjamitas.

[[v13-12-3]]

^<<v13-12-3,3>>^ Aiezer, o chefe, e Joás, filho de Semaa, o gibeatita, e Jeziel e Pelete, filhos de Azmavete; e Beraca, e Jeú, o anatotita,

[[v13-12-4]]

^<<v13-12-4,4>>^ E Ismaías, o gibeonita, valente entre os trinta, líder deles; e Jeremias, e Jaaziel, e Joanã, e Jozabade, o gederatita,

[[v13-12-5]]

^<<v13-12-5,5>>^ Eluzai, e Jerimote, e Bealias, e Samarias, e Sefatias, o harufita,

[[v13-12-6]]

^<<v13-12-6,6>>^ Elcana, Issias, Azarel, Joezer, e Jasobeão, os coraítas,

[[v13-12-7]]

^<<v13-12-7,7>>^ E Joela, e Zabadias, filhos de Jeroão de Gedor.

[[v13-12-8]]

^<<v13-12-8,8>>^ E dos gaditas se desertaram para Davi, ao lugar forte no deserto, valentes, homens de guerra para pelejar, armados com escudo e lança; e seus rostos eram como rostos de leões, e ligeiros como corças sobre os montes:

[[v13-12-9]]

^<<v13-12-9,9>>^ Ezer, o primeiro; Obadias, o segundo; Eliabe, o terceiro;

[[v13-12-10]]

^<<v13-12-10,10>>^ Mismana, o quarto; Jeremias, o quinto;

[[v13-12-11]]

^<<v13-12-11,11>>^ Atai, o sexto; Eliel, o sétimo;

[[v13-12-12]]

^<<v13-12-12,12>>^ Joanã, o oitavo; Elzabade, o nono;

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremias, o décimo; Macbanai, o undécimo;

[[v13-12-14]]

^<<v13-12-14,14>>^ Estes, dos filhos de Gade, foram os capitães do exército; o menor tinha o encargo de cem homens e o maior de mil.

[[v13-12-15]]

^<<v13-12-15,15>>^ Estes são os que passaram o Jordão no primeiro mês, quando ele transbordava por todas as suas ribanceiras, e fizeram fugir a todos os dos vales ao oriente e ao ocidente.

[[v13-12-16]]

^<<v13-12-16,16>>^ Também alguns dos filhos de Benjamim e de Judá vieram a Davi, ao lugar forte.

[[v13-12-17]]

^<<v13-12-17,17>>^ E Davi lhes saiu ao encontro, e lhes falou, dizendo: Se vós vindes a mim pacificamente e para me ajudar, o meu coração se unirá convosco; porém, se é para me entregar aos meus inimigos, sem que haja deslealdade nas minhas mãos, o Deus de nossos pais o veja e o repreenda.

[[v13-12-18]]

^<<v13-12-18,18>>^ Então veio o espírito sobre Amasai, chefe de trinta, e disse: Nós somos teus, ó Davi, e contigo estamos, ó filho de Jessé! Paz, paz contigo, e paz com quem te ajuda, pois que teu Deus te ajuda. E Davi os recebeu, e os fez capitães das tropas.

[[v13-12-19]]

^<<v13-12-19,19>>^ Também de Manassés alguns passaram para Davi, quando veio com os filisteus para a batalha contra Saul; todavia Davi não os ajudou, porque os príncipes dos filisteus, tendo feito conselho, o despediram, dizendo: À custa de nossas cabeças passará a Saul, seu senhor.

[[v13-12-20]]

^<<v13-12-20,20>>^ Voltando ele, pois, a Ziclague, passaram-se para ele, de Manassés, Adna, Jozabade, Jediael, Micael, Jozabade, Eliú, e Ziletai, capitães de milhares dos de Manassés.

[[v13-12-21]]

^<<v13-12-21,21>>^ E estes ajudaram a Davi contra aquela tropa, porque todos eles eram heróis poderosos, e foram capitães no exército.

[[v13-12-22]]

^<<v13-12-22,22>>^ Porque naquele tempo, dia após dia, vinham a Davi para o ajudar, até que se fez um grande exército, como o exército de Deus.

[[v13-12-23]]

^<<v13-12-23,23>>^ Ora este é o número dos chefes armados para a peleja, que vieram a Davi em Hebrom, para transferir a ele o reino de Saul, conforme a palavra do Senhor.

[[v13-12-24]]

^<<v13-12-24,24>>^ Dos filhos de Judá, que traziam escudo e lança, seis mil e oitocentos, armados para a peleja;

[[v13-12-25]]

^<<v13-12-25,25>>^ Dos filhos de Simeão, homens poderosos para pelejar, sete mil e cem;

[[v13-12-26]]

^<<v13-12-26,26>>^ Dos filhos de Levi, quatro mil e seiscentos.

[[v13-12-27]]

^<<v13-12-27,27>>^ Joiada, que era o líder dos de Arão, e com ele três mil e setecentos.

[[v13-12-28]]

^<<v13-12-28,28>>^ E Zadoque, sendo ainda jovem, homem poderoso, com vinte e dois capitães da família de seu pai;

[[v13-12-29]]

^<<v13-12-29,29>>^ E dos filhos de Benjamim, irmãos de Saul, três mil; porque até então havia ainda muitos deles que eram pela casa de Saul.

[[v13-12-30]]

^<<v13-12-30,30>>^ E dos filhos de Efraim, vinte mil e oitocentos homens poderosos, homens de nome nas casas de seus pais.

[[v13-12-31]]

^<<v13-12-31,31>>^ E da meia tribo de Manassés, dezoito mil, que foram apontados pelos seus nomes para virem fazer rei a Davi.

[[v13-12-32]]

^<<v13-12-32,32>>^ E dos filhos de Issacar, duzentos de seus chefes, destros na ciência dos tempos, para saberem o que Israel devia fazer, e todos os seus irmãos seguiam suas ordens.

[[v13-12-33]]

^<<v13-12-33,33>>^ De Zebulom, dos que podiam sair no exército, cinqüenta mil ordenados para a peleja com todas as armas de guerra; como também destros para ordenarem uma batalha, e não eram de coração dobre.

[[v13-12-34]]

^<<v13-12-34,34>>^ E de Naftali, mil capitães, e com eles trinta e sete mil com escudo e lança.

[[v13-12-35]]

^<<v13-12-35,35>>^ E dos danitas, ordenados para a peleja, vinte e oito mil e seiscentos.

[[v13-12-36]]

^<<v13-12-36,36>>^ E de Aser, dos que podiam sair no exército, para ordenarem a batalha, quarenta mil.

[[v13-12-37]]

^<<v13-12-37,37>>^ E do outro lado do Jordão, dos rubenitas e gaditas, e da meia tribo de Manassés, com toda a sorte de instrumentos de guerra para pelejar, cento e vinte mil.

[[v13-12-38]]

^<<v13-12-38,38>>^ Todos estes homens de guerra, postos em ordem de batalha, vieram a Hebrom, com corações decididos, para constituírem a Davi rei sobre todo o Israel; e também todo o restante de Israel tinha o mesmo coração para constituir a Davi rei.

[[v13-12-39]]

^<<v13-12-39,39>>^ E estiveram ali com Davi três dias, comendo e bebendo; porque seus irmãos lhes tinham preparado as provisões.

[[v13-12-40]]

^<<v13-12-40,40>>^ E também seus vizinhos de mais perto, até Issacar, e Zebulom, e Naftali, trouxeram, sobre jumentos, e sobre camelos, e sobre mulos, e sobre bois, pão, provisões de farinha, pastas de figos e cachos de passas, e vinho, e azeite, e bois, gado miúdo em abundância; porque havia alegria em Israel.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]