include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-18-1]]

^<<v13-18-1,1>>^ E depois disto aconteceu que Davi derrotou os filisteus, e os sujeitou; e tomou a Gate, e os lugares da sua jurisdição, da mão dos filisteus.

[[v13-18-2]]

^<<v13-18-2,2>>^ Também derrotou os moabitas; e os moabitas ficaram por servos de Davi, pagando tributos.

[[v13-18-3]]

^<<v13-18-3,3>>^ Também Davi derrotou a Hadar-Ezer, rei de Zobá, junto a Hamate, quando ele ia estabelecer o seu domínio sobre o rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ E Davi lhe tomou mil carros, e sete mil cavaleiros, e vinte mil homens de pé; e Davi jarretou todos os cavalos dos carros; porém reservou deles para cem carros.

[[v13-18-5]]

^<<v13-18-5,5>>^ E vieram os sírios de Damasco a socorrer a Hadar-Ezer, rei de Zobá; porém Davi feriu dos sírios vinte e dois mil homens.

[[v13-18-6]]

^<<v13-18-6,6>>^ E Davi pôs guarnições na Síria de Damasco, e os sírios ficaram por servos de Davi, pagando-lhe tributo; e o Senhor guardava a Davi, por onde quer que ia.

[[v13-18-7]]

^<<v13-18-7,7>>^ E Davi tomou os escudos de ouro, que tinham os servos de Hadar-Ezer, e os trouxe a Jerusalém.

[[v13-18-8]]

^<<v13-18-8,8>>^ Também de Tibate, e de Cum, cidades de Hadar-Ezer, tomou Davi muitíssimo cobre, de que Salomão fez o mar de cobre, e as colunas, e os utensílios de cobre.

[[v13-18-9]]

^<<v13-18-9,9>>^ E ouvindo Toí, rei de Hamate, que Davi destruíra todo o exército de Hadar-Ezer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ Mandou seu filho Hadorão a Davi, para lhe perguntar como estava, e para o abençoar, por haver pelejado contra Hadar-Ezer, e por havê-lo ferido (porque Hadar-Ezer fazia guerra a Toí), enviando-lhe também toda a sorte de vasos de ouro, e de prata, e de cobre.

[[v13-18-11]]

^<<v13-18-11,11>>^ Os quais Davi também consagrou ao Senhor, juntamente com a prata e ouro que trouxera de todas as demais nações: dos edomeus, e dos moabitas, e dos filhos de Amom, e dos filisteus, e dos amalequitas.

[[v13-18-12]]

^<<v13-18-12,12>>^ Também Abisai, filho de Zeruia, feriu a dezoito mil edomeus no Vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ E pôs guarnições em Edom, e todos os edomeus ficaram por servos de Davi; e o Senhor guardava a Davi, por onde quer que ia.

[[v13-18-14]]

^<<v13-18-14,14>>^ E Davi reinou sobre todo o Israel; e fazia juízo e justiça a todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ E Joabe, filho de Zeruia, comandava o exército; Jeosafá, filho de Ailude, era cronista.

[[v13-18-16]]

^<<v13-18-16,16>>^ E Zadoque, filho de Aitube, e Abimeleque, filho de Abiatar, eram sacerdotes; e Savsa escrivão.

[[v13-18-17]]

^<<v13-18-17,17>>^ E Benaia, filho de Joiada, estava sobre os quereteus e peleteus; porém os filhos de Davi eram os primeiros junto ao rei.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]