include::./index.adoc[]

[[v13-24-0]]
=== 1 Crônicas, 24
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-24-1]]

^<<v13-24-1,1>>^ E quanto aos filhos de Arão, estas foram as suas divisões: os filhos de Arão: Nadabe, Abiú, Eleazar e Itamar.

[[v13-24-2]]

^<<v13-24-2,2>>^ E morreram Nadabe e Abiú antes de seu pai, e não tiveram filhos; e Eleazar e Itamar administravam o sacerdócio.

[[v13-24-3]]

^<<v13-24-3,3>>^ E Davi, com Zadoque, dos filhos de Eleazar, e Aimeleque, dos filhos de Itamar, dividiu-os segundo o seu ofício no seu ministério.

[[v13-24-4]]

^<<v13-24-4,4>>^ E acharam-se muito mais chefes dos pais entre os filhos de Eleazar do que entre os filhos de Itamar, quando os repartiram; dos filhos de Eleazar dezesseis chefes das casas paternas, mas dos filhos de Itamar, segundo as casas paternas, oito.

[[v13-24-5]]

^<<v13-24-5,5>>^ E os repartiram por sortes, uns com os outros; porque houve governadores do santuário e governadores da casa de Deus, assim dentre os filhos de Eleazar, como dentre os filhos de Itamar.

[[v13-24-6]]

^<<v13-24-6,6>>^ E Semaías, filho de Natanael, o escrivão dentre os levitas, os registrou perante o rei, e os príncipes, e Zadoque, o sacerdote, e Aimeleque, filho de Abiatar, e os chefes dos pais entre os sacerdotes, e entre os levitas; dentre as casas dos pais tomou-se uma para Eleazar, e outra para Itamar.

[[v13-24-7]]

^<<v13-24-7,7>>^ E saiu a primeira sorte a Jeoiaribe, a segunda a Jedaías,

[[v13-24-8]]

^<<v13-24-8,8>>^ A terceira a Harim, a quarta a Seorim,

[[v13-24-9]]

^<<v13-24-9,9>>^ A quinta a Malquias, a sexta a Miamim,

[[v13-24-10]]

^<<v13-24-10,10>>^ A sétima a Hacoz, a oitava a Abias,

[[v13-24-11]]

^<<v13-24-11,11>>^ A nona a Jesua, a décima a Secanias,

[[v13-24-12]]

^<<v13-24-12,12>>^ A undécima a Eliasibe, a duodécima a Jaquim,

[[v13-24-13]]

^<<v13-24-13,13>>^ A décima terceira a Hupa, a décima quarta a Jesebeabe,

[[v13-24-14]]

^<<v13-24-14,14>>^ A décima quinta a Bilga, a décima sexta a Imer,

[[v13-24-15]]

^<<v13-24-15,15>>^ A décima sétima a Hezir, a décima oitava a Hapizes,

[[v13-24-16]]

^<<v13-24-16,16>>^ A décima nona a Petaías, a vigésima a Jeezquel,

[[v13-24-17]]

^<<v13-24-17,17>>^ A vigésima primeira a Jaquim, a vigésima segunda a Gamul,

[[v13-24-18]]

^<<v13-24-18,18>>^ A vigésima terceira a Delaías, a vigésima quarta a Maazias.

[[v13-24-19]]

^<<v13-24-19,19>>^ O ofício destes no seu ministério era entrar na casa do Senhor, segundo lhes fora ordenado por Arão seu pai, como o Senhor Deus de Israel lhe tinha mandado.

[[v13-24-20]]

^<<v13-24-20,20>>^ E do restante dos filhos de Levi: dos filhos de Anrão, Subael; dos filhos de Subael, Jedias.

[[v13-24-21]]

^<<v13-24-21,21>>^ Quanto a Reabias: dos filhos de Reabias, Issias era o primeiro;

[[v13-24-22]]

^<<v13-24-22,22>>^ Dos izaritas, Selomote; dos filhos de Selomote, Jaate;

[[v13-24-23]]

^<<v13-24-23,23>>^ E dos filhos de Hebrom, Jerias o primeiro, Amarias o segundo, Jaaziel o terceiro, Jecameão o quarto;

[[v13-24-24]]

^<<v13-24-24,24>>^ Dos filhos de Uziel, Mica; dos filhos de Mica, Samir;

[[v13-24-25]]

^<<v13-24-25,25>>^ O irmão de Mica, Issias; dos filhos de Issias, Zacarias;

[[v13-24-26]]

^<<v13-24-26,26>>^ Os filhos de Merari, Mali e Musi; dos filhos de Jaazias, Beno;

[[v13-24-27]]

^<<v13-24-27,27>>^ Os filhos de Merari: de Jaazias, Beno, e Soão, e Zacur, e Ibri;

[[v13-24-28]]

^<<v13-24-28,28>>^ De Mali, Eleazar; e este não teve filhos.

[[v13-24-29]]

^<<v13-24-29,29>>^ Quanto a Quis: dos filhos de Quis, Jerameel;

[[v13-24-30]]

^<<v13-24-30,30>>^ E os filhos de Musi: Mali, e Eder, e Jerimote; estes foram os filhos dos levitas, segundo as suas casas paternas.

[[v13-24-31]]

^<<v13-24-31,31>>^ Estes também lançaram sortes como seus irmãos, os filhos de Arão, perante o rei Davi, e Zadoque, e Aimeleque, e os chefes das famílias entre os sacerdotes e entre os levitas; assim fizeram, tanto os pais principais como os irmãos menores.

'''

xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[&#60; Capítulo Anterior] | <<v13-24-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[Próximo Capítulo &#62;]