include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-20-1]]

^<<v13-20-1,1>>^ Aconteceu que, no decurso de um ano, no tempo em que os reis costumam sair para a guerra, Joabe levou o exército, e destruiu a terra dos filhos de Amom, e veio, e cercou a Rabá; porém Davi ficou em Jerusalém; e Joabe feriu a Rabá, e a destruiu.

[[v13-20-2]]

^<<v13-20-2,2>>^ E Davi tirou a coroa da cabeça do rei deles, e achou nela o peso de um talento de ouro, e havia nela pedras preciosas; e foi posta sobre a cabeça de Davi; e levou da cidade mui grande despojo.

[[v13-20-3]]

^<<v13-20-3,3>>^ Também levou o povo que estava nela, e os fez trabalhar com a serra, e com talhadeiras de ferro e com machados; e assim fez Davi com todas as cidades dos filhos de Amom; então voltou Davi, com todo o povo, para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ E, depois disto, aconteceu que, levantando-se guerra em Gezer, com os filisteus, então Sibecai, o husatita, feriu a Sipai, dos filhos do gigante; e ficaram subjugados.

[[v13-20-5]]

^<<v13-20-5,5>>^ E tornou a haver guerra com os filisteus; e El-Hanã, filho de Jair, feriu a Lami, irmão de Golias, o giteu, cuja haste da lança era como órgão de tecelão.

[[v13-20-6]]

^<<v13-20-6,6>>^ E houve ainda outra guerra em Gate; onde havia um homem de grande estatura, e tinha vinte e quatro dedos, seis em cada mão, e seis em cada pé, e que também era filho do gigante.

[[v13-20-7]]

^<<v13-20-7,7>>^ E injuriou a Israel; porém Jônatas, filho de Simei, irmão de Davi, o feriu;

[[v13-20-8]]

^<<v13-20-8,8>>^ Estes nasceram ao gigante em Gate; e caíram pela mão de Davi e pela mão dos seus servos.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]