include::./index.adoc[]

[[v13-1-0]]
=== 1 Crônicas, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v13-1-1]]

^<<v13-1-1,1>>^ Adão, Sete, Enos,

[[v13-1-2]]

^<<v13-1-2,2>>^ Cainã, Maalaleel, Jerede,

[[v13-1-3]]

^<<v13-1-3,3>>^ Enoque, Matusalém, Lameque,

[[v13-1-4]]

^<<v13-1-4,4>>^ Noé, Sem, Cão e Jafé.

[[v13-1-5]]

^<<v13-1-5,5>>^ Os filhos de Jafé foram: Gomer, Magogue, Madai, Javã, Tubal, Meseque e Tiras.

[[v13-1-6]]

^<<v13-1-6,6>>^ E os filhos de Gomer: Asquenaz, Rifate, Togarma.

[[v13-1-7]]

^<<v13-1-7,7>>^ E os filhos de Javã: Elisá, Társis, Quitim e Dodanim.

[[v13-1-8]]

^<<v13-1-8,8>>^ Os filhos de Cão: Cuxe, Mizraim, Pute e Canaã.

[[v13-1-9]]

^<<v13-1-9,9>>^ E os filhos de Cuxe eram: Sebá, Havilá, Sabtá, Raamá e Sabtecá; os filhos de Raamá: Sebá e Dedã.

[[v13-1-10]]

^<<v13-1-10,10>>^ E Cuxe gerou a Ninrode, que começou a ser poderoso na terra.

[[v13-1-11]]

^<<v13-1-11,11>>^ E Mizraim gerou a Ludim e a Anamim e a Leabim e a Naftuim,

[[v13-1-12]]

^<<v13-1-12,12>>^ E a Patrusim e a Casluim (dos quais procedem os filisteus) e a Caftorim.

[[v13-1-13]]

^<<v13-1-13,13>>^ E Canaã gerou a Sidom seu primogênito, e a Hete,

[[v13-1-14]]

^<<v13-1-14,14>>^ E aos jebuseus e aos amorreus e aos girgaseus,

[[v13-1-15]]

^<<v13-1-15,15>>^ E aos heveus e aos arqueus e aos sineus,

[[v13-1-16]]

^<<v13-1-16,16>>^ E aos arvadeus e aos zemareus e aos hamateus.

[[v13-1-17]]

^<<v13-1-17,17>>^ E foram os filhos de Sem: Elão, Assur, Arfaxade, Lude, Arã, Uz, Hul, Geter e Meseque.

[[v13-1-18]]

^<<v13-1-18,18>>^ E Arfaxade gerou a Selá e Selá gerou a Éber.

[[v13-1-19]]

^<<v13-1-19,19>>^ E a Éber nasceram dois filhos: o nome de um foi Pelegue, porquanto nos seus dias se repartiu a terra, e o nome de seu irmão era Joctã.

[[v13-1-20]]

^<<v13-1-20,20>>^ E Joctã gerou a Almodá, a Selefe, a Hazarmavé, e a Jerá,

[[v13-1-21]]

^<<v13-1-21,21>>^ E a Hadorão, a Usal, e a Dicla,

[[v13-1-22]]

^<<v13-1-22,22>>^ E a Obal, a Abimael, a Sebá,

[[v13-1-23]]

^<<v13-1-23,23>>^ E a Ofir, a Havilá, e a Jobabe: todos estes foram filhos de Joctã.

[[v13-1-24]]

^<<v13-1-24,24>>^ Sem, Arfaxade, Selá,

[[v13-1-25]]

^<<v13-1-25,25>>^ Éber, Pelegue, Reú,

[[v13-1-26]]

^<<v13-1-26,26>>^ Serugue, Naor, Terá,

[[v13-1-27]]

^<<v13-1-27,27>>^ Abrão, que é Abraão.

[[v13-1-28]]

^<<v13-1-28,28>>^ Os filhos de Abraão foram: Isaque e Ismael.

[[v13-1-29]]

^<<v13-1-29,29>>^ Estas são as suas gerações: o primogênito de Ismael foi Nebaiote, e, depois, Quedar, Adbeel, Mibsão,

[[v13-1-30]]

^<<v13-1-30,30>>^ Misma, Dumá, Massá, Hadade, Tema,

[[v13-1-31]]

^<<v13-1-31,31>>^ Jetur, Nafis e Quedemá; estes foram os filhos de Ismael.

[[v13-1-32]]

^<<v13-1-32,32>>^ Quanto aos filhos de Quetura, concubina de Abraão, esta deu à luz a Zinrã, a Jocsã, a Medã, a Midiã, a Jisbaque e a Suá; e os filhos de Jocsã foram Seba e Dedã.

[[v13-1-33]]

^<<v13-1-33,33>>^ E os filhos de Midiã: Efá, Efer, Enoque, Abida e Elda; todos estes foram filhos de Quetura.

[[v13-1-34]]

^<<v13-1-34,34>>^ Abraão, pois, gerou a Isaque; e foram os filhos de Isaque: Esaú e Israel.

[[v13-1-35]]

^<<v13-1-35,35>>^ Os filhos de Esaú: Elifaz, Reuel, Jeús, Jalão e Coré.

[[v13-1-36]]

^<<v13-1-36,36>>^ Os filhos de Elifaz: Temã, Omar, Zefi, Gaetã, Quenaz, Timna e Amaleque.

[[v13-1-37]]

^<<v13-1-37,37>>^ Os filhos de Reuel: Naate, Zerá, Samá e Mizá.

[[v13-1-38]]

^<<v13-1-38,38>>^ E os filhos de Seir: Lotã, Sobal, Zibeão, Aná, Disom, Eser e Disã.

[[v13-1-39]]

^<<v13-1-39,39>>^ E os filhos de Lotã: Hori e Homã; e a irmã de Lotã foi Timna.

[[v13-1-40]]

^<<v13-1-40,40>>^ Os filhos de Sobal eram Alvã, Manaate, Ebal, Sefi e Onã; e os filhos de Zibeão eram Aiá e Aná.

[[v13-1-41]]

^<<v13-1-41,41>>^ O filho de Aná foi Disom; e os filhos de Disom foram Hanrão, Esbã, Itrã e Querã.

[[v13-1-42]]

^<<v13-1-42,42>>^ Os filhos de Eser eram: Bilã, Zaavã e Jaacã; os filhos de Disã eram: Uz e Arã.

[[v13-1-43]]

^<<v13-1-43,43>>^ E estes são os reis que reinaram na terra de Edom, antes que reinasse rei sobre os filhos de Israel: Bela, filho de Beor, e era o nome da sua cidade Dinabá.

[[v13-1-44]]

^<<v13-1-44,44>>^ E morreu Bela, e reinou em seu lugar Jobabe, filho de Zerá, de Bozra.

[[v13-1-45]]

^<<v13-1-45,45>>^ E morreu Jobabe, e reinou em seu lugar Husão, da terra dos temanitas.

[[v13-1-46]]

^<<v13-1-46,46>>^ E morreu Husão, e reinou em seu lugar Hadade, filho de Bedade; este feriu os midianitas no campo de Moabe; e era o nome da sua cidade Avite.

[[v13-1-47]]

^<<v13-1-47,47>>^ E morreu Hadade, e reinou em seu lugar Samlá, de Masreca.

[[v13-1-48]]

^<<v13-1-48,48>>^ E morreu Samlá, e reinou em seu lugar Saul, de Reobote, junto ao rio.

[[v13-1-49]]

^<<v13-1-49,49>>^ E morreu Saul, e reinou em seu lugar Baal-Hanã, filho de Acbor.

[[v13-1-50]]

^<<v13-1-50,50>>^ E, morrendo Baal-Hanã, Hadade reinou em seu lugar; e era o nome da sua cidade Paí; e o nome de sua mulher era Meetabel, filha de Matrede, filha de Me-Zaabe.

[[v13-1-51]]

^<<v13-1-51,51>>^ E, morrendo Hadade, foram príncipes em Edom o príncipe Timna, o príncipe Alva, o príncipe Jetete,

[[v13-1-52]]

^<<v13-1-52,52>>^ O príncipe Oolibama, o príncipe Elá, o príncipe Pinom,

[[v13-1-53]]

^<<v13-1-53,53>>^ O príncipe Quenaz, o príncipe Temã, o príncipe Mibzar,

[[v13-1-54]]

^<<v13-1-54,54>>^ O príncipe Magdiel, o príncipe Irã, estes foram os príncipes de Edom.

'''

xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[&#60; Capítulo Anterior] | <<v13-1-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[Próximo Capítulo &#62;]