include::./index.adoc[]

[[v16-11-0]]
=== Neemias, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v16-11-1]]

^<<v16-11-1,1>>^ E os líderes do povo habitaram em Jerusalém, porém o restante do povo lançou sortes, para tirar um de dez, que habitasse na santa cidade de Jerusalém, e as nove partes nas outras cidades.

[[v16-11-2]]

^<<v16-11-2,2>>^ E o povo bendisse a todos os homens que voluntariamente se ofereciam para habitar em Jerusalém.

[[v16-11-3]]

^<<v16-11-3,3>>^ E estes são os chefes da província, que habitaram em Jerusalém; porém nas cidades de Judá habitou cada um na sua possessão, nas suas cidades, Israel, os sacerdotes, os levitas, os servidores do templo, e os filhos dos servos de Salomão.

[[v16-11-4]]

^<<v16-11-4,4>>^ Habitaram, pois, em Jerusalém alguns dos filhos de Judá e dos filhos de Benjamim. Dos filhos de Judá, Ataías, filho de Uzias, filho de Zacarias, filho de Amarias, filho de Sefatias, filho de Maalaleel, dos filhos de Perez;

[[v16-11-5]]

^<<v16-11-5,5>>^ E Maaséias, filho de Baruque, filho de Col-Hoze, filho de Hazaías, filho de Adaías, filho de Joiaribe, filho de Zacarias, filho de Siloni.

[[v16-11-6]]

^<<v16-11-6,6>>^ Todos os filhos de Perez, que habitaram em Jerusalém, foram quatrocentos e sessenta e oito homens valentes.

[[v16-11-7]]

^<<v16-11-7,7>>^ E estes são os filhos de Benjamim: Salu, filho de Mesulão, filho de Joede, filho de Pedaías, filho de Colaías, filho de Maaséias, filho de Itiel, filho de Jesaías.

[[v16-11-8]]

^<<v16-11-8,8>>^ E depois dele Gabai e Salai, ao todo novecentos e vinte e oito.

[[v16-11-9]]

^<<v16-11-9,9>>^ E Joel, filho de Zicri, superintendente sobre eles; e Judá, filho de Senua, o segundo sobre a cidade.

[[v16-11-10]]

^<<v16-11-10,10>>^ Dos sacerdotes: Jedaías, filho de Joiaribe, Jaquim,

[[v16-11-11]]

^<<v16-11-11,11>>^ Seraías, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube, líder da casa de Deus,

[[v16-11-12]]

^<<v16-11-12,12>>^ E seus irmãos, que faziam a obra na casa, oitocentos e vinte e dois; e Adaías, filho de Jeroão, filho de Pelalias, filho de Anzi, filho de Zacarias, filho de Pasur, filho de Malquias,

[[v16-11-13]]

^<<v16-11-13,13>>^ E seus irmãos, chefes dos pais, duzentos e quarenta e dois; e Amassai, filho de Azareel, filho de Azai, filho de Mesilemote, filho de Imer,

[[v16-11-14]]

^<<v16-11-14,14>>^ E os irmãos deles, homens valentes, cento e vinte e oito, e superintendente sobre eles Zabdiel, filho de Gedolim.

[[v16-11-15]]

^<<v16-11-15,15>>^ E dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, filho de Buni;

[[v16-11-16]]

^<<v16-11-16,16>>^ E Sabetai, e Jozabade, dos chefes dos levitas, presidiam sobre a obra de fora da casa de Deus.

[[v16-11-17]]

^<<v16-11-17,17>>^ E Matanias, filho de Mica, filho de Zabdi, filho de Asafe, o chefe, que iniciava as ações de graças na oração, e Bacbuquias, o segundo de seus irmãos; depois Abda, filho de Samua, filho de Galal, filho de Jedutum.

[[v16-11-18]]

^<<v16-11-18,18>>^ Todos os levitas na santa cidade, foram duzentos e oitenta e quatro.

[[v16-11-19]]

^<<v16-11-19,19>>^ E os porteiros, Acube, Talmom, com seus irmãos, os guardas das portas, cento e setenta e dois.

[[v16-11-20]]

^<<v16-11-20,20>>^ E o restante de Israel, dos sacerdotes e levitas, habitou em todas as cidades de Judá, cada um na sua herança.

[[v16-11-21]]

^<<v16-11-21,21>>^ E os servidores do templo, habitaram em Ofel; e Zia e Gispa presidiam sobre os servidores do templo.

[[v16-11-22]]

^<<v16-11-22,22>>^ E o superintendente dos levitas em Jerusalém foi Uzi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Mica; dos filhos de Asafe, os cantores, ao serviço da casa de Deus.

[[v16-11-23]]

^<<v16-11-23,23>>^ Porque havia um mandado do rei acerca deles, e uma certa regra para os cantores, cada qual no seu dia.

[[v16-11-24]]

^<<v16-11-24,24>>^ E Petaías, filho de Mesezabeel, dos filhos de Zerá, filho de Judá, estava à mão do rei, em todos os negócios do povo.

[[v16-11-25]]

^<<v16-11-25,25>>^ E quanto às aldeias, com as suas terras, alguns dos filhos de Judá habitaram em Quiriate-Arba e nos lugares da sua jurisdição, e em Dibom, e nos lugares da sua jurisdição, e em Jecabzeel e nas suas aldeias,

[[v16-11-26]]

^<<v16-11-26,26>>^ E em Jesuá, e em Molada, e em Bete-Pelete,

[[v16-11-27]]

^<<v16-11-27,27>>^ E em Hazar-Sual, e em Berseba e nos lugares da sua jurisdição,

[[v16-11-28]]

^<<v16-11-28,28>>^ E em Ziclague, em Mecona e nos lugares da sua jurisdição,

[[v16-11-29]]

^<<v16-11-29,29>>^ E em En-Rimom, em Zorá e em Jarmute,

[[v16-11-30]]

^<<v16-11-30,30>>^ Em Zanoa, Adulão e nas suas aldeias, em Laquis e nas suas terras, em Azaca e nos lugares da sua jurisdição. Acamparam-se desde Berseba até ao vale de Hinom.

[[v16-11-31]]

^<<v16-11-31,31>>^ E os filhos de Benjamim habitaram desde Geba, em Micmás, Aia, Betel e nos lugares da sua jurisdição,

[[v16-11-32]]

^<<v16-11-32,32>>^ E em Anatote, em Nobe, em Ananias,

[[v16-11-33]]

^<<v16-11-33,33>>^ Em Hazor, em Ramá, em Gitaim,

[[v16-11-34]]

^<<v16-11-34,34>>^ Em Hadide, em Zeboim, em Nebalate,

[[v16-11-35]]

^<<v16-11-35,35>>^ Em Lode e em Ono, no vale dos artífices,

[[v16-11-36]]

^<<v16-11-36,36>>^ E alguns dos levitas habitaram nas divisões de Judá e de Benjamim.

'''

xref:016-neemias/016-neemias-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-neemias/016-neemias-012.adoc#v16-12-0[Próximo Capítulo &#62;]