include::./index.adoc[]

[[v16-9-0]]
=== Neemias, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v16-9-1]]

^<<v16-9-1,1>>^ E, no dia vinte e quatro deste mês, ajuntaram-se os filhos de Israel com jejum e com sacos, e traziam terra sobre si.

[[v16-9-2]]

^<<v16-9-2,2>>^ E a descendência de Israel se apartou de todos os estrangeiros, e puseram-se em pé, e fizeram confissão pelos seus pecados e pelas iniqüidades de seus pais.

[[v16-9-3]]

^<<v16-9-3,3>>^ E, levantando-se no seu lugar, leram no livro da lei do Senhor seu Deus uma quarta parte do dia; e na outra quarta parte fizeram confissão, e adoraram ao Senhor seu Deus.

[[v16-9-4]]

^<<v16-9-4,4>>^ E Jesuá, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenani se puseram em pé no lugar alto dos levitas, e clamaram em alta voz ao Senhor seu Deus.

[[v16-9-5]]

^<<v16-9-5,5>>^ E os levitas, Jesuá, Cadmiel, Bani, Hasabnéias, Serebias, Hodias, Sebanias e Petaías, disseram: Levantai-vos, bendizei ao Senhor vosso Deus de eternidade em eternidade; e bendigam o teu glorioso nome, que está exaltado sobre toda a bênção e louvor.

[[v16-9-6]]

^<<v16-9-6,6>>^ Só tu és Senhor; tu fizeste o céu, o céu dos céus, e todo o seu exército, a terra e tudo quanto nela há, os mares e tudo quanto neles há, e tu os guardas com vida a todos; e o exército dos céus te adora.

[[v16-9-7]]

^<<v16-9-7,7>>^ Tu és o Senhor, o Deus, que elegeste a Abrão, e o tiraste de Ur dos caldeus, e lhe puseste por nome Abraão.

[[v16-9-8]]

^<<v16-9-8,8>>^ E achaste o seu coração fiel perante ti, e fizeste com ele a aliança, de que darias à sua descendência a terra dos cananeus, dos heteus, dos amorreus, dos perizeus, dos jebuseus e dos girgaseus; e confirmaste as tuas palavras, porquanto és justo.

[[v16-9-9]]

^<<v16-9-9,9>>^ E viste a aflição de nossos pais no Egito, e ouviste o seu clamor junto ao Mar Vermelho.

[[v16-9-10]]

^<<v16-9-10,10>>^ E mostraste sinais e prodígios a Faraó, e a todos os seus servos, e a todo o povo da sua terra, porque soubeste que soberbamente os trataram; e assim adquiriste para ti nome, como hoje se vê.

[[v16-9-11]]

^<<v16-9-11,11>>^ E o mar fendeste perante eles, e passaram pelo meio do mar, em seco; e lançaste os seus perseguidores nas profundezas, como uma pedra nas águas violentas.

[[v16-9-12]]

^<<v16-9-12,12>>^ E guiaste-os de dia por uma coluna de nuvem, e de noite por uma coluna de fogo, para lhes iluminar o caminho por onde haviam de ir.

[[v16-9-13]]

^<<v16-9-13,13>>^ E sobre o monte Sinai desceste, e dos céus falaste com eles, e deste-lhes juízos retos e leis verdadeiras, estatutos e mandamentos bons.

[[v16-9-14]]

^<<v16-9-14,14>>^ E o teu santo sábado lhes fizeste conhecer; e preceitos, estatutos e lei lhes mandaste pelo ministério de Moisés, teu servo.

[[v16-9-15]]

^<<v16-9-15,15>>^ E pão dos céus lhes deste na sua fome, e água da penha lhes produziste na sua sede; e lhes disseste que entrassem para possuírem a terra pela qual alçaste a tua mão, que lhes havias de dar.

[[v16-9-16]]

^<<v16-9-16,16>>^ Porém eles e nossos pais se houveram soberbamente, e endureceram a sua cerviz, e não deram ouvidos aos teus mandamentos.

[[v16-9-17]]

^<<v16-9-17,17>>^ E recusaram ouvir-te, e não se lembraram das tuas maravilhas, que lhes fizeste, e endureceram a sua cerviz e, na sua rebelião, levantaram um capitão, a fim de voltarem para a sua servidão; porém tu, ó Deus perdoador, clemente e misericordioso, tardio em irar-te, e grande em beneficência, tu não os desamparaste.

[[v16-9-18]]

^<<v16-9-18,18>>^ Ainda mesmo quando eles fizeram para si um bezerro de fundição, e disseram: Este é o teu Deus, que te tirou do Egito; e cometeram grandes blasfêmias;

[[v16-9-19]]

^<<v16-9-19,19>>^ Todavia tu, pela multidão das tuas misericórdias, não os deixaste no deserto. A coluna de nuvem nunca se apartou deles de dia, para os guiar pelo caminho, nem a coluna de fogo de noite, para lhes iluminar; e isto pelo caminho por onde haviam de ir.

[[v16-9-20]]

^<<v16-9-20,20>>^ E deste o teu bom espírito, para os ensinar; e o teu maná não retiraste da sua boca; e água lhes deste na sua sede.

[[v16-9-21]]

^<<v16-9-21,21>>^ De tal modo os sustentaste quarenta anos no deserto; nada lhes faltou; as suas roupas não se envelheceram, e os seus pés não se incharam.

[[v16-9-22]]

^<<v16-9-22,22>>^ Também lhes deste reinos e povos, e os repartiste em porções; e eles possuíram a terra de Siom, a saber, a terra do rei de Hesbom, e a terra de Ogue, rei de Basã.

[[v16-9-23]]

^<<v16-9-23,23>>^ E multiplicaste os seus filhos como as estrelas do céu, e trouxeste-os à terra de que tinhas falado a seus pais que nela entrariam para a possuírem.

[[v16-9-24]]

^<<v16-9-24,24>>^ Assim os filhos entraram e possuíram aquela terra; e abateste perante eles os moradores da terra, os cananeus, e lhos entregaste na mão, como também os reis e os povos da terra, para fazerem deles conforme a sua vontade.

[[v16-9-25]]

^<<v16-9-25,25>>^ E tomaram cidades fortificadas e terra fértil, e possuíram casas cheias de toda a fartura, cisternas cavadas, vinhas e olivais, e árvores frutíferas, em abundância; e comeram e se fartaram e engordaram e viveram em delícias, pela tua grande bondade.

[[v16-9-26]]

^<<v16-9-26,26>>^ Porém se obstinaram, e se rebelaram contra ti, e lançaram a tua lei para trás das suas costas, e mataram os teus profetas, que protestavam contra eles, para que voltassem para ti; assim fizeram grandes abominações.

[[v16-9-27]]

^<<v16-9-27,27>>^ Por isso os entregaste na mão dos seus adversários, que os angustiaram; mas no tempo de sua angústia, clamando a ti, desde os céus tu ouviste; e segundo a tua grande misericórdia lhes deste libertadores que os libertaram da mão de seus adversários.

[[v16-9-28]]

^<<v16-9-28,28>>^ Porém, em tendo repouso, tornavam a fazer o mal diante de ti; e tu os deixavas na mão dos seus inimigos, para que dominassem sobre eles; e convertendo-se eles, e clamando a ti, tu os ouviste desde os céus, e segundo a tua misericórdia os livraste muitas vezes.

[[v16-9-29]]

^<<v16-9-29,29>>^ E testificaste contra eles, para que voltassem para a tua lei; porém eles se houveram soberbamente, e não deram ouvidos aos teus mandamentos, mas pecaram contra os teus juízos, pelos quais o homem que os cumprir viverá; viraram o ombro, endureceram a sua cerviz, e não quiseram ouvir.

[[v16-9-30]]

^<<v16-9-30,30>>^ Porém estendeste a tua benignidade sobre eles por muitos anos, e testificaste contra eles pelo teu Espírito, pelo ministério dos teus profetas; porém eles não deram ouvidos; por isso os entregaste nas mãos dos povos das terras.

[[v16-9-31]]

^<<v16-9-31,31>>^ Mas pela tua grande misericórdia os não destruíste nem desamparaste, porque és um Deus clemente e misericordioso.

[[v16-9-32]]

^<<v16-9-32,32>>^ Agora, pois, nosso Deus, o grande, poderoso e terrível Deus, que guardas a aliança e a beneficência, não tenhas em pouca conta toda a aflição que nos alcançou a nós, aos nossos reis, aos nossos príncipes, aos nossos sacerdotes, aos nossos profetas, aos nossos pais e a todo o teu povo, desde os dias dos reis da Assíria até ao dia de hoje.

[[v16-9-33]]

^<<v16-9-33,33>>^ Porém tu és justo em tudo quanto tem vindo sobre nós; porque tu tens agido fielmente, e nós temos agido impiamente.

[[v16-9-34]]

^<<v16-9-34,34>>^ E os nossos reis, os nossos príncipes, os nossos sacerdotes, e os nossos pais não guardaram a tua lei, e não deram ouvidos aos teus mandamentos e aos teus testemunhos, que testificaste contra eles.

[[v16-9-35]]

^<<v16-9-35,35>>^ Porque eles nem no seu reino, nem na muita abundância de bens que lhes deste, nem na terra espaçosa e fértil que puseste diante deles, te serviram, nem se converteram de suas más obras.

[[v16-9-36]]

^<<v16-9-36,36>>^ Eis que hoje somos servos; e até na terra que deste a nossos pais, para comerem o seu fruto e o seu bem, eis que somos servos nela.

[[v16-9-37]]

^<<v16-9-37,37>>^ E ela multiplica os seus produtos para os reis, que puseste sobre nós, por causa dos nossos pecados; e conforme a sua vontade dominam sobre os nossos corpos e sobre o nosso gado; e estamos numa grande angústia.

[[v16-9-38]]

^<<v16-9-38,38>>^ E, todavia fizemos uma firme aliança, e o escrevemos; e selaram-no os nossos príncipes, os nossos levitas e os nossos sacerdotes.

'''

xref:016-neemias/016-neemias-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-neemias/016-neemias-010.adoc#v16-10-0[Próximo Capítulo &#62;]