include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v16-5-1]]

^<<v16-5-1,1>>^ Foi, porém, grande o clamor do povo e de suas mulheres, contra os judeus, seus irmãos.

[[v16-5-2]]

^<<v16-5-2,2>>^ Porque havia quem dizia: Nós, nossos filhos e nossas filhas, somos muitos; então tomemos trigo, para que comamos e vivamos.

[[v16-5-3]]

^<<v16-5-3,3>>^ Também havia quem dizia: As nossas terras, as nossas vinhas e as nossas casas empenhamos, para tomarmos trigo nesta fome.

[[v16-5-4]]

^<<v16-5-4,4>>^ Também havia quem dizia: Tomamos emprestado dinheiro até para o tributo do rei, sobre as nossas terras e as nossas vinhas.

[[v16-5-5]]

^<<v16-5-5,5>>^ Agora, pois, a nossa carne é como a carne de nossos irmãos, e nossos filhos como seus filhos; e eis que sujeitamos nossos filhos e nossas filhas para serem servos; e até algumas de nossas filhas são tão sujeitas, que já não estão no poder de nossas mãos; e outros têm as nossas terras e as nossas vinhas.

[[v16-5-6]]

^<<v16-5-6,6>>^ Ouvindo eu, pois, o seu clamor, e estas palavras, muito me indignei.

[[v16-5-7]]

^<<v16-5-7,7>>^ E considerei comigo mesmo no meu coração; depois pelejei com os nobres e com os magistrados, e disse-lhes: Sois usurários cada um para com seu irmão. E convoquei contra eles uma grande assembléia.

[[v16-5-8]]

^<<v16-5-8,8>>^ E disse-lhes: Nós resgatamos os judeus, nossos irmãos, que foram vendidos às nações, segundo nossas posses; e vós outra vez venderíeis a vossos irmãos, ou vender-se-iam a nós? Então se calaram, e não acharam que responder.

[[v16-5-9]]

^<<v16-5-9,9>>^ Disse mais: Não é bom o que fazeis; porventura não andaríeis no temor do nosso Deus, por causa do opróbrio das nações, os nossos inimigos?

[[v16-5-10]]

^<<v16-5-10,10>>^ Também eu, meus irmãos e meus servos, a juros lhes temos emprestado dinheiro e trigo. Deixemos este ganho.

[[v16-5-11]]

^<<v16-5-11,11>>^ Restituí-lhes hoje, vos peço, as suas terras, as suas vinhas, os seus olivais e as suas casas; como também a centésima parte do dinheiro, do trigo, do mosto e do azeite, que vós exigis deles.

[[v16-5-12]]

^<<v16-5-12,12>>^ Então disseram: Restituir-lhes-emos, e nada procuraremos deles; faremos assim como dizes. Então chamei os sacerdotes, e os fiz jurar que fariam conforme a esta palavra.

[[v16-5-13]]

^<<v16-5-13,13>>^ Também sacudi as minhas vestes, e disse: Assim sacuda Deus todo o homem da sua casa e do seu trabalho que não confirmar esta palavra, e assim seja sacudido e vazio. E toda a congregação disse: Amém! E louvaram ao Senhor; e o povo fez conforme a esta palavra.

[[v16-5-14]]

^<<v16-5-14,14>>^ Também desde o dia em que me mandou que eu fosse seu governador na terra de Judá, desde o ano vinte, até ao ano trinta e dois do rei Artaxerxes, doze anos, nem eu nem meus irmãos comemos o pão do governador.

[[v16-5-15]]

^<<v16-5-15,15>>^ Mas os primeiros governadores, que foram antes de mim, oprimiram o povo, e tomaram-lhe pão e vinho e, além disso, quarenta siclos de prata, como também os seus servos dominavam sobre o povo; porém eu assim não fiz, por causa do temor de Deus.

[[v16-5-16]]

^<<v16-5-16,16>>^ Como também na obra deste muro fiz reparação, e terra nenhuma compramos; e todos os meus servos se ajuntaram ali à obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ Também dos judeus e dos magistrados, cento e cinqüenta homens, e os que vinham a nós dentre as nações que estão ao redor de nós, se punham à minha mesa.

[[v16-5-18]]

^<<v16-5-18,18>>^ E o que se preparava para cada dia era um boi e seis ovelhas escolhidas; também aves se me preparavam e, de dez em dez dias, muito vinho de todas as espécies; e nem por isso exigi o pão do governador, porquanto a servidão deste povo era grande.

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te de mim para bem, ó meu Deus, e de tudo quanto fiz a este povo.

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]