include::./index.adoc[]

[[v4-29-0]]
=== Números, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-29-1]]

^<<v4-29-1,1>>^ Semelhantemente, tereis santa convocação no sétimo mês, no primeiro dia do mês; nenhum trabalho servil fareis; será para vós dia de sonido de trombetas.

[[v4-29-2]]

^<<v4-29-2,2>>^ Então por holocausto, em cheiro suave ao Senhor, oferecereis um novilho, um carneiro e sete cordeiros de um ano, sem defeito.

[[v4-29-3]]

^<<v4-29-3,3>>^ E pela sua oferta de alimentos de flor de farinha misturada com azeite, três décimas para o novilho, e duas décimas para o carneiro,

[[v4-29-4]]

^<<v4-29-4,4>>^ E uma décima para cada um dos sete cordeiros.

[[v4-29-5]]

^<<v4-29-5,5>>^ E um bode para expiação do pecado, para fazer expiação por vós;

[[v4-29-6]]

^<<v4-29-6,6>>^ Além do holocausto do mês, e a sua oferta de alimentos, e o holocausto contínuo, e a sua oferta de alimentos, com as suas libações, segundo o seu estatuto, em cheiro suave, oferta queimada ao Senhor.

[[v4-29-7]]

^<<v4-29-7,7>>^ E no dia dez deste sétimo mês tereis santa convocação, e afligireis as vossas almas; nenhum trabalho fareis.

[[v4-29-8]]

^<<v4-29-8,8>>^ Mas por holocausto, em cheiro suave ao Senhor, oferecereis um novilho, um carneiro e sete cordeiros de um ano; eles serão sem defeito.

[[v4-29-9]]

^<<v4-29-9,9>>^ E, pela sua oferta de alimentos de flor de farinha misturada com azeite, três décimas para o novilho, duas décimas para o carneiro,

[[v4-29-10]]

^<<v4-29-10,10>>^ E uma décima para cada um dos sete cordeiros;

[[v4-29-11]]

^<<v4-29-11,11>>^ Um bode para expiação do pecado, além da expiação do pecado pelas propiciações, e do holocausto contínuo, e da sua oferta de alimentos com as suas libações.

[[v4-29-12]]

^<<v4-29-12,12>>^ Semelhantemente, aos quinze dias deste sétimo mês tereis santa convocação; nenhum trabalho servil fareis; mas sete dias celebrareis festa ao Senhor.

[[v4-29-13]]

^<<v4-29-13,13>>^ E, por holocausto em oferta queimada, de cheiro suave ao Senhor, oferecereis treze novilhos, dois carneiros e catorze cordeiros de um ano; todos eles sem defeito.

[[v4-29-14]]

^<<v4-29-14,14>>^ E, pela sua oferta de alimentos de flor de farinha misturada com azeite, três décimas para cada um dos treze novilhos, duas décimas para cada carneiro, entre os dois carneiros;

[[v4-29-15]]

^<<v4-29-15,15>>^ E uma décima para cada um dos catorze cordeiros;

[[v4-29-16]]

^<<v4-29-16,16>>^ E um bode para expiação do pecado, além do holocausto contínuo, a sua oferta de alimentos e a sua libação;

[[v4-29-17]]

^<<v4-29-17,17>>^ Depois, no segundo dia, doze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-18]]

^<<v4-29-18,18>>^ E a sua oferta de alimentos e as suas libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto;

[[v4-29-19]]

^<<v4-29-19,19>>^ E um bode para expiação do pecado, além do holocausto contínuo, da sua oferta de alimentos e das suas libações.

[[v4-29-20]]

^<<v4-29-20,20>>^ E, no terceiro dia, onze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-21]]

^<<v4-29-21,21>>^ E as suas ofertas de alimentos, e as suas libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto;

[[v4-29-22]]

^<<v4-29-22,22>>^ E um bode para expiação do pecado, além do holocausto contínuo, e da sua oferta de alimentos e da sua libação.

[[v4-29-23]]

^<<v4-29-23,23>>^ E, no quarto dia, dez novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-24]]

^<<v4-29-24,24>>^ A sua oferta de alimentos, e as suas libações para os novilhos, para os carneiros, e para os cordeiros, conforme o seu número, segundo o estatuto;

[[v4-29-25]]

^<<v4-29-25,25>>^ E um bode para expiação do pecado, além do holocausto contínuo, da sua oferta de alimentos e da sua libação.

[[v4-29-26]]

^<<v4-29-26,26>>^ E, no quinto dia, nove novilhos, dois carneiros e catorze cordeiros de um ano, sem defeito.

[[v4-29-27]]

^<<v4-29-27,27>>^ E a sua oferta de alimentos, e as suas libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto;

[[v4-29-28]]

^<<v4-29-28,28>>^ E um bode para expiação do pecado além do holocausto contínuo, e da sua oferta de alimentos e da sua libação.

[[v4-29-29]]

^<<v4-29-29,29>>^ E, no sexto dia, oito novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito;

[[v4-29-30]]

^<<v4-29-30,30>>^ E a sua oferta de alimentos, e as suas libações para os bezerros, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto;

[[v4-29-31]]

^<<v4-29-31,31>>^ E um bode para expiação do pecado, além do holocausto contínuo, da sua oferta de alimentos e da sua libação.

[[v4-29-32]]

^<<v4-29-32,32>>^ E, no sétimo dia, sete novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito.

[[v4-29-33]]

^<<v4-29-33,33>>^ E a sua oferta de alimentos, e as suas libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o seu estatuto,

[[v4-29-34]]

^<<v4-29-34,34>>^ E um bode para expiação do pecado, além do holocausto contínuo, da sua oferta de alimentos e da sua libação.

[[v4-29-35]]

^<<v4-29-35,35>>^ No oitavo dia tereis dia de solenidade; nenhum trabalho servil fareis;

[[v4-29-36]]

^<<v4-29-36,36>>^ E por holocausto em oferta queimada de cheiro suave ao Senhor oferecereis um novilho, um carneiro, sete cordeiros de um ano, sem defeito;

[[v4-29-37]]

^<<v4-29-37,37>>^ A sua oferta de alimentos e as suas libações para o novilho, para o carneiro e para os cordeiros, conforme o seu número, segundo o estatuto.

[[v4-29-38]]

^<<v4-29-38,38>>^ E um bode para expiação do pecado, além do holocausto contínuo, e da sua oferta de alimentos e da sua libação.

[[v4-29-39]]

^<<v4-29-39,39>>^ Estas coisas fareis ao Senhor nas vossas solenidades além dos vossos votos, e das vossas ofertas voluntárias, com os vossos holocaustos, e com as vossas ofertas de alimentos, e com as vossas libações, e com as vossas ofertas pacíficas.

[[v4-29-40]]

^<<v4-29-40,40>>^ E falou Moisés aos filhos de Israel, conforme a tudo o que o Senhor ordenara a Moisés.

'''

xref:004-numeros/004-numeros-028.adoc#v4-28-0[&#60; Capítulo Anterior] | <<v4-29-0,Topo>> | xref:004-numeros/004-numeros-030.adoc#v4-30-0[Próximo Capítulo &#62;]