include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-24-1]]

^<<v4-24-1,1>>^ Vendo Balaão que bem parecia aos olhos do SENHOR que abençoasse a Israel, não se foi esta vez como antes ao encontro dos encantamentos; mas voltou o seu rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ E, levantando Balaão os seus olhos, e vendo a Israel, que estava acampado segundo as suas tribos, veio sobre ele o Espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ E proferiu a sua parábola, e disse: Fala, Balaão, filho de Beor, e fala o homem de olhos abertos;

[[v4-24-4]]

^<<v4-24-4,4>>^ Fala aquele que ouviu as palavras de Deus, o que vê a visão do Todo-Poderoso; que cai, e se lhe abrem os olhos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Quão formosas são as tuas tendas, ó Jacó, as tuas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como ribeiros se estendem, como jardins à beira dos rios; como árvores de sândalo o Senhor os plantou, como cedros junto às águas;

[[v4-24-7]]

^<<v4-24-7,7>>^ De seus baldes manarão águas, e a sua semente estará em muitas águas; e o seu rei se erguerá mais do que Agague, e o seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus o tirou do Egito; as suas forças são como as do boi selvagem; consumirá as nações, seus inimigos, e quebrará seus ossos, e com as suas setas os atravessará.

[[v4-24-9]]

^<<v4-24-9,9>>^ Encurvou-se, deitou-se como leão, e como leoa; quem o despertará? benditos os que te abençoarem, e malditos os que te amaldiçoarem.

[[v4-24-10]]

^<<v4-24-10,10>>^ Então a ira de Balaque se acendeu contra Balaão, e bateu ele as suas palmas; e Balaque disse a Balaão: Para amaldiçoar os meus inimigos te tenho chamado; porém agora já três vezes os abençoaste inteiramente.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora, pois, foge para o teu lugar; eu tinha dito que te honraria grandemente; mas eis que o Senhor te privou desta honra.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então Balaão disse a Balaque: Não falei eu também aos teus mensageiros, que me enviaste, dizendo:

[[v4-24-13]]

^<<v4-24-13,13>>^ Ainda que Balaque me desse a sua casa cheia de prata e ouro, não poderia ir além da ordem do Senhor, fazendo bem ou mal de meu próprio coração; o que o Senhor falar, isso falarei eu?

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora, pois, eis que me vou ao meu povo; vem, avisar-te-ei do que este povo fará ao teu povo nos últimos dias.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então proferiu a sua parábola, e disse: Fala Balaão, filho de Beor, e fala o homem de olhos abertos;

[[v4-24-16]]

^<<v4-24-16,16>>^ Fala aquele que ouviu as palavras de Deus, e o que sabe a ciência do Altíssimo; o que viu a visão do Todo-Poderoso, que cai, e se lhe abrem os olhos.

[[v4-24-17]]

^<<v4-24-17,17>>^ Vê-lo-ei, mas não agora, contemplá-lo-ei, mas não de perto; uma estrela procederá de Jacó e um cetro subirá de Israel, que ferirá os termos dos moabitas, e destruirá todos os filhos de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ E Edom será uma possessão, e Seir, seus inimigos, também será uma possessão; pois Israel fará proezas.

[[v4-24-19]]

^<<v4-24-19,19>>^ E dominará um de Jacó, e matará os que restam das cidades.

[[v4-24-20]]

^<<v4-24-20,20>>^ E vendo os amalequitas, proferiu a sua parábola, e disse: Amaleque é a primeira das nações; porém o seu fim será a destruição.

[[v4-24-21]]

^<<v4-24-21,21>>^ E vendo os quenitas, proferiu a sua parábola, e disse: Firme está a tua habitação, e puseste o teu ninho na penha.

[[v4-24-22]]

^<<v4-24-22,22>>^ Todavia o quenita será consumido, até que Assur te leve por prisioneiro.

[[v4-24-23]]

^<<v4-24-23,23>>^ E, proferindo ainda a sua parábola, disse: Ai, quem viverá, quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ E as naus virão das costas de Quitim e afligirão a Assur; também afligirão a Éber; que também será para destruição.

[[v4-24-25]]

^<<v4-24-25,25>>^ Então Balaão levantou-se, e se foi, e voltou ao seu lugar, e também Balaque se foi pelo seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]