include::./index.adoc[]

[[v4-15-0]]
=== Números, 15
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-15-1]]

^<<v4-15-1,1>>^ Depois falou o SENHOR a Moisés, dizendo:

[[v4-15-2]]

^<<v4-15-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando entrardes na terra das vossas habitações, que eu vos hei de dar,

[[v4-15-3]]

^<<v4-15-3,3>>^ E ao Senhor fizerdes oferta queimada, holocausto, ou sacrifício, para cumprir um voto, ou em oferta voluntária, ou nas vossas solenidades, para fazerdes ao Senhor um cheiro suave de ovelhas ou gado,

[[v4-15-4]]

^<<v4-15-4,4>>^ Então aquele que apresentar a sua oferta ao Senhor, por oferta de alimentos trará uma décima de flor de farinha misturada com a quarta parte de um him de azeite.

[[v4-15-5]]

^<<v4-15-5,5>>^ E de vinho para libação prepararás a quarta parte de um him, para holocausto, ou para sacrifício para cada cordeiro;

[[v4-15-6]]

^<<v4-15-6,6>>^ E para cada carneiro prepararás uma oferta de alimentos de duas décimas de flor de farinha, misturada com a terça parte de um him de azeite.

[[v4-15-7]]

^<<v4-15-7,7>>^ E de vinho para a libação oferecerás a terça parte de um him ao Senhor, em cheiro suave.

[[v4-15-8]]

^<<v4-15-8,8>>^ E, quando preparares novilho para holocausto ou sacrifício, para cumprir um voto, ou um sacrifício pacífico ao Senhor,

[[v4-15-9]]

^<<v4-15-9,9>>^ Com o novilho apresentarás uma oferta de alimentos de três décimas de flor de farinha misturada com a metade de um him de azeite.

[[v4-15-10]]

^<<v4-15-10,10>>^ E de vinho para a libação oferecerás a metade de um him, oferta queimada em cheiro suave ao Senhor.

[[v4-15-11]]

^<<v4-15-11,11>>^ Assim se fará com cada boi, ou com cada carneiro, ou com cada um dos cordeiros ou cabritos.

[[v4-15-12]]

^<<v4-15-12,12>>^ Segundo o número que oferecerdes, assim o fareis com cada um, segundo o número deles.

[[v4-15-13]]

^<<v4-15-13,13>>^ Todo o natural assim fará estas coisas, oferecendo oferta queimada em cheiro suave ao Senhor.

[[v4-15-14]]

^<<v4-15-14,14>>^ Quando também peregrinar convosco algum estrangeiro, ou que estiver no meio de vós nas vossas gerações, e ele apresentar uma oferta queimada de cheiro suave ao Senhor, como vós fizerdes, assim fará ele.

[[v4-15-15]]

^<<v4-15-15,15>>^ Um mesmo estatuto haja para vós, ó congregação, e para o estrangeiro que entre vós peregrina, por estatuto perpétuo nas vossas gerações; como vós, assim será o peregrino perante o Senhor.

[[v4-15-16]]

^<<v4-15-16,16>>^ Uma mesma lei e um mesmo direito haverá para vós e para o estrangeiro que peregrina convosco.

[[v4-15-17]]

^<<v4-15-17,17>>^ Falou mais o Senhor a Moisés, dizendo:

[[v4-15-18]]

^<<v4-15-18,18>>^ Fala aos filhos de Israel, e dize-lhes: Quando entrardes na terra em que vos hei de introduzir,

[[v4-15-19]]

^<<v4-15-19,19>>^ Acontecerá que, quando comerdes do pão da terra, então oferecereis ao Senhor oferta alçada.

[[v4-15-20]]

^<<v4-15-20,20>>^ Das primícias da vossa massa oferecereis um bolo em oferta alçada; como a oferta da eira, assim o oferecereis.

[[v4-15-21]]

^<<v4-15-21,21>>^ Das primícias das vossas massas dareis ao Senhor oferta alçada nas vossas gerações.

[[v4-15-22]]

^<<v4-15-22,22>>^ E, quando vierdes a errar, e não cumprirdes todos estes mandamentos, que o Senhor falou a Moisés,

[[v4-15-23]]

^<<v4-15-23,23>>^ Tudo quanto o Senhor vos tem mandado por intermédio de Moisés, desde o dia que o Senhor ordenou, e dali em diante, nas vossas gerações,

[[v4-15-24]]

^<<v4-15-24,24>>^ Será que, quando se fizer alguma coisa por ignorância, e for encoberto aos olhos da congregação, toda a congregação oferecerá um novilho para holocausto em cheiro suave ao Senhor, com a sua oferta de alimentos e libação conforme ao estatuto, e um bode para expiação do pecado.

[[v4-15-25]]

^<<v4-15-25,25>>^ E o sacerdote fará expiação por toda a congregação dos filhos de Israel, e lhes será perdoado, porquanto foi por ignorância; e trouxeram a sua oferta, oferta queimada ao Senhor, e a sua expiação do pecado perante o Senhor, por causa da sua ignorância.

[[v4-15-26]]

^<<v4-15-26,26>>^ Será, pois, perdoado a toda a congregação dos filhos de Israel, e mais ao estrangeiro que peregrina no meio deles, porquanto por ignorância sobreveio a todo o povo.

[[v4-15-27]]

^<<v4-15-27,27>>^ E, se alguma alma pecar por ignorância, para expiação do pecado oferecerá uma cabra de um ano.

[[v4-15-28]]

^<<v4-15-28,28>>^ E o sacerdote fará expiação pela pessoa que pecou, quando pecar por ignorância, perante o Senhor, fazendo expiação por ela, e lhe será perdoado.

[[v4-15-29]]

^<<v4-15-29,29>>^ Para o natural dos filhos de Israel, e para o estrangeiro que no meio deles peregrina, uma mesma lei vos será, para aquele que pecar por ignorância.

[[v4-15-30]]

^<<v4-15-30,30>>^ Mas a pessoa que fizer alguma coisa temerariamente, quer seja dos naturais quer dos estrangeiros, injuria ao Senhor; tal pessoa será extirpada do meio do seu povo.

[[v4-15-31]]

^<<v4-15-31,31>>^ Pois desprezou a palavra do Senhor, e anulou o seu mandamento; totalmente será extirpada aquela pessoa, a sua iniqüidade será sobre ela.

[[v4-15-32]]

^<<v4-15-32,32>>^ Estando, pois, os filhos de Israel no deserto, acharam um homem apanhando lenha no dia de sábado.

[[v4-15-33]]

^<<v4-15-33,33>>^ E os que o acharam apanhando lenha o trouxeram a Moisés e a Arão, e a toda a congregação.

[[v4-15-34]]

^<<v4-15-34,34>>^ E o puseram em guarda; porquanto ainda não estava declarado o que se lhe devia fazer.

[[v4-15-35]]

^<<v4-15-35,35>>^ Disse, pois, o Senhor a Moisés: Certamente morrerá aquele homem; toda a congregação o apedrejará fora do arraial.

[[v4-15-36]]

^<<v4-15-36,36>>^ Então toda a congregação o tirou para fora do arraial, e o apedrejaram, e morreu, como o Senhor ordenara a Moisés.

[[v4-15-37]]

^<<v4-15-37,37>>^ E falou o Senhor a Moisés, dizendo:

[[v4-15-38]]

^<<v4-15-38,38>>^ Fala aos filhos de Israel, e dize-lhes: Que nas bordas das suas vestes façam franjas pelas suas gerações; e nas franjas das bordas ponham um cordão de azul.

[[v4-15-39]]

^<<v4-15-39,39>>^ E as franjas vos serão para que, vendo-as, vos lembreis de todos os mandamentos do Senhor, e os cumprais; e não seguireis o vosso coração, nem após os vossos olhos, pelos quais andais vos prostituindo.

[[v4-15-40]]

^<<v4-15-40,40>>^ Para que vos lembreis de todos os meus mandamentos, e os cumprais, e santos sejais a vosso Deus.

[[v4-15-41]]

^<<v4-15-41,41>>^ Eu sou o Senhor vosso Deus, que vos tirei da terra do Egito, para ser vosso Deus. Eu sou o Senhor vosso Deus.

'''

xref:004-numeros/004-numeros-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numeros/004-numeros-016.adoc#v4-16-0[Próximo Capítulo &#62;]