include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-4-1]]

^<<v4-4-1,1>>^ E falou o SENHOR a Moisés e a Arão, dizendo:

[[v4-4-2]]

^<<v4-4-2,2>>^ Fazei a soma dos filhos de Coate, dentre os filhos de Levi, pelas suas famílias, segundo a casa de seus pais;

[[v4-4-3]]

^<<v4-4-3,3>>^ Da idade de trinta anos para cima até aos cinqüenta anos, será todo aquele que entrar neste serviço, para fazer o trabalho na tenda da congregação.

[[v4-4-4]]

^<<v4-4-4,4>>^ Este será o ministério dos filhos de Coate na tenda da congregação, nas coisas santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando partir o arraial, Arão e seus filhos virão e tirarão o véu da tenda, e com ele cobrirão a arca do testemunho;

[[v4-4-6]]

^<<v4-4-6,6>>^ E pôr-lhe-ão por cima uma coberta de peles de texugos, e sobre ela estenderão um pano, todo azul, e lhe colocarão os varais.

[[v4-4-7]]

^<<v4-4-7,7>>^ Também sobre a mesa da proposição estenderão um pano azul; e sobre ela porão os pratos, as colheres, e as taças e os jarros para libação; também o pão contínuo estará sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Depois estenderão em cima deles um pano de carmesim, e com a coberta de peles de texugos o cobrirão, e lhe colocarão os seus varais.

[[v4-4-9]]

^<<v4-4-9,9>>^ Então tomarão um pano azul, e cobrirão o candelabro da luminária, e as suas lâmpadas, e os seus espevitadores, e os seus apagadores, e todos os seus vasos de azeite, com que o servem.

[[v4-4-10]]

^<<v4-4-10,10>>^ E envolverão, a ele e a todos os seus utensílios, na coberta de peles de texugos; e o colocarão sobre os varais.

[[v4-4-11]]

^<<v4-4-11,11>>^ E sobre o altar de ouro estenderão um pano azul, e com a coberta de peles de texugos, o cobrirão, e lhe colocarão os seus varais.

[[v4-4-12]]

^<<v4-4-12,12>>^ Também tomarão todos os utensílios do ministério, com que servem no santuário; e os colocarão num pano azul, e os cobrirão com uma coberta de peles de texugos, e os colocarão sobre os varais.

[[v4-4-13]]

^<<v4-4-13,13>>^ E tirarão as cinzas do altar, e por cima dele estenderão um pano de púrpura.

[[v4-4-14]]

^<<v4-4-14,14>>^ E sobre ele colocarão todos os seus instrumentos com que o servem: os seus braseiros, os garfos e as pás, e as bacias; todos os pertences do altar; e por cima dele estenderão uma coberta de peles de texugos, e lhe colocarão os seus varais.

[[v4-4-15]]

^<<v4-4-15,15>>^ Havendo, pois, Arão e seus filhos, ao partir do arraial, acabado de cobrir o santuário, e todos os instrumentos do santuário, então os filhos de Coate virão para levá-lo; mas no santuário não tocarão para que não morram; este é o cargo dos filhos de Coate na tenda da congregação.

[[v4-4-16]]

^<<v4-4-16,16>>^ Porém o cargo de Eleazar, filho de Arão, o sacerdote, será o azeite da luminária e o incenso aromático, e a contínua oferta dos alimentos, e o azeite da unção, o cargo de todo o tabernáculo, e de tudo que nele há, o santuário e os seus utensílios.

[[v4-4-17]]

^<<v4-4-17,17>>^ E falou o Senhor a Moisés e a Arão, dizendo:

[[v4-4-18]]

^<<v4-4-18,18>>^ Não deixareis extirpar a tribo das famílias dos coatitas do meio dos levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Mas isto lhes fareis, para que vivam e não morram, quando se aproximarem das coisas santíssimas: Arão e seus filhos virão, e a cada um colocarão no seu ministério e no seu cargo,

[[v4-4-20]]

^<<v4-4-20,20>>^ Porém não entrarão a ver, quando cobrirem o santuário, para que não morram.

[[v4-4-21]]

^<<v4-4-21,21>>^ Falou mais o Senhor a Moisés, dizendo:

[[v4-4-22]]

^<<v4-4-22,22>>^ Fazei também a soma dos filhos de Gérson, segundo a casa de seus pais, segundo as suas famílias:

[[v4-4-23]]

^<<v4-4-23,23>>^ Da idade de trinta anos para cima até aos cinqüenta, contarás a todo aquele que entrar a se ocupar no seu serviço, para executar o ministério na tenda da congregação.

[[v4-4-24]]

^<<v4-4-24,24>>^ Este será o ministério das famílias dos gersonitas no serviço e no cargo.

[[v4-4-25]]

^<<v4-4-25,25>>^ Levarão, pois, as cortinas do tabernáculo, e a tenda da congregação, e a sua coberta, e a coberta de peles de texugos, que está por cima dele, e a cortina da porta da tenda da congregação,

[[v4-4-26]]

^<<v4-4-26,26>>^ E as cortinas do pátio, e a cortina da porta do pátio, que está junto ao tabernáculo, e junto ao altar em redor, e as suas cordas, e todos os instrumentos do seu ministério, com tudo o que diz respeito a eles, para que sirvam.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o ministério dos filhos dos gersonitas, em todo o seu cargo, e em todo o seu trabalho, será segundo o mandado de Arão e de seus filhos; e lhes designareis as responsabilidades do seu cargo.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é o ministério das famílias dos filhos dos gersonitas na tenda da congregação; e a sua guarda será debaixo da mão de Itamar, filho de Arão, o sacerdote.

[[v4-4-29]]

^<<v4-4-29,29>>^ Quanto aos filhos de Merari, segundo as suas famílias e segundo a casa de seus pais os contarás;

[[v4-4-30]]

^<<v4-4-30,30>>^ Da idade de trinta anos para cima, até aos cinqüenta, contarás a todo aquele que entrar neste serviço, para administrar o ministério da tenda da congregação.

[[v4-4-31]]

^<<v4-4-31,31>>^ Esta, pois, será a responsabilidade do seu cargo, segundo todo o seu ministério, na tenda da congregação: As tábuas do tabernáculo, e os seus varais, e as suas colunas, e as suas bases;

[[v4-4-32]]

^<<v4-4-32,32>>^ Como também as colunas do pátio em redor, e as suas bases, e as suas estacas, e as suas cordas, com todos os seus instrumentos, e com todo o seu ministério; e contareis os objetos que ficarão a seu cargo, nome por nome.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é o ministério das famílias dos filhos de Merari, segundo todo o seu ministério, na tenda da congregação, debaixo da mão de Itamar, filho de Arão, o sacerdote.

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, pois, e Arão e os príncipes da congregação contaram os filhos dos coatitas, segundo as suas famílias e segundo a casa de seus pais;

[[v4-4-35]]

^<<v4-4-35,35>>^ Da idade de trinta anos para cima, até aos cinqüenta, todo aquele que entrou neste serviço, para o ministério da tenda da congregação.

[[v4-4-36]]

^<<v4-4-36,36>>^ Os que deles foram contados, pois, segundo as suas famílias, foram dois mil e setecentos e cinqüenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ Estes são os que foram contados das famílias dos coatitas, de todo aquele que ministrava na tenda da congregação, os quais Moisés e Arão contaram, conforme ao mandado do Senhor pela mão de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Semelhantemente os que foram contados dos filhos de Gérson, segundo as suas famílias, e segundo a casa de seus pais;

[[v4-4-39]]

^<<v4-4-39,39>>^ Da idade de trinta anos para cima até aos cinqüenta, todo aquele que entrou neste serviço, para o ministério na tenda da congregação.

[[v4-4-40]]

^<<v4-4-40,40>>^ Os que deles foram contados, segundo as suas famílias, segundo a casa de seus pais, foram dois mil e seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ Estes são os contados das famílias dos filhos de Gérson, de todo aquele que ministrava na tenda da congregação; os quais Moisés e Arão contaram, conforme ao mandado do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ E os que foram contados das famílias dos filhos de Merari, segundo as suas famílias, segundo a casa de seus pais;

[[v4-4-43]]

^<<v4-4-43,43>>^ Da idade de trinta anos para cima, até aos cinqüenta, todo aquele que entrou neste serviço, para o ministério na tenda da congregação.

[[v4-4-44]]

^<<v4-4-44,44>>^ Os que deles foram contados, segundo as suas famílias, eram três mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ Estes são os contados das famílias dos filhos de Merari; os quais Moisés e Arão contaram, conforme ao mandado do Senhor, pela mão de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os que deles foram contados, que contaram Moisés e Arão, e os príncipes de Israel, dos levitas, segundo as suas famílias, segundo a casa de seus pais;

[[v4-4-47]]

^<<v4-4-47,47>>^ Da idade de trinta anos para cima, até aos cinqüenta, todo aquele que entrava a executar o ministério da administração, e o ministério das cargas na tenda da congregação.

[[v4-4-48]]

^<<v4-4-48,48>>^ Os que deles foram contados foram oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Conforme ao mandado do Senhor, pela mão de Moisés, foram contados cada qual segundo o seu ministério, e segundo o seu cargo; assim foram contados por ele, como o Senhor ordenara a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]