include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-12-1]]

^<<v4-12-1,1>>^ E falaram Miriã e Arão contra Moisés, por causa da mulher cusita, com quem casara; porquanto tinha casado com uma mulher cusita.

[[v4-12-2]]

^<<v4-12-2,2>>^ E disseram: Porventura falou o Senhor somente por Moisés? Não falou também por nós? E o Senhor o ouviu.

[[v4-12-3]]

^<<v4-12-3,3>>^ E era o homem Moisés mui manso, mais do que todos os homens que havia sobre a terra.

[[v4-12-4]]

^<<v4-12-4,4>>^ E logo o Senhor disse a Moisés, a Arão e a Miriã: Vós três saí à tenda da congregação. E saíram eles três.

[[v4-12-5]]

^<<v4-12-5,5>>^ Então o Senhor desceu na coluna de nuvem, e se pôs à porta da tenda; depois chamou a Arão e a Miriã e ambos saíram.

[[v4-12-6]]

^<<v4-12-6,6>>^ E disse: Ouvi agora as minhas palavras; se entre vós houver profeta, eu, o Senhor, em visão a ele me farei conhecer, ou em sonhos falarei com ele.

[[v4-12-7]]

^<<v4-12-7,7>>^ Não é assim com o meu servo Moisés que é fiel em toda a minha casa.

[[v4-12-8]]

^<<v4-12-8,8>>^ Boca a boca falo com ele, claramente e não por enigmas; pois ele vê a semelhança do Senhor; por que, pois, não tivestes temor de falar contra o meu servo, contra Moisés?

[[v4-12-9]]

^<<v4-12-9,9>>^ Assim a ira do Senhor contra eles se acendeu; e retirou-se.

[[v4-12-10]]

^<<v4-12-10,10>>^ E a nuvem se retirou de sobre a tenda; e eis que Miriã ficou leprosa como a neve; e olhou Arão para Miriã, e eis que estava leprosa.

[[v4-12-11]]

^<<v4-12-11,11>>^ Por isso Arão disse a Moisés: Ai, senhor meu, não ponhas sobre nós este pecado, pois agimos loucamente, e temos pecado.

[[v4-12-12]]

^<<v4-12-12,12>>^ Ora, não seja ela como um morto, que saindo do ventre de sua mãe, a metade da sua carne já esteja consumida.

[[v4-12-13]]

^<<v4-12-13,13>>^ Clamou, pois, Moisés ao Senhor, dizendo: Ó Deus, rogo-te que a cures.

[[v4-12-14]]

^<<v4-12-14,14>>^ E disse o Senhor a Moisés: Se seu pai cuspira em seu rosto, não seria envergonhada sete dias? Esteja fechada sete dias fora do arraial, e depois a recolham.

[[v4-12-15]]

^<<v4-12-15,15>>^ Assim Miriã esteve fechada fora do arraial sete dias, e o povo não partiu, até que recolheram a Miriã.

[[v4-12-16]]

^<<v4-12-16,16>>^ Porém, depois o povo partiu de Hazerote; e acampou-se no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]