include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-36-1]]

^<<v4-36-1,1>>^ E chegaram os chefes dos pais da família de Gileade, filho de Maquir, filho de Manassés, das famílias dos filhos de José, e falaram diante de Moisés, e diante dos príncipes, chefes dos pais dos filhos de Israel,

[[v4-36-2]]

^<<v4-36-2,2>>^ E disseram: O SENHOR mandou a meu senhor que, por sorte, desse esta terra em herança aos filhos de Israel; e a meu senhor foi ordenado pelo SENHOR, que a herança do nosso irmão Zelofeade se desse às suas filhas.

[[v4-36-3]]

^<<v4-36-3,3>>^ E, casando-se elas com alguns dos filhos das outras tribos dos filhos de Israel, então a sua herança será diminuída da herança de nossos pais, e acrescentada à herança da tribo a que vierem a pertencer; assim se tirará da sorte da nossa herança.

[[v4-36-4]]

^<<v4-36-4,4>>^ Vindo também o ano do jubileu dos filhos de Israel, a sua herança será acrescentada à herança da tribo daqueles com que se casarem; assim a sua herança será tirada da herança da tribo de nossos pais.

[[v4-36-5]]

^<<v4-36-5,5>>^ Então Moisés deu ordem aos filhos de Israel, segundo o mandado do Senhor, dizendo: A tribo dos filhos de José fala o que é justo.

[[v4-36-6]]

^<<v4-36-6,6>>^ Isto é o que o Senhor mandou acerca das filhas de Zelofeade, dizendo: Sejam por mulheres a quem bem parecer aos seus olhos, contanto que se casem na família da tribo de seu pai.

[[v4-36-7]]

^<<v4-36-7,7>>^ Assim a herança dos filhos de Israel não passará de tribo em tribo; pois os filhos de Israel se chegarão cada um à herança da tribo de seus pais.

[[v4-36-8]]

^<<v4-36-8,8>>^ E qualquer filha que herdar alguma herança das tribos dos filhos de Israel se casará com alguém da família da tribo de seu pai; para que os filhos de Israel possuam cada um a herança de seus pais.

[[v4-36-9]]

^<<v4-36-9,9>>^ Assim a herança não passará de uma tribo a outra; pois as tribos dos filhos de Israel se chegarão cada uma à sua herança.

[[v4-36-10]]

^<<v4-36-10,10>>^ Como o Senhor ordenara a Moisés, assim fizeram as filhas de Zelofeade.

[[v4-36-11]]

^<<v4-36-11,11>>^ Pois Maalá, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, se casaram com os filhos de seus tios.

[[v4-36-12]]

^<<v4-36-12,12>>^ E elas casaram-se nas famílias dos filhos de Manassés, filho de José; assim a sua herança ficou na tribo da família de seu pai.

[[v4-36-13]]

^<<v4-36-13,13>>^ Estes são os mandamentos e os juízos que mandou o Senhor através de Moisés aos filhos de Israel nas campinas de Moabe, junto ao Jordão, na direção de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]