include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-23-1]]

^<<v4-23-1,1>>^ Então Balaão disse a Balaque: Edifica-me aqui sete altares, e prepara-me aqui sete novilhos e sete carneiros.

[[v4-23-2]]

^<<v4-23-2,2>>^ Fez, pois, Balaque como Balaão dissera: e Balaque e Balaão ofereceram um novilho e um carneiro sobre cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Então Balaão disse a Balaque: Fica-te junto do teu holocausto, e eu irei; porventura o Senhor me sairá ao encontro, e o que me mostrar te notificarei. Então foi a um lugar alto.

[[v4-23-4]]

^<<v4-23-4,4>>^ E encontrando-se Deus com Balaão, este lhe disse: Preparei sete altares, e ofereci um novilho e um carneiro sobre cada altar.

[[v4-23-5]]

^<<v4-23-5,5>>^ Então o Senhor pôs a palavra na boca de Balaão, e disse: Torna-te para Balaque, e assim falarás.

[[v4-23-6]]

^<<v4-23-6,6>>^ E tornando para ele, eis que estava junto do seu holocausto, ele e todos os príncipes dos moabitas.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então proferiu a sua parábola, e disse: De Arã, me mandou trazer Balaque, rei dos moabitas, das montanhas do oriente, dizendo: Vem, amaldiçoa-me a Jacó; e vem, denuncia a Israel.

[[v4-23-8]]

^<<v4-23-8,8>>^ Como amaldiçoarei o que Deus não amaldiçoa? E como denunciarei, quando o Senhor não denuncia?

[[v4-23-9]]

^<<v4-23-9,9>>^ Porque do cume das penhas o vejo, e dos outeiros o contemplo; eis que este povo habitará só, e entre as nações não será contado.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem contará o pó de Jacó e o número da quarta parte de Israel? Que a minha alma morra da morte dos justos, e seja o meu fim como o seu.

[[v4-23-11]]

^<<v4-23-11,11>>^ Então disse Balaque a Balaão: Que me fizeste? Chamei-te para amaldiçoar os meus inimigos, mas eis que inteiramente os abençoaste.

[[v4-23-12]]

^<<v4-23-12,12>>^ E ele respondeu, e disse: Porventura não terei cuidado de falar o que o Senhor pôs na minha boca?

[[v4-23-13]]

^<<v4-23-13,13>>^ Então Balaque lhe disse: Rogo-te que venhas comigo a outro lugar, de onde o verás; verás somente a última parte dele, mas a todo ele não verás; e amaldiçoa-mo dali.

[[v4-23-14]]

^<<v4-23-14,14>>^ Assim o levou consigo ao campo de Zofim, ao cume de Pisga; e edificou sete altares, e ofereceu um novilho e um carneiro sobre cada altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Então disse a Balaque: Fica aqui junto do teu holocausto, e eu irei ali ao encontro do Senhor.

[[v4-23-16]]

^<<v4-23-16,16>>^ E, encontrando-se o Senhor com Balaão, pôs uma palavra na sua boca, e disse: Torna para Balaque, e assim falarás.

[[v4-23-17]]

^<<v4-23-17,17>>^ E, vindo a ele, eis que estava junto do holocausto, e os príncipes dos moabitas com ele; disse-lhe pois Balaque: Que coisa falou o Senhor?

[[v4-23-18]]

^<<v4-23-18,18>>^ Então proferiu a sua parábola, e disse: Levanta-te, Balaque, e ouve; inclina os teus ouvidos a mim, filho de Zipor.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem, para que minta; nem filho do homem, para que se arrependa; porventura diria ele, e não o faria? Ou falaria, e não o confirmaria?

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que recebi mandado de abençoar; pois ele tem abençoado, e eu não o posso revogar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Não viu iniqüidade em Israel, nem contemplou maldade em Jacó; o Senhor seu Deus é com ele, e no meio dele se ouve a aclamação de um rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; as suas forças são como as do boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não vale encantamento, nem adivinhação contra Israel; neste tempo se dirá de Jacó e de Israel: Que coisas Deus tem realizado!

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que o povo se levantará como leoa, e se erguerá como leão; não se deitará até que coma a presa, e beba o sangue dos mortos.

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: Nem o amaldiçoarás, nem o abençoarás.

[[v4-23-26]]

^<<v4-23-26,26>>^ Porém Balaão respondeu, e disse a Balaque: Não te falei eu, dizendo: Tudo o que o Senhor falar isso farei?

[[v4-23-27]]

^<<v4-23-27,27>>^ Disse mais Balaque a Balaão: Ora vem, e te levarei a outro lugar; porventura bem parecerá aos olhos de Deus que dali mo amaldiçoes.

[[v4-23-28]]

^<<v4-23-28,28>>^ Então Balaque levou Balaão consigo ao cume de Peor, que dá para o lado do deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: Edifica-me aqui sete altares, e prepara-me aqui sete novilhos e sete carneiros.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque, pois, fez como dissera Balaão: e ofereceu um novilho e um carneiro sobre cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]