include::./index.adoc[]

[[v4-31-0]]
=== Números, 31
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-31-1]]

^<<v4-31-1,1>>^ E falou o SENHOR a Moisés, dizendo:

[[v4-31-2]]

^<<v4-31-2,2>>^ Vinga os filhos de Israel dos midianitas; depois recolhido serás ao teu povo.

[[v4-31-3]]

^<<v4-31-3,3>>^ Falou, pois, Moisés ao povo, dizendo: Armem-se alguns de vós para a guerra, e saiam contra os midianitas, para fazerem a vingança do Senhor contra eles.

[[v4-31-4]]

^<<v4-31-4,4>>^ Mil de cada tribo, entre todas as tribos de Israel, enviareis à guerra.

[[v4-31-5]]

^<<v4-31-5,5>>^ Assim foram dados, dos milhares de Israel, mil de cada tribo; doze mil armados para a peleja.

[[v4-31-6]]

^<<v4-31-6,6>>^ E Moisés os mandou à guerra, mil de cada tribo, e com eles Finéias, filho de Eleazar, o sacerdote, com os vasos do santuário, e com as trombetas do alarido na sua mão.

[[v4-31-7]]

^<<v4-31-7,7>>^ E pelejaram contra os midianitas, como o Senhor ordenara a Moisés; e mataram a todos os homens.

[[v4-31-8]]

^<<v4-31-8,8>>^ Mataram também, além dos que já haviam sido mortos, os reis dos midianitas: a Evi, e a Requém, e a Zur, e a Hur, e a Reba, cinco reis dos midianitas; também a Balaão, filho de Beor, mataram à espada.

[[v4-31-9]]

^<<v4-31-9,9>>^ Porém, os filhos de Israel levaram presas as mulheres dos midianitas e as suas crianças; também levaram todos os seus animais e todo o seu gado, e todos os seus bens.

[[v4-31-10]]

^<<v4-31-10,10>>^ E queimaram a fogo todas as suas cidades com todas as suas habitações e todos os seus acampamentos.

[[v4-31-11]]

^<<v4-31-11,11>>^ E tomaram todo o despojo e toda a presa de homens e de animais.

[[v4-31-12]]

^<<v4-31-12,12>>^ E trouxeram a Moisés e a Eleazar, o sacerdote, e à congregação dos filhos de Israel, os cativos, e a presa, e o despojo, para o arraial, nas campinas de Moabe, que estão junto ao Jordão, na altura de Jericó.

[[v4-31-13]]

^<<v4-31-13,13>>^ Porém Moisés e Eleazar, o sacerdote, e todos os príncipes da congregação, saíram a recebê-los fora do arraial.

[[v4-31-14]]

^<<v4-31-14,14>>^ E indignou-se Moisés grandemente contra os oficiais do exército, capitães dos milhares e capitães das centenas, que vinham do serviço da guerra.

[[v4-31-15]]

^<<v4-31-15,15>>^ E Moisés disse-lhes: Deixastes viver todas as mulheres?

[[v4-31-16]]

^<<v4-31-16,16>>^ Eis que estas foram as que, por conselho de Balaão, deram ocasião aos filhos de Israel de transgredir contra o Senhor no caso de Peor; por isso houve aquela praga entre a congregação do Senhor.

[[v4-31-17]]

^<<v4-31-17,17>>^ Agora, pois, matai todo o homem entre as crianças, e matai toda a mulher que conheceu algum homem, deitando-se com ele.

[[v4-31-18]]

^<<v4-31-18,18>>^ Porém, todas as meninas que não conheceram algum homem, deitando-se com ele, deixai-as viver para vós.

[[v4-31-19]]

^<<v4-31-19,19>>^ E alojai-vos sete dias fora do arraial; qualquer que tiver matado alguma pessoa, e qualquer que tiver tocado algum morto, ao terceiro dia, e ao sétimo dia vos purificareis, a vós e a vossos cativos.

[[v4-31-20]]

^<<v4-31-20,20>>^ Também purificareis toda a roupa, e toda a obra de peles, e toda a obra de pêlos de cabras, e todo o utensílio de madeira.

[[v4-31-21]]

^<<v4-31-21,21>>^ E disse Eleazar, o sacerdote, aos homens da guerra, que foram à peleja: Este é o estatuto da lei que o Senhor ordenou a Moisés.

[[v4-31-22]]

^<<v4-31-22,22>>^ Contudo o ouro, e a prata, o cobre, o ferro, o estanho, e o chumbo,

[[v4-31-23]]

^<<v4-31-23,23>>^ Toda a coisa que pode resistir ao fogo, fareis passar pelo fogo, para que fique limpa, todavia se purificará com a água da purificação; mas tudo que não pode resistir ao fogo, fareis passar pela água.

[[v4-31-24]]

^<<v4-31-24,24>>^ Também lavareis as vossas roupas ao sétimo dia, para que fiqueis limpos; e depois entrareis no arraial.

[[v4-31-25]]

^<<v4-31-25,25>>^ Falou mais o Senhor a Moisés, dizendo:

[[v4-31-26]]

^<<v4-31-26,26>>^ Faze a soma da presa que foi tomada, de homens e de animais, tu e Eleazar, o sacerdote, e os cabeças das casas dos pais da congregação,

[[v4-31-27]]

^<<v4-31-27,27>>^ E divide a presa em duas metades, entre os que se armaram para a peleja, e saíram à guerra, e toda a congregação.

[[v4-31-28]]

^<<v4-31-28,28>>^ Então para o Senhor tomarás o tributo dos homens de guerra, que saíram a esta peleja, de cada quinhentos uma alma, dos homens, e dos bois, e dos jumentos e das ovelhas.

[[v4-31-29]]

^<<v4-31-29,29>>^ Da sua metade o tomareis, e o dareis ao sacerdote Eleazar, para a oferta alçada do Senhor.

[[v4-31-30]]

^<<v4-31-30,30>>^ Mas, da metade dos filhos de Israel, tomarás um de cada cinqüenta, um dos homens, dos bois, dos jumentos, e das ovelhas, e de todos os animais; e os darás aos levitas que têm cuidado da guarda do tabernáculo do Senhor.

[[v4-31-31]]

^<<v4-31-31,31>>^ E fizeram Moisés e Eleazar, o sacerdote, como o Senhor ordenara a Moisés.

[[v4-31-32]]

^<<v4-31-32,32>>^ Foi a presa, restante do despojo que tomaram os homens de guerra, seiscentas e setenta e cinco mil ovelhas;

[[v4-31-33]]

^<<v4-31-33,33>>^ E setenta e dois mil bois;

[[v4-31-34]]

^<<v4-31-34,34>>^ E sessenta e um mil jumentos;

[[v4-31-35]]

^<<v4-31-35,35>>^ E, das mulheres que não conheceram homem algum, deitando-se com ele, todas as almas foram trinta e duas mil.

[[v4-31-36]]

^<<v4-31-36,36>>^ E a metade, que era a porção dos que saíram à guerra, foi em número de trezentas e trinta e sete mil e quinhentas ovelhas.

[[v4-31-37]]

^<<v4-31-37,37>>^ E das ovelhas, o tributo para o Senhor foi de seiscentas e setenta e cinco.

[[v4-31-38]]

^<<v4-31-38,38>>^ E foram os bois trinta e seis mil; e o seu tributo para o Senhor setenta e dois.

[[v4-31-39]]

^<<v4-31-39,39>>^ E foram os jumentos trinta mil e quinhentos; e o seu tributo para o Senhor sessenta e um.

[[v4-31-40]]

^<<v4-31-40,40>>^ E houve de pessoas dezesseis mil; e o seu tributo para o Senhor trinta e duas pessoas.

[[v4-31-41]]

^<<v4-31-41,41>>^ E deu Moisés a Eleazar, o sacerdote, o tributo da oferta alçada do Senhor, como o Senhor ordenara a Moisés.

[[v4-31-42]]

^<<v4-31-42,42>>^ E da metade dos filhos de Israel que Moisés separara da dos homens que pelejaram,

[[v4-31-43]]

^<<v4-31-43,43>>^ (A metade para a congregação foi, das ovelhas, trezentas e trinta e sete mil e quinhentas;

[[v4-31-44]]

^<<v4-31-44,44>>^ E dos bois trinta e seis mil;

[[v4-31-45]]

^<<v4-31-45,45>>^ E dos jumentos trinta mil e quinhentos;

[[v4-31-46]]

^<<v4-31-46,46>>^ E das pessoas, dezesseis mil).

[[v4-31-47]]

^<<v4-31-47,47>>^ Desta metade dos filhos de Israel, Moisés tomou um de cada cinqüenta, de homens e de animais, e os deu aos levitas, que tinham cuidado da guarda do tabernáculo do Senhor, como o Senhor ordenara a Moisés.

[[v4-31-48]]

^<<v4-31-48,48>>^ Então chegaram-se a Moisés os oficiais que estavam sobre os milhares do exército, os chefes de mil e os chefes de cem;

[[v4-31-49]]

^<<v4-31-49,49>>^ E disseram a Moisés: Teus servos tomaram a soma dos homens de guerra que estiveram sob as nossas ordens; e não falta nenhum de nós.

[[v4-31-50]]

^<<v4-31-50,50>>^ Por isso trouxemos uma oferta ao Senhor, cada um o que achou, objetos de ouro, cadeias, ou manilhas, anéis, arrecadas, e colares, para fazer expiação pelas nossas almas perante o Senhor.

[[v4-31-51]]

^<<v4-31-51,51>>^ Assim Moisés e Eleazar, o sacerdote, receberam deles o ouro, sendo todos os objetos bem trabalhados.

[[v4-31-52]]

^<<v4-31-52,52>>^ E foi todo o ouro da oferta alçada, que ofereceram ao Senhor, dezesseis mil e setecentos e cinqüenta siclos, dos chefes de mil e dos chefes de cem

[[v4-31-53]]

^<<v4-31-53,53>>^ (Pois cada um dos homens de guerra, tinha tomado presa para si).

[[v4-31-54]]

^<<v4-31-54,54>>^ Receberam, pois, Moisés e Eleazar, o sacerdote, o ouro dos chefes de mil e dos chefes de cem, e o levaram à tenda da congregação, por memorial para os filhos de Israel perante o Senhor.

'''

xref:004-numeros/004-numeros-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numeros/004-numeros-032.adoc#v4-32-0[Próximo Capítulo &#62;]