include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-28-1]]

^<<v4-28-1,1>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v4-28-2]]

^<<v4-28-2,2>>^ Dá ordem aos filhos de Israel, e dize-lhes: Da minha oferta, do meu alimento para as minhas ofertas queimadas, do meu cheiro suave, tereis cuidado, para me oferecê-las ao seu tempo determinado.

[[v4-28-3]]

^<<v4-28-3,3>>^ E dir-lhes-ás: Esta é a oferta queimada que oferecereis ao Senhor: dois cordeiros de um ano, sem defeito, cada dia, em contínuo holocausto;

[[v4-28-4]]

^<<v4-28-4,4>>^ Um cordeiro sacrificarás pela manhã, e o outro cordeiro sacrificarás à tarde;

[[v4-28-5]]

^<<v4-28-5,5>>^ E a décima parte de um efa de flor de farinha em oferta de alimentos, misturada com a quarta parte de um him de azeite batido.

[[v4-28-6]]

^<<v4-28-6,6>>^ Este é o holocausto contínuo, instituído no monte Sinai, em cheiro suave, oferta queimada ao Senhor.

[[v4-28-7]]

^<<v4-28-7,7>>^ E a sua libação será a quarta parte de um him para um cordeiro; no santuário, oferecerás a libação de bebida forte ao Senhor.

[[v4-28-8]]

^<<v4-28-8,8>>^ E o outro cordeiro sacrificarás à tarde, como a oferta de alimentos da manhã, e como a sua libação o oferecerás em oferta queimada de cheiro suave ao Senhor.

[[v4-28-9]]

^<<v4-28-9,9>>^ Porém, no dia de sábado, oferecerás dois cordeiros de um ano, sem defeito, e duas décimas de flor de farinha, misturada com azeite, em oferta de alimentos, com a sua libação.

[[v4-28-10]]

^<<v4-28-10,10>>^ Holocausto é de cada sábado, além do holocausto contínuo, e a sua libação.

[[v4-28-11]]

^<<v4-28-11,11>>^ E nos princípios dos vossos meses oferecereis, em holocausto ao Senhor, dois novilhos e um carneiro, sete cordeiros de um ano, sem defeito;

[[v4-28-12]]

^<<v4-28-12,12>>^ E três décimas de flor de farinha misturada com azeite, em oferta de alimentos, para um novilho; e duas décimas de flor de farinha misturada com azeite, em oferta de alimentos, para um carneiro.

[[v4-28-13]]

^<<v4-28-13,13>>^ E uma décima de flor de farinha misturada com azeite em oferta de alimentos, para um cordeiro; holocausto é de cheiro suave, oferta queimada ao Senhor.

[[v4-28-14]]

^<<v4-28-14,14>>^ E as suas libações serão a metade de um him de vinho para um novilho, e a terça parte de um him para um carneiro, e a quarta parte de um him para um cordeiro; este é o holocausto da lua nova de cada mês, segundo os meses do ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Também um bode para expiação do pecado ao Senhor, além do holocausto contínuo, com a sua libação se oferecerá.

[[v4-28-16]]

^<<v4-28-16,16>>^ Porém no mês primeiro, aos catorze dias do mês, é a páscoa do Senhor.

[[v4-28-17]]

^<<v4-28-17,17>>^ E aos quinze dias do mesmo mês haverá festa; sete dias se comerão pães ázimos.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia haverá santa convocação; nenhum trabalho servil fareis;

[[v4-28-19]]

^<<v4-28-19,19>>^ Mas oferecereis oferta queimada em holocausto ao Senhor, dois novilhos e um carneiro, e sete cordeiros de um ano; eles serão sem defeito.

[[v4-28-20]]

^<<v4-28-20,20>>^ E a sua oferta de alimentos será de flor de farinha misturada com azeite; oferecereis três décimas para um novilho, e duas décimas para um carneiro.

[[v4-28-21]]

^<<v4-28-21,21>>^ Para cada um dos sete cordeiros oferecereis uma décima;

[[v4-28-22]]

^<<v4-28-22,22>>^ E um bode para expiação do pecado, para fazer expiação por vós.

[[v4-28-23]]

^<<v4-28-23,23>>^ Estas coisas oferecereis, além do holocausto da manhã, que é o holocausto contínuo.

[[v4-28-24]]

^<<v4-28-24,24>>^ Segundo este modo, cada dia oferecereis, por sete dias, o alimento da oferta queimada em cheiro suave ao Senhor; além do holocausto contínuo se oferecerá isto com a sua libação.

[[v4-28-25]]

^<<v4-28-25,25>>^ E no sétimo dia tereis santa convocação; nenhum trabalho servil fareis.

[[v4-28-26]]

^<<v4-28-26,26>>^ Semelhantemente, tereis santa convocação no dia das primícias, quando oferecerdes oferta nova de alimentos ao Senhor, segundo as vossas semanas; nenhum trabalho servil fareis.

[[v4-28-27]]

^<<v4-28-27,27>>^ Então oferecereis ao Senhor por holocausto, em cheiro suave, dois novilhos, um carneiro e sete cordeiros de um ano;

[[v4-28-28]]

^<<v4-28-28,28>>^ E a sua oferta de alimentos de flor de farinha misturada com azeite: três décimas para um novilho, duas décimas para um carneiro;

[[v4-28-29]]

^<<v4-28-29,29>>^ E uma décima, para cada um dos sete cordeiros;

[[v4-28-30]]

^<<v4-28-30,30>>^ Um bode para fazer expiação por vós.

[[v4-28-31]]

^<<v4-28-31,31>>^ Além do holocausto contínuo, e a sua oferta de alimentos, os oferecereis (ser-vos-ão eles sem defeito) com as suas libações.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]