include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// acf ?, ACF - Almeida Corrigida Fiel

[[v4-32-1]]

^<<v4-32-1,1>>^ E os filhos de Rúben e os filhos de Gade tinham gado em grande quantidade; e viram a terra de Jazer, e a terra de Gileade, e eis que o lugar era lugar de gado.

[[v4-32-2]]

^<<v4-32-2,2>>^ Vieram, pois, os filhos de Gade, e os filhos de Rúben e falaram a Moisés e a Eleazar, o sacerdote, e aos chefes da congregação, dizendo:

[[v4-32-3]]

^<<v4-32-3,3>>^ Atarote, e Dibom, e Jazer, e Ninra, e Hesbom, e Eleale, e Sebã, e Nebo, e Beom,

[[v4-32-4]]

^<<v4-32-4,4>>^ A terra que o Senhor feriu diante da congregação de Israel, é terra para gado, e os teus servos têm gado.

[[v4-32-5]]

^<<v4-32-5,5>>^ Disseram mais: Se achamos graça aos teus olhos, dê-se esta terra aos teus servos em possessão; e não nos faças passar o Jordão.

[[v4-32-6]]

^<<v4-32-6,6>>^ Porém Moisés disse aos filhos de Gade e aos filhos de Rúben: Irão vossos irmãos à peleja, e ficareis vós aqui?

[[v4-32-7]]

^<<v4-32-7,7>>^ Por que, pois, desencorajais o coração dos filhos de Israel, para que não passem à terra que o Senhor lhes tem dado?

[[v4-32-8]]

^<<v4-32-8,8>>^ Assim fizeram vossos pais, quando os mandei de Cades-Barnéia, a ver esta terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Chegando eles até ao vale de Escol, e vendo esta terra, desencorajaram o coração dos filhos de Israel, para que não entrassem na terra que o Senhor lhes tinha dado.

[[v4-32-10]]

^<<v4-32-10,10>>^ Então a ira do Senhor se acendeu naquele mesmo dia, e jurou dizendo:

[[v4-32-11]]

^<<v4-32-11,11>>^ Que os homens, que subiram do Egito, de vinte anos para cima, não verão a terra que jurei a Abraão, a Isaque, e a Jacó! porquanto não perseveraram em seguir-me;

[[v4-32-12]]

^<<v4-32-12,12>>^ Exceto Calebe, filho de Jefoné o quenezeu, e Josué, filho de Num, porquanto perseveraram em seguir ao Senhor.

[[v4-32-13]]

^<<v4-32-13,13>>^ Assim se acendeu a ira do Senhor contra Israel, e fê-los andar errantes pelo deserto quarenta anos até que se consumiu toda aquela geração, que fizera mal aos olhos do Senhor.

[[v4-32-14]]

^<<v4-32-14,14>>^ E eis que vós, uma geração de homens pecadores, vos levantastes em lugar de vossos pais, para ainda mais acrescentar o furor da ira do Senhor contra Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ Se vós vos virardes de segui-lo, também ele os deixará de novo no deserto, e destruireis a todo este povo.

[[v4-32-16]]

^<<v4-32-16,16>>^ Então chegaram-se a ele, e disseram: Edificaremos currais aqui para o nosso gado, e cidades para as nossas crianças;

[[v4-32-17]]

^<<v4-32-17,17>>^ Porém nós nos armaremos, apressando-nos adiante dos de Israel, até que os levemos ao seu lugar; e ficarão as nossas crianças nas cidades fortes por causa dos moradores da terra.

[[v4-32-18]]

^<<v4-32-18,18>>^ Não voltaremos para nossas casas, até que os filhos de Israel estejam de posse, cada um, da sua herança.

[[v4-32-19]]

^<<v4-32-19,19>>^ Porque não herdaremos com eles além do Jordão, nem mais adiante; porquanto nós já temos a nossa herança aquém do Jordão, ao oriente.

[[v4-32-20]]

^<<v4-32-20,20>>^ Então Moisés lhes disse: Se isto fizerdes assim, se vos armardes à guerra perante o Senhor;

[[v4-32-21]]

^<<v4-32-21,21>>^ E cada um de vós, armado, passar o Jordão perante o Senhor, até que haja lançado fora os seus inimigos de diante dele,

[[v4-32-22]]

^<<v4-32-22,22>>^ E a terra esteja subjugada perante o Senhor; então voltareis e sereis inculpáveis perante o Senhor e perante Israel; e esta terra vos será por possessão perante o Senhor;

[[v4-32-23]]

^<<v4-32-23,23>>^ E se não fizerdes assim, eis que pecastes contra o Senhor; e sabei que o vosso pecado vos há de achar.

[[v4-32-24]]

^<<v4-32-24,24>>^ Edificai cidades para as vossas crianças, e currais para as vossas ovelhas; e fazei o que saiu da vossa boca.

[[v4-32-25]]

^<<v4-32-25,25>>^ Então falaram os filhos de Gade, e os filhos de Rúben a Moisés, dizendo: Como ordena meu senhor, assim farão teus servos.

[[v4-32-26]]

^<<v4-32-26,26>>^ As nossas crianças, as nossas mulheres, o nosso gado, e todos os nossos animais estarão aí nas cidades de Gileade.

[[v4-32-27]]

^<<v4-32-27,27>>^ Mas os teus servos passarão, cada um armado para a guerra, a pelejar perante o SENHOR, como tem falado o meu senhor.

[[v4-32-28]]

^<<v4-32-28,28>>^ Então Moisés deu ordem acerca deles a Eleazar, o sacerdote, e a Josué filho de Num, e aos cabeças das casas dos pais das tribos dos filhos de Israel.

[[v4-32-29]]

^<<v4-32-29,29>>^ E disse-lhes Moisés: Se os filhos de Gade e os filhos de Rúben passarem convosco o Jordão, armado cada um para a guerra, perante o Senhor, e a terra estiver subjugada diante de vós, em possessão lhes dareis a terra de Gileade.

[[v4-32-30]]

^<<v4-32-30,30>>^ Porém, se não passarem armados convosco, terão possessões entre vós, na terra de Canaã.

[[v4-32-31]]

^<<v4-32-31,31>>^ E responderam os filhos de Gade e os filhos de Rúben, dizendo: O que o Senhor falou a teus servos, isso faremos.

[[v4-32-32]]

^<<v4-32-32,32>>^ Nós passaremos, armados, perante o Senhor, à terra de Canaã, e teremos a possessão de nossa herança aquém do Jordão.

[[v4-32-33]]

^<<v4-32-33,33>>^ Assim deu-lhes Moisés, aos filhos de Gade, e aos filhos de Rúben, e à meia tribo de Manassés, filho de José, o reino de Siom, rei dos amorreus, e o reino de Ogue, rei de Basã; a terra com as suas cidades nos seus termos, e as cidades ao seu redor.

[[v4-32-34]]

^<<v4-32-34,34>>^ E os filhos de Gade edificaram a Dibom, e Atarote, e Aroer;

[[v4-32-35]]

^<<v4-32-35,35>>^ E Atarote-Sofã, e Jazer, e Jogbeá;

[[v4-32-36]]

^<<v4-32-36,36>>^ E Bete-Nimra, e Bete-Harã, cidades fortes; e currais de ovelhas.

[[v4-32-37]]

^<<v4-32-37,37>>^ E os filhos de Rúben edificaram a Hesbom, e Eleale, e Quiriataim;

[[v4-32-38]]

^<<v4-32-38,38>>^ E Nebo, e Baal-Meom, mudando-lhes o nome, e Sibma; e os nomes das cidades que edificaram chamaram por outros nomes.

[[v4-32-39]]

^<<v4-32-39,39>>^ E os filhos de Maquir, filho de Manassés, foram-se para Gileade, e a tomaram; e daquela possessão expulsaram os amorreus que estavam nela.

[[v4-32-40]]

^<<v4-32-40,40>>^ Assim Moisés deu Gileade a Maquir, filho de Manassés, o qual habitou nela.

[[v4-32-41]]

^<<v4-32-41,41>>^ E foi Jair, filho de Manassés, e tomou as suas aldeias; e chamou-as Havote-Jair.

[[v4-32-42]]

^<<v4-32-42,42>>^ E foi Nobá, e tomou a Quenate com as suas aldeias; e chamou-a Nobá, segundo o seu próprio nome.

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]