include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v11-10-1]]

^<<v11-10-1,1>>^ E ouvindo a rainha de Sabá a fama de Salomão, acerca do nome do SENHOR, veio prová-lo com questões difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ E chegou a Jerusalém com uma grande comitiva; com camelos carregados de especiarias, e muitíssimo ouro, e pedras preciosas; e foi a Salomão, e disse-lhe tudo quanto tinha no seu coração.

[[v11-10-3]]

^<<v11-10-3,3>>^ E Salomão lhe deu resposta a todas as suas perguntas, nada houve que não lhe pudesse esclarecer.

[[v11-10-4]]

^<<v11-10-4,4>>^ Vendo, pois, a rainha de Sabá toda a sabedoria de Salomão, e a casa que edificara,

[[v11-10-5]]

^<<v11-10-5,5>>^ E a comida da sua mesa, e o assentar de seus servos, e o estar de seus criados, e as vestes deles, e os seus copeiros, e os holocaustos que ele oferecia na casa do Senhor, ficou fora de si.

[[v11-10-6]]

^<<v11-10-6,6>>^ E disse ao rei: Era verdade a palavra que ouvi na minha terra, dos teus feitos e da tua sabedoria.

[[v11-10-7]]

^<<v11-10-7,7>>^ E eu não cria naquelas palavras, até que vim e os meus olhos o viram; eis que não me disseram metade; sobrepujaste em sabedoria e bens a fama que ouvi.

[[v11-10-8]]

^<<v11-10-8,8>>^ Bem-aventurados os teus homens, bem-aventurados estes teus servos, que estão sempre diante de ti, que ouvem a tua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor teu Deus, que teve agrado em ti, para te pôr no trono de Israel; porque o Senhor ama a Israel para sempre, por isso te estabeleceu rei, para fazeres juízo e justiça.

[[v11-10-10]]

^<<v11-10-10,10>>^ E deu ao rei cento e vinte talentos de ouro, e muitíssimas especiarias, e pedras preciosas; nunca veio especiaria em tanta abundância, como a que a rainha de Sabá deu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ Também as naus de Hirão, que de Ofir levavam ouro, traziam de Ofir muita madeira de almugue, e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ E desta madeira de almugue fez o rei balaústres para a casa do Senhor, e para a casa do rei, como também harpas e alaúdes para os cantores; nunca veio tal madeira de almugue, nem se viu até o dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ E o rei Salomão deu à rainha de Sabá tudo o que ela desejou, tudo quanto pediu, além do que dera por sua generosidade; então voltou e partiu para a sua terra, ela e os seus servos.

[[v11-10-14]]

^<<v11-10-14,14>>^ E o peso do ouro que se trazia a Salomão cada ano era de seiscentos e sessenta e seis talentos de ouro;

[[v11-10-15]]

^<<v11-10-15,15>>^ Além do que entrava dos negociantes, e do contrato dos especieiros, e de todos os reis da Arábia, e dos governadores da mesma terra.

[[v11-10-16]]

^<<v11-10-16,16>>^ Também o rei Salomão fez duzentos paveses de ouro batido; seiscentos siclos de ouro destinou para cada pavês;

[[v11-10-17]]

^<<v11-10-17,17>>^ Fez também trezentos escudos de ouro batido; três arráteis de ouro destinou para cada escudo; e o rei os pôs na casa do bosque do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ Fez mais o rei um grande trono de marfim, e o revestiu de ouro puríssimo.

[[v11-10-19]]

^<<v11-10-19,19>>^ Tinha este trono seis degraus, e era o alto do trono por detrás redondo, e de ambos os lados tinha encostos até ao assento; e dois leões, em pé, juntos aos encostos.

[[v11-10-20]]

^<<v11-10-20,20>>^ Também doze leões estavam ali sobre os seis degraus de ambos os lados; nunca se tinha feito obra semelhante em nenhum dos reinos.

[[v11-10-21]]

^<<v11-10-21,21>>^ Também todas as taças de beber do rei Salomão eram de ouro, e todos os vasos da casa do bosque do Líbano eram de ouro puro; não havia neles prata, porque nos dias de Salomão não tinha valor algum.

[[v11-10-22]]

^<<v11-10-22,22>>^ Porque o rei tinha no mar as naus de Társis, com as naus de Hirão; uma vez em três anos tornavam as naus de Társis, e traziam ouro e prata, marfim, e bugios, e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ Assim o rei Salomão excedeu a todos os reis da terra, tanto em riquezas como em sabedoria.

[[v11-10-24]]

^<<v11-10-24,24>>^ E toda a terra buscava a face de Salomão, para ouvir a sabedoria que Deus tinha posto no seu coração.

[[v11-10-25]]

^<<v11-10-25,25>>^ E cada um trazia o seu presente, vasos de prata e vasos de ouro, e roupas, e armaduras, e especiarias, cavalos e mulas; isso faziam de ano em ano.

[[v11-10-26]]

^<<v11-10-26,26>>^ Também ajuntou Salomão carros e cavaleiros, de sorte que tinha mil e quatrocentos carros e doze mil cavaleiros; e os levou às cidades dos carros, e junto ao rei em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ E fez o rei que em Jerusalém houvesse prata como pedras; e cedros em abundância como sicômoros que estão nas planícies.

[[v11-10-28]]

^<<v11-10-28,28>>^ E traziam do Egito, para Salomão, cavalos e fio de linho; e os mercadores do rei recebiam o fio de linho, por um certo preço.

[[v11-10-29]]

^<<v11-10-29,29>>^ E subia e saía um carro do Egito por seiscentos siclos de prata, e um cavalo por cento e cinqüenta; e assim, por meio deles, eram exportados para todos os reis dos heteus e para os reis da Síria.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]