include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// acf ?, ACF - Almeida Corrigida Fiel

[[v11-13-1]]

^<<v11-13-1,1>>^ E eis que, por ordem do SENHOR, veio, de Judá a Betel, um homem de Deus; e Jeroboão estava junto ao altar, para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ E ele clamou contra o altar por ordem do Senhor, e disse: Altar, altar! Assim diz o Senhor: Eis que um filho nascerá à casa de Davi, cujo nome será Josias, o qual sacrificará sobre ti os sacerdotes dos altos que sobre ti queimam incenso, e ossos de homens se queimarão sobre ti.

[[v11-13-3]]

^<<v11-13-3,3>>^ E deu, naquele mesmo dia, um sinal, dizendo: Este é o sinal de que o Senhor falou: Eis que o altar se fenderá, e a cinza, que nele está, se derramará.

[[v11-13-4]]

^<<v11-13-4,4>>^ Sucedeu, pois, que, ouvindo o rei a palavra do homem de Deus, que clamara contra o altar de Betel, Jeroboão estendeu a sua mão de sobre o altar, dizendo: Pegai-o! Mas a sua mão, que estendera contra ele, se secou, e não podia tornar a trazê-la a si.

[[v11-13-5]]

^<<v11-13-5,5>>^ E o altar se fendeu, e a cinza se derramou do altar, segundo o sinal que o homem de Deus apontara por ordem do Senhor.

[[v11-13-6]]

^<<v11-13-6,6>>^ Então respondeu o rei, e disse ao homem de Deus: Suplica ao Senhor teu Deus, e roga por mim, para que se me restitua a minha mão. Então o homem de Deus suplicou ao Senhor, e a mão do rei se lhe restituiu, e ficou como dantes.

[[v11-13-7]]

^<<v11-13-7,7>>^ E o rei disse ao homem de Deus: Vem comigo para casa, e conforta-te; e dar-te-ei um presente.

[[v11-13-8]]

^<<v11-13-8,8>>^ Porém o homem de Deus disse ao rei: Ainda que me desses metade da tua casa, não iria contigo, nem comeria pão nem beberia água neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Porque assim me ordenou o Senhor pela sua palavra, dizendo: Não comerás pão nem beberás água; e não voltarás pelo caminho por onde vieste.

[[v11-13-10]]

^<<v11-13-10,10>>^ Assim foi por outro caminho; e não voltou pelo caminho, por onde viera a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ E morava em Betel um velho profeta; e vieram seus filhos, e contaram-lhe tudo o que o homem de Deus fizera aquele dia em Betel, e as palavras que dissera ao rei; e as contaram a seu pai.

[[v11-13-12]]

^<<v11-13-12,12>>^ E disse-lhes seu pai: Por que caminho se foi? E seus filhos lhe mostraram o caminho por onde fora o homem de Deus que viera de Judá.

[[v11-13-13]]

^<<v11-13-13,13>>^ Então disse a seus filhos: Albardai-me um jumento. E albardaram-lhe o jumento no qual ele montou.

[[v11-13-14]]

^<<v11-13-14,14>>^ E foi após o homem de Deus, e achou-o assentado debaixo de um carvalho, e disse-lhe: És tu o homem de Deus que vieste de Judá? E ele disse: Sou.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então lhe disse: Vem comigo à casa, e come pão.

[[v11-13-16]]

^<<v11-13-16,16>>^ Porém ele disse: Não posso voltar contigo, nem entrarei contigo; nem tampouco comerei pão, nem beberei contigo água neste lugar.

[[v11-13-17]]

^<<v11-13-17,17>>^ Porque me foi mandado pela palavra do Senhor: Ali não comerás pão, nem beberás água; nem voltarás pelo caminho por onde vieste.

[[v11-13-18]]

^<<v11-13-18,18>>^ E ele lhe disse: Também eu sou profeta como tu, e um anjo me falou por ordem do Senhor, dizendo: Faze-o voltar contigo à tua casa, para que coma pão e beba água (porém mentiu-lhe).

[[v11-13-19]]

^<<v11-13-19,19>>^ Assim voltou com ele, e comeu pão em sua casa e bebeu água.

[[v11-13-20]]

^<<v11-13-20,20>>^ E sucedeu que, estando eles à mesa, a palavra do Senhor veio ao profeta que o tinha feito voltar.

[[v11-13-21]]

^<<v11-13-21,21>>^ E clamou ao homem de Deus, que viera de Judá, dizendo: Assim diz o Senhor: Porquanto foste rebelde à ordem do Senhor, e não guardaste o mandamento que o Senhor teu Deus te mandara,

[[v11-13-22]]

^<<v11-13-22,22>>^ Antes voltaste, e comeste pão e bebeste água no lugar de que o Senhor te dissera: Não comerás pão nem beberás água; o teu cadáver não entrará no sepulcro de teus pais.

[[v11-13-23]]

^<<v11-13-23,23>>^ E sucedeu que, depois que comeu pão, e depois que bebeu, albardou ele o jumento para o profeta que fizera voltar.

[[v11-13-24]]

^<<v11-13-24,24>>^ Este, pois, se foi, e um leão o encontrou no caminho, e o matou; e o seu cadáver ficou estendido no caminho, e o jumento estava parado junto a ele, e também o leão estava junto ao cadáver.

[[v11-13-25]]

^<<v11-13-25,25>>^ E eis que alguns homens passaram, e viram o corpo lançado no caminho, como também o leão, que estava junto ao corpo; e foram, e o disseram na cidade onde o velho profeta habitava.

[[v11-13-26]]

^<<v11-13-26,26>>^ E, ouvindo-o o profeta que o fizera voltar do caminho, disse: É o homem de Deus, que foi rebelde à ordem do Senhor; por isso o Senhor o entregou ao leão, que o despedaçou e matou, segundo a palavra que o Senhor lhe dissera.

[[v11-13-27]]

^<<v11-13-27,27>>^ Então disse a seus filhos: Albardai-me o jumento. Eles o albardaram.

[[v11-13-28]]

^<<v11-13-28,28>>^ Então foi, e achou o cadáver estendido no caminho, e o jumento e o leão, que estavam parados junto ao cadáver; e o leão não tinha devorado o corpo, nem tinha despedaçado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ Então o profeta levantou o cadáver do homem de Deus, e pô-lo em cima do jumento levando-o consigo; assim veio o velho profeta à cidade, para o chorar e enterrar.

[[v11-13-30]]

^<<v11-13-30,30>>^ E colocou o cadáver no seu próprio sepulcro; e prantearam-no, dizendo: Ah, irmão meu!

[[v11-13-31]]

^<<v11-13-31,31>>^ E sucedeu que, depois de o haver sepultado, disse a seus filhos: Morrendo eu, sepultai-me no sepulcro em que o homem de Deus está sepultado; ponde os meus ossos junto aos ossos dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Porque certamente se cumprirá o que pela palavra do Senhor exclamou contra o altar que está em Betel, como também contra todas as casas dos altos que estão nas cidades de Samaria.

[[v11-13-33]]

^<<v11-13-33,33>>^ Nem depois destas coisas deixou Jeroboão o seu mau caminho; antes, de todo o povo, tornou a constituir sacerdotes dos lugares altos; e a qualquer que queria consagrava sacerdote dos lugares altos.

[[v11-13-34]]

^<<v11-13-34,34>>^ E isso foi causa de pecado à casa de Jeroboão, para destruí-la e extingui-la da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]