include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-18-1]]

^<<v20-18-1,1>>^ Busca satisfazer seu próprio desejo aquele que se isola; ele se insurge contra toda sabedoria.

[[v20-18-2]]

^<<v20-18-2,2>>^ O tolo não tem prazer na sabedoria, mas só em que se manifeste aquilo que agrada o seu coração.

[[v20-18-3]]

^<<v20-18-3,3>>^ Vindo o ímpio, vem também o desprezo, e com a ignomínia a vergonha.

[[v20-18-4]]

^<<v20-18-4,4>>^ Águas profundas são as palavras da boca do homem, e ribeiro transbordante é a fonte da sabedoria.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é bom favorecer o ímpio, e com isso, fazer o justo perder a questão.

[[v20-18-6]]

^<<v20-18-6,6>>^ Os lábios do tolo entram na contenda, e a sua boca brada por açoites.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do tolo é a sua própria destruição, e os seus lábios um laço para a sua alma.

[[v20-18-8]]

^<<v20-18-8,8>>^ As palavras do mexeriqueiro são como doces bocados; elas descem ao íntimo do ventre.

[[v20-18-9]]

^<<v20-18-9,9>>^ O que é negligente na sua obra é também irmão do desperdiçador.

[[v20-18-10]]

^<<v20-18-10,10>>^ Torre forte é o nome do Senhor; a ela correrá o justo, e estará em alto refúgio.

[[v20-18-11]]

^<<v20-18-11,11>>^ Os bens do rico são a sua cidade forte, e como uma muralha na sua imaginação.

[[v20-18-12]]

^<<v20-18-12,12>>^ O coração do homem se exalta antes de ser abatido e diante da honra vai a humildade.

[[v20-18-13]]

^<<v20-18-13,13>>^ O que responde antes de ouvir comete estultícia que é para vergonha sua.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito do homem susterá a sua enfermidade, mas ao espírito abatido, quem o suportará?

[[v20-18-15]]

^<<v20-18-15,15>>^ O coração do entendido adquire o conhecimento, e o ouvido dos sábios busca a sabedoria.

[[v20-18-16]]

^<<v20-18-16,16>>^ Com presentes o homem alarga o seu caminho e o eleva diante dos grandes.

[[v20-18-17]]

^<<v20-18-17,17>>^ O que pleiteia por algo, a princípio parece justo, porém vem o seu próximo e o examina.

[[v20-18-18]]

^<<v20-18-18,18>>^ A sorte faz cessar os pleitos, e faz separação entre os poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ O irmão ofendido é mais difícil de conquistar do que uma cidade forte; e as contendas são como os ferrolhos de um palácio.

[[v20-18-20]]

^<<v20-18-20,20>>^ Do fruto da boca de cada um se fartará o seu ventre; dos renovos dos seus lábios ficará satisfeito.

[[v20-18-21]]

^<<v20-18-21,21>>^ A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.

[[v20-18-22]]

^<<v20-18-22,22>>^ Aquele que encontra uma esposa, acha o bem, e alcança a benevolência do Senhor.

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre fala com rogos, mas o rico responde com dureza.

[[v20-18-24]]

^<<v20-18-24,24>>^ O homem de muitos amigos deve mostrar-se amigável, mas há um amigo mais chegado do que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]