include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-3-1]]

^<<v20-3-1,1>>^ Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos.

[[v20-3-2]]

^<<v20-3-2,2>>^ Porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.

[[v20-3-3]]

^<<v20-3-3,3>>^ Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração.

[[v20-3-4]]

^<<v20-3-4,4>>^ E acharás graça e bom entendimento aos olhos de Deus e do homem.

[[v20-3-5]]

^<<v20-3-5,5>>^ Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.

[[v20-3-6]]

^<<v20-3-6,6>>^ Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não sejas sábio a teus próprios olhos; teme ao Senhor e aparta-te do mal.

[[v20-3-8]]

^<<v20-3-8,8>>^ Isto será saúde para o teu âmago, e medula para os teus ossos.

[[v20-3-9]]

^<<v20-3-9,9>>^ Honra ao Senhor com os teus bens, e com a primeira parte de todos os teus ganhos;

[[v20-3-10]]

^<<v20-3-10,10>>^ E se encherão os teus celeiros, e transbordarão de vinho os teus lagares.

[[v20-3-11]]

^<<v20-3-11,11>>^ Filho meu, não rejeites a correção do Senhor, nem te enojes da sua repreensão.

[[v20-3-12]]

^<<v20-3-12,12>>^ Porque o Senhor repreende aquele a quem ama, assim como o pai ao filho a quem quer bem.

[[v20-3-13]]

^<<v20-3-13,13>>^ Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento;

[[v20-3-14]]

^<<v20-3-14,14>>^ Porque é melhor a sua mercadoria do que artigos de prata, e maior o seu lucro que o ouro mais fino.

[[v20-3-15]]

^<<v20-3-15,15>>^ Mais preciosa é do que os rubis, e tudo o que mais possas desejar não se pode comparar a ela.

[[v20-3-16]]

^<<v20-3-16,16>>^ Vida longa de dias está na sua mão direita; e na esquerda, riquezas e honra.

[[v20-3-17]]

^<<v20-3-17,17>>^ Os seus caminhos são caminhos de delícias, e todas as suas veredas de paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ É árvore de vida para os que dela tomam, e são bem-aventurados todos os que a retêm.

[[v20-3-19]]

^<<v20-3-19,19>>^ O Senhor, com sabedoria fundou a terra; com entendimento preparou os céus.

[[v20-3-20]]

^<<v20-3-20,20>>^ Pelo seu conhecimento se fenderam os abismos, e as nuvens destilam o orvalho.

[[v20-3-21]]

^<<v20-3-21,21>>^ Filho meu, não se apartem estas coisas dos teus olhos: guarda a verdadeira sabedoria e o bom siso;

[[v20-3-22]]

^<<v20-3-22,22>>^ Porque serão vida para a tua alma, e adorno ao teu pescoço.

[[v20-3-23]]

^<<v20-3-23,23>>^ Então andarás confiante pelo teu caminho, e o teu pé não tropeçará.

[[v20-3-24]]

^<<v20-3-24,24>>^ Quando te deitares, não temerás; ao contrário, o teu sono será suave ao te deitares.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não temas o pavor repentino, nem a investida dos perversos quando vier.

[[v20-3-26]]

^<<v20-3-26,26>>^ Porque o Senhor será a tua esperança; guardará os teus pés de serem capturados.

[[v20-3-27]]

^<<v20-3-27,27>>^ Não deixes de fazer bem a quem o merece, estando em tuas mãos a capacidade de fazê-lo.

[[v20-3-28]]

^<<v20-3-28,28>>^ Não digas ao teu próximo: Vai, e volta amanhã que to darei, se já o tens contigo.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não maquines o mal contra o teu próximo, pois que habita contigo confiadamente.

[[v20-3-30]]

^<<v20-3-30,30>>^ Não contendas com alguém sem causa, se não te fez nenhum mal.

[[v20-3-31]]

^<<v20-3-31,31>>^ Não tenhas inveja do homem violento, nem escolhas nenhum dos seus caminhos.

[[v20-3-32]]

^<<v20-3-32,32>>^ Porque o perverso é abominável ao Senhor, mas com os sinceros ele tem intimidade.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição do Senhor habita na casa do ímpio, mas a habitação dos justos abençoará.

[[v20-3-34]]

^<<v20-3-34,34>>^ Certamente ele escarnecerá dos escarnecedores, mas dará graça aos mansos.

[[v20-3-35]]

^<<v20-3-35,35>>^ Os sábios herdarão honra, mas os loucos tomam sobre si vergonha.

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]