include::./index.adoc[]

[[v20-15-0]]
=== Provérbios, 15
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-15-1]]

^<<v20-15-1,1>>^ A resposta branda desvia o furor, mas a palavra dura suscita a ira.

[[v20-15-2]]

^<<v20-15-2,2>>^ A língua dos sábios adorna a sabedoria, mas a boca dos tolos derrama a estultícia.

[[v20-15-3]]

^<<v20-15-3,3>>^ Os olhos do Senhor estão em todo lugar, contemplando os maus e os bons.

[[v20-15-4]]

^<<v20-15-4,4>>^ A língua benigna é árvore de vida, mas a perversidade nela deprime o espírito.

[[v20-15-5]]

^<<v20-15-5,5>>^ O tolo despreza a instrução de seu pai, mas o que observa a repreensão se haverá prudentemente.

[[v20-15-6]]

^<<v20-15-6,6>>^ Na casa do justo há um grande tesouro, mas nos ganhos do ímpio há perturbação.

[[v20-15-7]]

^<<v20-15-7,7>>^ Os lábios dos sábios derramam o conhecimento, mas o coração dos tolos não faz assim.

[[v20-15-8]]

^<<v20-15-8,8>>^ O sacrifício dos ímpios é abominável ao Senhor, mas a oração dos retos é o seu contentamento.

[[v20-15-9]]

^<<v20-15-9,9>>^ O caminho do ímpio é abominável ao Senhor, mas ao que segue a justiça ele ama.

[[v20-15-10]]

^<<v20-15-10,10>>^ Correção severa há para o que deixa a vereda, e o que odeia a repreensão morrerá.

[[v20-15-11]]

^<<v20-15-11,11>>^ O inferno e a perdição estão perante o Senhor; quanto mais os corações dos filhos dos homens?

[[v20-15-12]]

^<<v20-15-12,12>>^ O escarnecedor não ama aquele que o repreende, nem se chegará aos sábios.

[[v20-15-13]]

^<<v20-15-13,13>>^ O coração alegre aformoseia o rosto, mas pela dor do coração o espírito se abate.

[[v20-15-14]]

^<<v20-15-14,14>>^ O coração entendido buscará o conhecimento, mas a boca dos tolos se apascentará de estultícia.

[[v20-15-15]]

^<<v20-15-15,15>>^ Todos os dias do oprimido são maus, mas o coração alegre é um banquete contínuo.

[[v20-15-16]]

^<<v20-15-16,16>>^ Melhor é o pouco com o temor do Senhor, do que um grande tesouro onde há inquietação.

[[v20-15-17]]

^<<v20-15-17,17>>^ Melhor é a comida de hortaliça, onde há amor, do que o boi cevado, e com ele o ódio.

[[v20-15-18]]

^<<v20-15-18,18>>^ O homem iracundo suscita contendas, mas o longânimo apaziguará a luta.

[[v20-15-19]]

^<<v20-15-19,19>>^ O caminho do preguiçoso é cercado de espinhos, mas a vereda dos retos é bem aplanada.

[[v20-15-20]]

^<<v20-15-20,20>>^ O filho sábio alegra seu pai, mas o homem insensato despreza a sua mãe.

[[v20-15-21]]

^<<v20-15-21,21>>^ A estultícia é alegria para o que carece de entendimento, mas o homem entendido anda retamente.

[[v20-15-22]]

^<<v20-15-22,22>>^ Quando não há conselhos os planos se dispersam, mas havendo muitos conselheiros eles se firmam.

[[v20-15-23]]

^<<v20-15-23,23>>^ O homem se alegra em responder bem, e quão boa é a palavra dita a seu tempo!

[[v20-15-24]]

^<<v20-15-24,24>>^ Para o entendido, o caminho da vida leva para cima, para que se desvie do inferno em baixo.

[[v20-15-25]]

^<<v20-15-25,25>>^ O Senhor desarraiga a casa dos soberbos, mas estabelece o termo da viúva.

[[v20-15-26]]

^<<v20-15-26,26>>^ Abomináveis são para o Senhor os pensamentos do mau, mas as palavras dos puros são aprazíveis.

[[v20-15-27]]

^<<v20-15-27,27>>^ O que agir com avareza perturba a sua casa, mas o que odeia presentes viverá.

[[v20-15-28]]

^<<v20-15-28,28>>^ O coração do justo medita no que há de responder, mas a boca dos ímpios jorra coisas más.

[[v20-15-29]]

^<<v20-15-29,29>>^ O Senhor está longe dos ímpios, mas a oração dos justos escutará.

[[v20-15-30]]

^<<v20-15-30,30>>^ A luz dos olhos alegra o coração, a boa notícia fortalece os ossos.

[[v20-15-31]]

^<<v20-15-31,31>>^ Os ouvidos que atendem à repreensão da vida farão a sua morada no meio dos sábios.

[[v20-15-32]]

^<<v20-15-32,32>>^ O que rejeita a instrução menospreza a própria alma, mas o que escuta a repreensão adquire entendimento.

[[v20-15-33]]

^<<v20-15-33,33>>^ O temor do Senhor é a instrução da sabedoria, e precedendo a honra vai a humildade.

'''

xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[&#60; Capítulo Anterior] | <<v20-15-0,Topo>> | xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[Próximo Capítulo &#62;]