include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-21-1]]

^<<v20-21-1,1>>^ Como ribeiros de águas assim é o coração do rei na mão do SENHOR, que o inclina a todo o seu querer.

[[v20-21-2]]

^<<v20-21-2,2>>^ Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.

[[v20-21-3]]

^<<v20-21-3,3>>^ Fazer justiça e juízo é mais aceitável ao Senhor do que sacrifício.

[[v20-21-4]]

^<<v20-21-4,4>>^ Os olhos altivos, o coração orgulhoso e a lavoura dos ímpios é pecado.

[[v20-21-5]]

^<<v20-21-5,5>>^ Os pensamentos do diligente tendem só para a abundância, porém os de todo apressado, tão-somente para a pobreza.

[[v20-21-6]]

^<<v20-21-6,6>>^ Trabalhar com língua falsa para ajuntar tesouros é vaidade que conduz aqueles que buscam a morte.

[[v20-21-7]]

^<<v20-21-7,7>>^ As rapinas dos ímpios os destruirão, porquanto se recusam a fazer justiça.

[[v20-21-8]]

^<<v20-21-8,8>>^ O caminho do homem é todo perverso e estranho, porém a obra do homem puro é reta.

[[v20-21-9]]

^<<v20-21-9,9>>^ É melhor morar num canto de telhado do que ter como companheira em casa ampla uma mulher briguenta.

[[v20-21-10]]

^<<v20-21-10,10>>^ A alma do ímpio deseja o mal; o seu próximo não agrada aos seus olhos.

[[v20-21-11]]

^<<v20-21-11,11>>^ Quando o escarnecedor é castigado, o simples torna-se sábio; e o sábio quando é instruído recebe o conhecimento.

[[v20-21-12]]

^<<v20-21-12,12>>^ O justo considera com prudência a casa do ímpio; mas Deus destrói os ímpios por causa dos seus males.

[[v20-21-13]]

^<<v20-21-13,13>>^ O que tapa o seu ouvido ao clamor do pobre, ele mesmo também clamará e não será ouvido.

[[v20-21-14]]

^<<v20-21-14,14>>^ O presente dado em segredo aplaca a ira, e a dádiva no regaço põe fim à maior indignação.

[[v20-21-15]]

^<<v20-21-15,15>>^ O fazer justiça é alegria para o justo, mas destruição para os que praticam a iniqüidade.

[[v20-21-16]]

^<<v20-21-16,16>>^ O homem que anda desviado do caminho do entendimento, na congregação dos mortos repousará.

[[v20-21-17]]

^<<v20-21-17,17>>^ O que ama os prazeres padecerá necessidade; o que ama o vinho e o azeite nunca enriquecerá.

[[v20-21-18]]

^<<v20-21-18,18>>^ O resgate do justo é o ímpio; o do honrado é o perverso.

[[v20-21-19]]

^<<v20-21-19,19>>^ É melhor morar numa terra deserta do que com a mulher rixosa e irritadiça.

[[v20-21-20]]

^<<v20-21-20,20>>^ Tesouro desejável e azeite há na casa do sábio, mas o homem insensato os esgota.

[[v20-21-21]]

^<<v20-21-21,21>>^ O que segue a justiça e a beneficência achará a vida, a justiça e a honra.

[[v20-21-22]]

^<<v20-21-22,22>>^ O sábio escala a cidade do poderoso e derruba a força da sua confiança.

[[v20-21-23]]

^<<v20-21-23,23>>^ O que guarda a sua boca e a sua língua guarda a sua alma das angústias.

[[v20-21-24]]

^<<v20-21-24,24>>^ O soberbo e presumido, zombador é o seu nome, trata com indignação e soberba.

[[v20-21-25]]

^<<v20-21-25,25>>^ O desejo do preguiçoso o mata, porque as suas mãos recusam trabalhar.

[[v20-21-26]]

^<<v20-21-26,26>>^ O cobiçoso cobiça o dia todo, mas o justo dá, e nada retém.

[[v20-21-27]]

^<<v20-21-27,27>>^ O sacrifício dos ímpios já é abominação; quanto mais oferecendo-o com má intenção!

[[v20-21-28]]

^<<v20-21-28,28>>^ A falsa testemunha perecerá, porém o homem que dá ouvidos falará sempre.

[[v20-21-29]]

^<<v20-21-29,29>>^ O homem ímpio endurece o seu rosto; mas o reto considera o seu caminho.

[[v20-21-30]]

^<<v20-21-30,30>>^ Não há sabedoria, nem inteligência, nem conselho contra o Senhor.

[[v20-21-31]]

^<<v20-21-31,31>>^ Prepara-se o cavalo para o dia da batalha, porém do Senhor vem a vitória.

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]