include::./index.adoc[]

[[v20-10-0]]
=== Provérbios, 10
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-10-1]]

^<<v20-10-1,1>>^ Provérbios de Salomão: O filho sábio alegra a seu pai, mas o filho insensato é a tristeza de sua mãe.

[[v20-10-2]]

^<<v20-10-2,2>>^ Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.

[[v20-10-3]]

^<<v20-10-3,3>>^ O Senhor não deixa o justo passar fome, mas rechaça a aspiração dos perversos.

[[v20-10-4]]

^<<v20-10-4,4>>^ O que trabalha com mão displicente empobrece, mas a mão dos diligentes enriquece.

[[v20-10-5]]

^<<v20-10-5,5>>^ O que ajunta no verão é filho ajuizado, mas o que dorme na sega é filho que envergonha.

[[v20-10-6]]

^<<v20-10-6,6>>^ Bênçãos há sobre a cabeça do justo, mas a violência cobre a boca dos perversos.

[[v20-10-7]]

^<<v20-10-7,7>>^ A memória do justo é abençoada, mas o nome dos perversos apodrecerá.

[[v20-10-8]]

^<<v20-10-8,8>>^ O sábio de coração aceita os mandamentos, mas o insensato de lábios ficará transtornado.

[[v20-10-9]]

^<<v20-10-9,9>>^ Quem anda em sinceridade, anda seguro; mas o que perverte os seus caminhos ficará conhecido.

[[v20-10-10]]

^<<v20-10-10,10>>^ O que acena com os olhos causa dores, e o tolo de lábios ficará transtornado.

[[v20-10-11]]

^<<v20-10-11,11>>^ A boca do justo é fonte de vida, mas a violência cobre a boca dos perversos.

[[v20-10-12]]

^<<v20-10-12,12>>^ O ódio excita contendas, mas o amor cobre todos os pecados.

[[v20-10-13]]

^<<v20-10-13,13>>^ Nos lábios do entendido se acha a sabedoria, mas a vara é para as costas do falto de entendimento.

[[v20-10-14]]

^<<v20-10-14,14>>^ Os sábios entesouram a sabedoria; mas a boca do tolo o aproxima da ruína.

[[v20-10-15]]

^<<v20-10-15,15>>^ Os bens do rico são a sua cidade forte, a pobreza dos pobres a sua ruína.

[[v20-10-16]]

^<<v20-10-16,16>>^ A obra do justo conduz à vida, o fruto do perverso, ao pecado.

[[v20-10-17]]

^<<v20-10-17,17>>^ O caminho para a vida é daquele que guarda a instrução, mas o que deixa a repreensão comete erro.

[[v20-10-18]]

^<<v20-10-18,18>>^ O que encobre o ódio tem lábios falsos, e o que divulga má fama é um insensato.

[[v20-10-19]]

^<<v20-10-19,19>>^ Na multidão de palavras não falta pecado, mas o que modera os seus lábios é sábio.

[[v20-10-20]]

^<<v20-10-20,20>>^ Prata escolhida é a língua do justo; o coração dos perversos é de nenhum valor.

[[v20-10-21]]

^<<v20-10-21,21>>^ Os lábios do justo apascentam a muitos, mas os tolos morrem por falta de entendimento.

[[v20-10-22]]

^<<v20-10-22,22>>^ A bênção do Senhor é que enriquece; e não traz consigo dores.

[[v20-10-23]]

^<<v20-10-23,23>>^ Para o tolo, o cometer desordem é divertimento; mas para o homem entendido é o ter sabedoria.

[[v20-10-24]]

^<<v20-10-24,24>>^ Aquilo que o perverso teme sobrevirá a ele, mas o desejo dos justos será concedido.

[[v20-10-25]]

^<<v20-10-25,25>>^ Como passa a tempestade, assim desaparece o perverso, mas o justo tem fundamento perpétuo.

[[v20-10-26]]

^<<v20-10-26,26>>^ Como vinagre para os dentes, como fumaça para os olhos, assim é o preguiçoso para aqueles que o mandam.

[[v20-10-27]]

^<<v20-10-27,27>>^ O temor do Senhor aumenta os dias, mas os perversos terão os anos da vida abreviados.

[[v20-10-28]]

^<<v20-10-28,28>>^ A esperança dos justos é alegria, mas a expectação dos perversos perecerá.

[[v20-10-29]]

^<<v20-10-29,29>>^ O caminho do Senhor é fortaleza para os retos, mas ruína para os que praticam a iniqüidade.

[[v20-10-30]]

^<<v20-10-30,30>>^ O justo nunca jamais será abalado, mas os perversos não habitarão a terra.

[[v20-10-31]]

^<<v20-10-31,31>>^ A boca do justo jorra sabedoria, mas a língua da perversidade será cortada.

[[v20-10-32]]

^<<v20-10-32,32>>^ Os lábios do justo sabem o que agrada, mas a boca dos perversos, só perversidades.

'''

xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[&#60; Capítulo Anterior] | <<v20-10-0,Topo>> | xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[Próximo Capítulo &#62;]