include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-11-1]]

^<<v20-11-1,1>>^ Balança enganosa é abominação para o SENHOR, mas o peso justo é o seu prazer.

[[v20-11-2]]

^<<v20-11-2,2>>^ Em vindo a soberba, virá também a afronta; mas com os humildes está a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A sinceridade dos íntegros os guiará, mas a perversidade dos aleivosos os destruirá.

[[v20-11-4]]

^<<v20-11-4,4>>^ De nada aproveitam as riquezas no dia da ira, mas a justiça livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A justiça do sincero endireitará o seu caminho, mas o perverso pela sua falsidade cairá.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos virtuosos os livrará, mas na sua perversidade serão apanhados os iníquos.

[[v20-11-7]]

^<<v20-11-7,7>>^ Morrendo o homem perverso perece sua esperança, e acaba-se a expectação de riquezas.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é libertado da angústia, e vem o ímpio para o seu lugar.

[[v20-11-9]]

^<<v20-11-9,9>>^ O hipócrita com a boca destrói o seu próximo, mas os justos se libertam pelo conhecimento.

[[v20-11-10]]

^<<v20-11-10,10>>^ No bem dos justos exulta a cidade; e perecendo os ímpios, há júbilo.

[[v20-11-11]]

^<<v20-11-11,11>>^ Pela bênção dos homens de bem a cidade se exalta, mas pela boca dos perversos é derrubada.

[[v20-11-12]]

^<<v20-11-12,12>>^ O que despreza o seu próximo carece de entendimento, mas o homem entendido se mantém calado.

[[v20-11-13]]

^<<v20-11-13,13>>^ O mexeriqueiro revela o segredo, mas o fiel de espírito o mantém em oculto.

[[v20-11-14]]

^<<v20-11-14,14>>^ Não havendo sábios conselhos, o povo cai, mas na multidão de conselhos há segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Decerto sofrerá severamente aquele que fica por fiador do estranho, mas o que evita a fiança estará seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher graciosa guarda a honra como os violentos guardam as riquezas.

[[v20-11-17]]

^<<v20-11-17,17>>^ O homem bom cuida bem de si mesmo, mas o cruel prejudica o seu corpo.

[[v20-11-18]]

^<<v20-11-18,18>>^ O ímpio faz obra falsa, mas para o que semeia justiça haverá galardão fiel.

[[v20-11-19]]

^<<v20-11-19,19>>^ Como a justiça encaminha para a vida, assim o que segue o mal vai para a sua morte.

[[v20-11-20]]

^<<v20-11-20,20>>^ Abominação ao Senhor são os perversos de coração, mas os de caminho sincero são o seu deleite.

[[v20-11-21]]

^<<v20-11-21,21>>^ Ainda que junte as mãos, o mau não ficará impune, mas a semente dos justos será liberada.

[[v20-11-22]]

^<<v20-11-22,22>>^ Como jóia de ouro no focinho de uma porca, assim é a mulher formosa que não tem discrição.

[[v20-11-23]]

^<<v20-11-23,23>>^ O desejo dos justos é tão somente para o bem, mas a esperança dos ímpios é criar contrariedades.

[[v20-11-24]]

^<<v20-11-24,24>>^ Ao que distribui mais se lhe acrescenta, e ao que retém mais do que é justo, é para a sua perda.

[[v20-11-25]]

^<<v20-11-25,25>>^ A alma generosa prosperará e aquele que atende também será atendido.

[[v20-11-26]]

^<<v20-11-26,26>>^ Ao que retém o trigo o povo amaldiçoa, mas bênção haverá sobre a cabeça do que o vende.

[[v20-11-27]]

^<<v20-11-27,27>>^ O que cedo busca o bem, busca favor, mas o que procura o mal, esse lhe sobrevirá.

[[v20-11-28]]

^<<v20-11-28,28>>^ Aquele que confia nas suas riquezas cairá, mas os justos reverdecerão como a folhagem.

[[v20-11-29]]

^<<v20-11-29,29>>^ O que perturba a sua casa herdará o vento, e o tolo será servo do sábio de coração.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é árvore de vida, e o que ganha almas é sábio.

[[v20-11-31]]

^<<v20-11-31,31>>^ Eis que o justo recebe na terra a retribuição; quanto mais o ímpio e o pecador!

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]