include::./index.adoc[]

[[v20-5-0]]
=== Provérbios, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-5-1]]

^<<v20-5-1,1>>^ Filho meu, atende à minha sabedoria; à minha inteligência inclina o teu ouvido;

[[v20-5-2]]

^<<v20-5-2,2>>^ Para que guardes os meus conselhos e os teus lábios observem o conhecimento.

[[v20-5-3]]

^<<v20-5-3,3>>^ Porque os lábios da mulher estranha destilam favos de mel, e o seu paladar é mais suave do que o azeite.

[[v20-5-4]]

^<<v20-5-4,4>>^ Mas o seu fim é amargoso como o absinto, agudo como a espada de dois gumes.

[[v20-5-5]]

^<<v20-5-5,5>>^ Os seus pés descem para a morte; os seus passos estão impregnados do inferno.

[[v20-5-6]]

^<<v20-5-6,6>>^ Para que não ponderes os caminhos da vida, as suas andanças são errantes: jamais os conhecerás.

[[v20-5-7]]

^<<v20-5-7,7>>^ Agora, pois, filhos, dai-me ouvidos, e não vos desvieis das palavras da minha boca.

[[v20-5-8]]

^<<v20-5-8,8>>^ Longe dela seja o teu caminho, e não te chegues à porta da sua casa;

[[v20-5-9]]

^<<v20-5-9,9>>^ Para que não dês a outrem a tua honra, e não entregues a cruéis os teus anos de vida;

[[v20-5-10]]

^<<v20-5-10,10>>^ Para que não farte a estranhos o teu esforço, e todo o fruto do teu trabalho vá parar em casa alheia;

[[v20-5-11]]

^<<v20-5-11,11>>^ E no fim venhas a gemer, no consumir-se da tua carne e do teu corpo.

[[v20-5-12]]

^<<v20-5-12,12>>^ E então digas: Como odiei a correção! e o meu coração desprezou a repreensão!

[[v20-5-13]]

^<<v20-5-13,13>>^ E não escutei a voz dos que me ensinavam, nem aos meus mestres inclinei o meu ouvido!

[[v20-5-14]]

^<<v20-5-14,14>>^ No meio da congregação e da assembléia foi que eu me achei em quase todo o mal.

[[v20-5-15]]

^<<v20-5-15,15>>^ Bebe água da tua fonte, e das correntes do teu poço.

[[v20-5-16]]

^<<v20-5-16,16>>^ Derramar-se-iam as tuas fontes por fora, e pelas ruas os ribeiros de águas?

[[v20-5-17]]

^<<v20-5-17,17>>^ Sejam para ti só, e não para os estranhos contigo.

[[v20-5-18]]

^<<v20-5-18,18>>^ Seja bendito o teu manancial, e alegra-te com a mulher da tua mocidade.

[[v20-5-19]]

^<<v20-5-19,19>>^ Como cerva amorosa, e gazela graciosa, os seus seios te saciem todo o tempo; e pelo seu amor sejas atraído perpetuamente.

[[v20-5-20]]

^<<v20-5-20,20>>^ E porque, filho meu, te deixarias atrair por outra mulher, e te abraçarias ao peito de uma estranha?

[[v20-5-21]]

^<<v20-5-21,21>>^ Eis que os caminhos do homem estão perante os olhos do Senhor, e ele pesa todas as suas veredas.

[[v20-5-22]]

^<<v20-5-22,22>>^ Quanto ao ímpio, as suas iniqüidades o prenderão, e com as cordas do seu pecado será detido.

[[v20-5-23]]

^<<v20-5-23,23>>^ Ele morrerá, porque desavisadamente andou, e pelo excesso da sua loucura se perderá.

'''

xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[Próximo Capítulo &#62;]