include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-1-1]]

^<<v20-1-1,1>>^ Provérbios de Salomão, filho de Davi, rei de Israel;

[[v20-1-2]]

^<<v20-1-2,2>>^ Para se conhecer a sabedoria e a instrução; para se entenderem, as palavras da prudência.

[[v20-1-3]]

^<<v20-1-3,3>>^ Para se receber a instrução do entendimento, a justiça, o juízo e a eqüidade;

[[v20-1-4]]

^<<v20-1-4,4>>^ Para dar aos simples, prudência, e aos moços, conhecimento e bom siso;

[[v20-1-5]]

^<<v20-1-5,5>>^ O sábio ouvirá e crescerá em conhecimento, e o entendido adquirirá sábios conselhos;

[[v20-1-6]]

^<<v20-1-6,6>>^ Para entender os provérbios e sua interpretação; as palavras dos sábios e as suas proposições.

[[v20-1-7]]

^<<v20-1-7,7>>^ O temor do Senhor é o princípio do conhecimento; os loucos desprezam a sabedoria e a instrução.

[[v20-1-8]]

^<<v20-1-8,8>>^ Filho meu, ouve a instrução de teu pai, e não deixes o ensinamento de tua mãe,

[[v20-1-9]]

^<<v20-1-9,9>>^ Porque serão como diadema gracioso em tua cabeça, e colares ao teu pescoço.

[[v20-1-10]]

^<<v20-1-10,10>>^ Filho meu, se os pecadores procuram te atrair com agrados, não aceites.

[[v20-1-11]]

^<<v20-1-11,11>>^ Se disserem: Vem conosco a tocaias de sangue; embosquemos o inocente sem motivo;

[[v20-1-12]]

^<<v20-1-12,12>>^ Traguemo-los vivos, como a sepultura; e inteiros, como os que descem à cova;

[[v20-1-13]]

^<<v20-1-13,13>>^ Acharemos toda sorte de bens preciosos; encheremos as nossas casas de despojos;

[[v20-1-14]]

^<<v20-1-14,14>>^ Lança a tua sorte conosco; teremos todos uma só bolsa!

[[v20-1-15]]

^<<v20-1-15,15>>^ Filho meu, não te ponhas a caminho com eles; desvia o teu pé das suas veredas;

[[v20-1-16]]

^<<v20-1-16,16>>^ Porque os seus pés correm para o mal, e se apressam a derramar sangue.

[[v20-1-17]]

^<<v20-1-17,17>>^ Na verdade é inútil estender-se a rede ante os olhos de qualquer ave.

[[v20-1-18]]

^<<v20-1-18,18>>^ No entanto estes armam ciladas contra o seu próprio sangue; e espreitam suas próprias vidas.

[[v20-1-19]]

^<<v20-1-19,19>>^ São assim as veredas de todo aquele que usa de cobiça: ela põe a perder a alma dos que a possuem.

[[v20-1-20]]

^<<v20-1-20,20>>^ A sabedoria clama lá fora; pelas ruas levanta a sua voz.

[[v20-1-21]]

^<<v20-1-21,21>>^ Nas esquinas movimentadas ela brada; nas entradas das portas e nas cidades profere as suas palavras:

[[v20-1-22]]

^<<v20-1-22,22>>^ Até quando, ó simples, amareis a simplicidade? E vós escarnecedores, desejareis o escárnio? E vós insensatos, odiareis o conhecimento?

[[v20-1-23]]

^<<v20-1-23,23>>^ Atentai para a minha repreensão; pois eis que vos derramarei abundantemente do meu espírito e vos farei saber as minhas palavras.

[[v20-1-24]]

^<<v20-1-24,24>>^ Entretanto, porque eu clamei e recusastes; e estendi a minha mão e não houve quem desse atenção,

[[v20-1-25]]

^<<v20-1-25,25>>^ Antes rejeitastes todo o meu conselho, e não quisestes a minha repreensão,

[[v20-1-26]]

^<<v20-1-26,26>>^ Também de minha parte eu me rirei na vossa perdição e zombarei, em vindo o vosso temor.

[[v20-1-27]]

^<<v20-1-27,27>>^ Vindo o vosso temor como a assolação, e vindo a vossa perdição como uma tormenta, sobrevirá a vós aperto e angústia.

[[v20-1-28]]

^<<v20-1-28,28>>^ Então clamarão a mim, mas eu não responderei; de madrugada me buscarão, porém não me acharão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Porquanto odiaram o conhecimento; e não preferiram o temor do Senhor:

[[v20-1-30]]

^<<v20-1-30,30>>^ Não aceitaram o meu conselho, e desprezaram toda a minha repreensão.

[[v20-1-31]]

^<<v20-1-31,31>>^ Portanto comerão do fruto do seu caminho, e fartar-se-ão dos seus próprios conselhos.

[[v20-1-32]]

^<<v20-1-32,32>>^ Porque o erro dos simples os matará, e o desvario dos insensatos os destruirá.

[[v20-1-33]]

^<<v20-1-33,33>>^ Mas o que me der ouvidos habitará em segurança, e estará livre do temor do mal.

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]