include::./index.adoc[]

[[v20-19-0]]
=== Provérbios, 19
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-19-1]]

^<<v20-19-1,1>>^ Melhor é o pobre que anda na sua integridade do que o perverso de lábios e tolo.

[[v20-19-2]]

^<<v20-19-2,2>>^ Assim como não é bom ficar a alma sem conhecimento, peca aquele que se apressa com seus pés.

[[v20-19-3]]

^<<v20-19-3,3>>^ A estultícia do homem perverterá o seu caminho, e o seu coração se irará contra o Senhor.

[[v20-19-4]]

^<<v20-19-4,4>>^ As riquezas granjeiam muitos amigos, mas ao pobre, o seu próprio amigo o deixa.

[[v20-19-5]]

^<<v20-19-5,5>>^ A falsa testemunha não ficará impune e o que respira mentiras não escapará.

[[v20-19-6]]

^<<v20-19-6,6>>^ Muitos se deixam acomodar pelos favores do príncipe, e cada um é amigo daquele que dá presentes.

[[v20-19-7]]

^<<v20-19-7,7>>^ Todos os irmãos do pobre o odeiam; quanto mais se afastarão dele os seus amigos! Corre após eles com palavras, que não servem de nada.

[[v20-19-8]]

^<<v20-19-8,8>>^ O que adquire entendimento ama a sua alma; o que cultiva a inteligência achará o bem.

[[v20-19-9]]

^<<v20-19-9,9>>^ A falsa testemunha não ficará impune; e o que profere mentiras perecerá.

[[v20-19-10]]

^<<v20-19-10,10>>^ Ao tolo não é certo gozar de deleites; quanto menos ao servo dominar sobre os príncipes!

[[v20-19-11]]

^<<v20-19-11,11>>^ A prudência do homem faz reter a sua ira, e é glória sua o passar por cima da transgressão.

[[v20-19-12]]

^<<v20-19-12,12>>^ Como o rugido do leão jovem é a indignação do rei, mas como o orvalho sobre a relva é a sua benevolência.

[[v20-19-13]]

^<<v20-19-13,13>>^ O filho insensato é uma desgraça para o pai, e um gotejar contínuo as contendas da mulher.

[[v20-19-14]]

^<<v20-19-14,14>>^ A casa e os bens são herança dos pais; porém do Senhor vem a esposa prudente.

[[v20-19-15]]

^<<v20-19-15,15>>^ A preguiça faz cair em profundo sono, e a alma indolente padecerá fome.

[[v20-19-16]]

^<<v20-19-16,16>>^ O que guardar o mandamento guardará a sua alma; porém o que desprezar os seus caminhos morrerá.

[[v20-19-17]]

^<<v20-19-17,17>>^ Ao Senhor empresta o que se compadece do pobre, ele lhe pagará o seu benefício.

[[v20-19-18]]

^<<v20-19-18,18>>^ Castiga o teu filho enquanto há esperança, mas não deixes que o teu ânimo se exalte até o matar.

[[v20-19-19]]

^<<v20-19-19,19>>^ O homem de grande indignação deve sofrer o dano; porque se tu o livrares ainda terás de tornar a fazê-lo.

[[v20-19-20]]

^<<v20-19-20,20>>^ Ouve o conselho, e recebe a correção, para que no fim sejas sábio.

[[v20-19-21]]

^<<v20-19-21,21>>^ Muitos propósitos há no coração do homem, porém o conselho do Senhor permanecerá.

[[v20-19-22]]

^<<v20-19-22,22>>^ O que o homem mais deseja é o que lhe faz bem; porém é melhor ser pobre do que mentiroso.

[[v20-19-23]]

^<<v20-19-23,23>>^ O temor do Senhor encaminha para a vida; aquele que o tem ficará satisfeito, e não o visitará mal nenhum.

[[v20-19-24]]

^<<v20-19-24,24>>^ O preguiçoso esconde a sua mão ao seio; e não tem disposição nem de torná-la à sua boca.

[[v20-19-25]]

^<<v20-19-25,25>>^ Açoita o escarnecedor, e o simples tomará aviso; repreende ao entendido, e aprenderá conhecimento.

[[v20-19-26]]

^<<v20-19-26,26>>^ O que aflige o seu pai, ou manda embora sua mãe, é filho que traz vergonha e desonra.

[[v20-19-27]]

^<<v20-19-27,27>>^ Filho meu, ouvindo a instrução, cessa de te desviares das palavras do conhecimento.

[[v20-19-28]]

^<<v20-19-28,28>>^ O ímpio escarnece do juízo, e a boca dos perversos devora a iniqüidade.

[[v20-19-29]]

^<<v20-19-29,29>>^ Preparados estão os juízos para os escarnecedores, e os açoites para as costas dos tolos.

'''

xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[Próximo Capítulo &#62;]