include::./index.adoc[]

[[v20-23-0]]
=== Provérbios, 23
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-23-1]]

^<<v20-23-1,1>>^ Quando te assentares a comer com um governador, atenta bem para o que é posto diante de ti,

[[v20-23-2]]

^<<v20-23-2,2>>^ E se és homem de grande apetite, põe uma faca à tua garganta.

[[v20-23-3]]

^<<v20-23-3,3>>^ Não cobices as suas iguarias porque são comidas enganosas.

[[v20-23-4]]

^<<v20-23-4,4>>^ Não te fatigues para enriqueceres; e não apliques nisso a tua sabedoria.

[[v20-23-5]]

^<<v20-23-5,5>>^ Porventura fixarás os teus olhos naquilo que não é nada? porque certamente criará asas e voará ao céu como a águia.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não comas o pão daquele que tem o olhar maligno, nem cobices as suas iguarias gostosas.

[[v20-23-7]]

^<<v20-23-7,7>>^ Porque, como imaginou no seu coração, assim é ele. Come e bebe, te disse ele; porém o seu coração não está contigo.

[[v20-23-8]]

^<<v20-23-8,8>>^ Vomitarás o bocado que comeste, e perderás as tuas suaves palavras.

[[v20-23-9]]

^<<v20-23-9,9>>^ Não fales ao ouvido do tolo, porque desprezará a sabedoria das tuas palavras.

[[v20-23-10]]

^<<v20-23-10,10>>^ Não removas os limites antigos nem entres nos campos dos órfãos,

[[v20-23-11]]

^<<v20-23-11,11>>^ Porque o seu redentor é poderoso; e pleiteará a causa deles contra ti.

[[v20-23-12]]

^<<v20-23-12,12>>^ Aplica o teu coração à instrução e os teus ouvidos às palavras do conhecimento.

[[v20-23-13]]

^<<v20-23-13,13>>^ Não retires a disciplina da criança; pois se a fustigares com a vara, nem por isso morrerá.

[[v20-23-14]]

^<<v20-23-14,14>>^ Tu a fustigarás com a vara, e livrarás a sua alma do inferno.

[[v20-23-15]]

^<<v20-23-15,15>>^ Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.

[[v20-23-16]]

^<<v20-23-16,16>>^ E exultarão os meus rins, quando os teus lábios falarem coisas retas.

[[v20-23-17]]

^<<v20-23-17,17>>^ O teu coração não inveje os pecadores; antes permanece no temor do Senhor todo dia.

[[v20-23-18]]

^<<v20-23-18,18>>^ Porque certamente acabará bem; não será malograda a tua esperança.

[[v20-23-19]]

^<<v20-23-19,19>>^ Ouve tu, filho meu, e sê sábio, e dirige no caminho o teu coração.

[[v20-23-20]]

^<<v20-23-20,20>>^ Não estejas entre os beberrões de vinho, nem entre os comilões de carne.

[[v20-23-21]]

^<<v20-23-21,21>>^ Porque o beberrão e o comilão acabarão na pobreza; e a sonolência os faz vestir-se de trapos.

[[v20-23-22]]

^<<v20-23-22,22>>^ Ouve teu pai, que te gerou, e não desprezes tua mãe, quando vier a envelhecer.

[[v20-23-23]]

^<<v20-23-23,23>>^ Compra a verdade, e não a vendas; e também a sabedoria, a instrução e o entendimento.

[[v20-23-24]]

^<<v20-23-24,24>>^ Grandemente se regozijará o pai do justo, e o que gerar um sábio, se alegrará nele.

[[v20-23-25]]

^<<v20-23-25,25>>^ Alegrem-se teu pai e tua mãe, e regozije-se a que te gerou.

[[v20-23-26]]

^<<v20-23-26,26>>^ Dá-me, filho meu, o teu coração, e os teus olhos observem os meus caminhos.

[[v20-23-27]]

^<<v20-23-27,27>>^ Porque cova profunda é a prostituta, e poço estreito a estranha.

[[v20-23-28]]

^<<v20-23-28,28>>^ Pois ela, como um salteador, se põe à espreita, e multiplica entre os homens os iníquos.

[[v20-23-29]]

^<<v20-23-29,29>>^ Para quem são os ais? Para quem os pesares? Para quem as pelejas? Para quem as queixas? Para quem as feridas sem causa? E para quem os olhos vermelhos?

[[v20-23-30]]

^<<v20-23-30,30>>^ Para os que se demoram perto do vinho, para os que andam buscando vinho misturado.

[[v20-23-31]]

^<<v20-23-31,31>>^ Não olhes para o vinho quando se mostra vermelho, quando resplandece no copo e se escoa suavemente.

[[v20-23-32]]

^<<v20-23-32,32>>^ No fim, picará como a cobra, e como o basilisco morderá.

[[v20-23-33]]

^<<v20-23-33,33>>^ Os teus olhos olharão para as mulheres estranhas, e o teu coração falará perversidades.

[[v20-23-34]]

^<<v20-23-34,34>>^ E serás como o que se deita no meio do mar, e como o que jaz no topo do mastro.

[[v20-23-35]]

^<<v20-23-35,35>>^ E dirás: Espancaram-me e não me doeu; bateram-me e nem senti; quando despertarei? aí então beberei outra vez.

'''

xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[Próximo Capítulo &#62;]