include::./index.adoc[]

[[v20-6-0]]
=== Provérbios, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-6-1]]

^<<v20-6-1,1>>^ Filho meu, se ficaste por fiador do teu companheiro, se deste a tua mão ao estranho,

[[v20-6-2]]

^<<v20-6-2,2>>^ E te deixaste enredar pelas próprias palavras; e te prendeste nas palavras da tua boca;

[[v20-6-3]]

^<<v20-6-3,3>>^ Faze pois isto agora, filho meu, e livra-te, já que caíste nas mãos do teu companheiro: vai, humilha-te, e importuna o teu companheiro.

[[v20-6-4]]

^<<v20-6-4,4>>^ Não dês sono aos teus olhos, nem deixes adormecer as tuas pálpebras.

[[v20-6-5]]

^<<v20-6-5,5>>^ Livra-te, como a gazela da mão do caçador, e como a ave da mão do passarinheiro.

[[v20-6-6]]

^<<v20-6-6,6>>^ Vai ter com a formiga, ó preguiçoso; olha para os seus caminhos, e sê sábio.

[[v20-6-7]]

^<<v20-6-7,7>>^ Pois ela, não tendo chefe, nem guarda, nem dominador,

[[v20-6-8]]

^<<v20-6-8,8>>^ Prepara no verão o seu pão; na sega ajunta o seu mantimento.

[[v20-6-9]]

^<<v20-6-9,9>>^ Ó preguiçoso, até quando ficarás deitado? Quando te levantarás do teu sono?

[[v20-6-10]]

^<<v20-6-10,10>>^ Um pouco a dormir, um pouco a tosquenejar; um pouco a repousar de braços cruzados;

[[v20-6-11]]

^<<v20-6-11,11>>^ Assim sobrevirá a tua pobreza como o meliante, e a tua necessidade como um homem armado.

[[v20-6-12]]

^<<v20-6-12,12>>^ O homem mau, o homem iníquo tem a boca pervertida.

[[v20-6-13]]

^<<v20-6-13,13>>^ Acena com os olhos, fala com os pés e faz sinais com os dedos.

[[v20-6-14]]

^<<v20-6-14,14>>^ Há no seu coração perversidade, todo o tempo maquina mal; anda semeando contendas.

[[v20-6-15]]

^<<v20-6-15,15>>^ Por isso a sua destruição virá repentinamente; subitamente será quebrantado, sem que haja cura.

[[v20-6-16]]

^<<v20-6-16,16>>^ Estas seis coisas o Senhor odeia, e a sétima a sua alma abomina:

[[v20-6-17]]

^<<v20-6-17,17>>^ Olhos altivos, língua mentirosa, mãos que derramam sangue inocente,

[[v20-6-18]]

^<<v20-6-18,18>>^ O coração que maquina pensamentos perversos, pés que se apressam a correr para o mal,

[[v20-6-19]]

^<<v20-6-19,19>>^ A testemunha falsa que profere mentiras, e o que semeia contendas entre irmãos.

[[v20-6-20]]

^<<v20-6-20,20>>^ Filho meu, guarda o mandamento de teu pai, e não deixes a lei da tua mãe;

[[v20-6-21]]

^<<v20-6-21,21>>^ Ata-os perpetuamente ao teu coração, e pendura-os ao teu pescoço.

[[v20-6-22]]

^<<v20-6-22,22>>^ Quando caminhares, te guiará; quando te deitares, te guardará; quando acordares, falará contigo.

[[v20-6-23]]

^<<v20-6-23,23>>^ Porque o mandamento é lâmpada, e a lei é luz; e as repreensões da correção são o caminho da vida,

[[v20-6-24]]

^<<v20-6-24,24>>^ Para te guardarem da mulher vil, e das lisonjas da estranha.

[[v20-6-25]]

^<<v20-6-25,25>>^ Não cobices no teu coração a sua formosura, nem te prendas aos seus olhos.

[[v20-6-26]]

^<<v20-6-26,26>>^ Porque por causa duma prostituta se chega a pedir um bocado de pão; e a adúltera anda à caça da alma preciosa.

[[v20-6-27]]

^<<v20-6-27,27>>^ Porventura tomará alguém fogo no seu seio, sem que suas vestes se queimem?

[[v20-6-28]]

^<<v20-6-28,28>>^ Ou andará alguém sobre brasas, sem que se queimem os seus pés?

[[v20-6-29]]

^<<v20-6-29,29>>^ Assim ficará o que entrar à mulher do seu próximo; não será inocente todo aquele que a tocar.

[[v20-6-30]]

^<<v20-6-30,30>>^ Não se injuria o ladrão, quando furta para saciar-se, tendo fome;

[[v20-6-31]]

^<<v20-6-31,31>>^ E se for achado pagará o tanto sete vezes; terá de dar todos os bens da sua casa.

[[v20-6-32]]

^<<v20-6-32,32>>^ Assim, o que adultera com uma mulher é falto de entendimento; aquele que faz isso destrói a sua alma.

[[v20-6-33]]

^<<v20-6-33,33>>^ Achará castigo e vilipêndio, e o seu opróbrio nunca se apagará.

[[v20-6-34]]

^<<v20-6-34,34>>^ Porque os ciúmes enfurecerão o marido; de maneira nenhuma perdoará no dia da vingança.

[[v20-6-35]]

^<<v20-6-35,35>>^ Não aceitará nenhum resgate, nem se conformará por mais que aumentes os presentes.

'''

xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[&#60; Capítulo Anterior] | <<v20-6-0,Topo>> | xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[Próximo Capítulo &#62;]