include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-22-1]]

^<<v20-22-1,1>>^ Vale mais ter um bom nome do que muitas riquezas; e o ser estimado é melhor do que a riqueza e o ouro.

[[v20-22-2]]

^<<v20-22-2,2>>^ O rico e o pobre se encontram; a todos o Senhor os fez.

[[v20-22-3]]

^<<v20-22-3,3>>^ O prudente prevê o mal, e esconde-se; mas os simples passam e acabam pagando.

[[v20-22-4]]

^<<v20-22-4,4>>^ O galardão da humildade e o temor do Senhor são riquezas, honra e vida.

[[v20-22-5]]

^<<v20-22-5,5>>^ Espinhos e laços há no caminho do perverso; o que guarda a sua alma retira-se para longe dele.

[[v20-22-6]]

^<<v20-22-6,6>>^ Educa a criança no caminho em que deve andar; e até quando envelhecer não se desviará dele.

[[v20-22-7]]

^<<v20-22-7,7>>^ O rico domina sobre os pobres e o que toma emprestado é servo do que empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ O que semear a perversidade segará males; e com a vara da sua própria indignação será extinto.

[[v20-22-9]]

^<<v20-22-9,9>>^ O que vê com bons olhos será abençoado, porque dá do seu pão ao pobre.

[[v20-22-10]]

^<<v20-22-10,10>>^ Lança fora o escarnecedor, e se irá a contenda; e acabará a questão e a vergonha.

[[v20-22-11]]

^<<v20-22-11,11>>^ O que ama a pureza de coração, e é amável de lábios, será amigo do rei.

[[v20-22-12]]

^<<v20-22-12,12>>^ Os olhos do Senhor conservam o conhecimento, mas as palavras do iníquo ele transtornará.

[[v20-22-13]]

^<<v20-22-13,13>>^ Diz o preguiçoso: Um leão está lá fora; serei morto no meio das ruas.

[[v20-22-14]]

^<<v20-22-14,14>>^ Cova profunda é a boca das mulheres estranhas; aquele contra quem o Senhor se irar, cairá nela.

[[v20-22-15]]

^<<v20-22-15,15>>^ A estultícia está ligada ao coração da criança, mas a vara da correção a afugentará dela.

[[v20-22-16]]

^<<v20-22-16,16>>^ O que oprime ao pobre para se engrandecer a si mesmo, ou o que dá ao rico, certamente empobrecerá.

[[v20-22-17]]

^<<v20-22-17,17>>^ Inclina o teu ouvido e ouve as palavras dos sábios, e aplica o teu coração ao meu conhecimento.

[[v20-22-18]]

^<<v20-22-18,18>>^ Porque te será agradável se as guardares no teu íntimo, se aplicares todas elas aos teus lábios.

[[v20-22-19]]

^<<v20-22-19,19>>^ Para que a tua confiança esteja no Senhor, faço-te sabê-las hoje, a ti mesmo.

[[v20-22-20]]

^<<v20-22-20,20>>^ Porventura não te escrevi excelentes coisas, acerca de todo conselho e conhecimento,

[[v20-22-21]]

^<<v20-22-21,21>>^ Para fazer-te saber a certeza das palavras da verdade, e assim possas responder palavras de verdade aos que te consultarem?

[[v20-22-22]]

^<<v20-22-22,22>>^ Não roubes ao pobre, porque é pobre, nem atropeles na porta o aflito;

[[v20-22-23]]

^<<v20-22-23,23>>^ Porque o Senhor defenderá a sua causa em juízo, e aos que os roubam ele lhes tirará a vida.

[[v20-22-24]]

^<<v20-22-24,24>>^ Não sejas companheiro do homem briguento nem andes com o colérico,

[[v20-22-25]]

^<<v20-22-25,25>>^ Para que não aprendas as suas veredas, e tomes um laço para a tua alma.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não estejas entre os que se comprometem, e entre os que ficam por fiadores de dívidas,

[[v20-22-27]]

^<<v20-22-27,27>>^ Pois se não tens com que pagar, deixarias que te tirassem até a tua cama de debaixo de ti?

[[v20-22-28]]

^<<v20-22-28,28>>^ Não removas os antigos limites que teus pais fizeram.

[[v20-22-29]]

^<<v20-22-29,29>>^ Viste o homem diligente na sua obra? Perante reis será posto; não permanecerá entre os de posição inferior.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]