include::./index.adoc[]

[[v20-20-0]]
=== Provérbios, 20
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-20-1]]

^<<v20-20-1,1>>^ O vinho é escarnecedor, a bebida forte alvoroçadora; e todo aquele que neles errar nunca será sábio.

[[v20-20-2]]

^<<v20-20-2,2>>^ Como o rugido do leão é o terror do rei; o que o provoca à ira peca contra a sua própria alma.

[[v20-20-3]]

^<<v20-20-3,3>>^ Honroso é para o homem desviar-se de questões, mas todo tolo é intrometido.

[[v20-20-4]]

^<<v20-20-4,4>>^ O preguiçoso não lavrará por causa do inverno, pelo que mendigará na sega, mas nada receberá.

[[v20-20-5]]

^<<v20-20-5,5>>^ Como as águas profundas é o conselho no coração do homem; mas o homem de inteligência o trará para fora.

[[v20-20-6]]

^<<v20-20-6,6>>^ A multidão dos homens apregoa a sua própria bondade, porém o homem fidedigno quem o achará?

[[v20-20-7]]

^<<v20-20-7,7>>^ O justo anda na sua sinceridade; bem-aventurados serão os seus filhos depois dele.

[[v20-20-8]]

^<<v20-20-8,8>>^ Assentando-se o rei no trono do juízo, com os seus olhos dissipa todo o mal.

[[v20-20-9]]

^<<v20-20-9,9>>^ Quem poderá dizer: Purifiquei o meu coração, limpo estou de meu pecado?

[[v20-20-10]]

^<<v20-20-10,10>>^ Dois pesos diferentes e duas espécies de medida são abominação ao Senhor, tanto um como outro.

[[v20-20-11]]

^<<v20-20-11,11>>^ Até a criança se dará a conhecer pelas suas ações, se a sua obra é pura e reta.

[[v20-20-12]]

^<<v20-20-12,12>>^ O ouvido que ouve, e o olho que vê, o Senhor os fez a ambos.

[[v20-20-13]]

^<<v20-20-13,13>>^ Não ames o sono, para que não empobreças; abre os teus olhos, e te fartarás de pão.

[[v20-20-14]]

^<<v20-20-14,14>>^ Nada vale, nada vale, dirá o comprador, mas, indo-se, então se gabará.

[[v20-20-15]]

^<<v20-20-15,15>>^ Há ouro e abundância de rubis, mas os lábios do conhecimento são jóia preciosa.

[[v20-20-16]]

^<<v20-20-16,16>>^ Ficando alguém por fiador de um estranho, tome-se-lhe a roupa; e por penhor àquele que se obriga pela mulher estranha.

[[v20-20-17]]

^<<v20-20-17,17>>^ Suave é ao homem o pão da mentira, mas depois a sua boca se encherá de cascalho.

[[v20-20-18]]

^<<v20-20-18,18>>^ Cada pensamento se confirma com conselho e com bons conselhos se faz a guerra.

[[v20-20-19]]

^<<v20-20-19,19>>^ O que anda tagarelando revela o segredo; não te intrometas com o que lisonjeia com os seus lábios.

[[v20-20-20]]

^<<v20-20-20,20>>^ O que amaldiçoa seu pai ou sua mãe, apagar-se-á a sua lâmpada em negras trevas.

[[v20-20-21]]

^<<v20-20-21,21>>^ A herança que no princípio é adquirida às pressas, no fim não será abençoada.

[[v20-20-22]]

^<<v20-20-22,22>>^ Não digas: Vingar-me-ei do mal; espera pelo Senhor, e ele te livrará.

[[v20-20-23]]

^<<v20-20-23,23>>^ Pesos diferentes são abomináveis ao Senhor, e balança enganosa não é boa.

[[v20-20-24]]

^<<v20-20-24,24>>^ Os passos do homem são dirigidos pelo Senhor; como, pois, entenderá o homem o seu caminho?

[[v20-20-25]]

^<<v20-20-25,25>>^ Laço é para o homem apropriar-se do que é santo, e só refletir depois de feitos os votos.

[[v20-20-26]]

^<<v20-20-26,26>>^ O rei sábio dispersa os ímpios e faz passar sobre eles a roda.

[[v20-20-27]]

^<<v20-20-27,27>>^ O espírito do homem é a lâmpada do Senhor, que esquadrinha todo o interior até o mais íntimo do ventre.

[[v20-20-28]]

^<<v20-20-28,28>>^ Benignidade e verdade guardam ao rei, e com benignidade sustém ele o seu trono.

[[v20-20-29]]

^<<v20-20-29,29>>^ A glória do jovem é a sua força; e a beleza dos velhos são as cãs.

[[v20-20-30]]

^<<v20-20-30,30>>^ Os vergões das feridas são a purificação dos maus, como também as pancadas que penetram até o mais íntimo do ventre.

'''

xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[&#60; Capítulo Anterior] | <<v20-20-0,Topo>> | xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[Próximo Capítulo &#62;]