include::./index.adoc[]

[[v20-28-0]]
=== Provérbios, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-28-1]]

^<<v20-28-1,1>>^ Os ímpios fogem sem que haja ninguém a persegui-los; mas os justos são ousados como um leão.

[[v20-28-2]]

^<<v20-28-2,2>>^ Pela transgressão da terra muitos são os seus príncipes, mas por homem prudente e entendido a sua continuidade será prolongada.

[[v20-28-3]]

^<<v20-28-3,3>>^ O homem pobre que oprime os pobres é como a chuva impetuosa, que causa a falta de alimento.

[[v20-28-4]]

^<<v20-28-4,4>>^ Os que deixam a lei louvam o ímpio; porém os que guardam a lei contendem com eles.

[[v20-28-5]]

^<<v20-28-5,5>>^ Os homens maus não entendem o juízo, mas os que buscam ao Senhor entendem tudo.

[[v20-28-6]]

^<<v20-28-6,6>>^ Melhor é o pobre que anda na sua integridade do que o de caminhos perversos ainda que seja rico.

[[v20-28-7]]

^<<v20-28-7,7>>^ O que guarda a lei é filho sábio, mas o companheiro dos desregrados envergonha a seu pai.

[[v20-28-8]]

^<<v20-28-8,8>>^ O que aumenta os seus bens com usura e ganância ajunta-os para o que se compadece do pobre.

[[v20-28-9]]

^<<v20-28-9,9>>^ O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável.

[[v20-28-10]]

^<<v20-28-10,10>>^ O que faz com que os retos errem por mau caminho, ele mesmo cairá na sua cova; mas os bons herdarão o bem.

[[v20-28-11]]

^<<v20-28-11,11>>^ O homem rico é sábio aos seus próprios olhos, mas o pobre que é entendido, o examina.

[[v20-28-12]]

^<<v20-28-12,12>>^ Quando os justos exultam, grande é a glória; mas quando os ímpios sobem, os homens se escondem.

[[v20-28-13]]

^<<v20-28-13,13>>^ O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia.

[[v20-28-14]]

^<<v20-28-14,14>>^ Bem-aventurado o homem que continuamente teme; mas o que endurece o seu coração cairá no mal.

[[v20-28-15]]

^<<v20-28-15,15>>^ Como leão rugidor, e urso faminto, assim é o ímpio que domina sobre um povo pobre.

[[v20-28-16]]

^<<v20-28-16,16>>^ O príncipe falto de entendimento é também um grande opressor, mas o que odeia a avareza prolongará seus dias.

[[v20-28-17]]

^<<v20-28-17,17>>^ O homem carregado do sangue de qualquer pessoa fugirá até à cova; ninguém o detenha.

[[v20-28-18]]

^<<v20-28-18,18>>^ O que anda sinceramente salvar-se-á, mas o perverso em seus caminhos cairá logo.

[[v20-28-19]]

^<<v20-28-19,19>>^ O que lavrar a sua terra virá a fartar-se de pão, mas o que segue a ociosos se fartará de pobreza.

[[v20-28-20]]

^<<v20-28-20,20>>^ O homem fiel será coberto de bênçãos, mas o que se apressa a enriquecer não ficará impune.

[[v20-28-21]]

^<<v20-28-21,21>>^ Dar importância à aparência das pessoas não é bom, porque até por um bocado de pão um homem prevaricará.

[[v20-28-22]]

^<<v20-28-22,22>>^ O que quer enriquecer depressa é homem de olho maligno, porém não sabe que a pobreza há de vir sobre ele.

[[v20-28-23]]

^<<v20-28-23,23>>^ O que repreende o homem gozará depois mais amizade do que aquele que lisonjeia com a língua.

[[v20-28-24]]

^<<v20-28-24,24>>^ O que rouba a seu próprio pai, ou a sua mãe, e diz: Não é transgressão, companheiro é do homem destruidor.

[[v20-28-25]]

^<<v20-28-25,25>>^ O orgulhoso de coração levanta contendas, mas o que confia no Senhor prosperará.

[[v20-28-26]]

^<<v20-28-26,26>>^ O que confia no seu próprio coração é insensato, mas o que anda em sabedoria, será salvo.

[[v20-28-27]]

^<<v20-28-27,27>>^ O que dá ao pobre não terá necessidade, mas o que esconde os seus olhos terá muitas maldições.

[[v20-28-28]]

^<<v20-28-28,28>>^ Quando os ímpios se elevam, os homens andam se escondendo, mas quando perecem, os justos se multiplicam.

'''

xref:020-proverbios/020-proverbios-027.adoc#v20-27-0[&#60; Capítulo Anterior] | <<v20-28-0,Topo>> | xref:020-proverbios/020-proverbios-029.adoc#v20-29-0[Próximo Capítulo &#62;]