include::./index.adoc[]

[[v20-27-0]]
=== Provérbios, 27
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-27-1]]

^<<v20-27-1,1>>^ Não presumas do dia de amanhã, porque não sabes o que ele trará.

[[v20-27-2]]

^<<v20-27-2,2>>^ Que um outro te louve, e não a tua própria boca; o estranho, e não os teus lábios.

[[v20-27-3]]

^<<v20-27-3,3>>^ A pedra é pesada, e a areia é espessa; porém a ira do insensato é mais pesada que ambas.

[[v20-27-4]]

^<<v20-27-4,4>>^ O furor é cruel e a ira impetuosa, mas quem poderá enfrentar a inveja?

[[v20-27-5]]

^<<v20-27-5,5>>^ Melhor é a repreensão franca do que o amor encoberto.

[[v20-27-6]]

^<<v20-27-6,6>>^ Leais são as feridas feitas pelo amigo, mas os beijos do inimigo são enganosos.

[[v20-27-7]]

^<<v20-27-7,7>>^ A alma farta pisa o favo de mel, mas para a alma faminta todo amargo é doce.

[[v20-27-8]]

^<<v20-27-8,8>>^ Qual a ave que vagueia longe do seu ninho, tal é o homem que anda vagueando longe da sua morada.

[[v20-27-9]]

^<<v20-27-9,9>>^ O óleo e o perfume alegram o coração; assim o faz a doçura do amigo pelo conselho cordial.

[[v20-27-10]]

^<<v20-27-10,10>>^ Não deixes o teu amigo, nem o amigo de teu pai; nem entres na casa de teu irmão no dia da tua adversidade; melhor é o vizinho perto do que o irmão longe.

[[v20-27-11]]

^<<v20-27-11,11>>^ Sê sábio, filho meu, e alegra o meu coração, para que tenha alguma coisa que responder àquele que me desprezar.

[[v20-27-12]]

^<<v20-27-12,12>>^ O avisado vê o mal e esconde-se; mas os simples passam e sofrem a pena.

[[v20-27-13]]

^<<v20-27-13,13>>^ Quando alguém fica por fiador do estranho, toma-lhe até a sua roupa, e por penhor àquele que se obriga pela mulher estranha.

[[v20-27-14]]

^<<v20-27-14,14>>^ O que, pela manhã de madrugada, abençoa o seu amigo em alta voz, lho será imputado por maldição.

[[v20-27-15]]

^<<v20-27-15,15>>^ O gotejar contínuo em dia de grande chuva, e a mulher contenciosa, uma e outra são semelhantes;

[[v20-27-16]]

^<<v20-27-16,16>>^ Tentar moderá-la será como deter o vento, ou como conter o óleo dentro da sua mão direita.

[[v20-27-17]]

^<<v20-27-17,17>>^ Como o ferro com ferro se aguça, assim o homem afia o rosto do seu amigo.

[[v20-27-18]]

^<<v20-27-18,18>>^ O que cuida da figueira comerá do seu fruto; e o que atenta para o seu senhor será honrado.

[[v20-27-19]]

^<<v20-27-19,19>>^ Como na água o rosto corresponde ao rosto, assim o coração do homem ao homem.

[[v20-27-20]]

^<<v20-27-20,20>>^ Como o inferno e a perdição nunca se fartam, assim os olhos do homem nunca se satisfazem.

[[v20-27-21]]

^<<v20-27-21,21>>^ Como o crisol é para a prata, e o forno para o ouro, assim o homem é provado pelos louvores.

[[v20-27-22]]

^<<v20-27-22,22>>^ Ainda que repreendas o tolo como quem bate o trigo com a mão de gral entre grãos pilados, não se apartará dele a sua estultícia.

[[v20-27-23]]

^<<v20-27-23,23>>^ Procura conhecer o estado das tuas ovelhas; põe o teu coração sobre os teus rebanhos,

[[v20-27-24]]

^<<v20-27-24,24>>^ Porque o tesouro não dura para sempre; e durará a coroa de geração em geração?

[[v20-27-25]]

^<<v20-27-25,25>>^ Quando brotar a erva, e aparecerem os renovos, e se juntarem as ervas dos montes,

[[v20-27-26]]

^<<v20-27-26,26>>^ Então os cordeiros serão para te vestires, e os bodes para o preço do campo;

[[v20-27-27]]

^<<v20-27-27,27>>^ E a abastança do leite das cabras para o teu sustento, para sustento da tua casa e para sustento das tuas servas.

'''

xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[&#60; Capítulo Anterior] | <<v20-27-0,Topo>> | xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[Próximo Capítulo &#62;]