include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-16-1]]

^<<v20-16-1,1>>^ Do homem são as preparações do coração, mas do SENHOR a resposta da língua.

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem são puros aos seus olhos, mas o Senhor pesa o espírito.

[[v20-16-3]]

^<<v20-16-3,3>>^ Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ O Senhor fez todas as coisas para atender aos seus próprios desígnios, até o ímpio para o dia do mal.

[[v20-16-5]]

^<<v20-16-5,5>>^ Abominação é ao Senhor todo o altivo de coração; não ficará impune mesmo de mãos postas.

[[v20-16-6]]

^<<v20-16-6,6>>^ Pela misericórdia e verdade a iniqüidade é perdoada, e pelo temor do Senhor os homens se desviam do pecado.

[[v20-16-7]]

^<<v20-16-7,7>>^ Sendo os caminhos do homem agradáveis ao Senhor, até a seus inimigos faz que tenham paz com ele.

[[v20-16-8]]

^<<v20-16-8,8>>^ Melhor é o pouco com justiça, do que a abundância de bens com injustiça.

[[v20-16-9]]

^<<v20-16-9,9>>^ O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Nos lábios do rei se acha a sentença divina; a sua boca não transgride quando julga.

[[v20-16-11]]

^<<v20-16-11,11>>^ O peso e a balança justos são do Senhor; obra sua são os pesos da bolsa.

[[v20-16-12]]

^<<v20-16-12,12>>^ Abominação é aos reis praticarem impiedade, porque com justiça é que se estabelece o trono.

[[v20-16-13]]

^<<v20-16-13,13>>^ Os lábios de justiça são o contentamento dos reis; eles amarão o que fala coisas retas.

[[v20-16-14]]

^<<v20-16-14,14>>^ O furor do rei é mensageiro da morte, mas o homem sábio o apaziguará.

[[v20-16-15]]

^<<v20-16-15,15>>^ No semblante iluminado do rei está a vida, e a sua benevolência é como a nuvem da chuva serôdia.

[[v20-16-16]]

^<<v20-16-16,16>>^ Quão melhor é adquirir a sabedoria do que o ouro! e quão mais excelente é adquirir a prudência do que a prata!

[[v20-16-17]]

^<<v20-16-17,17>>^ Os retos fazem o seu caminho desviar-se do mal; o que guarda o seu caminho preserva a sua alma.

[[v20-16-18]]

^<<v20-16-18,18>>^ A soberba precede a ruína, e a altivez do espírito precede a queda.

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é ser humilde de espírito com os mansos, do que repartir o despojo com os soberbos.

[[v20-16-20]]

^<<v20-16-20,20>>^ O que atenta prudentemente para o assunto achará o bem, e o que confia no Senhor será bem-aventurado.

[[v20-16-21]]

^<<v20-16-21,21>>^ O sábio de coração será chamado prudente, e a doçura dos lábios aumentará o ensino.

[[v20-16-22]]

^<<v20-16-22,22>>^ O entendimento para aqueles que o possuem, é uma fonte de vida, mas a instrução dos tolos é a sua estultícia.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio instrui a sua boca, e aumenta o ensino dos seus lábios.

[[v20-16-24]]

^<<v20-16-24,24>>^ As palavras suaves são favos de mel, doces para a alma, e saúde para os ossos.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há um caminho que parece direito ao homem, mas o seu fim são os caminhos da morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ O trabalhador trabalha para si mesmo, porque a sua boca o incita.

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem ímpio cava o mal, e nos seus lábios há como que uma fogueira.

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem perverso instiga a contenda, e o intrigante separa os maiores amigos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem violento coage o seu próximo, e o faz deslizar por caminhos nada bons.

[[v20-16-30]]

^<<v20-16-30,30>>^ O que fecha os olhos para imaginar coisas ruins, ao cerrar os lábios pratica o mal.

[[v20-16-31]]

^<<v20-16-31,31>>^ Coroa de honra são as cãs, quando elas estão no caminho da justiça.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o que tarda em irar-se do que o poderoso, e o que controla o seu ânimo do que aquele que toma uma cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte se lança no regaço, mas do Senhor procede toda a determinação.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]