include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-9-1]]

^<<v20-9-1,1>>^ A sabedoria já edificou a sua casa, já lavrou as suas sete colunas.

[[v20-9-2]]

^<<v20-9-2,2>>^ Já abateu os seus animais e misturou o seu vinho, e já preparou a sua mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ Já ordenou às suas criadas, e está convidando desde as alturas da cidade, dizendo:

[[v20-9-4]]

^<<v20-9-4,4>>^ Quem é simples, volte-se para cá. Aos faltos de senso diz:

[[v20-9-5]]

^<<v20-9-5,5>>^ Vinde, comei do meu pão, e bebei do vinho que tenho misturado.

[[v20-9-6]]

^<<v20-9-6,6>>^ Deixai os insensatos e vivei; e andai pelo caminho do entendimento.

[[v20-9-7]]

^<<v20-9-7,7>>^ O que repreende o escarnecedor, toma afronta para si; e o que censura o ímpio recebe a sua mancha.

[[v20-9-8]]

^<<v20-9-8,8>>^ Não repreendas o escarnecedor, para que não te odeie; repreende o sábio, e ele te amará.

[[v20-9-9]]

^<<v20-9-9,9>>^ Dá instrução ao sábio, e ele se fará mais sábio; ensina o justo e ele aumentará em entendimento.

[[v20-9-10]]

^<<v20-9-10,10>>^ O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo a prudência.

[[v20-9-11]]

^<<v20-9-11,11>>^ Porque por meu intermédio se multiplicam os teus dias, e anos de vida se te aumentarão.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se fores sábio, para ti serás sábio; e, se fores escarnecedor, só tu o suportarás.

[[v20-9-13]]

^<<v20-9-13,13>>^ A mulher louca é alvoroçadora; é simples e nada sabe.

[[v20-9-14]]

^<<v20-9-14,14>>^ Assenta-se à porta da sua casa numa cadeira, nas alturas da cidade,

[[v20-9-15]]

^<<v20-9-15,15>>^ E põe-se a chamar aos que vão pelo caminho, e que passam reto pelas veredas, dizendo:

[[v20-9-16]]

^<<v20-9-16,16>>^ Quem é simples, volte-se para cá. E aos faltos de entendimento ela diz:

[[v20-9-17]]

^<<v20-9-17,17>>^ As águas roubadas são doces, e o pão tomado às escondidas é agradável.

[[v20-9-18]]

^<<v20-9-18,18>>^ Mas não sabem que ali estão os mortos; os seus convidados estão nas profundezas do inferno.

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]