include::./index.adoc[]

[[v20-29-0]]
=== Provérbios, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-29-1]]

^<<v20-29-1,1>>^ O Homem que muitas vezes repreendido endurece a cerviz, de repente será destruído sem que haja remédio.

[[v20-29-2]]

^<<v20-29-2,2>>^ Quando os justos se engrandecem, o povo se alegra, mas quando o ímpio domina, o povo geme.

[[v20-29-3]]

^<<v20-29-3,3>>^ O homem que ama a sabedoria alegra a seu pai, mas o companheiro de prostitutas desperdiça os bens.

[[v20-29-4]]

^<<v20-29-4,4>>^ O rei com juízo sustém a terra, mas o amigo de peitas a transtorna.

[[v20-29-5]]

^<<v20-29-5,5>>^ O homem que lisonjeia o seu próximo arma uma rede aos seus passos.

[[v20-29-6]]

^<<v20-29-6,6>>^ Na transgressão do homem mau há laço, mas o justo jubila e se alegra.

[[v20-29-7]]

^<<v20-29-7,7>>^ O justo se informa da causa dos pobres, mas o ímpio nem sequer toma conhecimento.

[[v20-29-8]]

^<<v20-29-8,8>>^ Os homens escarnecedores alvoroçam a cidade, mas os sábios desviam a ira.

[[v20-29-9]]

^<<v20-29-9,9>>^ O homem sábio que pleiteia com o tolo, quer se zangue, quer se ria, não terá descanso.

[[v20-29-10]]

^<<v20-29-10,10>>^ Os homens sanguinários odeiam ao sincero, mas os justos procuram o seu bem.

[[v20-29-11]]

^<<v20-29-11,11>>^ O tolo revela todo o seu pensamento, mas o sábio o guarda até o fim.

[[v20-29-12]]

^<<v20-29-12,12>>^ O governador que dá atenção às palavras mentirosas, achará que todos os seus servos são ímpios.

[[v20-29-13]]

^<<v20-29-13,13>>^ O pobre e o usurário se encontram; o Senhor ilumina os olhos de ambos.

[[v20-29-14]]

^<<v20-29-14,14>>^ O rei que julga os pobres conforme a verdade firmará o seu trono para sempre.

[[v20-29-15]]

^<<v20-29-15,15>>^ A vara e a repreensão dão sabedoria, mas a criança entregue a si mesma, envergonha a sua mãe.

[[v20-29-16]]

^<<v20-29-16,16>>^ Quando os ímpios se multiplicam, multiplicam-se as transgressões, mas os justos verão a sua queda.

[[v20-29-17]]

^<<v20-29-17,17>>^ Castiga o teu filho, e te dará descanso; e dará delícias à tua alma.

[[v20-29-18]]

^<<v20-29-18,18>>^ Não havendo profecia, o povo perece; porém o que guarda a lei, esse é bem-aventurado.

[[v20-29-19]]

^<<v20-29-19,19>>^ O servo não se emendará com palavras, porque, ainda que entenda, todavia não atenderá.

[[v20-29-20]]

^<<v20-29-20,20>>^ Tens visto um homem precipitado no falar? Maior esperança há para um tolo do que para ele.

[[v20-29-21]]

^<<v20-29-21,21>>^ Quando alguém cria o seu servo com mimos desde a meninice, por fim ele tornar-se-á seu filho.

[[v20-29-22]]

^<<v20-29-22,22>>^ O homem irascível levanta contendas; e o furioso multiplica as transgressões.

[[v20-29-23]]

^<<v20-29-23,23>>^ A soberba do homem o abaterá, mas a honra sustentará o humilde de espírito.

[[v20-29-24]]

^<<v20-29-24,24>>^ O que tem parte com o ladrão odeia a sua própria alma; ouve maldições, e não o denuncia.

[[v20-29-25]]

^<<v20-29-25,25>>^ O temor do homem armará laços, mas o que confia no Senhor será posto em alto retiro.

[[v20-29-26]]

^<<v20-29-26,26>>^ Muitos buscam o favor do poderoso, mas o juízo de cada um vem do Senhor.

[[v20-29-27]]

^<<v20-29-27,27>>^ Abominação é, para os justos, o homem iníquo; mas abominação é, para o iníquo, o de retos caminhos.

'''

xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[Próximo Capítulo &#62;]