include::./index.adoc[]

[[v20-31-0]]
=== Provérbios, 31
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-31-1]]

^<<v20-31-1,1>>^ Palavras do rei Lemuel, a profecia que lhe ensinou a sua mãe.

[[v20-31-2]]

^<<v20-31-2,2>>^ Como, filho meu? e como, filho do meu ventre? e como, filho dos meus votos?

[[v20-31-3]]

^<<v20-31-3,3>>^ Não dês às mulheres a tua força, nem os teus caminhos ao que destrói os reis.

[[v20-31-4]]

^<<v20-31-4,4>>^ Não é próprio dos reis, ó Lemuel, não é próprio dos reis beber vinho, nem dos príncipes o desejar bebida forte;

[[v20-31-5]]

^<<v20-31-5,5>>^ Para que bebendo, se esqueçam da lei, e pervertam o direito de todos os aflitos.

[[v20-31-6]]

^<<v20-31-6,6>>^ Dai bebida forte ao que está prestes a perecer, e o vinho aos amargurados de espírito.

[[v20-31-7]]

^<<v20-31-7,7>>^ Que beba, e esqueça da sua pobreza, e da sua miséria não se lembre mais.

[[v20-31-8]]

^<<v20-31-8,8>>^ Abre a tua boca a favor do mudo, pela causa de todos que são designados à destruição.

[[v20-31-9]]

^<<v20-31-9,9>>^ Abre a tua boca; julga retamente; e faze justiça aos pobres e aos necessitados.

[[v20-31-10]]

^<<v20-31-10,10>>^ Mulher virtuosa quem a achará? O seu valor muito excede ao de rubis.

[[v20-31-11]]

^<<v20-31-11,11>>^ O coração do seu marido está nela confiado; assim ele não necessitará de despojo.

[[v20-31-12]]

^<<v20-31-12,12>>^ Ela só lhe faz bem, e não mal, todos os dias da sua vida.

[[v20-31-13]]

^<<v20-31-13,13>>^ Busca lã e linho, e trabalha de boa vontade com suas mãos.

[[v20-31-14]]

^<<v20-31-14,14>>^ Como o navio mercante, ela traz de longe o seu pão.

[[v20-31-15]]

^<<v20-31-15,15>>^ Levanta-se, mesmo à noite, para dar de comer aos da casa, e distribuir a tarefa das servas.

[[v20-31-16]]

^<<v20-31-16,16>>^ Examina uma propriedade e adquire-a; planta uma vinha com o fruto de suas mãos.

[[v20-31-17]]

^<<v20-31-17,17>>^ Cinge os seus lombos de força, e fortalece os seus braços.

[[v20-31-18]]

^<<v20-31-18,18>>^ Vê que é boa a sua mercadoria; e a sua lâmpada não se apaga de noite.

[[v20-31-19]]

^<<v20-31-19,19>>^ Estende as suas mãos ao fuso, e suas mãos pegam na roca.

[[v20-31-20]]

^<<v20-31-20,20>>^ Abre a sua mão ao pobre, e estende as suas mãos ao necessitado.

[[v20-31-21]]

^<<v20-31-21,21>>^ Não teme a neve na sua casa, porque toda a sua família está vestida de escarlata.

[[v20-31-22]]

^<<v20-31-22,22>>^ Faz para si cobertas de tapeçaria; seu vestido é de seda e de púrpura.

[[v20-31-23]]

^<<v20-31-23,23>>^ Seu marido é conhecido nas portas, e assenta-se entre os anciãos da terra.

[[v20-31-24]]

^<<v20-31-24,24>>^ Faz panos de linho fino e vende-os, e entrega cintos aos mercadores.

[[v20-31-25]]

^<<v20-31-25,25>>^ A força e a honra são seu vestido, e se alegrará com o dia futuro.

[[v20-31-26]]

^<<v20-31-26,26>>^ Abre a sua boca com sabedoria, e a lei da beneficência está na sua língua.

[[v20-31-27]]

^<<v20-31-27,27>>^ Está atenta ao andamento da casa, e não come o pão da preguiça.

[[v20-31-28]]

^<<v20-31-28,28>>^ Levantam-se seus filhos e chamam-na bem-aventurada; seu marido também, e ele a louva.

[[v20-31-29]]

^<<v20-31-29,29>>^ Muitas filhas têm procedido virtuosamente, mas tu és, de todas, a mais excelente!

[[v20-31-30]]

^<<v20-31-30,30>>^ Enganosa é a beleza e vã a formosura, mas a mulher que teme ao Senhor, essa sim será louvada.

[[v20-31-31]]

^<<v20-31-31,31>>^ Dai-lhe do fruto das suas mãos, e deixe o seu próprio trabalho louvá-la nas portas.

'''

xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[Próximo Capítulo &#62;]