include::./index.adoc[]

[[v20-25-0]]
=== Provérbios, 25
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-25-1]]

^<<v20-25-1,1>>^ Também estes são provérbios de Salomão, os quais transcreveram os homens de Ezequias, rei de Judá.

[[v20-25-2]]

^<<v20-25-2,2>>^ A glória de Deus está nas coisas encobertas; mas a honra dos reis, está em descobri-las.

[[v20-25-3]]

^<<v20-25-3,3>>^ Os céus, pela altura, e a terra, pela profundidade, assim o coração dos reis é insondável.

[[v20-25-4]]

^<<v20-25-4,4>>^ Tira da prata as escórias, e sairá vaso para o fundidor;

[[v20-25-5]]

^<<v20-25-5,5>>^ Tira o ímpio da presença do rei, e o seu trono se firmará na justiça.

[[v20-25-6]]

^<<v20-25-6,6>>^ Não te glories na presença do rei, nem te ponhas no lugar dos grandes;

[[v20-25-7]]

^<<v20-25-7,7>>^ Porque melhor é que te digam: Sobe aqui; do que seres humilhado diante do príncipe que os teus olhos já viram.

[[v20-25-8]]

^<<v20-25-8,8>>^ Não te precipites em litigar, para que depois, ao fim, fiques sem ação, quando teu próximo te puser em apuros.

[[v20-25-9]]

^<<v20-25-9,9>>^ Pleiteia a tua causa com o teu próximo, e não reveles o segredo a outrem,

[[v20-25-10]]

^<<v20-25-10,10>>^ Para que não te desonre o que o ouvir, e a tua infâmia não se aparte de ti.

[[v20-25-11]]

^<<v20-25-11,11>>^ Como maçãs de ouro em salvas de prata, assim é a palavra dita a seu tempo.

[[v20-25-12]]

^<<v20-25-12,12>>^ Como pendentes de ouro e gargantilhas de ouro fino, assim é o sábio repreensor para o ouvido atento.

[[v20-25-13]]

^<<v20-25-13,13>>^ Como o frio da neve no tempo da sega, assim é o mensageiro fiel para com os que o enviam; porque refresca a alma dos seus senhores.

[[v20-25-14]]

^<<v20-25-14,14>>^ Como nuvens e ventos que não trazem chuva, assim é o homem que se gaba falsamente de dádivas.

[[v20-25-15]]

^<<v20-25-15,15>>^ Pela longanimidade se persuade o príncipe, e a língua branda amolece até os ossos.

[[v20-25-16]]

^<<v20-25-16,16>>^ Achaste mel? come só o que te basta; para que porventura não te fartes dele, e o venhas a vomitar.

[[v20-25-17]]

^<<v20-25-17,17>>^ Não ponhas muito os pés na casa do teu próximo; para que se não enfade de ti, e passe a te odiar.

[[v20-25-18]]

^<<v20-25-18,18>>^ Martelo, espada e flecha aguda é o homem que profere falso testemunho contra o seu próximo.

[[v20-25-19]]

^<<v20-25-19,19>>^ Como dente quebrado, e pé desconjuntado, é a confiança no desleal, no tempo da angústia.

[[v20-25-20]]

^<<v20-25-20,20>>^ O que canta canções para o coração aflito é como aquele que despe a roupa num dia de frio, ou como o vinagre sobre salitre.

[[v20-25-21]]

^<<v20-25-21,21>>^ Se o teu inimigo tiver fome, dá-lhe pão para comer; e se tiver sede, dá-lhe água para beber;

[[v20-25-22]]

^<<v20-25-22,22>>^ Porque assim lhe amontoarás brasas sobre a cabeça; e o Senhor to retribuirá.

[[v20-25-23]]

^<<v20-25-23,23>>^ O vento norte afugenta a chuva, e a face irada, a língua fingida.

[[v20-25-24]]

^<<v20-25-24,24>>^ Melhor é morar só num canto de telhado do que com a mulher briguenta numa casa ampla.

[[v20-25-25]]

^<<v20-25-25,25>>^ Como água fresca para a alma cansada, tais são as boas novas vindas da terra distante.

[[v20-25-26]]

^<<v20-25-26,26>>^ Como fonte turvada, e manancial poluído, assim é o justo que cede diante do ímpio.

[[v20-25-27]]

^<<v20-25-27,27>>^ Comer mel demais não é bom; assim, a busca da própria glória não é glória.

[[v20-25-28]]

^<<v20-25-28,28>>^ Como a cidade derrubada, sem muro, assim é o homem que não pode conter o seu espírito.

'''

xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[&#60; Capítulo Anterior] | <<v20-25-0,Topo>> | xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[Próximo Capítulo &#62;]