include::./index.adoc[]

[[v20-2-0]]
=== Provérbios, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v20-2-1]]

^<<v20-2-1,1>>^ Filho meu, se aceitares as minhas palavras, e esconderes contigo os meus mandamentos,

[[v20-2-2]]

^<<v20-2-2,2>>^ Para fazeres o teu ouvido atento à sabedoria; e inclinares o teu coração ao entendimento;

[[v20-2-3]]

^<<v20-2-3,3>>^ Se clamares por conhecimento, e por inteligência alçares a tua voz,

[[v20-2-4]]

^<<v20-2-4,4>>^ Se como a prata a buscares e como a tesouros escondidos a procurares,

[[v20-2-5]]

^<<v20-2-5,5>>^ Então entenderás o temor do Senhor, e acharás o conhecimento de Deus.

[[v20-2-6]]

^<<v20-2-6,6>>^ Porque o Senhor dá a sabedoria; da sua boca é que vem o conhecimento e o entendimento.

[[v20-2-7]]

^<<v20-2-7,7>>^ Ele reserva a verdadeira sabedoria para os retos. Escudo é para os que caminham na sinceridade,

[[v20-2-8]]

^<<v20-2-8,8>>^ Para que guardem as veredas do juízo. Ele preservará o caminho dos seus santos.

[[v20-2-9]]

^<<v20-2-9,9>>^ Então entenderás a justiça, o juízo, a eqüidade e todas as boas veredas.

[[v20-2-10]]

^<<v20-2-10,10>>^ Pois quando a sabedoria entrar no teu coração, e o conhecimento for agradável à tua alma,

[[v20-2-11]]

^<<v20-2-11,11>>^ O bom siso te guardará e a inteligência te conservará;

[[v20-2-12]]

^<<v20-2-12,12>>^ Para te afastar do mau caminho, e do homem que fala coisas perversas;

[[v20-2-13]]

^<<v20-2-13,13>>^ Dos que deixam as veredas da retidão, para andarem pelos caminhos escusos;

[[v20-2-14]]

^<<v20-2-14,14>>^ Que se alegram de fazer mal, e folgam com as perversidades dos maus,

[[v20-2-15]]

^<<v20-2-15,15>>^ Cujas veredas são tortuosas e que se desviam nos seus caminhos;

[[v20-2-16]]

^<<v20-2-16,16>>^ Para te afastar da mulher estranha, sim da estranha que lisonjeia com suas palavras;

[[v20-2-17]]

^<<v20-2-17,17>>^ Que deixa o guia da sua mocidade e se esquece da aliança do seu Deus;

[[v20-2-18]]

^<<v20-2-18,18>>^ Porque a sua casa se inclina para a morte, e as suas veredas para os mortos.

[[v20-2-19]]

^<<v20-2-19,19>>^ Todos os que se dirigem a ela não voltarão e não atinarão com as veredas da vida.

[[v20-2-20]]

^<<v20-2-20,20>>^ Para andares pelos caminhos dos bons, e te conservares nas veredas dos justos.

[[v20-2-21]]

^<<v20-2-21,21>>^ Porque os retos habitarão a terra, e os íntegros permanecerão nela.

[[v20-2-22]]

^<<v20-2-22,22>>^ Mas os ímpios serão arrancados da terra, e os aleivosos serão dela exterminados.

'''

xref:020-proverbios/020-proverbios-001.adoc#v20-1-0[&#60; Capítulo Anterior] | <<v20-2-0,Topo>> | xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[Próximo Capítulo &#62;]