include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v17-9-1]]

^<<v17-9-1,1>>^ E, no duodécimo mês, que é o mês de Adar, no dia treze do mesmo mês em que chegou a palavra do rei e a sua ordem para se executar, no dia em que os inimigos dos judeus esperavam assenhorear-se deles, sucedeu o contrário, porque os judeus foram os que se assenhorearam dos que os odiavam.

[[v17-9-2]]

^<<v17-9-2,2>>^ Porque os judeus nas suas cidades, em todas as províncias do rei Assuero, se ajuntaram para pôr as mãos naqueles que procuravam o seu mal; e ninguém podia resistir-lhes, porque o medo deles caíra sobre todos aqueles povos.

[[v17-9-3]]

^<<v17-9-3,3>>^ E todos os líderes das províncias, e os sátrapas, e os governadores, e os que faziam a obra do rei, auxiliavam os judeus; porque tinha caído sobre eles o temor de Mardoqueu.

[[v17-9-4]]

^<<v17-9-4,4>>^ Porque Mardoqueu era grande na casa do rei, e a sua fama crescia por todas as províncias, porque o homem Mardoqueu ia sendo engrandecido.

[[v17-9-5]]

^<<v17-9-5,5>>^ Feriram, pois, os judeus a todos os seus inimigos, a golpes de espada, com matança e com destruição; e fizeram dos seus inimigos o que quiseram.

[[v17-9-6]]

^<<v17-9-6,6>>^ E na fortaleza de Susã os judeus mataram e destruíram quinhentos homens;

[[v17-9-7]]

^<<v17-9-7,7>>^ Como também a Parsandata, e a Dalfom e a Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ E a Porata, e a Adalia, e a Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ E a Farmasta, e a Arisai, e a Aridai, e a Vaisata; ú

[[v17-9-10]]

^<<v17-9-10,10>>^ Os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus, mataram, porém ao despojo não estenderam a sua mão.

[[v17-9-11]]

^<<v17-9-11,11>>^ No mesmo dia foi comunicado ao rei o número dos mortos na fortaleza de Susã.

[[v17-9-12]]

^<<v17-9-12,12>>^ E disse o rei à rainha Ester: Na fortaleza de Susã os judeus mataram e destruíram quinhentos homens, e os dez filhos de Hamã; nas mais províncias do rei que teriam feito? Qual é, pois, a tua petição? E dar-se-te-á. Ou qual é ainda o teu requerimento? E far-se-á.

[[v17-9-13]]

^<<v17-9-13,13>>^ Então disse Ester: Se bem parecer ao rei, conceda-se aos judeus que se acham em Susã que também façam amanhã conforme ao mandado de hoje; e pendurem numa forca os dez filhos de Hamã.

[[v17-9-14]]

^<<v17-9-14,14>>^ Então disse o rei que assim se fizesse; e publicou-se um edito em Susã, e enforcaram os dez filhos de Hamã.

[[v17-9-15]]

^<<v17-9-15,15>>^ E reuniram-se os judeus que se achavam em Susã também no dia catorze do mês de Adar, e mataram em Susã trezentos homens; porém ao despojo não estenderam a sua mão.

[[v17-9-16]]

^<<v17-9-16,16>>^ Também os demais judeus que se achavam nas províncias do rei se reuniram e se dispuseram em defesa das suas vidas, e tiveram descanso dos seus inimigos; e mataram dos seus inimigos setenta e cinco mil; porém ao despojo não estenderam a sua mão.

[[v17-9-17]]

^<<v17-9-17,17>>^ Sucedeu isto no dia treze do mês de Adar; e descansaram no dia catorze, e fizeram, daquele dia, dia de banquetes e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Também os judeus, que se achavam em Susã se ajuntaram nos dias treze e catorze do mesmo; e descansaram no dia quinze, e fizeram, daquele dia, dia de banquetes e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ Os judeus, porém, das aldeias, que habitavam nas vilas, fizeram do dia catorze do mês de Adar dia de alegria e de banquetes, e dia de folguedo, e de mandarem presentes uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ E Mardoqueu escreveu estas coisas, e enviou cartas a todos os judeus que se achavam em todas as províncias do rei Assuero, aos de perto, e aos de longe,

[[v17-9-21]]

^<<v17-9-21,21>>^ Ordenando-lhes que guardassem o dia catorze do mês de Adar, e o dia quinze do mesmo, todos os anos,

[[v17-9-22]]

^<<v17-9-22,22>>^ Como os dias em que os judeus tiveram repouso dos seus inimigos, e o mês que se lhes mudou de tristeza em alegria, e de luto em dia de festa, para que os fizessem dias de banquetes e de alegria, e de mandarem presentes uns aos outros, e dádivas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ E os judeus encarregaram-se de fazer o que já tinham começado, como também o que Mardoqueu lhes tinha escrito.

[[v17-9-24]]

^<<v17-9-24,24>>^ Porque Hamã, filho de Hamedata, o agagita, inimigo de todos os judeus, tinha intentado destruir os judeus, e tinha lançado Pur, isto é, a sorte, para os assolar e destruir.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas, vindo isto perante o rei, mandou ele por cartas que o mau intento que Hamã formara contra os judeus, se tornasse sobre a sua cabeça; pelo que penduraram a ele e a seus filhos numa forca.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso àqueles dias chamam Purim, do nome Pur; assim também por causa de todas as palavras daquela carta, e do que viram sobre isso, e do que lhes tinha sucedido,

[[v17-9-27]]

^<<v17-9-27,27>>^ Confirmaram os judeus, e tomaram sobre si, e sobre a sua descendência, e sobre todos os que se achegassem a eles, que não se deixaria de guardar estes dois dias conforme ao que se escrevera deles, e segundo o seu tempo determinado, todos os anos.

[[v17-9-28]]

^<<v17-9-28,28>>^ E que estes dias seriam lembrados e guardados em cada geração, família, província e cidade, e que esses dias de Purim não fossem revogados entre os judeus, e que a memória deles nunca teria fim entre os de sua descendência.

[[v17-9-29]]

^<<v17-9-29,29>>^ Então a rainha Ester, filha de Abiail, e Mardoqueu, o judeu, escreveram com toda autoridade uma segunda vez, para confirmar a carta a respeito de Purim.

[[v17-9-30]]

^<<v17-9-30,30>>^ E mandaram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras de paz e verdade.

[[v17-9-31]]

^<<v17-9-31,31>>^ Para confirmarem estes dias de Purim nos seus tempos determinados, como Mardoqueu, o judeu, e a rainha Ester lhes tinham estabelecido, e como eles mesmos já o tinham estabelecido sobre si e sobre a sua descendência, acerca do jejum e do seu clamor.

[[v17-9-32]]

^<<v17-9-32,32>>^ E o mandado de Ester estabeleceu os sucessos daquele Purim; e escreveu-se no livro.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]