include::./index.adoc[]

[[v17-4-0]]
=== Ester, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v17-4-1]]

^<<v17-4-1,1>>^ Quando Mardoqueu soube tudo quanto se havia passado, rasgou as suas vestes, e vestiu-se de saco e de cinza, e saiu pelo meio da cidade, e clamou com grande e amargo clamor;

[[v17-4-2]]

^<<v17-4-2,2>>^ E chegou até diante da porta do rei, porque ninguém vestido de saco podia entrar pelas portas do rei.

[[v17-4-3]]

^<<v17-4-3,3>>^ E em todas as províncias aonde a palavra do rei e a sua lei chegava, havia entre os judeus grande luto, com jejum, e choro, e lamentação; e muitos estavam deitados em saco e em cinza.

[[v17-4-4]]

^<<v17-4-4,4>>^ Então vieram as servas de Ester, e os seus camareiros, e fizeram-na saber, do que a rainha muito se doeu; e mandou roupas para vestir a Mardoqueu, e tirar-lhe o pano de saco; porém ele não as aceitou.

[[v17-4-5]]

^<<v17-4-5,5>>^ Então Ester chamou a Hatá (um dos camareiros do rei, que este tinha posto para servi-la), e deu-lhe ordem para ir a Mardoqueu, para saber que era aquilo, e porquê.

[[v17-4-6]]

^<<v17-4-6,6>>^ E, saindo Hatá a Mardoqueu, à praça da cidade, que estava diante da porta do rei,

[[v17-4-7]]

^<<v17-4-7,7>>^ Mardoqueu lhe fez saber tudo quanto lhe tinha sucedido; como também a soma exata do dinheiro, que Hamã dissera que daria para os tesouros do rei, pelos judeus, para destruí-los.

[[v17-4-8]]

^<<v17-4-8,8>>^ Também lhe deu a cópia da lei escrita, que se publicara em Susã, para os destruir, para que a mostrasse a Ester, e a fizesse saber; e para lhe ordenar que fosse ter com o rei, e lhe pedisse e suplicasse na sua presença pelo seu povo.

[[v17-4-9]]

^<<v17-4-9,9>>^ Veio, pois, Hatá, e fez saber a Ester as palavras de Mardoqueu.

[[v17-4-10]]

^<<v17-4-10,10>>^ Então falou Ester a Hatá, mandando-o dizer a Mardoqueu:

[[v17-4-11]]

^<<v17-4-11,11>>^ Todos os servos do rei, e o povo das províncias do rei, bem sabem que todo o homem ou mulher que chegar ao rei no pátio interior, sem ser chamado, não há senão uma sentença, a de morte, salvo se o rei estender para ele o cetro de ouro, para que viva; e eu nestes trinta dias não tenho sido chamada para ir ao rei.

[[v17-4-12]]

^<<v17-4-12,12>>^ E fizeram saber a Mardoqueu as palavras de Ester.

[[v17-4-13]]

^<<v17-4-13,13>>^ Então Mardoqueu mandou que respondessem a Ester: Não imagines no teu íntimo que, por estares na casa do rei, escaparás só tu entre todos os judeus.

[[v17-4-14]]

^<<v17-4-14,14>>^ Porque, se de todo te calares neste tempo, socorro e livramento de outra parte sairá para os judeus, mas tu e a casa de teu pai perecereis; e quem sabe se para tal tempo como este chegaste a este reino?

[[v17-4-15]]

^<<v17-4-15,15>>^ Então disse Ester que tornassem a dizer a Mardoqueu:

[[v17-4-16]]

^<<v17-4-16,16>>^ Vai, ajunta a todos os judeus que se acharem em Susã, e jejuai por mim, e não comais nem bebais por três dias, nem de dia nem de noite, e eu e as minhas servas também assim jejuaremos. E assim irei ter com o rei, ainda que não seja segundo a lei; e se perecer, pereci.

[[v17-4-17]]

^<<v17-4-17,17>>^ Então Mardoqueu foi, e fez conforme a tudo quanto Ester lhe ordenou.

'''

xref:017-ester/017-ester-003.adoc#v17-3-0[&#60; Capítulo Anterior] | <<v17-4-0,Topo>> | xref:017-ester/017-ester-005.adoc#v17-5-0[Próximo Capítulo &#62;]