include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-25-1]]

^<<v3-25-1,1>>^ Falou mais o SENHOR a Moisés no monte Sinai, dizendo:

[[v3-25-2]]

^<<v3-25-2,2>>^ Fala aos filhos de Israel, e dize-lhes: Quando tiverdes entrado na terra, que eu vos dou, então a terra descansará um sábado ao Senhor.

[[v3-25-3]]

^<<v3-25-3,3>>^ Seis anos semearás a tua terra, e seis anos podarás a tua vinha, e colherás os seus frutos;

[[v3-25-4]]

^<<v3-25-4,4>>^ Porém ao sétimo ano haverá sábado de descanso para a terra, um sábado ao Senhor; não semearás o teu campo nem podarás a tua vinha.

[[v3-25-5]]

^<<v3-25-5,5>>^ O que nascer de si mesmo da tua sega, não colherás, e as uvas da tua separação não vindimarás; ano de descanso será para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ Mas os frutos do sábado da terra vos serão por alimento, a ti, e ao teu servo, e à tua serva, e ao teu diarista, e ao estrangeiro que peregrina contigo;

[[v3-25-7]]

^<<v3-25-7,7>>^ E ao teu gado, e aos teus animais, que estão na tua terra, todo o seu produto será por mantimento.

[[v3-25-8]]

^<<v3-25-8,8>>^ Também contarás sete semanas de anos, sete vezes sete anos; de maneira que os dias das sete semanas de anos te serão quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então no mês sétimo, aos dez do mês, farás passar a trombeta do jubileu; no dia da expiação fareis passar a trombeta por toda a vossa terra,

[[v3-25-10]]

^<<v3-25-10,10>>^ E santificareis o ano qüinquagésimo, e apregoareis liberdade na terra a todos os seus moradores; ano de jubileu vos será, e tornareis, cada um à sua possessão, e cada um à sua família.

[[v3-25-11]]

^<<v3-25-11,11>>^ O ano qüinquagésimo vos será jubileu; não semeareis nem colhereis o que nele nascer de si mesmo, nem nele vindimareis as uvas das separações,

[[v3-25-12]]

^<<v3-25-12,12>>^ Porque jubileu é, santo será para vós; a novidade do campo comereis.

[[v3-25-13]]

^<<v3-25-13,13>>^ Neste ano do jubileu tornareis cada um à sua possessão.

[[v3-25-14]]

^<<v3-25-14,14>>^ E quando venderdes alguma coisa ao vosso próximo, ou a comprardes da mão do vosso próximo, ninguém engane a seu irmão;

[[v3-25-15]]

^<<v3-25-15,15>>^ Conforme ao número dos anos, desde o jubileu, comprarás ao teu próximo; e conforme o número dos anos das colheitas, ele a venderá a ti.

[[v3-25-16]]

^<<v3-25-16,16>>^ Conforme se multipliquem os anos, aumentarás o seu preço, e conforme à diminuição dos anos abaixarás o seu preço; porque conforme o número das colheitas é que ele te vende.

[[v3-25-17]]

^<<v3-25-17,17>>^ Ninguém, pois, engane ao seu próximo; mas terás temor do teu Deus; porque eu sou o Senhor vosso Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ E observareis os meus estatutos, e guardareis os meus juízos, e os cumprireis; assim habitareis seguros na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ E a terra dará o seu fruto, e comereis a fartar, e nela habitareis seguros.

[[v3-25-20]]

^<<v3-25-20,20>>^ E se disserdes: Que comeremos no ano sétimo? eis que não havemos de semear nem fazer a nossa colheita;

[[v3-25-21]]

^<<v3-25-21,21>>^ Então eu mandarei a minha bênção sobre vós no sexto ano, para que dê fruto por três anos,

[[v3-25-22]]

^<<v3-25-22,22>>^ E no oitavo ano semeareis, e comereis da colheita velha até ao ano nono; até que venha a nova colheita, comereis a velha.

[[v3-25-23]]

^<<v3-25-23,23>>^ Também a terra não se venderá em perpetuidade, porque a terra é minha; pois vós sois estrangeiros e peregrinos comigo.

[[v3-25-24]]

^<<v3-25-24,24>>^ Portanto em toda a terra da vossa possessão dareis resgate à terra.

[[v3-25-25]]

^<<v3-25-25,25>>^ Quando teu irmão empobrecer e vender alguma parte da sua possessão, então virá o seu resgatador, seu parente, e resgatará o que vendeu seu irmão.

[[v3-25-26]]

^<<v3-25-26,26>>^ E se alguém não tiver resgatador, porém conseguir o suficiente para o seu resgate,

[[v3-25-27]]

^<<v3-25-27,27>>^ Então contará os anos desde a sua venda, e o que ficar restituirá ao homem a quem a vendeu, e tornará à sua possessão.

[[v3-25-28]]

^<<v3-25-28,28>>^ Mas se não conseguir o suficiente para restituir-lha, então a que foi vendida ficará na mão do comprador até ao ano do jubileu; porém no ano do jubileu sairá, e ele tornará à sua possessão.

[[v3-25-29]]

^<<v3-25-29,29>>^ E, quando alguém vender uma casa de moradia em cidade murada, então poderá resgatá-la até que se cumpra o ano da sua venda; durante um ano inteiro será lícito o seu resgate.

[[v3-25-30]]

^<<v3-25-30,30>>^ Mas, se, cumprindo-se-lhe um ano inteiro, ainda não for resgatada, então a casa, que estiver na cidade que tem muro, em perpetuidade ficará ao que a comprou, pelas suas gerações; não sairá no jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Mas as casas das aldeias que não têm muro ao redor, serão estimadas como o campo da terra; para elas haverá resgate, e sairão no jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ Mas, no tocante às cidades dos levitas, às casas das cidades da sua possessão, direito perpétuo de resgate terão os levitas.

[[v3-25-33]]

^<<v3-25-33,33>>^ E se alguém comprar dos levitas, uma casa, a casa comprada e a cidade da sua possessão sairão do poder do comprador no jubileu; porque as casas das cidades dos levitas são a sua possessão no meio dos filhos de Israel.

[[v3-25-34]]

^<<v3-25-34,34>>^ Mas o campo do arrabalde das suas cidades não se venderá, porque lhes é possessão perpétua.

[[v3-25-35]]

^<<v3-25-35,35>>^ E, quando teu irmão empobrecer, e as suas forças decaírem, então sustentá-lo-ás, como estrangeiro e peregrino viverá contigo.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não tomarás dele juros, nem ganho; mas do teu Deus terás temor, para que teu irmão viva contigo.

[[v3-25-37]]

^<<v3-25-37,37>>^ Não lhe darás teu dinheiro com usura, nem darás do teu alimento por interesse.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o Senhor vosso Deus, que vos tirei da terra do Egito, para vos dar a terra de Canaã, para ser vosso Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ Quando também teu irmão empobrecer, estando ele contigo, e vender-se a ti, não o farás servir como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Como diarista, como peregrino estará contigo; até ao ano do jubileu te servirá;

[[v3-25-41]]

^<<v3-25-41,41>>^ Então sairá do teu serviço, ele e seus filhos com ele, e tornará à sua família e à possessão de seus pais.

[[v3-25-42]]

^<<v3-25-42,42>>^ Porque são meus servos, que tirei da terra do Egito; não serão vendidos como se vendem os escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não te assenhorearás dele com rigor, mas do teu Deus terás temor.

[[v3-25-44]]

^<<v3-25-44,44>>^ E quanto a teu escravo ou a tua escrava que tiveres, serão das nações que estão ao redor de vós; deles comprareis escravos e escravas.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também os comprareis dos filhos dos forasteiros que peregrinam entre vós, deles e das suas famílias que estiverem convosco, que tiverem gerado na vossa terra; e vos serão por possessão.

[[v3-25-46]]

^<<v3-25-46,46>>^ E possuí-los-eis por herança para vossos filhos depois de vós, para herdarem a possessão; perpetuamente os fareis servir; mas sobre vossos irmãos, os filhos de Israel, não vos assenhoreareis com rigor, uns sobre os outros.

[[v3-25-47]]

^<<v3-25-47,47>>^ E se o estrangeiro ou peregrino que está contigo alcançar riqueza, e teu irmão, que está com ele, empobrecer, e vender-se ao estrangeiro ou peregrino que está contigo, ou a alguém da família do estrangeiro,

[[v3-25-48]]

^<<v3-25-48,48>>^ Depois que se houver vendido, haverá resgate para ele; um de seus irmãos o poderá resgatar;

[[v3-25-49]]

^<<v3-25-49,49>>^ Ou seu tio, ou o filho de seu tio o poderá resgatar; ou um dos seus parentes, da sua família, o poderá resgatar; ou, se alcançar riqueza, se resgatará a si mesmo.

[[v3-25-50]]

^<<v3-25-50,50>>^ E acertará com aquele que o comprou, desde o ano que se vendeu a ele até ao ano do jubileu, e o preço da sua venda será conforme o número dos anos; conforme os dias de um diarista estará com ele.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se ainda faltarem muitos anos, conforme a eles restituirá, para seu resgate, parte do dinheiro pelo qual foi vendido,

[[v3-25-52]]

^<<v3-25-52,52>>^ E se ainda restarem poucos anos até ao ano do jubileu, então fará contas com ele; segundo os seus anos restituirá o seu resgate.

[[v3-25-53]]

^<<v3-25-53,53>>^ Como diarista, de ano em ano, estará com ele; não se assenhoreará sobre ele com rigor diante dos teus olhos.

[[v3-25-54]]

^<<v3-25-54,54>>^ E, se desta sorte não se resgatar, sairá no ano do jubileu, ele e seus filhos com ele.

[[v3-25-55]]

^<<v3-25-55,55>>^ Porque os filhos de Israel me são servos; meus servos são eles, que tirei da terra do Egito. Eu sou o Senhor vosso Deus.

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]