include::./index.adoc[]

[[v3-17-0]]
=== Levítico, 17
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-17-1]]

^<<v3-17-1,1>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-17-2]]

^<<v3-17-2,2>>^ Fala a Arão e aos seus filhos, e a todos os filhos de Israel, e dize-lhes: Esta é a palavra que o Senhor ordenou, dizendo:

[[v3-17-3]]

^<<v3-17-3,3>>^ Qualquer homem da casa de Israel que degolar boi, ou cordeiro, ou cabra, no arraial, ou quem os degolar fora do arraial,

[[v3-17-4]]

^<<v3-17-4,4>>^ E não os trouxer à porta da tenda da congregação, para oferecer oferta ao Senhor diante do tabernáculo do Senhor, a esse homem será imputado o sangue; derramou sangue; por isso será extirpado do seu povo;

[[v3-17-5]]

^<<v3-17-5,5>>^ Para que os filhos de Israel, trazendo os seus sacrifícios, que oferecem sobre a face do campo, os tragam ao Senhor, à porta da tenda da congregação, ao sacerdote, e os ofereçam por sacrifícios pacíficos ao Senhor.

[[v3-17-6]]

^<<v3-17-6,6>>^ E o sacerdote espargirá o sangue sobre o altar do Senhor, à porta da tenda da congregação, e queimará a gordura por cheiro suave ao Senhor.

[[v3-17-7]]

^<<v3-17-7,7>>^ E nunca mais oferecerão os seus sacrifícios aos demônios, após os quais eles se prostituem; isto ser-lhes-á por estatuto perpétuo nas suas gerações.

[[v3-17-8]]

^<<v3-17-8,8>>^ Dize-lhes, pois: Qualquer homem da casa de Israel, ou dos estrangeiros que peregrinam entre vós, que oferecer holocausto ou sacrifício,

[[v3-17-9]]

^<<v3-17-9,9>>^ E não o trouxer à porta da tenda da congregação, para oferecê-lo ao Senhor, esse homem será extirpado do seu povo.

[[v3-17-10]]

^<<v3-17-10,10>>^ E qualquer homem da casa de Israel, ou dos estrangeiros que peregrinam entre eles, que comer algum sangue, contra aquela alma porei a minha face, e a extirparei do seu povo.

[[v3-17-11]]

^<<v3-17-11,11>>^ Porque a vida da carne está no sangue; pelo que vo-lo tenho dado sobre o altar, para fazer expiação pelas vossas almas; porquanto é o sangue que fará expiação pela alma.

[[v3-17-12]]

^<<v3-17-12,12>>^ Portanto tenho dito aos filhos de Israel: Nenhum dentre vós comerá sangue, nem o estrangeiro, que peregrine entre vós, comerá sangue.

[[v3-17-13]]

^<<v3-17-13,13>>^ Também qualquer homem dos filhos de Israel, ou dos estrangeiros que peregrinam entre eles, que caçar animal ou ave que se come, derramará o seu sangue, e o cobrirá com pó;

[[v3-17-14]]

^<<v3-17-14,14>>^ Porquanto a vida de toda a carne é o seu sangue; por isso tenho dito aos filhos de Israel: Não comereis o sangue de nenhuma carne, porque a vida de toda a carne é o seu sangue; qualquer que o comer será extirpado.

[[v3-17-15]]

^<<v3-17-15,15>>^ E todo o homem entre os naturais, ou entre os estrangeiros, que comer corpo morto ou dilacerado, lavará as suas vestes, e se banhará com água, e será imundo até à tarde; depois será limpo.

[[v3-17-16]]

^<<v3-17-16,16>>^ Mas, se os não lavar, nem banhar a sua carne, levará sobre si a sua iniqüidade.

'''

xref:003-levitico/003-levitico-016.adoc#v3-16-0[&#60; Capítulo Anterior] | <<v3-17-0,Topo>> | xref:003-levitico/003-levitico-018.adoc#v3-18-0[Próximo Capítulo &#62;]