include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-11-1]]

^<<v3-11-1,1>>^ E falou o SENHOR a Moisés e a Arão, dizendo-lhes:

[[v3-11-2]]

^<<v3-11-2,2>>^ Fala aos filhos de Israel, dizendo: Estes são os animais, que comereis dentre todos os animais que há sobre a terra;

[[v3-11-3]]

^<<v3-11-3,3>>^ Dentre os animais, todo o que tem unhas fendidas, e a fenda das unhas se divide em duas, e rumina, deles comereis.

[[v3-11-4]]

^<<v3-11-4,4>>^ Destes, porém, não comereis; dos que ruminam ou dos que têm unhas fendidas; o camelo, que rumina, mas não tem unhas fendidas; esse vos será imundo;

[[v3-11-5]]

^<<v3-11-5,5>>^ E o coelho, porque rumina, mas não tem as unhas fendidas; esse vos será imundo;

[[v3-11-6]]

^<<v3-11-6,6>>^ E a lebre, porque rumina, mas não tem as unhas fendidas; essa vos será imunda.

[[v3-11-7]]

^<<v3-11-7,7>>^ Também o porco, porque tem unhas fendidas, e a fenda das unhas se divide em duas, mas não rumina; este vos será imundo.

[[v3-11-8]]

^<<v3-11-8,8>>^ Das suas carnes não comereis, nem tocareis nos seus cadáveres; estes vos serão imundos.

[[v3-11-9]]

^<<v3-11-9,9>>^ De todos os animais que há nas águas, comereis os seguintes: todo o que tem barbatanas e escamas, nas águas, nos mares e nos rios, esses comereis.

[[v3-11-10]]

^<<v3-11-10,10>>^ Mas todo o que não tem barbatanas, nem escamas, nos mares e nos rios, todo o réptil das águas, e todo o ser vivente que há nas águas, estes serão para vós abominação.

[[v3-11-11]]

^<<v3-11-11,11>>^ Ser-vos-ão, pois, por abominação; da sua carne não comereis, e abominareis o seu cadáver.

[[v3-11-12]]

^<<v3-11-12,12>>^ Todo o que não tem barbatanas ou escamas, nas águas, será para vós abominação.

[[v3-11-13]]

^<<v3-11-13,13>>^ Das aves, estas abominareis; não se comerão, serão abominação: a águia, e o quebrantosso, e o xofrango,

[[v3-11-14]]

^<<v3-11-14,14>>^ E o milhano, e o abutre segundo a sua espécie.

[[v3-11-15]]

^<<v3-11-15,15>>^ Todo o corvo segundo a sua espécie,

[[v3-11-16]]

^<<v3-11-16,16>>^ E o avestruz, e o mocho, e a gaivota, e o gavião segundo a sua espécie.

[[v3-11-17]]

^<<v3-11-17,17>>^ E o bufo, e o corvo marinho, e a coruja,

[[v3-11-18]]

^<<v3-11-18,18>>^ E a gralha, e o cisne, e o pelicano,

[[v3-11-19]]

^<<v3-11-19,19>>^ E a cegonha, a garça segundo a sua espécie, e a poupa, e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ Todo o inseto que voa, que anda sobre quatro pés, será para vós uma abominação.

[[v3-11-21]]

^<<v3-11-21,21>>^ Mas isto comereis de todo o inseto que voa, que anda sobre quatro pés: o que tiver pernas sobre os seus pés, para saltar com elas sobre a terra.

[[v3-11-22]]

^<<v3-11-22,22>>^ Deles comereis estes: a locusta segundo a sua espécie, o gafanhoto devorador segundo a sua espécie, o grilo segundo a sua espécie, e o gafanhoto segundo a sua espécie.

[[v3-11-23]]

^<<v3-11-23,23>>^ E todos os outros insetos que voam, que têm quatro pés, serão para vós uma abominação.

[[v3-11-24]]

^<<v3-11-24,24>>^ E por estes sereis imundos: qualquer que tocar os seus cadáveres, imundo será até à tarde.

[[v3-11-25]]

^<<v3-11-25,25>>^ Qualquer que levar os seus cadáveres lavará as suas vestes, e será imundo até à tarde.

[[v3-11-26]]

^<<v3-11-26,26>>^ Todo o animal que tem unha fendida, mas a fenda não se divide em duas, e todo o que não rumina, vos será por imundo; qualquer que tocar neles será imundo.

[[v3-11-27]]

^<<v3-11-27,27>>^ E todo o animal que anda sobre as suas patas, todo o animal que anda a quatro pés, vos será por imundo; qualquer que tocar nos seus cadáveres será imundo até à tarde.

[[v3-11-28]]

^<<v3-11-28,28>>^ E o que levar os seus cadáveres lavará as suas vestes, e será imundo até à tarde; eles vos serão por imundos.

[[v3-11-29]]

^<<v3-11-29,29>>^ Estes também vos serão por imundos entre os répteis que se arrastam sobre a terra; a doninha, e o rato, e a tartaruga segundo a sua espécie,

[[v3-11-30]]

^<<v3-11-30,30>>^ E o ouriço cacheiro, e o lagarto, e a lagartixa, e a lesma e a toupeira.

[[v3-11-31]]

^<<v3-11-31,31>>^ Estes vos serão por imundos dentre todos os répteis; qualquer que os tocar, estando eles mortos, será imundo até à tarde.

[[v3-11-32]]

^<<v3-11-32,32>>^ E tudo aquilo sobre o que cair alguma coisa deles estando eles mortos será imundo; seja vaso de madeira, ou veste, ou pele, ou saco, qualquer instrumento, com que se faz alguma obra, será posto na água, e será imundo até à tarde; depois será limpo.

[[v3-11-33]]

^<<v3-11-33,33>>^ E todo o vaso de barro, em que cair alguma coisa deles, tudo o que houver nele será imundo, e o vaso quebrareis.

[[v3-11-34]]

^<<v3-11-34,34>>^ Todo o alimento que se come, sobre o qual cair água de tais vasos, será imundo; e toda a bebida que se bebe, depositada nesses vasos, será imunda.

[[v3-11-35]]

^<<v3-11-35,35>>^ E aquilo sobre o que cair alguma parte de seu corpo morto, será imundo; o forno e o vaso de barro serão quebrados; imundos são: portanto vos serão por imundos.

[[v3-11-36]]

^<<v3-11-36,36>>^ Porém a fonte ou cisterna, em que se recolhem águas, será limpa, mas quem tocar no seu cadáver será imundo.

[[v3-11-37]]

^<<v3-11-37,37>>^ E, se dos seus cadáveres cair alguma coisa sobre alguma semente que se vai semear, será limpa;

[[v3-11-38]]

^<<v3-11-38,38>>^ Mas se for deitada água sobre a semente, e se dos seus cadáveres cair alguma coisa sobre ela, vos será por imunda.

[[v3-11-39]]

^<<v3-11-39,39>>^ E se morrer algum dos animais, que vos servem de mantimento, quem tocar no seu cadáver será imundo até à tarde;

[[v3-11-40]]

^<<v3-11-40,40>>^ E quem comer do seu cadáver lavará as suas vestes, e será imundo até à tarde; e quem levar o seu corpo morto lavará as suas vestes, e será imundo até à tarde.

[[v3-11-41]]

^<<v3-11-41,41>>^ Também todo o réptil, que se arrasta sobre a terra, será abominação; não se comerá.

[[v3-11-42]]

^<<v3-11-42,42>>^ Tudo o que anda sobre o ventre, e tudo o que anda sobre quatro pés, ou que tem muitos pés, entre todo o réptil que se arrasta sobre a terra, não comereis, porquanto são uma abominação.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não vos façais abomináveis, por nenhum réptil que se arrasta, nem neles vos contamineis, para não serdes imundos por eles;

[[v3-11-44]]

^<<v3-11-44,44>>^ Porque eu sou o Senhor vosso Deus; portanto vós vos santificareis, e sereis santos, porque eu sou santo; e não vos contaminareis com nenhum réptil que se arrasta sobre a terra;

[[v3-11-45]]

^<<v3-11-45,45>>^ Porque eu sou o Senhor, que vos fiz subir da terra do Egito, para que eu seja vosso Deus, e para que sejais santos; porque eu sou santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ Esta é a lei dos animais, e das aves, e de toda criatura vivente que se move nas águas, e de toda criatura que se arrasta sobre a terra;

[[v3-11-47]]

^<<v3-11-47,47>>^ Para fazer diferença entre o imundo e o limpo; e entre animais que se podem comer e os animais que não se podem comer.

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]