include::./index.adoc[]

[[v3-5-0]]
=== Levítico, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-5-1]]

^<<v3-5-1,1>>^ E quando alguma pessoa pecar, ouvindo uma voz de blasfêmia, de que for testemunha, seja porque viu, ou porque soube, se o não denunciar, então levará a sua iniqüidade.

[[v3-5-2]]

^<<v3-5-2,2>>^ Ou, quando alguma pessoa tocar em alguma coisa imunda, seja corpo morto de fera imunda, seja corpo morto de animal imundo, seja corpo morto de réptil imundo, ainda que não soubesse, contudo será ele imundo e culpado.

[[v3-5-3]]

^<<v3-5-3,3>>^ Ou, quando tocar a imundícia de um homem, seja qualquer que for a sua imundícia, com que se faça imundo, e lhe for oculto, e o souber depois, será culpado.

[[v3-5-4]]

^<<v3-5-4,4>>^ Ou, quando alguma pessoa jurar, pronunciando temerariamente com os seus lábios, para fazer mal, ou para fazer bem, em tudo o que o homem pronuncia temerariamente com juramento, e lhe for oculto, e o souber depois, culpado será numa destas coisas.

[[v3-5-5]]

^<<v3-5-5,5>>^ Será, pois, que, culpado sendo numa destas coisas, confessará aquilo em que pecou.

[[v3-5-6]]

^<<v3-5-6,6>>^ E a sua expiação trará ao Senhor, pelo seu pecado que cometeu: uma fêmea de gado miúdo, uma cordeira, ou uma cabrinha pelo pecado; assim o sacerdote por ela fará expiação do seu pecado.

[[v3-5-7]]

^<<v3-5-7,7>>^ Mas, se em sua mão não houver recurso para gado miúdo, então trará, para expiação da culpa que cometeu, ao Senhor, duas rolas ou dois pombinhos; um para expiação do pecado, e o outro para holocausto;

[[v3-5-8]]

^<<v3-5-8,8>>^ E os trará ao sacerdote, o qual primeiro oferecerá aquele que é para expiação do pecado; e com a sua unha lhe fenderá a cabeça junto ao pescoço, mas não o partirá;

[[v3-5-9]]

^<<v3-5-9,9>>^ E do sangue da expiação do pecado espargirá sobre a parede do altar, porém o que sobejar daquele sangue espremer-se-á à base do altar; expiação do pecado é.

[[v3-5-10]]

^<<v3-5-10,10>>^ E do outro fará holocausto conforme ao costume; assim o sacerdote por ela fará expiação do seu pecado que cometeu, e ele será perdoado.

[[v3-5-11]]

^<<v3-5-11,11>>^ Porém, se em sua mão não houver recurso para duas rolas, ou dois pombinhos, então aquele que pecou trará como oferta a décima parte de um efa de flor de farinha, para expiação do pecado; não deitará sobre ela azeite nem lhe porá em cima o incenso, porquanto é expiação do pecado;

[[v3-5-12]]

^<<v3-5-12,12>>^ E a trará ao sacerdote, e o sacerdote dela tomará a sua mão cheia pelo seu memorial, e a queimará sobre o altar, em cima das ofertas queimadas do Senhor; expiação de pecado é.

[[v3-5-13]]

^<<v3-5-13,13>>^ Assim o sacerdote por ela fará expiação do seu pecado, que cometeu em alguma destas coisas, e lhe será perdoado; e o restante será do sacerdote, como a oferta de alimentos.

[[v3-5-14]]

^<<v3-5-14,14>>^ E falou o Senhor a Moisés, dizendo:

[[v3-5-15]]

^<<v3-5-15,15>>^ Quando alguma pessoa cometer uma transgressão, e pecar por ignorância nas coisas sagradas do Senhor, então trará ao Senhor pela expiação, um carneiro sem defeito do rebanho, conforme à tua estimação em siclos de prata, segundo o siclo do santuário, para expiação da culpa.

[[v3-5-16]]

^<<v3-5-16,16>>^ Assim restituirá o que pecar nas coisas sagradas, e ainda lhe acrescentará a quinta parte, e a dará ao sacerdote; assim o sacerdote, com o carneiro da expiação, fará expiação por ele, e ser-lhe-á perdoado o pecado.

[[v3-5-17]]

^<<v3-5-17,17>>^ E, se alguma pessoa pecar, e fizer, contra algum dos mandamentos do Senhor, aquilo que não se deve fazer, ainda que o não soubesse, contudo será ela culpada, e levará a sua iniqüidade;

[[v3-5-18]]

^<<v3-5-18,18>>^ E trará ao sacerdote um carneiro sem defeito do rebanho, conforme à tua estimação, para expiação da culpa, e o sacerdote por ela fará expiação do erro que cometeu sem saber; e ser-lhe-á perdoado.

[[v3-5-19]]

^<<v3-5-19,19>>^ Expiação de culpa é; certamente se fez culpado diante do Senhor.

'''

xref:003-levitico/003-levitico-004.adoc#v3-4-0[&#60; Capítulo Anterior] | <<v3-5-0,Topo>> | xref:003-levitico/003-levitico-006.adoc#v3-6-0[Próximo Capítulo &#62;]