include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-12-1]]

^<<v3-12-1,1>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-12-2]]

^<<v3-12-2,2>>^ Fala aos filhos de Israel, dizendo: Se uma mulher conceber e der à luz um menino, será imunda sete dias, assim como nos dias da separação da sua enfermidade, será imunda.

[[v3-12-3]]

^<<v3-12-3,3>>^ E no dia oitavo se circuncidará ao menino a carne do seu prepúcio.

[[v3-12-4]]

^<<v3-12-4,4>>^ Depois ficará ela trinta e três dias no sangue da sua purificação; nenhuma coisa santa tocará e não entrará no santuário até que se cumpram os dias da sua purificação.

[[v3-12-5]]

^<<v3-12-5,5>>^ Mas, se der à luz uma menina será imunda duas semanas, como na sua separação; depois ficará sessenta e seis dias no sangue da sua purificação.

[[v3-12-6]]

^<<v3-12-6,6>>^ E, quando forem cumpridos os dias da sua purificação por filho ou por filha, trará um cordeiro de um ano por holocausto, e um pombinho ou uma rola para expiação do pecado, diante da porta da tenda da congregação, ao sacerdote.

[[v3-12-7]]

^<<v3-12-7,7>>^ O qual o oferecerá perante o Senhor, e por ela fará propiciação; e será limpa do fluxo do seu sangue; esta é a lei da que der à luz menino ou menina.

[[v3-12-8]]

^<<v3-12-8,8>>^ Mas, se em sua mão não houver recursos para um cordeiro, então tomará duas rolas, ou dois pombinhos, um para o holocausto e outro para a propiciação do pecado; assim o sacerdote por ela fará expiação, e será limpa.

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]