include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-9-1]]

^<<v3-9-1,1>>^ E aconteceu, ao dia oitavo, que Moisés chamou a Arão e seus filhos, e os anciãos de Israel,

[[v3-9-2]]

^<<v3-9-2,2>>^ E disse a Arão: Toma um bezerro, para expiação do pecado, e um carneiro para holocausto, sem defeito; e traze-os perante o Senhor.

[[v3-9-3]]

^<<v3-9-3,3>>^ Depois falarás aos filhos de Israel, dizendo: Tomai um bode para expiação do pecado, e um bezerro, e um cordeiro de um ano, sem defeito, para holocausto;

[[v3-9-4]]

^<<v3-9-4,4>>^ Também um boi e um carneiro por sacrifício pacífico, para sacrificar perante o Senhor, e oferta de alimentos, amassada com azeite; porquanto hoje o Senhor vos aparecerá.

[[v3-9-5]]

^<<v3-9-5,5>>^ Então trouxeram o que ordenara Moisés, diante da tenda da congregação, e chegou-se toda a congregação e se pôs perante o Senhor.

[[v3-9-6]]

^<<v3-9-6,6>>^ E disse Moisés: Esta é a coisa que o Senhor ordenou que fizésseis; e a glória do Senhor vos aparecerá.

[[v3-9-7]]

^<<v3-9-7,7>>^ E disse Moisés a Arão: Chega-te ao altar, e faze a tua expiação de pecado e o teu holocausto; e faze expiação por ti e pelo povo; depois faze a oferta do povo, e faze expiação por eles, como ordenou o Senhor.

[[v3-9-8]]

^<<v3-9-8,8>>^ Então Arão se chegou ao altar, e degolou o bezerro da expiação que era por si mesmo.

[[v3-9-9]]

^<<v3-9-9,9>>^ E os filhos de Arão trouxeram-lhe o sangue, e molhou o seu dedo no sangue, e o pôs sobre as pontas do altar; e o restante do sangue derramou à base do altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ Mas a gordura, e os rins, e o redenho do fígado de expiação do pecado, queimou sobre o altar, como o Senhor ordenara a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ Porém a carne e o couro queimou com fogo fora do arraial.

[[v3-9-12]]

^<<v3-9-12,12>>^ Depois degolou o holocausto, e os filhos de Arão lhe entregaram o sangue, e espargiu-o sobre o altar em redor.

[[v3-9-13]]

^<<v3-9-13,13>>^ Também lhe entregaram o holocausto nos seus pedaços, com a cabeça; e queimou-o sobre o altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ E lavou a fressura e as pernas, e as queimou sobre o holocausto no altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ Depois fez chegar a oferta do povo, e tomou o bode da expiação do pecado, que era pelo povo, e o degolou, e o preparou por expiação do pecado, como o primeiro.

[[v3-9-16]]

^<<v3-9-16,16>>^ Fez também chegar o holocausto, e ofereceu-o segundo o rito.

[[v3-9-17]]

^<<v3-9-17,17>>^ E fez chegar a oferta de alimentos, e a sua mão encheu dela, e queimou-a sobre o altar, além do holocausto da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Depois degolou o boi e o carneiro em sacrifício pacífico, que era pelo povo; e os filhos de Arão entregaram-lhe o sangue, que espargiu sobre o altar em redor.

[[v3-9-19]]

^<<v3-9-19,19>>^ Como também a gordura do boi e do carneiro, a cauda, e o que cobre a fressura, e os rins, e o redenho do fígado.

[[v3-9-20]]

^<<v3-9-20,20>>^ E puseram a gordura sobre os peitos, e queimou a gordura sobre o altar;

[[v3-9-21]]

^<<v3-9-21,21>>^ Mas os peitos e a espádua direita Arão ofereceu por oferta movida perante o Senhor, como Moisés tinha ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Depois Arão levantou as suas mãos ao povo e o abençoou; e desceu, havendo feito a expiação do pecado, e o holocausto, e a oferta pacífica.

[[v3-9-23]]

^<<v3-9-23,23>>^ Então entraram Moisés e Arão na tenda da congregação; depois saíram, e abençoaram ao povo; e a glória do Senhor apareceu a todo o povo.

[[v3-9-24]]

^<<v3-9-24,24>>^ Porque o fogo saiu de diante do Senhor, e consumiu o holocausto e a gordura, sobre o altar; o que vendo todo o povo, jubilaram e caíram sobre as suas faces.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]