include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// acf ?, ACF - Almeida Corrigida Fiel

[[v3-7-1]]

^<<v3-7-1,1>>^ E esta é a lei da expiação da culpa; coisa santíssima é.

[[v3-7-2]]

^<<v3-7-2,2>>^ No lugar onde degolam o holocausto, degolarão a oferta pela expiação da culpa, e o seu sangue se espargirá sobre o altar em redor.

[[v3-7-3]]

^<<v3-7-3,3>>^ E dela se oferecerá toda a sua gordura; a cauda, e a gordura que cobre a fressura.

[[v3-7-4]]

^<<v3-7-4,4>>^ Também ambos os rins, e a gordura que neles há, que está junto aos lombos, e o redenho sobre o fígado, com os rins se tirará;

[[v3-7-5]]

^<<v3-7-5,5>>^ E o sacerdote os queimará sobre o altar em oferta queimada ao Senhor; expiação da culpa é.

[[v3-7-6]]

^<<v3-7-6,6>>^ Todo o varão entre os sacerdotes a comerá; no lugar santo se comerá; coisa santíssima é.

[[v3-7-7]]

^<<v3-7-7,7>>^ Como a expiação pelo pecado, assim será a expiação da culpa; uma mesma lei haverá para elas; será do sacerdote que houver feito propiciação com ela.

[[v3-7-8]]

^<<v3-7-8,8>>^ Também o sacerdote, que oferecer o holocausto de alguém, terá para si o couro do holocausto que oferecer.

[[v3-7-9]]

^<<v3-7-9,9>>^ Como também toda a oferta que se cozer no forno, com tudo que se preparar na frigideira e na caçoula, será do sacerdote que a oferecer.

[[v3-7-10]]

^<<v3-7-10,10>>^ Também toda a oferta amassada com azeite, ou seca, será de todos os filhos de Arão, assim de um como de outro.

[[v3-7-11]]

^<<v3-7-11,11>>^ E esta é a lei do sacrifício pacífico que se oferecerá ao Senhor:

[[v3-7-12]]

^<<v3-7-12,12>>^ Se o oferecer por oferta de ação de graças, com o sacrifício de ação de graças, oferecerá bolos ázimos amassados com azeite; e coscorões ázimos amassados com azeite; e os bolos amassados com azeite serão fritos, de flor de farinha.

[[v3-7-13]]

^<<v3-7-13,13>>^ Com os bolos oferecerá por sua oferta pão levedado, com o sacrifício de ação de graças da sua oferta pacífica.

[[v3-7-14]]

^<<v3-7-14,14>>^ E de toda a oferta oferecerá uma parte por oferta alçada ao Senhor, que será do sacerdote que espargir o sangue da oferta pacífica.

[[v3-7-15]]

^<<v3-7-15,15>>^ Mas a carne do sacrifício de ação de graças da sua oferta pacífica se comerá no dia do seu oferecimento; nada se deixará dela até à manhã.

[[v3-7-16]]

^<<v3-7-16,16>>^ E, se o sacrifício da sua oferta for voto, ou oferta voluntária, no dia em que oferecer o seu sacrifício se comerá; e o que dele ficar também se comerá no dia seguinte;

[[v3-7-17]]

^<<v3-7-17,17>>^ E o que ainda ficar da carne do sacrifício ao terceiro dia será queimado no fogo.

[[v3-7-18]]

^<<v3-7-18,18>>^ Porque, se da carne do seu sacrifício pacífico se comer ao terceiro dia, aquele que a ofereceu não será aceito, nem lhe será imputado; coisa abominável será, e a pessoa que dela comer levará a sua iniqüidade.

[[v3-7-19]]

^<<v3-7-19,19>>^ E a carne que tocar alguma coisa imunda não se comerá; com fogo será queimada; mas da outra carne, qualquer que estiver limpo, comerá dela.

[[v3-7-20]]

^<<v3-7-20,20>>^ Porém, se alguma pessoa comer a carne do sacrifício pacífico, que é do Senhor, tendo ela sobre si a sua imundícia, aquela pessoa será extirpada do seu povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ E, se uma pessoa tocar alguma coisa imunda, como imundícia de homem, ou gado imundo, ou qualquer abominação imunda, e comer da carne do sacrifício pacífico, que é do Senhor, aquela pessoa será extirpada do seu povo.

[[v3-7-22]]

^<<v3-7-22,22>>^ Depois falou o Senhor a Moisés, dizendo:

[[v3-7-23]]

^<<v3-7-23,23>>^ Fala aos filhos de Israel, dizendo: Nenhuma gordura de boi, nem de carneiro, nem de cabra comereis;

[[v3-7-24]]

^<<v3-7-24,24>>^ Porém pode-se usar da gordura de corpo morto, e da gordura do dilacerado por feras, para toda a obra, mas de nenhuma maneira a comereis;

[[v3-7-25]]

^<<v3-7-25,25>>^ Porque qualquer que comer a gordura do animal, do qual se oferecer ao Senhor oferta queimada, a pessoa que a comer será extirpada do seu povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ E nenhum sangue comereis em qualquer das vossas habitações, quer de aves quer de gado.

[[v3-7-27]]

^<<v3-7-27,27>>^ Toda a pessoa que comer algum sangue, aquela pessoa será extirpada do seu povo.

[[v3-7-28]]

^<<v3-7-28,28>>^ Falou mais o Senhor a Moisés, dizendo:

[[v3-7-29]]

^<<v3-7-29,29>>^ Fala aos filhos de Israel, dizendo: Quem oferecer ao Senhor o seu sacrifício pacífico, trará a sua oferta ao Senhor do seu sacrifício pacífico.

[[v3-7-30]]

^<<v3-7-30,30>>^ As suas próprias mãos trarão as ofertas queimadas do Senhor; a gordura do peito com o peito trará para movê-lo por oferta movida perante o Senhor.

[[v3-7-31]]

^<<v3-7-31,31>>^ E o sacerdote queimará a gordura sobre o altar, porém o peito será de Arão e de seus filhos.

[[v3-7-32]]

^<<v3-7-32,32>>^ Também a espádua direita dareis ao sacerdote por oferta alçada dos vossos sacrifícios pacíficos.

[[v3-7-33]]

^<<v3-7-33,33>>^ Aquele dos filhos de Arão que oferecer o sangue do sacrifício pacífico, e a gordura, esse terá a espádua direita para a sua porção;

[[v3-7-34]]

^<<v3-7-34,34>>^ Porque o peito movido e a espádua alçada tomei dos filhos de Israel dos seus sacrifícios pacíficos, e os dei a Arão, o sacerdote, e a seus filhos, por estatuto perpétuo dos filhos de Israel.

[[v3-7-35]]

^<<v3-7-35,35>>^ Esta é a porção de Arão e a porção de seus filhos das ofertas queimadas do Senhor, desde o dia em que ele os apresentou para administrar o sacerdócio ao Senhor.

[[v3-7-36]]

^<<v3-7-36,36>>^ O que o Senhor ordenou que se lhes desse dentre os filhos de Israel no dia em que os ungiu; estatuto perpétuo é pelas suas gerações.

[[v3-7-37]]

^<<v3-7-37,37>>^ Esta é a lei do holocausto, da oferta de alimentos, e da expiação do pecado, e da expiação da culpa, e da oferta das consagrações, e do sacrifício pacífico,

[[v3-7-38]]

^<<v3-7-38,38>>^ Que o Senhor ordenou a Moisés no monte Sinai, no dia em que ordenou aos filhos de Israel que oferecessem as suas ofertas ao Senhor, no deserto de Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]