include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-2-1]]

^<<v28-2-1,1>>^ Dizei a vossos irmãos: Ami; e a vossas irmãs: Ruama.

[[v28-2-2]]

^<<v28-2-2,2>>^ Contendei com vossa mãe, contendei, porque ela não é minha mulher, e eu não sou seu marido; e desvie ela as suas prostituições da sua vista e os seus adultérios de entre os seus seios.

[[v28-2-3]]

^<<v28-2-3,3>>^ Para que eu não a despoje, ficando ela nua, e a ponha como no dia em que nasceu, e a faça como um deserto, e a torne como uma terra seca, e a mate à sede;

[[v28-2-4]]

^<<v28-2-4,4>>^ E não me compadeça de seus filhos, porque são filhos de prostituições.

[[v28-2-5]]

^<<v28-2-5,5>>^ Porque sua mãe se prostituiu; aquela que os concebeu houve-se torpemente, porque diz: Irei atrás de meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu óleo e as minhas bebidas.

[[v28-2-6]]

^<<v28-2-6,6>>^ Portanto, eis que cercarei o teu caminho com espinhos; e levantarei um muro de sebe, para que ela não ache as suas veredas.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela irá atrás de seus amantes, mas não os alcançará; e buscá-los-á, mas não os achará; então dirá: Ir-me-ei, e tornar-me-ei a meu primeiro marido, porque melhor me ia então do que agora.

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela, pois, não reconhece que eu lhe dei o grão, e o mosto, e o azeite, e que lhe multipliquei a prata e o ouro, que eles usaram para Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ Portanto tornarei a tirar o meu grão a seu tempo e o meu mosto no seu tempo determinado; e arrebatarei a minha lã e o meu linho, com que cobriam a sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ E agora descobrirei a sua vileza diante dos olhos dos seus amantes, e ninguém a livrará da minha mão.

[[v28-2-11]]

^<<v28-2-11,11>>^ E farei cessar todo o seu gozo, as suas festas, as suas luas novas, e os seus sábados, e todas as suas festividades.

[[v28-2-12]]

^<<v28-2-12,12>>^ E devastarei a sua vide e a sua figueira, de que ela diz: É esta a minha paga que me deram os meus amantes; eu, pois, farei delas um bosque, e as feras do campo as devorarão.

[[v28-2-13]]

^<<v28-2-13,13>>^ Castigá-la-ei pelos dias dos Baalins, nos quais lhes queimou incenso, e se adornou dos seus pendentes e das suas jóias, e andou atrás de seus amantes, mas de mim se esqueceu, diz o SENHOR.

[[v28-2-14]]

^<<v28-2-14,14>>^ Portanto, eis que eu a atrairei, e a levarei para o deserto, e lhe falarei ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ E lhe darei as suas vinhas dali, e o vale de Acor, por porta de esperança; e ali cantará, como nos dias de sua mocidade, e como no dia em que subiu da terra do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ E naquele dia, diz o SENHOR, tu me chamarás: Meu marido; e não mais me chamarás: Meu senhor.

[[v28-2-17]]

^<<v28-2-17,17>>^ E da sua boca tirarei os nomes dos Baalins, e não mais se lembrará desses nomes.

[[v28-2-18]]

^<<v28-2-18,18>>^ E naquele dia farei por eles aliança com as feras do campo, e com as aves do céu, e com os répteis da terra; e da terra quebrarei o arco, e a espada, e a guerra, e os farei deitar em segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ E desposar-te-ei comigo para sempre; desposar-te-ei comigo em justiça, e em juízo, e em benignidade, e em misericórdias.

[[v28-2-20]]

^<<v28-2-20,20>>^ E desposar-te-ei comigo em fidelidade, e conhecerás ao Senhor.

[[v28-2-21]]

^<<v28-2-21,21>>^ E acontecerá naquele dia que eu atenderei, diz o Senhor; eu atenderei aos céus, e estes atenderão à terra.

[[v28-2-22]]

^<<v28-2-22,22>>^ E a terra atenderá ao trigo, e ao mosto, e ao azeite, e estes atenderão a Jizreel.

[[v28-2-23]]

^<<v28-2-23,23>>^ E semeá-la-ei para mim na terra, e compadecer-me-ei dela que não obteve misericórdia; e eu direi àquele que não era meu povo: Tu és meu povo; e ele dirá: Tu és meu Deus!

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]