include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-1-1]]

^<<v28-1-1,1>>^ Palavra do SENHOR, que foi dirigida a Oséias, filho de Beeri, nos dias de Uzias, Jotão, Acaz, Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ O princípio da palavra do Senhor por meio de Oséias. Disse, pois, o Senhor a Oséias: Vai, toma uma mulher de prostituições, e filhos de prostituição; porque a terra certamente se prostitui, desviando-se do Senhor.

[[v28-1-3]]

^<<v28-1-3,3>>^ Foi, pois, e tomou a Gômer, filha de Diblaim, e ela concebeu, e lhe deu um filho.

[[v28-1-4]]

^<<v28-1-4,4>>^ E disse-lhe o Senhor: Põe-lhe o nome de Jizreel; porque daqui a pouco visitarei o sangue de Jizreel sobre a casa de Jeú, e farei cessar o reino da casa de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ E naquele dia quebrarei o arco de Israel no vale de Jizreel.

[[v28-1-6]]

^<<v28-1-6,6>>^ E tornou ela a conceber, e deu à luz uma filha. E Deus disse: Põe-lhe o nome de Lo-Ruama; porque eu não tornarei mais a compadecer-me da casa de Israel, mas tudo lhe tirarei.

[[v28-1-7]]

^<<v28-1-7,7>>^ Mas da casa de Judá me compadecerei, e os salvarei pelo Senhor seu Deus, pois não os salvarei pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros.

[[v28-1-8]]

^<<v28-1-8,8>>^ E, depois de haver desmamado a Lo-Ruama, concebeu e deu à luz um filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ E Deus disse: Põe-lhe o nome de Lo-Ami; porque vós não sois meu povo, nem eu serei vosso Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ Todavia o número dos filhos de Israel será como a areia do mar, que não pode medir-se nem contar-se; e acontecerá que no lugar onde se lhes dizia: Vós não sois meu povo, se lhes dirá: Vós sois filhos do Deus vivo.

[[v28-1-11]]

^<<v28-1-11,11>>^ E os filhos de Judá e os filhos de Israel juntos se congregarão, e constituirão sobre si uma só cabeça, e subirão da terra; porque grande será o dia de Jizreel.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]