include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-8-1]]

^<<v28-8-1,1>>^ Põe a trombeta à tua boca. Ele virá como a águia contra a casa do SENHOR, porque transgrediram a minha aliança, e se rebelaram contra a minha lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ E a mim clamarão: Deus meu! Nós, Israel, te conhecemos.

[[v28-8-3]]

^<<v28-8-3,3>>^ Israel rejeitou o bem; o inimigo persegui-lo-á.

[[v28-8-4]]

^<<v28-8-4,4>>^ Eles fizeram reis, mas não por mim; constituíram príncipes, mas eu não o soube; da sua prata e do seu ouro fizeram ídolos para si, para serem destruídos.

[[v28-8-5]]

^<<v28-8-5,5>>^ O teu bezerro, ó Samaria, te rejeitou; a minha ira se acendeu contra eles; até quando serão eles incapazes da inocência?

[[v28-8-6]]

^<<v28-8-6,6>>^ Porque isso vem de Israel, um artífice o fez, e não é Deus; mas em pedaços será desfeito o bezerro de Samaria.

[[v28-8-7]]

^<<v28-8-7,7>>^ Porque semearam vento, e segarão tormenta, não haverá seara, a erva não dará farinha; se a der, tragá-la-ão os estrangeiros.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel foi devorado; agora está entre os gentios como um vaso em que ninguém tem prazer.

[[v28-8-9]]

^<<v28-8-9,9>>^ Porque subiram à Assíria, como um jumento montês, por si só; Efraim mercou amores.

[[v28-8-10]]

^<<v28-8-10,10>>^ Todavia, ainda que eles merquem entre as nações, eu os congregarei; e serão um pouco afligidos por causa da carga do rei dos príncipes.

[[v28-8-11]]

^<<v28-8-11,11>>^ Porquanto Efraim multiplicou os altares para pecar; teve altares para pecar.

[[v28-8-12]]

^<<v28-8-12,12>>^ Escrevi-lhe as grandezas da minha lei, porém essas são estimadas como coisa estranha.

[[v28-8-13]]

^<<v28-8-13,13>>^ Quanto aos sacrifícios das minhas ofertas, sacrificam carne, e a comem, mas o Senhor não as aceita; agora se lembrará da sua iniqüidade, e punirá os seus pecados; eles voltarão para o Egito.

[[v28-8-14]]

^<<v28-8-14,14>>^ Porque Israel se esqueceu do seu Criador, e edificou templos, e Judá multiplicou cidades fortificadas. Mas eu enviarei um fogo contra as suas cidades, que consumirá os seus palácios.

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]