include::./index.adoc[]

[[v28-13-0]]
=== Oséias, 13
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-13-1]]

^<<v28-13-1,1>>^ Quando Efraim falava, tremia-se; foi exaltado em Israel; mas ele se fez culpado em Baal, e morreu.

[[v28-13-2]]

^<<v28-13-2,2>>^ E agora multiplicaram pecados, e da sua prata fizeram uma imagem de fundição, ídolos segundo o seu entendimento, todos obra de artífices, dos quais dizem: Os homens que sacrificam beijem os bezerros.

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso serão como a nuvem da manhã, e como o orvalho da madrugada, que cedo passa; como folhelho que a tempestade lança da eira, e como a fumaça da chaminé.

[[v28-13-4]]

^<<v28-13-4,4>>^ Todavia, eu sou o Senhor teu Deus desde a terra do Egito; portanto não reconhecerás outro deus além de mim, porque não há Salvador senão eu.

[[v28-13-5]]

^<<v28-13-5,5>>^ Eu te conheci no deserto, na terra muito seca.

[[v28-13-6]]

^<<v28-13-6,6>>^ Depois eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração, por isso se esqueceram de mim.

[[v28-13-7]]

^<<v28-13-7,7>>^ Serei, pois, para eles como leão; como leopardo espiarei no caminho.

[[v28-13-8]]

^<<v28-13-8,8>>^ Como ursa roubada dos seus filhos, os encontrarei, e lhes romperei as teias do seu coração, e como leão ali os devorarei; as feras do campo os despedaçarão.

[[v28-13-9]]

^<<v28-13-9,9>>^ Para a tua perda, ó Israel, te rebelaste contra mim, a saber, contra o teu ajudador.

[[v28-13-10]]

^<<v28-13-10,10>>^ Onde está agora o teu rei, para que te guarde em todas as tuas cidades, e os teus juízes, dos quais disseste: Dá-me rei e príncipes?

[[v28-13-11]]

^<<v28-13-11,11>>^ Dei-te um rei na minha ira, e tirei-o no meu furor.

[[v28-13-12]]

^<<v28-13-12,12>>^ A iniqüidade de Efraim está atada, o seu pecado está armazenado.

[[v28-13-13]]

^<<v28-13-13,13>>^ Dores de mulher de parto lhe sobrevirão; ele é um filho insensato; porque é tempo e não está no lugar em que deve vir à luz.

[[v28-13-14]]

^<<v28-13-14,14>>^ Eu os remirei da mão do inferno, e os resgatarei da morte. Onde estão, ó morte, as tuas pragas? Onde está, ó inferno, a tua perdição? O arrependimento está escondido de meus olhos.

[[v28-13-15]]

^<<v28-13-15,15>>^ Ainda que ele dê fruto entre os irmãos, virá o vento leste, vento do Senhor, subindo do deserto, e secar-se-á a sua nascente, e secar-se-á a sua fonte; ele saqueará o tesouro de todos os vasos desejáveis.

[[v28-13-16]]

^<<v28-13-16,16>>^ Samaria virá a ser deserta, porque se rebelou contra o seu Deus; cairão à espada, seus filhos serão despedaçados, e as suas grávidas serão fendidas pelo meio.

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]