include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-6-1]]

^<<v28-6-1,1>>^ Vinde, e tornemos ao SENHOR, porque ele despedaçou, e nos sarará; feriu, e nos atará a ferida.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias nos dará a vida; ao terceiro dia nos ressuscitará, e viveremos diante dele.

[[v28-6-3]]

^<<v28-6-3,3>>^ Então conheçamos, e prossigamos em conhecer ao Senhor; a sua saída, como a alva, é certa; e ele a nós virá como a chuva, como chuva serôdia que rega a terra.

[[v28-6-4]]

^<<v28-6-4,4>>^ Que te farei, ó Efraim? Que te farei, ó Judá? Porque a vossa benignidade é como a nuvem da manhã e como o orvalho da madrugada, que cedo passa.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso os abati pelos profetas; pelas palavras da minha boca os matei; e os teus juízos sairão como a luz,

[[v28-6-6]]

^<<v28-6-6,6>>^ Porque eu quero a misericórdia, e não o sacrifício; e o conhecimento de Deus, mais do que os holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Mas eles transgrediram a aliança, como Adão; eles se portaram aleivosamente contra mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é a cidade dos que praticam iniqüidade, manchada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Como as hordas de salteadores que esperam alguns, assim é a companhia dos sacerdotes que matam no caminho num mesmo consenso; sim, eles cometem abominações.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vejo uma coisa horrenda na casa de Israel, ali está a prostituição de Efraim; Israel está contaminado.

[[v28-6-11]]

^<<v28-6-11,11>>^ Também para ti, ó Judá, está assinada uma sega, quando eu trouxer o cativeiro do meu povo.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]