include::./index.adoc[]

[[v28-11-0]]
=== Oséias, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-11-1]]

^<<v28-11-1,1>>^ Quando Israel era menino, eu o amei; e do Egito chamei a meu filho.

[[v28-11-2]]

^<<v28-11-2,2>>^ Mas, como os chamavam, assim se iam da sua face; sacrificavam a baalins, e queimavam incenso às imagens de escultura.

[[v28-11-3]]

^<<v28-11-3,3>>^ Todavia, eu ensinei a andar a Efraim; tomando-os pelos seus braços, mas não entenderam que eu os curava.

[[v28-11-4]]

^<<v28-11-4,4>>^ Atraí-os com cordas humanas, com laços de amor, e fui para eles como os que tiram o jugo de sobre as suas queixadas, e lhes dei mantimento.

[[v28-11-5]]

^<<v28-11-5,5>>^ Não voltará para a terra do Egito, mas a Assíria será seu rei; porque recusam converter-se.

[[v28-11-6]]

^<<v28-11-6,6>>^ E cairá a espada sobre as suas cidades, e consumirá os seus ramos, e os devorará, por causa dos seus próprios conselhos.

[[v28-11-7]]

^<<v28-11-7,7>>^ Porque o meu povo é inclinado a desviar-se de mim; ainda que chamam ao Altíssimo, nenhum deles o exalta.

[[v28-11-8]]

^<<v28-11-8,8>>^ Como te deixaria, ó Efraim? Como te entregaria, ó Israel? Como te faria como Admá? Te poria como Zeboim? Está comovido em mim o meu coração, as minhas compaixões à uma se acendem.

[[v28-11-9]]

^<<v28-11-9,9>>^ Não executarei o furor da minha ira; não voltarei para destruir a Efraim, porque eu sou Deus e não homem, o Santo no meio de ti; eu não entrarei na cidade.

[[v28-11-10]]

^<<v28-11-10,10>>^ Andarão após o Senhor; ele rugirá como leão; rugindo, pois, ele, os filhos do ocidente tremerão.

[[v28-11-11]]

^<<v28-11-11,11>>^ Tremendo virão como um passarinho, os do Egito, e como uma pomba os da terra da Assíria, e os farei habitar em suas casas, diz o Senhor.

[[v28-11-12]]

^<<v28-11-12,12>>^ Efraim me cercou com mentira, e a casa de Israel com engano; mas Judá ainda domina com Deus, e com os santos está fiel.

'''

xref:028-oseias/028-oseias-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-oseias/028-oseias-012.adoc#v28-12-0[Próximo Capítulo &#62;]