include::./index.adoc[]

[[v28-7-0]]
=== Oséias, 7
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-7-1]]

^<<v28-7-1,1>>^ Sarando eu a Israel, se descobriu a iniqüidade de Efraim, como também as maldades de Samaria, porque praticaram a falsidade; e o ladrão entra, e a horda dos salteadores despoja por fora.

[[v28-7-2]]

^<<v28-7-2,2>>^ E não dizem no seu coração que eu me lembro de toda a sua maldade; agora, pois, os cercam as suas obras; diante da minha face estão.

[[v28-7-3]]

^<<v28-7-3,3>>^ Com a sua malícia alegram ao rei, e com as suas mentiras aos príncipes.

[[v28-7-4]]

^<<v28-7-4,4>>^ Todos eles são adúlteros; são semelhantes ao forno aceso pelo padeiro, que cessa de mexer nas brasas, depois que amassou a massa, até que seja levedada.

[[v28-7-5]]

^<<v28-7-5,5>>^ E no dia do nosso rei os príncipes se tornaram doentes com frascos de vinho; ele estendeu a sua mão com os escarnecedores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Porque, prepararam o coração como um forno, na sua emboscada; toda a noite dorme o seu padeiro, pela manhã arde como fogo de chama.

[[v28-7-7]]

^<<v28-7-7,7>>^ Todos eles estão quentes como um forno, e consomem os seus juízes; todos os seus reis caem, ninguém entre eles há que me invoque.

[[v28-7-8]]

^<<v28-7-8,8>>^ Efraim se mistura com os povos; Efraim é um bolo que não foi virado.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estrangeiros lhe comeram a força, e ele não o sabe; também as cãs se espalharam sobre ele, e não o sabe.

[[v28-7-10]]

^<<v28-7-10,10>>^ E a soberba de Israel testificará diante dele; todavia não voltarão para o Senhor seu Deus, nem o buscarão em tudo isto.

[[v28-7-11]]

^<<v28-7-11,11>>^ Porque Efraim é como uma pomba ingênua, sem entendimento; invocam o Egito, vão para a Assíria.

[[v28-7-12]]

^<<v28-7-12,12>>^ Quando forem, sobre eles estenderei a minha rede, e como aves do céu os farei descer; castigá-los-ei, conforme o que eles têm ouvido na sua congregação.

[[v28-7-13]]

^<<v28-7-13,13>>^ Ai deles, porque fugiram de mim; destruição sobre eles, porque se rebelaram contra mim; eu os remi, mas disseram mentiras contra mim.

[[v28-7-14]]

^<<v28-7-14,14>>^ E não clamaram a mim com seu coração, mas davam uivos nas suas camas; para o trigo e para o vinho se ajuntam, mas contra mim se rebelam.

[[v28-7-15]]

^<<v28-7-15,15>>^ Eu os corrigi, e lhes esforcei os braços, mas pensam mal contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ Eles voltaram, mas não para o Altíssimo. Fizeram-se como um arco enganador; caem à espada os seus príncipes, por causa do furor da sua língua; este será o seu escárnio na terra do Egito.

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]