include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v28-5-1]]

^<<v28-5-1,1>>^ Ouvi isto, ó sacerdotes, e escutai, ó casa de Israel, e dai ouvidos, ó casa do rei, porque contra vós se dirige este juízo, visto que fostes um laço para Mizpá, e rede estendida sobre o Tabor.

[[v28-5-2]]

^<<v28-5-2,2>>^ Os revoltos se aprofundaram na matança; mas eu castigarei a todos eles.

[[v28-5-3]]

^<<v28-5-3,3>>^ Eu conheço a Efraim, e Israel não se esconde de mim; porque agora te tens prostituído, ó Efraim, e Israel se contaminou.

[[v28-5-4]]

^<<v28-5-4,4>>^ Não querem ordenar as suas ações a fim de voltarem para o seu Deus, porque o espírito das prostituições está no meio deles, e não conhecem ao Senhor.

[[v28-5-5]]

^<<v28-5-5,5>>^ A soberba de Israel testificará no seu rosto; e Israel e Efraim cairão pela sua injustiça, e Judá cairá juntamente com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Então irão com os seus rebanhos, e com o seu gado, para buscarem ao Senhor, mas não o acharão; ele se retirou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Aleivosamente se houveram contra o Senhor, porque geraram filhos estranhos; agora em um só mês os consumirá com as suas porções.

[[v28-5-8]]

^<<v28-5-8,8>>^ Tocai a buzina em Gibeá, a trombeta em Ramá; gritai altamente em Bete-Áven; depois de ti, ó Benjamim.

[[v28-5-9]]

^<<v28-5-9,9>>^ Efraim será para assolação no dia do castigo; entre as tribos de Israel manifestei o que está certo.

[[v28-5-10]]

^<<v28-5-10,10>>^ Os príncipes de Judá são como os que mudam os limites; derramarei, pois, o meu furor sobre eles como água.

[[v28-5-11]]

^<<v28-5-11,11>>^ Efraim está oprimido e quebrantado no juízo, porque quis andar após o mandamento dos homens.

[[v28-5-12]]

^<<v28-5-12,12>>^ Portanto a Efraim serei como a traça, e para a casa de Judá como a podridão.

[[v28-5-13]]

^<<v28-5-13,13>>^ Quando Efraim viu a sua enfermidade, e Judá a sua chaga, subiu Efraim à Assíria e enviou ao rei Jarebe; mas ele não poderá sarar-vos, nem curar a vossa chaga.

[[v28-5-14]]

^<<v28-5-14,14>>^ Porque para Efraim serei como um leão, e como um leãozinho à casa de Judá: eu, eu o despedaçarei, e irme-ei embora; arrebatarei, e não haverá quem livre.

[[v28-5-15]]

^<<v28-5-15,15>>^ Irei e voltarei ao meu lugar, até que se reconheçam culpados e busquem a minha face; estando eles angustiados, de madrugada me buscarão.

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]