include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v36-2-1]]

^<<v36-2-1,1>>^ Congregai-vos, sim, congregai-vos, ó nação não desejável;

[[v36-2-2]]

^<<v36-2-2,2>>^ Antes que o decreto produza o seu efeito, e o dia passe como a pragana; antes que venha sobre vós o furor da ira do Senhor, antes que venha sobre vós o dia da ira do Senhor.

[[v36-2-3]]

^<<v36-2-3,3>>^ Buscai ao Senhor, vós todos os mansos da terra, que tendes posto por obra o seu juízo; buscai a justiça, buscai a mansidão; pode ser que sejais escondidos no dia da ira do Senhor.

[[v36-2-4]]

^<<v36-2-4,4>>^ Porque Gaza será desamparada, e Ascalom assolada; Asdode ao meio-dia será expelida, e Ecrom será desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai dos habitantes da costa do mar, a nação dos quereteus! A palavra do Senhor será contra vós, ó Canaã, terra dos filisteus; e eu vos destruirei, até que não haja morador.

[[v36-2-6]]

^<<v36-2-6,6>>^ E a costa do mar será de pastos e cabanas para os pastores, e currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ E será a costa para o restante da casa de Judá; ali apascentarão os seus rebanhos; de tarde se deitarão nas casas de Ascalom; porque o Senhor seu Deus os visitará, e os fará tornar do seu cativeiro.

[[v36-2-8]]

^<<v36-2-8,8>>^ Eu ouvi o escárnio de Moabe, e as injuriosas palavras dos filhos de Amom, com que escarneceram do meu povo, e se engrandeceram contra o seu termo.

[[v36-2-9]]

^<<v36-2-9,9>>^ Portanto, tão certo como eu vivo, diz o Senhor dos Exércitos, o Deus de Israel, Moabe será como Sodoma, e os filhos de Amom como Gomorra, campo de urtigas e poços de sal, e desolação perpétua; o restante do meu povo os saqueará, e o restante do meu povo os possuirá.

[[v36-2-10]]

^<<v36-2-10,10>>^ Isso terão em recompensa da sua soberba, porque escarneceram, e se engrandeceram contra o povo do Senhor dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O Senhor será terrível para eles, porque emagrecerá todos os deuses da terra; e todos virão adorá-lo, cada um desde o seu lugar, de todas as ilhas dos gentios.

[[v36-2-12]]

^<<v36-2-12,12>>^ Também vós, ó etíopes, sereis mortos com a minha espada.

[[v36-2-13]]

^<<v36-2-13,13>>^ Estenderá também a sua mão contra o norte, e destruirá a Assíria; e fará de Nínive uma desolação, terra seca como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ E no meio dela repousarão os rebanhos, todos os animais das nações; e alojar-se-ão nos seus capitéis assim o pelicano como o ouriço; o canto das aves se ouvirá nas janelas; e haverá desolação nos limiares, quando tiver descoberto a sua obra de cedro.

[[v36-2-15]]

^<<v36-2-15,15>>^ Esta é a cidade alegre, que habita despreocupadamente, que diz no seu coração: Eu sou, e não há outra além de mim; como se tornou em desolação, em pousada de animais! Todo o que passar por ela assobiará, e meneará a sua mão.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]