include::./index.adoc[]

[[v32-2-0]]
=== Jonas, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v32-2-1]]

^<<v32-2-1,1>>^ E orou Jonas ao SENHOR, seu Deus, das entranhas do peixe.

[[v32-2-2]]

^<<v32-2-2,2>>^ E disse: Na minha angústia clamei ao Senhor, e ele me respondeu; do ventre do inferno gritei, e tu ouviste a minha voz.

[[v32-2-3]]

^<<v32-2-3,3>>^ Porque tu me lançaste no profundo, no coração dos mares, e a corrente das águas me cercou; todas as tuas ondas e as tuas vagas têm passado por cima de mim.

[[v32-2-4]]

^<<v32-2-4,4>>^ E eu disse: Lançado estou de diante dos teus olhos; todavia tornarei a ver o teu santo templo.

[[v32-2-5]]

^<<v32-2-5,5>>^ As águas me cercaram até à alma, o abismo me rodeou, e as algas se enrolaram na minha cabeça.

[[v32-2-6]]

^<<v32-2-6,6>>^ Eu desci até aos fundamentos dos montes; a terra me encerrou para sempre com os seus ferrolhos; mas tu fizeste subir a minha vida da perdição, ó Senhor meu Deus.

[[v32-2-7]]

^<<v32-2-7,7>>^ Quando desfalecia em mim a minha alma, lembrei-me do Senhor; e entrou a ti a minha oração, no teu santo templo.

[[v32-2-8]]

^<<v32-2-8,8>>^ Os que observam as falsas vaidades deixam a sua misericórdia.

[[v32-2-9]]

^<<v32-2-9,9>>^ Mas eu te oferecerei sacrifício com a voz do agradecimento; o que votei pagarei. Do Senhor vem a salvação.

[[v32-2-10]]

^<<v32-2-10,10>>^ Falou, pois, o Senhor ao peixe, e este vomitou a Jonas na terra seca.

'''

xref:032-jonas/032-jonas-001.adoc#v32-1-0[&#60; Capítulo Anterior] | <<v32-2-0,Topo>> | xref:032-jonas/032-jonas-003.adoc#v32-3-0[Próximo Capítulo &#62;]