include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v32-1-1]]

^<<v32-1-1,1>>^ E veio a palavra do SENHOR a Jonas, filho de Amitai, dizendo:

[[v32-1-2]]

^<<v32-1-2,2>>^ Levanta-te, vai à grande cidade de Nínive, e clama contra ela, porque a sua malícia subiu até à minha presença.

[[v32-1-3]]

^<<v32-1-3,3>>^ Porém, Jonas se levantou para fugir da presença do Senhor para Társis. E descendo a Jope, achou um navio que ia para Társis; pagou, pois, a sua passagem, e desceu para dentro dele, para ir com eles para Társis, para longe da presença do Senhor.

[[v32-1-4]]

^<<v32-1-4,4>>^ Mas o Senhor mandou ao mar um grande vento, e fez-se no mar uma forte tempestade, e o navio estava a ponto de quebrar-se.

[[v32-1-5]]

^<<v32-1-5,5>>^ Então temeram os marinheiros, e clamavam cada um ao seu deus, e lançaram ao mar as cargas, que estavam no navio, para o aliviarem do seu peso; Jonas, porém, desceu ao porão do navio, e, tendo-se deitado, dormia um profundo sono.

[[v32-1-6]]

^<<v32-1-6,6>>^ E o mestre do navio chegou- se a ele, e disse-lhe: Que tens, dorminhoco? Levanta-te, clama ao teu Deus; talvez assim ele se lembre de nós para que não pereçamos.

[[v32-1-7]]

^<<v32-1-7,7>>^ E diziam cada um ao seu companheiro: Vinde, e lancemos sortes, para que saibamos por que causa nos sobreveio este mal. E lançaram sortes, e a sorte caiu sobre Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Então lhe disseram: Declara-nos tu agora, por causa de quem nos sobreveio este mal. Que ocupação é a tua? Donde vens? Qual é a tua terra? E de que povo és tu?

[[v32-1-9]]

^<<v32-1-9,9>>^ E ele lhes disse: Eu sou hebreu, e temo ao Senhor, o Deus do céu, que fez o mar e a terra seca.

[[v32-1-10]]

^<<v32-1-10,10>>^ Então estes homens se enche-ram de grande temor, e disseram-lhe: Por que fizeste tu isto? Pois sabiam os homens que fugia da presença do Senhor, porque ele lho tinha declarado.

[[v32-1-11]]

^<<v32-1-11,11>>^ E disseram-lhe: Que te faremos nós, para que o mar se nos acalme? Porque o mar ia se tornando cada vez mais tempestuoso.

[[v32-1-12]]

^<<v32-1-12,12>>^ E ele lhes disse: Levantai-me, e lançai-me ao mar, e o mar se vos aquietará; porque eu sei que por minha causa vos sobreveio esta grande tempestade.

[[v32-1-13]]

^<<v32-1-13,13>>^ Entretanto, os homens remavam, para fazer voltar o navio à terra, mas não podiam, porquanto o mar se ia embravecendo cada vez mais contra eles.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então clamaram ao Senhor, e disseram: Ah, Senhor! Nós te rogamos, que não pereçamos por causa da alma deste homem, e que não ponhas sobre nós o sangue inocente; porque tu, Senhor, fizeste como te aprouve.

[[v32-1-15]]

^<<v32-1-15,15>>^ E levantaram a Jonas, e o lançaram ao mar, e cessou o mar da sua fúria.

[[v32-1-16]]

^<<v32-1-16,16>>^ Temeram, pois, estes homens ao Senhor com grande temor; e ofereceram sacrifício ao Senhor, e fizeram votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ Preparou, pois, o Senhor um grande peixe, para que tragasse a Jonas; e esteve Jonas três dias e três noites nas entranhas do peixe.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]