include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v30-9-1]]

^<<v30-9-1,1>>^ Vi o Senhor, que estava em pé sobre o altar; e me disse: Fere o capitel, e estremeçam os umbrais, e faze tudo em pedaços sobre a cabeça de todos eles; e eu matarei à espada até ao último deles; nenhum deles conseguirá fugir, nenhum deles escapará.

[[v30-9-2]]

^<<v30-9-2,2>>^ Ainda que cavem até ao inferno, a minha mão os tirará dali; e, se subirem ao céu, dali os farei descer.

[[v30-9-3]]

^<<v30-9-3,3>>^ E, se se esconderem no cume do Carmelo, buscá-los-ei, e dali os tirarei; e, se dos meus olhos se ocultarem no fundo do mar, ali darei ordem à serpente, e ela os picará.

[[v30-9-4]]

^<<v30-9-4,4>>^ E, se forem em cativeiro diante de seus inimigos, ali darei ordem à espada que os mate; e eu porei os meus olhos sobre eles para o mal, e não para o bem.

[[v30-9-5]]

^<<v30-9-5,5>>^ Porque o Senhor DEUS dos Exércitos é o que toca a terra, e ela se derrete, e todos os que habitam nela chorarão; e ela subirá toda como um rio, e abaixará como o rio do Egito.

[[v30-9-6]]

^<<v30-9-6,6>>^ Ele é o que edifica as suas câmaras superiores no céu, e fundou na terra a sua abóbada, e o que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.

[[v30-9-7]]

^<<v30-9-7,7>>^ Não me sois, vós, ó filhos de Israel, como os filhos dos etíopes? diz o Senhor: Não fiz eu subir a Israel da terra do Egito, e aos filisteus de Caftor, e aos sírios de Quir?

[[v30-9-8]]

^<<v30-9-8,8>>^ Eis que os olhos do Senhor DEUS estão contra este reino pecador, e eu o destruirei de sobre a face da terra; mas não destruirei de todo a casa de Jacó, diz o SENHOR.

[[v30-9-9]]

^<<v30-9-9,9>>^ Porque eis que darei ordem, e sacudirei a casa de Israel entre todas as nações, assim como se sacode grão no crivo, sem que caia na terra um só grão.

[[v30-9-10]]

^<<v30-9-10,10>>^ Todos os pecadores do meu povo morrerão à espada, os que dizem: Não nos alcançará nem nos encontrará o mal.

[[v30-9-11]]

^<<v30-9-11,11>>^ Naquele dia tornarei a levantar o tabernáculo caído de Davi, e repararei as suas brechas, e tornarei a levantar as suas ruínas, e o edificarei como nos dias da antigüidade;

[[v30-9-12]]

^<<v30-9-12,12>>^ Para que possuam o restante de Edom, e todos os gentios que são chamados pelo meu nome, diz o Senhor, que faz essas coisas.

[[v30-9-13]]

^<<v30-9-13,13>>^ Eis que vêm dias, diz o Senhor, em que o que lavra alcançará ao que sega, e o que pisa as uvas ao que lança a semente; e os montes destilarão mosto, e todos os outeiros se derreterão.

[[v30-9-14]]

^<<v30-9-14,14>>^ E trarei do cativeiro meu povo Israel, e eles reedificarão as cidades assoladas, e nelas habitarão, e plantarão vinhas, e beberão o seu vinho, e farão pomares, e lhes comerão o fruto.

[[v30-9-15]]

^<<v30-9-15,15>>^ E plantá-los-ei na sua terra, e não serão mais arrancados da sua terra que lhes dei, diz o Senhor teu Deus.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]