include::./index.adoc[]

[[v30-5-0]]
=== Amós, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v30-5-1]]

^<<v30-5-1,1>>^ Ouvi esta palavra, que levanto como uma lamentação sobre vós, ó casa de Israel.

[[v30-5-2]]

^<<v30-5-2,2>>^ A virgem de Israel caiu, e não mais tornará a levantar-se; desamparada está na sua terra, não há quem a levante.

[[v30-5-3]]

^<<v30-5-3,3>>^ Porque assim diz o Senhor DEUS: A cidade da qual saem mil conservará cem, e aquela da qual saem cem conservará dez, para a casa de Israel.

[[v30-5-4]]

^<<v30-5-4,4>>^ Porque assim diz o Senhor à casa de Israel: Buscai-me, e vivei.

[[v30-5-5]]

^<<v30-5-5,5>>^ Mas não busqueis a Betel, nem venhais a Gilgal, nem passeis a Berseba, porque Gilgal certamente será levada ao cativeiro, e Betel será desfeita em nada.

[[v30-5-6]]

^<<v30-5-6,6>>^ Buscai ao Senhor, e vivei, para que ele não irrompa na casa de José como um fogo, e a consuma, e não haja em Betel quem o apague.

[[v30-5-7]]

^<<v30-5-7,7>>^ Vós que converteis o juízo em alosna, e deitais por terra a justiça,

[[v30-5-8]]

^<<v30-5-8,8>>^ Procurai o que faz o sete-estrêlo e o órion e torna a sombra da noite em manhã, e faz escurecer o dia como a noite, que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.

[[v30-5-9]]

^<<v30-5-9,9>>^ O que promove súbita destruição contra o forte; de modo que venha a destruição contra a fortaleza.

[[v30-5-10]]

^<<v30-5-10,10>>^ Odeiam na porta ao que os repreende, e abominam ao que fala sinceramente.

[[v30-5-11]]

^<<v30-5-11,11>>^ Portanto, visto que pisais o pobre e dele exigis um tributo de trigo, edificastes casas de pedras lavradas, mas nelas não habitareis; vinhas desejáveis plantastes, mas não bebereis do seu vinho.

[[v30-5-12]]

^<<v30-5-12,12>>^ Porque sei que são muitas as vossas transgressões e graves os vossos pecados; afligis o justo, tomais resgate, e rejeitais os necessitados na porta.

[[v30-5-13]]

^<<v30-5-13,13>>^ Portanto, o que for prudente guardará silêncio naquele tempo, porque o tempo será mau.

[[v30-5-14]]

^<<v30-5-14,14>>^ Buscai o bem, e não o mal, para que vivais; e assim o Senhor, o Deus dos Exércitos, estará convosco, como dizeis.

[[v30-5-15]]

^<<v30-5-15,15>>^ Odiai o mal, e amai o bem, e estabelecei na porta o juízo. Talvez o Senhor Deus dos Exércitos tenha piedade do remanescente de José.

[[v30-5-16]]

^<<v30-5-16,16>>^ Portanto, assim diz o Senhor, o Deus dos Exércitos, o Senhor: Em todas as ruas haverá pranto, e em todas as estradas dirão: Ai! Ai! E ao lavrador chamarão para choro, e para pranto os que souberem prantear.

[[v30-5-17]]

^<<v30-5-17,17>>^ E em todas as vinhas haverá pranto; porque passarei pelo meio de ti, diz o Senhor.

[[v30-5-18]]

^<<v30-5-18,18>>^ Ai daqueles que desejam o dia do Senhor! Para que quereis vós este dia do Senhor? Será de trevas e não de luz.

[[v30-5-19]]

^<<v30-5-19,19>>^ É como se um homem fugisse de diante do leão, e se encontrasse com ele o urso; ou como se entrando numa casa, a sua mão encostasse à parede, e fosse mordido por uma cobra.

[[v30-5-20]]

^<<v30-5-20,20>>^ Não será, pois, o dia do Senhor trevas e não luz, e escuridão, sem que haja resplendor?

[[v30-5-21]]

^<<v30-5-21,21>>^ Odeio, desprezo as vossas festas, e as vossas assembléias solenes não me exalarão bom cheiro.

[[v30-5-22]]

^<<v30-5-22,22>>^ E ainda que me ofereçais holocaustos, ofertas de alimentos, não me agradarei delas; nem atentarei para as ofertas pacíficas de vossos animais gordos.

[[v30-5-23]]

^<<v30-5-23,23>>^ Afasta de mim o estrépito dos teus cânticos; porque não ouvirei as melodias das tuas violas.

[[v30-5-24]]

^<<v30-5-24,24>>^ Corra, porém, o juízo como as águas, e a justiça como o ribeiro impetuoso.

[[v30-5-25]]

^<<v30-5-25,25>>^ Oferecestes-me vós sacrifícios e oblações no deserto por quarenta anos, ó casa de Israel?

[[v30-5-26]]

^<<v30-5-26,26>>^ Antes levastes a tenda de vosso Moloque, e a estátua das vossas imagens, a estrela do vosso deus, que fizestes para vós mesmos.

[[v30-5-27]]

^<<v30-5-27,27>>^ Portanto vos levarei cativos, para além de Damasco, diz o Senhor, cujo nome é o Deus dos Exércitos.

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]