include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// acf ?, ACF - Almeida Corrigida Fiel

[[v30-3-1]]

^<<v30-3-1,1>>^ Ouvi esta palavra que o SENHOR fala contra vós, filhos de Israel, contra toda a família que fiz subir da terra do Egito, dizendo:

[[v30-3-2]]

^<<v30-3-2,2>>^ De todas as famílias da terra só a vós vos tenho conhecido; portanto eu vos punirei por todas as vossas iniqüidades.

[[v30-3-3]]

^<<v30-3-3,3>>^ Porventura andarão dois juntos, se não estiverem de acordo?

[[v30-3-4]]

^<<v30-3-4,4>>^ Rugirá o leão no bosque, sem que tenha presa? Levantará o leãozinho no seu covil a sua voz, se nada tiver apanhado?

[[v30-3-5]]

^<<v30-3-5,5>>^ Cairá a ave no laço em terra, se não houver armadilha para ela? Levantar-se-á da terra o laço, sem que tenha apanhado alguma coisa?

[[v30-3-6]]

^<<v30-3-6,6>>^ Tocar-se-á a trombeta na cidade, e o povo não estremecerá? Sucederá algum mal na cidade, sem que o Senhor o tenha feito?

[[v30-3-7]]

^<<v30-3-7,7>>^ Certamente o Senhor DEUS não fará coisa alguma, sem ter revelado o seu segredo aos seus servos, os profetas.

[[v30-3-8]]

^<<v30-3-8,8>>^ Rugiu o leão, quem não temerá? Falou o Senhor DEUS, quem não profetizará?

[[v30-3-9]]

^<<v30-3-9,9>>^ Fazei ouvir isso nos palácios de Asdode, e nos palácios da terra do Egito, e dizei: Ajuntai-vos sobre os montes de Samaria, e vede que grandes alvoroços há no meio dela, e como são oprimidos dentro dela.

[[v30-3-10]]

^<<v30-3-10,10>>^ Porque não sabem fazer o que é reto, diz o Senhor, aqueles que entesouram nos seus palácios a violência e a destruição.

[[v30-3-11]]

^<<v30-3-11,11>>^ Portanto, o Senhor DEUS diz assim: O inimigo virá, e cercará a terra, derrubará a tua fortaleza, e os teus palácios serão saqueados.

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz o Senhor: Como o pastor livra da boca do leão as duas pernas, ou um pedaço da orelha, assim serão livrados os filhos de Israel que habitam em Samaria, no canto da cama, e no damasco do leito.

[[v30-3-13]]

^<<v30-3-13,13>>^ Ouvi, e protestai contra a casa de Jacó, diz o Senhor DEUS, o Deus dos Exércitos;

[[v30-3-14]]

^<<v30-3-14,14>>^ Pois no dia em que eu punir as transgressões de Israel, também castigarei os altares de Betel; e as pontas do altar serão cortadas, e cairão por terra.

[[v30-3-15]]

^<<v30-3-15,15>>^ E ferirei a casa de inverno juntamente com a casa de verão; e as casas de marfim perecerão, e as grandes casas terão fim, diz o Senhor.

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]