include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v30-6-1]]

^<<v30-6-1,1>>^ Ai dos que vivem sossegados em Sião, e dos que estão confiados no monte de Samaria, que têm nome entre as primeiras das nações, e aos quais vem a casa de Israel!

[[v30-6-2]]

^<<v30-6-2,2>>^ Passai a Calne, e vede; e dali ide à grande Hamate; e depois descei a Gate dos filisteus; serão melhores que estes reinos? Ou maior o seu termo do que o vosso termo?

[[v30-6-3]]

^<<v30-6-3,3>>^ Ó vós que afastais o dia mau, e fazeis chegar o assento da violência.

[[v30-6-4]]

^<<v30-6-4,4>>^ Ai dos que dormem em camas de marfim, e se estendem sobre os seus leitos, e comem os cordeiros do rebanho, e os bezerros do meio do curral;

[[v30-6-5]]

^<<v30-6-5,5>>^ Que cantam ao som da viola, e inventam para si instrumentos musicais, assim como Davi;

[[v30-6-6]]

^<<v30-6-6,6>>^ Que bebem vinho em taças, e se ungem com o mais excelente óleo: mas não se afligem pela ruína de José;

[[v30-6-7]]

^<<v30-6-7,7>>^ Portanto agora irão em cativeiro entre os primeiros dos que forem levados cativos, e cessarão os festins dos banqueteadores.

[[v30-6-8]]

^<<v30-6-8,8>>^ Jurou o Senhor DEUS por si mesmo, diz o SENHOR, o Deus dos Exércitos: Abomino a soberba de Jacó, e odeio os seus palácios; por isso entregarei a cidade e tudo o que nela há.

[[v30-6-9]]

^<<v30-6-9,9>>^ E acontecerá que, se numa casa ficarem dez homens, morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ Quando o tio de alguém, aquele que o queima, o tomar para levar-lhe os ossos para fora da casa, e disser ao que estiver no mais interior da casa: Está ainda alguém contigo? E este responder: Ninguém; então lhe dirá ele: Cala-te, porque não devemos fazer menção do nome do Senhor.

[[v30-6-11]]

^<<v30-6-11,11>>^ Porque, eis que o Senhor ordena, e ferirá a casa grande de brechas, e a casa pequena de fendas.

[[v30-6-12]]

^<<v30-6-12,12>>^ Porventura correrão cavalos sobre rocha? Lavrar-se-á nela com bois? Mas vós haveis tornado o juízo em fel, e o fruto da justiça em alosna;

[[v30-6-13]]

^<<v30-6-13,13>>^ Vós que vos alegrais do nada, vós que dizeis: Não é assim que por nossa própria força nos temos tornado poderosos?

[[v30-6-14]]

^<<v30-6-14,14>>^ Porque, eis que eu levantarei sobre vós, ó casa de Israel, uma nação, diz o Senhor, o Deus dos Exércitos, e oprimir-vos-á, desde a entrada de Hamate até ao ribeiro do deserto.

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]