include::./index.adoc[]

[[v9-16-0]]
=== 1 Samuel, 16
// acf ?, ACF - Almeida Corrigida Fiel

[[v9-16-1]]

^<<v9-16-1,1>>^ Então disse o SENHOR a Samuel: Até quando terás dó de Saul, havendo-o eu rejeitado, para que não reine sobre Israel? Enche um chifre de azeite, e vem, enviar-te-ei a Jessé o belemita; porque dentre os seus filhos me tenho provido de um rei.

[[v9-16-2]]

^<<v9-16-2,2>>^ Porém disse Samuel: Como irei eu? pois, ouvindo-o Saul, me matará. Então disse o Senhor: Toma uma bezerra das vacas em tuas mãos, e dize: Vim para sacrificar ao Senhor.

[[v9-16-3]]

^<<v9-16-3,3>>^ E convidarás a Jessé ao sacrifício; e eu te farei saber o que hás de fazer, e ungir-me-ás a quem eu te disser.

[[v9-16-4]]

^<<v9-16-4,4>>^ Fez, pois, Samuel o que dissera o Senhor, e veio a Belém; então os anciãos da cidade saíram ao encontro, tremendo, e disseram: De paz é a tua vinda?

[[v9-16-5]]

^<<v9-16-5,5>>^ E disse ele: É de paz, vim sacrificar ao Senhor; santificai-vos, e vinde comigo ao sacrifício. E santificou ele a Jessé e a seus filhos, e os convidou ao sacrifício.

[[v9-16-6]]

^<<v9-16-6,6>>^ E sucedeu que, entrando eles, viu a Eliabe, e disse: Certamente está perante o Senhor o seu ungido.

[[v9-16-7]]

^<<v9-16-7,7>>^ Porém o Senhor disse a Samuel: Não atentes para a sua aparência, nem para a grandeza da sua estatura, porque o tenho rejeitado; porque o Senhor não vê como vê o homem, pois o homem vê o que está diante dos olhos, porém o Senhor olha para o coração.

[[v9-16-8]]

^<<v9-16-8,8>>^ Então chamou Jessé a Abinadabe, e o fez passar diante de Samuel, o qual disse: Nem a este tem escolhido o Senhor.

[[v9-16-9]]

^<<v9-16-9,9>>^ Então Jessé fez passar a Sama; porém disse: Tampouco a este tem escolhido o Senhor.

[[v9-16-10]]

^<<v9-16-10,10>>^ Assim fez passar Jessé a seus sete filhos diante de Samuel; porém Samuel disse a Jessé: O Senhor não tem escolhido a estes.

[[v9-16-11]]

^<<v9-16-11,11>>^ Disse mais Samuel a Jessé: Acabaram-se os moços? E disse: Ainda falta o menor, que está apascentando as ovelhas. Disse, pois, Samuel a Jessé: Manda chamá-lo, porquanto não nos assentaremos até que ele venha aqui.

[[v9-16-12]]

^<<v9-16-12,12>>^ Então mandou chamá-lo e fê-lo entrar (e era ruivo e formoso de semblante e de boa presença); e disse o Senhor: Levanta-te, e unge-o, porque é este mesmo.

[[v9-16-13]]

^<<v9-16-13,13>>^ Então Samuel tomou o chifre do azeite, e ungiu-o no meio de seus irmãos; e desde aquele dia em diante o Espírito do Senhor se apoderou de Davi; então Samuel se levantou, e voltou a Ramá.

[[v9-16-14]]

^<<v9-16-14,14>>^ E o Espírito do Senhor se retirou de Saul, e atormentava-o um espírito mau da parte do Senhor.

[[v9-16-15]]

^<<v9-16-15,15>>^ Então os criados de Saul lhe disseram: Eis que agora o espírito mau da parte de Deus te atormenta;

[[v9-16-16]]

^<<v9-16-16,16>>^ Diga, pois, nosso senhor a seus servos, que estão na tua presença, que busquem um homem que saiba tocar harpa, e será que, quando o espírito mau da parte de Deus vier sobre ti, então ele tocará com a sua mão, e te acharás melhor.

[[v9-16-17]]

^<<v9-16-17,17>>^ Então disse Saul aos seus servos: Buscai-me, pois, um homem que toque bem, e trazei-mo.

[[v9-16-18]]

^<<v9-16-18,18>>^ Então respondeu um dos moços, e disse: Eis que tenho visto a um filho de Jessé, o belemita, que sabe tocar e é valente e vigoroso, e homem de guerra, e prudente em palavras, e de gentil presença; o Senhor é com ele.

[[v9-16-19]]

^<<v9-16-19,19>>^ E Saul enviou mensageiros a Jessé, dizendo: Envia-me Davi, teu filho, o que está com as ovelhas.

[[v9-16-20]]

^<<v9-16-20,20>>^ Então tomou Jessé um jumento carregado de pão, e um odre de vinho, e um cabrito, e enviou-os a Saul pela mão de Davi, seu filho.

[[v9-16-21]]

^<<v9-16-21,21>>^ Assim Davi veio a Saul, e esteve perante ele, e o amou muito, e foi seu pajem de armas.

[[v9-16-22]]

^<<v9-16-22,22>>^ Então Saul mandou dizer a Jessé: Deixa estar a Davi perante mim, pois achou graça em meus olhos.

[[v9-16-23]]

^<<v9-16-23,23>>^ E sucedia que, quando o espírito mau da parte de Deus vinha sobre Saul, Davi tomava a harpa, e a tocava com a sua mão; então Saul sentia alívio, e se achava melhor, e o espírito mau se retirava dele.

'''

xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[&#60; Capítulo Anterior] | <<v9-16-0,Topo>> | xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[Próximo Capítulo &#62;]