include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// acf ?, ACF - Almeida Corrigida Fiel

[[v9-30-1]]

^<<v9-30-1,1>>^ Sucedeu, pois, que, chegando Davi e os seus homens ao terceiro dia a Ziclague, já os amalequitas tinham invadido o sul, e Ziclague, e tinham ferido a Ziclague e a tinham queimado a fogo.

[[v9-30-2]]

^<<v9-30-2,2>>^ E tinham levado cativas as mulheres, e todos os que estavam nela, tanto pequenos como grandes; a ninguém, porém, mataram, tão-somente os levaram consigo, e foram o seu caminho.

[[v9-30-3]]

^<<v9-30-3,3>>^ E Davi e os seus homens chegaram à cidade e eis que estava queimada a fogo, e suas mulheres, seus filhos e suas filhas tinham sido levados cativos.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então Davi e o povo que se achava com ele alçaram a sua voz, e choraram, até que neles não houve mais forças para chorar.

[[v9-30-5]]

^<<v9-30-5,5>>^ Também as duas mulheres de Davi foram levadas cativas; Ainoã, a jizreelita, e Abigail, a mulher de Nabal, o carmelita.

[[v9-30-6]]

^<<v9-30-6,6>>^ E Davi muito se angustiou, porque o povo falava de apedrejá-lo, porque a alma de todo o povo estava em amargura, cada um por causa dos seus filhos e das suas filhas; todavia Davi se fortaleceu no Senhor seu Deus.

[[v9-30-7]]

^<<v9-30-7,7>>^ E disse Davi a Abiatar, o sacerdote, filho de Aimeleque: Traze-me, peço-te, aqui o éfode. E Abiatar trouxe o éfode a Davi.

[[v9-30-8]]

^<<v9-30-8,8>>^ Então consultou Davi ao Senhor, dizendo: Perseguirei eu a esta tropa? Alcançá-la-ei? E lhe disse: Persegue-a, porque decerto a alcançarás e tudo libertarás.

[[v9-30-9]]

^<<v9-30-9,9>>^ Partiu, pois, Davi, ele e os seiscentos homens que com ele se achavam, e chegaram ao ribeiro de Besor, onde pararam os que ficaram atrás.

[[v9-30-10]]

^<<v9-30-10,10>>^ E perseguiu-os Davi, ele e os quatrocentos homens, pois que duzentos homens ficaram, por não poderem, de cansados que estavam, passar o ribeiro de Besor.

[[v9-30-11]]

^<<v9-30-11,11>>^ E acharam no campo um homem egípcio, e o trouxeram a Davi; deram-lhe pão, e comeu, e deram-lhe a beber água.

[[v9-30-12]]

^<<v9-30-12,12>>^ Deram-lhe também um pedaço de massa de figos secos e dois cachos de passas, e comeu, e voltou-lhe o seu espírito, porque havia três dias e três noites que não tinha comido pão nem bebido água.

[[v9-30-13]]

^<<v9-30-13,13>>^ Então Davi lhe disse: De quem és tu, e de onde és? E disse o moço egípcio: Sou servo de um homem amalequita, e meu senhor me deixou, porque adoeci há três dias.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós invadimos o lado do sul dos queretitas, e o lado de Judá, e o lado do sul de Calebe, e pusemos fogo a Ziclague.

[[v9-30-15]]

^<<v9-30-15,15>>^ E disse-lhe Davi: Poderias, descendo, guiar-me a essa tropa? E disse-lhe: Por Deus jura-me que não me matarás, nem me entregarás na mão de meu senhor, e, descendo, te guiarei a essa tropa.

[[v9-30-16]]

^<<v9-30-16,16>>^ E, descendo, o guiou e eis que estavam espalhados sobre a face de toda a terra, comendo, e bebendo, e dançando, por todo aquele grande despojo que tomaram da terra dos filisteus e da terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ E feriu-os Davi, desde o crepúsculo até à tarde do dia seguinte; nenhum deles escapou, senão só quatrocentos moços que, montados sobre camelos, fugiram.

[[v9-30-18]]

^<<v9-30-18,18>>^ Assim salvou Davi tudo quanto tomaram os amalequitas; também as suas duas mulheres salvou Davi.

[[v9-30-19]]

^<<v9-30-19,19>>^ E ninguém lhes faltou, desde o menor até ao maior, e até os filhos e as filhas; e também desde o despojo até tudo quanto lhes tinham tomado, tudo Davi tornou a trazer.

[[v9-30-20]]

^<<v9-30-20,20>>^ Também tomou Davi todas as ovelhas e vacas, e levavam-nas adiante do outro gado, e diziam: Este é o despojo de Davi.

[[v9-30-21]]

^<<v9-30-21,21>>^ E, chegando Davi aos duzentos homens que, de cansados que estavam, não puderam seguir a Davi, e que deixaram ficar no ribeiro de Besor, estes saíram ao encontro de Davi e do povo que com ele vinha; e, chegando-se Davi com o povo, os saudou em paz.

[[v9-30-22]]

^<<v9-30-22,22>>^ Então todos os maus e perversos, dentre os homens que tinham ido com Davi, responderam, e disseram: Visto que não foram conosco, não lhes daremos do despojo que libertamos; mas que leve cada um sua mulher e seus filhos, e se vá.

[[v9-30-23]]

^<<v9-30-23,23>>^ Porém Davi disse: Não fareis assim, irmãos meus, com o que nos deu o Senhor, que nos guardou, e entregou a tropa que contra nós vinha, nas nossas mãos.

[[v9-30-24]]

^<<v9-30-24,24>>^ E quem vos daria ouvidos nisso? Porque qual é a parte dos que desceram à peleja, tal também será a parte dos que ficaram com a bagagem; igualmente repartirão.

[[v9-30-25]]

^<<v9-30-25,25>>^ O que assim foi desde aquele dia em diante, porquanto o pôs por estatuto e direito em Israel até ao dia de hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ E, chegando Davi a Ziclague, enviou do despojo aos anciãos de Judá, seus amigos, dizendo: Eis aí para vós uma bênção do despojo dos inimigos do Senhor;

[[v9-30-27]]

^<<v9-30-27,27>>^ Aos de Betel, e aos de Ramote do sul, e aos de Jater,

[[v9-30-28]]

^<<v9-30-28,28>>^ E aos de Aroer, e aos de Sifmote, e aos de Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ E aos de Racal, e aos que estavam nas cidades jerameelitas e nas cidades dos queneus,

[[v9-30-30]]

^<<v9-30-30,30>>^ E aos de Hormá, e aos de Corasã, e aos de Ataca,

[[v9-30-31]]

^<<v9-30-31,31>>^ E aos de Hebrom, e a todos os lugares em que andara Davi, ele e os seus homens.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]