include::./index.adoc[]

[[v9-6-0]]
=== 1 Samuel, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v9-6-1]]

^<<v9-6-1,1>>^ Havendo, pois, estado a arca do SENHOR na terra dos filisteus sete meses,

[[v9-6-2]]

^<<v9-6-2,2>>^ Os filisteus chamaram os sacerdotes e os adivinhadores, dizendo: Que faremos nós com a arca do Senhor? Fazei-nos saber como a tornaremos a enviar ao seu lugar.

[[v9-6-3]]

^<<v9-6-3,3>>^ Os quais disseram: Se enviardes a arca do Deus de Israel, não a envieis vazia, porém sem falta enviareis uma oferta para a expiação da culpa; então sereis curados, e se vos fará saber porque a sua mão não se retira de vós.

[[v9-6-4]]

^<<v9-6-4,4>>^ Então disseram: Qual é a expiação da culpa que lhe havemos de enviar? E disseram: Segundo o número dos príncipes dos filisteus, cinco hemorróidas de ouro e cinco ratos de ouro; porquanto a praga é uma mesma sobre todos vós e sobre todos os vossos príncipes.

[[v9-6-5]]

^<<v9-6-5,5>>^ Fazei, pois, umas imagens das vossas hemorróidas e dos vossos ratos, que andam destruindo a terra, e dai glória ao Deus de Israel; porventura aliviará a sua mão de cima de vós, e de cima do vosso deus, e de cima da vossa terra.

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que, pois, endureceríeis o vosso coração, como os egípcios e Faraó endureceram os seus corações? Porventura depois de os haver tratado tão mal, os não deixaram ir, e eles não se foram?

[[v9-6-7]]

^<<v9-6-7,7>>^ Agora, pois, tomai e fazei-vos um carro novo, e tomai duas vacas com crias, sobre as quais não tenha subido o jugo, e atai as vacas ao carro, e tirai delas os seus bezerros e levai-os para casa.

[[v9-6-8]]

^<<v9-6-8,8>>^ Então tomai a arca do Senhor, e ponde-a sobre o carro, e colocai, num cofre, ao seu lado, as figuras de ouro que lhe haveis de oferecer em expiação da culpa, e assim a enviareis, para que se vá.

[[v9-6-9]]

^<<v9-6-9,9>>^ Vede então: Se ela subir pelo caminho do seu termo a Bete-Semes, foi ele quem nos fez este grande mal; e, se não, saberemos que não nos tocou a sua mão, e que isto nos sucedeu por acaso.

[[v9-6-10]]

^<<v9-6-10,10>>^ E assim fizeram aqueles homens, e tomaram duas vacas que criavam, e as ataram ao carro; e os seus bezerros encerraram em casa.

[[v9-6-11]]

^<<v9-6-11,11>>^ E puseram a arca do Senhor sobre o carro, como também o cofre com os ratos de ouro e com as imagens das suas hemorróidas.

[[v9-6-12]]

^<<v9-6-12,12>>^ Então as vacas se encaminharam diretamente pelo caminho de Bete-Semes, e seguiam um mesmo caminho, andando e berrando, sem se desviarem, nem para a direita nem para a esquerda; e os príncipes dos filisteus foram atrás delas, até ao termo de Bete-Semes.

[[v9-6-13]]

^<<v9-6-13,13>>^ E andavam os de Bete-Semes fazendo a sega do trigo no vale, e, levantando os seus olhos, viram a arca, e, vendo-a, se alegraram.

[[v9-6-14]]

^<<v9-6-14,14>>^ E o carro veio ao campo de Josué, o bete-semita, e parou ali onde havia uma grande pedra. E fenderam a madeira do carro, e ofereceram as vacas ao Senhor em holocausto.

[[v9-6-15]]

^<<v9-6-15,15>>^ E os levitas desceram a arca do Senhor, como também o cofre que estava junto a ela, em que estavam os objetos de ouro, e puseram-nos sobre aquela grande pedra; e os homens de Bete-Semes ofereceram holocaustos e sacrifícios ao Senhor no mesmo dia.

[[v9-6-16]]

^<<v9-6-16,16>>^ E, vendo aquilo os cinco príncipes dos filisteus, voltaram para Ecrom no mesmo dia.

[[v9-6-17]]

^<<v9-6-17,17>>^ Estas, pois, são as hemorróidas de ouro que enviaram os filisteus ao Senhor em expiação da culpa: Por Asdode uma, por Gaza outra, por Ascalom outra, por Gate outra, por Ecrom outra.

[[v9-6-18]]

^<<v9-6-18,18>>^ Como também os ratos de ouro, segundo o número de todas as cidades dos filisteus, pertencentes aos cinco príncipes, desde as cidades fortificadas até às aldeias, e até Abel. A grande pedra, sobre a qual puseram a arca do Senhor, ainda está até ao dia de hoje no campo de Josué, o bete-semita.

[[v9-6-19]]

^<<v9-6-19,19>>^ E o Senhor feriu os homens de Bete-Semes, porquanto olharam para dentro da arca do Senhor; feriu do povo cinqüenta mil e setenta homens; então o povo se entristeceu, porquanto o Senhor fizera tão grande estrago entre o povo.

[[v9-6-20]]

^<<v9-6-20,20>>^ Então disseram os homens de Bete-Semes: Quem poderia subsistir perante este santo Senhor Deus? E a quem subirá de nós?

[[v9-6-21]]

^<<v9-6-21,21>>^ Enviaram, pois, mensageiros aos habitantes de Quiriate-Jearim, dizendo: Os filisteus remeteram a arca do Senhor; descei, pois, e fazei-a subir para vós.

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]