include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v12-11-1]]

^<<v12-11-1,1>>^ Vendo, pois, Atalia, mãe de Acazias, que seu filho era morto, levantou-se, e destruiu toda a descendência real.

[[v12-11-2]]

^<<v12-11-2,2>>^ Mas Jeoseba, filha do rei Jorão, irmã de Acazias, tomou a Joás, filho de Acazias, furtando-o dentre os filhos do rei, aos quais matavam, e o pôs, a ele e à sua ama na recâmara, e o escondeu de Atalia, e assim não o mataram.

[[v12-11-3]]

^<<v12-11-3,3>>^ E esteve com ela escondido na casa do Senhor seis anos; e Atalia reinava sobre o país.

[[v12-11-4]]

^<<v12-11-4,4>>^ E no sétimo ano enviou Joiada, e tomou os centuriões, com os capitães, e com os da guarda, e os colocou consigo na casa do Senhor; e fez com eles uma aliança e ajuramentou-os na casa do Senhor; e mostrou-lhes o filho do rei.

[[v12-11-5]]

^<<v12-11-5,5>>^ E deu-lhes ordem, dizendo: Isto é o que haveis de fazer: Uma terça parte de vós, que entrais no sábado, fará a guarda da casa do rei.

[[v12-11-6]]

^<<v12-11-6,6>>^ E outra terça parte estará à porta de Sur; e a outra terça parte à porta detrás dos da guarda; assim fareis a guarda desta casa, afastando a todos.

[[v12-11-7]]

^<<v12-11-7,7>>^ E as duas partes de vós, a saber, todos os que saem no sábado, farão a guarda da casa do Senhor junto ao rei.

[[v12-11-8]]

^<<v12-11-8,8>>^ E rodeareis o rei, cada um com as suas armas na mão, e aquele que entrar entre as fileiras o matarão; e vós estareis com o rei quando sair e quando entrar.

[[v12-11-9]]

^<<v12-11-9,9>>^ Fizeram, pois, os centuriões conforme tudo quanto ordenara o sacerdote Joiada, tomando cada um os seus homens, tanto os que entravam no sábado como os que saíam no sábado; e foram ao sacerdote Joiada.

[[v12-11-10]]

^<<v12-11-10,10>>^ E o sacerdote deu aos centuriões as lanças e os escudos que haviam sido do rei Davi, que estavam na casa do Senhor.

[[v12-11-11]]

^<<v12-11-11,11>>^ E os da guarda se puseram, cada um com as armas na mão, desde o lado direito da casa até ao lado esquerdo da casa, do lado do altar, e do lado da casa, em redor do rei.

[[v12-11-12]]

^<<v12-11-12,12>>^ Então Joiada fez sair o filho do rei, e lhe pôs a coroa, e lhe deu o testemunho; e o fizeram rei, e o ungiram, e bateram as palmas, e disseram: Viva o rei!

[[v12-11-13]]

^<<v12-11-13,13>>^ E Atalia, ouvindo a voz dos da guarda e do povo, foi ter com o povo, na casa do Senhor.

[[v12-11-14]]

^<<v12-11-14,14>>^ E olhou, e eis que o rei estava junto à coluna, conforme o costume, e os príncipes e os trombeteiros junto ao rei, e todo o povo da terra estava alegre e tocava as trombetas; então Atalia rasgou as suas vestes, e clamou: Traição! Traição!

[[v12-11-15]]

^<<v12-11-15,15>>^ Porém o sacerdote Joiada deu ordem aos centuriões que comandavam as tropas, dizendo-lhes: Tirai-a para fora das fileiras, e a quem a seguir matai-o à espada. Porque o sacerdote disse: Não a matem na casa do Senhor.

[[v12-11-16]]

^<<v12-11-16,16>>^ E lançaram mão dela; e ela foi, pelo caminho da entrada dos cavalos, à casa do rei, e ali a mataram.

[[v12-11-17]]

^<<v12-11-17,17>>^ E Joiada fez uma aliança entre o Senhor e o rei e o povo, para que fosse o povo do Senhor; como também entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Então todo o povo da terra entrou na casa de Baal, e a derrubaram, como também os seus altares, e as suas imagens, totalmente quebraram, e a Matã, sacerdote de Baal, mataram diante dos altares; então o sacerdote pôs oficiais sobre a casa do Senhor.

[[v12-11-19]]

^<<v12-11-19,19>>^ E tomou os centuriões, e os capitães, e os da guarda, e todo o povo da terra; e conduziram da casa do Senhor, o rei, e foram, pelo caminho da porta dos da guarda, à casa do rei, e ele se assentou no trono dos reis.

[[v12-11-20]]

^<<v12-11-20,20>>^ E todo o povo da terra se alegrou, e a cidade repousou, depois que mataram a Atalia, à espada, junto à casa do rei,

[[v12-11-21]]

^<<v12-11-21,21>>^ Era Joás da idade de sete anos quando o fizeram rei.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]