include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// acf ?, ACF - Almeida Corrigida Fiel

[[v12-13-1]]

^<<v12-13-1,1>>^ No ano vinte e três de Joás, filho de Acazias, rei de Judá, começou a reinar Jeoacaz, filho de Jeú, sobre Israel, em Samaria, e reinou dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ E fez o que era mau aos olhos do Senhor; porque seguiu os pecados de Jeroboão, filho de Nebate, que fez pecar a Israel; não se apartou deles.

[[v12-13-3]]

^<<v12-13-3,3>>^ Por isso a ira do Senhor se acendeu contra Israel; e entregou-os na mão de Hazael, rei da Síria, e na mão de Ben-Hadade, filho de Hazael, todos aqueles dias.

[[v12-13-4]]

^<<v12-13-4,4>>^ Porém Jeoacaz suplicou diante da face do Senhor; e o Senhor ouviu; porque viu a opressão de Israel, pois o rei da Síria os oprimia.

[[v12-13-5]]

^<<v12-13-5,5>>^ E o Senhor deu um salvador a Israel, e saíram de sob as mãos dos sírios; e os filhos de Israel habitaram nas suas tendas, como no passado

[[v12-13-6]]

^<<v12-13-6,6>>^ (Contudo não se apartaram dos pecados da casa de Jeroboão, com que fez Israel pecar; porém ele andou neles e também o bosque ficou em pé em Samaria).

[[v12-13-7]]

^<<v12-13-7,7>>^ Porque não deixou a Jeoacaz, do povo, senão só cinqüenta cavaleiros, dez carros e dez mil homens de pé, porquanto o rei da Síria os tinha destruído e os tinha feito como o pó, trilhando-os.

[[v12-13-8]]

^<<v12-13-8,8>>^ Ora, o mais dos atos de Jeoacaz, e tudo quanto fez, e o seu poder, porventura não está escrito no livro das crônicas dos reis de Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ E Jeoacaz dormiu com seus pais, e o sepultaram em Samaria; e Jeoás, seu filho, reinou em seu lugar.

[[v12-13-10]]

^<<v12-13-10,10>>^ No ano trinta e sete de Joás, rei de Judá, começou a reinar Jeoás, filho de Jeoacaz, sobre Israel, em Samaria, e reinou dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ E fez o que era mau aos olhos do Senhor; não se apartou de nenhum dos pecados de Jeroboão, filho de Nebate, com que fez Israel pecar, porém andou neles.

[[v12-13-12]]

^<<v12-13-12,12>>^ Ora, o mais dos atos de Jeoás, e tudo quanto fez, e o seu poder, com que pelejou contra Amazias, rei de Judá, porventura não está escrito no livro das crônicas dos reis de Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ E Jeoás dormiu com seus pais, e Jeroboão se assentou no seu trono; e Jeoás foi sepultado em Samaria, junto aos reis de Israel.

[[v12-13-14]]

^<<v12-13-14,14>>^ E Eliseu estava doente da enfermidade de que morreu, e Jeoás, rei de Israel, desceu a ele, e chorou sobre o seu rosto, e disse: Meu pai, meu pai, o carro de Israel, e seus cavaleiros!

[[v12-13-15]]

^<<v12-13-15,15>>^ E Eliseu lhe disse: Toma um arco e flechas. E tomou um arco e flechas.

[[v12-13-16]]

^<<v12-13-16,16>>^ Então disse ao rei de Israel: Põe a tua mão sobre o arco. E pôs sobre ele a sua mão; e Eliseu pôs as suas mãos sobre as do rei.

[[v12-13-17]]

^<<v12-13-17,17>>^ E disse: Abre a janela para o oriente. E abriu-a. Então disse Eliseu: Atira. E atirou; e disse: A flecha do livramento do Senhor é a flecha do livramento contra os sírios; porque ferirás os sírios; em Afeque, até os consumir.

[[v12-13-18]]

^<<v12-13-18,18>>^ Disse mais: Toma as flechas. E tomou-as. Então disse ao rei de Israel: Fere a terra. E feriu-a três vezes, e cessou.

[[v12-13-19]]

^<<v12-13-19,19>>^ Então o homem de Deus se indignou muito contra ele, e disse: Cinco ou seis vezes a deverias ter ferido; então feririas os sírios até os consumir; porém agora só três vezes ferirás os sírios.

[[v12-13-20]]

^<<v12-13-20,20>>^ Depois morreu Eliseu, e o sepultaram. Ora, as tropas dos moabitas invadiram a terra à entrada do ano.

[[v12-13-21]]

^<<v12-13-21,21>>^ E sucedeu que, enterrando eles um homem, eis que viram uma tropa, e lançaram o homem na sepultura de Eliseu; e, caindo nela o homem, e tocando os ossos de Eliseu, reviveu, e se levantou sobre os seus pés.

[[v12-13-22]]

^<<v12-13-22,22>>^ E Hazael, rei da Síria, oprimiu a Israel todos os dias de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ Porém o Senhor teve misericórdia deles, e se compadeceu deles, e tornou-se para eles por amor da sua aliança com Abraão, Isaque e Jacó, e não os quis destruir, e não os lançou ainda da sua presença.

[[v12-13-24]]

^<<v12-13-24,24>>^ E morreu Hazael, rei da Síria e Ben-Hadade, seu filho, reinou em seu lugar.

[[v12-13-25]]

^<<v12-13-25,25>>^ E Jeoás, filho de Jeoacaz, tornou a tomar as cidades das mãos de Ben-Hadade, que ele tinha tomado das mãos de Jeoacaz, seu pai, na guerra; três vezes Jeoás o feriu, e recuperou as cidades de Israel.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]