include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v12-1-1]]

^<<v12-1-1,1>>^ E depois da morte de Acabe, Moabe se rebelou contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ E caiu Acazias pelas grades de um quarto alto, que tinha em Samaria, e adoeceu; e enviou mensageiros, e disse-lhes: Ide, e perguntai a Baal-Zebube, deus de Ecrom, se sararei desta doença.

[[v12-1-3]]

^<<v12-1-3,3>>^ Mas o anjo do Senhor disse a Elias, o tisbita: Levanta-te, sobe para te encontrares com os mensageiros do rei de Samaria, e dize-lhes: Porventura não há Deus em Israel, para irdes consultar a Baal-Zebube, deus de Ecrom?

[[v12-1-4]]

^<<v12-1-4,4>>^ E por isso assim diz o Senhor: Da cama, a que subiste, não descerás, mas sem falta morrerás. Então Elias partiu.

[[v12-1-5]]

^<<v12-1-5,5>>^ E os mensageiros voltaram para ele; e ele lhes disse: Que há, que voltastes?

[[v12-1-6]]

^<<v12-1-6,6>>^ E eles lhe disseram: Um homem saiu ao nosso encontro, e nos disse: Ide, voltai para o rei que vos mandou, e dizei-lhe: Assim diz o Senhor: Porventura não há Deus em Israel, para que mandes consultar a Baal-Zebube, deus de Ecrom? Portanto da cama, a que subiste, não descerás, mas sem falta morrerás.

[[v12-1-7]]

^<<v12-1-7,7>>^ E ele lhes disse: Qual era a aparência do homem que veio ao vosso encontro e vos falou estas palavras?

[[v12-1-8]]

^<<v12-1-8,8>>^ E eles lhe disseram: Era um homem peludo, e com os lombos cingidos de um cinto de couro. Então disse ele: É Elias, o tisbita.

[[v12-1-9]]

^<<v12-1-9,9>>^ Então o rei lhe enviou um capitão de cinqüenta com seus cinqüenta; e, subindo a ele (porque eis que estava assentado no cume do monte), disse-lhe: Homem de Deus, o rei diz: Desce.

[[v12-1-10]]

^<<v12-1-10,10>>^ Mas Elias respondeu, e disse ao capitão de cinqüenta: Se eu, pois, sou homem de Deus, desça fogo do céu, e te consuma a ti e aos teus cinqüenta. Então fogo desceu do céu, e consumiu a ele e aos seus cinqüenta.

[[v12-1-11]]

^<<v12-1-11,11>>^ E tornou o rei a enviar-lhe outro capitão de cinqüenta, com os seus cinqüenta; ele lhe respondeu, dizendo: Homem de Deus, assim diz o rei: Desce depressa.

[[v12-1-12]]

^<<v12-1-12,12>>^ E respondeu Elias: Se eu sou homem de Deus, desça fogo do céu, e te consuma a ti e aos teus cinqüenta. Então o fogo de Deus desceu do céu, e o consumiu a ele e aos seus cinqüenta.

[[v12-1-13]]

^<<v12-1-13,13>>^ E tornou a enviar um terceiro capitão de cinqüenta, com os seus cinqüenta; então subiu o capitão de cinqüenta e, chegando, pôs-se de joelhos diante de Elias, e suplicou-lhe, dizendo: Homem de Deus, seja, peço-te, preciosa aos teus olhos a minha vida, e a vida destes cinqüenta teus servos.

[[v12-1-14]]

^<<v12-1-14,14>>^ Eis que fogo desceu do céu, e consumiu aqueles dois primeiros capitães de cinqüenta, com os seus cinqüenta; porém, agora seja preciosa aos teus olhos a minha vida.

[[v12-1-15]]

^<<v12-1-15,15>>^ Então o anjo do Senhor disse a Elias: Desce com este, não temas. E levantou-se, e desceu com ele ao rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ E disse-lhe: Assim diz o Senhor: Por que enviaste mensageiros a consultar a Baal-Zebube, deus de Ecrom? Porventura é porque não há Deus em Israel, para consultar a sua palavra? Portanto desta cama, a que subiste, não descerás, mas certamente morrerás.

[[v12-1-17]]

^<<v12-1-17,17>>^ Assim, pois, morreu, conforme a palavra do Senhor, que Elias falara; e Jorão começou a reinar no seu lugar no ano segundo de Jeorão, filho de Jeosafá, rei de Judá; porquanto não tinha filho.

[[v12-1-18]]

^<<v12-1-18,18>>^ O mais dos atos de Acazias, tudo quanto fez, porventura não está escrito no livro das crônicas dos reis de Israel?

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]