include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// acf ?, ACF - Almeida Corrigida Fiel

[[v12-24-1]]

^<<v12-24-1,1>>^ Nos seus dias subiu Nabucodonosor, rei de babilônia, e Jeoiaquim ficou três anos seu servo; depois se virou, e se rebelou contra ele.

[[v12-24-2]]

^<<v12-24-2,2>>^ E o Senhor enviou contra ele as tropas dos caldeus, as tropas dos sírios, as tropas dos moabitas e as tropas dos filhos de Amom; e as enviou contra Judá, para o destruir, conforme a palavra do Senhor, que falara pelo ministério de seus servos, os profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ E, na verdade, conforme o mandado do Senhor, assim sucedeu a Judá, para o afastar da sua presença por causa dos pecados de Manassés, conforme tudo quanto fizera.

[[v12-24-4]]

^<<v12-24-4,4>>^ Como também por causa do sangue inocente que derramou; pois encheu a Jerusalém de sangue inocente; e por isso o Senhor não quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Ora, o mais dos atos de Jeoiaquim, e tudo quanto fez, porventura não está escrito no livro das crônicas dos reis de Judá?

[[v12-24-6]]

^<<v12-24-6,6>>^ E Jeoiaquim dormiu com seus pais; e Joaquim, seu filho, reinou em seu lugar.

[[v12-24-7]]

^<<v12-24-7,7>>^ E o rei do Egito nunca mais saiu da sua terra; porque o rei de babilônia tomou tudo quanto era do rei do Egito, desde o rio do Egito até ao rio Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Tinha Joaquim dezoito anos de idade quando começou a reinar, e reinou três meses em Jerusalém; e era o nome de sua mãe, Neusta, filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ E fez o que era mau aos olhos do Senhor, conforme tudo quanto fizera seu pai.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquele tempo subiram os servos de Nabucodonosor, rei de babilônia, a Jerusalém; e a cidade foi cercada.

[[v12-24-11]]

^<<v12-24-11,11>>^ Também veio Nabucodonosor, rei de babilônia, contra a cidade, quando já os seus servos a estavam sitiando.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então saiu Joaquim, rei de Judá, ao rei de babilônia, ele, sua mãe, seus servos, seus príncipes e seus oficiais; e o rei de babilônia o tomou preso, no ano oitavo do seu reinado.

[[v12-24-13]]

^<<v12-24-13,13>>^ E tirou dali todos os tesouros da casa do Senhor e os tesouros da casa do rei; e partiu todos os vasos de ouro, que fizera Salomão, rei de Israel, no templo do Senhor, como o Senhor tinha falado.

[[v12-24-14]]

^<<v12-24-14,14>>^ E transportou a toda a Jerusalém como também a todos os príncipes, e a todos os homens valorosos, dez mil presos, e a todos os artífices e ferreiros; ninguém ficou senão o povo pobre da terra.

[[v12-24-15]]

^<<v12-24-15,15>>^ Assim transportou Joaquim à babilônia; como também a mãe do rei, as mulheres do rei, os seus oficiais e os poderosos da terra levou presos de Jerusalém à babilônia.

[[v12-24-16]]

^<<v12-24-16,16>>^ E todos os homens valentes, até sete mil, e artífices e ferreiros até mil, e todos os homens destros na guerra, a estes o rei de babilônia levou presos para babilônia.

[[v12-24-17]]

^<<v12-24-17,17>>^ E o rei de babilônia estabeleceu a Matanias, seu tio, rei em seu lugar; e lhe mudou o nome para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Tinha Zedequias vinte e um anos de idade quando começou a reinar, e reinou onze anos em Jerusalém; e era o nome de sua mãe Hamutal, filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ E fez o que era mau aos olhos do Senhor, conforme tudo quanto fizera Jeoiaquim.

[[v12-24-20]]

^<<v12-24-20,20>>^ Porque assim sucedeu por causa da ira do SENHOR contra Jerusalém, e contra Judá, até os rejeitar de diante da sua presença; e Zedequias se rebelou contra o rei de babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]