include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// acf ?, ACF - Almeida Corrigida Fiel

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois destas coisas veio a palavra do SENHOR a Abrão em visão, dizendo: Não temas, Abrão, eu sou o teu escudo, o teu grandíssimo galardão.

[[v1-15-2]]

^<<v1-15-2,2>>^ Então disse Abrão: Senhor DEUS, que me hás de dar, pois ando sem filhos, e o mordomo da minha casa é o damasceno Eliézer?

[[v1-15-3]]

^<<v1-15-3,3>>^ Disse mais Abrão: Eis que não me tens dado filhos, e eis que um nascido na minha casa será o meu herdeiro.

[[v1-15-4]]

^<<v1-15-4,4>>^ E eis que veio a palavra do Senhor a ele dizendo: Este não será o teu herdeiro; mas aquele que de tuas entranhas sair, este será o teu herdeiro.

[[v1-15-5]]

^<<v1-15-5,5>>^ Então o levou fora, e disse: Olha agora para os céus, e conta as estrelas, se as podes contar. E disse-lhe: Assim será a tua descendência.

[[v1-15-6]]

^<<v1-15-6,6>>^ E creu ele no Senhor, e imputou-lhe isto por justiça.

[[v1-15-7]]

^<<v1-15-7,7>>^ Disse-lhe mais: Eu sou o Senhor, que te tirei de Ur dos caldeus, para dar-te a ti esta terra, para herdá-la.

[[v1-15-8]]

^<<v1-15-8,8>>^ E disse ele: Senhor DEUS, como saberei que hei de herdá-la?

[[v1-15-9]]

^<<v1-15-9,9>>^ E disse-lhe: Toma-me uma bezerra de três anos, e uma cabra de três anos, e um carneiro de três anos, uma rola e um pombinho.

[[v1-15-10]]

^<<v1-15-10,10>>^ E trouxe-lhe todos estes, e partiu-os pelo meio, e pôs cada parte deles em frente da outra; mas as aves não partiu.

[[v1-15-11]]

^<<v1-15-11,11>>^ E as aves desciam sobre os cadáveres; Abrão, porém, as enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ E pondo-se o sol, um profundo sono caiu sobre Abrão; e eis que grande espanto e grande escuridão caiu sobre ele.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então disse a Abrão: Saibas, de certo, que peregrina será a tua descendência em terra alheia, e será reduzida à escravidão, e será afligida por quatrocentos anos,

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas também eu julgarei a nação, à qual ela tem de servir, e depois sairá com grande riqueza.

[[v1-15-15]]

^<<v1-15-15,15>>^ E tu irás a teus pais em paz; em boa velhice serás sepultado.

[[v1-15-16]]

^<<v1-15-16,16>>^ E a quarta geração tornará para cá; porque a medida da injustiça dos amorreus não está ainda cheia.

[[v1-15-17]]

^<<v1-15-17,17>>^ E sucedeu que, posto o sol, houve escuridão, e eis um forno de fumaça, e uma tocha de fogo, que passou por aquelas metades.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele mesmo dia fez o Senhor uma aliança com Abrão, dizendo: « tua descendência tenho dado esta terra, desde o rio do Egito até ao grande rio Eufrates;

[[v1-15-19]]

^<<v1-15-19,19>>^ E o queneu, e o quenezeu, e o cadmoneu,

[[v1-15-20]]

^<<v1-15-20,20>>^ E o heteu, e o perizeu, e os refains,

[[v1-15-21]]

^<<v1-15-21,21>>^ E o amorreu, e o cananeu, e o girgaseu, e o jebuseu.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]