include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// acf ?, ACF - Almeida Corrigida Fiel

[[v1-48-1]]

^<<v1-48-1,1>>^ E aconteceu, depois destas coisas, que alguém disse a José: Eis que teu pai está enfermo. Então tomou consigo os seus dois filhos, Manassés e Efraim.

[[v1-48-2]]

^<<v1-48-2,2>>^ E alguém participou a Jacó, e disse: Eis que José teu filho vem a ti. E esforçou-se Israel, e assentou-se sobre a cama.

[[v1-48-3]]

^<<v1-48-3,3>>^ E Jacó disse a José: O Deus Todo-Poderoso me apareceu em Luz, na terra de Canaã, e me abençoou.

[[v1-48-4]]

^<<v1-48-4,4>>^ E me disse: Eis que te farei frutificar e multiplicar, e tornar-te-ei uma multidão de povos e darei esta terra à tua descendência depois de ti, em possessão perpétua.

[[v1-48-5]]

^<<v1-48-5,5>>^ Agora, pois, os teus dois filhos, que te nasceram na terra do Egito, antes que eu viesse a ti no Egito, são meus: Efraim e Manassés serão meus, como Rúben e Simeão;

[[v1-48-6]]

^<<v1-48-6,6>>^ Mas a tua geração, que gerarás depois deles, será tua; segundo o nome de seus irmãos serão chamados na sua herança.

[[v1-48-7]]

^<<v1-48-7,7>>^ Vindo, pois, eu de Padã, morreu-me Raquel no caminho, na terra de Canaã, havendo ainda pequena distância para chegar a Efrata; e eu a sepultei ali, no caminho de Efrata, que é Belém.

[[v1-48-8]]

^<<v1-48-8,8>>^ E Israel viu os filhos de José, e disse: Quem são estes?

[[v1-48-9]]

^<<v1-48-9,9>>^ E José disse a seu pai: Eles são meus filhos, que Deus me tem dado aqui. E ele disse: Peço-te, traze-mos aqui, para que os abençoe.

[[v1-48-10]]

^<<v1-48-10,10>>^ Os olhos de Israel, porém, estavam carregados de velhice, já não podia ver; e fê-los chegar a ele, e beijou-os, e abraçou-os.

[[v1-48-11]]

^<<v1-48-11,11>>^ E Israel disse a José: Eu não cuidara ver o teu rosto; e eis que Deus me fez ver também a tua descendência.

[[v1-48-12]]

^<<v1-48-12,12>>^ Então José os tirou dos joelhos de seu pai, e inclinou-se à terra diante da sua face.

[[v1-48-13]]

^<<v1-48-13,13>>^ E tomou José a ambos, a Efraim na sua mão direita, à esquerda de Israel, e Manassés na sua mão esquerda, à direita de Israel, e fê-los chegar a ele.

[[v1-48-14]]

^<<v1-48-14,14>>^ Mas Israel estendeu a sua mão direita e a pôs sobre a cabeça de Efraim, que era o menor, e a sua esquerda sobre a cabeça de Manassés, dirigindo as suas mãos propositadamente, não obstante Manassés ser o primogênito.

[[v1-48-15]]

^<<v1-48-15,15>>^ E abençoou a José, e disse: O Deus, em cuja presença andaram os meus pais Abraão e Isaque, o Deus que me sustentou, desde que eu nasci até este dia;

[[v1-48-16]]

^<<v1-48-16,16>>^ O anjo que me livrou de todo o mal, abençoe estes rapazes, e seja chamado neles o meu nome, e o nome de meus pais Abraão e Isaque, e multipliquem-se como peixes, em multidão, no meio da terra.

[[v1-48-17]]

^<<v1-48-17,17>>^ Vendo, pois, José que seu pai punha a sua mão direita sobre a cabeça de Efraim, foi mau aos seus olhos; e tomou a mão de seu pai, para a transpor de sobre a cabeça de Efraim à cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ E José disse a seu pai: Não assim, meu pai, porque este é o primogênito; põe a tua mão direita sobre a sua cabeça.

[[v1-48-19]]

^<<v1-48-19,19>>^ Mas seu pai recusou, e disse: Eu o sei, meu filho, eu o sei; também ele será um povo, e também ele será grande; contudo o seu irmão menor será maior que ele, e a sua descendência será uma multidão de nações.

[[v1-48-20]]

^<<v1-48-20,20>>^ Assim os abençoou naquele dia, dizendo: Em ti abençoará Israel, dizendo: Deus te faça como a Efraim e como a Manassés. E pôs a Efraim diante de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Depois disse Israel a José: Eis que eu morro, mas Deus será convosco, e vos fará tornar à terra de vossos pais.

[[v1-48-22]]

^<<v1-48-22,22>>^ E eu tenho dado a ti um pedaço da terra a mais do que a teus irmãos, que tomei com a minha espada e com o meu arco, da mão dos amorreus.

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]