include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// acf ?, ACF - Almeida Corrigida Fiel

[[v1-46-1]]

^<<v1-46-1,1>>^ E partiu Israel com tudo quanto tinha, e veio a Berseba, e ofereceu sacrifícios ao Deus de seu pai Isaque.

[[v1-46-2]]

^<<v1-46-2,2>>^ E falou Deus a Israel em visões de noite, e disse: Jacó, Jacó! E ele disse: Eis-me aqui.

[[v1-46-3]]

^<<v1-46-3,3>>^ E disse: Eu sou Deus, o Deus de teu pai; não temas descer ao Egito, porque eu te farei ali uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ E descerei contigo ao Egito, e certamente te farei tornar a subir, e José porá a sua mão sobre os teus olhos.

[[v1-46-5]]

^<<v1-46-5,5>>^ Então levantou-se Jacó de Berseba; e os filhos de Israel levaram a seu pai Jacó, e seus meninos, e as suas mulheres, nos carros que Faraó enviara para o levar.

[[v1-46-6]]

^<<v1-46-6,6>>^ E tomaram o seu gado e os seus bens que tinham adquirido na terra de Canaã, e vieram ao Egito, Jacó e toda a sua descendência com ele;

[[v1-46-7]]

^<<v1-46-7,7>>^ Os seus filhos e os filhos de seus filhos com ele, as filhas, e as filhas de seus filhos, e toda a sua descendência levou consigo ao Egito.

[[v1-46-8]]

^<<v1-46-8,8>>^ E estes são os nomes dos filhos de Israel, que vieram ao Egito, Jacó e seus filhos: Rúben, o primogênito de Jacó.

[[v1-46-9]]

^<<v1-46-9,9>>^ E os filhos de Rúben: Enoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ E os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma mulher cananéia.

[[v1-46-11]]

^<<v1-46-11,11>>^ E os filhos de Levi: Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ E os filhos de Judá: Er, Onã, Selá, Perez e Zerá; Er e Onã, porém, morreram na terra de Canaã; e os filhos de Perez foram Hezrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ E os filhos de Issacar: Tola, Puva, Jó e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ E os filhos de Zebulom: Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Estes são os filhos de Lia, que ela deu a Jacó em Padã-Arã, além de Diná, sua filha; todas as almas de seus filhos e de suas filhas foram trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ E os filhos de Gade: Zifiom, Hagi, Suni, Esbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ E os filhos de Aser: Imna, Isvá, Isvi, Berias e Sera, a irmã deles; e os filhos de Berias: Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Estes são os filhos de Zilpa, a qual Labão deu à sua filha Lia; e deu a Jacó estas dezesseis almas.

[[v1-46-19]]

^<<v1-46-19,19>>^ Os filhos de Raquel, mulher de Jacó: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ E nasceram a José na terra do Egito, Manassés e Efraim, que lhe deu Azenate, filha de Potífera, sacerdote de Om.

[[v1-46-21]]

^<<v1-46-21,21>>^ E os filhos de Benjamim: Belá, Bequer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Estes são os filhos de Raquel, que nasceram a Jacó, ao todo catorze almas.

[[v1-46-23]]

^<<v1-46-23,23>>^ E o filho de Dã: Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ E os filhos de Naftali: Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Estes são os filhos de Bila, a qual Labão deu à sua filha Raquel; e deu estes a Jacó; todas as almas foram sete.

[[v1-46-26]]

^<<v1-46-26,26>>^ Todas as almas que vieram com Jacó ao Egito, que saíram dos seus lombos, fora as mulheres dos filhos de Jacó, todas foram sessenta e seis almas.

[[v1-46-27]]

^<<v1-46-27,27>>^ E os filhos de José, que lhe nasceram no Egito, eram duas almas. Todas as almas da casa de Jacó, que vieram ao Egito, eram setenta.

[[v1-46-28]]

^<<v1-46-28,28>>^ E Jacó enviou Judá adiante de si a José, para o encaminhar a Gósen; e chegaram à terra de Gósen.

[[v1-46-29]]

^<<v1-46-29,29>>^ Então José aprontou o seu carro, e subiu ao encontro de Israel, seu pai, a Gósen. E, apresentando-se-lhe, lançou-se ao seu pescoço, e chorou sobre o seu pescoço longo tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ E Israel disse a José: Morra eu agora, pois já tenho visto o teu rosto, que ainda vives.

[[v1-46-31]]

^<<v1-46-31,31>>^ Depois disse José a seus irmãos, e à casa de seu pai: Eu subirei e anunciarei a Faraó, e lhe direi: Meus irmãos e a casa de meu pai, que estavam na terra de Canaã, vieram a mim!

[[v1-46-32]]

^<<v1-46-32,32>>^ E os homens são pastores de ovelhas, porque são homens de gado, e trouxeram consigo as suas ovelhas, e as suas vacas, e tudo o que têm.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando, pois, acontecer que Faraó vos chamar, e disser: Qual é o vosso negócio?

[[v1-46-34]]

^<<v1-46-34,34>>^ Então direis: Teus servos foram homens de gado desde a nossa mocidade até agora, tanto nós como os nossos pais; para que habiteis na terra de Gósen, porque todo o pastor de ovelhas é abominação aos egípcios.

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]