include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// acf ?, ACF - Almeida Corrigida Fiel

[[v35-3-1]]

^<<v35-3-1,1>>^ Oração do profeta Habacuque sobre Sigionote.

[[v35-3-2]]

^<<v35-3-2,2>>^ Ouvi, Senhor, a tua palavra, e temi; aviva, ó Senhor, a tua obra no meio dos anos, no meio dos anos faze-a conhecida; na tua ira lembra-te da misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus veio de Temã, e do monte de Parã o Santo (Selá). A sua glória cobriu os céus, e a terra encheu-se do seu louvor.

[[v35-3-4]]

^<<v35-3-4,4>>^ E o resplendor se fez como a luz, raios brilhantes saíam da sua mão, e ali estava o esconderijo da sua força.

[[v35-3-5]]

^<<v35-3-5,5>>^ Adiante dele ia a peste, e brasas ardentes saíam dos seus passos.

[[v35-3-6]]

^<<v35-3-6,6>>^ Parou, e mediu a terra; olhou, e separou as nações; e os montes perpétuos foram esmiuçados; os outeiros eternos se abateram, porque os caminhos eternos lhe pertencem.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vi as tendas de Cusã em aflição; tremiam as cortinas da terra de Midiã.

[[v35-3-8]]

^<<v35-3-8,8>>^ Acaso é contra os rios, Senhor, que estás irado? É contra os ribeiros a tua ira, ou contra o mar o teu furor, visto que andas montado sobre os teus cavalos, e nos teus carros de salvação?

[[v35-3-9]]

^<<v35-3-9,9>>^ Descoberto se movimentou o teu arco; os juramentos feitos às tribos foram uma palavra segura. (Selá. ) Tu fendeste a terra com rios.

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes te viram, e tremeram; a inundação das águas passou; o abismo deu a sua voz, levantou ao alto as suas mãos.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua pararam nas suas moradas; andaram à luz das tuas flechas, ao resplendor do relâmpago da tua lança.

[[v35-3-12]]

^<<v35-3-12,12>>^ Com indignação marchaste pela terra, com ira trilhaste os gentios.

[[v35-3-13]]

^<<v35-3-13,13>>^ Tu saíste para salvação do teu povo, para salvação do teu ungido; tu feriste a cabeça da casa do ímpio, descobrindo o alicerce até ao pescoço. (Selá.)

[[v35-3-14]]

^<<v35-3-14,14>>^ Tu traspassaste com as suas próprias lanças a cabeça das suas vilas; eles me acometeram tempestuosos para me espalharem; alegravam-se, como se estivessem para devorar o pobre em segredo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Tu com os teus cavalos marchaste pelo mar, pela massa de grandes águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvindo-o eu, o meu ventre se comoveu, à sua voz tremeram os meus lábios; entrou a podridão nos meus ossos, e estremeci dentro de mim; no dia da angústia descansarei, quando subir contra o povo que invadirá com suas tropas.

[[v35-3-17]]

^<<v35-3-17,17>>^ Porque ainda que a figueira não floresça, nem haja fruto na vide; ainda que decepcione o produto da oliveira, e os campos não produzam mantimento; ainda que as ovelhas da malhada sejam arrebatadas, e nos currais não haja gado;

[[v35-3-18]]

^<<v35-3-18,18>>^ Todavia eu me alegrarei no Senhor; exultarei no Deus da minha salvação.

[[v35-3-19]]

^<<v35-3-19,19>>^ O Senhor Deus é a minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas. (Para o cantor-mor sobre os meus instrumentos de corda).

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]