include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v35-2-1]]

^<<v35-2-1,1>>^ Sobre a minha guarda estarei, e sobre a fortaleza me apresentarei e vigiarei, para ver o que falará a mim, e o que eu responderei quando eu for argüido.

[[v35-2-2]]

^<<v35-2-2,2>>^ Então o Senhor me respondeu, e disse: Escreve a visão e torna-a bem legível sobre tábuas, para que a possa ler quem passa correndo.

[[v35-2-3]]

^<<v35-2-3,3>>^ Porque a visão é ainda para o tempo determinado, mas se apressa para o fim, e não enganará; se tardar, espera-o, porque certamente virá, não tardará.

[[v35-2-4]]

^<<v35-2-4,4>>^ Eis que a sua alma está orgulhosa, não é reta nele; mas o justo pela sua fé viverá.

[[v35-2-5]]

^<<v35-2-5,5>>^ Tanto mais que, por ser dado ao vinho é desleal; homem soberbo que não permanecerá; que alarga como o inferno a sua alma; e é como a morte que não se farta, e ajunta a si todas as nações, e congrega a si todos os povos.

[[v35-2-6]]

^<<v35-2-6,6>>^ Não levantarão, pois, todos estes contra ele uma parábola e um provérbio sarcástico contra ele? E se dirá: Ai daquele que multiplica o que não é seu! (até quando? ) e daquele que carrega sobre si dívidas!

[[v35-2-7]]

^<<v35-2-7,7>>^ Porventura não se levantarão de repente os teus extorquiadores, e não despertarão os que te farão tremer, e não lhes servirás tu de despojo?

[[v35-2-8]]

^<<v35-2-8,8>>^ Porquanto despojaste a muitas nações, todos os demais povos te despojarão a ti, por causa do sangue dos homens, e da violência feita à terra, à cidade, e a todos os que nela habitam.

[[v35-2-9]]

^<<v35-2-9,9>>^ Ai daquele que, para a sua casa, ajunta cobiçosamente bens mal adquiridos, para pôr o seu ninho no alto, a fim de se livrar do poder do mal!

[[v35-2-10]]

^<<v35-2-10,10>>^ Vergonha maquinaste para a tua casa; destruindo tu a muitos povos, pecaste contra a tua alma.

[[v35-2-11]]

^<<v35-2-11,11>>^ Porque a pedra clamará da parede, e a trave lhe responderá do madeiramento.

[[v35-2-12]]

^<<v35-2-12,12>>^ Ai daquele que edifica a cidade com sangue, e que funda a cidade com iniqüidade!

[[v35-2-13]]

^<<v35-2-13,13>>^ Porventura não vem do Senhor dos Exércitos que os povos trabalhem pelo fogo e os homens se cansem em vão?

[[v35-2-14]]

^<<v35-2-14,14>>^ Porque a terra se encherá do conhecimento da glória do Senhor, como as águas cobrem o mar.

[[v35-2-15]]

^<<v35-2-15,15>>^ Ai daquele que dá de beber ao seu companheiro! Ai de ti, que adicionas à bebida o teu furor, e o embebedas para ver a sua nudez!

[[v35-2-16]]

^<<v35-2-16,16>>^ Serás farto de ignomínia em lugar de honra; bebe tu também, e sê como um incircunciso; o cálice da mão direita do Senhor voltará a ti, e ignomínia cairá sobre a tua glória.

[[v35-2-17]]

^<<v35-2-17,17>>^ Porque a violência cometida contra o Líbano te cobrirá, e a destruição das feras te amedrontará, por causa do sangue dos homens, e da violência feita à terra, à cidade, e a todos os que nela habitam.

[[v35-2-18]]

^<<v35-2-18,18>>^ Que aproveita a imagem de escultura, depois que a esculpiu o seu artífice? Ela é imagem de fundição que ensina mentira, para que quem a formou confie na sua obra, fazendo ídolos mudos?

[[v35-2-19]]

^<<v35-2-19,19>>^ Ai daquele que diz ao pau: Acorda! e à pedra muda: Desperta! Pode isso ensinar? Eis que está coberta de ouro e de prata, mas dentro dela não há espírito algum.

[[v35-2-20]]

^<<v35-2-20,20>>^ Mas o Senhor está no seu santo templo; cale-se diante dele toda a terra.

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]