include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v33-5-1]]

^<<v33-5-1,1>>^ Agora ajunta-te em tropas, ó filha de tropas; pôr-se-á cerco contra nós; ferirão com a vara na face ao juiz de Israel.

[[v33-5-2]]

^<<v33-5-2,2>>^ E tu, Belém Efrata, posto que pequena entre os milhares de Judá, de ti me sairá o que governará em Israel, e cujas saídas são desde os tempos antigos, desde os dias da eternidade.

[[v33-5-3]]

^<<v33-5-3,3>>^ Portanto os entregará até ao tempo em que a que está de parto tiver dado à luz; então o restante de seus irmãos voltará aos filhos de Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ E ele permanecerá, e apascentará ao povo na força do Senhor, na excelência do nome do Senhor seu Deus; e eles permanecerão, porque agora será engrandecido até aos fins da terra.

[[v33-5-5]]

^<<v33-5-5,5>>^ E este será a nossa paz; quando a Assíria vier à nossa terra, e quando pisar em nossos palácios, levantaremos contra ela sete pastores e oito príncipes dentre os homens.

[[v33-5-6]]

^<<v33-5-6,6>>^ Esses consumirão a terra da Assíria à espada, e a terra de Ninrode nas suas entradas. Assim nos livrará da Assíria, quando vier à nossa terra, e quando calcar os nossos termos.

[[v33-5-7]]

^<<v33-5-7,7>>^ E o remanescente de Jacó estará no meio de muitos povos, como orvalho da parte do Senhor, como chuvisco sobre a erva, que não espera pelo homem, nem aguarda a filhos de homens.

[[v33-5-8]]

^<<v33-5-8,8>>^ E o restante de Jacó estará entre os gentios, no meio de muitos povos, como um leão entre os animais do bosque, como um leãozinho entre os rebanhos de ovelhas, o qual, quando passar, pisará e despedaçará, sem que haja quem as livre.

[[v33-5-9]]

^<<v33-5-9,9>>^ A tua mão se exaltará sobre os teus adversários; e todos os teus inimigos serão exterminados.

[[v33-5-10]]

^<<v33-5-10,10>>^ E sucederá naquele dia, diz o Senhor, que eu exterminarei do meio de ti os teus cavalos, e destruirei os teus carros.

[[v33-5-11]]

^<<v33-5-11,11>>^ E destruirei as cidades da tua terra, e derrubarei todas as tuas fortalezas;

[[v33-5-12]]

^<<v33-5-12,12>>^ E exterminarei as feitiçarias da tua mão; e não terás adivinhadores;

[[v33-5-13]]

^<<v33-5-13,13>>^ E destruirei do meio de ti as tuas imagens de escultura e as tuas estátuas; e tu não te inclinarás mais diante da obra das tuas mãos.

[[v33-5-14]]

^<<v33-5-14,14>>^ E arrancarei os teus bosques do meio de ti; e destruirei as tuas cidades.

[[v33-5-15]]

^<<v33-5-15,15>>^ E com ira e com furor farei vingança sobre os gentios que não ouvem.

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]