include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v33-2-1]]

^<<v33-2-1,1>>^ Ai daqueles que nas suas camas intentam a iniqüidade, e maquinam o mal; à luz da alva o praticam, porque está no poder da sua mão!

[[v33-2-2]]

^<<v33-2-2,2>>^ E cobiçam campos, e roubam-nos, cobiçam casas, e arrebatam-nas; assim fazem violência a um homem e à sua casa, a uma pessoa e à sua herança.

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o Senhor: Eis que projeto um mal contra esta família, do qual não tirareis os vossos pescoços, e não andareis tão altivos, porque o tempo será mau.

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia se levantará sobre vós um provérbio, e se lamentará pranto lastimoso, dizendo: Nós estamos inteiramente desolados; a porção do meu povo ele a troca; como me despoja! Tira os nossos campos e os reparte!

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, não terás tu na congregação do Senhor quem lance o cordel pela sorte.

[[v33-2-6]]

^<<v33-2-6,6>>^ Não profetizeis aos que profetizam; eles não profetizarão para eles, pois não se apartará a sua vergonha.

[[v33-2-7]]

^<<v33-2-7,7>>^ Ó vós que sois chamados casa de Jacó, porventura encurtou-se o Espírito do Senhor? São estas as suas obras? E não é assim que fazem bem as minhas palavras ao que anda retamente?

[[v33-2-8]]

^<<v33-2-8,8>>^ Mas ontem, se levantou o meu povo como inimigo; de sobre a vestidura tirastes a capa daqueles que passavam seguros, como homens que voltavam da guerra.

[[v33-2-9]]

^<<v33-2-9,9>>^ Lançastes fora as mulheres do meu povo, da casa das suas delícias; das suas crianças tirastes para sempre a minha glória.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantai-vos, e ide-vos, porque este não é lugar de descanso; por causa da imundícia que traz destruição, sim, destruição enorme.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se houver alguém que, andando com espírito de falsidade, mentir, dizendo: Eu te profetizarei sobre o vinho e a bebida forte; será esse tal o profeta deste povo.

[[v33-2-12]]

^<<v33-2-12,12>>^ Certamente te ajuntarei todo, ó Jacó; certamente congregarei o restante de Israel; pô-los-ei todos juntos, como ovelhas de Bozra; como o rebanho no meio do seu pasto, farão estrondo por causa da multidão dos homens.

[[v33-2-13]]

^<<v33-2-13,13>>^ Subirá diante deles o que abrirá o caminho; eles romperão, e entrarão pela porta, e sairão por ela; e o rei irá adiante deles, e o Senhor à testa deles.

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]