include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v37-2-1]]

^<<v37-2-1,1>>^ No sétimo mês, ao vigésimo primeiro dia do mês, veio a palavra do SENHOR por intermédio do profeta Ageu, dizendo:

[[v37-2-2]]

^<<v37-2-2,2>>^ Fala agora a Zorobabel, filho de Sealtiel, governador de Judá, e a Josué, filho de Jozadaque, sumo sacerdote, e ao restante do povo, dizendo:

[[v37-2-3]]

^<<v37-2-3,3>>^ Quem há entre vós que, tendo ficado, viu esta casa na sua primeira glória? E como a vedes agora? Não é esta como nada diante dos vossos olhos, comparada com aquela?

[[v37-2-4]]

^<<v37-2-4,4>>^ Ora, pois, esforça-te, Zorobabel, diz o Senhor, e esforça-te, Josué, filho de Jozadaque, sumo sacerdote, e esforça-te, todo o povo da terra, diz o Senhor, e trabalhai; porque eu sou convosco, diz o Senhor dos Exércitos.

[[v37-2-5]]

^<<v37-2-5,5>>^ Segundo a palavra da aliança que fiz convosco, quando saístes do Egito, o meu Espírito permanece no meio de vós; não temais.

[[v37-2-6]]

^<<v37-2-6,6>>^ Porque assim diz o Senhor dos Exércitos: Ainda uma vez, daqui a pouco, farei tremer os céus e a terra, o mar e a terra seca;

[[v37-2-7]]

^<<v37-2-7,7>>^ E farei tremer todas as nações, e virão coisas preciosas de todas as nações, e encherei esta casa de glória, diz o Senhor dos Exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ Minha é a prata, e meu é o ouro, disse o Senhor dos Exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ A glória desta última casa será maior do que a da primeira, diz o Senhor dos Exércitos, e neste lugar darei a paz, diz o Senhor dos Exércitos.

[[v37-2-10]]

^<<v37-2-10,10>>^ Ao vigésimo quarto dia do mês nono, no segundo ano de Dario, veio a palavra do Senhor por intermédio do profeta Ageu, dizendo:

[[v37-2-11]]

^<<v37-2-11,11>>^ Assim diz o Senhor dos Exércitos: Pergunta agora aos sacerdotes, acerca da lei, dizendo:

[[v37-2-12]]

^<<v37-2-12,12>>^ Se alguém leva carne santa na orla das suas vestes, e com ela tocar no pão, ou no guisado, ou no vinho, ou no azeite, ou em outro qualquer mantimento, porventura ficará isto santificado? E os sacerdotes responderam: Não.

[[v37-2-13]]

^<<v37-2-13,13>>^ E disse Ageu: Se alguém que for contaminado pelo contato com o corpo morto, tocar nalguma destas coisas, ficará ela imunda? E os sacerdotes responderam, dizendo: Ficará imunda.

[[v37-2-14]]

^<<v37-2-14,14>>^ Então respondeu Ageu, dizendo: Assim é este povo, e assim é esta nação diante de mim, diz o Senhor; e assim é toda a obra das suas mãos; e tudo o que ali oferecem imundo é.

[[v37-2-15]]

^<<v37-2-15,15>>^ Agora, pois, eu vos rogo, considerai isto, desde este dia em diante, antes que se lançasse pedra sobre pedra no templo do Senhor,

[[v37-2-16]]

^<<v37-2-16,16>>^ Antes que sucedessem estas coisas, vinha alguém a um montão de grão, de vinte medidas, e havia somente dez; quando vinha ao lagar para tirar cinqüenta, havia somente vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Feri-vos com queimadura, e com ferrugem, e com saraiva, em toda a obra das vossas mãos, e não houve entre vós quem voltasse para mim, diz o Senhor.

[[v37-2-18]]

^<<v37-2-18,18>>^ Considerai, pois, vos rogo, desde este dia em diante; desde o vigésimo quarto dia do mês nono, desde o dia em que se fundou o templo do Senhor, considerai essas coisas.

[[v37-2-19]]

^<<v37-2-19,19>>^ Porventura há ainda semente no celeiro? Além disso a videira, a figueira, a romeira, a oliveira, não têm dado os seus frutos; mas desde este dia vos abençoarei.

[[v37-2-20]]

^<<v37-2-20,20>>^ E veio a palavra do Senhor segunda vez a Ageu, aos vinte e quatro dias do mês, dizendo:

[[v37-2-21]]

^<<v37-2-21,21>>^ Fala a Zorobabel, governador de Judá, dizendo: Farei tremer os céus e a terra;

[[v37-2-22]]

^<<v37-2-22,22>>^ E transtornarei o trono dos reinos, e destruirei a força dos reinos dos gentios; e transtornarei os carros e os que neles andam; e os cavalos e os seus cavaleiros cairão, cada um pela espada do seu irmão.

[[v37-2-23]]

^<<v37-2-23,23>>^ Naquele dia, diz o Senhor dos Exércitos, tomar-te-ei, ó Zorobabel, servo meu, filho de Sealtiel, diz o Senhor, e far-te-ei como um anel de selar; porque te escolhi, diz o Senhor dos Exércitos.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]