include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do SENHOR, por intermédio do profeta Ageu, a Zorobabel, filho de Sealtiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ Assim fala o Senhor dos Exércitos, dizendo: Este povo diz: Não veio ainda o tempo, o tempo em que a casa do Senhor deve ser edificada.

[[v37-1-3]]

^<<v37-1-3,3>>^ Veio, pois, a palavra do Senhor, por intermédio do profeta Ageu, dizendo:

[[v37-1-4]]

^<<v37-1-4,4>>^ Porventura é para vós tempo de habitardes nas vossas casas forradas, enquanto esta casa fica deserta?

[[v37-1-5]]

^<<v37-1-5,5>>^ Ora, pois, assim diz o Senhor dos Exércitos: Considerai os vossos caminhos.

[[v37-1-6]]

^<<v37-1-6,6>>^ Semeais muito, e recolheis pouco; comeis, porém não vos fartais; bebeis, porém não vos saciais; vestis-vos, porém ninguém se aquece; e o que recebe salário, recebe-o num saco furado.

[[v37-1-7]]

^<<v37-1-7,7>>^ Assim diz o Senhor dos Exércitos: Considerai os vossos caminhos.

[[v37-1-8]]

^<<v37-1-8,8>>^ Subi ao monte, e trazei madeira, e edificai a casa; e dela me agradarei, e serei glorificado, diz o Senhor.

[[v37-1-9]]

^<<v37-1-9,9>>^ Esperastes o muito, mas eis que veio a ser pouco; e esse pouco, quando o trouxestes para casa, eu dissipei com um sopro. Por que causa? disse o Senhor dos Exércitos. Por causa da minha casa, que está deserta, enquanto cada um de vós corre à sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso retém os céus sobre vós o orvalho, e a terra detém os seus frutos.

[[v37-1-11]]

^<<v37-1-11,11>>^ E mandei vir a seca sobre a terra, e sobre os montes, e sobre o trigo, e sobre o mosto, e sobre o azeite, e sobre o que a terra produz; como também sobre os homens, e sobre o gado, e sobre todo o trabalho das mãos.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então Zorobabel, filho de Sealtiel, e Josué, filho de Jozadaque, sumo sacerdote, e todo o restante do povo obedeceram à voz do Senhor seu Deus, e às palavras do profeta Ageu, assim como o Senhor seu Deus o enviara; e temeu o povo diante do Senhor.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o mensageiro do Senhor, falou ao povo conforme a mensagem do Senhor, dizendo: Eu sou convosco, diz o Senhor.

[[v37-1-14]]

^<<v37-1-14,14>>^ E o Senhor suscitou o espírito de Zorobabel, filho de Sealtiel, governador de Judá, e o espírito de Josué, filho de Jozadaque, sumo sacerdote, e o espírito de todo o restante do povo, e eles vieram, e fizeram a obra na casa do Senhor dos Exércitos, seu Deus,

[[v37-1-15]]

^<<v37-1-15,15>>^ Ao vigésimo quarto dia do sexto mês, no segundo ano do rei Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]