include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-30-1]]

^<<v18-30-1,1>>^ Agora, porém, se riem de mim os de menos idade do que eu, cujos pais eu teria desdenhado de pôr com os cães do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ De que também me serviria a força das mãos daqueles, cujo vigor se tinha esgotado?

[[v18-30-3]]

^<<v18-30-3,3>>^ De míngua e fome se debilitaram; e recolhiam-se para os lugares secos, tenebrosos, assolados e desertos.

[[v18-30-4]]

^<<v18-30-4,4>>^ Apanhavam malvas junto aos arbustos, e o seu mantimento eram as raízes dos zimbros.

[[v18-30-5]]

^<<v18-30-5,5>>^ Do meio dos homens eram expulsos, e gritavam contra eles, como contra o ladrão;

[[v18-30-6]]

^<<v18-30-6,6>>^ Para habitarem nos barrancos dos vales, e nas cavernas da terra e das rochas.

[[v18-30-7]]

^<<v18-30-7,7>>^ Bramavam entre os arbustos, e ajuntavam-se debaixo das urtigas.

[[v18-30-8]]

^<<v18-30-8,8>>^ Eram filhos de doidos, e filhos de gente sem nome, e da terra foram expulsos.

[[v18-30-9]]

^<<v18-30-9,9>>^ Agora, porém, sou a sua canção, e lhes sirvo de provérbio.

[[v18-30-10]]

^<<v18-30-10,10>>^ Abominam-me, e fogem para longe de mim, e no meu rosto não se privam de cuspir.

[[v18-30-11]]

^<<v18-30-11,11>>^ Porque Deus desatou a sua corda, e me oprimiu, por isso sacudiram de si o freio perante o meu rosto.

[[v18-30-12]]

^<<v18-30-12,12>>^ À direita se levantam os moços; empurram os meus pés, e preparam contra mim os seus caminhos de destruição.

[[v18-30-13]]

^<<v18-30-13,13>>^ Desbaratam-me o caminho; promovem a minha miséria; contra eles não há ajudador.

[[v18-30-14]]

^<<v18-30-14,14>>^ Vêm contra mim como por uma grande brecha, e revolvem-se entre a assolação.

[[v18-30-15]]

^<<v18-30-15,15>>^ Sobrevieram-me pavores; como vento perseguem a minha honra, e como nuvem passou a minha felicidade.

[[v18-30-16]]

^<<v18-30-16,16>>^ E agora derrama-se em mim a minha alma; os dias da aflição se apoderaram de mim.

[[v18-30-17]]

^<<v18-30-17,17>>^ De noite se me traspassam os meus ossos, e os meus nervos não descansam.

[[v18-30-18]]

^<<v18-30-18,18>>^ Pela grandeza do meu mal está desfigurada a minha veste, que, como a gola da minha túnica, me cinge.

[[v18-30-19]]

^<<v18-30-19,19>>^ Lançou-me na lama, e fiquei semelhante ao pó e à cinza.

[[v18-30-20]]

^<<v18-30-20,20>>^ Clamo a ti, porém, tu não me respondes; estou em pé, porém, para mim não atentas.

[[v18-30-21]]

^<<v18-30-21,21>>^ Tornaste-te cruel contra mim; com a força da tua mão resistes violentamente.

[[v18-30-22]]

^<<v18-30-22,22>>^ Levantas-me sobre o vento, fazes-me cavalgar sobre ele, e derretes-me o ser.

[[v18-30-23]]

^<<v18-30-23,23>>^ Porque eu sei que me levarás à morte e à casa do ajuntamento determinada a todos os viventes.

[[v18-30-24]]

^<<v18-30-24,24>>^ Porém não estenderá a mão para o túmulo, ainda que eles clamem na sua destruição.

[[v18-30-25]]

^<<v18-30-25,25>>^ Porventura não chorei sobre aquele que estava aflito, ou não se angustiou a minha alma pelo necessitado?

[[v18-30-26]]

^<<v18-30-26,26>>^ Todavia aguardando eu o bem, então me veio o mal, esperando eu a luz, veio a escuridão.

[[v18-30-27]]

^<<v18-30-27,27>>^ As minhas entranhas fervem e não estão quietas; os dias da aflição me surpreendem.

[[v18-30-28]]

^<<v18-30-28,28>>^ Denegrido ando, porém não do sol; levantando-me na congregação, clamo por socorro.

[[v18-30-29]]

^<<v18-30-29,29>>^ Irmão me fiz dos chacais, e companheiro dos avestruzes.

[[v18-30-30]]

^<<v18-30-30,30>>^ Enegreceu-se a minha pele sobre mim, e os meus ossos estão queimados do calor.

[[v18-30-31]]

^<<v18-30-31,31>>^ A minha harpa se tornou em luto, e o meu órgão em voz dos que choram.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]