include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-23-1]]

^<<v18-23-1,1>>^ Respondeu, porém, Jó, dizendo:

[[v18-23-2]]

^<<v18-23-2,2>>^ Ainda hoje a minha queixa está em amargura; a minha mão pesa sobre meu gemido.

[[v18-23-3]]

^<<v18-23-3,3>>^ Ah, se eu soubesse onde o poderia achar! Então me chegaria ao seu tribunal.

[[v18-23-4]]

^<<v18-23-4,4>>^ Exporia ante ele a minha causa, e a minha boca encheria de argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Saberia as palavras com que ele me responderia, e entenderia o que me dissesse.

[[v18-23-6]]

^<<v18-23-6,6>>^ Porventura segundo a grandeza de seu poder contenderia comigo? Não: ele antes me atenderia.

[[v18-23-7]]

^<<v18-23-7,7>>^ Ali o reto pleitearia com ele, e eu me livraria para sempre do meu Juiz.

[[v18-23-8]]

^<<v18-23-8,8>>^ Eis que se me adianto, ali não está; se torno para trás, não o percebo.

[[v18-23-9]]

^<<v18-23-9,9>>^ Se opera à esquerda, não o vejo; se se encobre à direita, não o diviso.

[[v18-23-10]]

^<<v18-23-10,10>>^ Porém ele sabe o meu caminho; provando-me ele, sairei como o ouro.

[[v18-23-11]]

^<<v18-23-11,11>>^ Nas suas pisadas os meus pés se afirmaram; guardei o seu caminho, e não me desviei dele.

[[v18-23-12]]

^<<v18-23-12,12>>^ Do preceito de seus lábios nunca me apartei, e as palavras da sua boca guardei mais do que a minha porção.

[[v18-23-13]]

^<<v18-23-13,13>>^ Mas, se ele resolveu alguma coisa, quem então o desviará? O que a sua alma quiser, isso fará.

[[v18-23-14]]

^<<v18-23-14,14>>^ Porque cumprirá o que está ordenado a meu respeito, e muitas coisas como estas ainda tem consigo.

[[v18-23-15]]

^<<v18-23-15,15>>^ Por isso me perturbo perante ele, e quando isto considero, temo-me dele.

[[v18-23-16]]

^<<v18-23-16,16>>^ Porque Deus macerou o meu coração, e o Todo-Poderoso me perturbou.

[[v18-23-17]]

^<<v18-23-17,17>>^ Porquanto não fui desarraigado por causa das trevas, e nem encobriu o meu rosto com a escuridão.

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]