include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-29-1]]

^<<v18-29-1,1>>^ E prosseguiu Jó no seu discurso, dizendo:

[[v18-29-2]]

^<<v18-29-2,2>>^ Ah! quem me dera ser como eu fui nos meses passados, como nos dias em que Deus me guardava!

[[v18-29-3]]

^<<v18-29-3,3>>^ Quando fazia resplandecer a sua lâmpada sobre a minha cabeça e quando eu pela sua luz caminhava pelas trevas.

[[v18-29-4]]

^<<v18-29-4,4>>^ Como fui nos dias da minha mocidade, quando o segredo de Deus estava sobre a minha tenda;

[[v18-29-5]]

^<<v18-29-5,5>>^ Quando o Todo-Poderoso ainda estava comigo, e os meus filhos em redor de mim.

[[v18-29-6]]

^<<v18-29-6,6>>^ Quando lavava os meus passos na manteiga, e da rocha me corriam ribeiros de azeite;

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando eu saía para a porta da cidade, e na rua fazia preparar a minha cadeira,

[[v18-29-8]]

^<<v18-29-8,8>>^ Os moços me viam, e se escondiam, e até os idosos se levantavam e se punham em pé;

[[v18-29-9]]

^<<v18-29-9,9>>^ Os príncipes continham as suas palavras, e punham a mão sobre a sua boca;

[[v18-29-10]]

^<<v18-29-10,10>>^ A voz dos nobres se calava, e a sua língua apegava-se ao seu paladar.

[[v18-29-11]]

^<<v18-29-11,11>>^ Ouvindo-me algum ouvido, me tinha por bem-aventurado; vendo-me algum olho, dava testemunho de mim;

[[v18-29-12]]

^<<v18-29-12,12>>^ Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse.

[[v18-29-13]]

^<<v18-29-13,13>>^ A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.

[[v18-29-14]]

^<<v18-29-14,14>>^ Vestia-me da justiça, e ela me servia de vestimenta; como manto e diadema era a minha justiça.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eu me fazia de olhos para o cego, e de pés para o coxo.

[[v18-29-16]]

^<<v18-29-16,16>>^ Dos necessitados era pai, e as causas de que eu não tinha conhecimento inquiria com diligência.

[[v18-29-17]]

^<<v18-29-17,17>>^ E quebrava os queixos do perverso, e dos seus dentes tirava a presa.

[[v18-29-18]]

^<<v18-29-18,18>>^ E dizia: No meu ninho expirarei, e multiplicarei os meus dias como a areia.

[[v18-29-19]]

^<<v18-29-19,19>>^ A minha raiz se estendia junto às águas, e o orvalho permanecia sobre os meus ramos;

[[v18-29-20]]

^<<v18-29-20,20>>^ A minha honra se renovava em mim, e o meu arco se reforçava na minha mão.

[[v18-29-21]]

^<<v18-29-21,21>>^ Ouviam-me e esperavam, e em silêncio atendiam ao meu conselho.

[[v18-29-22]]

^<<v18-29-22,22>>^ Havendo eu falado, não replicavam, e minhas razões destilavam sobre eles;

[[v18-29-23]]

^<<v18-29-23,23>>^ Porque me esperavam, como à chuva; e abriam a sua boca, como à chuva tardia.

[[v18-29-24]]

^<<v18-29-24,24>>^ Se eu ria para eles, não o criam, e a luz do meu rosto não faziam abater;

[[v18-29-25]]

^<<v18-29-25,25>>^ Eu escolhia o seu caminho, assentava-me como chefe, e habitava como rei entre as suas tropas; como aquele que consola os que pranteiam.

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]