include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-27-1]]

^<<v18-27-1,1>>^ E prosseguindo Jó em seu discurso, disse:

[[v18-27-2]]

^<<v18-27-2,2>>^ Vive Deus, que desviou a minha causa, e o Todo-Poderoso, que amargurou a minha alma.

[[v18-27-3]]

^<<v18-27-3,3>>^ Que, enquanto em mim houver alento, e o sopro de Deus nas minhas narinas,

[[v18-27-4]]

^<<v18-27-4,4>>^ Não falarão os meus lábios iniqüidade, nem a minha língua pronunciará engano.

[[v18-27-5]]

^<<v18-27-5,5>>^ Longe de mim que eu vos justifique; até que eu expire, nunca apartarei de mim a minha integridade.

[[v18-27-6]]

^<<v18-27-6,6>>^ À minha justiça me apegarei e não a largarei; não me reprovará o meu coração em toda a minha vida.

[[v18-27-7]]

^<<v18-27-7,7>>^ Seja como o ímpio o meu inimigo, e como o perverso o que se levantar contra mim.

[[v18-27-8]]

^<<v18-27-8,8>>^ Porque qual será a esperança do hipócrita, havendo sido avaro, quando Deus lhe arrancar a sua alma?

[[v18-27-9]]

^<<v18-27-9,9>>^ Porventura Deus ouvirá o seu clamor, sobrevindo-lhe a tribulação?

[[v18-27-10]]

^<<v18-27-10,10>>^ Deleitar-se-á no TodoPoderoso, ou invocará a Deus em todo o tempo?

[[v18-27-11]]

^<<v18-27-11,11>>^ Ensinar-vos-ei acerca da mão de Deus, e não vos encobrirei o que está com o Todo-Poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que todos vós já o vistes; por que, pois, vos desvaneceis na vossa vaidade?

[[v18-27-13]]

^<<v18-27-13,13>>^ Esta, pois, é a porção do homem ímpio da parte de Deus, e a herança, que os tiranos receberão do Todo-Poderoso.

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os seus filhos se multiplicarem, será para a espada, e a sua prole não se fartará de pão.

[[v18-27-15]]

^<<v18-27-15,15>>^ Os que ficarem dele na morte serão enterrados, e as suas viúvas não chorarão.

[[v18-27-16]]

^<<v18-27-16,16>>^ Se amontoar prata como pó, e aparelhar roupas como lodo,

[[v18-27-17]]

^<<v18-27-17,17>>^ Ele as aparelhará, porém o justo as vestirá, e o inocente repartirá a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ E edificará a sua casa como a traça, e como o guarda que faz a cabana.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico se deita, e não será recolhido; abre os seus olhos, e nada terá.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores se apoderam dele como águas; de noite o arrebata a tempestade.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento oriental leva-o, e ele se vai, e varre-o com ímpeto do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ E Deus lançará isto sobre ele, e não lhe poupará; irá fugindo da sua mão.

[[v18-27-23]]

^<<v18-27-23,23>>^ Cada um baterá palmas contra ele e assobiará tirando-o do seu lugar.

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]