include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-4-1]]

^<<v18-4-1,1>>^ Então respondeu Elifaz o temanita, e disse:

[[v18-4-2]]

^<<v18-4-2,2>>^ Se intentarmos falar-te, enfadar-te-ás? Mas quem poderia conter as palavras?

[[v18-4-3]]

^<<v18-4-3,3>>^ Eis que ensinaste a muitos, e tens fortalecido as mãos fracas.

[[v18-4-4]]

^<<v18-4-4,4>>^ As tuas palavras firmaram os que tropeçavam e os joelhos desfalecentes tens fortalecido.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora, que se trata de ti, te enfadas; e tocando-te a ti, te perturbas.

[[v18-4-6]]

^<<v18-4-6,6>>^ Porventura não é o teu temor de Deus a tua confiança, e a tua esperança a integridade dos teus caminhos?

[[v18-4-7]]

^<<v18-4-7,7>>^ Lembra-te agora qual é o inocente que jamais pereceu? E onde foram os sinceros destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Segundo eu tenho visto, os que lavram iniqüidade, e semeiam mal, segam o mesmo.

[[v18-4-9]]

^<<v18-4-9,9>>^ Com o hálito de Deus perecem; e com o sopro da sua ira se consomem.

[[v18-4-10]]

^<<v18-4-10,10>>^ O rugido do leão, e a voz do leão feroz, e os dentes dos leõezinhos se quebram.

[[v18-4-11]]

^<<v18-4-11,11>>^ Perece o leão velho, porque não tem presa; e os filhos da leoa andam dispersos.

[[v18-4-12]]

^<<v18-4-12,12>>^ Uma coisa me foi trazida em segredo; e os meus ouvidos perceberam um sussurro dela.

[[v18-4-13]]

^<<v18-4-13,13>>^ Entre pensamentos vindos de visões da noite, quando cai sobre os homens o sono profundo,

[[v18-4-14]]

^<<v18-4-14,14>>^ Sobrevieram-me o espanto e o tremor, e todos os meus ossos estremeceram.

[[v18-4-15]]

^<<v18-4-15,15>>^ Então um espírito passou por diante de mim; fez-me arrepiar os cabelos da minha carne.

[[v18-4-16]]

^<<v18-4-16,16>>^ Parou ele, porém não conheci a sua feição; um vulto estava diante dos meus olhos; houve silêncio, e ouvi uma voz que dizia:

[[v18-4-17]]

^<<v18-4-17,17>>^ Seria porventura o homem mais justo do que Deus? Seria porventura o homem mais puro do que o seu Criador?

[[v18-4-18]]

^<<v18-4-18,18>>^ Eis que ele não confia nos seus servos e aos seus anjos atribui loucura;

[[v18-4-19]]

^<<v18-4-19,19>>^ Quanto menos àqueles que habitam em casas de lodo, cujo fundamento está no pó, e são esmagados como a traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ Desde a manhã até à tarde são despedaçados; e eternamente perecem sem que disso se faça caso.

[[v18-4-21]]

^<<v18-4-21,21>>^ Porventura não passa com eles a sua excelência? Morrem, mas sem sabedoria.

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]