include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-36-1]]

^<<v18-36-1,1>>^ Prosseguiu ainda Eliú, e disse:

[[v18-36-2]]

^<<v18-36-2,2>>^ Espera-me um pouco, e mostrar-te-ei que ainda há razões a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ De longe trarei o meu conhecimento; e ao meu Criador atribuirei a justiça.

[[v18-36-4]]

^<<v18-36-4,4>>^ Porque na verdade, as minhas palavras não serão falsas; contigo está um que tem perfeito conhecimento.

[[v18-36-5]]

^<<v18-36-5,5>>^ Eis que Deus é mui grande, contudo a ninguém despreza; grande é em força e sabedoria.

[[v18-36-6]]

^<<v18-36-6,6>>^ Ele não preserva a vida do ímpio, e faz justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Do justo não tira os seus olhos; antes estão com os reis no trono; ali os assenta para sempre, e assim são exaltados.

[[v18-36-8]]

^<<v18-36-8,8>>^ E se estão presos em grilhões, amarrados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ Então lhes faz saber a obra deles, e as suas transgressões, porquanto prevaleceram nelas.

[[v18-36-10]]

^<<v18-36-10,10>>^ Abre-lhes também os seus ouvidos, para sua disciplina, e ordena-lhes que se convertam da maldade.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se o ouvirem, e o servirem, acabarão seus dias em bem, e os seus anos em delícias.

[[v18-36-12]]

^<<v18-36-12,12>>^ Porém se não o ouvirem, à espada serão passados, e expirarão sem conhecimento.

[[v18-36-13]]

^<<v18-36-13,13>>^ E os hipócritas de coração amontoam para si a ira; e amarrando-os ele, não clamam por socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ A sua alma morre na mocidade, e a sua vida perece entre os impuros.

[[v18-36-15]]

^<<v18-36-15,15>>^ Ao aflito livra da sua aflição, e na opressão se revela aos seus ouvidos.

[[v18-36-16]]

^<<v18-36-16,16>>^ Assim também te desviará da boca da angústia para um lugar espaçoso, em que não há aperto, e as iguarias da tua mesa serão cheias de gordura.

[[v18-36-17]]

^<<v18-36-17,17>>^ Mas tu estás cheio do juízo do ímpio; o juízo e a justiça te sustentam.

[[v18-36-18]]

^<<v18-36-18,18>>^ Porquanto há furor, guarda-te de que não sejas atingido pelo castigo violento, pois nem com resgate algum te livrarias dele.

[[v18-36-19]]

^<<v18-36-19,19>>^ Estimaria ele tanto tuas riquezas? Não, nem ouro, nem todas as forças do poder.

[[v18-36-20]]

^<<v18-36-20,20>>^ Não suspires pela noite, em que os povos sejam tomados do seu lugar.

[[v18-36-21]]

^<<v18-36-21,21>>^ Guarda-te, e não declines para a iniqüidade; porquanto isso escolheste antes que a aflição.

[[v18-36-22]]

^<<v18-36-22,22>>^ Eis que Deus é excelso em seu poder; quem ensina como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem lhe prescreveu o seu caminho? Ou, quem lhe dirá: Tu cometeste maldade?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembra-te de engrandecer a sua obra, que os homens contemplam.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos os homens a vêem, e o homem a enxerga de longe.

[[v18-36-26]]

^<<v18-36-26,26>>^ Eis que Deus é grande, e nós não o compreendemos, e o número dos seus anos não se pode esquadrinhar.

[[v18-36-27]]

^<<v18-36-27,27>>^ Porque faz miúdas as gotas das águas que, do seu vapor, derramam a chuva,

[[v18-36-28]]

^<<v18-36-28,28>>^ A qual as nuvens destilam e gotejam sobre o homem abundantemente.

[[v18-36-29]]

^<<v18-36-29,29>>^ Porventura pode alguém entender as extensões das nuvens, e os estalos da sua tenda?

[[v18-36-30]]

^<<v18-36-30,30>>^ Eis que estende sobre elas a sua luz, e encobre as profundezas do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Porque por estas coisas julga os povos e lhes dá mantimento em abundância.

[[v18-36-32]]

^<<v18-36-32,32>>^ Com as nuvens encobre a luz, e ordena não brilhar, interpondo a nuvem.

[[v18-36-33]]

^<<v18-36-33,33>>^ O que nos dá a entender o seu pensamento, como também ao gado, acerca do temporal que sobe.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]