include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-22-1]]

^<<v18-22-1,1>>^ Então respondeu Elifaz, o temanita, dizendo:

[[v18-22-2]]

^<<v18-22-2,2>>^ Porventura será o homem de algum proveito a Deus? Antes a si mesmo o prudente será proveitoso.

[[v18-22-3]]

^<<v18-22-3,3>>^ Ou tem o Todo-Poderoso prazer em que tu sejas justo, ou algum lucro em que tu faças perfeitos os teus caminhos?

[[v18-22-4]]

^<<v18-22-4,4>>^ Ou te repreende, pelo temor que tem de ti, ou entra contigo em juízo?

[[v18-22-5]]

^<<v18-22-5,5>>^ Porventura não é grande a tua malícia, e sem termo as tuas iniqüidades?

[[v18-22-6]]

^<<v18-22-6,6>>^ Porque sem causa penhoraste a teus irmãos, e aos nus despojaste as vestes.

[[v18-22-7]]

^<<v18-22-7,7>>^ Não deste ao cansado água a beber, e ao faminto retiveste o pão.

[[v18-22-8]]

^<<v18-22-8,8>>^ Mas para o poderoso era a terra, e o homem tido em respeito habitava nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ As viúvas despediste vazias, e os braços dos órfãos foram quebrados.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso é que estás cercado de laços, e te perturba um pavor repentino,

[[v18-22-11]]

^<<v18-22-11,11>>^ Ou trevas em que nada vês, e a abundância de águas que te cobre.

[[v18-22-12]]

^<<v18-22-12,12>>^ Porventura Deus não está na altura dos céus? Olha para a altura das estrelas; quão elevadas estão.

[[v18-22-13]]

^<<v18-22-13,13>>^ E dizes: que sabe Deus? Porventura julgará ele através da escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ As nuvens são esconderijo para ele, para que não veja; e passeia pelo circuito dos céus.

[[v18-22-15]]

^<<v18-22-15,15>>^ Porventura queres guardar a vereda antiga, que pisaram os homens iníquos?

[[v18-22-16]]

^<<v18-22-16,16>>^ Eles foram arrebatados antes do seu tempo; sobre o seu fundamento um dilúvio se derramou.

[[v18-22-17]]

^<<v18-22-17,17>>^ Diziam a Deus: Retira-te de nós. E: Que foi que o Todo-Poderoso nos fez?

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo ele encheu de bens as suas casas; mas o conselho dos ímpios esteja longe de mim.

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos o vêem, e se alegram, e o inocente escarnece deles.

[[v18-22-20]]

^<<v18-22-20,20>>^ Porquanto o nosso adversário não foi destruído, mas o fogo consumiu o que restou deles.

[[v18-22-21]]

^<<v18-22-21,21>>^ Apega-te, pois, a ele, e tem paz, e assim te sobrevirá o bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceita, peço-te, a lei da sua boca, e põe as suas palavras no teu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se te voltares ao Todo-Poderoso, serás edificado; se afastares a iniqüidade da tua tenda,

[[v18-22-24]]

^<<v18-22-24,24>>^ E deitares o teu tesouro no pó, e o ouro de Ofir nas pedras dos ribeiros,

[[v18-22-25]]

^<<v18-22-25,25>>^ Então o Todo-Poderoso será o teu tesouro, e a tua prata acumulada.

[[v18-22-26]]

^<<v18-22-26,26>>^ Porque então te deleitarás no Todo-Poderoso, e levantarás o teu rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Orarás a ele, e ele te ouvirá, e pagarás os teus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Determinarás tu algum negócio, e ser-te-á firme, e a luz brilhará em teus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Quando te abaterem, então tu dirás: Haja exaltação! E Deus salvará ao humilde.

[[v18-22-30]]

^<<v18-22-30,30>>^ E livrará até ao que não é inocente; porque será libertado pela pureza de tuas mãos.

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]