include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-41-1]]

^<<v18-41-1,1>>^ Poderás tirar com anzol o leviatã, ou ligarás a sua língua com uma corda?

[[v18-41-2]]

^<<v18-41-2,2>>^ Podes pôr um anzol no seu nariz, ou com um gancho furar a sua queixada?

[[v18-41-3]]

^<<v18-41-3,3>>^ Porventura multiplicará as súplicas para contigo, ou brandamente falará?

[[v18-41-4]]

^<<v18-41-4,4>>^ Fará ele aliança contigo, ou o tomarás tu por servo para sempre?

[[v18-41-5]]

^<<v18-41-5,5>>^ Brincarás com ele, como se fora um passarinho, ou o prenderás para tuas meninas?

[[v18-41-6]]

^<<v18-41-6,6>>^ Os teus companheiros farão dele um banquete, ou o repartirão entre os negociantes?

[[v18-41-7]]

^<<v18-41-7,7>>^ Encherás a sua pele de ganchos, ou a sua cabeça com arpões de pescadores?

[[v18-41-8]]

^<<v18-41-8,8>>^ Põe a tua mão sobre ele, lembra-te da peleja, e nunca mais tal intentarás.

[[v18-41-9]]

^<<v18-41-9,9>>^ Eis que é vã a esperança de apanhá-lo; pois não será o homem derrubado só ao vê-lo?

[[v18-41-10]]

^<<v18-41-10,10>>^ Ninguém há tão atrevido, que a despertá-lo se atreva; quem, pois, é aquele que ousa erguer-se diante de mim?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem primeiro me deu, para que eu haja de retribuir-lhe? Pois o que está debaixo de todos os céus é meu.

[[v18-41-12]]

^<<v18-41-12,12>>^ Não me calarei a respeito dos seus membros, nem da sua grande força, nem a graça da sua compostura.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem descobrirá a face da sua roupa? Quem entrará na sua couraça dobrada?

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem abrirá as portas do seu rosto? Pois ao redor dos seus dentes está o terror.

[[v18-41-15]]

^<<v18-41-15,15>>^ As suas fortes escamas são o seu orgulho, cada uma fechada como com selo apertado.

[[v18-41-16]]

^<<v18-41-16,16>>^ Uma à outra se chega tão perto, que nem o ar passa por entre elas.

[[v18-41-17]]

^<<v18-41-17,17>>^ Umas às outras se ligam; tanto aderem entre si, que não se podem separar.

[[v18-41-18]]

^<<v18-41-18,18>>^ Cada um dos seus espirros faz resplandecer a luz, e os seus olhos são como as pálpebras da alva.

[[v18-41-19]]

^<<v18-41-19,19>>^ Da sua boca saem tochas; faíscas de fogo saltam dela.

[[v18-41-20]]

^<<v18-41-20,20>>^ Das suas narinas procede fumaça, como de uma panela fervente, ou de uma grande caldeira.

[[v18-41-21]]

^<<v18-41-21,21>>^ O seu hálito faz incender os carvões; e da sua boca sai chama.

[[v18-41-22]]

^<<v18-41-22,22>>^ No seu pescoço reside a força; diante dele até a tristeza salta de prazer.

[[v18-41-23]]

^<<v18-41-23,23>>^ Os músculos da sua carne estão pegados entre si; cada um está firme nele, e nenhum se move.

[[v18-41-24]]

^<<v18-41-24,24>>^ O seu coração é firme como uma pedra e firme como a mó de baixo.

[[v18-41-25]]

^<<v18-41-25,25>>^ Levantando-se ele, tremem os valentes; em razão dos seus abalos se purificam.

[[v18-41-26]]

^<<v18-41-26,26>>^ Se alguém lhe tocar com a espada, essa não poderá penetrar, nem lança, dardo ou flecha.

[[v18-41-27]]

^<<v18-41-27,27>>^ Ele considera o ferro como palha, e o cobre como pau podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ A seta o não fará fugir; as pedras das fundas se lhe tornam em restolho.

[[v18-41-29]]

^<<v18-41-29,29>>^ As pedras atiradas são para ele como arestas, e ri-se do brandir da lança;

[[v18-41-30]]

^<<v18-41-30,30>>^ Debaixo de si tem conchas pontiagudas; estende-se sobre coisas pontiagudas como na lama.

[[v18-41-31]]

^<<v18-41-31,31>>^ As profundezas faz ferver, como uma panela; torna o mar como uma vasilha de ungüento.

[[v18-41-32]]

^<<v18-41-32,32>>^ Após si deixa uma vereda luminosa; parece o abismo tornado em brancura de cãs.

[[v18-41-33]]

^<<v18-41-33,33>>^ Na terra não há coisa que se lhe possa comparar, pois foi feito para estar sem pavor.

[[v18-41-34]]

^<<v18-41-34,34>>^ Ele vê tudo que é alto; é rei sobre todos os filhos da soberba.

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]