include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-28-1]]

^<<v18-28-1,1>>^ Na verdade, há veios de onde se extrai a prata, e lugar onde se refina o ouro.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro tira-se da terra, e da pedra se funde o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ Ele põe fim às trevas, e toda a extremidade ele esquadrinha, a pedra da escuridão e a da sombra da morte.

[[v18-28-4]]

^<<v18-28-4,4>>^ Abre um poço de mina longe dos homens, em lugares esquecidos do pé; ficando pendentes longe dos homens, oscilam de um lado para outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ Da terra procede o pão, mas por baixo é revolvida como por fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ As suas pedras são o lugar da safira, e tem pó de ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ Essa vereda a ave de rapina a ignora, e não a viram os olhos da gralha.

[[v18-28-8]]

^<<v18-28-8,8>>^ Nunca a pisaram filhos de animais altivos, nem o feroz leão passou por ela.

[[v18-28-9]]

^<<v18-28-9,9>>^ Ele estende a sua mão contra o rochedo, e revolve os montes desde as suas raízes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Dos rochedos faz sair rios, e o seu olho vê tudo o que há de precioso.

[[v18-28-11]]

^<<v18-28-11,11>>^ Os rios tapa, e nem uma gota sai deles, e tira à luz o que estava escondido.

[[v18-28-12]]

^<<v18-28-12,12>>^ Porém onde se achará a sabedoria, e onde está o lugar da inteligência?

[[v18-28-13]]

^<<v18-28-13,13>>^ O homem não conhece o seu valor, e nem ela se acha na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: Não está em mim; e o mar diz: Ela não está comigo.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não se dará por ela ouro fino, nem se pesará prata em troca dela.

[[v18-28-16]]

^<<v18-28-16,16>>^ Nem se pode comprar por ouro fino de Ofir, nem pelo precioso ônix, nem pela safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ Com ela não se pode comparar o ouro nem o cristal; nem se trocará por jóia de ouro fino.

[[v18-28-18]]

^<<v18-28-18,18>>^ Não se fará menção de coral nem de pérolas; porque o valor da sabedoria é melhor que o dos rubis.

[[v18-28-19]]

^<<v18-28-19,19>>^ Não se lhe igualará o topázio da Etiópia, nem se pode avaliar por ouro puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ Donde, pois, vem a sabedoria, e onde está o lugar da inteligência?

[[v18-28-21]]

^<<v18-28-21,21>>^ Pois está encoberta aos olhos de todo o vivente, e oculta às aves do céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ A perdição e a morte dizem: Ouvimos com os nossos ouvidos a sua fama.

[[v18-28-23]]

^<<v18-28-23,23>>^ Deus entende o seu caminho, e ele sabe o seu lugar.

[[v18-28-24]]

^<<v18-28-24,24>>^ Porque ele vê as extremidades da terra; e vê tudo o que há debaixo dos céus.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando deu peso ao vento, e tomou a medida das águas;

[[v18-28-26]]

^<<v18-28-26,26>>^ Quando prescreveu leis para a chuva e caminho para o relâmpago dos trovões;

[[v18-28-27]]

^<<v18-28-27,27>>^ Então a viu e relatou; estabeleceu-a, e também a esquadrinhou.

[[v18-28-28]]

^<<v18-28-28,28>>^ E disse ao homem: Eis que o temor do Senhor é a sabedoria, e apartar-se do mal é a inteligência.

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]