include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v18-18-1]]

^<<v18-18-1,1>>^ Então respondeu Bildade, o suíta, e disse:

[[v18-18-2]]

^<<v18-18-2,2>>^ Até quando poreis fim às palavras? Considerai bem, e então falaremos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que somos tratados como animais, e como imundos aos vossos olhos?

[[v18-18-4]]

^<<v18-18-4,4>>^ Oh tu, que despedaças a tua alma na tua ira, será a terra deixada por tua causa? Remover-se-ão as rochas do seu lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ Na verdade, a luz dos ímpios se apagará, e a chama do seu fogo não resplandecerá.

[[v18-18-6]]

^<<v18-18-6,6>>^ A luz se escurecerá nas suas tendas, e a sua lâmpada sobre ele se apagará.

[[v18-18-7]]

^<<v18-18-7,7>>^ Os seus passos firmes se estreitarão, e o seu próprio conselho o derrubará.

[[v18-18-8]]

^<<v18-18-8,8>>^ Porque por seus próprios pés é lançado na rede, e andará nos fios enredados.

[[v18-18-9]]

^<<v18-18-9,9>>^ O laço o apanhará pelo calcanhar, e a armadilha o prenderá.

[[v18-18-10]]

^<<v18-18-10,10>>^ Está escondida debaixo da terra uma corda, e uma armadilha na vereda.

[[v18-18-11]]

^<<v18-18-11,11>>^ Os assombros o espantarão de todos os lados, e o perseguirão a cada passo.

[[v18-18-12]]

^<<v18-18-12,12>>^ Será faminto o seu vigor, e a destruição está pronta ao seu lado.

[[v18-18-13]]

^<<v18-18-13,13>>^ Serão devorados os membros do seu corpo; sim, o primogênito da morte devorará os seus membros.

[[v18-18-14]]

^<<v18-18-14,14>>^ A sua confiança será arrancada da sua tenda, onde está confiado, e isto o fará caminhar para o rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ Morará na sua mesma tenda, o que não lhe pertence; espalhar-se-á enxofre sobre a sua habitação.

[[v18-18-16]]

^<<v18-18-16,16>>^ Por baixo se secarão as suas raízes e por cima serão cortados os seus ramos.

[[v18-18-17]]

^<<v18-18-17,17>>^ A sua memória perecerá da terra, e pelas praças não terá nome.

[[v18-18-18]]

^<<v18-18-18,18>>^ Da luz o lançarão nas trevas, e afugentá-lo-ão do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá filho nem neto entre o seu povo, e nem quem lhe suceda nas suas moradas.

[[v18-18-20]]

^<<v18-18-20,20>>^ Do seu dia se espantarão os do ocidente, assim como se espantam os do oriente.

[[v18-18-21]]

^<<v18-18-21,21>>^ Tais são, na verdade, as moradas do perverso, e este é o lugar do que não conhece a Deus.

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]