include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-34-1]]

^<<v14-34-1,1>>^ Tinha Josias oito anos quando começou a reinar, e trinta e um anos reinou em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ E fez o que era reto aos olhos do Senhor; e andou nos caminhos de Davi, seu pai, sem se desviar deles nem para a direita nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ Porque no oitavo ano do seu reinado, sendo ainda moço, começou a buscar o Deus de Davi, seu pai; e no duodécimo ano começou a purificar a Judá e a Jerusalém, dos altos, e dos bosques, e das imagens de escultura e de fundição.

[[v14-34-4]]

^<<v14-34-4,4>>^ E derrubaram perante ele os altares de Baalins; e despedaçou as imagens, que estavam acima deles; e os bosques, e as imagens de escultura e de fundição quebrou e reduziu a pó, e o espargiu sobre as sepulturas dos que lhes tinham sacrificado.

[[v14-34-5]]

^<<v14-34-5,5>>^ E os ossos dos sacerdotes queimou sobre os seus altares; e purificou a Judá e a Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ O mesmo fez nas cidades de Manassés, e de Efraim, e de Simeão, e ainda até Naftali, em seus lugares assolados ao redor.

[[v14-34-7]]

^<<v14-34-7,7>>^ E, tendo derrubado os altares, e os bosques, e as imagens de escultura, até reduzi-los a pó, e tendo despedaçado todas as imagens do sol em toda a terra de Israel, então voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ E no ano décimo oitavo do seu reinado, havendo já purificado a terra e a casa, enviou a Safã, filho de Azalias, e a Maaséias, governador da cidade, e a Joá, filho de Joacaz, cronista, para repararem a casa do Senhor seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ E foram a Hilquias, sumo sacerdote, e deram o dinheiro que se tinha trazido à casa de Deus, e que os levitas, que guardavam a entrada tinham recebido da mão de Manassés, e de Efraim, e de todo o restante de Israel, como também de todo o Judá e Benjamim, e dos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ E eles o entregaram aos que tinham o encargo da obra, e superintendiam a casa do Senhor; e estes o deram aos que faziam a obra, e trabalhavam na casa do Senhor, para consertarem e repararem a casa.

[[v14-34-11]]

^<<v14-34-11,11>>^ E deram-no aos carpinteiros e aos edificadores, para comprarem pedras lavradas, e madeiras para as junturas e para servirem de vigas para as casas que os reis de Judá tinham destruído.

[[v14-34-12]]

^<<v14-34-12,12>>^ E estes homens trabalhavam fielmente na obra; e os superintendentes sobre eles eram: Jaate e Obadias, levitas, dos filhos de Merari, como também Zacarias e Mesulão, dos filhos dos coatitas, para adiantarem a obra; e todos os levitas que eram entendidos em instrumentos de música.

[[v14-34-13]]

^<<v14-34-13,13>>^ Estavam também sobre os carregadores e dirigiam todos os que trabalhavam em alguma obra; e dentre os levitas havia escrivães, oficiais e porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ E, tirando eles o dinheiro que se tinha trazido à casa do Senhor, Hilquias, o sacerdote, achou o livro da lei do Senhor, dada pela mão de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ E Hilquias disse a Safã, o escrivão: Achei o livro da lei na casa do Senhor. E Hilquias deu o livro a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ E Safã levou o livro ao rei, e deu-lhe conta, dizendo: Teus servos fazem tudo quanto se lhes encomendou.

[[v14-34-17]]

^<<v14-34-17,17>>^ E ajuntaram o dinheiro que se achou na casa do Senhor, e o deram na mão dos superintendentes e na mão dos que faziam a obra.

[[v14-34-18]]

^<<v14-34-18,18>>^ Além disto, Safã, o escrivão, fez saber ao rei, dizendo: O sacerdote Hilquias entregou-me um livro. E Safã leu nele perante o rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Sucedeu que, ouvindo o rei as palavras da lei, rasgou as suas vestes.

[[v14-34-20]]

^<<v14-34-20,20>>^ E o rei ordenou a Hilquias, e a Aicão, filho de Safã, e a Abdom, filho de Mica, e a Safã, o escrivão, e a Asaías, servo do rei, dizendo:

[[v14-34-21]]

^<<v14-34-21,21>>^ Ide, consultai ao Senhor por mim, e pelos que restam em Israel e em Judá, sobre as palavras deste livro que se achou; porque grande é o furor do Senhor, que se derramou sobre nós; porquanto nossos pais não guardaram a palavra do Senhor, para fazerem conforme a tudo quanto está escrito neste livro.

[[v14-34-22]]

^<<v14-34-22,22>>^ Então Hilquias, e os enviados do rei, foram ter com a profetisa Hulda, mulher de Salum, filho de Tocate, filho de Harás, guarda das vestimentas (e habitava ela em Jerusalém na segunda parte); e falaram-lhe a esse respeito.

[[v14-34-23]]

^<<v14-34-23,23>>^ E ela lhes disse: Assim diz o Senhor Deus de Israel: Dizei ao homem que vos enviou a mim:

[[v14-34-24]]

^<<v14-34-24,24>>^ Assim diz o Senhor: Eis que trarei mal sobre este lugar, e sobre os seus habitantes, a saber, todas as maldições que estão escritas no livro que se leu perante o rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Porque me deixaram, e queimaram incenso perante outros deuses, para me provocarem à ira com todas as obras das suas mãos; portanto o meu furor se derramou sobre este lugar, e não se apagará.

[[v14-34-26]]

^<<v14-34-26,26>>^ Porém ao rei de Judá, que vos enviou a consultar ao Senhor, assim lhe direis: Assim diz o Senhor Deus de Israel, quanto às palavras que ouviste:

[[v14-34-27]]

^<<v14-34-27,27>>^ Porquanto o teu coração se enterneceu, e te humilhaste perante Deus, ouvindo as suas palavras contra este lugar, e contra os seus habitantes, e te humilhaste perante mim, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o Senhor.

[[v14-34-28]]

^<<v14-34-28,28>>^ Eis que te reunirei a teus pais, e tu serás recolhido ao teu sepulcro em paz, e os teus olhos não verão todo o mal que hei de trazer sobre este lugar e sobre os seus habitantes. E tornaram com esta resposta ao rei.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então o rei mandou reunir todos os anciãos de Judá e Jerusalém.

[[v14-34-30]]

^<<v14-34-30,30>>^ E o rei subiu à casa do Senhor, com todos os homens de Judá, e os habitantes de Jerusalém, e os sacerdotes, e os levitas, e todo o povo, desde o maior até ao menor; e ele leu aos ouvidos deles todas as palavras do livro da aliança que fora achado na casa do Senhor.

[[v14-34-31]]

^<<v14-34-31,31>>^ E pôs-se o rei em pé em seu lugar, e fez aliança perante o Senhor, para seguirem ao Senhor, e para guardar os seus mandamentos, e os seus testemunhos, e os seus estatutos, com todo o seu coração, e com toda a sua alma, cumprindo as palavras da aliança, que estão escritas naquele livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ E fez com que todos quantos se achavam em Jerusalém e em Benjamim o firmassem; e os habitantes de Jerusalém fizeram conforme a aliança de Deus, o Deus de seus pais.

[[v14-34-33]]

^<<v14-34-33,33>>^ E Josias tirou todas as abominações de todas as terras que eram dos filhos de Israel; e a todos quantos se achavam em Israel obrigou a que servissem ao Senhor seu Deus. Enquanto ele viveu não se desviaram de seguir o Senhor, o Deus de seus pais.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]