include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-25-1]]

^<<v14-25-1,1>>^ Era Amazias da idade de vinte e cinco anos, quando começou a reinar, e reinou vinte e nove anos em Jerusalém; e era o nome de sua mãe Joadã, de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ E fez o que era reto aos olhos do Senhor, porém não com inteireza de coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ Sucedeu que, sendo-lhe o reino já confirmado, matou a seus servos que mataram o rei seu pai;

[[v14-25-4]]

^<<v14-25-4,4>>^ Porém não matou os filhos deles; mas fez segundo está escrito na lei, no livro de Moisés, como o Senhor ordenou, dizendo: Não morrerão os pais pelos filhos, nem os filhos pelos pais; mas cada um morrerá pelo seu pecado.

[[v14-25-5]]

^<<v14-25-5,5>>^ E Amazias reuniu a Judá e os pôs segundo as casas dos pais, sob capitàes de milhares, e sob capitàes de cem, por todo o Judá e Benjamim; e os contou, de vinte anos para cima, e achou deles trezentos mil escolhidos que podiam sair à guerra, e manejar lança e escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também de Israel tomou a soldo cem mil homens valentes, por cem talentos de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Porém um homem de Deus veio a ele, dizendo: Ó rei, não deixes ir contigo o exército de Israel; porque o Senhor não é com Israel, a saber com os filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Se quiseres ir, faze-o assim, esforça-te para a peleja. Deus, porém, te fará cair diante do inimigo; porque força há em Deus para ajudar e para fazer cair.

[[v14-25-9]]

^<<v14-25-9,9>>^ E disse Amazias ao homem de Deus: Que se fará, pois, dos cem talentos de prata que dei às tropas de Israel? E disse o homem de Deus: Mais tem o Senhor que te dar do que isso.

[[v14-25-10]]

^<<v14-25-10,10>>^ Então separou Amazias as tropas que lhe tinham vindo de Efraim, para que se fossem ao seu lugar; pelo que se acendeu a sua ira contra Judá, e voltaram para as suas casas ardendo em ira.

[[v14-25-11]]

^<<v14-25-11,11>>^ Esforçou-se, pois, Amazias, e conduziu o seu povo, e foi ao Vale do Sal; onde feriu a dez mil dos filhos de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ Também os filhos de Judá prenderam vivos dez mil, e os levaram ao cume da rocha; e do mais alto da rocha os lançaram abaixo, e todos se despedaçaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Porém os homens das tropas que Amazias despedira, para que não fossem com ele à peleja, deram sobre as cidades de Judá desde Samaria, até Bete-Horom; e feriram deles três mil, e saquearam grande despojo.

[[v14-25-14]]

^<<v14-25-14,14>>^ E sucedeu que, depois que Amazias veio da matança dos edomitas e trouxe consigo os deuses dos filhos de Seir, tomou-os por seus deuses, e prostrou-se diante deles, e queimou-lhes incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Então a ira do Senhor se acendeu contra Amazias, e mandou-lhe um profeta que lhe disse: Por que buscaste deuses deste povo, os quais não livraram o seu próprio povo da tua mão?

[[v14-25-16]]

^<<v14-25-16,16>>^ E sucedeu que, falando ele ao rei, este lhe respondeu: Puseram-te por conselheiro do rei? Cala-te! Por que haveria de ser ferido? Então parou o profeta, e disse: Bem vejo eu que já Deus deliberou destruir-te; porquanto fizeste isto, e não deste ouvidos ao meu conselho.

[[v14-25-17]]

^<<v14-25-17,17>>^ E, tendo tomado conselho, Amazias, rei de Judá, mandou dizer a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel: Vem, vejamo-nos face a face.

[[v14-25-18]]

^<<v14-25-18,18>>^ Porém Jeoás, rei de Israel, mandou dizer a Amazias, rei de Judá: O cardo que estava no Líbano mandou dizer ao cedro que estava no Líbano: Dá tua filha por mulher a meu filho; porém os animais do campo, que estavam no Líbano passaram e pisaram o cardo.

[[v14-25-19]]

^<<v14-25-19,19>>^ Tu dizes: Eis que tenho ferido os edomitas; e elevou-se o teu coração, para te gloriares; agora, pois, fica em tua casa; por que te entremeterias no mal, para caíres tu e Judá contigo?

[[v14-25-20]]

^<<v14-25-20,20>>^ Porém Amazias não lhe deu ouvidos, porque isto vinha de Deus, para entregá-los na mão dos seus inimigos; porquanto buscaram os deuses dos edomitas.

[[v14-25-21]]

^<<v14-25-21,21>>^ E Jeoás, rei de Israel, subiu; e ele e Amazias, rei de Judá, viram-se face a face em Bete-Semes, que está em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ E Judá foi ferido diante de Israel; e fugiu cada um para a sua tenda.

[[v14-25-23]]

^<<v14-25-23,23>>^ E Jeoás, rei de Israel, prendeu a Amazias, rei de Judá, filho de Joás, o filho de Jeoacaz, em Bete-Semes, e o trouxe a Jerusalém; e derrubou o muro de Jerusalém, desde a porta de Efraim até à porta da esquina, quatrocentos côvados.

[[v14-25-24]]

^<<v14-25-24,24>>^ Também tomou todo o ouro, a prata, e todos os utensílios que se acharam na casa de Deus com Obede-Edom, e os tesouros da casa do rei, e os reféns; e voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ E viveu Amazias, filho de Joás, rei de Judá, depois da morte de Jeoás, filho de Jeoacaz, rei de Israel, quinze anos.

[[v14-25-26]]

^<<v14-25-26,26>>^ Quanto ao mais dos atos de Amazias, tanto os primeiros como os últimos, eis que, porventura, não estão escritos no livro dos reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ E desde o tempo em que Amazias se desviou do Senhor, conspiraram contra ele em Jerusalém, porém ele fugiu para Laquis; mas perseguiram-no até Laquis, e o mataram ali.

[[v14-25-28]]

^<<v14-25-28,28>>^ E trouxeram-no sobre cavalos e sepultaram-no com seus pais na cidade de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]