include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-33-1]]

^<<v14-33-1,1>>^ Tinha Manassés doze anos de idade, quando começou a reinar, e cinqüenta e cinco anos reinou em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme às abominações dos gentios que o Senhor lançara fora de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Porque tornou a edificar os altos que Ezequias, seu pai, tinha derrubado; e levantou altares aos Baalins, e fez bosques, e prostrou-se diante de todo o exército dos céus, e o serviu.

[[v14-33-4]]

^<<v14-33-4,4>>^ E edificou altares na casa do Senhor, da qual o Senhor tinha falado: Em Jerusalém estará o meu nome eternamente.

[[v14-33-5]]

^<<v14-33-5,5>>^ Edificou altares a todo o exército dos céus, em ambos os átrios da casa do Senhor.

[[v14-33-6]]

^<<v14-33-6,6>>^ Fez ele também passar seus filhos pelo fogo no vale do filho de Hinom, e usou de adivinhações e de agouros, e de feitiçarias, e consultou adivinhos e encantadores, e fez muitíssimo mal aos olhos do Senhor, para o provocar à ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Também pôs uma imagem de escultura do ídolo que tinha feito, na casa de Deus, da qual Deus tinha falado a Davi e a Salomão seu filho: Nesta casa e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre.

[[v14-33-8]]

^<<v14-33-8,8>>^ E nunca mais removerei o pé de Israel da terra que destinei a vossos pais; contanto que tenham cuidado de fazer tudo o que eu lhes ordenei, conforme a toda a lei, e estatutos, e juízos, dados pela mão de Moisés.

[[v14-33-9]]

^<<v14-33-9,9>>^ E Manassés tanto fez errar a Judá e aos moradores de Jerusalém, que fizeram pior do que as nações que o Senhor tinha destruído de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ E falou o Senhor a Manassés e ao seu povo, porém não deram ouvidos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Assim o Senhor trouxe sobre eles os capitàes do exército do rei da Assíria, os quais prenderam a Manassés com ganchos e, amarrando-o com cadeias, o levaram para Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ E ele, angustiado, orou deveras ao Senhor seu Deus, e humilhou-se muito perante o Deus de seus pais;

[[v14-33-13]]

^<<v14-33-13,13>>^ E fez-lhe oração, e Deus se aplacou para com ele, e ouviu a sua súplica, e tornou a trazê-lo a Jerusalém, ao seu reino. Então conheceu Manassés que o Senhor era Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ E depois disto edificou o muro de fora da cidade de Davi, ao ocidente de Giom, no vale, e à entrada da porta do peixe, e ao redor de Ofel, e o levantou muito alto; também pôs capitàes de guerra em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ E tirou da casa do Senhor os deuses estranhos e o ídolo, como também todos os altares que tinha edificado no monte da casa do Senhor, e em Jerusalém, e os lançou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ E reparou o altar do Senhor e ofereceu sobre ele sacrifícios de ofertas pacíficas e de louvor; e ordenou a Judá que servisse ao Senhor Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Contudo o povo ainda sacrificava nos altos, mas somente ao Senhor seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ O restante dos atos de Manassés, e a sua oração ao seu Deus, e as palavras dos videntes que lhe falaram no nome do Senhor Deus de Israel, eis que estão nas crônicas dos reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ E a sua oração, e como Deus se aplacou para com ele, e todo o seu pecado, e a sua transgressão, e os lugares onde edificou altos, e pôs bosques e imagens de escultura, antes que se humilhasse, eis que estão escritos nos livros dos videntes.

[[v14-33-20]]

^<<v14-33-20,20>>^ E dormiu Manassés com seus pais, e o sepultaram em sua casa. Amom, seu filho, reinou em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Tinha Amom vinte e dois anos de idade quando começou a reinar, e dois anos reinou em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ E fez o que era mau aos olhos do Senhor, como havia feito Manassés, seu pai; porque Amom sacrificou a todas as imagens de escultura que Manassés, seu pai tinha feito, e as serviu.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou perante o Senhor, como Manassés, seu pai, se humilhara; antes multiplicou Amom os seus delitos.

[[v14-33-24]]

^<<v14-33-24,24>>^ E conspiraram contra ele os seus servos, e o mataram em sua casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Porém o povo da terra feriu a todos quantos conspiraram contra o rei Amom; e o povo da terra fez reinar em seu lugar a Josias, seu filho.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]