include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-11-1]]

^<<v14-11-1,1>>^ Vindo, pois, Roboão a Jerusalém, reuniu, da casa de Judá e Benjamim, cento e oitenta mil escolhidos, destros na guerra, para pelejarem contra Israel, e para restituírem o reino a Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Porém a palavra do Senhor veio a Semaías, homem de Deus, dizendo:

[[v14-11-3]]

^<<v14-11-3,3>>^ Fala a Roboão, filho de Salomão, rei de Judá, e a todo o Israel, em Judá e Benjamim, dizendo:

[[v14-11-4]]

^<<v14-11-4,4>>^ Assim diz o Senhor: Não subireis, nem pelejareis contra os vossos irmãos; volte cada um à sua casa; porque de mim proveio isto. E ouviram as palavras do Senhor, e desistiram de ir contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ E Roboão habitou em Jerusalém; e para defesa, edificou cidades em Judá.

[[v14-11-6]]

^<<v14-11-6,6>>^ Edificou, pois, a Belém, a Etã, e a Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ E a Bete-Zur, a Socó, a Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ E a Gate, a Maressa, a Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ E a Adoraim, a Laquis, e a Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ E a Zorá, a Aijalom, e a Hebrom, que estavam em Judá e em Benjamim; cidades fortes.

[[v14-11-11]]

^<<v14-11-11,11>>^ E fortificou estas fortalezas e pôs nelas capitàes, e armazéns de víveres, de azeite, e de vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ E pôs em cada cidade paveses e lanças; fortificou-as grandemente; e Judá e Benjamim pertenceram-lhe.

[[v14-11-13]]

^<<v14-11-13,13>>^ Também os sacerdotes e os levitas, que havia em todo o Israel, se reuniram a ele de todos os seus termos.

[[v14-11-14]]

^<<v14-11-14,14>>^ Porque os levitas deixaram os seus arrabaldes, e a sua possessão, e vieram a Judá e a Jerusalém, porque Jeroboão e seus filhos os lançaram fora para que não ministrassem ao Senhor.

[[v14-11-15]]

^<<v14-11-15,15>>^ E ele constituiu para si sacerdotes, para os altos, para os demônios, e para os bezerros, que fizera.

[[v14-11-16]]

^<<v14-11-16,16>>^ Depois desses também, de todas as tribos de Israel, os que deram o seu coração a buscarem ao Senhor Deus de Israel, vieram a Jerusalém, para oferecerem sacrifícios ao Senhor Deus de seus pais.

[[v14-11-17]]

^<<v14-11-17,17>>^ Assim fortaleceram o reino de Judá e corroboraram a Roboão, filho de Salomão, por três anos; porque três anos andaram no caminho de Davi e Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ E Roboão tomou para si, por mulher, a Maalate, filha de Jerimote, filho de Davi; e Abiail, filha de Eliabe, filho de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ A qual lhe deu filhos: Jeús, Samarias e Zaã.

[[v14-11-20]]

^<<v14-11-20,20>>^ E depois dela tomou a Maaca, filha de Absalão; esta lhe deu Abias, Atai, Ziza e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ E amava Roboão mais a Maaca, filha de Absalão, do que a todas as suas outras mulheres e concubinas; porque ele tinha tomado dezoito mulheres, e sessenta concubinas; e gerou vinte e oito filhos, e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ E Roboão designou Abias, filho de Maaca, para ser chefe e líder entre os seus irmãos, porque queria fazê-lo rei.

[[v14-11-23]]

^<<v14-11-23,23>>^ E usou de prudência, e de todos os seus filhos, alguns espalhou por todas as terras de Judá, e Benjamim, por todas as cidades fortes; e deu-lhes víveres em abundância; e lhes procurou muitas mulheres.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]