include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-5-1]]

^<<v14-5-1,1>>^ Assim se acabou toda a obra que Salomão fez para a casa do SENHOR; então trouxe Salomão as coisas que seu pai Davi havia consagrado, a prata, o ouro e todos os objetos, e pô-los entre os tesouros da casa de Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Então Salomão congregou em Jerusalém os anciãos de Israel, e todos os chefes das tribos, os chefes dos pais entre os filhos de Israel, para fazerem subir a arca da aliança do Senhor, da cidade de Davi, que é Sião.

[[v14-5-3]]

^<<v14-5-3,3>>^ E todos os homens de Israel se congregaram ao rei na ocasião da festa, que foi no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ E vieram todos os anciãos de Israel; e os levitas levantaram a arca.

[[v14-5-5]]

^<<v14-5-5,5>>^ E fizeram subir a arca, e a tenda da congregação, com todos os objetos sagrados, que estavam na tenda; os sacerdotes e os levitas os fizeram subir.

[[v14-5-6]]

^<<v14-5-6,6>>^ Então o rei Salomão e toda a congregação de Israel, que se tinha reunido com ele diante da arca, sacrificaram carneiros e bois, que não se podiam contar, nem numerar, por causa da sua abundância.

[[v14-5-7]]

^<<v14-5-7,7>>^ Assim trouxeram os sacerdotes a arca da aliança do Senhor ao seu lugar, ao oráculo da casa, ao lugar santíssimo, até debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Porque os querubins estendiam ambas as asas sobre o lugar da arca, e os querubins cobriam, por cima, a arca e os seus varais.

[[v14-5-9]]

^<<v14-5-9,9>>^ Então os varais sobressaíam para que as pontas dos varais da arca se vissem perante o oráculo, mas não se vissem de fora; e ali tem estado até ao dia de hoje.

[[v14-5-10]]

^<<v14-5-10,10>>^ Na arca não havia coisa alguma senão as duas tábuas, que Moisés tinha posto em Horebe, quando o Senhor fez aliança com os filhos de Israel, saíndo eles do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ E sucedeu que, saindo os sacerdotes do santuário (porque todos os sacerdotes, que ali se acharam, se santificaram, sem respeitarem as suas turmas,

[[v14-5-12]]

^<<v14-5-12,12>>^ E os levitas, que eram cantores, todos eles, de Asafe, de Hemã, de Jedutum, de seus filhos e de seus irmãos, vestidos de linho fino, com címbalos, com saltérios e com harpas, estavam em pé para o oriente do altar; e com eles até cento e vinte sacerdotes, que tocavam as trombetas).

[[v14-5-13]]

^<<v14-5-13,13>>^ E aconteceu que, quando eles uniformemente tocavam as trombetas, e cantavam, para fazerem ouvir uma só voz, bendizendo e louvando ao Senhor; e levantando eles a voz com trombetas, címbalos, e outros instrumentos musicais, e louvando ao Senhor, dizendo: Porque ele é bom, porque a sua benignidade dura para sempre, então a casa se encheu de uma nuvem, a saber, a casa do Senhor;

[[v14-5-14]]

^<<v14-5-14,14>>^ E os sacerdotes não podiam permanecer em pé, para ministrar, por causa da nuvem; porque a glória do Senhor encheu a casa de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]