include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-9-1]]

^<<v14-9-1,1>>^ E ouvindo a rainha de Sabá a fama de Salomão, veio a Jerusalém, para prová-lo com questões difíceis, com um grande séquito, e com camelos carregados de especiarias; ouro em abundância e pedras preciosas; e foi a Salomão, e falou com ele de tudo o que tinha no seu coração.

[[v14-9-2]]

^<<v14-9-2,2>>^ E Salomão lhe respondeu a todas as suas questões; e não houve nada que não lhe pudesse esclarecer.

[[v14-9-3]]

^<<v14-9-3,3>>^ Vendo, pois, a rainha de Sabá a sabedoria de Salomão, e a casa que edificara;

[[v14-9-4]]

^<<v14-9-4,4>>^ E as iguarias da sua mesa, o assentar dos seus servos, o estar dos seus criados, e as vestes deles; e os seus copeiros e as vestes deles; e a sua subida pela qual ele chegava à casa do Senhor, ela ficou como fora de si.

[[v14-9-5]]

^<<v14-9-5,5>>^ Então disse ao rei: Era verdade a palavra que ouvi na minha terra acerca dos teus feitos e da tua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ Porém não cria naquelas palavras, até que vim, e meus olhos o viram, e eis que não me disseram a metade da grandeza da tua sabedoria; sobrepujaste a fama que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Bem-aventurados os teus homens, e bem-aventurados estes teus servos, que estão sempre diante de ti, e ouvem a tua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor teu Deus, que se agradou de ti para te colocar no seu trono como rei para o Senhor teu Deus; porque teu Deus ama a Israel, para estabelecê-lo perpetuamente; por isso te constituiu rei sobre eles para fazeres juízo e justiça.

[[v14-9-9]]

^<<v14-9-9,9>>^ E deu ao rei cento e vinte talentos de ouro, e especiarias em grande abundância, e pedras preciosas; e nunca houve tais especiarias, quais a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ E também os servos de Hirão e os servos de Salomão, que de Ofir tinham trazido ouro, trouxeram madeira de algumins, e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ E, da madeira de algumins, o rei fez balaústres, para a casa do Senhor, e para a casa do rei, como também harpas e saltérios para os cantores, quais nunca dantes se viram na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ E o rei Salomão deu à rainha de Sabá tudo quanto ela desejou, e tudo quanto lhe pediu, mais do que ela mesma trouxera ao rei. Assim voltou e foi para a sua terra, ela e os seus servos.

[[v14-9-13]]

^<<v14-9-13,13>>^ E o peso do ouro, que vinha em um ano a Salomão, era de seiscentos e sessenta e seis talentos de ouro,

[[v14-9-14]]

^<<v14-9-14,14>>^ Afora o que os negociantes e mercadores traziam; também todos os reis da Arábia, e os governadores da mesma terra traziam a Salomão ouro e prata.

[[v14-9-15]]

^<<v14-9-15,15>>^ Também fez o rei Salomão duzentos paveses de ouro batido; para cada pavês destinou seiscentos siclos de ouro batido.

[[v14-9-16]]

^<<v14-9-16,16>>^ Como também trezentos escudos de ouro batido; para cada escudo destinou trezentos siclos de ouro; e Salomão os pôs na casa do bosque do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ Fez mais o rei um grande trono de marfim, e o revestiu de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ E o trono tinha seis degraus, e um estrado de ouro, que eram ligados ao trono, e encostos de ambos os lados no lugar do assento; e dois leões estavam junto aos encostos.

[[v14-9-19]]

^<<v14-9-19,19>>^ E doze leões estavam ali de ambos os lados, sobre os seis degraus; outro tal não se fez em nenhum reino.

[[v14-9-20]]

^<<v14-9-20,20>>^ Também todas as taças do rei Salomão eram de ouro, e todos os vasos da casa do bosque do Líbano, de ouro puro; a prata reputava-se por nada nos dias de Salomão.

[[v14-9-21]]

^<<v14-9-21,21>>^ Porque, indo os navios do rei com os servos de Hirão, a Társis, voltavam os navios de Társis, uma vez em três anos, e traziam ouro e prata, marfim, bugios e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ Assim excedeu o rei Salomão a todos os reis da terra, em riquezas e sabedoria.

[[v14-9-23]]

^<<v14-9-23,23>>^ E todos os reis da terra buscavam a presença de Salomão, para ouvirem a sabedoria que Deus tinha posto no seu coração.

[[v14-9-24]]

^<<v14-9-24,24>>^ E cada um trazia o seu presente, vasos de prata, e vasos de ouro, e roupas, armaduras, especiarias, cavalos e mulas; assim faziam de ano em ano.

[[v14-9-25]]

^<<v14-9-25,25>>^ Teve também Salomão quatro mil estrebarias para os cavalos de seus carros, e doze mil cavaleiros; e colocou-os nas cidades dos carros, e junto ao rei em Jerusalém.

[[v14-9-26]]

^<<v14-9-26,26>>^ E dominava sobre todos os reis, desde o rio até à terra dos filisteus, e até ao termo do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ Também o rei fez que houvesse prata em Jerusalém como pedras, e cedros em tanta abundância como as figueiras bravas que há pelas campinas.

[[v14-9-28]]

^<<v14-9-28,28>>^ E do Egito e de todas aquelas terras traziam cavalos a Salomão.

[[v14-9-29]]

^<<v14-9-29,29>>^ Os demais atos de Salomão, tanto os primeiros como os últimos, porventura não estão escritos no livro das crônicas de Natã, o profeta, e na profecia de Aías, o silonita, e nas visões de Ido, o vidente, acerca de Jeroboão, filho de Nebate?

[[v14-9-30]]

^<<v14-9-30,30>>^ E reinou Salomão em Jerusalém quarenta anos sobre todo o Israel.

[[v14-9-31]]

^<<v14-9-31,31>>^ E dormiu Salomão com seus pais, e o sepultaram na cidade de Davi seu pai; e Roboão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]