include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-26-1]]

^<<v14-26-1,1>>^ Então todo o povo tomou a Uzias, que tinha dezesseis anos, e o fizeram rei em lugar de Amazias seu pai.

[[v14-26-2]]

^<<v14-26-2,2>>^ Este edificou a Elote, e a restituiu a Judá, depois que o rei dormiu com seus pais.

[[v14-26-3]]

^<<v14-26-3,3>>^ Tinha Uzias dezesseis anos quando começou a reinar, e cinqüenta e dois anos reinou em Jerusalém; e era o nome de sua mãe Jecolia, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ E fez o que era reto aos olhos do Senhor; conforme a tudo o que fizera Amazias seu pai.

[[v14-26-5]]

^<<v14-26-5,5>>^ Porque deu-se a buscar a Deus nos dias de Zacarias, que era entendido nas visões de Deus; e nos dias em que buscou ao Senhor, Deus o fez prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Porque saiu e guerreou contra os filisteus, e quebrou o muro de Gate, o muro de Jabne, e o muro de Asdode; e edificou cidades em Asdode, e entre os filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ E Deus o ajudou contra os filisteus e contra os árabes que habitavam em Gur-Baal, e contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ E os amonitas deram presentes a Uzias; e o seu nome foi espalhado até à entrada do Egito, porque se fortificou altamente.

[[v14-26-9]]

^<<v14-26-9,9>>^ Também Uzias edificou torres em Jerusalém, à porta da esquina, e à porta do vale, e à porta do ângulo, e as fortificou.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também edificou torres no deserto, e cavou muitos poços, porque tinha muito gado, tanto nos vales como nas campinas; tinha lavradores, e vinhateiros, nos montes e nos campos férteis; porque era amigo da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Tinha também Uzias um exército de homens destros na guerra, que saíam à guerra em tropas, segundo o número da resenha feita por mão de Jeiel, o escrivão, e Maaséias, oficial, sob a direção de Hananias, um dos capitàes do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O total dos chefes dos pais, homens valentes, era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ E debaixo das suas ordens havia um exército guerreiro de trezentos e sete mil e quinhentos homens, que faziam a guerra com força belicosa, para ajudar o rei contra os inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ E preparou Uzias, para todo o exército, escudos, lanças, capacetes, couraças e arcos, e até fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Também fez em Jerusalém máquinas da invenção de engenheiros, que estivessem nas torres e nos cantos, para atirarem flechas e grandes pedras; e propagou a sua fama até muito longe; porque foi maravilhosamente ajudado, até que se fortificou.

[[v14-26-16]]

^<<v14-26-16,16>>^ Mas, havendo-se já fortificado, exaltou-se o seu coração até se corromper; e transgrediu contra o Senhor seu Deus, porque entrou no templo do Senhor para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Porém o sacerdote Azarias entrou após ele, e com ele oitenta sacerdotes do Senhor, homens valentes.

[[v14-26-18]]

^<<v14-26-18,18>>^ E resistiram ao rei Uzias, e lhe disseram: A ti, Uzias, não compete queimar incenso perante o Senhor, mas aos sacerdotes, filhos de Arão, que são consagrados para queimar incenso; sai do santuário, porque transgrediste; e não será isto para honra tua da parte do Senhor Deus.

[[v14-26-19]]

^<<v14-26-19,19>>^ Então Uzias se indignou; e tinha o incensário na sua mão para queimar incenso. Indignando-se ele, pois, contra os sacerdotes, a lepra lhe saiu à testa perante os sacerdotes, na casa do Senhor, junto ao altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Então o sumo sacerdote Azarias olhou para ele, como também todos os sacerdotes, e eis que já estava leproso na sua testa, e apressuradamente o lançaram fora; e até ele mesmo se deu pressa a sair, visto que o Senhor o ferira.

[[v14-26-21]]

^<<v14-26-21,21>>^ Assim ficou leproso o rei Uzias até ao dia da sua morte; e morou, por ser leproso, numa casa separada, porque foi excluído da casa do Senhor. E Jotão, seu filho, tinha o encargo da casa do rei, julgando o povo da terra.

[[v14-26-22]]

^<<v14-26-22,22>>^ Quanto ao mais dos atos de Uzias, tanto os primeiros como os últimos, o profeta Isaías, filho de Amós, o escreveu.

[[v14-26-23]]

^<<v14-26-23,23>>^ E dormiu Uzias com seus pais, e o sepultaram com eles no campo do sepulcro que era dos reis; porque disseram: Leproso é. E Jotão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]