include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-29-1]]

^<<v14-29-1,1>>^ Tinha Ezequias vinte e cinco anos de idade, quando começou a reinar, e reinou vinte e nove anos em Jerusalém; e era o nome de sua mãe Abia, filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ E fez o que era reto aos olhos do Senhor, conforme a tudo quanto fizera Davi, seu pai.

[[v14-29-3]]

^<<v14-29-3,3>>^ Ele, no primeiro ano do seu reinado, no primeiro mês, abriu as portas da casa do Senhor, e as reparou.

[[v14-29-4]]

^<<v14-29-4,4>>^ E trouxe os sacerdotes, e os levitas, e ajuntou-os na praça oriental,

[[v14-29-5]]

^<<v14-29-5,5>>^ E lhes disse: Ouvi-me, ó levitas, santificai-vos agora, e santificai a casa do Senhor Deus de vossos pais, e tirai do santuário a imundícia.

[[v14-29-6]]

^<<v14-29-6,6>>^ Porque nossos pais transgrediram, e fizeram o que era mau aos olhos do Senhor nosso Deus, e o deixaram, e desviaram os seus rostos do tabernáculo do Senhor, e lhe deram as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas do alpendre, e apagaram as lâmpadas, e não queimaram incenso nem ofereceram holocaustos no santuário ao Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Por isso veio grande ira do Senhor sobre Judá e Jerusalém, e os entregou à perturbação, à assolação, e ao escárnio, como vós o estais vendo com os vossos olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Porque eis que nossos pais caíram à espada, e nossos filhos, e nossas filhas, e nossas mulheres; por isso estiveram em cativeiro.

[[v14-29-10]]

^<<v14-29-10,10>>^ Agora me tem vindo ao coração, que façamos uma aliança com o Senhor Deus de Israel, para que se desvie de nós o ardor da sua ira.

[[v14-29-11]]

^<<v14-29-11,11>>^ Agora, filhos meus, não sejais negligentes; pois o Senhor vos tem escolhido para estardes diante dele para o servirdes, e para serdes seus ministros e queimadores de incenso.

[[v14-29-12]]

^<<v14-29-12,12>>^ Então se levantaram os levitas, Maate, filho de Amasai, e Joel, filho de Azarias, dos filhos dos coatitas; e dos filhos de Merari, Quis, filho de Abdi, e Azarias, filho de Jealelel; e dos gersonitas, Joá, filho de Zima, e Éden, filho de Joá;

[[v14-29-13]]

^<<v14-29-13,13>>^ E dentre os filhos de Elisafã, Sinri e Jeuel; dentre os filhos de Asafe, Zacarias e Matanias;

[[v14-29-14]]

^<<v14-29-14,14>>^ E dentre os filhos de Hemam, Jeuel e Simei; e dentre os filhos de Jedutum, Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ E ajuntaram a seus irmãos, e santificaram-se e vieram conforme ao mandado do rei, pelas palavras do Senhor, para purificarem a casa do Senhor.

[[v14-29-16]]

^<<v14-29-16,16>>^ E os sacerdotes entraram na casa do Senhor, para a purificar, e tiraram para fora, ao pátio da casa do Senhor, toda a imundícia que acharam no templo do Senhor; e os levitas a tomaram, para a levarem para fora, ao ribeiro de Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram, pois, a santificar no primeiro dia, do primeiro mês; e ao oitavo dia do mês vieram ao alpendre do Senhor, e santificaram a casa do Senhor em oito dias; e no dia décimo sexto do primeiro mês acabaram.

[[v14-29-18]]

^<<v14-29-18,18>>^ Então foram ter com o rei Ezequias, e disseram: Já purificamos toda a casa do Senhor, como também o altar do holocausto com todos os seus utensílios e a mesa da proposição com todos os seus utensílios.

[[v14-29-19]]

^<<v14-29-19,19>>^ Também todos os objetos que o rei Acaz no seu reinado lançou fora, na sua transgressão, já preparamos e santificamos; e eis que estão diante do altar do Senhor.

[[v14-29-20]]

^<<v14-29-20,20>>^ Então o rei Ezequias se levantou de madrugada, e reuniu os líderes da cidade, e subiu à casa do Senhor.

[[v14-29-21]]

^<<v14-29-21,21>>^ E trouxeram sete novilhos e sete carneiros, e sete cordeiros e sete bodes, para sacrifício pelo pecado, pelo reino, e pelo santuário, e por Judá, e disse aos filhos de Arão, os sacerdotes, que os oferecessem sobre o altar do Senhor.

[[v14-29-22]]

^<<v14-29-22,22>>^ E eles mataram os bois, e os sacerdotes tomaram o sangue e o espargiram sobre o altar; também mataram os carneiros, e espargiram o sangue sobre o altar; semelhantemente mataram os cordeiros, e espargiram o sangue sobre o altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Então trouxeram os bodes para sacrifício pelo pecado, perante o rei e a congregação, e lhes impuseram as suas mãos.

[[v14-29-24]]

^<<v14-29-24,24>>^ E os sacerdotes os mataram, e com o seu sangue fizeram expiação do pecado sobre o altar, para reconciliar a todo o Israel; porque o rei tinha ordenado que se fizesse aquele holocausto e sacrifício pelo pecado, por todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ E pôs os levitas na casa do Senhor com címbalos, com saltérios, e com harpas, conforme ao mandado de Davi e de Gade, o vidente do rei, e do profeta Natã; porque este mandado veio do Senhor, por mão de seus profetas.

[[v14-29-26]]

^<<v14-29-26,26>>^ Estavam, pois, os levitas em pé com os instrumentos de Davi, e os sacerdotes com as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ E Ezequias deu ordem que oferecessem o holocausto sobre o altar; e ao tempo em que começou o holocausto, começou também o canto do Senhor, com as trombetas e com os instrumentos de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ E toda a congregação se prostrou, quando entoavam o canto, e as trombetas eram tocadas; tudo isto até o holocausto se acabar.

[[v14-29-29]]

^<<v14-29-29,29>>^ E acabando de o oferecer, o rei e todos quantos com ele se achavam se prostraram e adoraram.

[[v14-29-30]]

^<<v14-29-30,30>>^ Então o rei Ezequias e os príncipes disseram aos levitas que louvassem ao Senhor com as palavras de Davi, e de Asafe, o vidente. E o louvaram com alegria e se inclinaram e adoraram.

[[v14-29-31]]

^<<v14-29-31,31>>^ E respondeu Ezequias, dizendo: Agora vos consagrastes a vós mesmos ao Senhor; chegai-vos e trazei sacrifícios e ofertas de louvor à casa do Senhor. E a congregação trouxe sacrifícios e ofertas de louvor, e todos os dispostos de coração trouxeram holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ E o número dos holocaustos, que a congregação trouxe, foi de setenta bois, cem carneiros, duzentos cordeiros; tudo isto em holocausto para o Senhor.

[[v14-29-33]]

^<<v14-29-33,33>>^ Houve, também, de coisas consagradas, seiscentos bois e três mil ovelhas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Eram, porém, os sacerdotes mui poucos, e não podiam esfolar a todos os holocaustos; pelo que seus irmãos os levitas os ajudaram, até a obra se acabar, e até que os outros sacerdotes se santificaram; porque os levitas foram mais retos de coração, para se santificarem, do que os sacerdotes.

[[v14-29-35]]

^<<v14-29-35,35>>^ E houve também holocaustos em abundância, com a gordura das ofertas pacíficas, e com as ofertas de libação para os holocaustos. Assim se restabeleceu o ministério da casa do Senhor.

[[v14-29-36]]

^<<v14-29-36,36>>^ E Ezequias, e todo o povo se alegraram, por causa daquilo que Deus tinha preparado para o povo; porque apressuradamente se fez esta obra.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]