include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-4-1]]

^<<v14-4-1,1>>^ Também fez um altar de metal, de vinte côvados de comprimento, de vinte côvados de largura e de dez côvados de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez também o mar de fundição, de dez côvados de uma borda até a outra, redondo, e de cinco côvados de altura; cingia-o ao redor um cordão de trinta côvados.

[[v14-4-3]]

^<<v14-4-3,3>>^ E por baixo dele havia figuras de bois, que cingiam o mar ao redor, dez em cada côvado, contornando-o; e tinha duas fileiras de bois, fundidos juntamente com o mar.

[[v14-4-4]]

^<<v14-4-4,4>>^ E o mar estava posto sobre doze bois; três que olhavam para o norte, três que olhavam para o ocidente, três que olhavam para o sul e três que olhavam para o oriente; e o mar estava posto sobre eles; e as suas partes posteriores estavam todas para o lado de dentro.

[[v14-4-5]]

^<<v14-4-5,5>>^ E tinha um palmo de grossura, e a sua borda foi feita como a borda de um copo, ou como uma flor-de-lis, da capacidade de três mil batos.

[[v14-4-6]]

^<<v14-4-6,6>>^ Também fez dez pias; e pôs cinco à direita e cinco à esquerda, para lavarem nelas; o que pertencia ao holocausto o lavavam nelas; porém o mar era para que os sacerdotes se lavassem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez também dez castiçais de ouro, segundo a sua forma, e pô-los no templo, cinco à direita, e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Também fez dez mesas, e pô-las no templo, cinco à direita e cinco à esquerda; também fez cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Fez mais o pátio dos sacerdotes, e o grande átrio; como também as portas para o pátio, as quais revestiu de cobre.

[[v14-4-10]]

^<<v14-4-10,10>>^ E pôs o mar ao lado direito, para o lado do oriente, na direção do sul.

[[v14-4-11]]

^<<v14-4-11,11>>^ Também Hirão fez as caldeiras, as pás e as bacias. Assim acabou Hirão de fazer a obra, que fazia para o rei Salomão, na casa de Deus.

[[v14-4-12]]

^<<v14-4-12,12>>^ As duas colunas, os globos, e os dois capitéis sobre as cabeças das colunas; e as duas redes, para cobrir os dois globos dos capitéis, que estavam sobre a cabeça das colunas.

[[v14-4-13]]

^<<v14-4-13,13>>^ E as quatrocentas romãs para as duas redes; duas carreiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam em cima das colunas.

[[v14-4-14]]

^<<v14-4-14,14>>^ Também fez as bases; e as pias pôs sobre as bases;

[[v14-4-15]]

^<<v14-4-15,15>>^ Um mar, e os doze bois debaixo dele;

[[v14-4-16]]

^<<v14-4-16,16>>^ Semelhantemente as caldeiras, as pás, os garfos e todos os seus utensílios, fez Hirão Abiú ao rei Salomão, para a casa do Senhor, de cobre polido.

[[v14-4-17]]

^<<v14-4-17,17>>^ Na campina do Jordão os fundiu o rei, na terra argilosa, entre Sucote e Zeredá.

[[v14-4-18]]

^<<v14-4-18,18>>^ E fez Salomão todos estes objetos em grande abundância, que não se podia averiguar o peso do cobre.

[[v14-4-19]]

^<<v14-4-19,19>>^ Fez também Salomão todos os objetos que eram para a casa de Deus, como também o altar de ouro, e as mesas, sobre as quais estavam os pães da proposição.

[[v14-4-20]]

^<<v14-4-20,20>>^ E os castiçais com as suas lâmpadas de ouro finíssimo, para as acenderem segundo o costume, perante o oráculo.

[[v14-4-21]]

^<<v14-4-21,21>>^ E as flores, as lâmpadas e os espevitadores eram de ouro, do mais finíssimo ouro.

[[v14-4-22]]

^<<v14-4-22,22>>^ Como também os apagadores, as bacias, as colheres e os incensários de ouro finíssimo; e quanto à entrada da casa, as suas portas de dentro do lugar santíssimo, e as portas da casa do templo, eram de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]