include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-14-1]]

^<<v14-14-1,1>>^ E Abias dormiu com seus pais, e o sepultaram na cidade de Davi, e Asa, seu filho, reinou em seu lugar; nos seus dias esteve a terra em paz dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ E Asa fez o que era bom e reto aos olhos do Senhor seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Porque tirou os altares dos deuses estranhos, e os altos; e quebrou as imagens, e cortou os bosques.

[[v14-14-4]]

^<<v14-14-4,4>>^ E mandou a Judá que buscasse ao Senhor Deus de seus pais, e que observasse a lei e o mandamento.

[[v14-14-5]]

^<<v14-14-5,5>>^ Também tirou de todas as cidades de Judá os altos e as imagens; e sob ele o reino esteve em paz.

[[v14-14-6]]

^<<v14-14-6,6>>^ E edificou cidades fortificadas em Judá; porque a terra estava quieta, e não havia guerra contra ele naqueles anos; porquanto o Senhor lhe dera repouso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Disse, pois, a Judá: Edifiquemos estas cidades, e cerquemo-las de muros e torres, portas e ferrolhos, enquanto a terra ainda é nossa, pois buscamos ao Senhor nosso Deus; buscamo-lo, e deu-nos repouso de todos os lados. Edificaram, pois, e prosperaram.

[[v14-14-8]]

^<<v14-14-8,8>>^ Tinha Asa um exército de trezentos mil de Judá, que traziam pavês e lança; e duzentos e oitenta mil de Benjamim, que traziam escudo e atiravam com arco; todos estes eram homens valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ E Zerá, o etíope, saiu contra eles, com um exército de um milhão e com trezentos carros, e chegou até Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Então Asa saiu contra ele; e ordenaram a batalha no vale de Zefatá, junto a Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ E Asa clamou ao Senhor seu Deus, e disse: Senhor, nada para ti é ajudar, quer o poderoso quer o de nenhuma força; ajuda-nos, pois, Senhor nosso Deus, porque em ti confiamos, e no teu nome viemos contra esta multidão. Senhor, tu és nosso Deus, não prevaleça contra ti o homem.

[[v14-14-12]]

^<<v14-14-12,12>>^ E o Senhor feriu os etíopes diante de Asa e diante de Judá; e os etíopes fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ E Asa, e o povo que estava com ele os perseguiram até Gerar, e caíram tantos dos etíopes, que já não havia neles resistência alguma; porque foram destruídos diante do Senhor, e diante do seu exército; e levaram dali mui grande despojo.

[[v14-14-14]]

^<<v14-14-14,14>>^ E feriram todas as cidades nos arredores de Gerar, porque o terror do Senhor veio sobre elas; e saquearam todas as cidades, porque havia nelas muita presa.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também feriram as malhadas do gado; e levaram ovelhas em abundância, e camelos, e voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]