include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-13-1]]

^<<v14-13-1,1>>^ No ano décimo oitavo do rei Jeroboão, Abias começou a reinar sobre Judá.

[[v14-13-2]]

^<<v14-13-2,2>>^ Três anos reinou em Jerusalém; e era o nome de sua mãe Micaía, filha de Uriel de Gibeá; e houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ E Abias ordenou a peleja com um exército de valentes guerreiros, quatrocentos mil homens escolhidos; e Jeroboão dispôs contra ele a batalha com oitocentos mil homens escolhidos, todos homens corajosos.

[[v14-13-4]]

^<<v14-13-4,4>>^ E pôs-se Abias em pé em cima do monte de Zemaraim, que está na montanha de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel:

[[v14-13-5]]

^<<v14-13-5,5>>^ Porventura não vos convém saber que o Senhor Deus de Israel deu para sempre a Davi a soberania sobre Israel, a ele e a seus filhos, por uma aliança de sal?

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo levantou-se Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, e se rebelou contra seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ E ajuntaram-se a ele homens vadios, filhos de Belial; e fortificaram-se contra Roboão, filho de Salomão, sendo Roboão ainda jovem, e terno de coração, e não lhes podia resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ E agora julgais que podeis resistir ao reino do Senhor, que está na mão dos filhos de Davi, visto que sois uma grande multidão, e tendes convosco os bezerros de ouro que Jeroboão vos fez para deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não lançastes vós fora os sacerdotes do Senhor, os filhos de Arão, e os levitas, e não fizestes para vós sacerdotes, como os povos das outras terras? Qualquer que vem a consagrar-se com um novilho e sete carneiros logo se faz sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ Porém, quanto a nós, o Senhor é nosso Deus, e nunca o deixamos; e os sacerdotes que ministram ao Senhor são filhos de Arão, e os levitas se ocupam na sua obra.

[[v14-13-11]]

^<<v14-13-11,11>>^ E queimam ao Senhor cada manhã e cada tarde holocaustos, incenso aromático, com os pães da proposição sobre a mesa pura, e o castiçal de ouro, e as suas lâmpadas para se acenderem cada tarde, porque nós temos cuidado do serviço do Senhor nosso Deus; porém vós o deixastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ E eis que Deus está conosco, à nossa frente, como também os seus sacerdotes, tocando com as trombetas, para dar alarme contra vós. Ó filhos de Israel, não pelejeis contra o Senhor Deus de vossos pais; porque não prosperareis.

[[v14-13-13]]

^<<v14-13-13,13>>^ Mas Jeroboão armou uma emboscada, para dar sobre eles pela retaguarda; de maneira que estavam em frente de Judá e a emboscada por detrás deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Então Judá olhou, e eis que tinham que pelejar por diante e por detrás; então clamaram ao Senhor; e os sacerdotes tocaram as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ E os homens de Judá gritaram; e sucedeu que, gritando os homens de Judá, Deus feriu a Jeroboão e a todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ E os filhos de Israel fugiram de diante de Judá; e Deus os entregou na sua mão.

[[v14-13-17]]

^<<v14-13-17,17>>^ De maneira que Abias e o seu povo fizeram grande matança entre eles; porque caíram feridos de Israel quinhentos mil homens escolhidos.

[[v14-13-18]]

^<<v14-13-18,18>>^ E foram humilhados os filhos de Israel naquele tempo; e os filhos de Judá prevaleceram, porque confiaram no Senhor Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ E Abias perseguiu Jeroboão; e tomou-lhe a Betel com os lugares da sua jurisdição, e a Jesana com os lugares da sua jurisdição, e a Efrom com os lugares da sua jurisdição.

[[v14-13-20]]

^<<v14-13-20,20>>^ E Jeroboão não recobrou mais o seu poder nos dias de Abias; porém o Senhor o feriu, e morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, porém, se fortificou, e tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Os demais atos de Abias, tanto os seus caminhos como as suas palavras, estão escritos na história do profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]