include::./index.adoc[]

[[v14-16-0]]
=== 2 Crônicas, 16
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-16-1]]

^<<v14-16-1,1>>^ No trigésimo sexto ano do reinado de Asa, Baasa, rei de Israel, subiu contra Judá e edificou a Ramá, para não deixar ninguém sair, nem chegar a Asa, rei de Judá.

[[v14-16-2]]

^<<v14-16-2,2>>^ Então Asa tirou a prata e o ouro dos tesouros da casa do Senhor, e da casa do rei; e enviou servos a Ben-Hadade, rei da Síria, que habitava em Damasco, dizendo:

[[v14-16-3]]

^<<v14-16-3,3>>^ Acordo há entre mim e ti, como houve entre meu pai e o teu; eis que te envio prata e ouro; vai, pois, e anula o teu acordo com Baasa, rei de Israel, para que se retire de sobre mim.

[[v14-16-4]]

^<<v14-16-4,4>>^ E Ben-Hadade deu ouvidos ao rei Asa, e enviou os capitães dos seus exércitos, contra as cidades de Israel, e eles feriram a Ijom, a Dã, a Abel-Maim, e a todas as cidades-armazéns de Naftali.

[[v14-16-5]]

^<<v14-16-5,5>>^ E sucedeu que, ouvindo-o Baasa, deixou de edificar a Ramá, e não continuou a sua obra.

[[v14-16-6]]

^<<v14-16-6,6>>^ Então o rei Asa tomou a todo o Judá, e levaram as pedras de Ramá, e a sua madeira, com que Baasa edificara; e com elas edificou a Geba e a Mizpá.

[[v14-16-7]]

^<<v14-16-7,7>>^ Naquele mesmo tempo veio Hanani, o vidente, a Asa, rei de Judá, e disse-lhe: Porquanto confiaste no rei da Síria, e não confiaste no Senhor teu Deus, por isso o exército do rei da Síria escapou da tua mão.

[[v14-16-8]]

^<<v14-16-8,8>>^ Porventura não foram os etíopes e os líbios um grande exército, com muitíssimos carros e cavaleiros? Confiando tu, porém, no Senhor, ele os entregou nas tuas mãos.

[[v14-16-9]]

^<<v14-16-9,9>>^ Porque, quanto ao Senhor, seus olhos passam por toda a terra, para mostrar-se forte para com aqueles cujo coração é perfeito para com ele; nisto, pois, procedeste loucamente porque desde agora haverá guerras contra ti.

[[v14-16-10]]

^<<v14-16-10,10>>^ Porém Asa se indignou contra o vidente, e lançou-o na casa do tronco; porque estava enfurecido contra ele, por causa disto; também Asa, no mesmo tempo, oprimiu a alguns do povo.

[[v14-16-11]]

^<<v14-16-11,11>>^ E eis que os atos de Asa, tanto os primeiros, como os últimos, estão escritos no livro dos reis de Judá e Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ E, no ano trinta e nove do seu reinado, Asa caiu doente de seus pés, a sua doença era em extremo grave; contudo, na sua enfermidade, não buscou ao Senhor, mas antes os médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ E Asa dormiu com seus pais; e morreu no ano quarenta e um do seu reinado.

[[v14-16-14]]

^<<v14-16-14,14>>^ E o sepultaram no seu sepulcro, que tinha cavado para si na cidade de Davi, havendo-o deitado na cama, que se enchera de perfumes e especiarias preparadas segundo a arte dos perfumistas; e, destas coisas fizeram-lhe uma grande queima.

'''

xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]