include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v14-2-1]]

^<<v14-2-1,1>>^ E determinou Salomão edificar uma casa ao nome do SENHOR, como também uma casa para o seu reino.

[[v14-2-2]]

^<<v14-2-2,2>>^ E designou Salomão setenta mil homens de carga, e oitenta mil que talhavam pedras na montanha, e três mil e seiscentos inspetores sobre eles.

[[v14-2-3]]

^<<v14-2-3,3>>^ E Salomão mandou dizer a Hirão, rei de Tiro: Como fizeste com Davi meu pai, mandando-lhe cedros, para edificar uma casa em que morasse, assim também faze comigo.

[[v14-2-4]]

^<<v14-2-4,4>>^ Eis que estou para edificar uma casa ao nome do Senhor meu Deus, para lhe consagrar, para queimar perante ele incenso aromático, e para a apresentação contínua do pão da proposição, para os holocaustos da manhã e da tarde, nos sábados e nas luas novas, e nas festividades do Senhor nosso Deus; o que é obrigação perpétua de Israel.

[[v14-2-5]]

^<<v14-2-5,5>>^ E a casa que estou para edificar há de ser grande; porque o nosso Deus é maior do que todos os deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ Porém, quem seria capaz de lhe edificar uma casa, visto que os céus e até os céus dos céus o não podem conter? E quem sou eu, que lhe edificasse casa, salvo para queimar incenso perante ele?

[[v14-2-7]]

^<<v14-2-7,7>>^ Manda-me, pois, agora um homem hábil para trabalhar em ouro, em prata, em bronze, em ferro, em púrpura, em carmesim e em azul; e que saiba lavrar ao buril, juntamente com os peritos que estão comigo em Judá e em Jerusalém, os quais Davi, meu pai, preparou.

[[v14-2-8]]

^<<v14-2-8,8>>^ Manda-me também madeiras de cedro, de cipreste, e algumins do Líbano; porque bem sei eu que os teus servos sabem cortar madeira no Líbano; e eis que os meus servos estarão com os teus servos.

[[v14-2-9]]

^<<v14-2-9,9>>^ E isso para prepararem muita madeira; porque a casa que estou para fazer há de ser grande e maravilhosa.

[[v14-2-10]]

^<<v14-2-10,10>>^ E eis que a teus servos, os cortadores, que cortarem a madeira, darei vinte mil coros de trigo malhado, vinte mil coros de cevada, vinte mil batos de vinho e vinte mil batos de azeite.

[[v14-2-11]]

^<<v14-2-11,11>>^ E Hirão, rei de Tiro, respondeu por escrito que enviou a Salomão, dizendo: Porque o Senhor tem amado o seu povo, te constituiu sobre ele rei.

[[v14-2-12]]

^<<v14-2-12,12>>^ Disse mais Hirão: Bendito seja o Senhor Deus de Israel, que fez os céus e a terra; o que deu ao rei Davi um filho sábio, de grande prudência e entendimento, que edifique casa ao Senhor, e para o seu reino.

[[v14-2-13]]

^<<v14-2-13,13>>^ Agora, pois, envio um homem sábio de grande entendimento, a saber, Hirão Abiú.

[[v14-2-14]]

^<<v14-2-14,14>>^ Filho de uma mulher das filhas de Dã, e cujo pai foi homem de Tiro; este sabe trabalhar em ouro, em prata, em bronze, em ferro, em pedras e em madeira, em púrpura, em azul, e em linho fino, e em carmesim, e é hábil para toda a obra do buril, e para toda a espécie de invenções, qualquer coisa que se lhe propuser, juntamente com os teus peritos, e os peritos de Davi, meu senhor, teu pai.

[[v14-2-15]]

^<<v14-2-15,15>>^ Agora, pois, meu senhor, mande para os seus servos o trigo, a cevada, o azeite e o vinho, de que falou;

[[v14-2-16]]

^<<v14-2-16,16>>^ E nós cortaremos tanta madeira no Líbano, quanta houveres mister, e ta traremos em jangadas pelo mar até Jope, e tu a farás subir a Jerusalém.

[[v14-2-17]]

^<<v14-2-17,17>>^ E Salomão contou todos os homens estrangeiros, que havia na terra de Israel, conforme o censo com que os contara Davi seu pai; e acharam-se cento e cinqüenta e três mil e seiscentos.

[[v14-2-18]]

^<<v14-2-18,18>>^ E designou deles setenta mil carregadores, e oitenta mil cortadores na montanha; como também três mil e seiscentos inspetores, para fazerem trabalhar o povo.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]