include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-37-1]]

^<<v2-37-1,1>>^ Fez também Bezalel a arca de madeira de acácia; o seu comprimento era de dois côvados e meio; e a sua largura de um côvado e meio; e a sua altura de um côvado e meio.

[[v2-37-2]]

^<<v2-37-2,2>>^ E cobriu-a de ouro puro por dentro e por fora; e fez-lhe uma coroa de ouro ao redor;

[[v2-37-3]]

^<<v2-37-3,3>>^ E fundiu-lhe quatro argolas de ouro nos seus quatro cantos; num lado duas, e no outro lado duas argolas;

[[v2-37-4]]

^<<v2-37-4,4>>^ E fez varais de madeira de acácia, e os cobriu de ouro;

[[v2-37-5]]

^<<v2-37-5,5>>^ E pôs os varais pelas argolas aos lados da arca, para se levar a arca.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez também o propiciatório de ouro puro; o seu comprimento era de dois côvados e meio, e a sua largura de um côvado e meio.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro; de obra batida os fez, nas duas extremidades do propiciatório.

[[v2-37-8]]

^<<v2-37-8,8>>^ Um querubim na extremidade de um lado, e o outro na outra extremidade do outro lado; de uma só peça com o propiciatório fez os querubins nas duas extremidades dele.

[[v2-37-9]]

^<<v2-37-9,9>>^ E os querubins estendiam as asas por cima, cobrindo com elas o propiciatório; e os seus rostos estavam defronte um do outro; os rostos dos querubins estavam virados para o propiciatório.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também a mesa de madeira de acácia; o seu comprimento era de dois côvados, e a sua largura de um côvado, e a sua altura de um côvado e meio.

[[v2-37-11]]

^<<v2-37-11,11>>^ E cobriu-a de ouro puro, e fez-lhe uma coroa de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Fez-lhe também, ao redor, uma moldura da largura da mão; e fez uma coroa de ouro ao redor da moldura.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu-lhe também quatro argolas de ouro; e pôs as argolas nos quatro cantos que estavam em seus quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Defronte da moldura estavam as argolas para os lugares dos varais, para se levar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez também os varais de madeira de acácia, e os cobriu de ouro, para se levar a mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ E fez de ouro puro os utensílios que haviam de estar sobre a mesa, os seus pratos e as suas colheres, e as suas tigelas e as suas taças em que se haviam de oferecer libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o candelabro de ouro puro; de obra batida fez este candelabro; o seu pedestal, e as suas hastes, os seus copos, as suas maçãs, e as suas flores, formavam com ele uma só peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis hastes saíam dos seus lados; três hastes do candelabro, de um lado dele, e três do outro lado.

[[v2-37-19]]

^<<v2-37-19,19>>^ Numa haste estavam três copos do feitio de amêndoas, um botão e uma flor; e na outra haste três copos do feitio de amêndoas, um botão e uma flor; assim eram as seis hastes que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Mas no mesmo candelabro havia quatro copos do feitio de amêndoas com os seus botões e com as suas flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ E havia um botão debaixo de duas hastes da mesma peça; e outro botão debaixo de duas hastes da mesma peça; e mais um botão debaixo de duas hastes da mesma peça; assim se fez para as seis hastes, que saíam dele.

[[v2-37-22]]

^<<v2-37-22,22>>^ Os seus botões e as suas hastes eram da mesma peça; tudo era uma obra batida de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ E fez-lhe, de ouro puro, sete lâmpadas com os seus espevitadores e os seus apagadores;

[[v2-37-24]]

^<<v2-37-24,24>>^ De um talento de ouro puro fez o candelabro e todos os seus utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ E fez o altar do incenso de madeira de acácia; de um côvado era o seu comprimento, e de um côvado a sua largura, era quadrado; e de dois côvados a sua altura; dele mesmo eram feitas as suas pontas.

[[v2-37-26]]

^<<v2-37-26,26>>^ E cobriu-o de ouro puro, a parte superior e as suas paredes ao redor, e as suas pontas; e fez-lhe uma coroa de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez-lhe também duas argolas de ouro debaixo da sua coroa, e os seus dois cantos, de ambos os seus lados, para neles se colocar os varais, e com eles levá-lo.

[[v2-37-28]]

^<<v2-37-28,28>>^ E os varais fez de madeira de acácia, e os cobriu de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Também fez o azeite santo da unção, e o incenso aromático, puro, qual obra do perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]