include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-35-1]]

^<<v2-35-1,1>>^ Então Moisés convocou toda a congregação dos filhos de Israel, e disse-lhes: Estas são as palavras que o SENHOR ordenou que se cumprissem.

[[v2-35-2]]

^<<v2-35-2,2>>^ Seis dias se trabalhará, mas o sétimo dia vos será santo, o sábado do repouso ao Senhor; todo aquele que nele fizer qualquer trabalho morrerá.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendereis fogo em nenhuma das vossas moradas no dia do sábado.

[[v2-35-4]]

^<<v2-35-4,4>>^ Falou mais Moisés a toda a congregação dos filhos de Israel, dizendo: Esta é a palavra que o Senhor ordenou, dizendo:

[[v2-35-5]]

^<<v2-35-5,5>>^ Tomai do que tendes, uma oferta para o Senhor; cada um, cujo coração é voluntariamente disposto, a trará por oferta alçada ao Senhor: ouro, prata e cobre,

[[v2-35-6]]

^<<v2-35-6,6>>^ Como também azul, púrpura, carmesim, linho fino, pêlos de cabras,

[[v2-35-7]]

^<<v2-35-7,7>>^ E peles de carneiros, tintas de vermelho, e peles de texugos, madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ E azeite para a luminária, e especiarias para o azeite da unção, e para o incenso aromático.

[[v2-35-9]]

^<<v2-35-9,9>>^ E pedras de ônix, e pedras de engaste, para o éfode e para o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ E venham todos os sábios de coração entre vós, e façam tudo o que o Senhor tem mandado;

[[v2-35-11]]

^<<v2-35-11,11>>^ O tabernáculo, a sua tenda e a sua coberta, os seus colchetes e as suas tábuas, as suas barras, as suas colunas, e as suas bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ A arca e os seus varais, o propiciatório e o véu de cobertura,

[[v2-35-13]]

^<<v2-35-13,13>>^ A mesa e os seus varais, e todos os seus pertences; e os pães da proposição,

[[v2-35-14]]

^<<v2-35-14,14>>^ E o candelabro da luminária, e os seus utensílios, e as suas lâmpadas, e o azeite para a luminária,

[[v2-35-15]]

^<<v2-35-15,15>>^ E o altar do incenso e os seus varais, e o azeite da unção, e o incenso aromático, e a cortina da porta para a entrada do tabernáculo,

[[v2-35-16]]

^<<v2-35-16,16>>^ O altar do holocausto, e o crivo de cobre, os seus varais, e todos os seus pertences, a pia e a sua base,

[[v2-35-17]]

^<<v2-35-17,17>>^ As cortinas do pátio, as suas colunas e as suas bases, e o reposteiro da porta do pátio,

[[v2-35-18]]

^<<v2-35-18,18>>^ As estacas do tabernáculo, e as estacas do pátio, e as suas cordas,

[[v2-35-19]]

^<<v2-35-19,19>>^ As vestes do ministério para ministrar no santuário, as vestes santas de Arão o sacerdote, e as vestes de seus filhos, para administrarem o sacerdócio.

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a congregação dos filhos de Israel saiu da presença de Moisés,

[[v2-35-21]]

^<<v2-35-21,21>>^ E veio todo o homem, a quem o seu coração moveu, e todo aquele cujo espírito voluntariamente o excitou, e trouxeram a oferta alçada ao Senhor para a obra da tenda da congregação, e para todo o seu serviço, e para as vestes santas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Assim vieram homens e mulheres, todos dispostos de coração; trouxeram fivelas, e pendentes, e anéis, e braceletes, todos os objetos de ouro; e todo o homem fazia oferta de ouro ao Senhor;

[[v2-35-23]]

^<<v2-35-23,23>>^ E todo o homem que se achou com azul, e púrpura, e carmesim, e linho fino, e pêlos de cabras, e peles de carneiro tintas de vermelho, e peles de texugos, os trazia;

[[v2-35-24]]

^<<v2-35-24,24>>^ Todo aquele que fazia oferta alçada de prata ou de metal, a trazia por oferta alçada ao Senhor; e todo aquele que possuía madeira de acácia, a trazia para toda a obra do serviço.

[[v2-35-25]]

^<<v2-35-25,25>>^ E todas as mulheres sábias de coração fiavam com as suas mãos, e traziam o que tinham fiado, o azul e a púrpura, o carmesim e o linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres, cujo coração as moveu em habilidade fiavam os pêlos das cabras.

[[v2-35-27]]

^<<v2-35-27,27>>^ E os príncipes traziam pedras de ônix e pedras de engastes para o éfode e para o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ E especiarias, e azeite para a luminária, e para o azeite da unção, e para o incenso aromático.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todo homem e mulher, cujo coração voluntariamente se moveu a trazer alguma coisa para toda a obra que o Senhor ordenara se fizesse pela mão de Moisés; assim os filhos de Israel trouxeram por oferta voluntária ao Senhor.

[[v2-35-30]]

^<<v2-35-30,30>>^ Depois disse Moisés aos filhos de Israel: Eis que o Senhor tem chamado por nome a Bezalel, filho de Uri, filho de Hur, da tribo de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ E o Espírito de Deus o encheu de sabedoria, entendimento, ciência e em todo o lavor,

[[v2-35-32]]

^<<v2-35-32,32>>^ E para criar invenções, para trabalhar em ouro, e em prata, e em cobre,

[[v2-35-33]]

^<<v2-35-33,33>>^ E em lapidar de pedras para engastar, e em entalhar madeira, e para trabalhar em toda a obra esmerada.

[[v2-35-34]]

^<<v2-35-34,34>>^ Também lhe dispôs o coração para ensinar a outros; a ele e a Aoliabe, o filho de Aisamaque, da tribo de Dã.

[[v2-35-35]]

^<<v2-35-35,35>>^ Encheu-os de sabedoria do coração, para fazer toda a obra de mestre, até a mais engenhosa, e a do gravador, em azul, e em púrpura, em carmesim, e em linho fino, e do tecelão; fazendo toda a obra, e criando invenções.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]