include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-6-1]]

^<<v2-6-1,1>>^ Então disse o SENHOR a Moisés: Agora verás o que hei de fazer a Faraó; porque por uma mão poderosa os deixará ir, sim, por uma mão poderosa os lançará de sua terra.

[[v2-6-2]]

^<<v2-6-2,2>>^ Falou mais Deus a Moisés, e disse: Eu sou o Senhor.

[[v2-6-3]]

^<<v2-6-3,3>>^ E eu apareci a Abraão, a Isaque, e a Jacó, como o Deus Todo-Poderoso; mas pelo meu nome, o Senhor, não lhes fui perfeitamente conhecido.

[[v2-6-4]]

^<<v2-6-4,4>>^ E também estabeleci a minha aliança com eles, para dar-lhes a terra de Canaã, a terra de suas peregrinações, na qual foram peregrinos.

[[v2-6-5]]

^<<v2-6-5,5>>^ E também tenho ouvido o gemido dos filhos de Israel, aos quais os egípcios fazem servir, e lembrei-me da minha aliança.

[[v2-6-6]]

^<<v2-6-6,6>>^ Portanto dize aos filhos de Israel: Eu sou o Senhor, e vos tirarei de debaixo das cargas dos egípcios, e vos livrarei da servidão, e vos resgatarei com braço estendido e com grandes juízos.

[[v2-6-7]]

^<<v2-6-7,7>>^ E eu vos tomarei por meu povo, e serei vosso Deus; e sabereis que eu sou o Senhor vosso Deus, que vos tiro de debaixo das cargas dos egípcios;

[[v2-6-8]]

^<<v2-6-8,8>>^ E eu vos levarei à terra, acerca da qual levantei minha mão, jurando que a daria a Abraão, a Isaque e a Jacó, e vo-la darei por herança, eu o Senhor.

[[v2-6-9]]

^<<v2-6-9,9>>^ Deste modo falou Moisés aos filhos de Israel, mas eles não ouviram a Moisés, por causa da angústia de espírito e da dura servidão.

[[v2-6-10]]

^<<v2-6-10,10>>^ Falou mais o Senhor a Moisés, dizendo:

[[v2-6-11]]

^<<v2-6-11,11>>^ Entra, e fala a Faraó rei do Egito, que deixe sair os filhos de Israel da sua terra.

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés, porém, falou perante o Senhor, dizendo: Eis que os filhos de Israel não me têm ouvido; como, pois, Faraó me ouvirá? Também eu sou incircunciso de lábios.

[[v2-6-13]]

^<<v2-6-13,13>>^ Todavia o Senhor falou a Moisés e a Arão, e deu-lhes mandamento para os filhos de Israel, e para Faraó rei do Egito, para que tirassem os filhos de Israel da terra do Egito.

[[v2-6-14]]

^<<v2-6-14,14>>^ Estas são as cabeças das casas de seus pais: Os filhos de Rúben, o primogênito de Israel: Enoque e Palu, Hezrom e Carmi; estas são as famílias de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ E os filhos de Simeão: Jemuel, Jamin, Oade, Jaquim, Zoar e Saul, filho de uma cananéia; estas são as famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ E estes são os nomes dos filhos de Levi, segundo as suas gerações: Gérson, Coate e Merari; e os anos da vida de Levi foram cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Os filhos de Gérson: Libni e Simei, segundo as suas famílias;

[[v2-6-18]]

^<<v2-6-18,18>>^ E os filhos de Coate: Anrão, Izar, Hebrom e Uziel; e os anos da vida de Coate foram cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ E os filhos de Merari: Mali e Musi; estas são as famílias de Levi, segundo as suas gerações.

[[v2-6-20]]

^<<v2-6-20,20>>^ E Anrão tomou por mulher a Joquebede, sua tia, e ela deu-lhe Arão e Moisés: e os anos da vida de Anrão foram cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ E os filhos de Izar: Corá, Nefegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ E os filhos de Uziel: Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ E Arão tomou por mulher a Eliseba, filha de Aminadabe, irmã de Naasson; e ela deu-lhe Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ E os filhos de Corá: Assir, Elcana e Abiasafe; estas são as famílias dos coraítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ E Eleazar, filho de Arão, tomou por mulher uma das filhas de Putiel, e ela deu-lhe a Finéias; estes são os cabeças dos pais dos levitas, segundo as suas famílias.

[[v2-6-26]]

^<<v2-6-26,26>>^ Estes são Arão e Moisés, aos quais o Senhor disse: Tirai os filhos de Israel da terra do Egito, segundo os seus exércitos.

[[v2-6-27]]

^<<v2-6-27,27>>^ Estes são os que falaram a Faraó, rei do Egito, para que tirasse do Egito os filhos de Israel; estes são Moisés e Arão.

[[v2-6-28]]

^<<v2-6-28,28>>^ E aconteceu que naquele dia, quando o Senhor falou a Moisés na terra do Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ Falou o Senhor a Moisés, dizendo: Eu sou o Senhor; fala a Faraó, rei do Egito, tudo quanto eu te digo.

[[v2-6-30]]

^<<v2-6-30,30>>^ Então disse Moisés perante o Senhor: Eis que eu sou incircunciso de lábios; como, pois, Faraó me ouvirá?

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]