include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-22-1]]

^<<v2-22-1,1>>^ Se alguém furtar boi ou ovelha, e o degolar ou vender, por um boi pagará cinco bois, e pela ovelha quatro ovelhas.

[[v2-22-2]]

^<<v2-22-2,2>>^ Se o ladrão for achado roubando, e for ferido, e morrer, o que o feriu não será culpado do sangue.

[[v2-22-3]]

^<<v2-22-3,3>>^ Se o sol houver saído sobre ele, o agressor será culpado do sangue; o ladrão fará restituição total; e se não tiver com que pagar, será vendido por seu furto.

[[v2-22-4]]

^<<v2-22-4,4>>^ Se o furto for achado vivo na sua mão, seja boi, ou jumento, ou ovelha, pagará o dobro.

[[v2-22-5]]

^<<v2-22-5,5>>^ Se alguém fizer pastar o seu animal num campo ou numa vinha, e largá-lo para comer no campo de outro, o melhor do seu próprio campo e o melhor da sua própria vinha restituirá.

[[v2-22-6]]

^<<v2-22-6,6>>^ Se irromper um fogo, e pegar nos espinhos, e queimar a meda de trigo, ou a seara, ou o campo, aquele que acendeu o fogo totalmente pagará o queimado.

[[v2-22-7]]

^<<v2-22-7,7>>^ Se alguém der ao seu próximo dinheiro, ou bens, a guardar, e isso for furtado da casa daquele homem, o ladrão, se for achado, pagará o dobro.

[[v2-22-8]]

^<<v2-22-8,8>>^ Se o ladrão não for achado, então o dono da casa será levado diante dos juízes, a ver se não pôs a sua mão nos bens do seu próximo.

[[v2-22-9]]

^<<v2-22-9,9>>^ Sobre todo o negócio fraudulento, sobre boi, sobre jumento, sobre gado miúdo, sobre roupa, sobre toda a coisa perdida, de que alguém disser que é sua, a causa de ambos será levada perante os juízes; aquele a quem condenarem os juízes pagará em dobro ao seu próximo.

[[v2-22-10]]

^<<v2-22-10,10>>^ Se alguém der a seu próximo a guardar um jumento, ou boi, ou ovelha, ou outro animal, e este morrer, ou for dilacerado, ou arrebatado, ninguém o vendo,

[[v2-22-11]]

^<<v2-22-11,11>>^ Então haverá juramento do Senhor entre ambos, de que não pôs a sua mão nos bens do seu próximo; e seu dono o aceitará, e o outro não o restituirá.

[[v2-22-12]]

^<<v2-22-12,12>>^ Mas, se de fato lhe tiver sido furtado, pagá-lo-á ao seu dono.

[[v2-22-13]]

^<<v2-22-13,13>>^ Porém se lhe for dilacerado, trá-lo-á em testemunho disso, e não pagará o dilacerado.

[[v2-22-14]]

^<<v2-22-14,14>>^ E se alguém pedir emprestado a seu próximo algum animal, e for danificado ou morto, não estando presente o seu dono, certamente o pagará.

[[v2-22-15]]

^<<v2-22-15,15>>^ Se o seu dono estava presente, não o pagará; se foi alugado, será pelo seu aluguel.

[[v2-22-16]]

^<<v2-22-16,16>>^ Se alguém enganar alguma virgem, que não for desposada, e se deitar com ela, certamente a dotará e tomará por sua mulher.

[[v2-22-17]]

^<<v2-22-17,17>>^ Se seu pai inteiramente recusar dar-lha, pagará ele em dinheiro conforme ao dote das virgens.

[[v2-22-18]]

^<<v2-22-18,18>>^ A feiticeira não deixarás viver.

[[v2-22-19]]

^<<v2-22-19,19>>^ Todo aquele que se deitar com animal, certamente morrerá.

[[v2-22-20]]

^<<v2-22-20,20>>^ O que sacrificar aos deuses, e não só ao Senhor, será morto.

[[v2-22-21]]

^<<v2-22-21,21>>^ O estrangeiro não afligirás, nem o oprimirás; pois estrangeiros fostes na terra do Egito.

[[v2-22-22]]

^<<v2-22-22,22>>^ A nenhuma viúva nem órfão afligireis.

[[v2-22-23]]

^<<v2-22-23,23>>^ Se de algum modo os afligires, e eles clamarem a mim, eu certamente ouvirei o seu clamor.

[[v2-22-24]]

^<<v2-22-24,24>>^ E a minha ira se acenderá, e vos matarei à espada; e vossas mulheres ficarão viúvas, e vossos filhos órfãos.

[[v2-22-25]]

^<<v2-22-25,25>>^ Se emprestares dinheiro ao meu povo, ao pobre que está contigo, não te haverás com ele como um usurário; não lhe imporeis usura.

[[v2-22-26]]

^<<v2-22-26,26>>^ Se tomares em penhor a roupa do teu próximo, lho restituirás antes do pôr do sol,

[[v2-22-27]]

^<<v2-22-27,27>>^ Porque aquela é a sua cobertura, e o vestido da sua pele; em que se deitaria? Será pois que, quando clamar a mim, eu o ouvirei, porque sou misericordioso.

[[v2-22-28]]

^<<v2-22-28,28>>^ A Deus não amaldiçoarás, e o príncipe dentre o teu povo não maldirás.

[[v2-22-29]]

^<<v2-22-29,29>>^ As tuas primícias, e os teus licores não retardarás; o primogênito de teus filhos me darás.

[[v2-22-30]]

^<<v2-22-30,30>>^ Assim farás dos teus bois e das tuas ovelhas: sete dias estarão com sua mãe, e ao oitavo dia mos darás.

[[v2-22-31]]

^<<v2-22-31,31>>^ E ser-me-eis homens santos; portanto não comereis carne despedaçada no campo; aos cães a lançareis.

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]