include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-36-1]]

^<<v2-36-1,1>>^ Assim trabalharam Bezalel e Aoliabe, e todo o homem sábio de coração, a quem o SENHOR dera sabedoria e inteligência, para saber como haviam de fazer toda a obra para o serviço do santuário, conforme a tudo o que o SENHOR tinha ordenado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Então Moisés chamou a Bezalel e a Aoliabe, e a todo o homem sábio de coração, em cujo coração o Senhor tinha dado sabedoria; a todo aquele a quem o seu coração moveu a se chegar à obra para fazê-la.

[[v2-36-3]]

^<<v2-36-3,3>>^ Estes receberam de Moisés toda a oferta alçada, que trouxeram os filhos de Israel para a obra do serviço do santuário, para fazê-la, e ainda eles lhe traziam cada manhã ofertas voluntárias.

[[v2-36-4]]

^<<v2-36-4,4>>^ E vieram todos os sábios, que faziam toda a obra do santuário, cada um da obra que fazia,

[[v2-36-5]]

^<<v2-36-5,5>>^ E falaram a Moisés, dizendo: O povo traz muito mais do que basta para o serviço da obra que o Senhor ordenou se fizesse.

[[v2-36-6]]

^<<v2-36-6,6>>^ Então mandou Moisés que proclamassem por todo o arraial, dizendo: Nenhum homem, nem mulher, faça mais obra alguma para a oferta alçada do santuário. Assim o povo foi proibido de trazer mais,

[[v2-36-7]]

^<<v2-36-7,7>>^ Porque tinham material bastante para toda a obra que havia de fazer-se, e ainda sobejava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Assim todo o sábio de coração, entre os que faziam a obra, fez o tabernáculo de dez cortinas de linho fino torcido, e de azul, e de púrpura, e de carmesim, com querubins; da obra mais esmerada as fez.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada cortina era de vinte e oito côvados, e a largura de quatro côvados; todas as cortinas tinham uma mesma medida.

[[v2-36-10]]

^<<v2-36-10,10>>^ E ligou cinco cortinas uma com a outra; e outras cinco cortinas também ligou uma com outra.

[[v2-36-11]]

^<<v2-36-11,11>>^ Depois fez laçadas de azul na borda de uma cortina, à extremidade, na juntura; assim também fez na borda, à extremidade da juntura da segunda cortina.

[[v2-36-12]]

^<<v2-36-12,12>>^ Cinqüenta laçadas fez numa cortina, e cinqüenta laçadas fez numa extremidade da cortina, que se ligava com a segunda; estas laçadas eram contrapostas uma a outra.

[[v2-36-13]]

^<<v2-36-13,13>>^ Também fez cinqüenta colchetes de ouro, e com estes colchetes uniu as cortinas uma com a outra; e assim foi feito um tabernáculo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fez também cortinas de pêlos de cabras para a tenda sobre o tabernáculo; fez onze cortinas.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de uma cortina era de trinta côvados, e a largura de quatro côvados; estas onze cortinas tinham uma mesma medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ E uniu cinco cortinas à parte, e outras seis à parte,

[[v2-36-17]]

^<<v2-36-17,17>>^ E fez cinqüenta laçadas na borda da última cortina, na juntura; também fez cinqüenta laçadas na borda da cortina, na outra juntura.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fez também cinqüenta colchetes de metal, para ajuntar a tenda, para que fosse um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fez também, para a tenda, uma coberta de peles de carneiros, tintas de vermelho; e por cima uma coberta de peles de texugos.

[[v2-36-20]]

^<<v2-36-20,20>>^ Também fez, de madeira de acácia, tábuas levantadas para o tabernáculo, que foram colocadas verticalmente.

[[v2-36-21]]

^<<v2-36-21,21>>^ O comprimento de cada tábua era de dez côvados, e a largura de um côvado e meio.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha duas cavilhas pregadas uma a outra; assim fez com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ Assim, pois, fez as tábuas para o tabernáculo; vinte tábuas para o lado que dá para o sul;

[[v2-36-24]]

^<<v2-36-24,24>>^ E fez quarenta bases de prata debaixo das vinte tábuas; duas bases debaixo de uma tábua, para as suas duas cavilhas, e duas debaixo de outra, para as suas duas cavilhas.

[[v2-36-25]]

^<<v2-36-25,25>>^ Também fez vinte tábuas ao outro lado do tabernáculo, do lado norte,

[[v2-36-26]]

^<<v2-36-26,26>>^ Com as suas quarenta bases de prata; duas bases debaixo de uma tábua, e duas bases debaixo de outra tábua.

[[v2-36-27]]

^<<v2-36-27,27>>^ E ao lado do tabernáculo para o ocidente fez seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ Fez também duas tábuas para os cantos do tabernáculo nos dois lados,

[[v2-36-29]]

^<<v2-36-29,29>>^ As quais por baixo estavam juntas, e também se ajuntavam por cima com uma argola; assim fez com ambas nos dois cantos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Assim eram oito tábuas com as suas bases de prata, a saber, dezesseis bases; duas bases debaixo de cada tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fez também travessas de madeira de acácia; cinco para as tábuas de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ E cinco travessas para as tábuas do outro lado do tabernáculo; e outras cinco travessas para as tábuas do tabernáculo do lado ocidental.

[[v2-36-33]]

^<<v2-36-33,33>>^ E fez que a travessa do meio passasse pelo meio das tábuas de uma extremidade até a outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ E cobriu as tábuas de ouro, e as suas argolas (os lugares das travessas) fez de ouro; as travessas também cobriu de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Depois fez o véu de azul, e de púrpura, e de carmesim, e de linho fino torcido; de obra esmerada o fez com querubins.

[[v2-36-36]]

^<<v2-36-36,36>>^ E fez-lhe quatro colunas de madeira de acácia, e as cobriu de ouro; e seus colchetes fez de ouro, e fundiu-lhe quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fez também para a porta da tenda o véu de azul, e de púrpura, e de carmesim, e de linho fino torcido, da obra do bordador,

[[v2-36-38]]

^<<v2-36-38,38>>^ Com as suas cinco colunas e os seus colchetes; e as suas cabeças e as suas molduras cobriu de ouro; e as suas cinco bases eram de cobre.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]