include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-34-1]]

^<<v2-34-1,1>>^ Então disse o SENHOR a Moisés: Lavra duas tábuas de pedra, como as primeiras; e eu escreverei nas tábuas as mesmas palavras que estavam nas primeiras tábuas, que tu quebraste.

[[v2-34-2]]

^<<v2-34-2,2>>^ E prepara-te para amanhã, para que subas pela manhã ao monte Sinai, e ali põe-te diante de mim no cume do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ E ninguém suba contigo, e também ninguém apareça em todo o monte; nem ovelhas nem bois se apascentem defronte do monte.

[[v2-34-4]]

^<<v2-34-4,4>>^ Então Moisés lavrou duas tábuas de pedra, como as primeiras; e levantando-se pela manhã de madrugada, subiu ao monte Sinai, como o Senhor lhe tinha ordenado; e levou as duas tábuas de pedra nas suas mãos.

[[v2-34-5]]

^<<v2-34-5,5>>^ E o Senhor desceu numa nuvem e se pôs ali junto a ele; e ele proclamou o nome do Senhor.

[[v2-34-6]]

^<<v2-34-6,6>>^ Passando, pois, o Senhor perante ele, clamou: O Senhor, o Senhor Deus, misericordioso e piedoso, tardio em irar-se e grande em beneficência e verdade;

[[v2-34-7]]

^<<v2-34-7,7>>^ Que guarda a beneficência em milhares; que perdoa a iniqüidade, e a transgressão e o pecado; que ao culpado não tem por inocente; que visita a iniqüidade dos pais sobre os filhos e sobre os filhos dos filhos até a terceira e quarta geração.

[[v2-34-8]]

^<<v2-34-8,8>>^ E Moisés apressou-se, e inclinou a cabeça à terra, adorou,

[[v2-34-9]]

^<<v2-34-9,9>>^ E disse: Senhor, se agora tenho achado graça aos teus olhos, vá agora o Senhor no meio de nós; porque este é povo de dura cerviz; porém perdoa a nossa iniqüidade e o nosso pecado, e toma-nos por tua herança.

[[v2-34-10]]

^<<v2-34-10,10>>^ Então disse: Eis que eu faço uma aliança; farei diante de todo o teu povo maravilhas que nunca foram feitas em toda a terra, nem em nação alguma; de maneira que todo este povo, em cujo meio tu estás, veja a obra do Senhor; porque coisa terrível é o que faço contigo.

[[v2-34-11]]

^<<v2-34-11,11>>^ Guarda o que eu te ordeno hoje; eis que eu lançarei fora diante de ti os amorreus, e os cananeus, e os heteus, e os perizeus, e os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Guarda-te de fazeres aliança com os moradores da terra aonde hás de entrar; para que não seja por laço no meio de ti.

[[v2-34-13]]

^<<v2-34-13,13>>^ Mas os seus altares derrubareis, e as suas estátuas quebrareis, e os seus bosques cortareis.

[[v2-34-14]]

^<<v2-34-14,14>>^ Porque não te inclinarás diante de outro deus; pois o nome do Senhor é Zeloso; é um Deus zeloso.

[[v2-34-15]]

^<<v2-34-15,15>>^ Para que não faças aliança com os moradores da terra, e quando eles se prostituírem após os seus deuses, ou sacrificarem aos seus deuses, tu, como convidado deles, comas também dos seus sacrifícios,

[[v2-34-16]]

^<<v2-34-16,16>>^ E tomes mulheres das suas filhas para os teus filhos, e suas filhas, prostituindo-se com os seus deuses, façam que também teus filhos se prostituam com os seus deuses.

[[v2-34-17]]

^<<v2-34-17,17>>^ Não te farás deuses de fundição.

[[v2-34-18]]

^<<v2-34-18,18>>^ A festa dos pães ázimos guardarás; sete dias comerás pães ázimos, como te tenho ordenado, ao tempo apontado do mês de Abibe; porque no mês de Abibe saíste do Egito.

[[v2-34-19]]

^<<v2-34-19,19>>^ Tudo o que abre a madre meu é, até todo o teu gado, que seja macho, e que abre a madre de vacas e de ovelhas;

[[v2-34-20]]

^<<v2-34-20,20>>^ O burro, porém, que abrir a madre, resgatarás com um cordeiro; mas, se o não resgatares, cortar-lhe-ás a cabeça; todo o primogênito de teus filhos resgatarás. E ninguém aparecerá vazio diante de mim.

[[v2-34-21]]

^<<v2-34-21,21>>^ Seis dias trabalharás, mas ao sétimo dia descansarás: na aradura e na sega descansarás.

[[v2-34-22]]

^<<v2-34-22,22>>^ Também guardarás a festa das semanas, que é a festa das primícias da sega do trigo, e a festa da colheita no fim do ano.

[[v2-34-23]]

^<<v2-34-23,23>>^ Três vezes ao ano todos os homens aparecerão perante o Senhor DEUS, o Deus de Israel;

[[v2-34-24]]

^<<v2-34-24,24>>^ Porque eu lançarei fora as nações de diante de ti, e alargarei o teu território; ninguém cobiçará a tua terra, quando subires para aparecer três vezes no ano diante do Senhor teu Deus.

[[v2-34-25]]

^<<v2-34-25,25>>^ Não sacrificarás o sangue do meu sacrifício com pão levedado, nem o sacrifício da festa da páscoa ficará da noite para a manhã.

[[v2-34-26]]

^<<v2-34-26,26>>^ As primícias dos primeiros frutos da tua terra trarás à casa do Senhor teu Deus; não cozerás o cabrito no leite de sua mãe.

[[v2-34-27]]

^<<v2-34-27,27>>^ Disse mais o Senhor a Moisés: Escreve estas palavras; porque conforme ao teor destas palavras tenho feito aliança contigo e com Israel.

[[v2-34-28]]

^<<v2-34-28,28>>^ E esteve ali com o Senhor quarenta dias e quarenta noites; não comeu pão, nem bebeu água, e escreveu nas tábuas as palavras da aliança, os dez mandamentos.

[[v2-34-29]]

^<<v2-34-29,29>>^ E aconteceu que, descendo Moisés do monte Sinai trazia as duas tábuas do testemunho em suas mãos, sim, quando desceu do monte, Moisés não sabia que a pele do seu rosto resplandecia, depois que falara com ele.

[[v2-34-30]]

^<<v2-34-30,30>>^ Olhando, pois, Arão e todos os filhos de Israel para Moisés, eis que a pele do seu rosto resplandecia; por isso temeram chegar-se a ele.

[[v2-34-31]]

^<<v2-34-31,31>>^ Então Moisés os chamou, e Arão e todos os príncipes da congregação tornaram-se a ele; e Moisés lhes falou.

[[v2-34-32]]

^<<v2-34-32,32>>^ Depois chegaram também todos os filhos de Israel; e ele lhes ordenou tudo o que o Senhor falara com ele no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Assim que Moisés acabou de falar com eles, pôs um véu sobre o seu rosto.

[[v2-34-34]]

^<<v2-34-34,34>>^ Porém, entrando Moisés perante o Senhor, para falar com ele, tirava o véu até sair; e, saindo, falava com os filhos de Israel o que lhe era ordenado.

[[v2-34-35]]

^<<v2-34-35,35>>^ Assim, pois, viam os filhos de Israel o rosto de Moisés, e que resplandecia a pele do seu rosto; e tornava Moisés a pôr o véu sobre o seu rosto, até entrar para falar com ele.

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]