include::./index.adoc[]

[[v2-2-0]]
=== Êxodo, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v2-2-1]]

^<<v2-2-1,1>>^ E foi um homem da casa de Levi e casou com uma filha de Levi.

[[v2-2-2]]

^<<v2-2-2,2>>^ E a mulher concebeu e deu à luz um filho; e, vendo que ele era formoso, escondeu-o três meses.

[[v2-2-3]]

^<<v2-2-3,3>>^ Não podendo, porém, mais escondê-lo, tomou uma arca de juncos, e a revestiu com barro e betume; e, pondo nela o menino, a pôs nos juncos à margem do rio.

[[v2-2-4]]

^<<v2-2-4,4>>^ E sua irmã postou-se de longe, para saber o que lhe havia de acontecer.

[[v2-2-5]]

^<<v2-2-5,5>>^ E a filha de Faraó desceu a lavar-se no rio, e as suas donzelas passeavam, pela margem do rio; e ela viu a arca no meio dos juncos, e enviou a sua criada, que a tomou.

[[v2-2-6]]

^<<v2-2-6,6>>^ E abrindo-a, viu ao menino e eis que o menino chorava; e moveu-se de compaixão dele, e disse: Dos meninos dos hebreus é este.

[[v2-2-7]]

^<<v2-2-7,7>>^ Então disse sua irmã à filha de Faraó: Irei chamar uma ama das hebréias, que crie este menino para ti?

[[v2-2-8]]

^<<v2-2-8,8>>^ E a filha de Faraó disse-lhe: Vai. Foi, pois, a moça, e chamou a mãe do menino.

[[v2-2-9]]

^<<v2-2-9,9>>^ Então lhe disse a filha de Faraó: Leva este menino, e cria-mo; eu te darei teu salário. E a mulher tomou o menino, e criou-o.

[[v2-2-10]]

^<<v2-2-10,10>>^ E, quando o menino já era grande, ela o trouxe à filha de Faraó, a qual o adotou; e chamou-lhe Moisés, e disse: Porque das águas o tenho tirado.

[[v2-2-11]]

^<<v2-2-11,11>>^ E aconteceu naqueles dias que, sendo Moisés já homem, saiu a seus irmãos, e atentou para as suas cargas; e viu que um egípcio feria a um hebreu, homem de seus irmãos.

[[v2-2-12]]

^<<v2-2-12,12>>^ E olhou a um e a outro lado e, vendo que não havia ninguém ali, matou ao egípcio, e escondeu-o na areia.

[[v2-2-13]]

^<<v2-2-13,13>>^ E tornou a sair no dia seguinte, e eis que dois homens hebreus contendiam; e disse ao injusto: Por que feres a teu próximo?

[[v2-2-14]]

^<<v2-2-14,14>>^ O qual disse: Quem te tem posto a ti por maioral e juiz sobre nós? Pensas matar-me, como mataste o egípcio? Então temeu Moisés, e disse: Certamente este negócio foi descoberto.

[[v2-2-15]]

^<<v2-2-15,15>>^ Ouvindo, pois, Faraó este caso, procurou matar a Moisés; mas Moisés fugiu de diante da face de Faraó, e habitou na terra de Midiã, e assentou-se junto a um poço.

[[v2-2-16]]

^<<v2-2-16,16>>^ E o sacerdote de Midiã tinha sete filhas, as quais vieram tirar água, e encheram os bebedouros, para dar de beber ao rebanho de seu pai.

[[v2-2-17]]

^<<v2-2-17,17>>^ Então vieram os pastores, e expulsaram-nas dali; Moisés, porém, levantou-se e defendeu-as, e deu de beber ao rebanho.

[[v2-2-18]]

^<<v2-2-18,18>>^ E voltando elas a Reuel seu pai, ele disse: Por que hoje tornastes tão depressa?

[[v2-2-19]]

^<<v2-2-19,19>>^ E elas disseram: Um homem egípcio nos livrou da mão dos pastores; e também nos tirou água em abundância, e deu de beber ao rebanho.

[[v2-2-20]]

^<<v2-2-20,20>>^ E disse a suas filhas: E onde está ele? Por que deixastes o homem? Chamai-o para que coma pão.

[[v2-2-21]]

^<<v2-2-21,21>>^ E Moisés consentiu em morar com aquele homem; e ele deu a Moisés sua filha Zípora,

[[v2-2-22]]

^<<v2-2-22,22>>^ A qual deu à luz um filho, a quem ele chamou Gérson, porque disse: Peregrino fui em terra estranha.

[[v2-2-23]]

^<<v2-2-23,23>>^ E aconteceu, depois de muitos dias, que morrendo o rei do Egito, os filhos de Israel suspiraram por causa da servidão, e clamaram; e o seu clamor subiu a Deus por causa de sua servidão.

[[v2-2-24]]

^<<v2-2-24,24>>^ E ouviu Deus o seu gemido, e lembrou-se Deus da sua aliança com Abraão, com Isaque, e com Jacó;

[[v2-2-25]]

^<<v2-2-25,25>>^ E viu Deus os filhos de Israel, e atentou Deus para a sua condição.

'''

xref:002-exodo/002-exodo-001.adoc#v2-1-0[&#60; Capítulo Anterior] | <<v2-2-0,Topo>> | xref:002-exodo/002-exodo-003.adoc#v2-3-0[Próximo Capítulo &#62;]