include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-18-1]]

^<<v7-18-1,1>>^ Naqueles dias não havia rei em Israel; e nos mesmos dias a tribo dos danitas buscava para si herança para habitar; porquanto até àquele dia entre as tribos de Israel não lhe havia caído por sorte sua herança.

[[v7-18-2]]

^<<v7-18-2,2>>^ E enviaram os filhos de Dã, da sua tribo, cinco homens dentre eles, homens valorosos, de Zorá e de Estaol, a espiar e reconhecer a terra, e lhes disseram: Ide, reconhecei a terra. E chegaram à montanha de Efraim, até à casa de Mica, e passaram ali a noite.

[[v7-18-3]]

^<<v7-18-3,3>>^ E quando eles estavam junto da casa de Mica, reconheceram a voz do moço, do levita; e dirigindo-se para lá, lhe disseram: Quem te trouxe aqui? Que fazes aqui? E que é que tens aqui?

[[v7-18-4]]

^<<v7-18-4,4>>^ E ele lhes disse: Assim e assim me tem feito Mica; pois me tem contratado, e eu lhe sirvo de sacerdote.

[[v7-18-5]]

^<<v7-18-5,5>>^ Então lhe disseram: Consulta a Deus, para que possamos saber se prosperará o caminho que seguimos.

[[v7-18-6]]

^<<v7-18-6,6>>^ E disse-lhes o sacerdote: Ide em paz; o caminho que seguis está perante o Senhor.

[[v7-18-7]]

^<<v7-18-7,7>>^ Então foram-se aqueles cinco homens, e chegaram a Laís; e viram que o povo que havia no meio dela estava seguro, conforme ao costume dos sidônios, quieto e confiado; nem havia autoridade alguma do reino que por qualquer coisa envergonhasse a alguém naquela terra; também estavam longe dos sidônios, e não tinham relação com ninguém.

[[v7-18-8]]

^<<v7-18-8,8>>^ Então voltaram a seus irmãos, a Zorá e a Estaol, os quais lhes disseram: Que dizeis vós?

[[v7-18-9]]

^<<v7-18-9,9>>^ E eles disseram: Levantai-vos, e subamos contra eles; porque examinamos a terra, e eis que é muitíssimo boa. E vós estareis aqui tranqüilos? Não sejais preguiçosos em irdes para entrar a possuir esta terra.

[[v7-18-10]]

^<<v7-18-10,10>>^ Quando lá chegardes, vereis um povo confiado, e a terra é larga de extensão; porque Deus vo-la entregou nas mãos; lugar em que não há falta de coisa alguma que há na terra.

[[v7-18-11]]

^<<v7-18-11,11>>^ Então partiram dali, da tribo dos danitas, de Zorá e de Estaol, seiscentos homens munidos de armas de guerra.

[[v7-18-12]]

^<<v7-18-12,12>>^ E subiram, e acamparam-se em Quiriate-Jearim, em Judá; então chamaram a este lugar Maané-Dã, até ao dia de hoje; eis que está por detrás de Quiriate-Jearim.

[[v7-18-13]]

^<<v7-18-13,13>>^ E dali passaram à montanha de Efraim; e chegaram até a casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Então responderam os cinco homens, que foram espiar a terra de Laís, e disseram a seus irmãos: Sabeis vós também que naquelas casas há um éfode, e terafins, e uma imagem de escultura e uma de fundição? Vede, pois, agora o que haveis de fazer.

[[v7-18-15]]

^<<v7-18-15,15>>^ Então se dirigiram para lá, e chegaram à casa do moço, o levita, em casa de Mica, e o saudaram.

[[v7-18-16]]

^<<v7-18-16,16>>^ E os seiscentos homens, que eram dos filhos de Dã, munidos com suas armas de guerra, ficaram à entrada da porta.

[[v7-18-17]]

^<<v7-18-17,17>>^ Porém subindo os cinco homens, que foram espiar a terra, entraram ali, e tomaram a imagem de escultura, o éfode, e os terafins, e a imagem de fundição, ficando o sacerdote em pé à entrada da porta, com os seiscentos homens que estavam munidos com as armas de guerra.

[[v7-18-18]]

^<<v7-18-18,18>>^ Entrando eles, pois, em casa de Mica, e tomando a imagem de escultura, e o éfode, e os terafins, e a imagem de fundição, disse-lhes o sacerdote: Que estais fazendo?

[[v7-18-19]]

^<<v7-18-19,19>>^ E eles lhe disseram: Cala-te, põe a mão na boca, e vem conosco, e sê-nos por pai e sacerdote. É melhor ser sacerdote da casa de um só homem, do que ser sacerdote de uma tribo e de uma família em Israel?

[[v7-18-20]]

^<<v7-18-20,20>>^ Então alegrou-se o coração do sacerdote, e tomou o éfode, e os terafins, e a imagem de escultura; e entrou no meio do povo.

[[v7-18-21]]

^<<v7-18-21,21>>^ Assim viraram, e partiram; e os meninos, e o gado, e a bagagem puseram diante de si.

[[v7-18-22]]

^<<v7-18-22,22>>^ E, estando já longe da casa de Mica, os homens que estavam nas casas junto à casa de Mica, reuniram-se, e alcançaram os filhos de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ E clamaram após os filhos de Dã, os quais viraram os seus rostos, e disseram a Mica: Que tens, que tanta gente convocaste?

[[v7-18-24]]

^<<v7-18-24,24>>^ Então ele disse: Os meus deuses, que eu fiz, me tomastes, juntamente com o sacerdote, e partistes; que mais me resta agora? Como, pois, me dizeis: Que é que tens?

[[v7-18-25]]

^<<v7-18-25,25>>^ Porém os filhos de Dã lhe disseram: Não nos faças ouvir a tua voz, para que porventura homens de ânimo mau não se lancem sobre vós, e tu percas a tua vida, e a vida dos da tua casa.

[[v7-18-26]]

^<<v7-18-26,26>>^ Assim seguiram o seu caminho os filhos de Dã; e Mica, vendo que eram mais fortes do que ele, virou-se, e voltou à sua casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Eles, pois, tomaram o que Mica tinha feito, e o sacerdote que tivera, e chegaram a Laís, a um povo quieto e confiado, e os feriram ao fio da espada, e queimaram a cidade a fogo.

[[v7-18-28]]

^<<v7-18-28,28>>^ E ninguém houve que os livrasse, porquanto estavam longe de Sidom, e não tinham relações com ninguém, e a cidade estava no vale que está junto de Bete-Reobe; depois reedificaram a cidade e habitaram nela.

[[v7-18-29]]

^<<v7-18-29,29>>^ E chamaram-lhe Dã, conforme ao nome de Dã, seu pai, que nascera a Israel; era, porém, antes o nome desta cidade Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ E os filhos de Dã levantaram para si aquela imagem de escultura; e Jônatas, filho de Gérson, o filho de Manassés, ele e seus filhos foram sacerdotes da tribo dos danitas, até ao dia do cativeiro da terra.

[[v7-18-31]]

^<<v7-18-31,31>>^ Assim, pois, estabeleceram para si a imagem de escultura, que fizera Mica, por todos os dias em que a casa de Deus esteve em Siló.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]