include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-4-1]]

^<<v7-4-1,1>>^ Porém os filhos de Israel tornaram a fazer o que era mau aos olhos do SENHOR, depois de falecer Eúde.

[[v7-4-2]]

^<<v7-4-2,2>>^ E vendeu-os o Senhor na mão de Jabim, rei de Canaã, que reinava em Hazor; e Sísera era o capitão do seu exército, o qual então habitava em Harosete dos gentios.

[[v7-4-3]]

^<<v7-4-3,3>>^ Então os filhos de Israel clamaram ao Senhor, porquanto ele tinha novecentos carros de ferro, e por vinte anos oprimia violentamente os filhos de Israel.

[[v7-4-4]]

^<<v7-4-4,4>>^ E Débora, mulher profetisa, mulher de Lapidote, julgava a Israel naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela assentava-se debaixo das palmeiras de Débora, entre Ramá e Betel, nas montanhas de Efraim; e os filhos de Israel subiam a ela a juízo.

[[v7-4-6]]

^<<v7-4-6,6>>^ E mandou chamar a Baraque, filho de Abinoão de Quedes de Naftali, e disse-lhe: Porventura o Senhor Deus de Israel não deu ordem, dizendo: Vai, e atrai gente ao monte Tabor, e toma contigo dez mil homens dos filhos de Naftali e dos filhos de Zebulom;

[[v7-4-7]]

^<<v7-4-7,7>>^ E atrairei a ti para o ribeiro de Quisom, a Sísera, capitão do exército de Jabim, com os seus carros, e com a sua multidão; e o darei na tua mão.

[[v7-4-8]]

^<<v7-4-8,8>>^ Então lhe disse Baraque: Se fores comigo, irei; porém, se não fores comigo, não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ E disse ela: Certamente irei contigo, porém não será tua a honra da jornada que empreenderes; pois à mão de uma mulher o Senhor venderá a Sísera. E Débora se levantou, e partiu com Baraque para Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Então Baraque convocou a Zebulom e a Naftali em Quedes, e subiu com dez mil homens após ele; e Débora subiu com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ E Héber, queneu, se tinha apartado dos queneus, dos filhos de Hobabe, sogro de Moisés; e tinha estendido as suas tendas até ao carvalho de Zaanaim, que está junto a Quedes,

[[v7-4-12]]

^<<v7-4-12,12>>^ E anunciaram a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ E Sísera convocou todos os seus carros, novecentos carros de ferro, e todo o povo que estava com ele, desde Harosete dos gentios até ao ribeiro de Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então disse Débora a Baraque: Levanta-te, porque este é o dia em que o Senhor tem dado a Sísera na tua mão; porventura o Senhor não saiu adiante de ti? Baraque, pois, desceu do monte Tabor, e dez mil homens após ele.

[[v7-4-15]]

^<<v7-4-15,15>>^ E o Senhor derrotou a Sísera, e a todos os seus carros, e a todo o seu exército ao fio da espada, diante de Baraque; e Sísera desceu do carro, e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ E Baraque perseguiu os carros, e o exército, até Harosete dos gentios; e todo o exército de Sísera caiu ao fio da espada, até não ficar um só.

[[v7-4-17]]

^<<v7-4-17,17>>^ Porém Sísera fugiu a pé à tenda de Jael, mulher de Héber, queneu; porquanto havia paz entre Jabim, rei de Hazor, e a casa de Héber, queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ E Jael saiu ao encontro de Sísera, e disse-lhe: Entra, senhor meu, entra aqui, não temas. Ele entrou na sua tenda, e ela o cobriu com uma coberta.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então ele lhe disse: Dá-me, peço-te, de beber um pouco de água, porque tenho sede. Então ela abriu um odre de leite, e deu-lhe de beber, e o cobriu.

[[v7-4-20]]

^<<v7-4-20,20>>^ E ele lhe disse: Põe-te à porta da tenda; e há de ser que se alguém vier e te perguntar: Há aqui alguém? Responderás então: Não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Então Jael, mulher de Héber, tomou uma estaca da tenda, e lançou mão de um martelo, e chegou-se mansamente a ele, e lhe cravou a estaca na fonte, de sorte que penetrou na terra, estando ele, porém, num profundo sono, e já muito cansado; e assim morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ E eis que, seguindo Baraque a Sísera, Jael lhe saiu ao encontro, e disse-lhe: Vem, e mostrar-te-ei o homem que buscas. E foi a ela, e eis que Sísera jazia morto, com a estaca na fonte.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim Deus naquele dia sujeitou a Jabim, rei de Canaã, diante dos filhos de Israel.

[[v7-4-24]]

^<<v7-4-24,24>>^ E continuou a mão dos filhos de Israel a pesar e a endurecer-se sobre Jabim, rei de Canaã; até que exterminaram a Jabim, rei de Canaã.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]