include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-1-1]]

^<<v7-1-1,1>>^ E sucedeu, depois da morte de Josué, que os filhos de Israel perguntaram ao SENHOR, dizendo: Quem dentre nós primeiro subirá aos cananeus, para pelejar contra eles?

[[v7-1-2]]

^<<v7-1-2,2>>^ E disse o Senhor: Judá subirá; eis que entreguei esta terra na sua mão.

[[v7-1-3]]

^<<v7-1-3,3>>^ Então disse Judá a Simeão, seu irmão: Sobe comigo à minha herança. E pelejemos contra os cananeus, e também eu contigo subirei à tua herança. E Simeão partiu com ele.

[[v7-1-4]]

^<<v7-1-4,4>>^ E subiu Judá, e o Senhor lhe entregou na sua mão os cananeus e os perizeus; e feriram deles, em Bezeque, a dez mil homens.

[[v7-1-5]]

^<<v7-1-5,5>>^ E acharam Adoni-Bezeque em Bezeque, e pelejaram contra ele; e feriram aos cananeus e aos perizeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Porém Adoni-Bezeque fugiu, mas o seguiram, e prenderam-no e cortaram-lhe os dedos polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então disse Adoni-Bezeque: Setenta reis, com os dedos polegares das mãos e dos pés cortados, apanhavam as migalhas debaixo da minha mesa; assim como eu fiz, assim Deus me pagou. E levaram-no a Jerusalém, e morreu ali.

[[v7-1-8]]

^<<v7-1-8,8>>^ E os filhos de Judá pelejaram contra Jerusalém, e tomando-a, feriram-na ao fio da espada; e puseram fogo na cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ E depois os filhos de Judá desceram a pelejar contra os cananeus, que habitavam nas montanhas, e no sul, e nas planícies.

[[v7-1-10]]

^<<v7-1-10,10>>^ E partiu Judá contra os cananeus que habitavam em Hebrom (era porém outrora o nome de Hebrom, Quiriate-Arba), e feriram a Sesai, e a Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ E dali partiu contra os moradores de Debir; e era outrora o nome de Debir, Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ E disse Calebe: Quem ferir a Quiriate-Sefer, e a tomar, lhe darei a minha filha Acsa por mulher.

[[v7-1-13]]

^<<v7-1-13,13>>^ E tomou-a Otniel, filho de Quenaz, o irmão de Calebe, mais novo do que ele; e Calebe lhe deu a sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ E sucedeu que, indo ela a ele, o persuadiu que pedisse um campo a seu pai; e ela desceu do jumento, e Calebe lhe disse: Que é que tens?

[[v7-1-15]]

^<<v7-1-15,15>>^ E ela lhe disse: Dá-me uma bênção; pois me deste uma terra seca, dá-me também fontes de águas. E Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Também os filhos do queneu, sogro de Moisés, subiram da cidade das palmeiras com os filhos de Judá ao deserto de Judá, que está ao sul de Arade, e foram, e habitaram com o povo.

[[v7-1-17]]

^<<v7-1-17,17>>^ E foi Judá com Simeão, seu irmão, e feriram aos cananeus que habitavam em Zefate; e totalmente a destruíram, e chamou-se o nome desta cidade Hormá.

[[v7-1-18]]

^<<v7-1-18,18>>^ Tomou mais Judá a Gaza com o seu termo, e a Ascalom com o seu termo, e a Ecrom com o seu termo.

[[v7-1-19]]

^<<v7-1-19,19>>^ E estava o Senhor com Judá, e despovoou as montanhas; porém não expulsou aos moradores do vale, porquanto tinham carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ E deram Hebrom a Calebe, como Moisés o dissera; e dali expulsou os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Porém os filhos de Benjamim não expulsaram os jebuseus que habitavam em Jerusalém; antes os jebuseus ficaram habitando com os filhos de Benjamim em Jerusalém, até ao dia de hoje,

[[v7-1-22]]

^<<v7-1-22,22>>^ E subiu também a casa de José contra Betel, e foi o Senhor com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ E a casa de José mandou espias a Betel, e foi antes o nome desta cidade Luz.

[[v7-1-24]]

^<<v7-1-24,24>>^ E viram os espias a um homem, que saía da cidade, e lhe disseram: Ora, mostra-nos a entrada da cidade, e usaremos contigo de misericórdia.

[[v7-1-25]]

^<<v7-1-25,25>>^ E, mostrando-lhes ele a entrada da cidade, feriram-na ao fio da espada; porém àquele homem e a toda a sua família deixaram ir.

[[v7-1-26]]

^<<v7-1-26,26>>^ Então aquele homem se foi à terra dos heteus, e edificou uma cidade, e chamou o seu nome Luz; este é o seu nome até ao dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés não expulsou os habitantes de Bete-Seã, nem mesmo dos lugares da sua jurisdição; nem a Taanaque, com os lugares da sua jurisdição; nem os moradores de Dor, com os lugares da sua jurisdição; nem os moradores de Ibleão, com os lugares da sua jurisdição; nem os moradores de Megido, com os lugares da sua jurisdição; e resolveram os cananeus habitar na mesma terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ E sucedeu que, quando Israel cobrou mais forças, fez dos cananeus tributários; porém não os expulsou de todo.

[[v7-1-29]]

^<<v7-1-29,29>>^ Tampouco expulsou Efraim os cananeus que habitavam em Gezer; antes os cananeus ficaram habitando com ele, em Gezer.

[[v7-1-30]]

^<<v7-1-30,30>>^ Tampouco expulsou Zebulom os moradores de Quitrom, nem os moradores de Naalol; porém os cananeus ficaram habitando com ele, e foram tributários.

[[v7-1-31]]

^<<v7-1-31,31>>^ Tampouco Aser expulsou os moradores de Aco, nem os moradores de Sidom; como nem de Alabe, nem de Aczibe, nem de Helba, nem de Afeque, nem de Reobe;

[[v7-1-32]]

^<<v7-1-32,32>>^ Porém os aseritas habitaram no meio dos cananeus que habitavam na terra; porquanto não os expulsaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ Tampouco Naftali expulsou os moradores de Bete-Semes, nem os moradores de Bete-Anate; mas habitou no meio dos cananeus que habitavam na terra; porém lhes foram tributários os moradores de Bete-Semes e Bete-Anate.

[[v7-1-34]]

^<<v7-1-34,34>>^ E os amorreus impeliram os filhos de Dã até às montanhas; porque nem os deixavam descer ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ Também os amorreus quiseram habitar nas montanhas de Heres, em Aijalom e em Saalbim; porém prevaleceu a mão da casa de José, e ficaram tributários.

[[v7-1-36]]

^<<v7-1-36,36>>^ E foi o termo dos amorreus desde a subida de Acrabim, desde a penha, e dali para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]