include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-17-1]]

^<<v7-17-1,1>>^ E havia um homem da montanha de Efraim, cujo nome era Mica.

[[v7-17-2]]

^<<v7-17-2,2>>^ O qual disse à sua mãe: As mil e cem moedas de prata que te foram tiradas, por cuja causa lançaste maldições, e de que também me falaste, eis que esse dinheiro está comigo; eu o tomei. Então lhe disse sua mãe: Bendito do Senhor seja meu filho.

[[v7-17-3]]

^<<v7-17-3,3>>^ Assim restituiu as mil e cem moedas de prata à sua mãe; porém sua mãe disse: Inteiramente tenho dedicado este dinheiro da minha mão ao Senhor, para meu filho fazer uma imagem de escultura e uma de fundição; de sorte que agora to tornarei a dar.

[[v7-17-4]]

^<<v7-17-4,4>>^ Porém ele restituiu aquele dinheiro à sua mãe; e sua mãe tomou duzentas moedas de prata, e as deu ao ourives, o qual fez delas uma imagem de escultura e uma de fundição, que ficaram em casa de Mica.

[[v7-17-5]]

^<<v7-17-5,5>>^ E teve este homem, Mica, uma casa de deuses; e fez um éfode e terafins, e consagrou um de seus filhos, para que lhe fosse por sacerdote.

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias não havia rei em Israel; cada um fazia o que parecia bem aos seus olhos.

[[v7-17-7]]

^<<v7-17-7,7>>^ E havia um moço de Belém de Judá, da tribo de Judá, que era levita, e peregrinava ali.

[[v7-17-8]]

^<<v7-17-8,8>>^ E este homem partiu da cidade de Belém de Judá para peregrinar onde quer que achasse conveniente. Chegando ele, pois, à montanha de Efraim, até à casa de Mica, seguindo o seu caminho,

[[v7-17-9]]

^<<v7-17-9,9>>^ Disse-lhe Mica: Donde vens? E ele lhe disse: Sou levita de Belém de Judá, e vou peregrinar onde quer que achar conveniente.

[[v7-17-10]]

^<<v7-17-10,10>>^ Então lhe disse Mica: Fica comigo, e sê-me por pai e sacerdote; e cada ano te darei dez moedas de prata, e vestuário, e o sustento. E o levita entrou.

[[v7-17-11]]

^<<v7-17-11,11>>^ E consentiu o levita em ficar com aquele homem; e o moço lhe foi como um de seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ E Mica consagrou o levita, e aquele moço lhe foi por sacerdote; e esteve em casa de Mica.

[[v7-17-13]]

^<<v7-17-13,13>>^ Então disse Mica: Agora sei que o SENHOR me fará bem; porquanto tenho um levita por sacerdote.

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]