include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-9-1]]

^<<v7-9-1,1>>^ E Abimeleque, filho de Jerubaal, foi a Siquém, aos irmãos de sua mãe, e falou-lhes e a toda a geração da casa do pai de sua mãe, dizendo:

[[v7-9-2]]

^<<v7-9-2,2>>^ Falai, peço-vos, aos ouvidos de todos os cidadãos de Siquém: Qual é melhor para vós, que setenta homens, todos os filhos de Jerubaal, dominem sobre vós, ou que um homem sobre vós domine? Lembrai-vos também de que sou osso vosso e carne vossa.

[[v7-9-3]]

^<<v7-9-3,3>>^ Então os irmãos de sua mãe falaram acerca dele perante os ouvidos de todos os cidadãos de Siquém todas aquelas palavras; e o coração deles se inclinou a seguir Abimeleque, porque disseram: É nosso irmão.

[[v7-9-4]]

^<<v7-9-4,4>>^ E deram-lhe setenta peças de prata, da casa de Baal-Berite; e com elas alugou Abimeleque uns homens ociosos e levianos, que o seguiram.

[[v7-9-5]]

^<<v7-9-5,5>>^ E veio à casa de seu pai, a Ofra, e matou a seus irmãos, os filhos de Jerubaal, setenta homens, sobre uma pedra. Porém Jotão, filho menor de Jerubaal, ficou, porque se tinha escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então se ajuntaram todos os cidadãos de Siquém, e toda a casa de Milo; e foram, e constituíram a Abimeleque rei, junto ao carvalho alto que está perto de Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ E, dizendo-o a Jotão, foi e pôs-se no cume do monte de Gerizim, e levantou a sua voz, e clamou e disse-lhes: Ouvi-me, cidadãos de Siquém, e Deus vos ouvirá a vós;

[[v7-9-8]]

^<<v7-9-8,8>>^ Foram uma vez as árvores a ungir para si um rei, e disseram à oliveira: Reina tu sobre nós.

[[v7-9-9]]

^<<v7-9-9,9>>^ Porém a oliveira lhes disse: Deixaria eu a minha gordura, que Deus e os homens em mim prezam, e iria pairar sobre as árvores?

[[v7-9-10]]

^<<v7-9-10,10>>^ Então disseram as árvores à figueira: Vem tu, e reina sobre nós.

[[v7-9-11]]

^<<v7-9-11,11>>^ Porém a figueira lhes disse: Deixaria eu a minha doçura, o meu bom fruto, e iria pairar sobre as árvores?

[[v7-9-12]]

^<<v7-9-12,12>>^ Então disseram as árvores à videira: Vem tu, e reina sobre nós.

[[v7-9-13]]

^<<v7-9-13,13>>^ Porém a videira lhes disse: Deixaria eu o meu mosto, que alegra a Deus e aos homens, e iria pairar sobre as árvores?

[[v7-9-14]]

^<<v7-9-14,14>>^ Então todas as árvores disseram ao espinheiro: Vem tu, e reina sobre nós.

[[v7-9-15]]

^<<v7-9-15,15>>^ E disse o espinheiro às árvores: Se, na verdade, me ungis por rei sobre vós, vinde, e confiai-vos debaixo da minha sombra; mas, se não, saia fogo do espinheiro que consuma os cedros do Líbano.

[[v7-9-16]]

^<<v7-9-16,16>>^ Agora, pois, se é que em verdade e sinceridade agistes, fazendo rei a Abimeleque, e se bem fizestes para com Jerubaal e para com a sua casa, e se com ele usastes conforme ao merecimento das suas mãos

[[v7-9-17]]

^<<v7-9-17,17>>^ (Porque meu pai pelejou por vós, e desprezou a sua vida, e vos livrou da mão dos midianitas;

[[v7-9-18]]

^<<v7-9-18,18>>^ Porém vós hoje vos levantastes contra a casa de meu pai, e matastes a seus filhos, setenta homens, sobre uma pedra; e a Abimeleque, filho da sua serva, fizestes reinar sobre os cidadãos de Siquém, porque é vosso irmão);

[[v7-9-19]]

^<<v7-9-19,19>>^ Pois, se em verdade e sinceridade usastes com Jerubaal e com a sua casa hoje, alegrai-vos com Abimeleque, e também ele se alegre convosco.

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se não, saia fogo de Abimeleque, e consuma aos cidadãos de Siquém, e a casa de Milo; e saia fogo dos cidadãos de Siquém, e da casa de Milo, que consuma a Abimeleque.

[[v7-9-21]]

^<<v7-9-21,21>>^ Então partiu Jotão, e fugiu e foi para Beer; e ali habitou por medo de Abimeleque, seu irmão.

[[v7-9-22]]

^<<v7-9-22,22>>^ Havendo, pois, Abimeleque dominado três anos sobre Israel,

[[v7-9-23]]

^<<v7-9-23,23>>^ Enviou Deus um mau espírito entre Abimeleque e os cidadãos de Siquém; e estes se houveram aleivosamente contra Abimeleque;

[[v7-9-24]]

^<<v7-9-24,24>>^ Para que a violência feita aos setenta filhos de Jerubaal viesse, e o seu sangue caísse sobre Abimeleque, seu irmão, que os matara, e sobre os cidadãos de Siquém, que fortaleceram as mãos dele para matar a seus irmãos;

[[v7-9-25]]

^<<v7-9-25,25>>^ E os cidadãos de Siquém puseram contra ele quem lhe armasse emboscadas sobre os cumes dos montes; e a todo aquele que passava pelo caminho junto a eles o assaltavam; e contou-se isso a Abimeleque.

[[v7-9-26]]

^<<v7-9-26,26>>^ Veio também Gaal, filho de Ebede, com seus irmãos, e passaram a Siquém; e os cidadãos de Siquém confiaram nele.

[[v7-9-27]]

^<<v7-9-27,27>>^ E saíram ao campo, e vindimaram as suas vinhas, e pisaram as uvas, e fizeram festas; e foram à casa de seu deus, e comeram, e beberam, e amaldiçoaram a Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ E disse Gaal, filho de Ebede: Quem é Abimeleque, e quem é Siquém, para que o sirvamos? Não é porventura filho de Jerubaal? E não é Zebul o seu mordomo? Servi antes aos homens de Hamor, pai de Siquém; pois, por que razão serviríamos nós a ele?

[[v7-9-29]]

^<<v7-9-29,29>>^ Ah! se este povo estivera na minha mão, eu expulsaria a Abimeleque. E diria a Abimeleque: Multiplica o teu exército, e sai.

[[v7-9-30]]

^<<v7-9-30,30>>^ E, ouvindo Zebul, o maioral da cidade, as palavras de Gaal, filho de Ebede, se acendeu a sua ira;

[[v7-9-31]]

^<<v7-9-31,31>>^ E enviou astutamente mensageiros a Abimeleque, dizendo: Eis que Gaal, filho de Ebede, e seus irmãos vieram a Siquém, e eis que eles estão sublevando esta cidade contra ti.

[[v7-9-32]]

^<<v7-9-32,32>>^ Levanta-te, pois, de noite, tu e o povo que tiveres contigo, e põe emboscadas no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ E levanta-te pela manhã ao sair o sol, e dá de golpe sobre a cidade; e eis que, saindo contra ti, ele e o povo que tiver com ele, faze-lhe como puderes.

[[v7-9-34]]

^<<v7-9-34,34>>^ Levantou-se, pois, Abimeleque, e todo o povo que com ele havia, de noite, e puseram emboscadas a Siquém, com quatro tropas.

[[v7-9-35]]

^<<v7-9-35,35>>^ E Gaal, filho de Ebede, saiu, e pôs-se à entrada da porta da cidade; e Abimeleque, e todo o povo que com ele havia, se levantou das emboscadas.

[[v7-9-36]]

^<<v7-9-36,36>>^ E, vendo Gaal aquele povo, disse a Zebul: Eis que desce gente dos cumes dos montes. Zebul, ao contrário, lhe disse: As sombras dos montes vês como se fossem homens.

[[v7-9-37]]

^<<v7-9-37,37>>^ Porém Gaal ainda tornou a falar, e disse: Eis ali desce gente do meio da terra, e uma tropa vem do caminho do carvalho de Meonenim.

[[v7-9-38]]

^<<v7-9-38,38>>^ Então lhe disse Zebul: Onde está agora a tua boca, com a qual dizias: Quem é Abimeleque, para que o sirvamos? Não é este porventura o povo que desprezaste? Sai pois, peço-te, e peleja contra ele.

[[v7-9-39]]

^<<v7-9-39,39>>^ E saiu Gaal à vista dos cidadãos de Siquém, e pelejou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ E Abimeleque o perseguiu porquanto fugiu de diante dele; e muitos feridos caíram até à entrada da porta da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ E Abimeleque ficou em Aruma. E Zebul expulsou a Gaal e a seus irmãos, para que não pudessem habitar em Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ E sucedeu no dia seguinte que o povo saiu ao campo; disto foi avisado Abimeleque.

[[v7-9-43]]

^<<v7-9-43,43>>^ Então tomou o povo, e o repartiu em três tropas, e pôs emboscadas no campo; e olhou, e eis que o povo saía da cidade, e levantou-se contra ele, e o feriu.

[[v7-9-44]]

^<<v7-9-44,44>>^ Porque Abimeleque, e as tropas que com ele havia, romperam de improviso, e pararam à entrada da porta da cidade; e as outras duas tropas deram de improviso sobre todos quantos estavam no campo, e os feriram.

[[v7-9-45]]

^<<v7-9-45,45>>^ E Abimeleque pelejou contra a cidade todo aquele dia, e tomou a cidade, e matou o povo que nela havia; e assolou a cidade, e a semeou de sal.

[[v7-9-46]]

^<<v7-9-46,46>>^ O que ouvindo todos os cidadãos da torre de Siquém, entraram na fortaleza, na casa do deus Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ E contou-se a Abimeleque que todos os cidadãos da torre de Siquém se haviam congregado.

[[v7-9-48]]

^<<v7-9-48,48>>^ Subiu, pois, Abimeleque ao monte Salmom, ele e todo o povo que com ele havia; e Abimeleque tomou na sua mão um machado, e cortou um ramo de árvore, e o levantou, e pô-lo ao seu ombro, e disse ao povo, que com ele havia: O que me vistes fazer apressai-vos a fazê-lo assim como eu.

[[v7-9-49]]

^<<v7-9-49,49>>^ Assim, pois, cada um de todo o povo, também cortou o seu ramo e seguiu a Abimeleque; e pondo os ramos junto da fortaleza, queimaram-na a fogo com os que nela estavam, de modo que todos os da torre de Siquém morreram, uns mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Então Abimeleque foi a Tebes e a sitiou, e a tomou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia, porém, no meio da cidade uma torre forte; e todos os homens e mulheres, e todos os cidadãos da cidade se refugiaram nela, e fecharam após si as portas, e subiram ao eirado da torre.

[[v7-9-52]]

^<<v7-9-52,52>>^ E Abimeleque veio até à torre, e a combateu; e chegou-se até à porta da torre, para a incendiar.

[[v7-9-53]]

^<<v7-9-53,53>>^ Porém uma mulher lançou um pedaço de uma mó sobre a cabeça de Abimeleque; e quebrou-lhe o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Então chamou logo ao moço, que levava as suas armas, e disse-lhe: Desembainha a tua espada, e mata-me; para que não se diga de mim: Uma mulher o matou. E o moço o atravessou e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Vendo, pois, os homens de Israel que Abimeleque já era morto, foram-se cada um para o seu lugar.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim Deus fez tornar sobre Abimeleque o mal que tinha feito a seu pai, matando a seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ Como também todo o mal dos homens de Siquém fez tornar sobre a cabeça deles; e a maldição de Jotão, filho de Jerubaal, veio sobre eles.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]