include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-21-1]]

^<<v7-21-1,1>>^ Ora, tinham jurado os homens de Israel em Mizpá, dizendo: Nenhum de nós dará sua filha por mulher aos benjamitas.

[[v7-21-2]]

^<<v7-21-2,2>>^ Veio, pois, o povo a Betel, e ali ficou até à tarde diante de Deus; e todos levantaram a sua voz, e prantearam com grande pranto,

[[v7-21-3]]

^<<v7-21-3,3>>^ E disseram: Ah! Senhor Deus de Israel, por que sucedeu isto, que hoje falte uma tribo em Israel?

[[v7-21-4]]

^<<v7-21-4,4>>^ E sucedeu que, no dia seguinte, o povo, pela manhã se levantou, e edificou ali um altar; e ofereceu holocaustos e ofertas pacíficas.

[[v7-21-5]]

^<<v7-21-5,5>>^ E disseram os filhos de Israel: Quem de todas as tribos de Israel não subiu à assembléia do Senhor? Porque se tinha feito um grande juramento acerca dos que não fossem ao Senhor em Mizpá, dizendo: Morrerá certamente.

[[v7-21-6]]

^<<v7-21-6,6>>^ E arrependeram-se os filhos de Israel acerca de Benjamim, seu irmão, e disseram: Cortada é hoje de Israel uma tribo.

[[v7-21-7]]

^<<v7-21-7,7>>^ Como havemos de conseguir mulheres para os que restaram deles, pois nós temos jurado pelo Senhor que nenhuma de nossas filhas lhes daríamos por mulher?

[[v7-21-8]]

^<<v7-21-8,8>>^ E disseram: Há algumas das tribos de Israel que não subiram ao Senhor a Mizpá? E eis que ninguém de Jabes-Gileade viera ao arraial, à assembléia.

[[v7-21-9]]

^<<v7-21-9,9>>^ Porquanto, quando se contou o povo, eis que nenhum dos moradores de Jabes-Gileade se achou ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Então a assembléia enviou para lá doze mil homens dos mais valentes, e lhes ordenou, dizendo: Ide, e ao fio da espada feri aos moradores de Jabes-Gileade, e às mulheres e aos meninos.

[[v7-21-11]]

^<<v7-21-11,11>>^ Porém isto é o que haveis de fazer: A todo o homem e a toda a mulher que se houver deitado com um homem totalmente destruireis.

[[v7-21-12]]

^<<v7-21-12,12>>^ E acharam entre os moradores de Jabes-Gileade quatrocentas moças virgens, que não tinham conhecido homem; e as trouxeram ao arraial, a Siló, que está na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Então toda a assembléia enviou, e falou aos filhos de Benjamim, que estavam na penha de Rimom, e lhes proclamou a paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ E ao mesmo tempo voltaram os benjamitas; e deram-lhes as mulheres que haviam guardado com vida, das mulheres de Jabes-Gileade; porém estas ainda não lhes bastaram.

[[v7-21-15]]

^<<v7-21-15,15>>^ Então o povo se arrependeu por causa de Benjamim; porquanto o Senhor tinha feito brecha nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ E disseram os anciãos da assembléia: Que faremos acerca de mulheres para os que restaram, pois foram destruídas as mulheres de Benjamim?

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram mais: Tenha Benjamim uma herança nos que restaram, e não seja destruída nenhuma tribo de Israel.

[[v7-21-18]]

^<<v7-21-18,18>>^ Porém nós não lhes poderemos dar mulheres de nossas filhas, porque os filhos de Israel juraram, dizendo: Maldito aquele que der mulher aos benjamitas.

[[v7-21-19]]

^<<v7-21-19,19>>^ Então disseram: Eis que de ano em ano há solenidade do Senhor em Siló, que se celebra para o norte de Betel do lado do nascente do sol, pelo caminho alto que sobe de Betel a Siquém, e para o sul de Lebona.

[[v7-21-20]]

^<<v7-21-20,20>>^ E mandaram aos filhos de Benjamim, dizendo: Ide, e emboscai-vos nas vinhas.

[[v7-21-21]]

^<<v7-21-21,21>>^ E olhai, e eis aí as filhas de Siló a dançar em rodas, saí vós das vinhas, e arrebatai cada um sua mulher das filhas de Siló, e ide-vos à terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ E será que, quando seus pais ou seus irmãos vierem a litigar conosco, nós lhes diremos: Por amor de nós, tende compaixão deles, pois nesta guerra não tomamos mulheres para cada um deles; porque não lhas destes vós, para que agora ficásseis culpados.

[[v7-21-23]]

^<<v7-21-23,23>>^ E os filhos de Benjamim o fizeram assim, e levaram mulheres conforme ao número deles, das que arrebataram das rodas que dançavam; e foram-se, e voltaram à sua herança, e reedificaram as cidades, e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Também os filhos de Israel partiram dali, cada um para a sua tribo e para a sua família; e saíram dali, cada um para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias não havia rei em Israel; porém cada um fazia o que parecia reto aos seus olhos.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]