include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// acf ?, ACF - Almeida Corrigida Fiel

[[v7-3-1]]

^<<v7-3-1,1>>^ Estas, pois, são as nações que o SENHOR deixou ficar, para por elas provar a Israel, a saber, a todos os que não sabiam de todas as guerras de Canaã.

[[v7-3-2]]

^<<v7-3-2,2>>^ Tão-somente para que as gerações dos filhos de Israel delas soubessem (para lhes ensinar a guerra), pelo menos os que dantes não sabiam delas.

[[v7-3-3]]

^<<v7-3-3,3>>^ Cinco príncipes dos filisteus, e todos os cananeus, e sidônios, e heveus que habitavam nas montanhas do Líbano desde o monte de Baal-Hermom, até à entrada de Hamate.

[[v7-3-4]]

^<<v7-3-4,4>>^ Estes, pois, ficaram, para por eles provar a Israel, para saber se dariam ouvido aos mandamentos do Senhor, que ele tinha ordenado a seus pais, pelo ministério de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Habitando, pois, os filhos de Israel no meio dos cananeus, dos heteus, e amorreus, e perizeus, e heveus, e jebuseus,

[[v7-3-6]]

^<<v7-3-6,6>>^ Tomaram de suas filhas para si por mulheres, e deram as suas filhas aos filhos deles; e serviram aos seus deuses.

[[v7-3-7]]

^<<v7-3-7,7>>^ E os filhos de Israel fizeram o que era mau aos olhos do Senhor, e se esqueceram do Senhor seu Deus; e serviram aos baalins e a Astarote.

[[v7-3-8]]

^<<v7-3-8,8>>^ Então a ira do SENHOR se acendeu contra Israel, e ele os vendeu na mão de Cusã-Risataim, rei da mesopotâmia; e os filhos de Israel serviram a Cusã-Risataim oito anos.

[[v7-3-9]]

^<<v7-3-9,9>>^ E os filhos de Israel clamaram ao Senhor, e o Senhor levantou-lhes um libertador, que os libertou: Otniel, filho de Quenaz, irmão de Calebe, mais novo do que ele.

[[v7-3-10]]

^<<v7-3-10,10>>^ E veio sobre ele o Espírito do Senhor, e julgou a Israel, e saiu à peleja; e o Senhor entregou na sua mão a Cusã-Risataim, rei da Síria; contra o qual prevaleceu a sua mão.

[[v7-3-11]]

^<<v7-3-11,11>>^ Então a terra sossegou quarenta anos; e Otniel, filho de Quenaz, faleceu.

[[v7-3-12]]

^<<v7-3-12,12>>^ Porém os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor; então o Senhor fortaleceu a Eglom, rei dos moabitas, contra Israel; porquanto fizeram o que era mau aos olhos do Senhor.

[[v7-3-13]]

^<<v7-3-13,13>>^ E reuniu consigo os filhos de Amom e os amalequitas, e foi, e feriu a Israel, e tomaram a cidade das palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ E os filhos de Israel serviram a Eglom, rei dos moabitas, dezoito anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Então os filhos de Israel clamaram ao Senhor, e o Senhor lhes levantou um libertador, a Eúde, filho de Gera, filho de Jemim, homem canhoto. E os filhos de Israel enviaram pela sua mão um presente a Eglom, rei dos moabitas.

[[v7-3-16]]

^<<v7-3-16,16>>^ E Eúde fez para si uma espada de dois fios, do comprimento de um côvado; e cingiu-a por baixo das suas vestes, à sua coxa direita.

[[v7-3-17]]

^<<v7-3-17,17>>^ E levou aquele presente a Eglom, rei dos moabitas; e era Eglom homem muito gordo.

[[v7-3-18]]

^<<v7-3-18,18>>^ E sucedeu que, acabando de entregar o presente, despediu a gente que o trouxera.

[[v7-3-19]]

^<<v7-3-19,19>>^ Porém ele mesmo voltou das imagens de escultura que estavam ao pé de Gilgal, e disse: Tenho uma palavra secreta para ti, ó rei. O qual disse: Cala-te. E todos os que lhe assistiam saíram de diante dele.

[[v7-3-20]]

^<<v7-3-20,20>>^ E Eúde entrou numa sala de verão, que o rei tinha só para si, onde estava sentado, e disse: Tenho, para dizer-te, uma palavra de Deus. E levantou-se da cadeira.

[[v7-3-21]]

^<<v7-3-21,21>>^ Então Eúde estendeu a sua mão esquerda, e tirou a espada de sobre sua coxa direita, e lha cravou no ventre,

[[v7-3-22]]

^<<v7-3-22,22>>^ De tal maneira que entrou até o cabo após a lâmina, e a gordura encerrou a lâmina (porque não tirou a espada do ventre); e saiu-lhe o excremento.

[[v7-3-23]]

^<<v7-3-23,23>>^ Então Eúde saiu ao pátio, e fechou as portas da sala e as trancou.

[[v7-3-24]]

^<<v7-3-24,24>>^ E, saindo ele, vieram os servos do rei, e viram, e eis que as portas da sala estavam fechadas; e disseram: Sem dúvida está cobrindo seus pés na recâmara da sala de verão.

[[v7-3-25]]

^<<v7-3-25,25>>^ E, esperando até se alarmarem, eis que ele não abria as portas da sala; então tomaram a chave, e abriram, e eis ali seu senhor estendido morto em terra.

[[v7-3-26]]

^<<v7-3-26,26>>^ E Eúde escapou, enquanto eles se demoravam; porque ele passou pelas imagens de escultura, e escapou para Seirá.

[[v7-3-27]]

^<<v7-3-27,27>>^ E sucedeu que, chegando ele, tocou a buzina nas montanhas de Efraim, e os filhos de Israel desceram com ele das montanhas, e ele adiante deles.

[[v7-3-28]]

^<<v7-3-28,28>>^ E disse-lhes: Segui-me, porque o Senhor vos tem entregue vossos inimigos, os moabitas, nas vossas mãos; e desceram após ele, e tomaram os vaus do Jordão contra Moabe, e a ninguém deixaram passar.

[[v7-3-29]]

^<<v7-3-29,29>>^ E naquele tempo feriram dos moabitas uns dez mil homens, todos corpulentos, e todos homens valorosos; e não escapou nenhum.

[[v7-3-30]]

^<<v7-3-30,30>>^ Assim foi subjugado Moabe naquele dia debaixo da mão de Israel; e a terra sossegou oitenta anos.

[[v7-3-31]]

^<<v7-3-31,31>>^ Depois dele foi Sangar, filho de Anate, que feriu a seiscentos homens dos filisteus com uma aguilhada de bois; e também ele libertou a Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]