include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v29-2-1]]

^<<v29-2-1,1>>^ Tocai a trombeta em Sião, e clamai em alta voz no meu santo monte; tremam todos os moradores da terra, porque o dia do SENHOR vem, já está perto;

[[v29-2-2]]

^<<v29-2-2,2>>^ Dia de trevas e de escuridão; dia de nuvens e densas trevas, como a alva espalhada sobre os montes; povo grande e poderoso, qual nunca houve desde o tempo antigo, nem depois dele haverá pelos anos adiante, de geração em geração.

[[v29-2-3]]

^<<v29-2-3,3>>^ Diante dele um fogo consome, e atrás dele uma chama abrasa; a terra diante dele é como o jardim do Éden, mas atrás dele um desolado deserto; sim, nada lhe escapará.

[[v29-2-4]]

^<<v29-2-4,4>>^ A sua aparência é como a de cavalos; e como cavaleiros assim correm.

[[v29-2-5]]

^<<v29-2-5,5>>^ Como o estrondo de carros, irão saltando sobre os cumes dos montes, como o ruído da chama de fogo que consome a pragana, como um povo poderoso, posto em ordem para o combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante dele temerão os povos; todos os rostos se tornarão enegrecidos.

[[v29-2-7]]

^<<v29-2-7,7>>^ Como valentes correrão, como homens de guerra subirão os muros; e marchará cada um no seu caminho e não se desviará da sua fileira.

[[v29-2-8]]

^<<v29-2-8,8>>^ Ninguém apertará a seu irmão; marchará cada um pelo seu caminho; sobre a mesma espada se arremessarão, e não serão feridos.

[[v29-2-9]]

^<<v29-2-9,9>>^ Irão pela cidade, correrão pelos muros, subirão às casas, entrarão pelas janelas como o ladrão.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante dele tremerá a terra, abalar-se-ão os céus; o sol e a lua se enegrecerão, e as estrelas retirarão o seu resplendor.

[[v29-2-11]]

^<<v29-2-11,11>>^ E o Senhor levantará a sua voz diante do seu exército; porque muitíssimo grande é o seu arraial; porque poderoso é, executando a sua palavra; porque o dia do Senhor é grande e mui terrível, e quem o poderá suportar?

[[v29-2-12]]

^<<v29-2-12,12>>^ Ainda assim, agora mesmo diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto.

[[v29-2-13]]

^<<v29-2-13,13>>^ E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em benignidade, e se arrepende do mal.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se não se voltará e se arrependerá, e deixará após si uma bênção, em oferta de alimentos e libação para o Senhor vosso Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ Tocai a trombeta em Sião, santificai um jejum, convocai uma assembléia solene.

[[v29-2-16]]

^<<v29-2-16,16>>^ Congregai o povo, santificai a congregação, ajuntai os anciãos, congregai as crianças, e os que mamam; saia o noivo da sua recâmara, e a noiva do seu aposento.

[[v29-2-17]]

^<<v29-2-17,17>>^ Chorem os sacerdotes, ministros do Senhor, entre o alpendre e o altar, e digam: Poupa a teu povo, ó Senhor, e não entregues a tua herança ao opróbrio, para que os gentios o dominem; por que diriam entre os povos: Onde está o seu Deus?

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor se mostrou zeloso da sua terra, e compadeceu-se do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ E o Senhor, respondendo, disse ao seu povo: Eis que vos envio o trigo, e o mosto, e o azeite, e deles sereis fartos, e vos não entregarei mais ao opróbrio entre os gentios.

[[v29-2-20]]

^<<v29-2-20,20>>^ Mas removerei para longe de vós o exército do norte, e lançá-lo-ei em uma terra seca e deserta; a sua frente para o mar oriental, e a sua retaguarda para o mar ocidental; e subirá o seu mau cheiro, e subirá a sua podridão; porque fez grandes coisas.

[[v29-2-21]]

^<<v29-2-21,21>>^ Não temas, ó terra: regozija-te e alegra-te, porque o Senhor fez grandes coisas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não temais, animais do campo, porque os pastos do deserto reverdecerão, porque o arvoredo dará o seu fruto, a vide e a figueira darão a sua força.

[[v29-2-23]]

^<<v29-2-23,23>>^ E vós, filhos de Sião, regozijai-vos e alegrai-vos no Senhor vosso Deus, porque ele vos dará em justa medida a chuva temporã; fará descer a chuva no primeiro mês, a temporã e a serôdia.

[[v29-2-24]]

^<<v29-2-24,24>>^ E as eiras se encherão de trigo, e os lagares trasbordarão de mosto e de azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ E restituir-vos-ei os anos que comeu o gafanhoto, a locusta, e o pulgão e a lagarta, o meu grande exército que enviei contra vós.

[[v29-2-26]]

^<<v29-2-26,26>>^ E comereis abundantemente e vos fartareis, e louvareis o nome do Senhor vosso Deus, que procedeu para convosco maravilhosamente; e o meu povo nunca mais será envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ E vós sabereis que eu estou no meio de Israel, e que eu sou o Senhor vosso Deus, e que não há outro; e o meu povo nunca mais será envergonhado.

[[v29-2-28]]

^<<v29-2-28,28>>^ E há de ser que, depois derramarei o meu Espírito sobre toda a carne, e vossos filhos e vossas filhas profetizarão, os vossos velhos terão sonhos, os vossos jovens terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ E também sobre os servos e sobre as servas naqueles dias derramarei o meu Espírito.

[[v29-2-30]]

^<<v29-2-30,30>>^ E mostrarei prodígios no céu, e na terra, sangue e fogo, e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se converterá em trevas, e a lua em sangue, antes que venha o grande e terrível dia do Senhor.

[[v29-2-32]]

^<<v29-2-32,32>>^ E há de ser que todo aquele que invocar o nome do Senhor será salvo; porque no monte Sião e em Jerusalém haverá livramento, assim como disse o Senhor, e entre os sobreviventes, aqueles que o Senhor chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]