include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o SENHOR: Onde está a carta de divórcio de vossa mãe, pela qual eu a repudiei? Ou quem é o meu credor a quem eu vos tenha vendido? Eis que por vossas maldades fostes vendidos, e por vossas transgressões vossa mãe foi repudiada.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que razão vim eu, e ninguém apareceu? Chamei, e ninguém respondeu? Porventura tanto se encolheu a minha mão, que já não possa remir? Ou não há mais força em mim para livrar? Eis que com a minha repreensão faço secar o mar, torno os rios em deserto, até que cheirem mal os seus peixes, porquanto não têm água e morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Eu visto os céus de negridão, pôr-lhes-ei um saco para a sua cobertura.

[[v23-50-4]]

^<<v23-50-4,4>>^ O Senhor DEUS me deu uma língua erudita, para que eu saiba dizer a seu tempo uma boa palavra ao que está cansado. Ele desperta-me todas as manhãs, desperta-me o ouvido para que ouça, como aqueles que aprendem.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Senhor DEUS me abriu os ouvidos, e eu não fui rebelde; não me retirei para trás.

[[v23-50-6]]

^<<v23-50-6,6>>^ As minhas costas ofereci aos que me feriam, e a minha face aos que me arrancavam os cabelos; não escondi a minha face dos que me afrontavam e me cuspiam.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o Senhor DEUS me ajuda, assim não me confundo; por isso pus o meu rosto como um seixo, porque sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Perto está o que me justifica; quem contenderá comigo? Compareçamos juntamente; quem é meu adversário? Chegue-se para mim.

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o Senhor DEUS me ajuda; quem há que me condene? Eis que todos eles como roupas se envelhecerão, e a traça os comerá.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem há entre vós que tema ao Senhor e ouça a voz do seu servo? Quando andar em trevas, e não tiver luz nenhuma, confie no nome do Senhor, e firme-se sobre o seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Eis que todos vós, que acendeis fogo, e vos cingis com faíscas, andai entre as labaredas do vosso fogo, e entre as faíscas, que acendestes. Isto vos sobrevirá da minha mão, e em tormentos jazereis.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]