include::./index.adoc[]

[[v23-4-0]]
=== Isaías, 4
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-4-1]]

^<<v23-4-1,1>>^ E sete mulheres naquele dia lançarão mão de um homem, dizendo: Nós comeremos do nosso pão, e nos vestiremos do que é nosso; tão-somente queremos ser chamadas pelo teu nome; tira o nosso opróbrio.

[[v23-4-2]]

^<<v23-4-2,2>>^ Naquele dia o renovo do Senhor será cheio de beleza e de glória; e o fruto da terra excelente e formoso para os que escaparem de Israel.

[[v23-4-3]]

^<<v23-4-3,3>>^ E será que aquele que for deixado em Sião, e ficar em Jerusalém, será chamado santo; todo aquele que estiver inscrito entre os viventes em Jerusalém;

[[v23-4-4]]

^<<v23-4-4,4>>^ Quando o Senhor lavar a imundícia das filhas de Sião, e limpar o sangue de Jerusalém, do meio dela, com o espírito de justiça, e com o espírito de ardor.

[[v23-4-5]]

^<<v23-4-5,5>>^ E criará o Senhor sobre todo o lugar do monte de Sião, e sobre as suas assembléias, uma nuvem de dia e uma fumaça, e um resplendor de fogo flamejante de noite; porque sobre toda a glória haverá proteção.

[[v23-4-6]]

^<<v23-4-6,6>>^ E haverá um tabernáculo para sombra contra o calor do dia; e para refúgio e esconderijo contra a tempestade e a chuva.

'''

xref:023-isaias/023-isaias-003.adoc#v23-3-0[&#60; Capítulo Anterior] | <<v23-4-0,Topo>> | xref:023-isaias/023-isaias-005.adoc#v23-5-0[Próximo Capítulo &#62;]