include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia se entoará este cântico na terra de Judá: Temos uma cidade forte, a que Deus pôs a salvação por muros e antemuros.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abri as portas, para que entre nelas a nação justa, que observa a verdade.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiai no SENHOR perpetuamente; porque o SENHOR DEUS é uma rocha eterna.

[[v23-26-5]]

^<<v23-26-5,5>>^ Porque ele abate os que habitam no alto, na cidade elevada; humilha-a, humilha-a até ao chão, e derruba-a até ao pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ O pé pisá-la-á; os pés dos aflitos, e os passos dos pobres.

[[v23-26-7]]

^<<v23-26-7,7>>^ O caminho do justo é todo plano; tu retamente pesas o andar do justo.

[[v23-26-8]]

^<<v23-26-8,8>>^ Também no caminho dos teus juízos, Senhor, te esperamos; no teu nome e na tua memória está o desejo da nossa alma.

[[v23-26-9]]

^<<v23-26-9,9>>^ Com minha alma te desejei de noite, e com o meu espírito, que está dentro de mim, madrugarei a buscar-te; porque, havendo os teus juízos na terra, os moradores do mundo aprendem justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que se mostre favor ao ímpio, nem por isso aprende a justiça; até na terra da retidão ele pratica a iniqüidade, e não atenta para a majestade do Senhor.

[[v23-26-11]]

^<<v23-26-11,11>>^ Senhor, a tua mão está exaltada, mas nem por isso a vêem; vê-la-ão, porém, e confundir-se-ão por causa do zelo que tens do teu povo; e o fogo consumirá os teus adversários.

[[v23-26-12]]

^<<v23-26-12,12>>^ Senhor, tu nos darás a paz, porque tu és o que fizeste em nós todas as nossas obras.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Senhor Deus nosso, já outros senhores têm tido domínio sobre nós; porém, por ti só, nos lembramos de teu nome.

[[v23-26-14]]

^<<v23-26-14,14>>^ Morrendo eles, não tornarão a viver; falecendo, não ressuscitarão; por isso os visitaste e destruíste, e apagaste toda a sua memória.

[[v23-26-15]]

^<<v23-26-15,15>>^ Tu, Senhor, aumentaste a esta nação, tu aumentaste a esta nação, fizeste-te glorioso; alargaste todos os confins da terra.

[[v23-26-16]]

^<<v23-26-16,16>>^ Ó Senhor, na angústia te buscaram; vindo sobre eles a tua correção, derramaram a sua oração secreta.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como a mulher grávida, quando está próxima a sua hora, tem dores de parto, e dá gritos nas suas dores, assim fomos nós diante de ti, ó Senhor!

[[v23-26-18]]

^<<v23-26-18,18>>^ Bem concebemos nós e tivemos dores de parto, porém demos à luz o vento; livramento não trouxemos à terra, nem caíram os moradores do mundo.

[[v23-26-19]]

^<<v23-26-19,19>>^ Os teus mortos e também o meu cadáver viverão e ressuscitarão; despertai e exultai, os que habitais no pó, porque o teu orvalho será como o orvalho das ervas, e a terra lançará de si os mortos.

[[v23-26-20]]

^<<v23-26-20,20>>^ Vai, pois, povo meu, entra nos teus quartos, e fecha as tuas portas sobre ti; esconde-te só por um momento, até que passe a ira.

[[v23-26-21]]

^<<v23-26-21,21>>^ Porque eis que o Senhor sairá do seu lugar, para castigar os moradores da terra, por causa da sua iniqüidade, e a terra descobrirá o seu sangue, e não encobrirá mais os seu mortos.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]