include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-45-1]]

^<<v23-45-1,1>>^ Assim diz o SENHOR ao seu ungido, a Ciro, a quem tomo pela mão direita, para abater as nações diante de sua face, e descingir os lombos dos reis, para abrir diante dele as portas, e as portas não se fecharão.

[[v23-45-2]]

^<<v23-45-2,2>>^ Eu irei adiante de ti, e endireitarei os caminhos tortuosos; quebrarei as portas de bronze, e despedaçarei os ferrolhos de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Dar-te-ei os tesouros escondidos, e as riquezas encobertas, para que saibas que eu sou o Senhor, o Deus de Israel, que te chama pelo teu nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Por amor de meu servo Jacó, e de Israel, meu eleito, eu te chamei pelo teu nome, pus o teu sobrenome, ainda que não me conhecesses.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou o Senhor, e não há outro; fora de mim não há Deus; eu te cingirei, ainda que tu não me conheças;

[[v23-45-6]]

^<<v23-45-6,6>>^ Para que se saiba desde o nascente do sol, e desde o poente, que fora de mim não há outro; eu sou o Senhor, e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu formo a luz, e crio as trevas; eu faço a paz, e crio o mal; eu, o Senhor, faço todas estas coisas.

[[v23-45-8]]

^<<v23-45-8,8>>^ Destilai, ó céus, dessas alturas, e as nuvens chovam justiça; abra-se a terra, e produza a salvação, e ao mesmo tempo frutifique a justiça; eu, o Senhor, as criei.

[[v23-45-9]]

^<<v23-45-9,9>>^ Ai daquele que contende com o seu Criador! o caco entre outros cacos de barro! Porventura dirá o barro ao que o formou: Que fazes? ou a tua obra: Não tens mãos?

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz ao pai: Que é o que geras? E à mulher: Que dás tu à luz?

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim diz o Senhor, o Santo de Israel, aquele que o formou: Perguntai-me as coisas futuras; demandai-me acerca de meus filhos, e acerca da obra das minhas mãos.

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu fiz a terra, e criei nela o homem; eu o fiz; as minhas mãos estenderam os céus, e a todos os seus exércitos dei as minhas ordens.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu o despertei em justiça, e todos os seus caminhos endireitarei; ele edificará a minha cidade, e soltará os meus cativos, não por preço nem por presente, diz o Senhor dos Exércitos.

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o SENHOR: O trabalho do Egito, e o comércio dos etíopes e dos sabeus, homens de alta estatura, passarão para ti, e serão teus; irão atrás de ti, virão em grilhões, e diante de ti se prostrarão; far-te-ão as suas súplicas, dizendo: Deveras Deus está em ti, e não há nenhum outro deus.

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente tu és o Deus que te ocultas, o Deus de Israel, o Salvador.

[[v23-45-16]]

^<<v23-45-16,16>>^ Envergonhar-se-ão, e também se confundirão todos; cairão juntamente na afronta os que fabricam imagens.

[[v23-45-17]]

^<<v23-45-17,17>>^ Porém Israel é salvo pelo Senhor, com uma eterna salvação; por isso não sereis envergonhados nem confundidos em toda a eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Porque assim diz o Senhor que tem criado os céus, o Deus que formou a terra, e a fez; ele a confirmou, não a criou vazia, mas a formou para que fosse habitada: Eu sou o Senhor e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei em segredo, nem em lugar algum escuro da terra; não disse à descendência de Jacó: Buscai-me em vão; eu sou o Senhor, que falo a justiça, e anuncio coisas retas.

[[v23-45-20]]

^<<v23-45-20,20>>^ Congregai-vos, e vinde; chegai-vos juntos, os que escapastes das nações; nada sabem os que conduzem em procissão as suas imagens de escultura, feitas de madeira, e rogam a um deus que não pode salvar.

[[v23-45-21]]

^<<v23-45-21,21>>^ Anunciai, e chegai-vos, e tomai conselho todos juntos; quem fez ouvir isto desde a antiguidade? Quem desde então o anunciou? Porventura não sou eu, o Senhor? Pois não há outro Deus senão eu; Deus justo e Salvador não há além de mim.

[[v23-45-22]]

^<<v23-45-22,22>>^ Olhai para mim, e sereis salvos, vós, todos os termos da terra; porque eu sou Deus, e não há outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Por mim mesmo tenho jurado, já saiu da minha boca a palavra de justiça, e não tornará atrás; que diante de mim se dobrará todo o joelho, e por mim jurará toda a língua.

[[v23-45-24]]

^<<v23-45-24,24>>^ De mim se dirá: Deveras no Senhor há justiça e força; até ele virão, mas serão envergonhados todos os que se indignarem contra ele.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas no Senhor será justificada, e se gloriará toda a descendência de Israel.

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]