include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que Tartã, enviado por Sargom, rei da Assíria, veio a Asdode, e guerreou contra ela, e a tomou,

[[v23-20-2]]

^<<v23-20-2,2>>^ Nesse mesmo tempo falou o Senhor por intermédio de Isaías, filho de Amós, dizendo: Vai, solta o cilício de teus lombos, e descalça os sapatos dos teus pés. E ele assim o fez, indo nu e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Então disse o Senhor: Assim como o meu servo Isaías andou três anos nu e descalço, por sinal e prodígio sobre o Egito e sobre a Etiópia,

[[v23-20-4]]

^<<v23-20-4,4>>^ Assim o rei da Assíria levará em cativeiro os presos do Egito, e os exilados da Etiópia, tanto moços como velhos, nus e descalços, e com as nádegas descobertas, para vergonha do Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ E assombrar-se-ão, e envergonhar-se-ão, por causa dos etíopes, sua esperança, como também dos egípcios, sua glória.

[[v23-20-6]]

^<<v23-20-6,6>>^ Então os moradores desta ilha dirão naquele dia: Vede que tal é a nossa esperança, à qual fugimos por socorro, para nos livrarmos da face do rei da Assíria! Como pois escaparemos nós?

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]