include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-63-1]]

^<<v23-63-1,1>>^ Quem é este, que vem de Edom, de Bozra, com vestes tintas; este que é glorioso em sua vestidura, que marcha com a sua grande força? Eu, que falo em justiça, poderoso para salvar.

[[v23-63-2]]

^<<v23-63-2,2>>^ Por que está vermelha a tua vestidura, e as tuas roupas como as daquele que pisa no lagar?

[[v23-63-3]]

^<<v23-63-3,3>>^ Eu sozinho pisei no lagar, e dos povos ninguém houve comigo; e os pisei na minha ira, e os esmaguei no meu furor; e o seu sangue salpicou as minhas vestes, e manchei toda a minha vestidura.

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia da vingança estava no meu coração; e o ano dos meus remidos é chegado.

[[v23-63-5]]

^<<v23-63-5,5>>^ E olhei, e não havia quem me ajudasse; e admirei-me de não haver quem me sustivesse, por isso o meu braço me trouxe a salvação, e o meu furor me susteve.

[[v23-63-6]]

^<<v23-63-6,6>>^ E atropelei os povos na minha ira, e os embriaguei no meu furor; e a sua força derrubei por terra.

[[v23-63-7]]

^<<v23-63-7,7>>^ As benignidades do Senhor mencionarei, e os muitos louvores do Senhor, conforme tudo quanto o Senhor nos concedeu; e grande bondade para com a casa de Israel, que usou com eles segundo as suas misericórdias, e segundo a multidão das suas benignidades.

[[v23-63-8]]

^<<v23-63-8,8>>^ Porque dizia: Certamente eles são meu povo, filhos que não mentirão; assim ele se fez o seu Salvador.

[[v23-63-9]]

^<<v23-63-9,9>>^ Em toda a angústia deles ele foi angustiado, e o anjo da sua presença os salvou; pelo seu amor, e pela sua compaixão ele os remiu; e os tomou, e os conduziu todos os dias da antiguidade.

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles foram rebeldes, e contristaram o seu Espírito Santo; por isso se lhes tornou em inimigo, e ele mesmo pelejou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Todavia se lembrou dos dias da antiguidade, de Moisés, e do seu povo, dizendo: Onde está agora o que os fez subir do mar com os pastores do seu rebanho? Onde está o que pôs no meio deles o seu Espírito Santo?

[[v23-63-12]]

^<<v23-63-12,12>>^ Aquele cujo braço glorioso ele fez andar à mão direita de Moisés, que fendeu as águas diante deles, para fazer para si um nome eterno?

[[v23-63-13]]

^<<v23-63-13,13>>^ Aquele que os guiou pelos abismos, como o cavalo no deserto, de modo que nunca tropeçaram?

[[v23-63-14]]

^<<v23-63-14,14>>^ Como o animal que desce ao vale, o Espírito do Senhor lhes deu descanso; assim guiaste ao teu povo, para te fazeres um nome glorioso.

[[v23-63-15]]

^<<v23-63-15,15>>^ Atenta desde os céus, e olha desde a tua santa e gloriosa habitação. Onde estão o teu zelo e as tuas obras poderosas? A comoção das tuas entranhas, e das tuas misericórdias, detém-se para comigo?

[[v23-63-16]]

^<<v23-63-16,16>>^ Mas tu és nosso Pai, ainda que Abraão não nos conhece, e Israel não nos reconhece; tu, ó Senhor, és nosso Pai; nosso Redentor desde a antiguidade é o teu nome.

[[v23-63-17]]

^<<v23-63-17,17>>^ Por que, ó Senhor, nos fazes errar dos teus caminhos? Por que endureces o nosso coração, para que não te temamos? Volta, por amor dos teus servos, às tribos da tua herança.

[[v23-63-18]]

^<<v23-63-18,18>>^ Só por um pouco de tempo o teu santo povo a possuiu; nossos adversários pisaram o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Somos feitos como aqueles sobre quem tu nunca dominaste, e como os que nunca se chamaram pelo teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]