include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-21-1]]

^<<v23-21-1,1>>^ Peso do deserto do mar. Como os tufões de vento do sul, que tudo assolam, ele virá do deserto, de uma terra horrível.

[[v23-21-2]]

^<<v23-21-2,2>>^ Dura visão me foi anunciada: o pérfido trata perfidamente, e o destruidor anda destruindo. Sobe, ó Elão, sitia, ó Média, que já fiz cessar todo o seu gemido.

[[v23-21-3]]

^<<v23-21-3,3>>^ Por isso os meus lombos estão cheios de angústia; dores se apoderam de mim como as dores daquela que dá à luz; fiquei abatido quando ouvi, e desanimado vendo isso.

[[v23-21-4]]

^<<v23-21-4,4>>^ O meu coração se agita, o horror apavora-me; a noite que desejava, se me tornou em temor.

[[v23-21-5]]

^<<v23-21-5,5>>^ Põem-se a mesa, estão de atalaia, comem, bebem; levantai-vos, príncipes, e untai o escudo.

[[v23-21-6]]

^<<v23-21-6,6>>^ Porque assim me disse o Senhor: Vai, põe uma sentinela, e ela que diga o que vir.

[[v23-21-7]]

^<<v23-21-7,7>>^ E quando vir um carro com um par de cavaleiros, um carro com jumentos, e um carro com camelos, ela que observe atentamente com grande cuidado.

[[v23-21-8]]

^<<v23-21-8,8>>^ E clamou: Um leão, meu Senhor! Sobre a torre de vigia estou em pé continuamente de dia, e de guarda me ponho noites inteiras.

[[v23-21-9]]

^<<v23-21-9,9>>^ E eis agora vem um carro com homens, e um par de cavaleiros. Então respondeu e disse: Caída é babilônia, caída é! E todas as imagens de escultura dos seus deuses quebraram-se no chão.

[[v23-21-10]]

^<<v23-21-10,10>>^ Ah, malhada minha, e trigo da minha eira! O que ouvi do Senhor dos Exércitos, Deus de Israel, isso vos anunciei.

[[v23-21-11]]

^<<v23-21-11,11>>^ Peso de Dumá. Gritam-me de Seir: Guarda, que houve de noite? Guarda, que houve de noite?

[[v23-21-12]]

^<<v23-21-12,12>>^ E disse o guarda: Vem a manhã, e também a noite; se quereis perguntar, perguntai; voltai, vinde.

[[v23-21-13]]

^<<v23-21-13,13>>^ Peso contra Arábia. Nos bosques da Arábia passareis a noite, ó viandantes de Dedanim.

[[v23-21-14]]

^<<v23-21-14,14>>^ Saí com água ao encontro dos sedentos; moradores da terra de Tema, saí com pão ao encontro dos fugitivos.

[[v23-21-15]]

^<<v23-21-15,15>>^ Porque fogem de diante das espadas, de diante da espada desembainhada, e de diante do arco armado, e de diante do peso da guerra.

[[v23-21-16]]

^<<v23-21-16,16>>^ Porque assim me disse o Senhor: Dentro de um ano, como os anos de jornaleiro, desaparecerá toda a glória de Quedar.

[[v23-21-17]]

^<<v23-21-17,17>>^ E os restantes do número dos flecheiros, os poderosos dos filhos de Quedar, serão diminuídos, porque assim disse o Senhor Deus de Israel.

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]