include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-34-1]]

^<<v23-34-1,1>>^ Chegai-vos, nações, para ouvir, e vós povos, escutai; ouça a terra, e a sua plenitude, o mundo, e tudo quanto produz.

[[v23-34-2]]

^<<v23-34-2,2>>^ Porque a indignação do Senhor está sobre todas as nações, e o seu furor sobre todo o exército delas; ele as destruiu totalmente, entregou-as à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ E os seus mortos serão arremessados e dos seus cadáveres subirá o seu mau cheiro; e os montes se derreterão com o seu sangue.

[[v23-34-4]]

^<<v23-34-4,4>>^ E todo o exército dos céus se dissolverá, e os céus se enrolarão como um livro; e todo o seu exército cairá, como cai a folha da vide e como cai o figo da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ Porque a minha espada se embriagou nos céus; eis que sobre Edom descerá, e sobre o povo do meu anátema para exercer juízo.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do Senhor está cheia de sangue, está engordurada da gordura do sangue de cordeiros e de bodes, da gordura dos rins de carneiros; porque o Senhor tem sacrifício em Bozra, e grande matança na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ E os bois selvagens cairão com eles, e os bezerros com os touros; e a sua terra embriagar-se-á de sangue até se fartar, e o seu pó se engrossará com a gordura.

[[v23-34-8]]

^<<v23-34-8,8>>^ Porque será o dia da vingança do Senhor, ano de retribuições pela contenda de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ E os seus ribeiros se tornarão em pez, e o seu pó em enxofre, e a sua terra em pez ardente.

[[v23-34-10]]

^<<v23-34-10,10>>^ Nem de noite nem de dia se apagará; para sempre a sua fumaça subirá; de geração em geração será assolada; pelos séculos dos séculos ninguém passará por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ Mas o pelicano e a coruja a possuirão, e o bufo e o corvo habitarão nela; e ele estenderá sobre ela o cordel de confusão e nível de vaidade.

[[v23-34-12]]

^<<v23-34-12,12>>^ Eles chamarão ao reino os seus nobres, mas nenhum haverá; e todos os seus príncipes não serão coisa alguma.

[[v23-34-13]]

^<<v23-34-13,13>>^ E nos seus palácios crescerão espinhos, urtigas e cardos nas suas fortalezas; e será uma habitação de chacais, e sítio para avestruzes.

[[v23-34-14]]

^<<v23-34-14,14>>^ As feras do deserto se encontrarão com as feras da ilha, e o sátiro clamará ao seu companheiro; e os animais noturnos ali pousarão, e acharão lugar de repouso para si.

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali se aninhará a coruja e porá os seus ovos, e tirará os seus filhotes, e os recolherá debaixo da sua sombra; também ali os abutres se ajuntarão uns com os outros.

[[v23-34-16]]

^<<v23-34-16,16>>^ Buscai no livro do Senhor, e lede; nenhuma destas coisas faltará, ninguém faltará com a sua companheira; porque a minha boca tem ordenado, e o seu espírito mesmo as tem ajuntado.

[[v23-34-17]]

^<<v23-34-17,17>>^ Porque ele mesmo lançou as sortes por elas, e sua mão lhas tens repartido com o cordel; para sempre a possuirão, de geração em geração habitarão nela.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]