include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-61-1]]

^<<v23-61-1,1>>^ O espírito do Senhor DEUS está sobre mim; porque o SENHOR me ungiu, para pregar boas novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos, e a abertura de prisão aos presos;

[[v23-61-2]]

^<<v23-61-2,2>>^ A apregoar o ano aceitável do Senhor e o dia da vingança do nosso Deus; a consolar todos os tristes;

[[v23-61-3]]

^<<v23-61-3,3>>^ A ordenar acerca dos tristes de Sião que se lhes dê glória em vez de cinza, óleo de gozo em vez de tristeza, vestes de louvor em vez de espírito angustiado; a fim de que se chamem árvores de justiça, plantações do Senhor, para que ele seja glorificado.

[[v23-61-4]]

^<<v23-61-4,4>>^ E edificarão os lugares antigamente assolados, e restaurarão os anteriormente destruídos, e renovarão as cidades assoladas, destruídas de geração em geração.

[[v23-61-5]]

^<<v23-61-5,5>>^ E haverá estrangeiros, que apascentarão os vossos rebanhos; e estranhos serão os vossos lavradores e os vossos vinhateiros.

[[v23-61-6]]

^<<v23-61-6,6>>^ Porém vós sereis chamados sacerdotes do Senhor, e vos chamarão ministros de nosso Deus; comereis a riqueza dos gentios, e na sua glória vos gloriareis.

[[v23-61-7]]

^<<v23-61-7,7>>^ Em lugar da vossa vergonha tereis dupla honra; e em lugar da afronta exultareis na vossa parte; por isso na sua terra possuirão o dobro, e terão perpétua alegria.

[[v23-61-8]]

^<<v23-61-8,8>>^ Porque eu, o Senhor, amo o juízo, odeio o que foi roubado oferecido em holocausto; portanto, firmarei em verdade a sua obra; e farei uma aliança eterna com eles.

[[v23-61-9]]

^<<v23-61-9,9>>^ E a sua posteridade será conhecida entre os gentios, e os seus descendentes no meio dos povos; todos quantos os virem os conhecerão, como descendência bendita do Senhor.

[[v23-61-10]]

^<<v23-61-10,10>>^ Regozijar-me-ei muito no Senhor, a minha alma se alegrará no meu Deus; porque me vestiu de roupas de salvação, cobriu-me com o manto de justiça, como um noivo se adorna com turbante sacerdotal, e como a noiva que se enfeita com as suas jóias.

[[v23-61-11]]

^<<v23-61-11,11>>^ Porque, como a terra produz os seus renovos, e como o jardim faz brotar o que nele se semeia, assim o Senhor DEUS fará brotar a justiça e o louvor para todas as nações.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]