include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-23-1]]

^<<v23-23-1,1>>^ Peso de Tiro. Uivai, navios de Társis, porque está assolada, a ponto de não haver nela casa nenhuma, e de ninguém mais entrar nela; desde a terra de Quitim lhes foi isto revelado.

[[v23-23-2]]

^<<v23-23-2,2>>^ Calai-vos, moradores da ilha, vós a quem encheram os mercadores de Sidom, navegando pelo mar.

[[v23-23-3]]

^<<v23-23-3,3>>^ E a sua provisão era a semente de Sior, que vinha com as muitas águas, a ceifa do Nilo, e ela era a feira das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sidom, porque o mar, a fortaleza do mar, fala, dizendo: Eu não tive dores de parto, nem dei à luz, nem ainda criei jovens, nem eduquei virgens.

[[v23-23-5]]

^<<v23-23-5,5>>^ Como quando se ouviram as novas do Egito, assim haverá dores quando se ouvirem as de Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Passai a Társis; clamai, moradores da ilha.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta, porventura, a vossa cidade exultante, cuja origem é dos dias antigos, cujos pés a levaram para longe a peregrinar?

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem formou este desígnio contra Tiro, distribuidora de coroas, cujos mercadores são príncipes e cujos negociantes são os mais nobres da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O Senhor dos Exércitos formou este desígnio para denegrir a soberba de toda a glória, e envilecer os mais nobres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Passa como o Nilo pela tua terra, ó filha de Társis; já não há quem te restrinja.

[[v23-23-11]]

^<<v23-23-11,11>>^ Ele estendeu a sua mão sobre o mar, e turbou os reinos; o Senhor deu ordens contra Canaã, para que se destruíssem as suas fortalezas.

[[v23-23-12]]

^<<v23-23-12,12>>^ E disse: Nunca mais exultarás de alegria, ó oprimida virgem, filha de Sidom; levanta-te, passa a Quitim, e ainda ali não terás descanso.

[[v23-23-13]]

^<<v23-23-13,13>>^ Vede a terra dos caldeus, ainda este povo não era povo; a Assíria a fundou para os que moravam no deserto; levantaram as suas fortalezas, e edificaram os seus palácios; porém converteu-a em ruína.

[[v23-23-14]]

^<<v23-23-14,14>>^ Uivai, navios de Társis, porque está destruída a vossa fortaleza.

[[v23-23-15]]

^<<v23-23-15,15>>^ Naquele dia Tiro será posta em esquecimento por setenta anos, conforme os dias de um rei; porém no fim de setenta anos Tiro cantará como uma prostituta.

[[v23-23-16]]

^<<v23-23-16,16>>^ Toma a harpa, rodeia a cidade, ó prostituta entregue ao esquecimento; faça doces melodias, canta muitas canções, para que haja memória de ti.

[[v23-23-17]]

^<<v23-23-17,17>>^ Porque será no fim de setenta anos que o Senhor visitará a Tiro, e ela tornará à sua ganância de prostituta, e prostituir-se-á com todos os reinos que há sobre a face da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ E o seu comércio e a sua ganância de prostituta serão consagrados ao Senhor; não se entesourará, nem se fechará; mas o seu comércio será para os que habitam perante o Senhor, para que comam até se saciarem, e tenham vestimenta durável.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]