include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-42-1]]

^<<v23-42-1,1>>^ Eis aqui o meu servo, a quem sustenho, o meu eleito, em quem se apraz a minha alma; pus o meu espírito sobre ele; ele trará justiça aos gentios.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não clamará, não se exaltará, nem fará ouvir a sua voz na praça.

[[v23-42-3]]

^<<v23-42-3,3>>^ A cana trilhada não quebrará, nem apagará o pavio que fumega; com verdade trará justiça.

[[v23-42-4]]

^<<v23-42-4,4>>^ Não faltará, nem será quebrantado, até que ponha na terra a justiça; e as ilhas aguardarão a sua lei.

[[v23-42-5]]

^<<v23-42-5,5>>^ Assim diz Deus, o Senhor, que criou os céus, e os estendeu, e espraiou a terra, e a tudo quanto produz; que dá a respiração ao povo que nela está, e o espírito aos que andam nela.

[[v23-42-6]]

^<<v23-42-6,6>>^ Eu, o Senhor, te chamei em justiça, e te tomarei pela mão, e te guardarei, e te darei por aliança do povo, e para luz dos gentios.

[[v23-42-7]]

^<<v23-42-7,7>>^ Para abrir os olhos dos cegos, para tirar da prisão os presos, e do cárcere os que jazem em trevas.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou o Senhor; este é o meu nome; a minha glória, pois, a outrem não darei, nem o meu louvor às imagens de escultura.

[[v23-42-9]]

^<<v23-42-9,9>>^ Eis que as primeiras coisas já se cumpriram, e as novas eu vos anuncio, e, antes que venham à luz, vo-las faço ouvir.

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantai ao Senhor um cântico novo, e o seu louvor desde a extremidade da terra; vós os que navegais pelo mar, e tudo quanto há nele; vós, ilhas, e seus habitantes.

[[v23-42-11]]

^<<v23-42-11,11>>^ Alcem a voz o deserto e as suas cidades, com as aldeias que Quedar habita; exultem os que habitam nas rochas, e clamem do cume dos montes.

[[v23-42-12]]

^<<v23-42-12,12>>^ Dêem a glória ao Senhor, e anunciem o seu louvor nas ilhas.

[[v23-42-13]]

^<<v23-42-13,13>>^ O Senhor sairá como poderoso, como homem de guerra despertará o zelo; clamará, e fará grande ruído, e prevalecerá contra seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ Por muito tempo me calei; estive em silêncio, e me contive; mas agora darei gritos como a que está de parto, e a todos os assolarei e juntamente devorarei.

[[v23-42-15]]

^<<v23-42-15,15>>^ Os montes e outeiros tornarei em deserto, e toda a sua erva farei secar, e tornarei os rios em ilhas, e as lagoas secarei.

[[v23-42-16]]

^<<v23-42-16,16>>^ E guiarei os cegos pelo caminho que nunca conheceram, fá-los-ei caminhar pelas veredas que não conheceram; tornarei as trevas em luz perante eles, e as coisas tortas farei direitas. Estas coisas lhes farei, e nunca os desampararei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Tornarão atrás e confundir-se-ão de vergonha os que confiam em imagens de escultura, e dizem às imagens de fundição: Vós sois nossos deuses.

[[v23-42-18]]

^<<v23-42-18,18>>^ Surdos, ouvi, e vós, cegos, olhai, para que possais ver.

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é cego, senão o meu servo, ou surdo como o meu mensageiro, a quem envio? E quem é cego como o que é perfeito, e cego como o servo do Senhor?

[[v23-42-20]]

^<<v23-42-20,20>>^ Tu vês muitas coisas, mas não as guardas; ainda que tenhas os ouvidos abertos, nada ouves.

[[v23-42-21]]

^<<v23-42-21,21>>^ O Senhor se agradava dele por amor da sua justiça; engrandeceu-o pela lei, e o fez glorioso.

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas este é um povo roubado e saqueado; todos estão enlaçados em cavernas, e escondidos em cárceres; são postos por presa, e ninguém há que os livre; por despojo, e ninguém diz: Restitui.

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem há entre vós que ouça isto, que atenda e ouça o que há de ser depois?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou a Jacó por despojo, e a Israel aos roubadores? Porventura não foi o Senhor, aquele contra quem pecamos, e nos caminhos do qual não queriam andar, não dando ouvidos à sua lei?

[[v23-42-25]]

^<<v23-42-25,25>>^ Por isso derramou sobre eles a indignação da sua ira, e a força da guerra, e lhes pôs labaredas em redor; porém nisso não atentaram; e os queimou, mas não puseram nisso o coração.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]