include::./index.adoc[]

[[v23-49-0]]
=== Isaías, 49
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-49-1]]

^<<v23-49-1,1>>^ Ouvi-me, ilhas, e escutai vós, povos de longe: O SENHOR me chamou desde o ventre, desde as entranhas de minha mãe fez menção do meu nome.

[[v23-49-2]]

^<<v23-49-2,2>>^ E fez a minha boca como uma espada aguda, com a sombra da sua mão me cobriu; e me pôs como uma flecha limpa, e me escondeu na sua aljava;

[[v23-49-3]]

^<<v23-49-3,3>>^ E me disse: Tu és meu servo; és Israel, aquele por quem hei de ser glorificado.

[[v23-49-4]]

^<<v23-49-4,4>>^ Porém eu disse: Debalde tenho trabalhado, inútil e vãmente gastei as minhas forças; todavia o meu direito está perante o Senhor, e o meu galardão perante o meu Deus.

[[v23-49-5]]

^<<v23-49-5,5>>^ E agora diz o Senhor, que me formou desde o ventre para ser seu servo, para que torne a trazer Jacó; porém Israel não se deixará ajuntar; contudo aos olhos do Senhor serei glorificado, e o meu Deus será a minha força.

[[v23-49-6]]

^<<v23-49-6,6>>^ Disse mais: Pouco é que sejas o meu servo, para restaurares as tribos de Jacó, e tornares a trazer os preservados de Israel; também te dei para luz dos gentios, para seres a minha salvação até à extremidade da terra.

[[v23-49-7]]

^<<v23-49-7,7>>^ Assim diz o Senhor, o Redentor de Israel, o seu Santo, à alma desprezada, ao que a nação abomina, ao servo dos que dominam: Os reis o verão, e se levantarão, como também os príncipes, e eles diante de ti se inclinarão, por amor do Senhor, que é fiel, e do Santo de Israel, que te escolheu.

[[v23-49-8]]

^<<v23-49-8,8>>^ Assim diz o Senhor: No tempo aceitável te ouvi e no dia da salvação te ajudei, e te guardarei, e te darei por aliança do povo, para restaurares a terra, e dar-lhes em herança as herdades assoladas;

[[v23-49-9]]

^<<v23-49-9,9>>^ Para dizeres aos presos: Saí; e aos que estão em trevas: Aparecei. Eles pastarão nos caminhos, e em todos os lugares altos haverá o seu pasto.

[[v23-49-10]]

^<<v23-49-10,10>>^ Nunca terão fome, nem sede, nem o calor, nem o sol os afligirá; porque o que se compadece deles os guiará e os levará mansamente aos mananciais das águas.

[[v23-49-11]]

^<<v23-49-11,11>>^ E farei de todos os meus montes um caminho; e as minhas estradas serão levantadas.

[[v23-49-12]]

^<<v23-49-12,12>>^ Eis que estes virão de longe, e eis que aqueles do norte, e do ocidente, e aqueles outros da terra de Sinim.

[[v23-49-13]]

^<<v23-49-13,13>>^ Exultai, ó céus, e alegra-te, ó terra, e vós, montes, estalai com júbilo, porque o Senhor consolou o seu povo, e dos seus aflitos se compadecerá.

[[v23-49-14]]

^<<v23-49-14,14>>^ Porém Sião diz: Já me desamparou o Senhor, e o meu Senhor se esqueceu de mim.

[[v23-49-15]]

^<<v23-49-15,15>>^ Porventura pode uma mulher esquecer-se tanto de seu filho que cria, que não se compadeça dele, do filho do seu ventre? Mas ainda que esta se esquecesse dele, contudo eu não me esquecerei de ti.

[[v23-49-16]]

^<<v23-49-16,16>>^ Eis que nas palmas das minhas mãos eu te gravei; os teus muros estão continuamente diante de mim.

[[v23-49-17]]

^<<v23-49-17,17>>^ Os teus filhos pressurosamente virão, mas os teus destruidores e os teus assoladores sairão do meio de ti.

[[v23-49-18]]

^<<v23-49-18,18>>^ Levanta os teus olhos ao redor, e olha; todos estes que se ajuntam vêm a ti; vivo eu, diz o Senhor, que de todos estes te vestirás, como de um ornamento, e te cingirás deles como noiva.

[[v23-49-19]]

^<<v23-49-19,19>>^ Porque nos teus desertos, e nos teus lugares solitários, e na tua terra destruída, agora te verás apertada de moradores, e os que te devoravam se afastarão para longe de ti.

[[v23-49-20]]

^<<v23-49-20,20>>^ E até mesmo os filhos da tua orfandade dirão aos teus ouvidos: Muito estreito é para mim este lugar; aparta-te de mim, para que possa habitar nele.

[[v23-49-21]]

^<<v23-49-21,21>>^ E dirás no teu coração: Quem me gerou estes? Pois eu estava desfilhada e solitária; entrara em cativeiro, e me retirara; quem, pois, me criou estes? Eis que eu fui deixada sozinha; e estes onde estavam?

[[v23-49-22]]

^<<v23-49-22,22>>^ Assim diz o Senhor DEUS: Eis que levantarei a minha mão para os gentios, e ante os povos arvorarei a minha bandeira; então trarão os teus filhos nos braços, e as tuas filhas serão levadas sobre os ombros.

[[v23-49-23]]

^<<v23-49-23,23>>^ E os reis serão os teus aios, e as suas rainhas as tuas amas; diante de ti se inclinarão com o rosto em terra, e lamberão o pó dos teus pés; e saberás que eu sou o Senhor, que os que confiam em mim não serão confundidos.

[[v23-49-24]]

^<<v23-49-24,24>>^ Porventura tirar-se-ia a presa ao poderoso, ou escapariam os legalmente presos?

[[v23-49-25]]

^<<v23-49-25,25>>^ Mas assim diz o Senhor: Por certo que os presos se tirarão ao poderoso, e a presa do tirano escapará; porque eu contenderei com os que contendem contigo, e os teus filhos eu remirei.

[[v23-49-26]]

^<<v23-49-26,26>>^ E sustentarei os teus opressores com a sua própria carne, e com o seu próprio sangue se embriagarão, como com mosto; e toda a carne saberá que eu sou o Senhor, o teu Salvador, e o teu Redentor, o Forte de Jacó.

'''

xref:023-isaias/023-isaias-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaias/023-isaias-050.adoc#v23-50-0[Próximo Capítulo &#62;]