include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-65-1]]

^<<v23-65-1,1>>^ Fui buscado dos que não perguntavam por mim, fui achado daqueles que não me buscavam; a uma nação que não se chamava do meu nome eu disse: Eis-me aqui. Eis-me aqui.

[[v23-65-2]]

^<<v23-65-2,2>>^ Estendi as minhas mãos o dia todo a um povo rebelde, que anda por caminho, que não é bom, após os seus pensamentos;

[[v23-65-3]]

^<<v23-65-3,3>>^ Povo que de contínuo me irrita diante da minha face, sacrificando em jardins e queimando incenso sobre altares de tijolos;

[[v23-65-4]]

^<<v23-65-4,4>>^ Que habita entre as sepulturas, e passa as noites junto aos lugares secretos; come carne de porco e tem caldo de coisas abomináveis nos seus vasos;

[[v23-65-5]]

^<<v23-65-5,5>>^ Que dizem: Fica onde estás, e não te chegues a mim, porque sou mais santo do que tu. Estes são fumaça no meu nariz, um fogo que arde todo o dia.

[[v23-65-6]]

^<<v23-65-6,6>>^ Eis que está escrito diante de mim: não me calarei; mas eu pagarei, sim, pagarei no seu seio,

[[v23-65-7]]

^<<v23-65-7,7>>^ As vossas iniqüidades, e juntamente as iniqüidades de vossos pais, diz o Senhor, que queimaram incenso nos montes, e me afrontaram nos outeiros; assim lhes tornarei a medir as suas obras antigas no seu seio.

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o Senhor: Como quando se acha mosto num cacho de uvas, dizem: Não o desperdices, pois há bênção nele, assim farei por amor de meus servos, que não os destrua a todos,

[[v23-65-9]]

^<<v23-65-9,9>>^ E produzirei descendência a Jacó, e a Judá um herdeiro que possua os meus montes; e os meus eleitos herdarão a terra e os meus servos habitarão ali.

[[v23-65-10]]

^<<v23-65-10,10>>^ E Sarom servirá de curral de rebanhos, e o vale de Acor lugar de repouso de gados, para o meu povo, que me buscou.

[[v23-65-11]]

^<<v23-65-11,11>>^ Mas a vós, os que vos apartais do Senhor, os que vos esqueceis do meu santo monte, os que preparais uma mesa para a Fortuna, e que misturais a bebida para o Destino.

[[v23-65-12]]

^<<v23-65-12,12>>^ Também vos destinareis à espada, e todos vos encurvareis à matança; porquanto chamei, e não respondestes; falei, e não ouvistes; mas fizestes o que era mau aos meus olhos, e escolhestes aquilo em que não tinha prazer.

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto assim diz o Senhor DEUS: Eis que os meus servos comerão, mas vós padecereis fome; eis que os meus servos beberão, porém vós tereis sede; eis que os meus servos se alegrarão, mas vós vos envergonhareis;

[[v23-65-14]]

^<<v23-65-14,14>>^ Eis que os meus servos exultarão pela alegria de coração, mas vós gritareis pela tristeza de coração; e uivareis pelo quebrantamento de espírito.

[[v23-65-15]]

^<<v23-65-15,15>>^ E deixareis o vosso nome aos meus eleitos por maldição; e o Senhor DEUS vos matará; e a seus servos chamará por outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ Assim que aquele que se bendisser na terra, se bendirá no Deus da verdade; e aquele que jurar na terra, jurará pelo Deus da verdade; porque já estão esquecidas as angústias passadas, e estão escondidas dos meus olhos.

[[v23-65-17]]

^<<v23-65-17,17>>^ Porque, eis que eu crio novos céus e nova terra; e não haverá mais lembrança das coisas passadas, nem mais se recordarão.

[[v23-65-18]]

^<<v23-65-18,18>>^ Mas vós folgareis e exultareis perpetuamente no que eu crio; porque eis que crio para Jerusalém uma alegria, e para o seu povo gozo.

[[v23-65-19]]

^<<v23-65-19,19>>^ E exultarei em Jerusalém, e me alegrarei no meu povo; e nunca mais se ouvirá nela voz de choro nem voz de clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ Não haverá mais nela criança de poucos dias, nem velho que não cumpra os seus dias; porque o menino morrerá de cem anos; porém o pecador de cem anos será amaldiçoado.

[[v23-65-21]]

^<<v23-65-21,21>>^ E edificarão casas, e as habitarão; e plantarão vinhas, e comerão o seu fruto.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não edificarão para que outros habitem; não plantarão para que outros comam; porque os dias do meu povo serão como os dias da árvore, e os meus eleitos gozarão das obras das suas mãos.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão debalde, nem terão filhos para a perturbação; porque são a posteridade bendita do Senhor, e os seus descendentes estarão com eles.

[[v23-65-24]]

^<<v23-65-24,24>>^ E será que antes que clamem eu responderei; estando eles ainda falando, eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro se apascentarão juntos, e o leão comerá palha como o boi; e pó será a comida da serpente. Não farão mal nem dano algum em todo o meu santo monte, diz o Senhor.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]