include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-46-1]]

^<<v23-46-1,1>>^ Bel está abatido, Nebo se encurvou, os seus ídolos são postos sobre os animais e sobre as feras; as cargas dos vossos fardos são canseiras para as feras já cansadas.

[[v23-46-2]]

^<<v23-46-2,2>>^ Juntamente se encurvaram e se abateram; não puderam livrar-se da carga, mas a sua alma entrou em cativeiro.

[[v23-46-3]]

^<<v23-46-3,3>>^ Ouvi-me, ó casa de Jacó, e todo o restante da casa de Israel; vós a quem trouxe nos braços desde o ventre, e sois levados desde a madre.

[[v23-46-4]]

^<<v23-46-4,4>>^ E até à velhice eu serei o mesmo, e ainda até às cãs eu vos carregarei; eu vos fiz, e eu vos levarei, e eu vos trarei, e vos livrarei.

[[v23-46-5]]

^<<v23-46-5,5>>^ A quem me assemelhareis, e com quem me igualareis, e me comparareis, para que sejamos semelhantes?

[[v23-46-6]]

^<<v23-46-6,6>>^ Gastam o ouro da bolsa, e pesam a prata nas balanças; assalariam o ourives, e ele faz um deus, e diante dele se prostram e se inclinam.

[[v23-46-7]]

^<<v23-46-7,7>>^ Sobre os ombros o tomam, o levam, e o põem no seu lugar; ali fica em pé, do seu lugar não se move; e, se alguém clama a ele, resposta nenhuma dá, nem livra alguém da sua tribulação.

[[v23-46-8]]

^<<v23-46-8,8>>^ Lembrai-vos disto, e considerai; trazei-o à memória, ó prevaricadores.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrai-vos das coisas passadas desde a antiguidade; que eu sou Deus, e não há outro Deus, não há outro semelhante a mim.

[[v23-46-10]]

^<<v23-46-10,10>>^ Que anuncio o fim desde o princípio, e desde a antiguidade as coisas que ainda não sucederam; que digo: O meu conselho será firme, e farei toda a minha vontade.

[[v23-46-11]]

^<<v23-46-11,11>>^ Que chamo a ave de rapina desde o oriente, e de uma terra remota o homem do meu conselho; porque assim o disse, e assim o farei vir; eu o formei, e também o farei.

[[v23-46-12]]

^<<v23-46-12,12>>^ Ouvi-me, ó duros de coração, os que estais longe da justiça.

[[v23-46-13]]

^<<v23-46-13,13>>^ Faço chegar a minha justiça, e não estará ao longe, e a minha salvação não tardará; mas estabelecerei em Sião a salvação, e em Israel a minha glória.

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]