include::./index.adoc[]

[[v23-40-0]]
=== Isaías, 40
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-40-1]]

^<<v23-40-1,1>>^ Consolai, consolai o meu povo, diz o vosso Deus.

[[v23-40-2]]

^<<v23-40-2,2>>^ Falai benignamente a Jerusalém, e bradai-lhe que já a sua milícia é acabada, que a sua iniqüidade está expiada e que já recebeu em dobro da mão do Senhor, por todos os seus pecados.

[[v23-40-3]]

^<<v23-40-3,3>>^ Voz do que clama no deserto: Preparai o caminho do Senhor; endireitai no ermo vereda a nosso Deus.

[[v23-40-4]]

^<<v23-40-4,4>>^ Todo o vale será exaltado, e todo o monte e todo o outeiro será abatido; e o que é torcido se endireitará, e o que é áspero se aplainará.

[[v23-40-5]]

^<<v23-40-5,5>>^ E a glória do Senhor se manifestará, e toda a carne juntamente a verá, pois a boca do Senhor o disse.

[[v23-40-6]]

^<<v23-40-6,6>>^ Uma voz diz: Clama; e alguém disse: Que hei de clamar? Toda a carne é erva e toda a sua beleza como a flor do campo.

[[v23-40-7]]

^<<v23-40-7,7>>^ Seca-se a erva, e cai a flor, soprando nela o Espírito do Senhor. Na verdade o povo é erva.

[[v23-40-8]]

^<<v23-40-8,8>>^ Seca-se a erva, e cai a flor, porém a palavra de nosso Deus subsiste eternamente.

[[v23-40-9]]

^<<v23-40-9,9>>^ Tu, ó Sião, que anuncias boas novas, sobe a um monte alto. Tu, ó Jerusalém, que anuncias boas novas, levanta a tua voz fortemente; levanta-a, não temas, e dize às cidades de Judá: Eis aqui está o vosso Deus.

[[v23-40-10]]

^<<v23-40-10,10>>^ Eis que o Senhor DEUS virá com poder e seu braço dominará por ele; eis que o seu galardão está com ele, e o seu salário diante da sua face.

[[v23-40-11]]

^<<v23-40-11,11>>^ Como pastor apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos, e os levará no seu regaço; as que amamentam guiará suavemente.

[[v23-40-12]]

^<<v23-40-12,12>>^ Quem mediu na concha da sua mão as águas, e tomou a medida dos céus aos palmos, e recolheu numa medida o pó da terra e pesou os montes com peso e os outeiros em balanças?

[[v23-40-13]]

^<<v23-40-13,13>>^ Quem guiou o Espírito do Senhor, ou como seu conselheiro o ensinou?

[[v23-40-14]]

^<<v23-40-14,14>>^ Com quem tomou ele conselho, que lhe desse entendimento, e lhe ensinasse o caminho do juízo, e lhe ensinasse conhecimento, e lhe mostrasse o caminho do entendimento?

[[v23-40-15]]

^<<v23-40-15,15>>^ Eis que as nações são consideradas por ele como a gota de um balde, e como o pó miúdo das balanças; eis que ele levanta as ilhas como a uma coisa pequeníssima.

[[v23-40-16]]

^<<v23-40-16,16>>^ Nem todo o Líbano basta para o fogo, nem os seus animais bastam para holocaustos.

[[v23-40-17]]

^<<v23-40-17,17>>^ Todas as nações são como nada perante ele; ele as considera menos do que nada e como uma coisa vã.

[[v23-40-18]]

^<<v23-40-18,18>>^ A quem, pois, fareis semelhante a Deus, ou com que o comparareis?

[[v23-40-19]]

^<<v23-40-19,19>>^ O artífice funde a imagem, e o ourives a cobre de ouro, e forja para ela cadeias de prata.

[[v23-40-20]]

^<<v23-40-20,20>>^ O empobrecido, que não pode oferecer tanto, escolhe madeira que não se apodrece; artífice sábio busca, para gravar uma imagem que não se pode mover.

[[v23-40-21]]

^<<v23-40-21,21>>^ Porventura não sabeis? Porventura não ouvis, ou desde o princípio não se vos notificou, ou não atentastes para os fundamentos da terra?

[[v23-40-22]]

^<<v23-40-22,22>>^ Ele é o que está assentado sobre o círculo da terra, cujos moradores são para ele como gafanhotos; é ele o que estende os céus como cortina, e os desenrola como tenda, para neles habitar;

[[v23-40-23]]

^<<v23-40-23,23>>^ O que reduz a nada os príncipes, e torna em coisa vã os juízes da terra.

[[v23-40-24]]

^<<v23-40-24,24>>^ E mal se tem plantado, mal se tem semeado, e mal se tem arraigado na terra o seu tronco, já se secam, quando ele sopra sobre eles, e um tufão os leva como a pragana.

[[v23-40-25]]

^<<v23-40-25,25>>^ A quem, pois, me fareis semelhante, para que eu lhe seja igual? diz o Santo.

[[v23-40-26]]

^<<v23-40-26,26>>^ Levantai ao alto os vossos olhos, e vede quem criou estas coisas; foi aquele que faz sair o exército delas segundo o seu número; ele as chama a todas pelos seus nomes; por causa da grandeza das suas forças, e porquanto é forte em poder, nenhuma delas faltará.

[[v23-40-27]]

^<<v23-40-27,27>>^ Por que dizes, ó Jacó, e tu falas, ó Israel: O meu caminho está encoberto ao Senhor, e o meu juízo passa despercebido ao meu Deus?

[[v23-40-28]]

^<<v23-40-28,28>>^ Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos fins da terra, nem se cansa nem se fatiga? É inescrutável o seu entendimento.

[[v23-40-29]]

^<<v23-40-29,29>>^ Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.

[[v23-40-30]]

^<<v23-40-30,30>>^ Os jovens se cansarão e se fatigarão, e os moços certamente cairão;

[[v23-40-31]]

^<<v23-40-31,31>>^ Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.

'''

xref:023-isaias/023-isaias-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaias/023-isaias-041.adoc#v23-41-0[Próximo Capítulo &#62;]