include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-24-1]]

^<<v23-24-1,1>>^ Eis que o SENHOR esvazia a terra, e a desola, e transtorna a sua superfície, e dispersa os seus moradores.

[[v23-24-2]]

^<<v23-24-2,2>>^ E o que suceder ao povo, assim sucederá ao sacerdote; ao servo, como ao seu senhor; à serva, como à sua senhora; ao comprador, como ao vendedor; ao que empresta, como ao que toma emprestado; ao que dá usura, como ao que paga usura.

[[v23-24-3]]

^<<v23-24-3,3>>^ De todo se esvaziará a terra, e de todo será saqueada, porque o Senhor pronunciou esta palavra.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra pranteia e se murcha; o mundo enfraquece e se murcha; enfraquecem os mais altos do povo da terra.

[[v23-24-5]]

^<<v23-24-5,5>>^ Na verdade a terra está contaminada por causa dos seus moradores; porquanto têm transgredido as leis, mudado os estatutos, e quebrado a aliança eterna.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso a maldição tem consumido a terra; e os que habitam nela são desolados; por isso são queimados os moradores da terra, e poucos homens restam.

[[v23-24-7]]

^<<v23-24-7,7>>^ Pranteia o mosto, enfraquece a vide; e suspiram todos os alegres de coração.

[[v23-24-8]]

^<<v23-24-8,8>>^ Cessa o folguedo dos tamboris, acaba o ruído dos que exultam, e cessa a alegria da harpa.

[[v23-24-9]]

^<<v23-24-9,9>>^ Com canções não beberão vinho; a bebida forte será amarga para os que a beberem.

[[v23-24-10]]

^<<v23-24-10,10>>^ Demolida está a cidade vazia, todas as casas fecharam, ninguém pode entrar.

[[v23-24-11]]

^<<v23-24-11,11>>^ Há lastimoso clamor nas ruas por falta do vinho; toda a alegria se escureceu, desterrou-se o gozo da terra.

[[v23-24-12]]

^<<v23-24-12,12>>^ Na cidade só ficou a desolação, a porta ficou reduzida a ruínas.

[[v23-24-13]]

^<<v23-24-13,13>>^ Porque assim será no interior da terra, e no meio destes povos, como a sacudidura da oliveira, e como os rabiscos, quando está acabada a vindima.

[[v23-24-14]]

^<<v23-24-14,14>>^ Estes alçarão a sua voz, e cantarão com alegria; e por causa da glória do Senhor exultarão desde o mar.

[[v23-24-15]]

^<<v23-24-15,15>>^ Por isso glorificai ao Senhor no oriente, e nas ilhas do mar, ao nome do Senhor Deus de Israel.

[[v23-24-16]]

^<<v23-24-16,16>>^ Dos confins da terra ouvimos cantar: Glória ao justo. Mas eu disse: Emagreço, emagreço, ai de mim! Os pérfidos têm tratado perfidamente; sim, os pérfidos têm tratado perfidamente.

[[v23-24-17]]

^<<v23-24-17,17>>^ O temor, e a cova, e o laço vêm sobre ti, ó morador da terra.

[[v23-24-18]]

^<<v23-24-18,18>>^ E será que aquele que fugir da voz de temor cairá na cova, e o que subir da cova o laço o prenderá; porque as janelas do alto estão abertas, e os fundamentos da terra tremem.

[[v23-24-19]]

^<<v23-24-19,19>>^ De todo está quebrantada a terra, de todo está rompida a terra, e de todo é movida a terra.

[[v23-24-20]]

^<<v23-24-20,20>>^ De todo cambaleará a terra como o ébrio, e será movida e removida como a choça de noite; e a sua transgressão se agravará sobre ela, e cairá, e nunca mais se levantará.

[[v23-24-21]]

^<<v23-24-21,21>>^ E será que naquele dia o Senhor castigará os exércitos do alto nas alturas, e os reis da terra sobre a terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ E serão ajuntados como presos numa masmorra, e serão encerrados num cárcere; e outra vez serão castigados depois de muitos dias.

[[v23-24-23]]

^<<v23-24-23,23>>^ E a lua se envergonhará, e o sol se confundirá quando o Senhor dos Exércitos reinar no monte Sião e em Jerusalém, e perante os seus anciãos gloriosamente.

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]