include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-47-1]]

^<<v23-47-1,1>>^ Desce, e assenta-te no pó, ó virgem filha de babilônia; assenta-te no chão; já não há trono, ó filha dos caldeus, porque nunca mais serás chamada a tenra nem a delicada.

[[v23-47-2]]

^<<v23-47-2,2>>^ Toma a mó, e mói a farinha; remove o teu véu, descalça os pés, descobre as pernas e passa os rios.

[[v23-47-3]]

^<<v23-47-3,3>>^ A tua vergonha se descobrirá, e ver-se-á o teu opróbrio; tomarei vingança, e não pouparei a homem algum.

[[v23-47-4]]

^<<v23-47-4,4>>^ O nosso redentor cujo nome é o Senhor dos Exércitos, é o Santo de Israel.

[[v23-47-5]]

^<<v23-47-5,5>>^ Assenta-te calada, e entra nas trevas, ó filha dos caldeus, porque nunca mais serás chamada senhora de reinos.

[[v23-47-6]]

^<<v23-47-6,6>>^ Muito me agastei contra o meu povo, profanei a minha herança, e os entreguei na tua mão; porém não usaste com eles de misericórdia, e até sobre os velhos fizeste muito pesado o teu jugo.

[[v23-47-7]]

^<<v23-47-7,7>>^ E disseste: Eu serei senhora para sempre; até agora não te importaste com estas coisas, nem te lembraste do fim delas.

[[v23-47-8]]

^<<v23-47-8,8>>^ Agora, pois, ouve isto, tu que és dada a prazeres, que habitas tão segura, que dizes no teu coração: Eu o sou, e fora de mim não há outra; não ficarei viúva, nem conhecerei a perda de filhos.

[[v23-47-9]]

^<<v23-47-9,9>>^ Porém ambas estas coisas virão sobre ti num momento, no mesmo dia, perda de filhos e viuvez; em toda a sua plenitude virão sobre ti, por causa da multidão das tuas feitiçarias, e da grande abundância dos teus muitos encantamentos.

[[v23-47-10]]

^<<v23-47-10,10>>^ Porque confiaste na tua maldade e disseste: Ninguém me pode ver; a tua sabedoria e o teu conhecimento, isso te fez desviar, e disseste no teu coração: Eu sou, e fora de mim não há outra.

[[v23-47-11]]

^<<v23-47-11,11>>^ Portanto sobre ti virá o mal, sem que saibas a sua origem, e tal destruição cairá sobre ti, sem que a possas evitar; e virá sobre ti de repente desolação que não poderás conhecer.

[[v23-47-12]]

^<<v23-47-12,12>>^ Deixa-te estar com os teus encantamentos, e com a multidão das tuas feitiçarias, em que trabalhaste desde a tua mocidade, a ver se podes tirar proveito, ou se porventura te podes fortalecer.

[[v23-47-13]]

^<<v23-47-13,13>>^ Cansaste-te na multidão dos teus conselhos; levantem-se pois agora os agoureiros dos céus, os que contemplavam os astros, os prognosticadores das luas novas, e salvem-te do que há de vir sobre ti.

[[v23-47-14]]

^<<v23-47-14,14>>^ Eis que serão como a pragana, o fogo os queimará; não poderão salvar a sua vida do poder das chamas; não haverá brasas, para se aquentar, nem fogo para se assentar junto dele.

[[v23-47-15]]

^<<v23-47-15,15>>^ Assim serão para contigo aqueles com quem trabalhaste, os teus negociantes desde a tua mocidade; cada qual irá vagueando pelo seu caminho; ninguém te salvará.

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]