include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-30-1]]

^<<v23-30-1,1>>^ Ai dos filhos rebeldes, diz o SENHOR, que tomam conselho, mas não de mim; e que se cobrem, com uma cobertura, mas não do meu espírito, para acrescentarem pecado sobre pecado;

[[v23-30-2]]

^<<v23-30-2,2>>^ Que descem ao Egito, sem pedirem o meu conselho; para se fortificarem com a força de Faraó, e para confiarem na sombra do Egito.

[[v23-30-3]]

^<<v23-30-3,3>>^ Porque a força de Faraó se vos tornará em vergonha, e a confiança na sombra do Egito em confusão.

[[v23-30-4]]

^<<v23-30-4,4>>^ Porque os seus príncipes já estão em Zoã, e os seus embaixadores já chegaram a Hanes.

[[v23-30-5]]

^<<v23-30-5,5>>^ Todos se envergonharão de um povo que de nada lhes servirá nem de ajuda, nem de proveito, porém de vergonha, e de opróbrio.

[[v23-30-6]]

^<<v23-30-6,6>>^ Peso dos animais do sul. Para a terra de aflição e de angústia (de onde vêm a leoa e o leão, a víbora, e a serpente ardente, voadora) levarão às costas de jumentinhos as suas riquezas, e sobre as corcovas de camelos os seus tesouros, a um povo que de nada lhes aproveitará.

[[v23-30-7]]

^<<v23-30-7,7>>^ Porque o Egito os ajudará em vão, e para nenhum fim; por isso clamei acerca disto: No estarem quietos será a sua força.

[[v23-30-8]]

^<<v23-30-8,8>>^ Vai, pois, agora, escreve isto numa tábua perante eles e registra-o num livro; para que fique até ao último dia, para sempre e perpetuamente.

[[v23-30-9]]

^<<v23-30-9,9>>^ Porque este é um povo rebelde, filhos mentirosos, filhos que não querem ouvir a lei do Senhor.

[[v23-30-10]]

^<<v23-30-10,10>>^ Que dizem aos videntes: Não vejais; e aos profetas: Não profetizeis para nós o que é reto; dizei-nos coisas aprazíveis, e vede para nós enganos.

[[v23-30-11]]

^<<v23-30-11,11>>^ Desviai-vos do caminho, apartai-vos da vereda; fazei que o Santo de Israel cesse de estar perante nós.

[[v23-30-12]]

^<<v23-30-12,12>>^ Por isso, assim diz o Santo de Israel: porquanto rejeitais esta palavra, e confiais na opressão e perversidade, e sobre isso vos estribais,

[[v23-30-13]]

^<<v23-30-13,13>>^ Por isso esta maldade vos será como a brecha de um alto muro que, formando uma barriga, está prestes a cair e cuja quebra virá subitamente.

[[v23-30-14]]

^<<v23-30-14,14>>^ E ele o quebrará como se quebra o vaso do oleiro e, quebrando-o, não se compadecerá; de modo que não se achará entre os seus pedaços um caco para tomar fogo do lar, ou tirar água da poça.

[[v23-30-15]]

^<<v23-30-15,15>>^ Porque assim diz o Senhor DEUS, o Santo de Israel: Voltando e descansando sereis salvos; no sossego e na confiança estaria a vossa força, mas não quisestes.

[[v23-30-16]]

^<<v23-30-16,16>>^ Mas dizeis: Não; antes sobre cavalos fugiremos; portanto fugireis; e, sobre cavalos ligeiros cavalgaremos; por isso os vossos perseguidores também serão ligeiros.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil homens fugirão ao grito de um, e ao grito de cinco todos vós fugireis, até que sejais deixados como o mastro no cume do monte, e como a bandeira no outeiro.

[[v23-30-18]]

^<<v23-30-18,18>>^ Por isso, o Senhor esperará, para ter misericórdia de vós; e por isso se levantará, para se compadecer de vós, porque o Senhor é um Deus de eqüidade; bem-aventurados todos os que nele esperam.

[[v23-30-19]]

^<<v23-30-19,19>>^ Porque o povo habitará em Sião, em Jerusalém; não chorarás mais; certamente se compadecerá de ti, à voz do teu clamor e, ouvindo-a, te responderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ Bem vos dará o Senhor pão de angústia e água de aperto, mas os teus mestres nunca mais fugirão de ti, como voando com asas; antes os teus olhos verão a todos os teus mestres.

[[v23-30-21]]

^<<v23-30-21,21>>^ E os teus ouvidos ouvirão a palavra do que está por detrás de ti, dizendo: Este é o caminho, andai nele, sem vos desviardes nem para a direita nem para a esquerda.

[[v23-30-22]]

^<<v23-30-22,22>>^ E terás por contaminadas as coberturas de tuas esculturas de prata, e o revestimento das tuas esculturas fundidas de ouro; e as lançarás fora como um pano imundo, e dirás a cada uma delas: Fora daqui.

[[v23-30-23]]

^<<v23-30-23,23>>^ Então te dará chuva sobre a tua semente, com que semeares a terra, como também pão da novidade da terra; e esta será fértil e cheia; naquele dia o teu gado pastará em largos pastos.

[[v23-30-24]]

^<<v23-30-24,24>>^ E os bois e os jumentinhos, que lavram a terra, comerão grão puro, que for padejado com a pá, e cirandado com a ciranda.

[[v23-30-25]]

^<<v23-30-25,25>>^ E em todo o monte alto, e em todo o outeiro levantado, haverá ribeiros e correntes de águas, no dia da grande matança, quando caírem as torres.

[[v23-30-26]]

^<<v23-30-26,26>>^ E a luz da lua será como a luz do sol, e a luz do sol sete vezes maior, como a luz de sete dias, no dia em que o Senhor ligar a quebradura do seu povo, e curar a chaga da sua ferida.

[[v23-30-27]]

^<<v23-30-27,27>>^ Eis que o nome do Senhor vem de longe, ardendo a sua ira, sendo pesada a sua carga; os seus lábios estão cheios de indignação, e a sua língua é como um fogo consumidor.

[[v23-30-28]]

^<<v23-30-28,28>>^ E a sua respiração como o ribeiro transbordante, que chega até ao pescoço, para peneirar as nações com peneira de destruição, e um freio de fazer errar nas queixadas dos povos.

[[v23-30-29]]

^<<v23-30-29,29>>^ Um cântico haverá entre vós, como na noite em que se celebra uma festa santa; e alegria de coração, como a daquele que vai com flauta, para entrar no monte do Senhor, à Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ E o Senhor fará ouvir a sua voz majestosa e fará ver o abaixamento do seu braço, com indignação de ira, e labareda de fogo consumidor, raios e dilúvio e pedras de saraiva.

[[v23-30-31]]

^<<v23-30-31,31>>^ Porque com a voz do Senhor será desfeita em pedaços a Assíria, que feriu com a vara.

[[v23-30-32]]

^<<v23-30-32,32>>^ E a cada pancada do bordão do juízo que o Senhor lhe der, haverá tamboris e harpas; e com combates de agitação combaterá contra eles.

[[v23-30-33]]

^<<v23-30-33,33>>^ Porque Tofete já há muito está preparada; sim, está preparada para o rei; ele a fez profunda e larga; a sua pira é de fogo, e tem muita lenha; o assopro do Senhor como torrente de enxofre a acenderá.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]