include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-5-1]]

^<<v23-5-1,1>>^ Agora cantarei ao meu amado o cântico do meu querido a respeito da sua vinha. O meu amado tem uma vinha num outeiro fértil.

[[v23-5-2]]

^<<v23-5-2,2>>^ E cercou-a, e limpando-a das pedras, plantou-a de excelentes vides; e edificou no meio dela uma torre, e também construiu nela um lagar; e esperava que desse uvas boas, porém deu uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora, pois, ó moradores de Jerusalém, e homens de Judá, julgai, vos peço, entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se podia fazer à minha vinha, que eu lhe não tenha feito? Por que, esperando eu que desse uvas boas, veio a dar uvas bravas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora, pois, vos farei saber o que eu hei de fazer à minha vinha: tirarei a sua sebe, para que sirva de pasto; derrubarei a sua parede, para que seja pisada;

[[v23-5-6]]

^<<v23-5-6,6>>^ E a tornarei em deserto; não será podada nem cavada; porém crescerão nela sarças e espinheiros; e às nuvens darei ordem que não derramem chuva sobre ela.

[[v23-5-7]]

^<<v23-5-7,7>>^ Porque a vinha do Senhor dos Exércitos é a casa de Israel, e os homens de Judá são a planta das suas delícias; e esperou que exercesse juízo, e eis aqui opressão; justiça, e eis aqui clamor.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que ajuntam casa a casa, reúnem campo a campo, até que não haja mais lugar, e fiquem como únicos moradores no meio da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ A meus ouvidos disse o Senhor dos Exércitos: Em verdade que muitas casas ficarão desertas, e até as grandes e excelentes sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ E dez jeiras de vinha não darão mais do que um bato; e um ômer de semente não dará mais do que um efa.

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam pela manhã, e seguem a bebedice; e continuam até à noite, até que o vinho os esquente!

[[v23-5-12]]

^<<v23-5-12,12>>^ E harpas e alaúdes, tamboris e gaitas, e vinho há nos seus banquetes; e não olham para a obra do Senhor, nem consideram as obras das suas mãos.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto o meu povo será levado cativo, por falta de entendimento; e os seus nobres terão fome, e a sua multidão se secará de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Portanto o inferno grandemente se alargou, e se abriu a sua boca desmesuradamente; e para lá descerão o seu esplendor, e a sua multidão, e a sua pompa, e os que entre eles se alegram.

[[v23-5-15]]

^<<v23-5-15,15>>^ Então o plebeu se abaterá, e o nobre se humilhará; e os olhos dos altivos se humilharão.

[[v23-5-16]]

^<<v23-5-16,16>>^ Porém o Senhor dos Exércitos será exaltado em juízo; e Deus, o Santo, será santificado em justiça.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então os cordeiros pastarão como de costume, e os estranhos comerão dos lugares devastados pelos gordos.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que puxam a iniqüidade com cordas de vaidade, e o pecado com tirantes de carro!

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: Avie-se, e acabe a sua obra, para que a vejamos; e aproxime-se e venha o conselho do Santo de Israel, para que o conheçamos.

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que ao mal chamam bem, e ao bem mal; que fazem das trevas luz, e da luz trevas; e fazem do amargo doce, e do doce amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios a seus próprios olhos, e prudentes diante de si mesmos!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são poderosos para beber vinho, e homens de poder para misturar bebida forte;

[[v23-5-23]]

^<<v23-5-23,23>>^ Dos que justificam ao ímpio por suborno, e aos justos negam a justiça!

[[v23-5-24]]

^<<v23-5-24,24>>^ Por isso, como a língua de fogo consome a palha, e o restolho se desfaz pela chama, assim será a sua raiz como podridão, e a sua flor se esvaecerá como pó; porquanto rejeitaram a lei do Senhor dos Exércitos, e desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso se acendeu a ira do Senhor contra o seu povo, e estendeu a sua mão contra ele, e o feriu, de modo que as montanhas tremeram, e os seus cadáveres se fizeram como lixo no meio das ruas; com tudo isto não tornou atrás a sua ira, mas a sua mão ainda está estendida.

[[v23-5-26]]

^<<v23-5-26,26>>^ E ele arvorará o estandarte para as nações de longe, e lhes assobiará para que venham desde a extremidade da terra; e eis que virão apressurada e ligeiramente.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não haverá entre eles cansado, nem quem tropece; ninguém tosquenejará nem dormirá; não se lhe desatará o cinto dos seus lombos, nem se lhe quebrará a correia dos seus sapatos.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas flechas serão agudas, e todos os seus arcos retesados; os cascos dos seus cavalos são reputados como pederneiras, e as rodas dos seus carros como redemoinho.

[[v23-5-29]]

^<<v23-5-29,29>>^ O seu rugido será como o do leão; rugirão como filhos de leão; sim, rugirão e arrebatarão a presa, e a levarão, e não haverá quem a livre.

[[v23-5-30]]

^<<v23-5-30,30>>^ E bramarão contra eles naquele dia, como o bramido do mar; então olharão para a terra, e eis que só verão trevas e ânsia, e a luz se escurecerá nos céus.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]