include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// acf ?, ACF - Almeida Corrigida Fiel

[[v23-3-1]]

^<<v23-3-1,1>>^ Porque, eis que o Senhor, o SENHOR dos Exércitos, tirará de Jerusalém e de Judá o sustento e o apoio; a todo o sustento de pão e a todo o sustento de água;

[[v23-3-2]]

^<<v23-3-2,2>>^ O poderoso, e o homem de guerra, o juiz, e o profeta, e o adivinho, e o ancião,

[[v23-3-3]]

^<<v23-3-3,3>>^ O capitão de cinqüenta, e o homem respeitável, e o conselheiro, e o sábio entre os artífices, e o eloqüente orador.

[[v23-3-4]]

^<<v23-3-4,4>>^ E dar-lhes-ei meninos por príncipes, e crianças governarão sobre eles.

[[v23-3-5]]

^<<v23-3-5,5>>^ E o povo será oprimido; um será contra o outro, e cada um contra o seu próximo; o menino se atreverá contra o ancião, e o vil contra o nobre.

[[v23-3-6]]

^<<v23-3-6,6>>^ Quando alguém pegar de seu irmão na casa de seu pai, dizendo: Tu tens roupa, sê nosso governador, e toma sob a tua mão esta ruína;

[[v23-3-7]]

^<<v23-3-7,7>>^ Naquele dia levantará este a sua voz, dizendo: Não posso ser médico, nem tampouco há em minha casa pão, ou roupa alguma; não me haveis de constituir governador sobre o povo.

[[v23-3-8]]

^<<v23-3-8,8>>^ Porque Jerusalém está arruinada, e Judá caída; porque a sua língua e as suas obras são contra o Senhor, para provocarem os olhos da sua glória.

[[v23-3-9]]

^<<v23-3-9,9>>^ O aspecto do seu rosto testifica contra eles; e publicam os seus pecados, como Sodoma; não os dissimulam. Ai da sua alma! Porque fazem mal a si mesmos.

[[v23-3-10]]

^<<v23-3-10,10>>^ Dizei ao justo que bem lhe irá; porque comerão do fruto das suas obras.

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai do ímpio! Mal lhe irá; porque se lhe fará o que as suas mãos fizeram.

[[v23-3-12]]

^<<v23-3-12,12>>^ Os opressores do meu povo são crianças, e mulheres dominam sobre ele; ah, povo meu! Os que te guiam te enganam, e destroem o caminho das tuas veredas.

[[v23-3-13]]

^<<v23-3-13,13>>^ O Senhor se levanta para pleitear, e põe-se de pé para julgar os povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ O Senhor entrará em juízo contra os anciãos do seu povo, e contra os seus príncipes; é que fostes vós que consumistes esta vinha; o espólio do pobre está em vossas casas.

[[v23-3-15]]

^<<v23-3-15,15>>^ Que tendes vós, que esmagais o meu povo e moeis as faces dos pobres? Diz o Senhor DEUS dos Exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ Diz ainda mais o Senhor: Porquanto as filhas de Sião se exaltam, e andam com o pescoço erguido, lançando olhares impudentes; e quando andam, caminham afetadamente, fazendo um tilintar com os seus pés;

[[v23-3-17]]

^<<v23-3-17,17>>^ Portanto o Senhor fará tinhoso o alto da cabeça das filhas de Sião, e o Senhor porá a descoberto a sua nudez,

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia tirará o Senhor os ornamentos dos pés, e as toucas, e adornos em forma de lua,

[[v23-3-19]]

^<<v23-3-19,19>>^ Os pendentes, e os braceletes, as estolas,

[[v23-3-20]]

^<<v23-3-20,20>>^ Os gorros, e os ornamentos das pernas, e os cintos e as caixinhas de perfumes, e os brincos,

[[v23-3-21]]

^<<v23-3-21,21>>^ Os anéis, e as jóias do nariz,

[[v23-3-22]]

^<<v23-3-22,22>>^ Os vestidos de festa, e os mantos, e os xales, e as bolsas.

[[v23-3-23]]

^<<v23-3-23,23>>^ Os espelhos, e o linho finíssimo, e os turbantes, e os véus.

[[v23-3-24]]

^<<v23-3-24,24>>^ E será que em lugar de perfume haverá mau cheiro; e por cinto uma corda; e em lugar de encrespadura de cabelos, calvície; e em lugar de veste luxuosa, pano de saco; e queimadura em lugar de formosura.

[[v23-3-25]]

^<<v23-3-25,25>>^ Teus homens cairão à espada e teus poderosos na peleja.

[[v23-3-26]]

^<<v23-3-26,26>>^ E as suas portas gemerão e prantearão; e ela, desolada, se assentará no chão.

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]