include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-32-1]]

^<<v24-32-1,1>>^ A palavra que veio a Jeremias da parte do SENHOR, no ano décimo de Zedequias, rei de Judá, o qual foi o décimo oitavo de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ Ora, nesse tempo o exército do rei de babilônia cercava Jerusalém; e Jeremias, o profeta, estava encerrado no pátio da guarda que estava na casa do rei de Judá;

[[v24-32-3]]

^<<v24-32-3,3>>^ Porque Zedequias, rei de Judá, o tinha encerrado, dizendo: Por que profetizas tu, dizendo: Assim diz o SENHOR: Eis que entrego esta cidade na mão do rei de babilônia, e ele a tomará;

[[v24-32-4]]

^<<v24-32-4,4>>^ E Zedequias, rei de Judá, não escapará das mãos dos caldeus; mas certamente será entregue na mão do rei de babilônia, e com ele falará boca a boca, e os seus olhos verão os dele;

[[v24-32-5]]

^<<v24-32-5,5>>^ E ele levará Zedequias para babilônia, e ali estará, até que eu o visite, diz o SENHOR e, ainda que pelejeis contra os caldeus, não ganhareis?

[[v24-32-6]]

^<<v24-32-6,6>>^ Disse, pois, Jeremias: Veio a mim a palavra do Senhor, dizendo:

[[v24-32-7]]

^<<v24-32-7,7>>^ Eis que Hanameel, filho de Salum, teu tio, virá a ti dizendo: Compra para ti a minha herdade que está em Anatote, pois tens o direito de resgate para comprá-la.

[[v24-32-8]]

^<<v24-32-8,8>>^ Veio, pois, a mim Hanameel, filho de meu tio, segundo a palavra do Senhor, ao pátio da guarda, e me disse: Compra agora a minha herdade que está em Anatote, na terra de Benjamim; porque teu é o direito de herança, e tens o resgate; compra-a para ti. Então entendi que isto era a palavra do Senhor.

[[v24-32-9]]

^<<v24-32-9,9>>^ Comprei, pois, a herdade de Hanameel, filho de meu tio, a qual está em Anatote; e pesei-lhe o dinheiro, dezessete siclos de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ E assinei a escritura, e selei-a, e fiz confirmar por testemunhas; e pesei-lhe o dinheiro numa balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ E tomei a escritura da compra, selada segundo a lei e os estatutos, e a cópia aberta.

[[v24-32-12]]

^<<v24-32-12,12>>^ E dei a escritura da compra a Baruque, filho de Nerias, filho de Maaséias, na presença de Hanameel, filho de meu tio e na presença das testemunhas, que subscreveram a escritura da compra, e na presença de todos os judeus que se assentavam no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ E dei ordem a Baruque, na presença deles, dizendo:

[[v24-32-14]]

^<<v24-32-14,14>>^ Assim diz o Senhor dos Exércitos, o Deus de Israel: Toma estas escrituras, este auto de compra, tanto a selada, como a aberta, e coloca-as num vaso de barro, para que se possam conservar muitos dias.

[[v24-32-15]]

^<<v24-32-15,15>>^ Porque assim diz o Senhor dos Exércitos, o Deus de Israel: Ainda se comprarão casas, e campos, e vinhas nesta terra.

[[v24-32-16]]

^<<v24-32-16,16>>^ E depois que dei a escritura da compra a Baruque, filho de Nerias, orei ao Senhor, dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ Ah Senhor DEUS! Eis que tu fizeste os céus e a terra com o teu grande poder, e com o teu braço estendido; nada há que te seja demasiado difícil;

[[v24-32-18]]

^<<v24-32-18,18>>^ Tu que usas de benignidade com milhares, e retribuis a maldade dos pais ao seio dos filhos depois deles; o grande, o poderoso Deus cujo nome é o Senhor dos Exércitos;

[[v24-32-19]]

^<<v24-32-19,19>>^ Grande em conselho, e magnífico em obras; porque os teus olhos estão abertos sobre todos os caminhos dos filhos dos homens, para dar a cada um segundo os seus caminhos e segundo o fruto das suas obras;

[[v24-32-20]]

^<<v24-32-20,20>>^ Tu puseste sinais e maravilhas na terra do Egito até ao dia de hoje, tanto em Israel, como entre os outros homens, e te fizeste um nome, o qual tu tens neste dia.

[[v24-32-21]]

^<<v24-32-21,21>>^ E tiraste o teu povo Israel da terra do Egito, com sinais e com maravilhas, e com mão forte, e com braço estendido, e com grande espanto,

[[v24-32-22]]

^<<v24-32-22,22>>^ E lhes deste esta terra, que juraste a seus pais que lhes havias de dar, terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ E entraram nela, e a possuíram, mas não obedeceram à tua voz, nem andaram na tua lei; tudo o que lhes mandaste que fizessem, eles não o fizeram; por isso ordenaste lhes sucedesse todo este mal.

[[v24-32-24]]

^<<v24-32-24,24>>^ Eis aqui os valados; já vieram contra a cidade para tomá-la, e a cidade está entregue na mão dos caldeus, que pelejam contra ela, pela espada, pela fome e pela pestilência; e o que disseste se cumpriu, e eis aqui o estás presenciando.

[[v24-32-25]]

^<<v24-32-25,25>>^ Contudo tu me disseste, ó Senhor DEUS: Compra para ti o campo por dinheiro, e faze que o confirmem testemunhas, embora a cidade já esteja entregue na mão dos caldeus.

[[v24-32-26]]

^<<v24-32-26,26>>^ Então veio a palavra do Senhor a Jeremias, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ Eis que eu sou o Senhor, o Deus de toda a carne; acaso haveria alguma coisa demasiado difícil para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto assim diz o SENHOR: Eis que eu entrego esta cidade na mão dos caldeus, e na mão de Nabucodonosor, rei de babilônia, e ele a tomará.

[[v24-32-29]]

^<<v24-32-29,29>>^ E os caldeus, que pelejam contra esta cidade, entrarão nela, e pôr-lhe-ão fogo, e queimarão, as casas sobre cujos terraços queimaram incenso a Baal e ofereceram libações a outros deuses, para me provocarem à ira.

[[v24-32-30]]

^<<v24-32-30,30>>^ Porque os filhos de Israel e os filhos de Judá não fizeram senão mal aos meus olhos, desde a sua mocidade; porque os filhos de Israel nada fizeram senão provocar-me à ira com as obras das suas mãos, diz o Senhor.

[[v24-32-31]]

^<<v24-32-31,31>>^ Porque para a minha ira e para o meu furor me tem sido esta cidade, desde o dia em que a edificaram, e até ao dia de hoje, para que a tirasse da minha presença;

[[v24-32-32]]

^<<v24-32-32,32>>^ Por causa de toda a maldade dos filhos de Israel, e dos filhos de Judá, que fizeram, para me provocarem à ira, eles e os seus reis, os seus príncipes, os seus sacerdotes, e os seus profetas, como também os homens de Judá e os moradores de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ E viraram-me as costas, e não o rosto; ainda que eu os ensinava, madrugando e ensinando-os, contudo eles não deram ouvidos, para receberem o ensino.

[[v24-32-34]]

^<<v24-32-34,34>>^ Antes puseram as suas abominações na casa que se chama pelo meu nome, para a profanarem.

[[v24-32-35]]

^<<v24-32-35,35>>^ E edificaram os altos de Baal, que estão no Vale do Filho de Hinom, para fazerem passar seus filhos e suas filhas pelo fogo a Moloque; o que nunca lhes ordenei, nem veio ao meu coração, que fizessem tal abominação, para fazerem pecar a Judá.

[[v24-32-36]]

^<<v24-32-36,36>>^ E por isso agora assim diz o SENHOR, o Deus de Israel, acerca desta cidade, da qual vós dizeis: Já está dada na mão do rei de babilônia, pela espada, pela fome, e pela pestilência:

[[v24-32-37]]

^<<v24-32-37,37>>^ Eis que eu os congregarei de todas as terras, para onde os tenho lançado na minha ira, e no meu furor, e na minha grande indignação; e os tornarei a trazer a este lugar, e farei que habitem nele seguramente.

[[v24-32-38]]

^<<v24-32-38,38>>^ E eles serão o meu povo, e eu lhes serei o seu Deus;

[[v24-32-39]]

^<<v24-32-39,39>>^ E lhes darei um mesmo coração, e um só caminho, para que me temam todos os dias, para seu bem, e o bem de seus filhos, depois deles.

[[v24-32-40]]

^<<v24-32-40,40>>^ E farei com eles uma aliança eterna de não me desviar de fazer-lhes o bem; e porei o meu temor nos seus corações, para que nunca se apartem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ E alegrar-me-ei deles, fazendo-lhes bem; e plantá-los-ei nesta terra firmemente, com todo o meu coração e com toda a minha alma.

[[v24-32-42]]

^<<v24-32-42,42>>^ Porque assim diz o Senhor: Como eu trouxe sobre este povo todo este grande mal, assim eu trarei sobre ele todo o bem que lhes tenho declarado.

[[v24-32-43]]

^<<v24-32-43,43>>^ E comprar-se-ão campos nesta terra, da qual vós dizeis: Está desolada, sem homens, sem animais; está entregue na mão dos caldeus.

[[v24-32-44]]

^<<v24-32-44,44>>^ Comprarão campos por dinheiro, e assinarão as escrituras, e as selarão, e farão que confirmem testemunhas, na terra de Benjamim, e nos contornos de Jerusalém, e nas cidades de Judá, e nas cidades das montanhas, e nas cidades das planícies, e nas cidades do sul; porque os farei voltar do seu cativeiro, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]