include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-52-1]]

^<<v24-52-1,1>>^ Era Zedequias da idade de vinte e um anos quando começou a reinar, e reinou onze anos em Jerusalém; e o nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ E fez o que era mau aos olhos do Senhor, conforme tudo o que fizera Jeoiaquim.

[[v24-52-3]]

^<<v24-52-3,3>>^ Assim, por causa da ira do SENHOR, contra Jerusalém e Judá, ele os lançou de diante dele, e Zedequias se rebelou contra o rei de babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ E aconteceu, que no ano nono do seu reinado, no décimo mês, no décimo dia do mês, veio Nabucodonosor, rei de babilônia, contra Jerusalém, ele e todo o seu exército, e se acamparam contra ela, e levantaram contra ela trincheiras ao redor.

[[v24-52-5]]

^<<v24-52-5,5>>^ Assim esteve cercada a cidade, até ao undécimo ano do rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ No quarto mês, aos nove dias do mês, quando já a fome prevalecia na cidade, e o povo da terra não tinha pão,

[[v24-52-7]]

^<<v24-52-7,7>>^ Então foi aberta uma brecha na cidade, e todos os homens de guerra fugiram, e saíram da cidade de noite, pelo caminho da porta entre os dois muros, a qual estava perto do jardim do rei (porque os caldeus cercavam a cidade ao redor), e foram pelo caminho da campina.

[[v24-52-8]]

^<<v24-52-8,8>>^ Mas o exército dos caldeus perseguiu o rei, e alcançou a Zedequias nas campinas de Jericó, e todo o seu exército se espalhou, abandonando-o.

[[v24-52-9]]

^<<v24-52-9,9>>^ E prenderam o rei, e o fizeram subir ao rei de babilônia, a Ribla, na terra de Hamate, o qual lhe pronunciou a sentença.

[[v24-52-10]]

^<<v24-52-10,10>>^ E o rei de babilônia degolou os filhos de Zedequias à sua vista, e também degolou a todos os príncipes de Judá em Ribla.

[[v24-52-11]]

^<<v24-52-11,11>>^ E cegou os olhos a Zedequias, e o atou com cadeias; e o rei de babilônia o levou para babilônia, e o conservou na prisão até o dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ E no quinto mês, no décimo dia do mês, que era o décimo nono ano do rei Nabucodonosor, rei de babilônia, Nebuzaradã, capitão da guarda, que assistia na presença do rei de babilônia, veio a Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ E queimou a casa do Senhor, e a casa do rei; e também a todas as casas de Jerusalém, e a todas as casas dos grandes ele as incendiou.

[[v24-52-14]]

^<<v24-52-14,14>>^ E todo o exército dos caldeus, que estava com o capitão da guarda, derrubou a todos os muros em redor de Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ E dos mais pobres do povo, e a parte do povo, que tinha ficado na cidade, e os rebeldes que se haviam passado para o rei de babilônia, e o mais da multidão, Nebuzaradã, capitão da guarda, levou presos.

[[v24-52-16]]

^<<v24-52-16,16>>^ Mas dos mais pobres da terra Nebuzaradã, capitão da guarda, deixou ficar alguns, para serem vinhateiros e lavradores.

[[v24-52-17]]

^<<v24-52-17,17>>^ Quebraram mais os caldeus as colunas de bronze, que estavam na casa do SENHOR, e as bases, e o mar de bronze, que estavam na casa do SENHOR, e levaram todo o bronze para babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Também tomaram os caldeirões, e as pás, e as espevitadeiras, e as bacias, e as colheres, e todos os utensílios de bronze, com que se ministrava.

[[v24-52-19]]

^<<v24-52-19,19>>^ E tomou o capitão da guarda as bacias, e os braseiros, e as tigelas, e os caldeirões, e os castiçais, e as colheres, e os copos; tanto o que era de puro ouro, como o que era de prata maciça.

[[v24-52-20]]

^<<v24-52-20,20>>^ Quanto às duas colunas, ao único mar, e aos doze bois de bronze, que estavam debaixo das bases, que fizera o rei Salomão para a casa do Senhor, o peso do bronze de todos estes utensílios era incalculável.

[[v24-52-21]]

^<<v24-52-21,21>>^ Quanto às colunas, a altura de cada uma era de dezoito côvados, e um fio de doze côvados a cercava; e era a sua espessura de quatro dedos, e era oca.

[[v24-52-22]]

^<<v24-52-22,22>>^ E havia sobre ela um capitel de bronze; e a altura do capitel era de cinco côvados; a rede e as romãs ao redor do capitel eram de bronze; e semelhante a esta era a segunda coluna, com as romãs.

[[v24-52-23]]

^<<v24-52-23,23>>^ E havia noventa e seis romãs em cada lado; as romãs todas, em redor da rede, eram cem.

[[v24-52-24]]

^<<v24-52-24,24>>^ Levou também o capitão da guarda a Seraías, o sacerdote chefe, e a Sofonias, o segundo sacerdote, e aos três guardas da porta.

[[v24-52-25]]

^<<v24-52-25,25>>^ E da cidade tomou a um eunuco que tinha a seu cargo os homens de guerra, e a sete homens que estavam próximos à pessoa do rei, que se achavam na cidade, como também o escrivão-mor do exército, que alistava o povo da terra para a guerra, e a sessenta homens do povo da terra, que se achavam no meio da cidade.

[[v24-52-26]]

^<<v24-52-26,26>>^ Tomando-os, pois, Nebuzaradã, capitão da guarda, levou-os ao rei de babilônia, a Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ E o rei de babilônia os feriu e os matou em Ribla, na terra de Hamate; assim Judá foi levado cativo para fora da sua terra.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o povo que Nabucodonosor levou cativo, no sétimo ano: três mil e vinte e três judeus.

[[v24-52-29]]

^<<v24-52-29,29>>^ No ano décimo oitavo de Nabucodonosor, ele levou cativas de Jerusalém oitocentas e trinta e duas pessoas.

[[v24-52-30]]

^<<v24-52-30,30>>^ No ano vinte e três de Nabucodonosor, Nebuzaradã, capitão da guarda, levou cativas, dos judeus, setecentas e quarenta e cinco pessoas; todas as pessoas foram quatro mil e seiscentas.

[[v24-52-31]]

^<<v24-52-31,31>>^ Sucedeu, pois, no ano trigésimo sétimo do cativeiro de Jeoiaquim, rei de Judá, no duodécimo mês, aos vinte e cinco dias do mês, que Evil-Merodaque, rei de babilônia, no primeiro ano do seu reinado, levantou a cabeça de Jeoiaquim, rei de Judá, e tirou-o do cárcere;

[[v24-52-32]]

^<<v24-52-32,32>>^ E falou com ele benignamente, e pôs o seu trono acima dos tronos dos reis que estavam com ele em babilônia;

[[v24-52-33]]

^<<v24-52-33,33>>^ E lhe fez mudar as vestes da sua prisão; e passou a comer pão sempre na presença do rei, todos os dias da sua vida.

[[v24-52-34]]

^<<v24-52-34,34>>^ E, quanto à sua alimentação, foi-lhe dada refeição contínua do rei de babilônia, porção cotidiana, no seu dia, até o dia da sua morte, todos os dias da sua vida.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]