include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-51-1]]

^<<v24-51-1,1>>^ Assim diz o SENHOR: Eis que levantarei um vento destruidor contra babilônia, e contra os que habitam no meio dos que se levantam contra mim.

[[v24-51-2]]

^<<v24-51-2,2>>^ E enviarei padejadores contra babilônia, que a padejarão, e despejarão a sua terra; porque virão contra ela em redor no dia da calamidade.

[[v24-51-3]]

^<<v24-51-3,3>>^ O flecheiro arme o seu arco contra o que arma o seu arco, e contra o que se exalta na sua couraça; e não perdoeis aos seus jovens; destruí a todo o seu exército.

[[v24-51-4]]

^<<v24-51-4,4>>^ E os mortos cairão na terra dos caldeus, e atravessados nas suas ruas.

[[v24-51-5]]

^<<v24-51-5,5>>^ Porque Israel e Judá não foram abandonados do seu Deus, do Senhor dos Exércitos, ainda que a sua terra esteja cheia de culpas contra o Santo de Israel.

[[v24-51-6]]

^<<v24-51-6,6>>^ Fugi do meio de babilônia, e livrai cada um a sua alma, e não vos destruais na sua maldade; porque este é o tempo da vingança do SENHOR; que lhe dará a sua recompensa.

[[v24-51-7]]

^<<v24-51-7,7>>^ babilônia era um copo de ouro na mão do SENHOR, o qual embriagava a toda a terra; do seu vinho beberam as nações; por isso as nações enlouqueceram.

[[v24-51-8]]

^<<v24-51-8,8>>^ Num momento caiu babilônia, e ficou arruinada; lamentai por ela, tomai bálsamo para a sua dor, porventura sarará.

[[v24-51-9]]

^<<v24-51-9,9>>^ Queríamos curar babilônia, porém ela não sarou; deixai-a, e vamo-nos cada um para a sua terra; porque o seu juízo chegou até ao céu, e se elevou até às mais altas nuvens.

[[v24-51-10]]

^<<v24-51-10,10>>^ O Senhor trouxe a nossa justiça à luz; vinde e contemos em Sião a obra do Senhor, nosso Deus.

[[v24-51-11]]

^<<v24-51-11,11>>^ Aguçai as flechas, preparai os escudos; o SENHOR despertou o espírito dos reis da Média; porque o seu intento é contra babilônia para a destruir; porque esta é a vingança do SENHOR, a vingança do seu templo.

[[v24-51-12]]

^<<v24-51-12,12>>^ Arvorai um estandarte sobre os muros de babilônia, reforçai a guarda, colocai sentinelas, preparai as ciladas; porque como o SENHOR intentou, assim fez o que tinha falado contra os moradores de babilônia.

[[v24-51-13]]

^<<v24-51-13,13>>^ Ó tu, que habitas sobre muitas águas, rica de tesouros, é chegado o teu fim, a medida da tua avareza.

[[v24-51-14]]

^<<v24-51-14,14>>^ Jurou o Senhor dos Exércitos por si mesmo, dizendo: Ainda que te enchi de homens, como de lagarta, contudo levantarão gritaria contra ti.

[[v24-51-15]]

^<<v24-51-15,15>>^ Ele fez a terra com o seu poder, e ordenou o mundo com a sua sabedoria, e estendeu os céus com o seu entendimento.

[[v24-51-16]]

^<<v24-51-16,16>>^ Fazendo ele ouvir a sua voz, grande estrondo de águas há nos céus, e faz subir os vapores desde o fim da terra; faz os relâmpagos com a chuva, e tira o vento dos seus tesouros,

[[v24-51-17]]

^<<v24-51-17,17>>^ Embrutecido é todo o homem, no seu conhecimento; envergonha-se todo o artífice da imagem de escultura; porque a sua imagem de fundição é mentira, e nelas não há espírito.

[[v24-51-18]]

^<<v24-51-18,18>>^ Vaidade são, obra de enganos; no tempo da sua visitação perecerão.

[[v24-51-19]]

^<<v24-51-19,19>>^ Não é semelhante a estes a porção de Jacó; porque ele é o que formou tudo; e Israel é a tribo da sua herança; o Senhor dos Exércitos é o seu nome.

[[v24-51-20]]

^<<v24-51-20,20>>^ Tu és meu machado de batalha e minhas armas de guerra, e por meio de ti despedaçarei as nações e por ti destruirei os reis;

[[v24-51-21]]

^<<v24-51-21,21>>^ E por meio de ti despedaçarei o cavalo e o seu cavaleiro; e por meio de ti despedaçarei o carro e o que nele vai;

[[v24-51-22]]

^<<v24-51-22,22>>^ E por meio de ti despedaçarei o homem e a mulher, e por meio de ti despedaçarei o velho e o moço, e por meio de ti despedaçarei o jovem e a virgem;

[[v24-51-23]]

^<<v24-51-23,23>>^ E por meio de ti despedaçarei o pastor e o seu rebanho, e por meio de ti despedaçarei o lavrador e a sua junta de bois, e por meio de ti despedaçarei os capitães e os magistrados.

[[v24-51-24]]

^<<v24-51-24,24>>^ E pagarei a babilônia, e a todos os moradores da Caldéia, toda a maldade que fizeram em Sião, aos vossos olhos, diz o SENHOR.

[[v24-51-25]]

^<<v24-51-25,25>>^ Eis-me aqui contra ti, ó monte destruidor, diz o Senhor, que destróis toda a terra; e estenderei a minha mão contra ti, e te revolverei das rochas, e farei de ti um monte de queima.

[[v24-51-26]]

^<<v24-51-26,26>>^ E não tomarão de ti pedra para esquina, nem pedra para fundamentos, porque te tornarás em assolação perpétua, diz o Senhor.

[[v24-51-27]]

^<<v24-51-27,27>>^ Arvorai um estandarte na terra, tocai a buzina entre as nações, preparai as nações contra ela, convocai contra ela os reinos de Ararate, Mini, e Asquenaz; ordenai contra ela um capitão, fazei subir cavalos, como lagartas eriçadas.

[[v24-51-28]]

^<<v24-51-28,28>>^ Preparai contra ela as nações, os reis da Média, os seus capitães, e todos os seus magistrados, e toda a terra do seu domínio.

[[v24-51-29]]

^<<v24-51-29,29>>^ Então tremerá a terra, e doer-se-á, porque cada um dos desígnios do SENHOR está firme contra babilônia, para fazer da terra de babilônia uma desolação, sem habitantes.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os poderosos de babilônia cessaram de pelejar, ficaram nas fortalezas, desfaleceu a sua força, tornaram-se como mulheres; incendiaram as suas moradas, quebrados foram os seus ferrolhos.

[[v24-51-31]]

^<<v24-51-31,31>>^ Um correio correrá ao encontro de outro correio, e um mensageiro ao encontro de outro mensageiro, para anunciar ao rei de babilônia que a sua cidade está tomada de todos os lados.

[[v24-51-32]]

^<<v24-51-32,32>>^ E os vaus estão ocupados, e os canaviais queimados a fogo; e os homens de guerra ficaram assombrados.

[[v24-51-33]]

^<<v24-51-33,33>>^ Porque assim diz o SENHOR dos Exércitos, o Deus de Israel: A filha de babilônia é como uma eira, no tempo da debulha; ainda um pouco, e o tempo da sega lhe virá.

[[v24-51-34]]

^<<v24-51-34,34>>^ Nabucodonosor, rei de babilônia, devorou-me, colocou-me de lado, fez de mim um vaso vazio, como chacal me tragou, encheu o seu ventre das minhas delicadezas; lançou-me fora.

[[v24-51-35]]

^<<v24-51-35,35>>^ A violência que se fez a mim e à minha carne venha sobre babilônia, dirá a moradora de Sião; e o meu sangue caia sobre os moradores da Caldéia, dirá Jerusalém.

[[v24-51-36]]

^<<v24-51-36,36>>^ Portanto, assim diz o Senhor: Eis que pleitearei a tua causa, e tomarei vingança por ti; e secarei o seu mar, e farei que se esgote o seu manancial.

[[v24-51-37]]

^<<v24-51-37,37>>^ E babilônia se tornará em montões, morada de chacais, espanto e assobio, sem que haja quem nela habite.

[[v24-51-38]]

^<<v24-51-38,38>>^ Juntamente rugirão como filhos dos leões; bramarão como filhotes de leões.

[[v24-51-39]]

^<<v24-51-39,39>>^ Estando eles excitados, lhes darei a sua bebida, e os embriagarei, para que andem saltando; porém dormirão um perpétuo sono, e não acordarão, diz o Senhor.

[[v24-51-40]]

^<<v24-51-40,40>>^ Fá-los-ei descer como cordeiros à matança, como carneiros e bodes.

[[v24-51-41]]

^<<v24-51-41,41>>^ Como foi tomada Sesaque, e apanhada de surpresa a glória de toda a terra! Como se tornou babilônia objeto de espanto entre as nações!

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar subiu sobre babilônia; com a multidão das suas ondas se cobriu.

[[v24-51-43]]

^<<v24-51-43,43>>^ Tornaram-se as suas cidades em desolação, terra seca e deserta, terra em que ninguém habita, nem passa por ela filho de homem.

[[v24-51-44]]

^<<v24-51-44,44>>^ E castigarei a Bel em babilônia, e tirarei da sua boca o que tragou, e nunca mais concorrerão a ele as nações; também o muro de babilônia caiu.

[[v24-51-45]]

^<<v24-51-45,45>>^ Saí do meio dela, ó povo meu, e livrai cada um a sua alma do ardor da ira do Senhor.

[[v24-51-46]]

^<<v24-51-46,46>>^ E para que porventura não se enterneça o vosso coração, e não temais pelo rumor que se ouvir na terra; porque virá num ano um rumor, e depois noutro ano outro rumor; e haverá violência na terra, dominador contra dominador.

[[v24-51-47]]

^<<v24-51-47,47>>^ Portanto, eis que vêm dias, em que farei juízo sobre as imagens de escultura de babilônia, e toda a sua terra será envergonhada, e todos os seus mortos cairão no meio dela.

[[v24-51-48]]

^<<v24-51-48,48>>^ E os céus e a terra, com tudo quanto neles há, jubilarão sobre babilônia; porque do norte lhe virão os destruidores, diz o SENHOR.

[[v24-51-49]]

^<<v24-51-49,49>>^ Como babilônia fez cair mortos os de Israel, assim em babilônia cairão os mortos de toda a terra.

[[v24-51-50]]

^<<v24-51-50,50>>^ Vós, que escapastes da espada, ide-vos, não pareis; de longe lembrai-vos do Senhor, e suba Jerusalém a vossa mente.

[[v24-51-51]]

^<<v24-51-51,51>>^ Direis: Envergonhados estamos, porque ouvimos opróbrio; vergonha cobriu o nosso rosto, porquanto vieram estrangeiros contra os santuários da casa do Senhor.

[[v24-51-52]]

^<<v24-51-52,52>>^ Portanto, eis que vêm dias, diz o Senhor, em que farei juízo sobre as suas imagens de escultura; e gemerão os feridos em toda a sua terra.

[[v24-51-53]]

^<<v24-51-53,53>>^ Ainda que babilônia subisse aos céus, e ainda que fortificasse a altura da sua fortaleza, todavia de mim virão destruidores sobre ela, diz o SENHOR.

[[v24-51-54]]

^<<v24-51-54,54>>^ De babilônia se ouve clamor de grande destruição da terra dos caldeus;

[[v24-51-55]]

^<<v24-51-55,55>>^ Porque o SENHOR tem destruído babilônia, e tem feito perecer nela a sua grande voz; quando as suas ondas bramam como muitas águas, é emitido o ruído da sua voz.

[[v24-51-56]]

^<<v24-51-56,56>>^ Porque o destruidor vem sobre ela, sobre babilônia, e os seus poderosos serão presos, já estão quebrados os seus arcos; porque o SENHOR, Deus das recompensas, certamente lhe retribuirá.

[[v24-51-57]]

^<<v24-51-57,57>>^ E embriagarei os seus príncipes, e os seus sábios e os seus capitães, e os seus magistrados, e os seus poderosos; e dormirão um sono eterno, e não acordarão, diz o Rei, cujo nome é o Senhor dos Exércitos.

[[v24-51-58]]

^<<v24-51-58,58>>^ Assim diz o SENHOR dos Exércitos: Os largos muros de babilônia serão totalmente derrubados, e as suas altas portas serão abrasadas pelo fogo; e trabalharão os povos em vão, e as nações no fogo, e eles se cansarão.

[[v24-51-59]]

^<<v24-51-59,59>>^ A palavra que Jeremias, o profeta, mandou a Seraías, filho de Nerias, filho de Maaséias, indo ele com Zedequias, rei de Judá, a babilônia, no quarto ano do seu reinado. E Seraías era o camareiro-mor.

[[v24-51-60]]

^<<v24-51-60,60>>^ Escreveu, pois, Jeremias num livro todo o mal que havia de vir sobre babilônia, a saber, todas estas palavras que estavam escritas contra babilônia.

[[v24-51-61]]

^<<v24-51-61,61>>^ E disse Jeremias a Seraías: Quando chegares a babilônia, verás e lerás todas estas palavras.

[[v24-51-62]]

^<<v24-51-62,62>>^ E dirás: Senhor, tu falaste contra este lugar, que o havias de desarraigar, até não ficar nele morador algum, nem homem nem animal, e que se tornaria em perpétua desolação.

[[v24-51-63]]

^<<v24-51-63,63>>^ E será que, acabando tu de ler este livro, atar-lhe-ás uma pedra e lançá-lo-ás no meio do Eufrates.

[[v24-51-64]]

^<<v24-51-64,64>>^ E dirás: Assim será afundada babilônia, e não se levantará, por causa do mal que eu hei de trazer sobre ela; e eles se cansarão. Até aqui são as palavras de Jeremias.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]