include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-48-1]]

^<<v24-48-1,1>>^ Contra Moabe, assim diz o SENHOR dos Exércitos, Deus de Israel: Ai de Nebo, porque foi destruída; envergonhada está Quiriataim, já está tomada; Misgabe está envergonhada e desanimada.

[[v24-48-2]]

^<<v24-48-2,2>>^ A glória de Moabe já não existe mais; em Hesbom tramaram mal contra ela, dizendo: Vinde, e exterminemo-la, para que não seja mais nação; também tu, ó Madmém, serás silenciada; a espada te perseguirá.

[[v24-48-3]]

^<<v24-48-3,3>>^ Voz de clamor de Horonaim; ruína e grande destruição!

[[v24-48-4]]

^<<v24-48-4,4>>^ Está destruída Moabe; seus filhinhos fizeram ouvir um clamor.

[[v24-48-5]]

^<<v24-48-5,5>>^ Porque pela subida de Luíte eles irão com choro contínuo; porque na descida de Horonaim os adversários de Moabe ouviram as angústias do grito da destruição.

[[v24-48-6]]

^<<v24-48-6,6>>^ Fugi, salvai a vossa vida; sede como a tamargueira no deserto;

[[v24-48-7]]

^<<v24-48-7,7>>^ Porque, por causa da tua confiança nas tuas obras, e nos teus tesouros, também tu serás tomada; e Quemós sairá para o cativeiro, os seus sacerdotes e os seus príncipes juntamente.

[[v24-48-8]]

^<<v24-48-8,8>>^ Porque virá o destruidor sobre cada uma das cidades, e nenhuma cidade escapará, e perecerá o vale, e destruir-se-á a campina; porque o Senhor o disse.

[[v24-48-9]]

^<<v24-48-9,9>>^ Dai asas a Moabe; porque voando sairá, e as suas cidades se tornarão em desolação, e ninguém morará nelas.

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que fizer a obra do Senhor fraudulosamente; e maldito aquele que retém a sua espada do sangue.

[[v24-48-11]]

^<<v24-48-11,11>>^ Moabe esteve descansado desde a sua mocidade, e repousou nas suas borras, e não foi mudado de vasilha para vasilha, nem foi para o cativeiro; por isso conservou o seu sabor, e o seu cheiro não se alterou.

[[v24-48-12]]

^<<v24-48-12,12>>^ Portanto, eis que dias vêm, diz o Senhor, em que lhe enviarei derramadores que o derramarão; e despejarão as suas vasilhas, e romperão os seus odres.

[[v24-48-13]]

^<<v24-48-13,13>>^ E Moabe terá vergonha de Quemós como a casa de Israel se envergonhou de Betel, sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ Como direis: Somos valentes e homens fortes para a guerra?

[[v24-48-15]]

^<<v24-48-15,15>>^ Moabe está destruído, e subiu das suas cidades, e os seus jovens escolhidos desceram à matança, diz o Rei, cujo nome é o Senhor dos Exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ Está prestes a vir a calamidade de Moabe; e apressa-se muito a sua aflição.

[[v24-48-17]]

^<<v24-48-17,17>>^ Condoei-vos dele todos os que estais ao seu redor, e todos os que sabeis o seu nome; dizei: Como se quebrou a vara forte, o cajado formoso?

[[v24-48-18]]

^<<v24-48-18,18>>^ Desce da tua glória, e assenta-te em terra seca, ó moradora, filha de Dibom; porque o destruidor de Moabe subiu contra ti, e desfez as tuas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Põe-te no caminho, e espia, ó moradora de Aroer; pergunta ao que vai fugindo; e à que escapou dize: Que sucedeu?

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe está envergonhado, porque foi quebrantado; lamentai e gritai; anunciai em Arnom que Moabe está destruído.

[[v24-48-21]]

^<<v24-48-21,21>>^ Também o julgamento veio sobre a terra da campina; sobre Holom, sobre Jaza, sobre Mefaate,

[[v24-48-22]]

^<<v24-48-22,22>>^ Sobre Dibom, sobre Nebo, sobre Bete-Diblataim,

[[v24-48-23]]

^<<v24-48-23,23>>^ Sobre Quiriataim, sobre Bete-Gamul, sobre Bete-Meom,

[[v24-48-24]]

^<<v24-48-24,24>>^ Sobre Queriote, e sobre Bozra; e até sobre todas as cidades da terra de Moabe, as de longe e as de perto.

[[v24-48-25]]

^<<v24-48-25,25>>^ Já é cortado o poder de Moabe, e é quebrantado o seu braço, diz o Senhor.

[[v24-48-26]]

^<<v24-48-26,26>>^ Embriagai-o, porque contra o Senhor se engrandeceu; e Moabe se revolverá no seu vômito, e ele também se tornará objeto de escárnio.

[[v24-48-27]]

^<<v24-48-27,27>>^ Pois não foi também Israel objeto de escárnio? Porventura foi achado entre ladrões, para que sempre que fales dele, saltes de alegria?

[[v24-48-28]]

^<<v24-48-28,28>>^ Deixai as cidades, e habitai no rochedo, ó moradores de Moabe; e sede como a pomba que se aninha nos lados da boca da caverna.

[[v24-48-29]]

^<<v24-48-29,29>>^ Ouvimos da soberba de Moabe, que é soberbíssimo, como também da sua arrogância, e da sua vaidade, e da sua altivez e do seu orgulhoso coração.

[[v24-48-30]]

^<<v24-48-30,30>>^ Eu conheço, diz o Senhor, a sua indignação, mas isso nada é; as suas mentiras nada farão.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso gemerei por Moabe, sim, gritarei por todo o Moabe; pelos homens de Quir-Heres lamentarei;

[[v24-48-32]]

^<<v24-48-32,32>>^ Com o choro de Jazer chorar-te-ei, ó vide de Sibma; os teus ramos passaram o mar, chegaram até ao mar de Jazer; porém o destruidor caiu sobre os teus frutos do verão, e sobre a tua vindima.

[[v24-48-33]]

^<<v24-48-33,33>>^ Tirou-se, pois, o folguedo e a alegria do campo fértil e da terra de Moabe; porque fiz cessar o vinho nos lagares; já não pisarão uvas com júbilo; o júbilo não será júbilo.

[[v24-48-34]]

^<<v24-48-34,34>>^ Por causa do grito de Hesbom até Eleale e até Jaaz, se ouviu a sua voz desde Zoar até Horonaim, como bezerra de três anos; porque até as águas do Ninrim se tornarão em assolação.

[[v24-48-35]]

^<<v24-48-35,35>>^ E farei cessar em Moabe, diz o Senhor, quem sacrifique nos altos, e queime incenso aos seus deuses.

[[v24-48-36]]

^<<v24-48-36,36>>^ Por isso ressoará como flauta o meu coração por Moabe, também ressoará como flauta o meu coração pelos homens de Quir-Heres; porquanto a abundância que ajuntou se perdeu.

[[v24-48-37]]

^<<v24-48-37,37>>^ Porque toda a cabeça será tosquiada, e toda a barba será diminuída; sobre todas as mãos haverá sarjaduras, e sobre os lombos, sacos.

[[v24-48-38]]

^<<v24-48-38,38>>^ Sobre todos os telhados de Moabe e nas suas ruas haverá um pranto geral; porque quebrei a Moabe, como a um vaso que não agrada, diz o Senhor.

[[v24-48-39]]

^<<v24-48-39,39>>^ Como está quebrantado! Como gritam! Como virou Moabe a cerviz envergonhado! Assim será Moabe objeto de escárnio e de desmaio, para todos que estão em redor dele.

[[v24-48-40]]

^<<v24-48-40,40>>^ Porque assim diz o Senhor: Eis que voará como a águia, e estenderá as suas asas sobre Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ São tomadas as cidades, e ocupadas as fortalezas; e naquele dia será o coração dos valentes de Moabe como o coração da mulher que está com dores de parto.

[[v24-48-42]]

^<<v24-48-42,42>>^ E Moabe será destruído, para que não seja povo; porque se engrandeceu contra o Senhor.

[[v24-48-43]]

^<<v24-48-43,43>>^ Temor, e cova, e laço, vêm sobre ti, ó morador de Moabe, diz o Senhor.

[[v24-48-44]]

^<<v24-48-44,44>>^ O que fugir do temor cairá na cova, e o que subir da cova ficará preso no laço; porque trarei sobre ele, sobre Moabe, o ano do seu castigo, diz o Senhor.

[[v24-48-45]]

^<<v24-48-45,45>>^ Os que fugiam sem força pararam à sombra de Hesbom; pois saiu fogo de Hesbom, e a labareda do meio de Siom, e devorou o canto de Moabe e o alto da cabeça dos turbulentos.

[[v24-48-46]]

^<<v24-48-46,46>>^ Ai de ti, Moabe! Pereceu o povo de Quemós; porque teus filhos ficaram cativos, e tuas filhas em cativeiro.

[[v24-48-47]]

^<<v24-48-47,47>>^ Mas nos últimos dias farei voltar os cativos de Moabe, diz o Senhor. Até aqui o juízo de Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]