include::./index.adoc[]

[[v24-28-0]]
=== Jeremias, 28
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-28-1]]

^<<v24-28-1,1>>^ E sucedeu no mesmo ano, no princípio do reinado de Zedequias, rei de Judá, no ano quarto, no mês quinto, que Hananias, filho de Azur, o profeta que era de Gibeom, me falou na casa do SENHOR, na presença dos sacerdotes e de todo o povo, dizendo:

[[v24-28-2]]

^<<v24-28-2,2>>^ Assim fala o SENHOR dos Exércitos, o Deus de Israel, dizendo: Eu quebrei o jugo do rei de babilônia.

[[v24-28-3]]

^<<v24-28-3,3>>^ Depois de passados dois anos completos, eu tornarei a trazer a este lugar todos os utensílios da casa do SENHOR, que deste lugar tomou Nabucodonosor, rei de babilônia, levando-os a babilônia.

[[v24-28-4]]

^<<v24-28-4,4>>^ Também a Jeconias, filho de Jeoiaquim, rei de Judá, e a todos os do cativeiro de Judá, que entraram em babilônia, eu tornarei a trazer a este lugar, diz o SENHOR; porque quebrarei o jugo do rei de babilônia.

[[v24-28-5]]

^<<v24-28-5,5>>^ Então falou o profeta Jeremias ao profeta Hananias, na presença dos sacerdotes, e na presença de todo o povo que estava na casa do Senhor.

[[v24-28-6]]

^<<v24-28-6,6>>^ Disse, pois, Jeremias, o profeta: Amém! Assim faça o SENHOR; confirme o SENHOR as tuas palavras, que profetizaste, e torne ele a trazer os utensílios da casa do SENHOR, e todos os do cativeiro de babilônia a este lugar.

[[v24-28-7]]

^<<v24-28-7,7>>^ Mas ouve agora esta palavra, que eu falo aos teus ouvidos e aos ouvidos de todo o povo:

[[v24-28-8]]

^<<v24-28-8,8>>^ Os profetas que houve antes de mim e antes de ti, desde a antiguidade, profetizaram contra muitas terras, e contra grandes reinos, acerca de guerra, e de mal, e de peste.

[[v24-28-9]]

^<<v24-28-9,9>>^ O profeta que profetizar de paz, quando se cumprir a palavra desse profeta, será conhecido como aquele a quem o Senhor na verdade enviou.

[[v24-28-10]]

^<<v24-28-10,10>>^ Então Hananias, o profeta, tomou o jugo do pescoço do profeta Jeremias, e o quebrou.

[[v24-28-11]]

^<<v24-28-11,11>>^ E falou Hananias na presença de todo o povo, dizendo: Assim diz o SENHOR: Assim, passados dois anos completos, quebrarei o jugo de Nabucodonosor, rei de babilônia, de sobre o pescoço de todas as nações. E Jeremias, o profeta, seguiu o seu caminho.

[[v24-28-12]]

^<<v24-28-12,12>>^ Mas veio a palavra do Senhor a Jeremias, depois que Hananias, o profeta, quebrou o jugo de sobre o pescoço de Jeremias, o profeta, dizendo:

[[v24-28-13]]

^<<v24-28-13,13>>^ Vai, e fala a Hananias, dizendo: Assim diz o Senhor: Jugos de madeira quebraste, mas em vez deles farás jugos de ferro.

[[v24-28-14]]

^<<v24-28-14,14>>^ Porque assim diz o SENHOR dos Exércitos, o Deus de Israel: Jugo de ferro pus sobre o pescoço de todas estas nações, para servirem a Nabucodonosor, rei de babilônia, e servi-lo-ão, e até os animais do campo lhe dei.

[[v24-28-15]]

^<<v24-28-15,15>>^ E disse o profeta Jeremias ao profeta Hananias: Ouve agora, Hananias: Não te enviou o Senhor, mas tu fizeste que este povo confiasse em mentiras.

[[v24-28-16]]

^<<v24-28-16,16>>^ Portanto, assim diz o Senhor: Eis que te lançarei de sobre a face da terra; este ano morrerás, porque falaste em rebeldia contra o Senhor.

[[v24-28-17]]

^<<v24-28-17,17>>^ E morreu Hananias, o profeta, no mesmo ano, no sétimo mês.

'''

xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[Próximo Capítulo &#62;]