include::./index.adoc[]

[[v24-47-0]]
=== Jeremias, 47
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-47-1]]

^<<v24-47-1,1>>^ A palavra do SENHOR, que veio a Jeremias, o profeta, contra os filisteus, antes que Faraó ferisse a Gaza.

[[v24-47-2]]

^<<v24-47-2,2>>^ Assim diz o Senhor: Eis que se levantam as águas do norte, e tornar-se-ão em torrente transbordante, e alagarão a terra e sua plenitude, a cidade, e os que nela habitam; e os homens clamarão, e todos os moradores da terra se lamentarão;

[[v24-47-3]]

^<<v24-47-3,3>>^ Ao ruído estrepitoso dos cascos dos seus fortes cavalos, ao barulho de seus carros, ao estrondo das suas rodas; os pais não atendem aos filhos, por causa da fraqueza das mãos;

[[v24-47-4]]

^<<v24-47-4,4>>^ Por causa do dia que vem, para destruir a todos os filisteus, para cortar de Tiro e de Sidom todo o restante que os socorra; porque o Senhor destruirá os filisteus, o remanescente da ilha de Caftor.

[[v24-47-5]]

^<<v24-47-5,5>>^ A calvície veio sobre Gaza, foi desarraigada Ascalom, com o restante do seu vale; até quando te retalharás?

[[v24-47-6]]

^<<v24-47-6,6>>^ Ah; espada do Senhor! Até quando deixarás de repousar? Volta para a tua bainha, descansa, e aquieta-te.

[[v24-47-7]]

^<<v24-47-7,7>>^ Mas como te aquietarás? Pois o Senhor deu ordem à espada contra Ascalom, e contra a praia do mar, para onde ele a enviou.

'''

xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[&#60; Capítulo Anterior] | <<v24-47-0,Topo>> | xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[Próximo Capítulo &#62;]