include::./index.adoc[]

[[v24-39-0]]
=== Jeremias, 39
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-39-1]]

^<<v24-39-1,1>>^ No ano nono de Zedequias, rei de Judá, no décimo mês, veio Nabucodonosor, rei de babilônia, e todo o seu exército, contra Jerusalém, e a cercaram.

[[v24-39-2]]

^<<v24-39-2,2>>^ No ano undécimo de Zedequias, no quarto mês, aos nove do mês, fez-se uma brecha na cidade.

[[v24-39-3]]

^<<v24-39-3,3>>^ Entraram nela todos os príncipes do rei de babilônia, e pararam na porta do meio, a saber: Nergal-Sarezer, Sangar-Nebo, Sarsequim, Rabe-Saris, Nergal-Sarezer, Rabe-Mague, e todos os outros príncipes do rei de babilônia.

[[v24-39-4]]

^<<v24-39-4,4>>^ E sucedeu que, vendo-os Zedequias, rei de Judá, e todos os homens de guerra, fugiram, saindo de noite da cidade, pelo caminho do jardim do rei, pela porta que está entre os dois muros; e seguiram pelo caminho da campina.

[[v24-39-5]]

^<<v24-39-5,5>>^ Mas o exército dos caldeus os perseguiu, e alcançou a Zedequias nas campinas de Jericó; e eles o prenderam, e fizeram-no subir a Nabucodonosor, rei de babilônia, a Ribla, na terra de Hamate, e o rei o sentenciou.

[[v24-39-6]]

^<<v24-39-6,6>>^ E o rei de babilônia matou em Ribla os filhos de Zedequias, diante dos seus olhos; também matou o rei de babilônia a todos os nobres de Judá.

[[v24-39-7]]

^<<v24-39-7,7>>^ E cegou os olhos de Zedequias, e o atou com duas cadeias de bronze, para levá-lo a babilônia.

[[v24-39-8]]

^<<v24-39-8,8>>^ E os caldeus incendiaram a casa do rei e as casas do povo, e derrubaram os muros de Jerusalém.

[[v24-39-9]]

^<<v24-39-9,9>>^ E o restante do povo, que ficou na cidade, e os desertores que se tinham passado para ele, e o restante do povo que ficou, Nebuzaradã, capitão da guarda, levou cativo para a babilônia.

[[v24-39-10]]

^<<v24-39-10,10>>^ Porém os pobres dentre o povo, que não tinham nada, Nebuzaradã, capitão da guarda, deixou na terra de Judá; e deu-lhes vinhas e campos naquele dia.

[[v24-39-11]]

^<<v24-39-11,11>>^ Mas Nabucodonosor, rei de babilônia, havia ordenado acerca de Jeremias, a Nebuzaradã, capitão da guarda, dizendo:

[[v24-39-12]]

^<<v24-39-12,12>>^ Toma-o, e põe sobre ele os teus olhos, e não lhe faças nenhum mal; antes como ele te disser, assim procederás com ele.

[[v24-39-13]]

^<<v24-39-13,13>>^ Por isso mandou Nebuzaradã, capitão da guarda, e Nebusazbã, Rabe-Saris, Nergal-Sarezer, Rabe-Mague, e todos os príncipes do rei de babilônia,

[[v24-39-14]]

^<<v24-39-14,14>>^ Mandaram retirar a Jeremias do átrio da guarda, e o entregaram a Gedalias, filho de Aicão, filho de Safã, para que o levassem à casa; e ele habitou entre o povo.

[[v24-39-15]]

^<<v24-39-15,15>>^ Ora, tinha vindo a Jeremias a palavra do Senhor, estando ele ainda encarcerado no átrio da guarda, dizendo:

[[v24-39-16]]

^<<v24-39-16,16>>^ Vai, e fala a Ebede-Meleque, o etíope, dizendo: Assim diz o Senhor dos Exércitos, Deus de Israel: Eis que eu trarei as minhas palavras sobre esta cidade para mal e não para bem; e cumprir-se-ão diante de ti naquele dia.

[[v24-39-17]]

^<<v24-39-17,17>>^ A ti, porém, eu livrarei naquele dia, diz o Senhor, e não serás entregue na mão dos homens, a quem temes.

[[v24-39-18]]

^<<v24-39-18,18>>^ Porque certamente te livrarei, e não cairás à espada; mas a tua alma terás por despojo, porquanto confiaste em mim, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[Próximo Capítulo &#62;]