include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-36-1]]

^<<v24-36-1,1>>^ Sucedeu, pois, no ano quarto de Jeoiaquim, filho de Josias, rei de Judá, que veio esta palavra do SENHOR a Jeremias, dizendo:

[[v24-36-2]]

^<<v24-36-2,2>>^ Toma o rolo de um livro, e escreve nele todas as palavras que te tenho falado de Israel, e de Judá, e de todas as nações, desde o dia em que eu te falei, desde os dias de Josias até ao dia de hoje.

[[v24-36-3]]

^<<v24-36-3,3>>^ Porventura ouvirão os da casa de Judá todo o mal que eu intento fazer-lhes; para que cada qual se converta do seu mau caminho, e eu perdoe a sua maldade e o seu pecado.

[[v24-36-4]]

^<<v24-36-4,4>>^ Então Jeremias chamou a Baruque, filho de Nerias; e escreveu Baruque da boca de Jeremias no rolo de um livro todas as palavras do Senhor, que ele lhe tinha falado.

[[v24-36-5]]

^<<v24-36-5,5>>^ E Jeremias deu ordem a Baruque, dizendo: Eu estou encarcerado; não posso entrar na casa do Senhor.

[[v24-36-6]]

^<<v24-36-6,6>>^ Entra, pois, tu, e pelo rolo que escreveste da minha boca, lê as palavras do Senhor aos ouvidos do povo, na casa do Senhor, no dia de jejum; e também, aos ouvidos de todos os de Judá, que vêm das suas cidades, as lerás.

[[v24-36-7]]

^<<v24-36-7,7>>^ Pode ser que caia a sua súplica diante do Senhor, e se converta cada um do seu mau caminho; porque grande é a ira e o furor que o Senhor tem expressado contra este povo.

[[v24-36-8]]

^<<v24-36-8,8>>^ E fez Baruque, filho de Nerias, conforme tudo quanto lhe havia ordenado Jeremias, o profeta, lendo naquele livro as palavras do Senhor, na casa do Senhor.

[[v24-36-9]]

^<<v24-36-9,9>>^ E aconteceu, no quinto ano de Jeoiaquim, filho de Josias, rei de Judá, no mês nono, que apregoaram jejum diante do Senhor a todo o povo em Jerusalém, como também a todo o povo que vinha das cidades de Judá a Jerusalém.

[[v24-36-10]]

^<<v24-36-10,10>>^ Leu, pois, Baruque naquele livro as palavras de Jeremias, na casa do Senhor, na câmara de Gemarias, filho de Safã, o escriba, no átrio superior, à entrada da porta nova da casa do Senhor, aos ouvidos de todo o povo.

[[v24-36-11]]

^<<v24-36-11,11>>^ E, ouvindo Micaías, filho de Gemarias, filho de Safã, todas as palavras do Senhor, daquele livro,

[[v24-36-12]]

^<<v24-36-12,12>>^ Desceu à casa do rei, à câmara do escriba. E eis que todos os príncipes estavam ali assentados, a saber: Elisama, o escriba, e Delaías, filho de Semaías, e Elnatã, filho de Acbor, e Gemarias, filho de Safã, e Zedequias, filho de Hananias, e todos os outros príncipes.

[[v24-36-13]]

^<<v24-36-13,13>>^ E Micaías anunciou-lhes todas as palavras que ouvira, quando Baruque leu o livro, aos ouvidos do povo.

[[v24-36-14]]

^<<v24-36-14,14>>^ Então todos os príncipes mandaram Jeudi, filho de Netanias, filho de Selemias, filho de Cusi, a Baruque, para lhe dizer: O rolo que leste aos ouvidos do povo, toma-o na tua mão, e vem. E Baruque, filho de Nerias, tomou o rolo na sua mão, e foi ter com eles.

[[v24-36-15]]

^<<v24-36-15,15>>^ E disseram-lhe: Assenta-te agora, e lê-o aos nossos ouvidos. E leu Baruque aos ouvidos deles.

[[v24-36-16]]

^<<v24-36-16,16>>^ E sucedeu que, ouvindo eles todas aquelas palavras, voltaram-se temerosos uns para os outros, e disseram a Baruque: Sem dúvida alguma anunciaremos ao rei todas estas palavras.

[[v24-36-17]]

^<<v24-36-17,17>>^ E perguntaram a Baruque, dizendo: Declara-nos agora como escreveste da sua boca todas estas palavras.

[[v24-36-18]]

^<<v24-36-18,18>>^ E disse-lhes Baruque: Da sua boca ele me ditava todas estas palavras, e eu com tinta as escrevia no livro.

[[v24-36-19]]

^<<v24-36-19,19>>^ Então disseram os príncipes a Baruque: Vai, esconde-te, tu e Jeremias, e ninguém saiba onde estais.

[[v24-36-20]]

^<<v24-36-20,20>>^ E foram ter com o rei ao átrio: mas depositaram o rolo na câmara de Elisama, o escriba, e anunciaram aos ouvidos do rei todas aquelas palavras.

[[v24-36-21]]

^<<v24-36-21,21>>^ Então enviou o rei a Jeudi, para que tomasse o rolo; e Jeudi tomou-o da câmara de Elisama, o escriba, e leu-o aos ouvidos do rei e aos ouvidos de todos os príncipes que estavam em torno do rei.

[[v24-36-22]]

^<<v24-36-22,22>>^ Ora, o rei estava assentado na casa de inverno, pelo nono mês; e diante dele estava um braseiro aceso.

[[v24-36-23]]

^<<v24-36-23,23>>^ E sucedeu que, tendo Jeudi lido três ou quatro folhas, cortou-as com um canivete de escrivão, e lançou-as no fogo que havia no braseiro, até que todo o rolo se consumiu no fogo que estava sobre o braseiro.

[[v24-36-24]]

^<<v24-36-24,24>>^ E não temeram, nem rasgaram as suas vestes, nem o rei, nem nenhum dos seus servos que ouviram todas aquelas palavras.

[[v24-36-25]]

^<<v24-36-25,25>>^ E, posto que Elnatã, e Delaías, e Gemarias tivessem rogado ao rei que não queimasse o rolo, ele não lhes deu ouvidos.

[[v24-36-26]]

^<<v24-36-26,26>>^ Antes deu ordem o rei a Jerameel, filho de Hamaleque, e a Seraías, filho de Azriel, e a Selemias, filho de Abdeel, que prendessem a Baruque, o escrivão, e a Jeremias, o profeta; mas o Senhor os escondera.

[[v24-36-27]]

^<<v24-36-27,27>>^ Então veio a Jeremias a palavra do Senhor, depois que o rei queimara o rolo, com as palavras que Baruque escrevera da boca de Jeremias, dizendo:

[[v24-36-28]]

^<<v24-36-28,28>>^ Toma ainda outro rolo, e escreve nele todas aquelas palavras que estavam no primeiro rolo, que queimou Jeoiaquim, rei de Judá.

[[v24-36-29]]

^<<v24-36-29,29>>^ E a Jeoiaquim, rei de Judá, dirás: Assim diz o SENHOR: Tu queimaste este rolo, dizendo: Por que escreveste nele, dizendo: Certamente virá o rei de babilônia, e destruirá esta terra e fará cessar nela homens e animais?

[[v24-36-30]]

^<<v24-36-30,30>>^ Portanto assim diz o Senhor, acerca de Jeoiaquim, rei de Judá: Não terá quem se assente sobre o trono de Davi, e será lançado o seu cadáver ao calor do dia, e à geada da noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ E castigarei a sua iniqüidade nele, e na sua descendência, e nos seus servos; e trarei sobre ele e sobre os moradores de Jerusalém, e sobre os homens de Judá, todo aquele mal que lhes tenho falado, e não ouviram.

[[v24-36-32]]

^<<v24-36-32,32>>^ Tomou, pois, Jeremias outro rolo, e deu-o a Baruque, filho de Nerias, o escrivão, o qual escreveu nele, da boca de Jeremias, todas as palavras do livro que Jeoiaquim, rei de Judá, tinha queimado no fogo; e ainda se lhes acrescentaram muitas palavras semelhantes.

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]