include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-2-1]]

^<<v24-2-1,1>>^ E veio a mim a palavra do SENHOR, dizendo:

[[v24-2-2]]

^<<v24-2-2,2>>^ Vai, e clama aos ouvidos de Jerusalém, dizendo: Assim diz o Senhor: Lembro-me de ti, da piedade da tua mocidade, e do amor do teu noivado, quando me seguias no deserto, numa terra que não se semeava.

[[v24-2-3]]

^<<v24-2-3,3>>^ Então Israel era santidade para o Senhor, e as primícias da sua novidade; todos os que o devoravam eram tidos por culpados; o mal vinha sobre eles, diz o Senhor.

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouvi a palavra do Senhor, ó casa de Jacó, e todas as famílias da casa de Israel;

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz o Senhor: Que injustiça acharam vossos pais em mim, para se afastarem de mim, indo após a vaidade, e tornando-se levianos?

[[v24-2-6]]

^<<v24-2-6,6>>^ E não disseram: Onde está o Senhor, que nos fez subir da terra do Egito, que nos guiou através do deserto, por uma terra árida, e de covas, por uma terra de sequidão e sombra de morte, por uma terra pela qual ninguém transitava, e na qual não morava homem algum?

[[v24-2-7]]

^<<v24-2-7,7>>^ E eu vos introduzi numa terra fértil, para comerdes o seu fruto e o seu bem; mas quando nela entrastes contaminastes a minha terra, e da minha herança fizestes uma abominação.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não disseram: Onde está o Senhor? E os que tratavam da lei não me conheciam, e os pastores prevaricavam contra mim, e os profetas profetizavam por Baal, e andaram após o que é de nenhum proveito.

[[v24-2-9]]

^<<v24-2-9,9>>^ Portanto ainda contenderei convosco, diz o Senhor; e até com os filhos de vossos filhos contenderei.

[[v24-2-10]]

^<<v24-2-10,10>>^ Pois, passai às ilhas de Quitim, e vede; e enviai a Quedar, e atentai bem, e vede se jamais sucedeu coisa semelhante.

[[v24-2-11]]

^<<v24-2-11,11>>^ Houve alguma nação que trocasse os seus deuses, ainda que não fossem deuses? Todavia o meu povo trocou a sua glória por aquilo que é de nenhum proveito.

[[v24-2-12]]

^<<v24-2-12,12>>^ Espantai-vos disto, ó céus, e horrorizai-vos! Ficai verdadeiramente desolados, diz o Senhor.

[[v24-2-13]]

^<<v24-2-13,13>>^ Porque o meu povo fez duas maldades: a mim me deixaram, o manancial de águas vivas, e cavaram cisternas, cisternas rotas, que não retêm águas.

[[v24-2-14]]

^<<v24-2-14,14>>^ Acaso é Israel um servo? É ele um escravo nascido em casa? Por que, pois, veio a ser presa?

[[v24-2-15]]

^<<v24-2-15,15>>^ Os filhos de leão rugiram sobre ele, levantaram a sua voz; e fizeram da sua terra uma desolação; as suas cidades se queimaram, e ninguém habita nelas.

[[v24-2-16]]

^<<v24-2-16,16>>^ Até os filhos de Nofe e de Tafnes te quebraram o alto da cabeça.

[[v24-2-17]]

^<<v24-2-17,17>>^ Porventura não fizeste isto a ti mesmo, deixando o Senhor teu Deus, no tempo em que ele te guiava pelo caminho?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, pois, que te importa a ti o caminho do Egito, para beberes as águas de Sior? E que te importa a ti o caminho da Assíria, para beberes as águas do rio?

[[v24-2-19]]

^<<v24-2-19,19>>^ A tua malícia te castigará, e as tuas apostasias te repreenderão; sabe, pois, e vê, que mal e quão amargo é deixares ao SENHOR teu Deus, e não teres em ti o meu temor, diz o Senhor DEUS dos Exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ Quando eu já há muito quebrava o teu jugo, e rompia as tuas ataduras, dizias tu: Nunca mais transgredirei; contudo em todo o outeiro alto e debaixo de toda a árvore verde te andas encurvando e prostituindo-te.

[[v24-2-21]]

^<<v24-2-21,21>>^ Eu mesmo te plantei como vide excelente, uma semente inteiramente fiel; como, pois, te tornaste para mim uma planta degenerada como vide estranha?

[[v24-2-22]]

^<<v24-2-22,22>>^ Por isso, ainda que te laves com salitre, e amontoes sabão, a tua iniqüidade está gravada diante de mim, diz o Senhor DEUS.

[[v24-2-23]]

^<<v24-2-23,23>>^ Como dizes logo: Não estou contaminada nem andei após os baalins? Vê o teu caminho no vale, conhece o que fizeste; dromedária ligeira és, que anda torcendo os seus caminhos.

[[v24-2-24]]

^<<v24-2-24,24>>^ Jumenta montês, acostumada ao deserto, que, conforme o desejo da sua alma, sorve o vento, quem a deteria no seu cio? Todos os que a buscarem não se cansarão; no mês dela a acharão.

[[v24-2-25]]

^<<v24-2-25,25>>^ Evita que o teu pé ande descalço, e a tua garganta tenha sede. Mas tu dizes: Não há esperança; porque amo os estranhos, após eles andarei.

[[v24-2-26]]

^<<v24-2-26,26>>^ Como fica confundido o ladrão quando o apanham, assim se confundem os da casa de Israel; eles, os seus reis, os seus príncipes, e os seus sacerdotes, e os seus profetas,

[[v24-2-27]]

^<<v24-2-27,27>>^ Que dizem ao pau: Tu és meu pai; e à pedra: Tu me geraste; porque me viraram as costas, e não o rosto; mas no tempo da sua angústia dirão: Levanta-te, e livra-nos.

[[v24-2-28]]

^<<v24-2-28,28>>^ Onde, pois, estão os teus deuses, que fizeste para ti? Que se levantem, se te podem livrar no tempo da tua angústia; porque os teus deuses, ó Judá, são tão numerosos como as tuas cidades.

[[v24-2-29]]

^<<v24-2-29,29>>^ Por que contendeis comigo? Todos vós transgredistes contra mim, diz o Senhor.

[[v24-2-30]]

^<<v24-2-30,30>>^ Em vão castiguei os vossos filhos; eles não aceitaram a correção; a vossa espada devorou os vossos profetas como um leão destruidor.

[[v24-2-31]]

^<<v24-2-31,31>>^ Oh geração! Considerai vós a palavra do Senhor: Porventura tenho eu sido para Israel um deserto? Ou uma terra da mais espessa escuridão? Por que, pois, diz o meu povo: Temos determinado; não viremos mais a ti?

[[v24-2-32]]

^<<v24-2-32,32>>^ Porventura esquece-se a virgem dos seus enfeites, ou a noiva dos seus adornos? Todavia o meu povo se esqueceu de mim por inumeráveis dias.

[[v24-2-33]]

^<<v24-2-33,33>>^ Por que ornamentas o teu caminho, para buscares o amor? Pois até às malignas ensinaste os teus caminhos.

[[v24-2-34]]

^<<v24-2-34,34>>^ Até nas orlas dos teus vestidos se achou o sangue das almas dos inocentes e necessitados; não cavei para achar, pois se vê em todas estas coisas.

[[v24-2-35]]

^<<v24-2-35,35>>^ E ainda dizes: Eu estou inocente; certamente a sua ira se desviou de mim. Eis que entrarei em juízo contigo, porquanto dizes: Não pequei.

[[v24-2-36]]

^<<v24-2-36,36>>^ Por que te desvias tanto, mudando o teu caminho? Também do Egito serás envergonhada, como foste envergonhada da Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Também daquele sairás com as mãos sobre a tua cabeça; porque o Senhor rejeitou a tua confiança, e não prosperarás com eles.

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]