include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-11-1]]

^<<v24-11-1,1>>^ A palavra que veio a Jeremias, da parte do SENHOR, dizendo:

[[v24-11-2]]

^<<v24-11-2,2>>^ Ouvi as palavras desta aliança, e falai aos homens de Judá, e aos habitantes de Jerusalém.

[[v24-11-3]]

^<<v24-11-3,3>>^ Dize-lhes pois: Assim diz o Senhor Deus de Israel: Maldito o homem que não escutar as palavras desta aliança,

[[v24-11-4]]

^<<v24-11-4,4>>^ Que ordenei a vossos pais no dia em que os tirei da terra do Egito, da fornalha de ferro, dizendo: Dai ouvidos à minha voz, e fazei conforme a tudo quanto vos mando; e vós sereis o meu povo, e eu serei o vosso Deus.

[[v24-11-5]]

^<<v24-11-5,5>>^ Para que confirme o juramento que fiz a vossos pais de dar-lhes uma terra que manasse leite e mel, como se vê neste dia. Então eu respondi, e disse: Amém, ó Senhor.

[[v24-11-6]]

^<<v24-11-6,6>>^ E disse-me o Senhor: Apregoa todas estas palavras nas cidades de Judá, e nas ruas de Jerusalém, dizendo: Ouvi as palavras desta aliança, e cumpri-as.

[[v24-11-7]]

^<<v24-11-7,7>>^ Porque deveras adverti a vossos pais, no dia em que os tirei da terra do Egito, até ao dia de hoje, madrugando, e protestando, e dizendo: Dai ouvidos à minha voz.

[[v24-11-8]]

^<<v24-11-8,8>>^ Mas não ouviram, nem inclinaram os seus ouvidos, antes andaram cada um conforme o propósito do seu coração malvado; por isso trouxe sobre eles todas as palavras desta aliança que lhes mandei que cumprissem, porém não cumpriram.

[[v24-11-9]]

^<<v24-11-9,9>>^ Disse-me mais o Senhor: Uma conspiração se achou entre os homens de Judá, entre os habitantes de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Tornaram às maldades de seus primeiros pais, que não quiseram ouvir as minhas palavras; e eles andaram após outros deuses para os servir; a casa de Israel e a casa de Judá quebraram a minha aliança, que tinha feito com seus pais.

[[v24-11-11]]

^<<v24-11-11,11>>^ Portanto assim diz o Senhor: Eis que trarei mal sobre eles, de que não poderão escapar; e clamarão a mim, mas eu não os ouvirei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então irão as cidades de Judá e os habitantes de Jerusalém e clamarão aos deuses a quem eles queimaram incenso; estes, porém, de nenhum modo os livrarão no tempo do seu mal.

[[v24-11-13]]

^<<v24-11-13,13>>^ Porque, segundo o número das tuas cidades, são os teus deuses, ó Judá! E, segundo o número das ruas de Jerusalém, levantastes altares à impudência, altares para queimardes incenso a Baal.

[[v24-11-14]]

^<<v24-11-14,14>>^ Tu, pois, não ores por este povo, nem levantes por ele clamor nem oração; porque não os ouvirei no tempo em que eles clamarem a mim, por causa do seu mal.

[[v24-11-15]]

^<<v24-11-15,15>>^ Que direito tem a minha amada na minha casa, visto que com muitos tem cometido grande lascívia? Crês que os sacrifícios e as carnes santificadas poderão afastar de ti o mal? Então saltarias de prazer.

[[v24-11-16]]

^<<v24-11-16,16>>^ Denominou-te o Senhor oliveira verde, formosa por seus deliciosos frutos, mas agora à voz de um grande tumulto acendeu fogo ao redor dela e se quebraram os seus ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ Porque o Senhor dos Exércitos, que te plantou, pronunciou contra ti o mal, pela maldade da casa de Israel e da casa de Judá, que para si mesma fizeram, pois me provocaram à ira, queimando incenso a Baal.

[[v24-11-18]]

^<<v24-11-18,18>>^ E o Senhor me fez saber, e assim o soube; então me fizeste ver as suas ações.

[[v24-11-19]]

^<<v24-11-19,19>>^ E eu era como um cordeiro, como um boi que levam à matança; porque não sabia que maquinavam propósitos contra mim, dizendo: Destruamos a árvore com o seu fruto, e cortemo-lo da terra dos viventes, e não haja mais memória do seu nome.

[[v24-11-20]]

^<<v24-11-20,20>>^ Mas, ó Senhor dos Exércitos, justo Juiz, que provas os rins e o coração, veja eu a tua vingança sobre eles; pois a ti descobri a minha causa.

[[v24-11-21]]

^<<v24-11-21,21>>^ Portanto, assim diz o Senhor acerca dos homens de Anatote, que buscam a tua vida, dizendo: Não profetizes no nome do Senhor, para que não morras às nossas mãos.

[[v24-11-22]]

^<<v24-11-22,22>>^ Portanto, assim diz o Senhor dos Exércitos: Eis que eu os castigarei; os jovens morrerão à espada, os seus filhos e suas filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ E não haverá deles um remanescente, porque farei vir o mal sobre os homens de Anatote, no ano da sua visitação.

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]