include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-12-1]]

^<<v24-12-1,1>>^ Justo serias, ó SENHOR, ainda que eu entrasse contigo num pleito; contudo falarei contigo dos teus juízos. Por que prospera o caminho dos ímpios, e vivem em paz todos os que procedem aleivosamente?

[[v24-12-2]]

^<<v24-12-2,2>>^ Plantaste-os, e eles se arraigaram; crescem, dão também fruto; chegado estás à sua boca, porém longe dos seus rins.

[[v24-12-3]]

^<<v24-12-3,3>>^ Mas tu, ó Senhor, me conheces, tu me vês, e provas o meu coração para contigo; arranca-os como as ovelhas para o matadouro, e dedica-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando lamentará a terra, e se secará a erva de todo o campo? Pela maldade dos que habitam nela, perecem os animais e as aves; porquanto dizem: Ele não verá o nosso fim.

[[v24-12-5]]

^<<v24-12-5,5>>^ Se te fatigas correndo com homens que vão a pé, como poderás competir com os cavalos? Se tão-somente numa terra de paz estás confiado, como farás na enchente do Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Porque até os teus irmãos, e a casa de teu pai, eles próprios procedem deslealmente contigo; eles mesmos clamam após ti em altas vozes: Não te fies neles, ainda que te digam coisas boas.

[[v24-12-7]]

^<<v24-12-7,7>>^ Desamparei a minha casa, abandonei a minha herança; entreguei a amada da minha alma na mão de seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ Tornou-se a minha herança para mim como leão numa floresta; levantou a sua voz contra mim, por isso eu a odiei.

[[v24-12-9]]

^<<v24-12-9,9>>^ A minha herança é para mim ave de rapina de várias cores. Andam as aves de rapina contra ela em redor. Vinde, pois, ajuntai todos os animais do campo, trazei-os para a devorarem.

[[v24-12-10]]

^<<v24-12-10,10>>^ Muitos pastores destruíram a minha vinha, pisaram o meu campo; tornaram em desolado deserto o meu campo desejado.

[[v24-12-11]]

^<<v24-12-11,11>>^ Em desolação a puseram, e clama a mim na sua desolação; e toda a terra está desolada, porquanto não há ninguém que tome isso a sério.

[[v24-12-12]]

^<<v24-12-12,12>>^ Sobre todos os lugares altos do deserto vieram destruidores; porque a espada do Senhor devora desde um extremo da terra até o outro; não há paz para nenhuma carne.

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo, e segaram espinhos; cansaram-se, mas de nada se aproveitaram; envergonhados sereis das vossas colheitas, e por causa do ardor da ira do Senhor.

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o Senhor, acerca de todos os meus maus vizinhos, que tocam a minha herança, que fiz herdar ao meu povo Israel: Eis que os arrancarei da sua terra, e a casa de Judá arrancarei do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ E será que, depois de os haver arrancado, tornarei, e me compadecerei deles, e os farei voltar cada um à sua herança, e cada um à sua terra.

[[v24-12-16]]

^<<v24-12-16,16>>^ E será que, se diligentemente aprenderem os caminhos do meu povo, jurando pelo meu nome: Vive o Senhor, como ensinaram o meu povo a jurar por Baal; então edificar-se-ão no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas se não quiserem ouvir, totalmente arrancarei a tal nação, e a farei perecer, diz o Senhor.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]