include::./index.adoc[]

[[v24-43-0]]
=== Jeremias, 43
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-43-1]]

^<<v24-43-1,1>>^ E sucedeu que, acabando Jeremias de falar a todo o povo todas as palavras do SENHOR seu Deus, com as quais o SENHOR seu Deus lho havia enviado, para que lhes dissesse todas estas palavras,

[[v24-43-2]]

^<<v24-43-2,2>>^ Então falaram Azarias, filho de Hosaías, e Joanã, filho de Careá, e todos os homens soberbos, dizendo a Jeremias: Tu dizes mentiras; o Senhor nosso Deus não te enviou a dizer: Não entreis no Egito, para ali habitar;

[[v24-43-3]]

^<<v24-43-3,3>>^ Mas Baruque, filho de Nerias, te incita contra nós, para entregar-nos na mão dos caldeus, para nos matarem, ou para nos levarem cativos para babilônia.

[[v24-43-4]]

^<<v24-43-4,4>>^ Não obedeceu, pois, Joanã, filho de Careá, nem nenhum de todos os capitães dos exércitos, nem o povo todo, à voz do Senhor, para ficarem na terra de Judá.

[[v24-43-5]]

^<<v24-43-5,5>>^ Antes tomou Joanã, filho de Careá, e todos os capitães dos exércitos a todo o restante de Judá, que havia voltado dentre todas as nações, para onde haviam sido lançados, para morarem na terra de Judá;

[[v24-43-6]]

^<<v24-43-6,6>>^ Aos homens, e às mulheres, e aos meninos, e às filhas do rei, e a toda a alma que Nebuzaradã, capitão da guarda, deixara com Gedalias, filho de Aicão, filho de Safã; como também a Jeremias, o profeta, e a Baruque, filho de Nerias;

[[v24-43-7]]

^<<v24-43-7,7>>^ E entraram na terra do Egito, porque não obedeceram à voz do Senhor; e vieram até Tafnes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Então veio a palavra do Senhor a Jeremias, em Tafnes, dizendo:

[[v24-43-9]]

^<<v24-43-9,9>>^ Toma na tua mão pedras grandes, e esconde-as no barro, no forno que está à entrada da casa de Faraó, em Tafnes, perante os olhos dos homens de Judá,

[[v24-43-10]]

^<<v24-43-10,10>>^ E dize-lhes: Assim diz o SENHOR dos Exércitos, Deus de Israel: Eis que eu enviarei, e tomarei a Nabucodonosor, rei de babilônia, meu servo, e porei o seu trono sobre estas pedras que escondi; e ele estenderá a sua tenda real sobre elas.

[[v24-43-11]]

^<<v24-43-11,11>>^ E virá, e ferirá a terra do Egito; entregando para a morte, quem é para a morte; e quem é para o cativeiro, para o cativeiro; e quem é para a espada, para a espada.

[[v24-43-12]]

^<<v24-43-12,12>>^ E lançarei fogo às casas dos deuses do Egito, e queimá-los-á, e levá-los-á cativos; e vestir-se-á da terra do Egito, como veste o pastor a sua roupa, e sairá dali em paz.

[[v24-43-13]]

^<<v24-43-13,13>>^ E quebrará as estátuas de Bete-Semes, que está na terra do Egito; e as casas dos deuses do Egito queimará a fogo.

'''

xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[Próximo Capítulo &#62;]