include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-9-1]]

^<<v24-9-1,1>>^ Oh! se a minha cabeça se tornasse em águas, e os meus olhos numa fonte de lágrimas! Então choraria de dia e de noite os mortos da filha do meu povo.

[[v24-9-2]]

^<<v24-9-2,2>>^ Oh! se tivesse no deserto uma estalagem de caminhantes! Então deixaria o meu povo, e me apartaria dele, porque todos eles são adúlteros, um bando de aleivosos.

[[v24-9-3]]

^<<v24-9-3,3>>^ E encurvam a língua como se fosse o seu arco, para a mentira; fortalecem-se na terra, mas não para a verdade; porque avançam de malícia em malícia, e a mim não me conhecem, diz o Senhor.

[[v24-9-4]]

^<<v24-9-4,4>>^ Guardai-vos cada um do seu próximo, e de irmão nenhum vos fieis; porque todo o irmão não faz mais do que enganar, e todo o próximo anda caluniando.

[[v24-9-5]]

^<<v24-9-5,5>>^ E zombará cada um do seu próximo, e não falam a verdade; ensinam a sua língua a falar a mentira, andam-se cansando em proceder perversamente.

[[v24-9-6]]

^<<v24-9-6,6>>^ A tua habitação está no meio do engano; pelo engano recusam conhecer-me, diz o Senhor.

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto assim diz o Senhor dos Exércitos: Eis que eu os fundirei e os provarei; pois, de que outra maneira procederia com a filha do meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ Uma flecha mortífera é a língua deles; fala engano; com a sua boca fala cada um de paz com o seu próximo mas no seu coração arma-lhe ciladas.

[[v24-9-9]]

^<<v24-9-9,9>>^ Porventura por estas coisas não os castigaria? diz o Senhor; ou não se vingaria a minha alma de nação tal como esta?

[[v24-9-10]]

^<<v24-9-10,10>>^ Pelos montes levantarei choro e pranto, e pelas pastagens do deserto lamentação; porque já estão queimadas, e ninguém passa por elas; nem se ouve mugido de gado; desde as aves dos céus, até os animais, andaram vagueando, e fugiram.

[[v24-9-11]]

^<<v24-9-11,11>>^ E farei de Jerusalém montões de pedras, morada de chacais, e das cidades de Judá farei assolação, de sorte que não haja habitante.

[[v24-9-12]]

^<<v24-9-12,12>>^ Quem é o homem sábio, que entenda isto? e a quem falou a boca do Senhor, para que o possa anunciar? Por que razão pereceu a terra, e se queimou como deserto, sem que ninguém passa por ela?

[[v24-9-13]]

^<<v24-9-13,13>>^ E disse o Senhor: Porque deixaram a minha lei, que pus perante eles, e não deram ouvidos à minha voz, nem andaram nela,

[[v24-9-14]]

^<<v24-9-14,14>>^ Antes andaram após o propósito do seu próprio coração, e após os baalins, como lhes ensinaram os seus pais.

[[v24-9-15]]

^<<v24-9-15,15>>^ Portanto assim diz o Senhor dos Exércitos, Deus de Israel: Eis que darei de comer losna a este povo, e lhe darei a beber água de fel.

[[v24-9-16]]

^<<v24-9-16,16>>^ E os espalharei entre gentios, que não conheceram, nem eles nem seus pais, e mandarei a espada após eles, até que venha a consumi-los.

[[v24-9-17]]

^<<v24-9-17,17>>^ Assim diz o Senhor dos Exércitos: Considerai, e chamai carpideiras que venham; e mandai procurar mulheres hábeis, para que venham.

[[v24-9-18]]

^<<v24-9-18,18>>^ E se apressem, e levantem o seu lamento sobre nós; e desfaçam-se em lágrimas os nossos olhos, e as nossas pálpebras destilem águas.

[[v24-9-19]]

^<<v24-9-19,19>>^ Porque uma voz de pranto se ouviu de Sião: Como estamos arruinados! Estamos mui envergonhados, porque deixamos a terra, e por terem eles lançado fora as nossas moradas.

[[v24-9-20]]

^<<v24-9-20,20>>^ Ouvi, pois, vós, mulheres, a palavra do Senhor, e os vossos ouvidos recebam a palavra da sua boca; e ensinai o pranto a vossas filhas, e cada uma à sua vizinha a lamentação;

[[v24-9-21]]

^<<v24-9-21,21>>^ Porque a morte subiu pelas nossas janelas, e entrou em nossos palácios, para exterminar as crianças das ruas e os jovens das praças.

[[v24-9-22]]

^<<v24-9-22,22>>^ Fala: Assim diz o Senhor: Até os cadáveres dos homens jazerão como esterco sobre a face do campo, e como gavela atrás do segador, e não há quem a recolha.

[[v24-9-23]]

^<<v24-9-23,23>>^ Assim diz o Senhor: Não se glorie o sábio na sua sabedoria, nem se glorie o forte na sua força; não se glorie o rico nas suas riquezas,

[[v24-9-24]]

^<<v24-9-24,24>>^ Mas o que se gloriar, glorie-se nisto: em me entender e me conhecer, que eu sou o Senhor, que faço beneficência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor.

[[v24-9-25]]

^<<v24-9-25,25>>^ Eis que vêm dias, diz o Senhor, em que castigarei a todo o circuncidado com o incircunciso.

[[v24-9-26]]

^<<v24-9-26,26>>^ Ao Egito, e a Judá, e a Edom, e aos filhos de Amom, e a Moabe, e a todos os que cortam os cantos do seu cabelo, que habitam no deserto; porque todas as nações são incircuncisas, e toda a casa de Israel é incircuncisa de coração.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]