include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-20-1]]

^<<v24-20-1,1>>^ E Pasur, filho de Imer, o sacerdote, que havia sido nomeado presidente na casa do SENHOR, ouviu a Jeremias, que profetizava estas palavras.

[[v24-20-2]]

^<<v24-20-2,2>>^ E feriu Pasur ao profeta Jeremias, e o colocou no cepo que está na porta superior de Benjamim, na casa do Senhor.

[[v24-20-3]]

^<<v24-20-3,3>>^ E sucedeu que no dia seguinte Pasur tirou a Jeremias do cepo. Então disse-lhe Jeremias: O Senhor não chama o teu nome Pasur, mas, Terror por todos os lados.

[[v24-20-4]]

^<<v24-20-4,4>>^ Porque assim diz o SENHOR: Eis que farei de ti um terror para ti mesmo, e para todos os teus amigos. Eles cairão à espada de seus inimigos, e teus olhos o verão. Entregarei todo o Judá na mão do rei de babilônia; ele os levará presos a babilônia, e feri-los-á à espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Também entregarei toda a riqueza desta cidade, e todo o seu trabalho, e todas as suas coisas preciosas, sim, todos os tesouros dos reis de Judá entregarei na mão de seus inimigos, e saqueá-los-ão, e tomá-los-ão e levá-los-ão a babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E tu, Pasur, e todos os moradores da tua casa ireis para o cativeiro; e virás a babilônia, e ali morrerás, e ali serás sepultado, tu, e todos os teus amigos, aos quais profetizaste falsamente.

[[v24-20-7]]

^<<v24-20-7,7>>^ Persuadiste-me, ó Senhor, e persuadido fiquei; mais forte foste do que eu, e prevaleceste; sirvo de escárnio todo o dia; cada um deles zomba de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Porque desde que falo, grito, clamo: Violência e destruição; porque se tornou a palavra do Senhor um opróbrio e ludíbrio todo o dia.

[[v24-20-9]]

^<<v24-20-9,9>>^ Então disse eu: Não me lembrarei dele, e não falarei mais no seu nome; mas isso foi no meu coração como fogo ardente, encerrado nos meus ossos; e estou fatigado de sofrer, e não posso mais.

[[v24-20-10]]

^<<v24-20-10,10>>^ Porque ouvi a murmuração de muitos, terror de todos os lados: Denunciai, e o denunciaremos; todos os que têm paz comigo aguardam o meu manquejar, dizendo: Bem pode ser que se deixe persuadir; então prevaleceremos contra ele e nos vingaremos dele.

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas o Senhor está comigo como um valente terrível; por isso tropeçarão os meus perseguidores, e não prevalecerão; ficarão muito confundidos; porque não se houveram prudentemente, terão uma confusão perpétua que nunca será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Tu, pois, ó Senhor dos Exércitos, que provas o justo, e vês os rins e o coração, permite que eu veja a tua vingança contra eles; pois já te revelei a minha causa.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantai ao Senhor, louvai ao Senhor; pois livrou a alma do necessitado da mão dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que nasci; não seja bendito o dia em que minha mãe me deu à luz.

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem que deu as novas a meu pai, dizendo: Nasceu-te um filho; alegrando-o com isso grandemente.

[[v24-20-16]]

^<<v24-20-16,16>>^ E seja esse homem como as cidades que o Senhor destruiu e não se arrependeu; e ouça clamor pela manhã, e ao tempo do meio-dia um alarido.

[[v24-20-17]]

^<<v24-20-17,17>>^ Por que não me matou na madre? Assim minha mãe teria sido a minha sepultura, e teria ficado grávida perpetuamente!

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que saí da madre, para ver trabalho e tristeza, e para que os meus dias se consumam na vergonha?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]