include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// acf ?, ACF - Almeida Corrigida Fiel

[[v24-6-1]]

^<<v24-6-1,1>>^ Fugi para salvação vossa, filhos de Benjamim, do meio de Jerusalém; e tocai a buzina em Tecoa, e levantai um sinal de fogo sobre Bete-Haquerém; porque do lado norte surge um mal e uma grande destruição.

[[v24-6-2]]

^<<v24-6-2,2>>^ À formosa e delicada assemelhei a filha de Sião.

[[v24-6-3]]

^<<v24-6-3,3>>^ Mas contra ela virão pastores com os seus rebanhos; levantarão contra ela tendas em redor, e cada um apascentará no seu lugar.

[[v24-6-4]]

^<<v24-6-4,4>>^ Preparai a guerra contra ela, levantai-vos, e subamos ao pino do meio-dia. Ai de nós! Já declina o dia, já se vão estendendo as sombras da tarde.

[[v24-6-5]]

^<<v24-6-5,5>>^ Levantai-vos, e subamos de noite, e destruamos os seus palácios.

[[v24-6-6]]

^<<v24-6-6,6>>^ Porque assim diz o SENHOR dos Exércitos: Cortai árvores, e levantai trincheiras contra Jerusalém; esta é a cidade que há de ser castigada, só opressão há no meio dela.

[[v24-6-7]]

^<<v24-6-7,7>>^ Como a fonte produz as suas águas, assim ela produz a sua malícia; violência e estrago se ouvem nela; enfermidade e feridas há diante de mim continuamente.

[[v24-6-8]]

^<<v24-6-8,8>>^ Corrige-te, ó Jerusalém, para que a minha alma não se aparte de ti, para que não te torne em assolação e terra não habitada.

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim diz o Senhor dos Exércitos: Diligentemente respigarão os resíduos de Israel como uma vinha; torna a tua mão, como o vindimador, aos cestos.

[[v24-6-10]]

^<<v24-6-10,10>>^ A quem falarei e testemunharei, para que ouça? Eis que os seus ouvidos estão incircuncisos, e não podem ouvir; eis que a palavra do Senhor é para eles coisa vergonhosa, e não gostam dela.

[[v24-6-11]]

^<<v24-6-11,11>>^ Por isso estou cheio do furor do Senhor; estou cansado de o conter; derramá-lo-ei sobre os meninos pelas ruas e na reunião de todos os jovens; porque até o marido com a mulher serão presos, e o velho com o que está cheio de dias.

[[v24-6-12]]

^<<v24-6-12,12>>^ E as suas casas passarão a outros, como também as suas herdades e as suas mulheres juntamente; porque estenderei a minha mão contra os habitantes desta terra, diz o Senhor.

[[v24-6-13]]

^<<v24-6-13,13>>^ Porque desde o menor deles até ao maior, cada um se dá à avareza; e desde o profeta até ao sacerdote, cada um usa de falsidade.

[[v24-6-14]]

^<<v24-6-14,14>>^ E curam superficialmente a ferida da filha do meu povo, dizendo: Paz, paz; quando não há paz.

[[v24-6-15]]

^<<v24-6-15,15>>^ Porventura envergonham-se de cometer abominação? Pelo contrário, de maneira nenhuma se envergonham, nem tampouco sabem que coisa é envergonhar-se; portanto cairão entre os que caem; no tempo em que eu os visitar, tropeçarão, diz o Senhor.

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim diz o Senhor: Ponde-vos nos caminhos, e vede, e perguntai pelas veredas antigas, qual é o bom caminho, e andai por ele; e achareis descanso para as vossas almas; mas eles dizem: Não andaremos nele.

[[v24-6-17]]

^<<v24-6-17,17>>^ Também pus atalaias sobre vós, dizendo: Estai atentos ao som da trombeta; mas dizem: Não escutaremos.

[[v24-6-18]]

^<<v24-6-18,18>>^ Portanto ouvi, vós, nações; e informa-te tu, ó congregação, do que se faz entre eles!

[[v24-6-19]]

^<<v24-6-19,19>>^ Ouve tu, ó terra! Eis que eu trarei mal sobre este povo, o próprio fruto dos seus pensamentos; porque não estão atentos às minhas palavras, e rejeitam a minha lei.

[[v24-6-20]]

^<<v24-6-20,20>>^ Para que, pois, me vem o incenso de Sabá e a melhor cana aromática de terras remotas? Vossos holocaustos não me agradam, nem me são suaves os vossos sacrifícios.

[[v24-6-21]]

^<<v24-6-21,21>>^ Portanto assim diz o Senhor: Eis que armarei tropeços a este povo; e tropeçarão neles pais e filhos juntamente; o vizinho e o seu companheiro perecerão.

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim diz o Senhor: Eis que um povo vem da terra do norte, e uma grande nação se levantará das extremidades da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Arco e lança trarão; são cruéis, e não usarão de misericórdia; a sua voz rugirá como o mar, e em cavalos virão montados, dispostos como homens de guerra contra ti, ó filha de Sião.

[[v24-6-24]]

^<<v24-6-24,24>>^ Ouvimos a sua fama, afrouxaram-se as nossas mãos; angústia nos tomou, e dores como as de parturiente.

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saiais ao campo, nem andeis pelo caminho; porque espada do inimigo e espanto há ao redor.

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó filha do meu povo, cinge-te de saco, e revolve-te na cinza; pranteia como por um filho único, pranto de amargura; porque de repente virá o destruidor sobre nós.

[[v24-6-27]]

^<<v24-6-27,27>>^ Por torre de guarda te pus entre o meu povo, por fortaleza, para que soubesses e examinasses o seu caminho.

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos eles são os mais rebeldes, andam murmurando; são duros como bronze e ferro; todos eles são corruptores.

[[v24-6-29]]

^<<v24-6-29,29>>^ Já o fole se queimou, o chumbo se consumiu com o fogo; em vão fundiu o fundidor tão diligentemente, pois os maus não são arrancados.

[[v24-6-30]]

^<<v24-6-30,30>>^ Prata rejeitada lhes chamarão, porque o Senhor os rejeitou.

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]